// Operating Systems bank, part 2: bare metal versus Linux.

BANKS["Operating Systems"] = BANKS["Operating Systems"].concat([

// -------------------------------------------------------------- os-choose
{ t: "os-choose", d: 1, q: "Roughly how long does embedded Linux take to boot?", o: ["Microseconds", "Seconds", "Milliseconds", "Under a millisecond"], a: 1, why: "Two to twenty, across five boot stages. If a user presses a button and expects a response, that is a product problem rather than an engineering one." },
{ t: "os-choose", d: 1, q: "What is usually the decisive argument for Linux?", o: ["It is far easier to develop against", "Stacks you would otherwise write", "It runs faster than an RTOS does", "It is required for anything networked"], a: 1, why: "TCP/IP with TLS, a power-fail-safe filesystem, USB host, a display or camera pipeline. Months of work bare metal, a configuration choice here." },
{ t: "os-choose", d: 2, q: "Which cost most often rules Linux out on a battery product?", o: ["The GPLv2 obligations on the kernel", "Idle current: milliamps, not microamps", "The board area the DRAM needs", "The longer development schedule"], a: 1, why: "Three orders of magnitude on the quantity that sets battery life. Boot time and bill of materials hurt too, but this is usually the fatal one." },
{ t: "os-choose", d: 2, q: "What does Linux require that an RTOS does not?", o: ["A floating point unit", "An MMU", "More than one core", "External flash memory"], a: 1, why: "Without address translation there are no processes and no isolation, so a Cortex-M with only an MPU is out however much RAM you attach to it." },
{ t: "os-choose", d: 2, q: "Can PREEMPT_RT give a provable worst-case latency?", o: ["Yes, that is precisely its purpose", "No, it improves a distribution", "Only alongside SCHED_DEADLINE", "Only on a single-core system"], a: 1, why: "It gets typical latency into the tens of microseconds, which is a different claim from the bound fixed-priority scheduling on bare hardware lets you prove." },
{ t: "os-choose", d: 2, q: "Which parts does choosing Linux add to the bill of materials?", o: ["A crystal and a decoupling network", "DRAM, eMMC and a PMIC", "An external watchdog and a supervisor", "A JTAG header and level shifters"], a: 1, why: "Plus more pins, more board layers and a processor an order of magnitude dearer. The software choice reaches straight into the hardware cost." },
{ t: "os-choose", d: 3, q: "What obligation does shipping Linux create?", o: ["Publishing a minimum update period", "Open sourcing your application code", "Certifying against a safety standard", "Guaranteeing a fixed boot time"], a: 0, why: "You have attached a CVE feed to the product for its life, and the UK PSTI Act requires the support window to be published. GPLv2 touches the kernel, not your userspace." },
{ t: "os-choose", d: 3, q: "Does the kernel's GPLv2 licence affect your application?", o: ["Yes, it must be released too", "No, userspace is unaffected", "Only if it links any kernel header", "Only if it ships in the same image"], a: 1, why: "The boundary is the syscall interface, which is why proprietary software lives in userspace. Kernel modifications and in-tree drivers are the part with obligations." },
{ t: "os-choose", d: 3, q: "You need TLS networking and a 50 microsecond deadline. What do you do?", o: ["Tune Linux until it meets the deadline", "Split it across two cores", "Use an RTOS and write a TLS stack", "Raise the control thread to SCHED_FIFO"], a: 1, why: "Neither half compromises. Linux takes connectivity and an RTOS or bare metal owns the deadline, which is an AMP design rather than a fudge." },
{ t: "os-choose", d: 3, q: "Which is the strongest reason to prefer an RTOS?", o: ["Developers find it simpler to learn", "A worst case you can prove", "It produces a smaller binary image", "It avoids any licensing questions"], a: 1, why: "Determinism is the thing Linux cannot give you at any price. Size and simplicity are consequences, not the argument." },

// ----------------------------------------------------------------- os-amp
{ t: "os-amp", d: 1, q: "What distinguishes AMP from SMP?", o: ["AMP needs cores of differing speed", "Each core runs its own software", "SMP means two chips, AMP means one", "AMP requires a hypervisor to arbitrate"], a: 1, why: "Under SMP one kernel schedules a pool of identical cores. Under AMP the cores run different software, frequently on different architectures." },
{ t: "os-amp", d: 1, q: "In a typical AMP split, what does the Linux core own?", o: ["The microsecond control deadlines", "Networking, storage and the UI", "The motor PWM and current sensing", "The interrupt with the tightest latency"], a: 1, why: "It takes everything with no hard deadline and every stack you would rather not write, and the other core keeps the timing-critical work away from it." },
{ t: "os-amp", d: 2, q: "What carries the payload between the two cores?", o: ["The mailbox registers themselves", "A shared memory region", "The interrupt controller's queue", "A UART between the two cores"], a: 1, why: "The mailbox is only the doorbell. Data lives in memory both cores can see, which is what makes cache coherency the thing to get right." },
{ t: "os-amp", d: 2, q: "What is the mailbox or IPCC for?", o: ["Passing the message contents across", "Interrupting the other core to look", "Keeping both caches coherent", "Booting the second core at reset"], a: 1, why: "Polling shared memory from Linux burns power and adds latency, so a hardware interrupt tells the other side something is waiting." },
{ t: "os-amp", d: 2, q: "What does remoteproc do?", o: ["Routes rpmsg between the two cores", "Loads and starts the other core's firmware", "Maps shared memory into both", "Decides which of the two cores owns each peripheral"], a: 1, why: "It takes the firmware image out of the Linux filesystem and boots the second core with it, so the RTOS image ships and updates like any other file." },
{ t: "os-amp", d: 2, q: "What is rpmsg built on?", o: ["A dedicated serial link between cores", "Virtio rings plus a mailbox", "The kernel's own socket layer", "A shared interrupt vector table"], a: 1, why: "Shared-memory rings for the data and a mailbox for notification, presented to Linux as a character device. It is the standardised form of the hand-rolled scheme." },
{ t: "os-amp", d: 3, q: "Why is peripheral ownership a hazard in a single-SoC AMP design?", o: ["Only one core can be granted access", "Both can reach everything, unenforced", "The bus arbiter picks a core at random", "Peripherals must be assigned at reset"], a: 1, why: "Nothing stops either core touching any peripheral, so the split is a convention. When it is broken the failure is silent corruption rather than an error." },
{ t: "os-amp", d: 3, q: "Linux reboots for an update. What must the M core do?", o: ["Reset itself and rejoin cleanly", "Keep running and survive the gap", "Halt until Linux comes back", "Hand its peripherals to the bootloader"], a: 1, why: "The motor cannot stop because the application processor is updating, so the real-time half has to tolerate its peer vanishing and returning mid-conversation." },
{ t: "os-amp", d: 3, q: "Which SoCs are typical heterogeneous AMP parts?", o: ["STM32MP1 and i.MX8", "STM32F4 and SAMD21", "RP2040 and ESP32-C3", "Zynq and Artix, both FPGAs"], a: 0, why: "A Cortex-A running Linux beside a Cortex-M in one package. The alternative shape is two separate chips, which is simpler and more clearly isolated." },
{ t: "os-amp", d: 3, q: "Why is a two-chip AMP design often preferred over one SoC?", o: ["It costs less in volume", "Every boundary is visible and enforced", "It uses noticeably less board area overall", "It needs no inter-core protocol"], a: 1, why: "Separate silicon means separate memory and peripherals, so the split cannot be violated by accident. You pay in parts cost and a physical link." },

// ---------------------------------------------------------------- os-boot
{ t: "os-boot", d: 1, q: "What runs first on a Cortex-M after reset?", o: ["main, called by the C runtime", "Hardware loads MSP from vector zero", "The Reset_Handler copies .data", "The bootloader validates the image"], a: 1, why: "The core reads the first vector word into the stack pointer and the second as the reset vector, before any software runs at all. That is silicon." },
{ t: "os-boot", d: 1, q: "How many stages does a typical embedded Linux boot have?", o: ["Two", "Five", "One", "Three"], a: 1, why: "Boot ROM, SPL, U-Boot, kernel, init. Each exists purely to make the next one possible, which is the whole explanation for the apparent complexity." },
{ t: "os-boot", d: 2, q: "Why is a separate first stage needed before U-Boot?", o: ["To verify the bootloader's signature", "DRAM is not up, so it must fit SRAM", "To select between several kernels", "To decompress the kernel image"], a: 1, why: "A few tens of kilobytes is all the on-chip SRAM there is, and the SPL's job is to bring up the DDR controller so a full bootloader has somewhere to live." },
{ t: "os-boot", d: 2, q: "How does the kernel receive the device tree?", o: ["Compiled into the kernel image", "As a pointer from the bootloader", "Read from the root filesystem", "Placed in SRAM by the boot ROM"], a: 1, why: "U-Boot loads the .dtb and hands over a pointer, which is why one kernel binary boots many boards. Zephyr has no blob because it resolved everything at build time." },
{ t: "os-boot", d: 2, q: "What is PID 1?", o: ["The kernel's own idle thread", "init, usually systemd", "The first driver to probe", "The bootloader's handover stub"], a: 1, why: "The first userspace process, which starts everything else and adopts orphans. The kernel is up long before the product does anything useful." },
{ t: "os-boot", d: 2, q: "Where does embedded Linux boot time usually go?", o: ["Decompressing the kernel image", "U-Boot's delay and the init units", "The boot ROM reading its straps", "Bringing up the DDR controller"], a: 1, why: "Rarely the kernel. It is the bootloader countdown, probing devices that are not fitted, and systemd starting dozens of units in dependency order." },
{ t: "os-boot", d: 3, q: "What makes the boot ROM the root of trust?", o: ["It runs with interrupts disabled", "It is in silicon and cannot be replaced", "It holds the private signing key", "It is the smallest stage of the chain"], a: 1, why: "Mask-programmed and unchangeable, so it is the one link an attacker cannot swap. Everything above is only as trustworthy as whatever verified it." },
{ t: "os-boot", d: 3, q: "What does Reset_Handler do before calling main?", o: ["Enables the interrupt controller", "Copies .data and zeroes .bss", "Configures the PLL and the flash wait states", "Validates the application checksum"], a: 1, why: "The C runtime environment has to exist before any C runs. Constructors follow, and only then does main get called." },
{ t: "os-boot", d: 3, q: "An initramfs is used for what?", o: ["Storing the device tree blob", "A root filesystem in RAM, early", "Caching the kernel image itself", "Holding the bootloader environment"], a: 1, why: "It gives the kernel something to mount before the real root is reachable, which is how drivers or decryption needed to find that root get loaded." },
{ t: "os-boot", d: 3, q: "Secure boot verifies the kernel. What verified U-Boot?", o: ["The kernel verifies it retrospectively", "The stage before it, back to ROM", "A signature checked by init", "Nothing: U-Boot is trusted"], a: 1, why: "It is a chain: ROM verifies SPL, SPL verifies U-Boot, U-Boot verifies the kernel. Break any link and everything above it is unverified." },

// ------------------------------------------------------------- os-cchange
{ t: "os-cchange", d: 1, q: "What happens when main returns on Linux?", o: ["The startup code traps in a loop", "The process exits with that value", "Behaviour is undefined by the standard", "The runtime restarts the program"], a: 1, why: "The return value is the exit code, which is the interface to every script and CI system. Printing an error and returning zero is a real bug." },
{ t: "os-cchange", d: 1, q: "How does userspace drive a peripheral register?", o: ["By writing to its physical address", "It cannot: through a driver or /dev", "By enabling a privileged mode first", "Only when the process runs as root"], a: 1, why: "The MMU and the privilege boundary make it impossible by design. Even as root you go through a driver, or an explicit mmap of /dev/mem." },
{ t: "os-cchange", d: 2, q: "When is errno meaningful?", o: ["At any time after the call", "Just after a call has failed", "Once explicitly cleared and reread", "Only in a single-threaded program"], a: 1, why: "A successful call does not reset it, so reading it without first checking the return value gives you whatever failed earlier. It is thread-local, so threads are not the hazard." },
{ t: "os-cchange", d: 2, q: "What can a file descriptor refer to?", o: ["Only a file on a mounted filesystem, nothing else", "A file, socket, pipe, GPIO chip or timer", "Any object the kernel has allocated", "Only things opened with open()"], a: 1, why: "One integer and one set of operations across all of them, which is why epoll can watch thousands of unrelated things at once." },
{ t: "os-cchange", d: 2, q: "Why can a signal handler not call printf?", o: ["The stream may not be open yet", "Only async-signal-safe calls are allowed", "Signals run with interrupts disabled", "It would block the delivering thread"], a: 1, why: "It is an ISR by another name and can interrupt the process mid-malloc or mid-printf, so re-entering those corrupts them. Set a flag, act in the main loop." },
{ t: "os-cchange", d: 2, q: "Which type should a signal handler's flag be?", o: ["A plain int, read in the loop", "volatile sig_atomic_t", "An int protected by a mutex", "A bool declared as static"], a: 1, why: "volatile because it changes outside the visible flow, and sig_atomic_t because the write must be indivisible. Exactly the reasoning you already apply to an ISR flag." },
{ t: "os-cchange", d: 3, q: "A binary built on your desktop will not start on the target. Likeliest cause?", o: ["The target has a read-only filesystem", "glibc on the host, musl on the target", "The binary was linked statically", "The target kernel is too old for it"], a: 1, why: "Most embedded roots use musl or uClibc for size, and a glibc-linked binary will not run. ldd shows what it wants; static linking sidesteps it at a cost in size." },
{ t: "os-cchange", d: 3, q: "What changes about dynamic allocation on Linux?", o: ["It is still banned on any real-time path", "Normal, and leaks matter more than exhaustion", "It becomes faster than a static buffer", "It must be replaced by a fixed pool"], a: 1, why: "Virtual memory removes the fragmentation that makes malloc dangerous bare metal. On a real-time thread you still avoid it, for the unbounded latency." },
{ t: "os-cchange", d: 3, q: "What does a linker script no longer let you do?", o: ["Place a buffer at a fixed address", "Set the entry point of the program", "Control which sections are emitted", "Define symbols for the build"], a: 0, why: "The address space is virtual, so pinning something at 0x20000000 is meaningless. Counting bytes of RAM stops being a design activity too." },
{ t: "os-cchange", d: 3, q: "Where does a program get its configuration on Linux?", o: ["Compiled in, as on bare metal", "argv, the environment and files", "From the device tree at boot", "From a fixed flash sector"], a: 1, why: "Arguments, environment variables and config files all arrive at run time, so the same binary behaves differently without being rebuilt." }

]);
