// Operating Systems bank, part 3: embedded Linux.

BANKS["Operating Systems"] = BANKS["Operating Systems"].concat([

// ------------------------------------------------------------------ os-dt
{ t: "os-dt", d: 1, q: "When does Linux consume the device tree?", o: ["At build time, as constants", "At run time, from a blob", "At link time, into the image", "When a module is first loaded"], a: 1, why: "Everything else follows from that. It is why one kernel binary boots many boards, and why a mistake is a missing device rather than a compile error." },
{ t: "os-dt", d: 1, q: "What does dtc produce?", o: ["A header of generated macros", "A .dtb, a flattened blob", "An object file to be linked", "A patch against the kernel tree"], a: 1, why: "The bootloader loads that blob and passes the kernel a pointer to it. Zephyr's toolchain instead turns the same source into compile-time constants." },
{ t: "os-dt", d: 2, q: "How does a driver claim a device tree node?", o: ["By node label, looked up at probe", "A compatible string in its match table", "By registering against its address", "Through a kernel config symbol"], a: 1, why: "The bus code matches compatible against every driver's of_match_table and calls probe on the winner. No match means no device, silently." },
{ t: "os-dt", d: 2, q: "Which call reads an integer property at probe?", o: ["DT_PROP, from a generated header", "of_property_read_u32", "device_property_get_int", "dt_node_read_u32"], a: 1, why: "The of_ family reads from the live tree. DT_PROP is the Zephyr form and resolves during the build, which is the whole difference in one line." },
{ t: "os-dt", d: 2, q: "Your device does not appear and nothing logs an error. Look where first?", o: ["The kernel log, for a driver failure", "/proc/device-tree, for what arrived", "The .dts source you edited", "The bootloader environment"], a: 1, why: "The tree the kernel actually received is often not the one you wrote. Checking it separates a build or overlay problem from a driver problem at once." },
{ t: "os-dt", d: 2, q: "What does a .dtbo let you do?", o: ["Describe a node without a binding", "Change the description with no rebuild", "Override a driver's match table", "Compile the tree more quickly"], a: 1, why: "Merged into the live tree by U-Boot or configfs, which is how a Raspberry Pi enables SPI from config.txt. Zephyr has nothing at run time to modify." },
{ t: "os-dt", d: 2, q: "A node exists but no driver bound to it. What is wrong?", o: ["The node is missing status okay", "compatible matches no driver's table", "The reg property is out of range", "The parent bus is not enabled"], a: 1, why: "Almost always a typo in the string or a kernel config symbol that was never enabled, so the driver is simply not in the build to match against." },
{ t: "os-dt", d: 3, q: "Which Yocto variable names the device trees to build?", o: ["MACHINE_DEVICETREE", "KERNEL_DEVICETREE", "DTB_FILES", "IMAGE_DEVICETREE"], a: 1, why: "Set in the machine configuration, and it is the join between the device tree and the build system, with the .dts living in the kernel tree or a BSP layer." },
{ t: "os-dt", d: 3, q: "Why does Linux keep the tree at run time rather than compiling it in?", o: ["Parsing is faster than macro expansion", "One kernel binary can boot many boards", "It allows drivers to be loaded later", "The blob compresses better than code"], a: 1, why: "Ship the same kernel to every board and vary only the blob. Zephyr targets one board per build, so it can afford to resolve everything earlier." },
{ t: "os-dt", d: 3, q: "How do you dump the tree a running kernel is using?", o: ["cat /sys/kernel/devicetree", "dtc -I fs -O dts /proc/device-tree", "dmesg | grep devicetree", "of_dump from the kernel shell"], a: 1, why: "It reconstructs readable source from what the kernel actually holds, so you can compare it with what you believe you built and loaded." },

// -------------------------------------------------------------- os-driver
{ t: "os-driver", d: 1, q: "What calls a driver's probe function?", o: ["init, during system startup", "The kernel, on matching a device", "The driver's own module_init", "A program opening its /dev node"], a: 1, why: "The bus code pairs a device with a driver that lists it, and probe is where resources are claimed and the userspace interface registered." },
{ t: "os-driver", d: 1, q: "What does the devm_ prefix do?", o: ["Allocates from a faster memory pool", "Ties the resource to the device's life", "Makes the call safe from an interrupt", "Defers the work until after probe"], a: 1, why: "Released automatically in reverse order on a failed probe or on remove, so every error path becomes a single return with no cleanup ladder." },
{ t: "os-driver", d: 2, q: "Why is devm_ better than a goto cleanup ladder?", o: ["It produces measurably smaller code", "No path can forget to release", "It is required by the coding style", "It allows allocation while atomic"], a: 1, why: "The leak on the third failure branch that nobody ever executes is exactly the bug host tests are written to catch. Here the framework removes the possibility." },
{ t: "os-driver", d: 2, q: "What is a file_operations table?", o: ["The list of files a driver opens", "The syscalls arriving at your driver", "The driver's own internal callbacks", "A mapping of minor numbers to devices"], a: 1, why: "open, read, write, ioctl and release, reaching your code from userspace. It is the concrete meaning of a character device in /dev." },
{ t: "os-driver", d: 2, q: "What is ioctl for?", o: ["Reading a stream of bytes efficiently", "Everything that is not a byte stream", "Mapping device memory into a process", "Waiting for the device to become ready"], a: 1, why: "Set a sample rate, trigger a conversion, read a status word. read and write suit streams; ioctl is the escape hatch for everything else." },
{ t: "os-driver", d: 2, q: "What splits a kernel interrupt handler into two halves?", o: ["One runs per core, the other globally", "The bottom half is allowed to sleep", "The top half handles errors only", "The bottom half runs at higher priority"], a: 1, why: "Top half does the minimum with interrupts off; a workqueue or threaded handler does the rest where blocking is legal. Your ISR-queues, task-processes pattern with kernel names." },
{ t: "os-driver", d: 3, q: "When should you use spidev rather than write a driver?", o: ["Whenever the part sits on SPI", "When ordinary transfers suffice", "When there is no device tree node", "When the driver would be a module"], a: 1, why: "Go into the kernel for interrupt latency, precise timing, or to present the part through a subsystem like iio. Plain transfers do not need any of that." },
{ t: "os-driver", d: 3, q: "What does MODULE_DEVICE_TABLE add?", o: ["A runtime list of the devices currently bound", "Match data for automatic module loading", "The device's entry under /sys", "A reference count on the module"], a: 1, why: "It exports the match table so userspace tooling can work out which module to load for a device that has appeared, rather than everything being built in." },
{ t: "os-driver", d: 3, q: "Why must probe leave the device usable or clean up fully?", o: ["The kernel retries it three times", "A half-initialised device is worse than none", "remove will not be called after a probe failure", "The bus will bind another driver"], a: 1, why: "Returning an error means the device stays unbound, so anything acquired must be released. devm_ is what makes that automatic rather than a discipline." },
{ t: "os-driver", d: 3, q: "What does platform_set_drvdata do?", o: ["Registers the driver with the bus", "Stashes your private pointer on the device", "Publishes data to userspace via sysfs", "Sets the device's DMA mask"], a: 1, why: "So remove and the file operations can find the state probe allocated. Without it every callback would need a global, which breaks with two instances." },

// ----------------------------------------------------------- os-userspace
{ t: "os-userspace", d: 1, q: "Which is the modern interface for GPIO from userspace?", o: ["/sys/class/gpio and export", "libgpiod on /dev/gpiochipN", "Writing to /dev/mem directly", "The gpio_request kernel call"], a: 1, why: "The sysfs interface is deprecated: no line ownership, state left behind when a program dies, and no edge timestamps. Tutorials still show it." },
{ t: "os-userspace", d: 1, q: "What is sysfs well suited to?", o: ["Streaming samples at high rate", "Occasional configuration and status", "Bulk transfer of a firmware blob", "Interrupt-driven event delivery"], a: 1, why: "One value per file, readable from a shell. It is a syscall per value formatted as text, so it is fine for settings and hopeless as a data path." },
{ t: "os-userspace", d: 2, q: "What should you check before writing any driver?", o: ["Whether a binding exists for the part", "Whether a subsystem already covers it", "Whether the bus driver is enabled", "Whether the kernel version supports it"], a: 1, why: "If iio, input, hwmon or v4l2 handles that class, you inherit buffered reads, triggers and unit conversion instead of writing them yourself." },
{ t: "os-userspace", d: 2, q: "How do you set the slave address on /dev/i2c-1?", o: ["By writing it as the first byte", "With an ioctl, I2C_SLAVE", "By opening a per-address node", "Through a sysfs attribute"], a: 1, why: "Then ordinary read and write calls talk to that device. It is the fastest route from having a sensor to having a reading, with no kernel code at all." },
{ t: "os-userspace", d: 2, q: "What does the iio subsystem give you for free?", o: ["Direct register access from userspace", "Buffered reads, triggers and scaling", "A guaranteed sampling latency", "Automatic calibration of the part"], a: 1, why: "A standard interface for sensors, so other software sees a normal device. Writing it yourself means reimplementing all of it badly." },
{ t: "os-userspace", d: 2, q: "Why is /sys/class/gpio deprecated?", o: ["It is slower than the character device", "No ownership, and it leaks on a crash", "It cannot configure a pull-up", "It requires root, unlike libgpiod"], a: 1, why: "Nothing records which program holds a line, exported state survives the process that made it, and there is no way to timestamp an edge." },
{ t: "os-userspace", d: 3, q: "When is mmap of /dev/mem defensible?", o: ["When you need the lowest latency", "During bring-up, then deleted", "When the process already runs as root", "When no driver exists for the part"], a: 1, why: "It needs root, bypasses any driver that owns the peripheral, is not portable between boards, and is restricted on a hardened kernel. A tool for understanding, not shipping." },
{ t: "os-userspace", d: 3, q: "Why is /dev/mem dangerous even when it works?", o: ["It can corrupt the page tables", "Another driver may own that peripheral", "It disables the MMU for as long as it stays mapped", "It cannot be unmapped cleanly"], a: 1, why: "Two pieces of code writing the same registers with no coordination, and the kernel has no idea you are there. The failure is silent and intermittent." },
{ t: "os-userspace", d: 3, q: "Where does /proc differ from /sys?", o: ["/proc is writable and /sys is not", "/proc is processes and kernel internals", "/sys is only for block devices", "/proc is a real on-disk filesystem"], a: 1, why: "/sys exposes the driver model as objects and attributes; /proc grew as a place for process information and assorted kernel state, and is less tidily organised." },
{ t: "os-userspace", d: 3, q: "A sensor needs a 1 kHz sampled stream. Which route?", o: ["sysfs attributes, read in a loop", "A kernel driver, or iio with a trigger", "libgpiod polling a data-ready line", "Reading /dev/mem in a tight loop"], a: 1, why: "A syscall per value formatted as text cannot do it. Buffered reads with a hardware trigger are exactly what the subsystem exists to provide." },

// --------------------------------------------------------------- os-yocto
{ t: "os-yocto", d: 1, q: "What is Yocto?", o: ["An embedded Linux distribution", "A build system that makes you one", "A cross-compiler toolchain", "A package manager for embedded"], a: 1, why: "It builds a bespoke image from source for your board with only what you asked for, plus a licence manifest. Getting that distinction out first matters." },
{ t: "os-yocto", d: 1, q: "What is a recipe?", o: ["The list of packages in an image", "How to build one thing", "A board's hardware description", "A patch applied to the kernel"], a: 1, why: "A .bb file saying where to fetch the source, how to configure, compile and install it, and what it depends on at build and at run time." },
{ t: "os-yocto", d: 2, q: "What is a layer?", o: ["A stage of the boot sequence", "A directory of related recipes", "A partition in the final image", "A level of the build's dependency graph"], a: 1, why: "Layers stack, and a later one can modify an earlier one, which is what lets a vendor BSP and your own changes coexist without either forking the other." },
{ t: "os-yocto", d: 2, q: "How do you patch the vendor's kernel recipe?", o: ["Edit the recipe in their BSP layer", "A bbappend in your own layer", "Copy the recipe into your layer", "Apply the patch after the build"], a: 1, why: "Your changes stay yours and their layer can update underneath you. Editing theirs works until the first BSP update silently overwrites it." },
{ t: "os-yocto", d: 2, q: "What is the difference between DEPENDS and RDEPENDS?", o: ["Libraries against executables", "Build-time against run-time", "Required against optional", "Host tools against target packages"], a: 1, why: "Confusing them gives either a build that cannot find a header, or an image missing a shared library at run time, which is far harder to diagnose." },
{ t: "os-yocto", d: 2, q: "What does MACHINE select?", o: ["Which build host is being used", "Which board you are building for", "Which package format to produce", "Which init system the image uses"], a: 1, why: "It sets the architecture, the kernel, the bootloader and the device trees, and is normally provided by the silicon vendor's BSP layer." },
{ t: "os-yocto", d: 3, q: "Why does Yocto fail when a LICENSE file changes upstream?", o: ["To keep the source checksum stable", "So you must confirm your licence position", "To stop a stale download being reused", "To check the SRCREV pin still resolves"], a: 1, why: "LIC_FILES_CHKSUM is a deliberate tripwire. A project relicensing under your feet is a legal problem, so the build stops rather than shipping it quietly." },
{ t: "os-yocto", d: 3, q: "When is Buildroot the better choice?", o: ["One product and a small team", "Whenever storage is constrained", "When no vendor BSP layer exists", "For anything without licence duties"], a: 0, why: "A Kconfig menu and a Makefile, understandable in an afternoon and built in twenty minutes. Yocto earns its complexity across many boards and licence compliance at scale." },
{ t: "os-yocto", d: 3, q: "Roughly what does a first Yocto build need?", o: ["An hour and 10 GB of disk", "Hours, and 50 to 100 GB", "A few minutes on a fast machine", "A day, and a dedicated build server"], a: 1, why: "It builds a cross compiler before it builds anything of yours. Subsequent builds use the shared state cache and are far quicker." },
{ t: "os-yocto", d: 3, q: "What does bitbake actually do?", o: ["Cross-compiles a single recipe", "Resolves the dependency graph and builds", "Flashes the finished image to a board", "Manages packages on the target"], a: 1, why: "It reads every layer and recipe, works out what depends on what, and schedules the tasks. The recipes describe; bitbake executes." },

// ---------------------------------------------------------- os-linuxdebug
{ t: "os-linuxdebug", d: 1, q: "What does strace show?", o: ["Every function the program calls", "The system calls, with arguments", "The instructions actually executed", "The libraries it has loaded"], a: 1, why: "Library calls are invisible, which is why the output is far shorter than the source suggests, and why it goes straight to what the program asked the kernel for." },
{ t: "os-linuxdebug", d: 1, q: "Where do kernel and driver messages go?", o: ["stderr of the calling process", "dmesg, and the journal", "/proc/kmsg only, for root", "The bootloader's console buffer"], a: 1, why: "printk goes to the ring buffer, which dmesg reads and journald usually persists. It is the first place to look when a driver has failed quietly." },
{ t: "os-linuxdebug", d: 2, q: "Why not just halt the CPU as you would on a Cortex-M?", o: ["The debug port is fused off in production", "It stops things that must not stop", "The MMU makes addresses meaningless", "gdb cannot attach to a running kernel"], a: 1, why: "Hundreds of threads and peripherals still running, so the discipline inverts to observing a live system rather than freezing a stopped one." },
{ t: "os-linuxdebug", d: 2, q: "How do you debug a process on a target with gdb?", o: ["Run gdb on the target directly", "gdbserver on target, cross gdb on host", "Attach through the JTAG probe", "Enable the kernel's built-in debugger"], a: 1, why: "It is the right tool for a logic bug inside one process, and the wrong tool for anything involving timing or other processes, because stopping one changes the rest." },
{ t: "os-linuxdebug", d: 2, q: "A kernel oops prints mysensor_read+0x2c/0x120. What is that?", o: ["A line number in the source file", "An offset into a function, like a stacked PC", "The size of the faulting allocation", "The address the faulting driver tried to write to"], a: 1, why: "Resolved against the build that produced it, exactly as you decode a Cortex-M fault. decode_stacktrace.sh needs the matching vmlinux and modules." },
{ t: "os-linuxdebug", d: 2, q: "Which tool answers where the CPU time is going?", o: ["strace, tracing every call", "perf", "dmesg, with timestamps on", "ldd, on the binary"], a: 1, why: "Sampling profiles by symbol across the whole system including the kernel, which is the question strace cannot answer because it only sees syscalls." },
{ t: "os-linuxdebug", d: 3, q: "Why keep vmlinux for a shipped kernel?", o: ["It is needed to boot the image", "To decode an oops from the field", "It contains the device tree source", "The bootloader verifies against it"], a: 1, why: "Symbol offsets only mean something against the exact build that produced them. Same argument as archiving the ELF for a microcontroller image." },
{ t: "os-linuxdebug", d: 3, q: "What is ftrace for?", o: ["Tracing library calls in userspace", "Seeing what the kernel is doing", "Recording every filesystem access", "Following a process across a fork"], a: 1, why: "Function tracing and tracepoints inside the kernel, which is where you go when the question is about scheduling, interrupts or a driver rather than your own code." },
{ t: "os-linuxdebug", d: 3, q: "What does ldd tell you?", o: ["Which symbols a binary exports", "Which shared libraries it needs", "How large each section is", "Whether it was built with symbols"], a: 1, why: "The fastest answer to why a binary will not start on the target, which is usually a C library mismatch between the build host and the image." },
{ t: "os-linuxdebug", d: 3, q: "Which instinct from bare metal should you unlearn?", o: ["Reproducing before attempting a fix", "Reaching for the debugger first", "Checking what the code actually did", "Making the fault happen more often"], a: 1, why: "The method transfers intact. What changes is that observing a running system usually beats stopping it, and strace answers in seconds what a breakpoint takes an hour to reach." }

]);
