// A second pass over every DSP lesson: ten more questions each.
//
// Topic tags are lesson ids, so topicLesson() resolves them by the byId
// fallback and no TOPIC_LESSON entry is needed.
//
// Written so that in roughly three questions out of four a distractor is the
// longest option, which puts "the correct answer is longest" back at chance
// for a four-option question.
BANKS["DSP"] = BANKS["DSP"].concat([

// ----------------------------------------------------------------- sampling
{ t: "sampling", d: 1, q: "What does the Nyquist criterion require?", o: ["Sampling above twice the highest frequency present", "Sampling at a rate that is an exact multiple of the signal's own frequency", "Sampling above twice the bandwidth of the anti-alias filter used", "Sampling at least ten times faster than the fastest edge in the signal"], a: 0, why: "It is the highest frequency present that matters, not the one you are interested in, which is why the anti-alias filter has to come first. Bandpass sampling relaxes this to twice the bandwidth for a signal in a known band." },
{ t: "sampling", d: 2, q: "Why must the anti-alias filter be analogue?", o: ["Once folded, the alias cannot be separated", "Digital filters cannot reach the necessary attenuation at those frequencies", "The converter's input impedance requires a passive network in front of it", "A digital filter would add a delay that breaks the sampling instant"], a: 0, why: "After sampling, an alias sits at the same digital frequency as real signal and nothing downstream can tell them apart. The filtering has to happen while they are still separable." },
{ t: "sampling", d: 2, q: "What does a sample-and-hold circuit remove?", o: ["The input's movement during the conversion", "The quantisation error introduced by the converter's finite resolution", "The offset voltage contributed by the input buffer amplifier", "The high-frequency content that would otherwise alias into the band"], a: 0, why: "A converter that takes microseconds cannot track a moving input, so the hold freezes it at one instant. Successive-approximation parts include one; some sigma-delta architectures do not need it." },
{ t: "sampling", d: 3, q: "A 70 kHz tone is sampled at 100 kHz with no filter. Where does it appear?", o: ["At 30 kHz", "At 70 kHz, unchanged by the sampling process", "At 170 kHz, above the sampling rate itself", "Spread across the band as broadband noise"], a: 0, why: "It folds about the Nyquist frequency, so it lands at the sample rate minus the input, 30 kHz. Nothing marks it as an alias, which is exactly why the filter is mandatory." },
{ t: "sampling", d: 2, q: "What is bandpass sampling?", o: ["Sampling below twice the carrier but above twice the bandwidth", "Sampling only the portion of the signal that lies inside the passband", "Applying a bandpass filter after the converter to select the wanted band", "Varying the sample rate to track a signal whose carrier is drifting"], a: 0, why: "A signal confined to a known band can be deliberately aliased down, provided the band does not straddle a multiple of half the sample rate. The filter in front becomes a bandpass rather than a lowpass." },
{ t: "sampling", d: 2, q: "Why does oversampling relax the anti-alias filter?", o: ["The transition band becomes far wider", "The converter's resolution rises, so the filter needs less attenuation", "Aliased content is removed by the decimation stage that follows", "The filter can be made digital once the rate is high enough"], a: 0, why: "With Nyquist far above the signal, the filter has a whole octave or more to roll off instead of a few kilohertz. A gentle analogue filter plus a sharp digital one after decimation is the standard split." },
{ t: "sampling", d: 3, q: "What limits the signal to noise ratio of a fast converter clocked with jittery timing?", o: ["Timing error becomes amplitude error on a slewing input", "The converter's internal reference is modulated by the clock's phase noise", "The digital filter cannot track a clock whose period keeps changing", "The acquisition window shortens and the sampling capacitor cannot settle"], a: 0, why: "Sampling a moment early or late reads a different voltage, and the error grows with input frequency. The cap is roughly minus twenty log of two pi f times the jitter." },
{ t: "sampling", d: 2, q: "What does quantisation do to a signal, in noise terms?", o: ["Adds an error of about one twelfth of a step squared", "Adds a noise floor that is entirely independent of the number of bits", "Removes low-level detail without contributing any noise power at all", "Introduces a fixed offset equal to half the least significant bit"], a: 0, why: "Treated as uniform noise, the variance is the step squared over twelve, which gives the familiar six decibels per bit. It only behaves as noise when the signal is busy enough to exercise many codes." },
{ t: "sampling", d: 2, q: "Why is dither added before quantisation?", o: ["It turns quantisation tones into broadband noise", "It raises the signal amplitude so the converter's range is fully used", "It compensates for the differential nonlinearity of the converter", "It shifts the signal away from the converter's reference voltage"], a: 0, why: "On a small periodic input the quantisation error is correlated with the signal and appears as harmonics. A little added noise decorrelates it, and averaging then removes it." },
{ t: "sampling", d: 2, q: "What does the sinc roll-off of a zero-order hold do at the output?", o: ["Attenuates the top of the band", "Adds a linear phase delay of exactly half a sample to every frequency", "Removes the images above Nyquist without any further filtering needed", "Increases the amplitude of the signal towards the Nyquist frequency"], a: 0, why: "The hold's response follows sinc, so the passband droops towards Nyquist, by about four decibels at the edge. A compensating digital filter, or an inverse-sinc stage, flattens it back." },

// --------------------------------------------------------------------- fft
{ t: "fft", d: 1, q: "What does the FFT compute?", o: ["The DFT, using a divide-and-conquer factorisation", "A continuous Fourier transform sampled at the frequencies of interest", "The autocorrelation of the input sequence expressed in the frequency domain", "An approximation to the DFT that trades accuracy for execution speed"], a: 0, why: "It is the same transform, computed in N log N instead of N squared by exploiting symmetry in the twiddle factors. The result is exact to within floating-point rounding." },
{ t: "fft", d: 2, q: "What sets the frequency spacing of FFT bins?", o: ["Sample rate divided by the transform length", "The number of bits used to represent each input sample in the buffer", "The window function applied to the data before the transform is taken", "The ratio between the highest and lowest frequencies of interest"], a: 0, why: "Bin spacing is fs over N, so resolution comes from observing for longer, not from more points. Zero padding adds points between the same bins without adding information." },
{ t: "fft", d: 2, q: "What does zero padding an FFT actually give you?", o: ["Interpolation between bins, not extra resolution", "A genuine improvement in the ability to separate two nearby tones", "A reduction in the spectral leakage caused by the analysis window", "A lower noise floor, because the added samples contribute no noise"], a: 0, why: "It samples the same underlying spectrum more finely, which helps you locate a peak but cannot resolve two peaks the observation length could not separate. Resolution is set by the duration of real data." },
{ t: "fft", d: 3, q: "Why does an unwindowed FFT of a non-integer number of cycles leak?", o: ["The implied periodic extension has a discontinuity", "The transform assumes the signal is zero outside the observed interval", "The bin centres do not coincide with the frequencies actually present", "Rounding in the butterfly stages spreads energy into adjacent bins"], a: 0, why: "A rectangular window makes the record repeat, and the join is a step whose spectrum is a sinc that spreads across every bin. A tapered window removes the step at the cost of a wider main lobe." },
{ t: "fft", d: 2, q: "What does a window function trade?", o: ["Main lobe width against sidelobe level", "Frequency resolution against the total execution time of the transform", "Amplitude accuracy against the phase accuracy of the recovered spectrum", "Noise floor against the dynamic range available in the fixed-point path"], a: 0, why: "A gentler taper suppresses the sidelobes but broadens the peak, so two close tones merge. Hann is the usual compromise, and flat-top is chosen when amplitude accuracy matters more than resolution." },
{ t: "fft", d: 2, q: "Why is the FFT of a real signal symmetric?", o: ["Negative-frequency terms must conjugate the positive ones", "The transform discards the imaginary part of a purely real input sequence", "Real signals contain only cosine components, which are inherently even", "The algorithm computes only half the bins and mirrors the remainder"], a: 0, why: "For the imaginary parts to cancel in the reconstruction, X of minus f must be the conjugate of X of f. A real FFT exploits this to compute in about half the time and memory." },
{ t: "fft", d: 3, q: "What is scalloping loss?", o: ["Amplitude error when a tone falls between bin centres", "Attenuation of the highest bins caused by the converter's sinc roll-off", "Leakage of energy from a strong tone into the bins adjacent to it", "The loss of resolution when the transform length is not a power of two"], a: 0, why: "The window's response is not flat between bin centres, so a tone at a bin edge reads low, by about 1.4 decibels for a Hann window. A flat-top window trades resolution to reduce it to a few hundredths." },
{ t: "fft", d: 2, q: "Why is a power-of-two transform length preferred?", o: ["The radix-2 factorisation is the simplest and fastest", "Other lengths cannot be transformed without padding the input with zeros", "Only powers of two give a bin spacing that divides the sample rate exactly", "The window functions are defined only for power-of-two record lengths"], a: 0, why: "Repeated halving gives the cleanest decimation and the best-optimised code paths. Mixed-radix libraries handle other lengths well, and a prime length falls back to a much slower algorithm." },
{ t: "fft", d: 2, q: "What does averaging several FFT magnitudes achieve?", o: ["Reduces the variance of the noise floor estimate", "Improves the frequency resolution in proportion to the number averaged", "Removes any tones that are not present in every one of the segments", "Increases the dynamic range by the square root of the segment count"], a: 0, why: "A single periodogram has a noise variance as large as its mean, so the floor looks ragged. Averaging M independent segments cuts that variance by M without changing the resolution." },
{ t: "fft", d: 2, q: "Why does overlapping segments help when a window is applied?", o: ["It recovers data attenuated by the window's tapered ends", "It increases the effective transform length beyond the segment size", "It removes the need to apply a window to each segment separately", "It guarantees that the segments are statistically independent of each other"], a: 0, why: "The taper throws away the ends of each record, so without overlap you are discarding data. Fifty percent overlap with a Hann window recovers almost all of it, at the cost of some correlation between segments." },

// ----------------------------------------------------------------- filters
{ t: "filters", d: 1, q: "What is the defining property of an FIR filter?", o: ["Its impulse response has finitely many terms", "Its coefficients are always smaller than one so it cannot become unstable", "It uses feedback from previous outputs to shape the frequency response", "Its phase response is always exactly linear whatever the coefficients are"], a: 0, why: "No feedback means the response ends after N samples, so it cannot be unstable. Linear phase follows from coefficient symmetry, which is usual but not automatic." },
{ t: "filters", d: 2, q: "What does an IIR filter buy over an FIR filter?", o: ["A much sharper response for far fewer coefficients", "Guaranteed stability regardless of where the poles happen to be placed", "Exactly linear phase, which is what makes it suitable for audio work", "Immunity to coefficient quantisation because the poles are placed directly"], a: 0, why: "Poles let a low-order design achieve what an FIR needs dozens of taps for. You give up linear phase and take on stability and quantisation sensitivity." },
{ t: "filters", d: 2, q: "Why is linear phase useful?", o: ["Every frequency is delayed by the same amount", "It guarantees that the filter cannot ring on a step input at any frequency", "It allows the filter to be implemented with half the number of multiplies", "It makes the magnitude response flatter across the whole of the passband"], a: 0, why: "A constant group delay means the waveform shape survives, which matters for a pulse or an image edge. The cost is a delay of half the filter length." },
{ t: "filters", d: 3, q: "What makes a filter minimum phase?", o: ["All its zeros lie inside the unit circle", "Its impulse response is symmetric about its midpoint", "It has the smallest possible number of coefficients for the response", "Its group delay is constant across the entire passband"], a: 0, why: "It has the least phase lag and the least delay of any filter with that magnitude response, with energy concentrated early in the impulse response. It is also invertible with a stable inverse." },
{ t: "filters", d: 2, q: "Why is a cascade of second-order sections preferred for a high-order IIR?", o: ["The roots of a high-order polynomial are extremely sensitive to rounding", "A cascade uses fewer multiplies than the direct-form structure", "Second-order sections are the only form that guarantees linear phase", "The sections can be evaluated in parallel on a multi-core processor"], a: 0, why: "Direct-form coefficients of an eighth-order filter are so sensitive that quantisation moves the poles anywhere. Second-order sections localise the sensitivity and are well conditioned." },
{ t: "filters", d: 2, q: "What does a Butterworth response optimise?", o: ["Flatness in the passband", "The steepness of the transition band for a given filter order", "The uniformity of the group delay across the passband and beyond", "The attenuation achieved in the stopband for a fixed number of poles"], a: 0, why: "It is maximally flat, so it has no ripple anywhere at the cost of a gentle roll-off. Chebyshev trades passband ripple for a sharper knee, and elliptic ripples in both bands for the sharpest of all." },
{ t: "filters", d: 2, q: "What does a Bessel filter optimise instead?", o: ["Flat group delay", "The number of coefficients needed to reach a given stopband attenuation", "The rejection of frequencies immediately above the cutoff frequency", "The insensitivity of the response to variation in component values"], a: 0, why: "It preserves waveform shape, which matters for a pulse, at the cost of a very gradual magnitude roll-off. It is the analogue answer to the same problem linear-phase FIR solves digitally." },
{ t: "filters", d: 3, q: "Why can a bilinear-transformed filter's cutoff land in the wrong place?", o: ["The frequency mapping is nonlinear near Nyquist", "The transform introduces a delay that shifts the whole response upward", "The analogue prototype's poles do not map to stable digital poles", "The sample rate must be an exact multiple of the cutoff frequency"], a: 0, why: "The mapping compresses the whole infinite analogue axis into a finite digital one, so frequencies warp increasingly towards Nyquist. Pre-warping the critical frequencies puts them back where you wanted." },
{ t: "filters", d: 2, q: "What is a moving average filter's frequency response?", o: ["A sinc, with nulls at multiples of the reciprocal of the length", "A first-order lowpass with a single pole", "A brick wall whose cutoff is the sample rate divided by the length", "A flat response with a linear phase shift and no attenuation at all"], a: 0, why: "It is a rectangular window in time, so its transform is a sinc, with a poor stopband. It is nonetheless the cheapest possible smoother and its nulls can be placed on an interfering tone." },
{ t: "filters", d: 2, q: "Why does a notch filter need a high Q for mains interference?", o: ["To remove 50 Hz without damaging nearby signal content", "Because the interference amplitude varies with the time of day", "To keep the filter's group delay constant across the passband", "Because a low-Q notch would become unstable in fixed point"], a: 0, why: "The zero pair sits on the unit circle at the mains angle with poles just inside, and the pole radius sets how narrow the notch is. Too wide and you remove signal; too narrow and drift in the mains frequency walks out of it." },

// -------------------------------------------------------- dsp-convolution
{ t: "dsp-convolution", d: 1, q: "What does convolution in the time domain correspond to in frequency?", o: ["Multiplication", "Convolution of the two spectra with each other", "Addition of the two magnitude responses in decibels", "Correlation between the two transformed sequences"], a: 0, why: "That equivalence is the whole basis of filtering by transform, and it is why an FFT-based convolution beats a direct one for long filters. The reverse also holds: multiplying in time convolves in frequency, which is what windowing does." },
{ t: "dsp-convolution", d: 2, q: "What is the length of the convolution of an M-point and an N-point sequence?", o: ["M plus N minus one", "The larger of the two lengths, since the shorter is padded to match", "M times N, because every pair of samples contributes one product", "Exactly N, because convolution preserves the length of the input signal"], a: 0, why: "The result runs from the first overlap to the last, which is M plus N minus one samples. Getting this wrong is why a circular convolution wraps and corrupts the ends." },
{ t: "dsp-convolution", d: 2, q: "Why does an FFT-based convolution give a circular result?", o: ["A finite transform implies a periodic sequence", "The FFT discards the samples that fall outside the transform length", "Multiplication in frequency is only exact for infinitely long sequences", "The inverse transform wraps any values that exceed the numeric range"], a: 0, why: "The DFT treats the record as one period of a periodic signal, so the tail of the convolution folds onto the start. Zero padding to at least M plus N minus one keeps them separate." },
{ t: "dsp-convolution", d: 3, q: "What do overlap-add and overlap-save solve?", o: ["Applying block transforms to a continuous stream", "The instability that arises when convolving with a very long impulse response", "The loss of precision when convolving in fixed point over many blocks", "The need to know the entire input before any output can be produced"], a: 0, why: "You cannot transform an endless stream, so it is cut into blocks and the block boundaries reconciled. Overlap-add sums the tails; overlap-save discards the wrapped part of each block." },
{ t: "dsp-convolution", d: 2, q: "What does correlation compute that convolution does not?", o: ["Similarity, with no time reversal of the second sequence", "The energy contained in the overlap between the two signals at each lag", "The phase difference between the two sequences at every frequency", "A normalised measure that is independent of either signal's amplitude"], a: 0, why: "Convolution flips one sequence before sliding it; correlation does not. That is the only difference, and it is why the two coincide when one sequence is symmetric." },
{ t: "dsp-convolution", d: 2, q: "Why is a matched filter optimal for detecting a known pulse?", o: ["It maximises the output signal to noise ratio in white noise", "It gives the sharpest possible time resolution for the pulse's arrival", "It removes the need for a threshold by producing a binary decision", "It works regardless of the statistics of the background noise present"], a: 0, why: "Correlating with the known shape concentrates the pulse energy into one peak while the noise adds incoherently. It is optimal for white noise; coloured noise needs a whitening stage first." },
{ t: "dsp-convolution", d: 2, q: "What does the autocorrelation of white noise look like?", o: ["An impulse at zero lag and nothing elsewhere", "A slowly decaying exponential whose time constant sets the bandwidth", "A constant value across every lag, since the noise power is uniform", "A sinc function whose first null is at the reciprocal of the bandwidth"], a: 0, why: "White means uncorrelated between samples, so only the zero lag has any value. Its transform is a flat spectrum, which is the frequency-domain statement of the same fact." },
{ t: "dsp-convolution", d: 3, q: "Why is deconvolution ill-posed in the presence of noise?", o: ["Dividing by small spectral values amplifies noise enormously", "The convolution operation destroys information that cannot be recovered", "The inverse filter is always unstable because its poles lie outside the circle", "Deconvolution requires both signals to be causal, which is rarely true"], a: 0, why: "Where the forward response is near zero, the inverse is enormous and multiplies whatever noise is there. Regularisation, such as a Wiener filter, bounds that gain at the cost of some resolution." },
{ t: "dsp-convolution", d: 2, q: "What does convolving a signal with a delayed impulse do?", o: ["Delays it by the same amount", "Attenuates it in proportion to the length of the delay applied", "Reverses the signal in time about the position of the impulse", "Produces two copies of the signal, one at each end of the record"], a: 0, why: "An impulse is the identity for convolution, so shifting it shifts the output. That is why an impulse response tells you everything a linear time-invariant system does." },
{ t: "dsp-convolution", d: 2, q: "When does direct convolution beat the FFT approach?", o: ["When the filter is short, a few tens of taps", "When the input is very long and cannot be held in memory all at once", "When the filter coefficients change from one sample to the next", "Whenever the processor has a hardware multiply-accumulate instruction"], a: 0, why: "The FFT's advantage grows with filter length, and below roughly thirty to sixty taps the transform overhead dominates. The crossover depends on the platform and is worth measuring rather than assuming." },

// ---------------------------------------------------------- dsp-multirate
{ t: "dsp-multirate", d: 1, q: "What must happen before decimating by M?", o: ["Lowpass filter below the new Nyquist frequency", "Multiply the signal by M to preserve its original amplitude", "Remove the DC offset so the decimated record remains centred", "Interpolate to a higher rate first so the ratio becomes an integer"], a: 0, why: "Dropping samples aliases everything above the new Nyquist into the band, and it cannot be removed afterwards. The filter has to come first." },
{ t: "dsp-multirate", d: 2, q: "What must happen after upsampling by L?", o: ["Lowpass filter to remove the spectral images", "Scale the samples by L to restore the correct signal amplitude", "Re-quantise the output to the original word length of the input", "Apply a delay of L samples to keep the group delay constant"], a: 0, why: "Inserting zeros creates images of the spectrum at multiples of the original rate. The interpolation filter removes them, and it also supplies the gain of L that the zeros lost." },
{ t: "dsp-multirate", d: 2, q: "Why is a polyphase implementation more efficient?", o: ["It skips the multiplies whose results are discarded", "It replaces the filter with a shorter one of equivalent response", "It moves the filtering into the frequency domain where it costs less", "It allows the filter coefficients to be stored at lower precision"], a: 0, why: "In decimation most outputs are thrown away, and in interpolation most inputs are zero, so those products are wasted. Decomposing the filter into phases computes only the ones that matter." },
{ t: "dsp-multirate", d: 3, q: "How do you resample from 48 kHz to 44.1 kHz?", o: ["Upsample by 147, downsample by 160", "Upsample by 160, then downsample by 147 with the filter in between", "Interpolate to a common multiple and truncate every fourth sample", "Apply a fractional delay filter tuned to the ratio of the two rates"], a: 0, why: "The ratio 44100 over 48000 reduces to 147 over 160, so you interpolate by 147 and decimate by 160. The intermediate rate is high, which is exactly why a polyphase structure is used." },
{ t: "dsp-multirate", d: 2, q: "What is a CIC filter's main attraction?", o: ["No multipliers at all, only adders and delays", "A perfectly flat passband that needs no compensation afterwards", "Linear phase combined with a very sharp transition band", "Complete immunity to the overflow that troubles other structures"], a: 0, why: "Integrators and combs need only additions, which suits a high-rate front end in an FPGA. The passband droop is the price, and it is corrected by a short FIR at the lower rate." },
{ t: "dsp-multirate", d: 2, q: "Why does a CIC filter need a compensation filter?", o: ["Its passband droops like a sinc response", "Its group delay varies substantially across the passband of interest", "Its stopband attenuation is too low to prevent aliasing on decimation", "Its gain grows without bound as the decimation factor is increased"], a: 0, why: "The comb sections give a sinc-shaped magnitude, so the top of the band sags noticeably. A short inverse-sinc FIR after decimation flattens it cheaply." },
{ t: "dsp-multirate", d: 2, q: "What happens to noise power when you decimate by M?", o: ["In-band noise stays, out-of-band noise is filtered away", "It falls by a factor of M because there are fewer samples to carry it", "It rises by a factor of M as the out-of-band noise folds into the band", "It is unchanged, since decimation is a lossless operation on the samples"], a: 0, why: "The anti-alias filter removes the noise above the new Nyquist before it can fold. Without that filter it would indeed fold in and raise the floor." },
{ t: "dsp-multirate", d: 3, q: "Why is a half-band filter especially cheap?", o: ["About half its coefficients are exactly zero", "It requires only half the memory of an equivalent full-band design", "It halves the sample rate automatically without a separate decimator", "Its coefficients are all powers of two, so no multiplier is needed"], a: 0, why: "The symmetry forces every other coefficient to zero except the centre tap, so a decimate-by-two costs about half the multiplies. Cascading them is the standard way to change rate by a large power of two." },
{ t: "dsp-multirate", d: 2, q: "What does a fractional delay filter do?", o: ["Interpolates between samples to shift by part of a sample", "Changes the sample rate by a ratio that is not a whole number", "Compensates for the group delay of the anti-alias filter in front", "Aligns two channels whose clocks differ by a small frequency offset"], a: 0, why: "It approximates the ideal sinc interpolator over a short window, so you can position a waveform between the sampling instants. It is how a beamformer steers without changing the clock." },
{ t: "dsp-multirate", d: 2, q: "Why decimate as early as possible in a processing chain?", o: ["Everything downstream then runs at a lower rate", "The signal to noise ratio improves with each stage of decimation", "It removes the need for anti-alias filtering later in the chain", "The dynamic range of the fixed-point path grows as the rate falls"], a: 0, why: "Every operation after the decimator costs proportionally less, which is the whole point of a multirate design. The filter that permits the decimation is itself the expensive part, which is why it is made cheap with polyphase or CIC structures." },

// -------------------------------------------------------------- dsp-noise
{ t: "dsp-noise", d: 1, q: "What is the processing gain of coherent averaging over M records?", o: ["The square root of M in amplitude terms", "A factor of M in amplitude, because the signals add directly", "The logarithm of M, since the noise adds on a decibel scale", "It depends on the bandwidth rather than the number of records"], a: 0, why: "Signal amplitudes add linearly and independent noise adds in RMS, so the ratio improves as root M. That is three decibels per doubling, and it needs the records to be aligned in phase." },
{ t: "dsp-noise", d: 2, q: "Why does coherent averaging require a stable trigger?", o: ["Jitter between records smears the signal but not the noise", "A drifting trigger changes the effective sample rate of each record", "Without it the records cannot be scaled to a common amplitude", "The noise would otherwise become correlated between the records"], a: 0, why: "The signal only adds coherently if it lands in the same samples every time. Trigger jitter acts as a lowpass on the averaged result and destroys the high-frequency content first." },
{ t: "dsp-noise", d: 2, q: "What does a lock-in amplifier exploit?", o: ["Correlation with a reference to reject everything else", "The fact that noise is always smaller than the signal being measured", "The ability of a narrow analogue filter to track a drifting carrier", "The statistical independence of successive samples of the noise"], a: 0, why: "Multiplying by a reference at the signal frequency and lowpass filtering leaves only components correlated with that reference. The effective bandwidth is set by the output filter and can be a fraction of a hertz." },
{ t: "dsp-noise", d: 3, q: "Why does a longer measurement stop improving a DC reading eventually?", o: ["Flicker noise dominates as the averaging time grows", "The converter's quantisation error accumulates over many samples", "The reference voltage drifts by more than the noise you removed", "The record length exceeds what the processor's accumulator can hold"], a: 0, why: "Averaging beats white noise as root time, but 1/f noise grows in the same direction, so there is a floor. Chopping moves the measurement above the flicker corner and lets averaging work again." },
{ t: "dsp-noise", d: 2, q: "How do two uncorrelated noise sources combine?", o: ["Their powers add, so voltages add in quadrature", "Their peak-to-peak voltages add directly to give the total", "The larger source dominates and the smaller can be ignored entirely", "They add linearly if they are in phase and cancel if they are not"], a: 0, why: "Adding in power means a source ten decibels below another contributes about half a decibel. That is why chasing the second-largest noise source is usually wasted effort." },
{ t: "dsp-noise", d: 2, q: "What does noise shaping in a sigma-delta converter achieve?", o: ["It pushes quantisation noise out of the signal band", "It reduces the total quantisation noise power the converter produces", "It removes the need for any anti-alias filtering at the input", "It linearises the converter's transfer function across the range"], a: 0, why: "The total noise is unchanged but its distribution is not: the loop attenuates it in band and amplifies it above. The decimation filter then discards the part that was pushed up." },
{ t: "dsp-noise", d: 2, q: "Why does narrowing the analysis bandwidth improve signal to noise ratio?", o: ["Broadband noise scales with bandwidth, a tone does not", "A narrower filter has a lower insertion loss and passes more signal", "The processor can use a longer word length at a lower bandwidth", "Narrow filters remove the quantisation noise as well as the thermal noise"], a: 0, why: "Halving the bandwidth halves the noise power while a narrowband signal is untouched. That is the entire basis of both lock-in detection and long FFT integration." },
{ t: "dsp-noise", d: 3, q: "What does the crest factor of a signal tell a fixed-point designer?", o: ["How much headroom is needed above the RMS level", "The ratio between the signal's bandwidth and the sample rate used", "How many bits of the word length carry useful information", "The degree of correlation between successive samples of the signal"], a: 0, why: "A high crest factor means rare large peaks, so scaling for RMS alone will clip them. Scaling for the peak instead wastes bits on a level that is almost never reached, which is the trade to be made explicitly." },
{ t: "dsp-noise", d: 2, q: "Why is a median filter better than a mean for impulsive noise?", o: ["A single outlier cannot move the median much", "The median is faster to compute than a mean over the same window", "The median preserves the frequency content that a mean would remove", "A median filter is linear, so its effect can be analysed in frequency"], a: 0, why: "One extreme value shifts a mean in proportion to its size but barely moves the ordering. The cost is that the filter is nonlinear, so superposition and frequency analysis no longer apply." },
{ t: "dsp-noise", d: 2, q: "What does subtracting a recorded background do that filtering cannot?", o: ["Removes an interferer that overlaps the signal in frequency", "Improves the signal to noise ratio by the square root of the record length", "Eliminates the random component of the noise as well as the fixed part", "Compensates for the nonlinearity of the acquisition chain"], a: 0, why: "If the interference is repeatable, subtracting a measurement of it removes it even where a filter could not separate it. It only works while the background stays stable, which is worth verifying." },

// ------------------------------------------------------------ dsp-spectral
{ t: "dsp-spectral", d: 2, q: "What does Welch's method do?", o: ["Averages periodograms of overlapping windowed segments", "Applies a single very long transform and smooths the result in frequency", "Fits an autoregressive model and evaluates its spectrum analytically", "Computes the exact power spectral density with no variance whatsoever"], a: 0, why: "Splitting the record trades frequency resolution for a much lower variance in the estimate. More segments means a smoother floor and coarser bins, which is the central trade in spectral estimation." },
{ t: "dsp-spectral", d: 2, q: "Why does a single periodogram look so ragged?", o: ["Its variance does not fall as the record gets longer", "The window function introduces ripple across the whole spectrum", "Quantisation noise in the transform dominates the low-level bins", "The estimate is biased upward by the leakage from strong components"], a: 0, why: "A longer record gives more bins but each is still one noisy sample of the underlying density. Only averaging independent estimates reduces the variance." },
{ t: "dsp-spectral", d: 3, q: "What is the relationship between the autocorrelation and the power spectrum?", o: ["They are a Fourier transform pair", "The spectrum is the derivative of the autocorrelation with respect to lag", "The autocorrelation is the inverse transform of the magnitude spectrum", "They are equal when the signal is stationary and zero mean"], a: 0, why: "That is the Wiener-Khinchin theorem, and it is why you can estimate a spectrum either by transforming the data or by transforming its autocorrelation. The second route is the basis of the Blackman-Tukey method." },
{ t: "dsp-spectral", d: 2, q: "What does a spectrogram show?", o: ["How the spectrum changes over time", "The phase relationship between two channels at every frequency", "The total energy in each frequency band across the whole record", "The correlation between the signal and a set of reference waveforms"], a: 0, why: "It is a sequence of short transforms laid side by side, so the window length sets the trade between time and frequency resolution. You cannot have both at once, which is the uncertainty principle in practice." },
{ t: "dsp-spectral", d: 2, q: "Why does a flat-top window exist?", o: ["It measures amplitude accurately even between bin centres", "It gives the narrowest main lobe of any window in common use", "It has the lowest sidelobes, which suits weak-signal detection", "It requires no correction factor when computing power spectral density"], a: 0, why: "Its response is deliberately flat over more than a bin, so scalloping loss falls to a few hundredths of a decibel. The main lobe is very wide, so it is useless for resolving close tones." },
{ t: "dsp-spectral", d: 2, q: "What is the noise-equivalent bandwidth of a window?", o: ["The width of an ideal filter passing the same noise power", "The frequency range over which the window's response is within 3 dB", "The spacing between the first two nulls of the window's transform", "The bandwidth beyond which the sidelobes fall below the noise floor"], a: 0, why: "It is the factor you need to convert a bin's value into a power spectral density in units per hertz. Forgetting it is a common reason two instruments disagree about a noise floor." },
{ t: "dsp-spectral", d: 3, q: "Why can a strong tone hide a weak one nearby?", o: ["The window's sidelobes bury the weaker component", "The transform's dynamic range is limited by the input word length", "The two tones interfere and produce a beat that averages to nothing", "The stronger tone saturates the converter and suppresses the weaker"], a: 0, why: "A rectangular window's first sidelobe is only thirteen decibels down, so anything weaker than that within a few bins is lost. A Blackman-Harris window buys ninety decibels at the cost of a much wider main lobe." },
{ t: "dsp-spectral", d: 2, q: "What does the coherence between two signals measure?", o: ["How much of the output is linearly explained by the input", "The correlation between the two signals at zero time lag", "The phase difference between the two channels", "The ratio of their power spectral densities at each frequency"], a: 0, why: "It runs from zero to one at each frequency and is the frequency-domain analogue of a correlation coefficient. A value well below one says there is noise, nonlinearity or another input involved." },
{ t: "dsp-spectral", d: 2, q: "Why must you window before, not after, the transform?", o: ["Windowing is a time-domain multiplication", "The window's own spectrum would otherwise be added to the result", "The transform would overflow without the window's attenuation", "Applying it afterwards would change the phase of every component"], a: 0, why: "Tapering the record is what removes the discontinuity in the implied periodic extension. Doing it in frequency would be a convolution, which is neither what you want nor cheap." },
{ t: "dsp-spectral", d: 2, q: "What does a peak in the cepstrum indicate?", o: ["A periodic structure in the spectrum, such as an echo", "The dominant frequency component present in the original signal", "The point at which the signal's phase wraps through 2 pi", "A nonlinearity in the acquisition chain producing harmonics"], a: 0, why: "Taking a transform of the log spectrum turns regularly spaced spectral ripples into a single peak at the corresponding quefrency. It is how an echo delay or a pitch period is extracted." },

// -------------------------------------------------------------- dsp-timing
{ t: "dsp-timing", d: 2, q: "How is time of flight usually estimated to sub-sample accuracy?", o: ["Interpolate the peak of the cross-correlation", "Increase the sample rate until the required resolution is reached", "Measure the phase of the signal at a single chosen frequency", "Count the number of zero crossings before the arrival of the echo"], a: 0, why: "Fitting a parabola or a sinc through the peak and its neighbours locates it to a small fraction of a sample. It costs nothing in acquisition and is limited by the signal to noise ratio." },
{ t: "dsp-timing", d: 2, q: "Why does a matched filter improve time-of-flight precision?", o: ["It concentrates the pulse energy into one sharp peak", "It removes the frequency-dependent attenuation of the medium", "It compensates for the transducer's phase response automatically", "It converts the amplitude measurement into a phase measurement"], a: 0, why: "The output is the autocorrelation of the transmitted pulse, which is as narrow as the bandwidth allows and as tall as the energy permits. Precision scales with bandwidth and with the square root of the energy." },
{ t: "dsp-timing", d: 3, q: "What is the advantage of a chirp over a short pulse?", o: ["Energy without sacrificing resolution after compression", "A lower peak transmit voltage for the same received amplitude", "Immunity to the frequency-dependent absorption of the medium", "A simpler receiver, since no correlation processing is required"], a: 0, why: "A long chirp puts far more energy into the medium, and correlating with the known sweep compresses it to the reciprocal of the bandwidth. That decouples energy from resolution, which a plain pulse cannot do." },
{ t: "dsp-timing", d: 2, q: "Why is envelope detection often used before peak picking?", o: ["It removes the carrier so the peak is not a single cycle", "It increases the signal to noise ratio by the compression factor", "It corrects the group delay introduced by the receive filter", "It converts the signal to a form the correlator can accept"], a: 0, why: "On a narrowband signal the correlation peak repeats every cycle, so the envelope tells you which cycle without ambiguity. Once the envelope has chosen the cycle, the phase can refine within it." },
{ t: "dsp-timing", d: 2, q: "What is cycle-skipping in a phase-based measurement?", o: ["Choosing the wrong cycle, giving a whole-period error", "Losing samples because the processor cannot keep up with the rate", "A gradual drift in the measured phase as the medium warms", "The failure of the phase-locked loop to acquire the incoming signal"], a: 0, why: "Phase is only known modulo two pi, so the coarse envelope estimate has to be good enough to pick the right cycle. A wrong choice is a large, discrete error rather than a small one." },
{ t: "dsp-timing", d: 2, q: "Why does averaging many pulses improve timing precision?", o: ["The noise on the correlation peak falls as root M", "The transmitted pulse becomes narrower with each repetition", "Systematic errors in the trigger cancel out over many records", "The effective bandwidth of the measurement increases with M"], a: 0, why: "Precision on the peak position scales with the signal to noise ratio, which improves as root M for coherent averaging. It does nothing for a systematic offset such as an uncalibrated cable delay." },
{ t: "dsp-timing", d: 3, q: "What limits the precision of a time-of-flight measurement fundamentally?", o: ["Bandwidth and signal to noise ratio together", "The sample rate, since you cannot resolve below one sample", "The stability of the oscillator driving the transmit electronics", "The linearity of the receiver's amplifier at high signal levels"], a: 0, why: "The Cramer-Rao bound falls with bandwidth and with the square root of the energy, and interpolation gets you well below one sample. The clock matters only if its drift is comparable to that bound." },
{ t: "dsp-timing", d: 2, q: "Why is a fixed threshold a poor arrival detector?", o: ["The crossing moves as the amplitude changes", "It cannot be implemented in real time on a small processor", "A threshold responds to noise as readily as to the signal", "It requires the signal to be positive at the moment of arrival"], a: 0, why: "A weaker echo crosses the same threshold later, so the measured time depends on amplitude. Correlation, or a threshold on the normalised envelope, removes the dependence." },
{ t: "dsp-timing", d: 2, q: "What does an anti-alias filter contribute to a timing measurement?", o: ["A group delay that must be calibrated out", "A reduction in the achievable precision by the filter's order", "An amplitude error that varies with the arrival time of the echo", "A phase reversal that inverts the sign of the correlation peak"], a: 0, why: "Every filter in the chain delays the signal, and unless it is measured it appears as a constant offset in the result. Calibrating against a known path is the practical way to remove it." },
{ t: "dsp-timing", d: 2, q: "Why measure a reference path alongside the unknown?", o: ["Common delays and drifts cancel in the difference", "It doubles the signal to noise ratio of the measurement", "It provides a trigger for synchronising the acquisition", "It removes the need to know the speed of sound in the medium"], a: 0, why: "Cable delay, electronics delay and temperature drift are common to both, so the difference is insensitive to them. It is the timing equivalent of a ratiometric measurement." },

// ------------------------------------------------------------ dsp-zdomain
{ t: "dsp-zdomain", d: 1, q: "Where must the poles of a stable causal digital filter lie?", o: ["Strictly inside the unit circle", "Anywhere in the left half of the complex frequency plane", "Outside the unit circle but within a radius of two", "On the unit circle, at the frequencies of interest"], a: 0, why: "A pole at radius r contributes a term that decays as r to the n, so r below one is what makes it die away. On the circle it rings for ever and outside it grows without bound." },
{ t: "dsp-zdomain", d: 2, q: "What does the unit circle represent in the z plane?", o: ["The frequency axis, from DC round to Nyquist", "The boundary beyond which the filter's gain exceeds unity", "The set of points at which the filter has zero phase shift", "The locus of all possible pole positions for a stable design"], a: 0, why: "Evaluating the transfer function on the circle gives the frequency response, with z equal to one at DC and minus one at Nyquist. That is why a zero on the circle is an exact null." },
{ t: "dsp-zdomain", d: 2, q: "What does a pole close to the unit circle mean physically?", o: ["A resonance that rings for a long time", "A filter that will be unstable in fixed-point arithmetic", "A sharp transition between the passband and the stopband", "A frequency at which the filter's output is exactly zero"], a: 0, why: "The closer to the circle, the slower the decay and the higher the Q. It is also where coefficient quantisation is most dangerous, because a small move crosses the circle." },
{ t: "dsp-zdomain", d: 3, q: "Why must complex poles appear in conjugate pairs?", o: ["A real impulse response needs the complex terms to cancel", "Otherwise the filter would be unstable at some frequencies", "The z transform is only defined for conjugate-symmetric functions", "It halves the number of multiplies needed in the implementation"], a: 0, why: "Each complex pole contributes a complex exponential, and only its conjugate can cancel the imaginary part. A single unpaired complex pole would give a complex-valued output." },
{ t: "dsp-zdomain", d: 2, q: "What does a zero at z equal to one do?", o: ["Blocks DC completely", "Introduces a ninety degree phase shift at every frequency", "Makes the filter's response flat across the whole passband", "Places a null at the Nyquist frequency rather than at DC"], a: 0, why: "z equals one is the DC point on the unit circle, so a zero there gives infinite rejection of a constant. A differencing filter, one minus z to the minus one, is exactly that." },
{ t: "dsp-zdomain", d: 2, q: "What is a non-minimum-phase filter?", o: ["One with a zero outside the unit circle", "One whose poles and zeros are not in conjugate pairs", "One whose group delay varies across the passband", "One that cannot be implemented causally at all"], a: 0, why: "The magnitude response is achievable, but the phase lag is larger than necessary and the inverse is unstable. That is why a system identified from data is often forced to be minimum phase." },
{ t: "dsp-zdomain", d: 2, q: "What does the region of convergence tell you?", o: ["Whether the sequence is causal and whether it is stable", "The frequencies at which the filter has appreciable gain", "The range of coefficient values for which the design is realisable", "How many samples the impulse response takes to decay"], a: 0, why: "For a causal sequence it is outside the outermost pole, and stability additionally requires it to include the unit circle. The same pole-zero plot can describe several sequences with different regions." },
{ t: "dsp-zdomain", d: 3, q: "Why is direct-form II transposed the preferred structure?", o: ["Better numerical behaviour and only two state variables", "It uses fewer multiplies than any of the other direct forms", "It is the only structure that guarantees linear phase response", "It avoids the need to store any previous input samples at all"], a: 0, why: "The accumulator ordering keeps intermediate values smaller, which matters in fixed point, and the state is minimal. It is the default in most libraries for exactly these reasons." },
{ t: "dsp-zdomain", d: 2, q: "What does moving a pole radially outward do to the response?", o: ["Narrows and heightens the resonance peak", "Shifts the resonance to a higher frequency without changing its width", "Reduces the filter's overall gain at every frequency equally", "Converts the resonance into a null at the same frequency"], a: 0, why: "The radius controls the Q while the angle controls the frequency, so radius alone changes sharpness. Approaching the circle makes the peak both taller and narrower until it becomes an oscillator." },
{ t: "dsp-zdomain", d: 2, q: "How does the pole angle relate to frequency?", o: ["Angle is frequency scaled so that pi is Nyquist", "Angle is the phase shift the filter applies at that frequency", "Angle determines the decay rate and radius the frequency", "Angle is measured from the imaginary axis rather than the real one"], a: 0, why: "A pole at angle theta resonates at theta over two pi times the sample rate. That is why a filter designed at one sample rate lands at a different frequency in hertz if the rate changes." },

// -------------------------------------------------------- dsp-fir-design
{ t: "dsp-fir-design", d: 2, q: "What does the window method for FIR design do?", o: ["Truncates the ideal impulse response and tapers it", "Places zeros directly on the unit circle at the stopband frequencies", "Solves a least-squares problem for the best coefficient set", "Iteratively adjusts the coefficients until the specification is met"], a: 0, why: "The ideal brick wall is an infinite sinc, so it is cut short and windowed to control the resulting ripple. It is simple and gives no control over passband and stopband ripple separately." },
{ t: "dsp-fir-design", d: 2, q: "Why does simple truncation give poor stopband attenuation?", o: ["The discontinuity produces sidelobes near minus thirteen decibels", "The filter has too few coefficients for the stopband", "Truncation moves the zeros off the unit circle where they do less", "The impulse response is no longer symmetric, so phase is nonlinear"], a: 0, why: "A rectangular window's transform is a sinc whose first sidelobe is thirteen decibels down, regardless of length. Adding taps narrows the transition but does not lower those sidelobes." },
{ t: "dsp-fir-design", d: 3, q: "What does the Parks-McClellan algorithm optimise?", o: ["Equiripple error, minimising the worst deviation", "The total squared error across the passband and stopband together", "The number of coefficients required to meet a stated specification", "The group delay flatness across the whole of the passband"], a: 0, why: "It spreads the error evenly so the maximum deviation is as small as possible, which needs fewer taps than a windowed design for the same worst-case specification. The ripple is uniform rather than decaying." },
{ t: "dsp-fir-design", d: 2, q: "What symmetry gives an FIR filter linear phase?", o: ["Coefficients symmetric or antisymmetric about the centre", "All coefficients positive and summing to exactly one", "Coefficients that decay away from the centre tap", "An odd number of taps with a zero-valued centre coefficient"], a: 0, why: "Symmetry makes the frequency response a real function times a pure delay, which is constant group delay. It also halves the multiplies, since pairs of taps share a coefficient." },
{ t: "dsp-fir-design", d: 2, q: "Which FIR type cannot implement a highpass filter?", o: ["Type II, which is forced to have a zero at Nyquist", "Type I, because its centre tap is always the largest", "Type III, since its response is zero at DC by construction", "Type IV, whose antisymmetry prevents any highpass response"], a: 0, why: "An even number of taps with symmetric coefficients forces a zero at z equals minus one, which is Nyquist. That rules it out for a highpass, and the design tool will tell you so." },
{ t: "dsp-fir-design", d: 2, q: "How does filter length relate to transition width?", o: ["Roughly inversely: a narrower transition needs more taps", "Linearly, so halving the transition halves the tap count", "Not at all; the length only affects the stopband attenuation", "By the square, so halving the transition needs four times the taps"], a: 0, why: "The rule of thumb is attenuation in decibels over about twenty-two times the normalised transition width. It is why a very sharp filter at a high sample rate is so expensive." },
{ t: "dsp-fir-design", d: 3, q: "What is the practical effect of quantising FIR coefficients?", o: ["The stopband floor rises but the filter stays stable", "The filter can become unstable if the rounding is severe", "The passband gain drifts with the input signal amplitude", "The phase response stops being linear"], a: 0, why: "With no feedback there is nothing to become unstable, so the damage is limited to a raised stopband and a slightly wrong response. Keeping the coefficient symmetry exact preserves linear phase through quantisation." },
{ t: "dsp-fir-design", d: 2, q: "When would you accept a non-linear-phase FIR design?", o: ["When the delay of a symmetric filter is unacceptable", "When the filter must be implemented in fixed-point arithmetic", "When the stopband attenuation requirement is unusually severe", "When the input signal is real rather than complex valued"], a: 0, why: "A minimum-phase design concentrates its energy early, so it has far less delay for the same magnitude response. That matters inside a control loop, where delay costs phase margin." },
{ t: "dsp-fir-design", d: 2, q: "Why is a Kaiser window popular?", o: ["One parameter trades main lobe width against sidelobes", "It gives exactly equiripple behaviour in both bands", "It requires no multiplications when applied to the data", "It is the only window with a closed-form inverse"], a: 0, why: "The beta parameter moves continuously between rectangular-like and very heavily tapered, so a design formula can hit an attenuation target directly. It is close to optimal in an energy-concentration sense." },
{ t: "dsp-fir-design", d: 2, q: "What does specifying passband ripple in decibels imply?", o: ["A tolerance band the response must stay inside", "The maximum attenuation permitted in the stopband region", "The variation in group delay allowed across the passband", "The accuracy to which the coefficients must be represented"], a: 0, why: "It is a peak-to-peak deviation about the nominal gain, and tightening it costs taps. Trading a little more passband ripple for a narrower transition is often the cheapest way to meet a specification." },

// -------------------------------------------------------- dsp-iir-design
{ t: "dsp-iir-design", d: 2, q: "What is the usual route to an IIR design?", o: ["Design an analogue prototype and transform it", "Place the poles and zeros directly on the z plane by inspection", "Solve a least-squares fit to the desired frequency response", "Truncate an infinite impulse response to a finite number of terms"], a: 0, why: "Butterworth, Chebyshev and elliptic prototypes are well characterised, and the bilinear transform maps them to the z plane. Direct placement is used for simple cases such as a notch." },
{ t: "dsp-iir-design", d: 2, q: "What does pre-warping correct?", o: ["The nonlinear frequency mapping of the bilinear transform", "The gain error introduced by transforming an analogue prototype", "The phase distortion caused by the filter's feedback path", "The difference between the analogue and digital sample rates"], a: 0, why: "The bilinear transform compresses the infinite analogue axis into a finite digital one, so critical frequencies shift. Pre-warping the prototype's frequencies puts the digital ones where you asked for them." },
{ t: "dsp-iir-design", d: 3, q: "Why can an IIR filter that simulates correctly still fail in fixed point?", o: ["Quantised coefficients move the poles, possibly outside the circle", "Fixed-point arithmetic cannot represent the feedback terms at all", "The filter's group delay changes when the word length is reduced", "Overflow in the input stage prevents the filter from ever settling"], a: 0, why: "High-Q poles are exquisitely sensitive to coefficient rounding, and a small move across the unit circle is instability. Second-order sections, and a structure such as coupled form, reduce that sensitivity." },
{ t: "dsp-iir-design", d: 2, q: "What is a limit cycle?", o: ["A small self-sustaining oscillation caused by rounding", "A slow drift of the output away from its correct value", "The maximum input before the filter overflows", "A resonance at the boundary of the filter's passband"], a: 0, why: "Rounding in the feedback path can trap the filter in a small repeating pattern even with zero input. Adding a tiny dither, or using magnitude truncation, breaks it." },
{ t: "dsp-iir-design", d: 2, q: "Why order the sections of a cascaded IIR filter carefully?", o: ["To keep intermediate signals within the available range", "Because sections must be evaluated in frequency order", "So that the total group delay comes out constant", "Because the last section determines the overall stability"], a: 0, why: "Pairing each pole with its nearest zero and sequencing the sections controls the internal signal levels. Get it wrong and a middle section overflows even though the input and output are well scaled." },
{ t: "dsp-iir-design", d: 2, q: "What does an elliptic filter give you?", o: ["The sharpest transition for a given order, with ripple in both bands", "A perfectly flat passband and a monotonic stopband roll-off", "Constant group delay across the passband, like a Bessel design", "Guaranteed stability regardless of the coefficient word length"], a: 0, why: "It is the most efficient in order for a given selectivity, which is why it appears in anti-alias front ends. The ripple in both bands and its poor phase response are the price." },
{ t: "dsp-iir-design", d: 3, q: "How do you get zero-phase filtering from an IIR filter?", o: ["Filter forwards, then backwards through the same filter", "Design the filter with symmetric feedback coefficients", "Apply an all-pass section to flatten the group delay", "Halve the filter order and double the sample rate"], a: 0, why: "The backward pass cancels the phase of the forward one, giving zero phase and squared magnitude. It needs the whole record in advance, so it is an offline technique only." },
{ t: "dsp-iir-design", d: 2, q: "What is an all-pass section used for?", o: ["Shaping phase or group delay without touching magnitude", "Attenuating a narrow band of frequencies very sharply", "Removing the DC component and nothing else", "Converting a lowpass response into a highpass one"], a: 0, why: "Its poles and zeros are reflections in the unit circle, so the magnitude is flat everywhere. That makes it the tool for delay equalisation and for building filter banks." },
{ t: "dsp-iir-design", d: 2, q: "Why does a biquad's b coefficients set the zeros?", o: ["The numerator polynomial's roots are the zeros", "The feedback path determines where the response falls to zero", "The b coefficients scale the output and hence the nulls", "Zeros are always at the reciprocal of the pole locations"], a: 0, why: "The transfer function is numerator over denominator, so numerator roots are zeros and denominator roots are poles. Recognising which array is which is the first step in reading any biquad implementation." },
{ t: "dsp-iir-design", d: 2, q: "What happens to an IIR filter's cutoff if the sample rate changes?", o: ["It moves in proportion, since the design is in normalised frequency", "It stays where it was, because the coefficients are absolute", "It becomes unstable, because the poles move outside the circle", "Nothing at all, since the coefficients are dimensionless numbers"], a: 0, why: "The coefficients encode a normalised frequency, so running the same filter at forty-eight times the rate puts the cutoff forty-eight times higher in hertz. Redesigning per rate is the only correct answer." },

// -------------------------------------------------------------- dsp-fixed
{ t: "dsp-fixed", d: 1, q: "What does Q15 format represent?", o: ["A signed value with fifteen fractional bits", "An unsigned integer with a range of fifteen bits", "A floating-point value with a fifteen-bit mantissa", "A fixed-point number with fifteen integer bits and one sign"], a: 0, why: "One sign bit and fifteen fraction bits gives a range of about minus one to just under one. It is the standard format for signal samples because the natural range is already normalised." },
{ t: "dsp-fixed", d: 2, q: "What format results from multiplying two Q15 values?", o: ["Q30, needing a shift to return to Q15", "Q15, because the format is preserved by multiplication", "Q16, since one bit is gained from the rounding step", "Q45, because the fractional bits multiply rather than add"], a: 0, why: "The fractional bits add, so the product has thirty of them plus two sign bits in a 32-bit accumulator. Shifting left by one and taking the high half is the usual way back to Q15." },
{ t: "dsp-fixed", d: 2, q: "Why is saturating arithmetic preferred to wrapping?", o: ["It clamps at the extreme instead of jumping to the opposite sign", "It uses fewer instruction cycles on most processors", "It prevents overflow from occurring in the first place", "It preserves the exact value when the result is out of range"], a: 0, why: "A wrap turns a large positive into a large negative, which in a filter is a violent discontinuity that can start an oscillation. Saturation degrades gracefully, which is almost always what you want." },
{ t: "dsp-fixed", d: 3, q: "What is the hardest part of a fixed-point implementation?", o: ["Deciding the expected range at every node in the path", "Choosing between rounding and truncation at each stage", "Selecting saturating rather than wrapping instructions", "Converting the coefficients from floating point"], a: 0, why: "Every gain, sum and accumulation changes the range, and the scaling strategy has to be planned end to end. Simulating with real data and recording the extremes at each node is how it is actually done." },
{ t: "dsp-fixed", d: 2, q: "Why round once at the end of a filter rather than after each tap?", o: ["Accumulated rounding error stays far smaller", "It avoids the saturation that per-tap rounding would cause", "The accumulator cannot hold the intermediate products otherwise", "Rounding per tap would break the filter's linear phase property"], a: 0, why: "A wide accumulator carries the full precision through all the products, so only one rounding error appears. Rounding each product would add N independent errors instead of one." },
{ t: "dsp-fixed", d: 2, q: "What does a guard bit in an accumulator provide?", o: ["Headroom for sums that temporarily exceed the output range", "Extra precision below the least significant bit", "Protection against a coefficient being loaded incorrectly", "A place to store the sign during a multiply-accumulate"], a: 0, why: "Intermediate sums in a filter can exceed the final output range even when the result does not. Guard bits let that happen without saturating, and the value comes back into range by the end." },
{ t: "dsp-fixed", d: 3, q: "Why is a floating-point unit not automatically the answer on a microcontroller?", o: ["Divides and transcendentals remain multi-cycle operations", "Floating point cannot represent the small values a filter needs", "The unit is unavailable inside an interrupt service routine", "Floating-point arithmetic is not deterministic in its timing"], a: 0, why: "Single-precision add and multiply are usually single cycle, but divide, square root and the transcendentals are not. Using floating point in an interrupt may also require extra context to be saved." },
{ t: "dsp-fixed", d: 2, q: "What does headroom mean in a fixed-point signal chain?", o: ["The margin between the working level and full scale", "The number of bits left unused at the bottom of the word", "The difference between the input and output word lengths", "The range of frequencies the filter passes without attenuation"], a: 0, why: "Peaks well above the RMS level need somewhere to go, and the amount depends on the crest factor of the signal. Too little and you clip; too much and you throw away signal to noise ratio." },
{ t: "dsp-fixed", d: 2, q: "Why can a fixed-point IIR filter oscillate with no input?", o: ["Rounding in the feedback path sustains a limit cycle", "The coefficients drift as the processor's temperature changes", "Fixed-point arithmetic cannot represent an exact zero", "The accumulator retains a residue from the previous block"], a: 0, why: "The rounding error is fed back and can settle into a repeating pattern of a few least significant bits. It is audible as a low-level tone and is fixed by dithering or by a different rounding rule." },
{ t: "dsp-fixed", d: 2, q: "What is the signal to noise ratio of an ideal N-bit fixed-point path?", o: ["About 6.02N plus 1.76 decibels", "Exactly six decibels for every bit, with no constant term", "Three decibels per bit, since power rather than amplitude doubles", "It depends only on the sample rate, not on the word length"], a: 0, why: "The constant comes from assuming a full-scale sine and uniform quantisation noise. Real paths fall short of it because the signal rarely uses the full range." },

// ----------------------------------------------------------- dsp-adaptive
{ t: "dsp-adaptive", d: 2, q: "What does the LMS algorithm actually compute?", o: ["A gradient descent step using the instantaneous error", "The exact least-squares solution over the whole data record", "The correlation between the input and the desired response", "A recursive estimate of the inverse input covariance matrix"], a: 0, why: "It uses the instantaneous gradient as a noisy estimate of the true one, which is what makes it so cheap. RLS estimates the inverse covariance and converges far faster at much greater cost." },
{ t: "dsp-adaptive", d: 2, q: "What happens if the LMS step size is too large?", o: ["The weights diverge or oscillate about the optimum", "Convergence becomes slower but remains stable throughout", "The filter converges to the wrong solution but stays bounded", "The adaptation stops entirely once the error becomes small"], a: 0, why: "Each update overshoots, and beyond a bound set by the input power the algorithm is unstable. That bound is why normalised LMS, which divides by the input power, is so widely used." },
{ t: "dsp-adaptive", d: 3, q: "What does normalised LMS fix?", o: ["Convergence that otherwise depends on the input signal level", "The bias in the weight estimate caused by correlated input", "The inability of LMS to track a time-varying system", "The excess error remaining once the filter has converged"], a: 0, why: "Dividing the step by the input power makes the effective step size independent of how loud the signal is. Without it, a stable step for quiet input diverges when the input gets louder." },
{ t: "dsp-adaptive", d: 2, q: "What does an acoustic echo canceller's adaptive filter estimate?", o: ["The loudspeaker to microphone impulse response", "The inverse of the room's transfer function", "The delay between the far and near ends", "The spectrum of the background noise in the room"], a: 0, why: "It models the path so the echo can be predicted and subtracted. When the path changes, because someone moves, the filter has to re-converge, which is why doubletalk detection matters." },
{ t: "dsp-adaptive", d: 2, q: "What does adaptive noise cancellation require?", o: ["A reference sensor carrying the noise but not the signal", "A signal that is periodic and therefore predictable", "Prior knowledge of the noise's frequency spectrum", "Two microphones placed exactly one wavelength apart"], a: 0, why: "The primary carries signal plus noise and the reference carries correlated noise alone, so the filter can learn the path between them. If the reference picks up signal too, the canceller removes the signal along with the noise." },
{ t: "dsp-adaptive", d: 3, q: "Why does eigenvalue spread of the input matter for LMS?", o: ["A large spread means some modes converge far more slowly", "It determines whether the filter can be stable at all", "It sets the minimum filter length required", "It fixes the residual error once the filter has converged"], a: 0, why: "Convergence along each eigenvector proceeds at a rate set by its eigenvalue, so a wide spread means the slowest mode dominates. RLS is insensitive to this, which is a large part of why it converges faster." },
{ t: "dsp-adaptive", d: 2, q: "What is misadjustment in an adaptive filter?", o: ["Excess steady-state error from the weights jittering", "The difference between the initial and final weight vectors", "A bias caused by the reference being correlated with the signal", "The error remaining because the filter is too short to model the path"], a: 0, why: "The weights never settle exactly; they wander around the optimum by an amount proportional to the step size. That is the classic trade: a larger step converges faster and leaves more residual error." },
{ t: "dsp-adaptive", d: 2, q: "Why does an adaptive filter need persistent excitation?", o: ["Without it the algorithm cannot distinguish parameter sets", "The step size would otherwise have to be reduced to zero", "The filter would converge to a solution that is not causal", "The error signal would not be available for the update"], a: 0, why: "A single tone cannot tell you the response at any other frequency, so the weights wander on noise. The input must be rich enough to identify every parameter you are trying to estimate." },
{ t: "dsp-adaptive", d: 2, q: "What does a leakage term in the LMS update do?", o: ["Pulls the weights gently toward zero, bounding their growth", "Increases the convergence rate when the error is large", "Removes the DC component from the input signal", "Compensates for the delay in the error measurement"], a: 0, why: "Without excitation the weights can drift to large values that are numerically dangerous. A small leak constrains them at the cost of a small bias in the converged solution." },
{ t: "dsp-adaptive", d: 2, q: "When is RLS worth its cost over LMS?", o: ["When fast convergence on coloured input matters", "When the filter must run on a processor without a multiplier", "When the input is white and the step size is hard to choose", "When the system being identified never changes with time"], a: 0, why: "RLS converges in about twice the filter length regardless of eigenvalue spread, which LMS cannot approach on coloured input. It costs order N squared per sample instead of order N." },

// ---------------------------------------------------------- dsp-detection
{ t: "dsp-detection", d: 2, q: "What does the Neyman-Pearson criterion state?", o: ["Maximise detection probability at a fixed false alarm rate", "Minimise the total number of errors of both kinds together", "Choose the threshold that equalises both errors", "Select the hypothesis with the higher prior probability"], a: 0, why: "It fixes the false alarm rate you can tolerate and then does as well as possible, which is implemented as a likelihood ratio test. It avoids needing prior probabilities you usually do not have." },
{ t: "dsp-detection", d: 2, q: "What does a receiver operating characteristic curve plot?", o: ["Detection probability against false alarm probability", "Signal to noise ratio against the achievable detection range", "The threshold value against the resulting error rate", "The distribution of the detector output under each hypothesis"], a: 0, why: "Each point on the curve is one threshold setting, so the curve summarises the detector independently of where you choose to operate. A detector on the diagonal is performing at chance." },
{ t: "dsp-detection", d: 3, q: "What does a constant false alarm rate detector do?", o: ["Sets its threshold from the local noise in nearby cells", "Fixes the threshold once at calibration", "Adapts the transmitted power to keep the return constant", "Applies a matched filter before every threshold comparison"], a: 0, why: "Estimating the noise from reference cells around the cell under test lets the threshold follow a varying background. A second strong target in the reference window raises the threshold and masks the first." },
{ t: "dsp-detection", d: 2, q: "Why is a matched filter the optimal detector in white noise?", o: ["It maximises output signal to noise ratio for a known shape", "It gives the narrowest possible peak in the time domain", "It removes the need to know the noise statistics at all", "It works for any signal shape, known or otherwise"], a: 0, why: "Correlating with the known waveform adds the signal coherently and the noise incoherently. In coloured noise you must whiten first, or the filter is no longer optimal." },
{ t: "dsp-detection", d: 2, q: "What does raising the detection threshold do?", o: ["Fewer false alarms and more missed detections", "Improves both error rates simultaneously", "Changes only the noise floor of the detector", "Increases the detector's resolution in time"], a: 0, why: "The two error types trade directly against each other, which is exactly what the operating characteristic curve shows. Only improving the signal to noise ratio moves the whole curve." },
{ t: "dsp-detection", d: 2, q: "Why does integration before detection help?", o: ["It raises the signal to noise ratio before the decision", "It reduces the number of decisions that must be made", "It removes the correlation between noise samples", "It compensates for the loss in the matched filter"], a: 0, why: "Coherent integration improves the ratio as M and incoherent as root M, so the threshold can be set relative to a much cleaner statistic. The cost is time resolution and, for coherent integration, a phase-stable signal." },
{ t: "dsp-detection", d: 3, q: "What is the difference between coherent and incoherent integration?", o: ["Coherent sums complex samples, incoherent sums magnitudes", "Coherent uses a matched filter, incoherent a threshold", "Coherent operates in frequency and incoherent in time", "Coherent requires two channels and incoherent only one"], a: 0, why: "Coherent addition needs phase alignment and gains a factor of M in power; incoherent throws phase away and gains only root M. Which is available depends on whether the signal stays phase-stable over the integration." },
{ t: "dsp-detection", d: 2, q: "What does an operating point on the diagonal of the curve mean?", o: ["The detector is performing no better than guessing", "The threshold has been set to its optimal value", "Both kinds of error are equally costly", "The signal to noise ratio is exactly zero decibels"], a: 0, why: "Detection probability equal to false alarm probability means the output carries no information about which hypothesis is true. No threshold choice will help; the detector or the signal has to change." },
{ t: "dsp-detection", d: 2, q: "Why is the envelope, rather than the raw signal, usually thresholded?", o: ["The carrier phase is unknown, so the peak position varies", "The envelope has a higher signal to noise ratio than the signal", "Thresholding the raw signal would require twice the sample rate", "The envelope removes the noise entirely from the measurement"], a: 0, why: "Without phase knowledge, the raw waveform crosses the threshold at a point that depends on the carrier phase. The envelope is phase-insensitive, at the cost of a small loss against a fully coherent detector." },
{ t: "dsp-detection", d: 2, q: "What does a low sensitivity with a high false alarm rate suggest?", o: ["The threshold is too low for the noise present", "The matched filter is correlating against the wrong shape", "The signal is absent from the data being processed", "The detector needs a longer integration time only"], a: 0, why: "Alarms far outnumbering real detections means the operating point is wrong, and nobody will act on the output. Either raise the threshold and accept fewer detections, or improve the signal to noise ratio first." },

// --------------------------------------------------------------- dsp-phase
{ t: "dsp-phase", d: 2, q: "What does the Hilbert transform do to a signal?", o: ["Shifts every frequency component by minus ninety degrees", "Removes the negative-frequency half of the spectrum entirely", "Converts the signal into its own frequency-domain representation", "Produces the envelope of the signal directly without further steps"], a: 0, why: "Magnitudes are unchanged and every component is rotated by a quarter cycle. Combining the original with its Hilbert transform gives the analytic signal, whose magnitude is the envelope." },
{ t: "dsp-phase", d: 2, q: "How is the envelope of a signal obtained from the analytic signal?", o: ["Take the magnitude of the complex analytic signal", "Lowpass filter the squared signal and take the square root", "Differentiate the phase and integrate the result", "Take the real part and rectify what remains"], a: 0, why: "The analytic signal is the original plus j times its Hilbert transform, and its modulus is the envelope. Its argument, differentiated, gives the instantaneous frequency." },
{ t: "dsp-phase", d: 3, q: "What is group delay?", o: ["The negative derivative of phase with respect to frequency", "The delay experienced by the carrier of a modulated signal", "The time taken for the filter's impulse response to decay", "The difference in delay between the first and last samples"], a: 0, why: "It is the delay applied to the envelope at that frequency, so a constant group delay preserves waveform shape. Phase delay, which is phase over frequency, is a different quantity and applies to the carrier." },
{ t: "dsp-phase", d: 2, q: "Why does phase unwrapping fail on a noisy signal?", o: ["A change of more than pi between samples is ambiguous", "The arctangent function is undefined at certain angles", "Noise shifts the signal outside the valid range", "Unwrapping requires the signal to be strictly bandlimited"], a: 0, why: "The algorithm assumes any jump larger than pi is a wrap, so a noisy step in the true phase is misread. Smoothing before unwrapping, or unwrapping along a different dimension, helps." },
{ t: "dsp-phase", d: 2, q: "What does instantaneous frequency mean?", o: ["The derivative of the analytic signal's phase", "The frequency of the strongest component in a short transform", "The reciprocal of the interval between successive zero crossings", "The centre of gravity of the signal's power spectrum"], a: 0, why: "It is defined from the analytic signal's argument and only has a clear meaning for a narrowband signal. For a multi-component signal it gives an average that may correspond to nothing present." },
{ t: "dsp-phase", d: 2, q: "Why is zero-phase filtering unavailable in real time?", o: ["The backward pass needs samples that have not arrived", "It requires twice the processing power of a forward pass", "The filter becomes unstable when run in reverse", "It only works on symmetric impulse responses"], a: 0, why: "Filtering backwards means starting at the end of the record, which does not exist yet. A linear-phase FIR gives constant delay in real time, which is the closest available substitute." },
{ t: "dsp-phase", d: 3, q: "What is the phase response of a minimum-phase filter?", o: ["The least phase lag of any filter with that magnitude", "Exactly linear across the whole of the passband", "Zero at every frequency in the passband", "The same as the corresponding maximum-phase filter"], a: 0, why: "For a given magnitude response, all zeros inside the unit circle gives the smallest possible phase lag and the smallest delay. It also makes the inverse stable, which matters for deconvolution." },
{ t: "dsp-phase", d: 2, q: "What does a constant phase offset between two channels indicate?", o: ["A fixed delay difference or a wiring inversion", "That one channel has a different sample rate", "A nonlinearity in one of the two signal paths", "That the two channels are measuring different quantities"], a: 0, why: "A pure delay gives a phase that grows linearly with frequency, while a constant offset across frequency suggests an inversion or a broadband phase shift. Distinguishing them means looking at the phase against frequency, not at one frequency." },
{ t: "dsp-phase", d: 2, q: "Why does phase matter for beamforming?", o: ["The array steers by the relative phase across elements", "Phase determines the amplitude weighting of each element", "The beam width is set by the oscillator's phase noise", "Phase errors change the frequency the array responds to"], a: 0, why: "Delaying or phase-shifting each element aligns the wavefront from a chosen direction so the contributions add. Phase errors across the aperture raise the sidelobes and blur the main lobe." },
{ t: "dsp-phase", d: 2, q: "What does an all-pass filter change?", o: ["Only the phase and group delay, never the magnitude", "Only the magnitude, leaving the phase untouched", "Both, but in a way that preserves the total energy", "Neither; it is a mathematical curiosity with no use"], a: 0, why: "Its poles and zeros are reflections in the unit circle, so the magnitude is flat everywhere. That makes it the standard tool for delay equalisation and for filter bank design." },

// ------------------------------------------------------------ dsp-realtime
{ t: "dsp-realtime", d: 2, q: "What is the real-time constraint for double-buffered block processing?", o: ["Worst-case block processing must finish before the other fills", "Average processing time must be below the block period", "The processor must be idle for half of every block period", "Each sample must be processed before the next one arrives"], a: 0, why: "It is the worst case that matters, because one late block loses data irrecoverably. Average timing tells you the load, not whether you will ever overrun." },
{ t: "dsp-realtime", d: 2, q: "What does increasing the block size trade?", o: ["Lower per-sample overhead against higher latency", "Better frequency resolution against worse timing accuracy", "Lower memory use against more processing per sample", "Higher throughput against reduced numerical precision"], a: 0, why: "Fixed per-block costs are amortised over more samples, so efficiency rises, but the output waits a whole block. In an interactive or control path the latency is usually what binds." },
{ t: "dsp-realtime", d: 3, q: "Why is dynamic memory allocation avoided in a real-time path?", o: ["Its timing is unbounded and it can fail after fragmentation", "It uses more memory than a statically allocated equivalent", "The allocator is not available inside an interrupt handler", "It prevents the compiler optimising nearby code"], a: 0, why: "malloc may take a lock, walk free lists or ask the kernel for pages, none of which is bounded. Allocating everything up front turns an unpredictable cost into a known one." },
{ t: "dsp-realtime", d: 2, q: "How do you actually measure worst-case execution time?", o: ["Toggle a GPIO and watch the widest pulse over a long run", "Count the instructions in the source and multiply by the clock", "Average the execution time over many thousands of blocks", "Read the cycle counter once and scale by the block size"], a: 0, why: "The worst case involves the most expensive branch, cache misses and any interrupt that preempts, none of which a static count captures. Watching on a scope with realistic input is what finds it." },
{ t: "dsp-realtime", d: 2, q: "What should you do when a buffer occasionally overruns?", o: ["Find and bound the worst-case path", "Increase the buffer size until the overruns stop", "Lower the sample rate until the load fits", "Move the processing into a lower-priority thread"], a: 0, why: "A bigger buffer delays the failure and adds latency without fixing anything. The overrun is telling you the worst case exceeds the budget, and that is what has to change." },
{ t: "dsp-realtime", d: 2, q: "Why does a cache make real-time analysis harder?", o: ["Execution time depends on what was accessed before", "The cache cannot be disabled on most processors", "Cached data may be stale when the DMA writes it", "It increases the average execution time"], a: 0, why: "A miss costs tens or hundreds of cycles, so the same code takes different times depending on history. Locking critical routines and data into cache, or using tightly coupled memory, restores predictability." },
{ t: "dsp-realtime", d: 3, q: "What does DMA buy in a sampled system?", o: ["Data moves without the processor servicing every sample", "The conversion happens at a more precisely controlled instant", "The processor can run at a lower clock frequency", "Cache coherency is maintained automatically by hardware"], a: 0, why: "One interrupt per block instead of one per sample removes an enormous overhead and its jitter. Cache coherency is precisely the thing DMA does not give you for free." },
{ t: "dsp-realtime", d: 2, q: "Why must a buffer written by DMA be handled carefully with a cache?", o: ["The processor may read a stale cached copy", "The DMA controller cannot address cached memory", "The buffer must be aligned to the cache line size", "DMA writes are slower than processor writes"], a: 0, why: "The DMA writes to memory behind the cache's back, so the cached copy predates it. Invalidating the range before reading, or placing the buffer in non-cached memory, is the fix." },
{ t: "dsp-realtime", d: 2, q: "What determines the latency of a filter in a real-time path?", o: ["The block size plus the filter's own group delay", "The sample rate alone, since each sample is processed in turn", "The number of coefficients divided by the processor speed", "The interrupt priority assigned to the processing routine"], a: 0, why: "Block buffering and the filter's delay add, and for a linear-phase FIR the filter contributes half its length. Reducing either costs efficiency or filter sharpness respectively." },
{ t: "dsp-realtime", d: 2, q: "Why should the processing load be measured under realistic input?", o: ["Branch and data-dependent paths only appear with real data", "The compiler optimises differently for synthetic signals", "Real input has a higher sample rate than test signals", "Synthetic input cannot exercise the floating-point unit"], a: 0, why: "Silence or a pure tone may never take the expensive branch, so the measured load is optimistic. Feeding recorded field data is the cheapest way to find the real worst case." },

]);
