// A second pass over every C++ lesson: ten more questions each.
//
// Topic tags are lesson ids, so topicLesson() resolves them by the byId
// fallback and no TOPIC_LESSON entry is needed.
//
// Options are written to a similar length within each question. The correct
// one is deliberately the longest in only about a quarter of them, which is
// chance, so neither "pick the longest" nor "avoid the longest" pays.
BANKS["C++"] = BANKS["C++"].concat([

// ------------------------------------------------------------------- raii
{ t: "raii", d: 1, q: "RAII ties the lifetime of a resource to what?", o: ["The lifetime of an automatic object", "An explicit call to a release function", "The end of the enclosing function body", "The point where the last reference dies"], a: 0, why: "Acquisition happens in the constructor and release in the destructor, so the resource follows an object with automatic storage duration. The compiler then runs the release for you on every exit path, including a throw." },
{ t: "raii", d: 2, q: "Why must a destructor not let an exception escape?", o: ["Destructors run too late to report it", "It would leak the object being destroyed", "During unwinding it calls std::terminate", "The compiler rejects any throwing dtor"], a: 2, why: "If a destructor throws while the stack is already unwinding from another exception, there are two live exceptions and the runtime calls std::terminate. Since C++11 destructors are noexcept by default, which makes this explicit." },
{ t: "raii", d: 2, q: "A constructor throws halfway through. What happens to the members already built?", o: ["They leak, since the object never existed", "They are destroyed, in reverse order", "Only members with a destructor are freed", "Nothing runs until the object is complete"], a: 1, why: "Fully-constructed subobjects are destroyed in reverse order of construction. The object's own destructor does not run, because the object was never fully constructed, which is exactly why raw owning pointers as members are unsafe." },
{ t: "raii", d: 1, q: "What is the rule of zero?", o: ["Write no constructors at all in a class", "Never allocate anything on the free store in the class", "Let members own, so you write no special functions", "Zero-initialise every member you declare"], a: 2, why: "If each member manages its own resource, the compiler-generated copy, move and destructor are all correct, so you write none of them. Writing one of the five usually means you should have written a member type instead." },
{ t: "raii", d: 2, q: "Why prefer std::make_unique over unique_ptr with a bare new?", o: ["It is measurably faster at runtime", "It names the type only once and is exception safe", "Only make_unique supports custom deleters", "It allocates the control block and the object together"], a: 1, why: "It avoids repeating the type and closes the old argument-evaluation-order leak. Allocating the object and control block together is make_shared's property, not make_unique's, since unique_ptr has no control block." },
{ t: "raii", d: 2, q: "What does std::lock_guard guarantee that a bare lock() and unlock() pair does not?", o: ["The mutex is released on every exit path", "That no other thread can take the mutex", "A strictly fairer ordering between waiters", "Detection of a deadlock before it happens"], a: 0, why: "An early return, a break or a throw between lock and unlock leaks the lock. lock_guard releases in its destructor, so every path out of the scope is covered without you enumerating them." },
{ t: "raii", d: 3, q: "You must run cleanup code that is not a resource release, on every exit path. What is the idiom?", o: ["A try/catch block wrapping the whole function body", "A goto to a shared label at the end", "A small guard object whose destructor runs it", "Repeat the cleanup before each return"], a: 2, why: "Wrap the action in a type whose destructor invokes it, the scope-guard idiom. It composes, survives exceptions, and unlike try/catch it also covers the ordinary return paths." },
{ t: "raii", d: 2, q: "Why is a raw owning pointer stored as a member a design smell?", o: ["Raw pointers are slower to dereference", "It forces you to write all five special functions", "Raw pointers simply cannot be null-checked safely at all", "The compiler will warn on every use of it"], a: 1, why: "The compiler-generated copy would double-free and the generated destructor would leak, so you must supply destructor, copy and move yourself. Holding a unique_ptr instead gets all five right for free." },
{ t: "raii", d: 3, q: "A unique_ptr with a custom deleter is used to close a file descriptor. What does the deleter's type affect?", o: ["Nothing; the deleter is always type-erased", "The size of the unique_ptr object itself", "Whether the pointer can be moved at all", "The order in which members are destroyed"], a: 1, why: "unique_ptr stores the deleter, so a stateful or function-pointer deleter grows the object. A stateless lambda or empty struct costs nothing. shared_ptr is the one that type-erases its deleter, at the cost of a control block." },
{ t: "raii", d: 2, q: "What is the main reason RAII matters more in C++ than in a garbage-collected language?", o: ["C++ has no exceptions to unwind through", "Destruction is deterministic and immediate", "The heap is much smaller in C++ programs", "Garbage collectors cannot free memory at all"], a: 1, why: "A collector reclaims memory eventually and says nothing about sockets, locks or file handles. C++ destroys at a known point, so scope can carry any resource, not just memory." },

// ------------------------------------------------------------------- move
{ t: "move", d: 1, q: "What does std::move actually do?", o: ["It moves the object's data immediately", "It casts its argument to an rvalue reference", "It marks the source as invalid for later use", "It swaps the source and destination values"], a: 1, why: "It is a cast and nothing else. Whether anything is moved depends on which overload the cast selects, so std::move on a const object silently gives you a copy." },
{ t: "move", d: 2, q: "What state is a moved-from standard library object left in?", o: ["Exactly the state it had before the move", "Unspecified, but valid and destructible", "Undefined, so touching it is a hard error", "Always empty, for every standard type"], a: 1, why: "You may destroy it or assign to it, but you may not assume its value. Containers happen to be left empty in practice, and relying on that is a portability bug waiting to happen." },
{ t: "move", d: 2, q: "Why should a move constructor be marked noexcept?", o: ["The compiler refuses to move without it", "Otherwise vector reallocation falls back to copying", "It removes the need for writing a move assignment as well", "noexcept makes the move itself run faster"], a: 1, why: "vector must give the strong guarantee on reallocation, so it only moves when the move cannot throw. A throwing move quietly turns every growth into a full copy of every element." },
{ t: "move", d: 2, q: "Inside a function taking T&& x, what is x itself?", o: ["An rvalue, because of the && in the type", "An lvalue, because it is a named variable", "A prvalue until it is first used", "Neither, since references have no category"], a: 1, why: "A named rvalue reference is an lvalue, which is why you must std::move or std::forward it to pass the rvalue-ness on. Forgetting this is the commonest source of an accidental copy." },
{ t: "move", d: 3, q: "What distinguishes std::forward from std::move?", o: ["forward casts only when the argument was an rvalue", "forward works on const objects, whereas move does not", "forward moves, while move only marks", "There is no difference in generated code"], a: 0, why: "forward is a conditional cast driven by the deduced template parameter, so an lvalue argument stays an lvalue. move is unconditional, which is why using it in a forwarding wrapper silently steals the caller's object." },
{ t: "move", d: 2, q: "Why does returning a local object by value not need std::move?", o: ["Return values are always copied anyway", "It would block copy elision and cost more", "The compiler rewrites move into copy there", "Locals cannot be moved from at all"], a: 1, why: "The return is already treated as an rvalue and is usually elided entirely. Writing std::move on it turns a guaranteed elision into an actual move, which is slower, not faster." },
{ t: "move", d: 3, q: "What does T&& mean when T is a deduced template parameter?", o: ["An rvalue reference, exactly as it is everywhere else", "A forwarding reference, binding to either category", "A const reference chosen by the compiler", "An error, since T cannot be deduced there"], a: 1, why: "In a deduced context reference collapsing makes T&& bind to lvalues and rvalues alike. That is why it pairs with std::forward, and why auto&& behaves the same way." },
{ t: "move", d: 2, q: "You declare a destructor. What happens to the implicit move operations?", o: ["They are generated exactly as before", "They are not generated, so copies happen", "They are generated but marked deleted", "The whole class becomes non-copyable as well"], a: 1, why: "Declaring a destructor suppresses the implicit move constructor and move assignment. Copy is still generated for compatibility, so the class silently gets slower rather than failing to compile." },
{ t: "move", d: 2, q: "When is passing a parameter by value and then moving it a good choice?", o: ["Whenever the parameter is larger than a word", "When the function stores a copy either way", "Only for types with no move constructor", "Never; a const reference is always better"], a: 1, why: "If you are going to keep a copy anyway, by-value plus move costs one move for an rvalue caller and one copy plus one move for an lvalue caller. Where you do not keep it, a const reference is still cheaper." },
{ t: "move", d: 3, q: "Why can a move constructor not simply be a memcpy for most types?", o: ["memcpy is undefined in C++ entirely", "The source must be left destructible", "Alignment rules forbid it for classes", "Move must copy, so memcpy is too fast"], a: 1, why: "After a memcpy both objects own the same pointer and both destructors run. A move must also null out or otherwise neutralise the source, which is the part memcpy cannot do." },

// -------------------------------------------------------------------- stl
{ t: "stl", d: 1, q: "What does std::vector guarantee about the storage of its elements?", o: ["They are contiguous in one allocation", "Each element sits in its own node", "Elements never move once inserted", "Storage is allocated one element at a time"], a: 0, why: "Contiguity is why vector is cache-friendly and why you may pass data() to a C API. It is also why insertion in the middle is linear and why growth invalidates every iterator." },
{ t: "stl", d: 2, q: "Which container operation invalidates references to existing elements?", o: ["push_back on a deque", "insert somewhere in the middle of a list", "push_back on a vector that reallocates", "erase at the end of a vector"], a: 2, why: "Reallocation moves every element to new storage, so all pointers, references and iterators dangle. deque keeps references valid on end insertion, and list keeps them valid always." },
{ t: "stl", d: 2, q: "What is the difference between reserve and resize on a vector?", o: ["reserve allocates only, resize creates elements", "resize allocates only, reserve creates elements", "They are the same call with different names", "reserve shrinks, while resize only grows"], a: 0, why: "reserve changes capacity and leaves size alone, so no element is constructed. resize changes size, constructing or destroying elements, which is why reserve then push_back is the pattern for filling a known count." },
{ t: "stl", d: 2, q: "Why is std::map's lookup logarithmic rather than constant?", o: ["It hashes the key on every access", "It is a balanced tree ordered by key", "It scans the keys linearly from the root", "It caches only the most recent lookups"], a: 1, why: "map is a node-based ordered tree, so lookup is a sequence of comparisons down its depth. unordered_map hashes and is constant on average, at the cost of losing key order and cache locality." },
{ t: "stl", d: 3, q: "What does the erase-remove idiom actually do?", o: ["remove frees, and then erase resizes the whole container", "remove shuffles kept elements forward, erase trims", "erase removes and remove reclaims capacity", "Both are needed only for node-based containers"], a: 1, why: "std::remove cannot change a container's size, so it compacts the survivors and returns the new logical end. erase then drops the tail. C++20's std::erase does both in one call." },
{ t: "stl", d: 2, q: "What does emplace_back do that push_back does not?", o: ["It constructs the element in place from arguments", "It guarantees no reallocation will occur", "It appends without checking the capacity", "It is the only way to append a move-only type at all"], a: 0, why: "It forwards its arguments to the element's constructor, avoiding a temporary. Move-only types work fine with push_back given an rvalue, and neither call can avoid reallocation." },
{ t: "stl", d: 2, q: "Why does std::array differ from a raw C array in practice?", o: ["It stores its elements on the free store", "It knows its size and does not decay", "It can change size after construction", "It bounds-checks every element access"], a: 1, why: "It is the same storage with a real type, so size() works and it does not decay to a pointer when passed. Only at() bounds-checks; operator[] is as unchecked as the raw array." },
{ t: "stl", d: 3, q: "What is the practical cost of std::list compared with std::vector?", o: ["Insertion in the middle is far slower", "One allocation and a cache miss per element", "It cannot hold types without a default constructor", "Iteration over it is not possible at all"], a: 1, why: "Each node is a separate allocation and pointer chase, so traversal defeats the prefetcher. That usually outweighs its O(1) middle insertion, which is why vector wins on real hardware more often than the complexity table suggests." },
{ t: "stl", d: 2, q: "What does a std::span give you over passing a pointer and a length?", o: ["It owns and frees the underlying storage", "One parameter that keeps the two in step", "Automatic bounds checking on every access", "A guarantee that the data is contiguous heap"], a: 1, why: "It bundles pointer and extent so they cannot disagree, and it is non-owning, so lifetime is still yours to manage. Checking is not automatic outside a hardened standard library." },
{ t: "stl", d: 2, q: "Why does std::unordered_map degrade when the hash is poor?", o: ["It rehashes on every single insertion", "Keys pile into few buckets, so lookup is linear", "The container silently drops all the colliding keys", "It falls back to a tree in every case"], a: 1, why: "A bucket is a list, so clustering turns constant lookup into a scan. Some libraries convert a heavily loaded bucket to a tree, but that is a mitigation rather than the standard behaviour." },

// ----------------------------------------------------------------- threads
{ t: "threads", d: 1, q: "What must happen to a std::thread before its destructor runs?", o: ["It must be joined or detached", "It must have finished its function", "It must be assigned to another thread", "Its stack must be freed manually"], a: 0, why: "A joinable thread destructed without join or detach calls std::terminate. std::jthread in C++20 joins in its own destructor, which is the RAII answer to exactly this footgun." },
{ t: "threads", d: 2, q: "Two threads read the same non-atomic variable while a third writes it. What is that?", o: ["Safe, because reads cannot conflict", "A data race, and therefore undefined behaviour", "Safe if the variable is a machine-word sized one", "A benign race that the compiler resolves"], a: 1, why: "Any unsynchronised access where at least one is a write is a data race, with no exception for word-sized types. The compiler may assume races do not happen and optimise accordingly." },
{ t: "threads", d: 2, q: "Why must a condition_variable wait be given a predicate?", o: ["To choose which waiting thread wakes up", "To cope with spurious and stale wakeups", "The API refuses to compile without one", "To decide how long the wait should last"], a: 1, why: "A wait can return without a notification, and the condition may also have changed back before you run. The predicate loop rechecks the actual state, which is the only thing that is authoritative." },
{ t: "threads", d: 2, q: "What does std::atomic guarantee that volatile does not?", o: ["That the variable lives in main memory", "Atomicity and a defined ordering between threads", "That the compiler will not cache it in a register", "Immunity from compiler optimisation entirely"], a: 1, why: "volatile only constrains the compiler's elision of accesses; it says nothing about other cores or about tearing. atomic gives indivisible access plus the memory ordering the model needs." },
{ t: "threads", d: 3, q: "What is the practical consequence of memory_order_relaxed?", o: ["The operation may be reordered around others", "The variable is then no longer atomic in any way", "Only one thread may touch it at a time", "It disables the cache on that address"], a: 0, why: "The read or write is still indivisible, but nothing is ordered relative to other memory operations. It suits a counter whose value you read later, and not a flag that publishes other data." },
{ t: "threads", d: 2, q: "Why does locking two mutexes in different orders in different threads deadlock?", o: ["The mutexes fail to release on scope exit", "Each holds one and waits for the other", "A mutex cannot be held by two threads", "Recursive locking is undefined behaviour"], a: 1, why: "That is circular wait, one of Coffman's four conditions. Fix it by imposing a global lock order, or by taking both at once with std::scoped_lock, which uses a deadlock-avoiding algorithm." },
{ t: "threads", d: 2, q: "What does std::async with the default launch policy actually promise?", o: ["It always starts a new thread immediately", "It may run on a new thread or lazily on get", "It runs on a thread pool sized to the cores", "It runs the work synchronously before returning"], a: 1, why: "The default is async or deferred at the implementation's choice, so work may not start until you call get. Pass std::launch::async explicitly when you actually want concurrency." },
{ t: "threads", d: 3, q: "A future returned by std::async is not stored. What happens?", o: ["The task is silently cancelled", "Its destructor blocks until the task finishes", "The task runs detached in the background instead", "The behaviour is undefined at runtime"], a: 1, why: "The temporary future is destroyed at the end of the full expression, and that destructor waits. The apparently asynchronous call therefore runs synchronously, which is a classic surprise in a loop." },
{ t: "threads", d: 2, q: "Why is a spin lock usually wrong on a general-purpose operating system?", o: ["Spinning is forbidden by the C++ standard", "A descheduled holder makes waiters burn a slice", "Spin locks cannot protect more than one word", "Atomic operations are unavailable in userspace"], a: 1, why: "If the owner loses the CPU, every spinner wastes its whole quantum waiting for a thread that is not running. Spinning pays only when the critical section is shorter than a context switch and preemption is bounded." },
{ t: "threads", d: 2, q: "What is false sharing?", o: ["Two threads writing the same variable", "Two variables sharing one cache line", "A lock protecting the wrong data", "Sharing a pointer without ownership"], a: 1, why: "The variables are independent but the line is not, so each write invalidates the other core's copy. Padding or aligning to hardware_destructive_interference_size separates them." },

// ------------------------------------------------------------- cpp-classes
{ t: "cpp-classes", d: 1, q: "What does a virtual destructor in a base class ensure?", o: ["Derived objects can be copied safely", "delete through a base pointer runs the full chain", "The class can no longer be instantiated directly at all", "Every member function becomes virtual too"], a: 1, why: "Without it, deleting a derived object through a base pointer is undefined and typically skips the derived destructor. Any class you intend to delete polymorphically needs one." },
{ t: "cpp-classes", d: 2, q: "What is object slicing?", o: ["Splitting up a class across several header files", "Copying a derived object into a base by value", "Removing unused members at link time", "Truncating a member during narrowing"], a: 1, why: "The base copy constructor copies only the base subobject, so the derived part is discarded and virtual dispatch is lost. Passing by reference or pointer avoids it." },
{ t: "cpp-classes", d: 2, q: "Why does calling a virtual function from a constructor not dispatch to the override?", o: ["Constructors cannot call member functions", "The dynamic type is still the base at that point", "The vtable pointer is only ever set upon first use", "Overrides are resolved at link time only"], a: 1, why: "The object becomes its derived type only once the derived constructor body starts, so the base constructor sees the base vtable. That is deliberate: the derived members are not initialised yet." },
{ t: "cpp-classes", d: 2, q: "What does the override keyword buy you?", o: ["It makes a non-virtual function virtual", "A compile error when nothing is overridden", "Faster dispatch than a plain override", "It prevents further overriding downstream"], a: 1, why: "It fails to compile if the signature does not match a base virtual, catching a wrong const, a wrong parameter type or a missing base virtual. final is the keyword that stops further overriding." },
{ t: "cpp-classes", d: 3, q: "In what order are members initialised?", o: ["In the order of the initialiser list", "In declaration order in the class", "Alphabetically by member name", "Base classes last, then members"], a: 1, why: "Declaration order always wins, whatever order you write the initialiser list in. Writing the list out of order earns a warning precisely because it looks like it should matter." },
{ t: "cpp-classes", d: 2, q: "What does marking a single-argument constructor explicit prevent?", o: ["Implicit conversion from the argument type", "The constructor from ever being called at all", "Copy construction of the same type", "Aggregate initialisation with braces"], a: 0, why: "It stops the compiler silently converting an int, or a string, into your type at a call site. That silent conversion is how an overload set picks a surprising candidate." },
{ t: "cpp-classes", d: 2, q: "Why is a protected member often worse than a private one?", o: ["Protected access is slower at runtime", "It exposes the invariant to every subclass", "Protected members cannot be initialised", "The compiler cannot inline access to them"], a: 1, why: "Every present and future derived class becomes part of the class's interface, so the invariant is no longer yours alone to maintain. A protected accessor is usually the smaller commitment." },
{ t: "cpp-classes", d: 3, q: "What is the non-virtual interface idiom?", o: ["Making every member function non-virtual", "A public non-virtual wrapper over a private virtual", "Replacing inheritance with free functions", "Declaring the whole interface without any methods at all"], a: 1, why: "The public function is fixed and can enforce pre- and post-conditions, while the customisation point below it is private and virtual. It separates what callers see from what subclasses change." },
{ t: "cpp-classes", d: 2, q: "What does = default on a copy constructor mean?", o: ["Copying is forbidden for this whole class", "Ask for the compiler-generated version", "Copy is deferred until first use", "The copy is a shallow memcpy"], a: 1, why: "You get the implicit definition even though declaring other special functions would have suppressed it. = delete is the one that forbids the operation." },
{ t: "cpp-classes", d: 2, q: "What is the cost of adding the first virtual function to a class?", o: ["Every member call becomes indirect", "One vtable pointer per object", "The class can no longer be copied", "All members must become virtual"], a: 1, why: "Each object grows by a pointer and the type gains a vtable, which matters for a small type held in a large array. Only calls through a base reference or pointer actually go indirect." },

// ----------------------------------------------------------- cpp-templates
{ t: "cpp-templates", d: 1, q: "When is a function template's body checked for errors involving its parameters?", o: ["When the template is first parsed", "When it is instantiated with a type", "At link time, once per translation unit", "Only when the program is run"], a: 1, why: "Two-phase lookup checks non-dependent constructs at definition, but anything depending on the template parameter waits for instantiation. That is why an unused template can hide a type error indefinitely." },
{ t: "cpp-templates", d: 2, q: "Why does a template definition usually live in a header?", o: ["Templates cannot be compiled at all", "The compiler needs the body to instantiate it", "Headers make template code faster", "The linker simply cannot see any template symbols"], a: 1, why: "Instantiation happens where the template is used, so that translation unit must see the body. Explicit instantiation in one source file is the escape hatch when you want to keep it out of the header." },
{ t: "cpp-templates", d: 2, q: "What does typename do in typename T::value_type?", o: ["Declares a new template parameter", "Says the dependent name is a type", "Restricts T to standard containers", "Forces the compiler to deduce T"], a: 1, why: "Without it the compiler assumes a dependent qualified name is a value, and the parse fails. C++20 removed the need in many contexts, but the rule is still worth knowing." },
{ t: "cpp-templates", d: 3, q: "What is SFINAE?", o: ["A failed substitution removes an overload quietly", "Templates never fail to substitute at all", "A rule that forbids partial specialisation", "An optimisation that inlines every template call made"], a: 0, why: "If substituting the deduced arguments produces an invalid type in the signature, that candidate is dropped rather than raising an error. Concepts express the same intent far more readably." },
{ t: "cpp-templates", d: 2, q: "What advantage do concepts have over enable_if?", o: ["They run checks at run time instead", "Readable constraints and far better errors", "They allow templates in source files", "They remove the need for instantiation entirely"], a: 1, why: "The constraint is stated positively and named, so a failure says which requirement was not met instead of dumping a substitution trace. They also participate in overload ordering by subsumption." },
{ t: "cpp-templates", d: 2, q: "Why can a template cause code bloat?", o: ["Each distinct type gets its own instantiation", "Templates disable inlining completely", "The compiler emits the body twice per use", "Every instantiation carries a vtable of its own"], a: 0, why: "Ten container element types mean ten copies of every function you use. Hoisting the type-independent part into a non-template base is the standard mitigation." },
{ t: "cpp-templates", d: 3, q: "What does a variadic template pack expansion do?", o: ["Repeats a pattern once per pack element", "Converts the pack into a std::vector", "Requires all arguments to share a type", "Limits the pack to sixteen arguments"], a: 0, why: "Writing f(args)... applies the pattern to each element in turn. Fold expressions in C++17 make the common reductions, such as summing or logical and, far shorter to write." },
{ t: "cpp-templates", d: 2, q: "What is the difference between a class template's full and partial specialisation?", o: ["Full fixes every parameter, partial only some", "Partial is for functions, full for classes", "Full is chosen at run time, partial at compile", "There is no difference in behaviour"], a: 0, why: "Full specialisation names concrete arguments for all parameters; partial leaves some free and constrains the rest. Function templates cannot be partially specialised, which is why overloading is used instead." },
{ t: "cpp-templates", d: 2, q: "What does if constexpr give you that a plain if does not?", o: ["A faster branch at run time", "The discarded branch is not instantiated", "Evaluation of the condition at link time", "Support for conditions on runtime values"], a: 1, why: "Only the taken branch is compiled for that instantiation, so the other may contain code that would be invalid for the type. That replaces a great deal of tag dispatch and specialisation." },
{ t: "cpp-templates", d: 3, q: "Why does template argument deduction ignore the return type?", o: ["Return types are erased before deduction", "There is no argument to deduce it from", "The standard forbids deducing any return", "Return types are always deduced as auto"], a: 1, why: "Deduction works from the call's arguments, and the return type appears in no argument. That is why factory-style functions take an explicit template argument or return auto." },

// -------------------------------------------------------------- cpp-memory
{ t: "cpp-memory", d: 1, q: "What does a shared_ptr's control block hold?", o: ["Only the pointer to the managed object", "Strong and weak counts, and the deleter", "A copy of the object being managed", "The allocation size of the object"], a: 1, why: "It holds the reference counts plus the type-erased deleter and allocator. That is why a shared_ptr is two pointers wide and why make_shared, which fuses object and block, saves an allocation." },
{ t: "cpp-memory", d: 2, q: "What problem does weak_ptr solve?", o: ["It makes shared_ptr copies cheaper", "It breaks a reference cycle between owners", "It allows sharing across processes", "It removes the need for a control block at all"], a: 1, why: "Two objects holding shared_ptr to each other never reach zero. Making one direction weak lets the cycle die, and lock() gives you a safe temporary shared_ptr when the object is still alive." },
{ t: "cpp-memory", d: 2, q: "Why must you not build two shared_ptr from the same raw pointer?", o: ["The second construction fails to compile", "Two control blocks mean a double free", "Only one shared_ptr may exist per type", "The counts merge and leak the object"], a: 1, why: "Each gets its own count, so each reaches zero independently and deletes. Copy the existing shared_ptr instead, or use enable_shared_from_this when only the raw pointer is in hand." },
{ t: "cpp-memory", d: 3, q: "What does placement new do?", o: ["Allocates from a thread-local pool", "Constructs an object in storage you supply", "Registers the object for later destruction", "Moves an existing object to new storage"], a: 1, why: "It runs the constructor at an address you provide and allocates nothing. You must then call the destructor explicitly, since no matching delete exists, which is how containers manage raw buffers." },
{ t: "cpp-memory", d: 2, q: "Why is delete on a pointer obtained from new[] wrong?", o: ["The array length is stored elsewhere", "It destroys one element and mismatches the pair", "It frees the memory but leaks every one of the objects", "delete refuses to accept array pointers"], a: 1, why: "new[] and delete[] are a matched pair that may use different bookkeeping, so mixing them is undefined. In practice you avoid the question entirely by using vector or unique_ptr of an array type." },
{ t: "cpp-memory", d: 2, q: "What does alignas do?", o: ["Pads the type to a power of two", "Requires a minimum alignment for the type", "Packs the members with no padding", "Aligns the object to a cache line always"], a: 1, why: "It raises the alignment requirement, which matters for SIMD types and for avoiding false sharing. Packing is the opposite request and is spelled with a compiler attribute, not alignas." },
{ t: "cpp-memory", d: 3, q: "Why does a custom allocator matter in a real-time system?", o: ["It makes allocation measurably faster", "The general heap has unbounded latency", "The standard heap is not thread safe", "Custom allocators avoid fragmentation entirely"], a: 1, why: "malloc may take a lock, walk free lists or ask the kernel for pages, and none of that is bounded. A pool or arena gives a fixed cost, which is what a deadline needs; fragmentation still has to be designed out." },
{ t: "cpp-memory", d: 2, q: "What is the practical difference between the stack and the free store?", o: ["Stack objects live until you free them", "Stack size is fixed and known in advance", "The free store is faster to allocate from", "Only the free store can hold class types"], a: 1, why: "The stack is a bounded region that unwinds automatically, which is why a large local array or deep recursion overflows it. The free store is large and flexible, and costs a call plus bookkeeping." },
{ t: "cpp-memory", d: 2, q: "Why can std::vector's growth still be a problem in embedded code?", o: ["It allocates on every push_back", "Reallocation is unpredictable in time", "It cannot use a custom allocator", "Its elements are never contiguous at all"], a: 1, why: "Growth copies or moves every element and touches the allocator, so the cost spikes unpredictably. reserve up front, or a fixed-capacity container, keeps the timing flat." },
{ t: "cpp-memory", d: 3, q: "What does std::launder exist for?", o: ["To zero memory before reuse", "To get a usable pointer after reusing storage", "To flush the cache line for one particular address", "To detect use-after-free at run time"], a: 1, why: "When you construct a new object in the storage of an old one, the old pointer may not legally refer to the new object. launder gives you a pointer the optimiser must treat as fresh." },

// ------------------------------------------------------------ cpp-embedded
{ t: "cpp-embedded", d: 2, q: "What is the main runtime cost of enabling exceptions on a small MCU?", o: ["Every function call becomes slower", "Unwind tables enlarge the binary considerably", "Interrupts must all be disabled while it throws", "The heap is required for every throw"], a: 1, why: "The tables and personality routine dominate, and the throw path itself needs an allocation. On a happy path a zero-cost implementation adds nothing, which is why the argument is usually about flash, not speed." },
{ t: "cpp-embedded", d: 2, q: "Why is a global object with a non-trivial constructor risky in firmware?", o: ["Its constructor runs before main, unordered", "Globals cannot have constructors at all", "It is placed in flash and cannot be written", "The linker removes it if it is unused"], a: 0, why: "Initialisation order across translation units is unspecified, so one global may use another before it is built. A function-local static, constructed on first use, removes the ordering question." },
{ t: "cpp-embedded", d: 2, q: "What does constexpr buy you in embedded C++?", o: ["Faster arithmetic at run time", "Values computed at compile time into flash", "Automatic use of the FPU wherever one is present", "Smaller stack frames in every function"], a: 1, why: "A table or a checked constant is folded during compilation, so it costs no startup time and no RAM. It also lets you assert on the value at compile time rather than discovering it in the field." },
{ t: "cpp-embedded", d: 3, q: "Why might you disable RTTI in a firmware build?", o: ["Virtual dispatch stops working entirely without it", "It pulls in type-info tables and name strings", "Templates cannot be instantiated with it", "It forces every class to gain a vtable"], a: 1, why: "The type descriptors and their mangled names cost flash, and dynamic_cast pulls in a runtime routine. Virtual dispatch itself does not need RTTI, so ordinary polymorphism still works." },
{ t: "cpp-embedded", d: 2, q: "What is the safest way to model a hardware register in C++?", o: ["A plain int at a hard-coded address", "A volatile member in a struct at that address", "A constexpr value initialised from the address", "A reference bound to the address once"], a: 1, why: "volatile stops the compiler eliding or reordering the accesses it can see, and the struct gives the layout a name. It is still not atomic and says nothing about other bus masters." },
{ t: "cpp-embedded", d: 2, q: "Why prefer a scoped enum over a plain enum for register fields?", o: ["Scoped enums are stored in fewer bits", "No implicit conversion to int, and no name clash", "Only scoped enums may be given an underlying type at all", "Scoped enums can be used in switch statements"], a: 1, why: "The values do not leak into the enclosing scope and will not silently become an int in arithmetic. Both kinds can fix an underlying type since C++11, and both work in a switch." },
{ t: "cpp-embedded", d: 3, q: "What does a std::array of function pointers give you over a switch?", o: ["Constant dispatch time regardless of cases", "Smaller code in every possible case", "Compile-time checking of every single handler", "Automatic bounds checking on the index"], a: 0, why: "One indexed load and an indirect call, whatever the case count, which suits a state machine with a deadline. A dense switch often compiles to a jump table anyway, so measure before assuming." },
{ t: "cpp-embedded", d: 2, q: "Why is dynamic_cast usually avoided in hard real-time code?", o: ["It cannot cross a virtual base", "Its cost depends on the hierarchy walked", "It always allocates from the heap", "It is undefined without exceptions enabled"], a: 1, why: "The traversal is not constant and not easy to bound, which is what a deadline needs. A tag in the object, or a virtual function, gives the same answer in fixed time." },
{ t: "cpp-embedded", d: 2, q: "What does -ffunction-sections with --gc-sections achieve?", o: ["It inlines every small function that it finds", "Unused functions are dropped at link time", "It moves all functions into RAM", "It compresses the code segment"], a: 1, why: "Each function gets its own section so the linker can discard the ones nothing references. Without it, one used symbol drags in the whole object file." },
{ t: "cpp-embedded", d: 3, q: "Why is a virtual function in an ISR-called class worth a second look?", o: ["Virtual calls cannot occur in an ISR", "It costs an indirect call and blocks inlining", "The vtable lives in RAM and may be corrupt", "Interrupts disable virtual dispatch entirely"], a: 1, why: "The compiler usually cannot see through it, so the call is a load and a jump with no inlining and less predictable timing. Where the type is known, making the call non-virtual or final restores the optimisation." },

// -------------------------------------------------------------- cpp-errors
{ t: "cpp-errors", d: 2, q: "What does the strong exception guarantee promise?", o: ["The function is marked noexcept", "The operation completes or changes nothing", "No memory is leaked by the failure", "Errors are reported through a return code"], a: 1, why: "It is transactional: on a throw the observable state is as it was. The usual implementation is copy-and-swap, doing the work on a copy and swapping in only once it cannot fail." },
{ t: "cpp-errors", d: 2, q: "What happens when an exception escapes a noexcept function?", o: ["It propagates to the caller as usual", "std::terminate is called immediately", "The compiler converts it to a return code", "The function retries once, then rethrows"], a: 1, why: "noexcept is a promise, not a filter, and breaking it ends the program rather than unwinding. That is the point: the optimiser is allowed to omit unwind machinery on the strength of it." },
{ t: "cpp-errors", d: 2, q: "Why catch an exception by const reference?", o: ["Catching by value slices the exception", "Only references can be rethrown", "The compiler requires const in a catch", "By value would leak the exception object"], a: 0, why: "Catching a base by value copies only the base subobject, losing the derived type and the message with it. A reference also avoids a copy of a possibly large object." },
{ t: "cpp-errors", d: 3, q: "What does std::expected model that an exception does not?", o: ["A failure that is expected and typed", "A failure that cannot be recovered from", "An error detected at compile time", "An error occurring in another thread"], a: 0, why: "It puts the failure in the return type, so the caller must handle it and the cost is visible. Exceptions suit the genuinely exceptional; parsing a user's input is not that." },
{ t: "cpp-errors", d: 2, q: "What is wrong with catch (...) that logs and continues?", o: ["It cannot catch standard exceptions", "You resume with an unknown broken state", "The compiler will not allow it in main", "It rethrows automatically at scope exit"], a: 1, why: "You have swallowed something you could not name, so any invariant may now be violated. Catching everything is defensible at a thread or task boundary, provided you fail that unit rather than pressing on." },
{ t: "cpp-errors", d: 2, q: "Why is error handling by return code error-prone in practice?", o: ["Return codes cannot carry any detail", "Ignoring a code is silent and easy", "Codes cannot cross a library boundary", "They force every function to be inline"], a: 1, why: "Nothing forces the caller to look, and the failure then surfaces far from its cause. nodiscard closes most of that gap, which is why it is worth putting on any status-returning function." },
{ t: "cpp-errors", d: 3, q: "What is the exception guarantee of vector::push_back?", o: ["Nothrow, since it may only allocate", "Strong, provided the element move is noexcept", "Basic, leaving the vector in some valid state", "None; a throw leaves it unspecified"], a: 1, why: "It gives the strong guarantee, and to do so it must copy rather than move when the element's move constructor can throw. That is precisely why marking your move noexcept matters for performance." },
{ t: "cpp-errors", d: 2, q: "When is it right to let an exception leave main?", o: ["Whenever the error is unrecoverable", "Never; you lose the chance to report it", "Only if the exception is std::bad_alloc", "Always, since the runtime prints it"], a: 1, why: "Escaping main gives an implementation-defined message and may skip destructors of automatic objects. Catch at the top, report what happened, and return a failing status." },
{ t: "cpp-errors", d: 2, q: "What does an assert give you that an exception does not?", o: ["It survives into the release build", "It states a precondition and can compile away", "It can be caught and then handled by the caller", "It reports the error to the user cleanly"], a: 1, why: "An assert documents something the code believes is impossible and vanishes under NDEBUG. An exception is for conditions you expect to occur and intend to handle." },
{ t: "cpp-errors", d: 3, q: "Why is throwing from a destructor during a failed operation particularly bad?", o: ["Destructors run in an unspecified order", "A second live exception ends the program", "The object's memory is leaked instead", "Destructors cannot throw at all in C++"], a: 1, why: "During unwinding one exception is already in flight, and a second calls std::terminate. If cleanup can fail, offer an explicit close() that reports it and let the destructor swallow." },

// ------------------------------------------------------------- cpp-lambdas
{ t: "cpp-lambdas", d: 1, q: "What is a lambda expression, in terms of the type system?", o: ["A function pointer with its bound arguments", "A unique unnamed class with an operator()", "A std::function object created inline", "A macro expanded by the preprocessor"], a: 1, why: "Each lambda has its own closure type, which is why two identical lambdas are different types. The captures become members, and a captureless lambda additionally converts to a plain function pointer." },
{ t: "cpp-lambdas", d: 2, q: "What is the danger of capturing by reference with [&]?", o: ["It copies more than you expect", "The referents may die before the lambda runs", "Reference captures simply cannot be called twice", "It forces the lambda onto the heap"], a: 1, why: "Fine for a call that happens within the scope, and a dangling reference the moment the lambda is stored or posted to another thread. Capture by value, or capture exactly what you need, when the lifetime is not obvious." },
{ t: "cpp-lambdas", d: 2, q: "How do you move a unique_ptr into a lambda?", o: ["Capture it by reference with [&p]", "Use an init capture, [p = std::move(p)]", "Pass it in as an argument to the operator()", "Capture by value; unique_ptr copies"], a: 1, why: "Init capture, introduced in C++14, constructs a new member from an arbitrary expression. Plain capture by value would need a copy, which unique_ptr does not have." },
{ t: "cpp-lambdas", d: 2, q: "What does capturing this by [=] actually capture?", o: ["A copy of every member of the object", "The this pointer, so members are indirect", "Nothing, since members are not variables", "A reference to the object, safely counted"], a: 1, why: "You get the pointer, not the members, so the lambda dangles if the object dies first. C++17 added [*this] to capture a copy of the object, which is what you usually meant." },
{ t: "cpp-lambdas", d: 2, q: "Why does mutable exist on a lambda?", o: ["To allow modifying by-value captures", "To make the lambda thread safe", "To permit capturing by reference", "To let the lambda be reassigned later"], a: 0, why: "operator() is const by default, so by-value captures are read-only. mutable drops the const, and it changes nothing about by-reference captures, which were never const." },
{ t: "cpp-lambdas", d: 3, q: "What is the cost of storing a lambda in a std::function?", o: ["Type erasure, an indirect call, maybe an allocation", "Nothing, since std::function is a typedef", "It forces the whole lambda to become captureless first", "The lambda is recompiled at each call site"], a: 0, why: "std::function erases the type, so the call goes through a virtual-like indirection and cannot inline, and a large closure may heap-allocate. Passing the lambda as a template parameter keeps it inlinable." },
{ t: "cpp-lambdas", d: 2, q: "Why is a lambda passed to std::sort usually faster than a function pointer?", o: ["Lambdas use a better sorting algorithm", "Its unique type lets the comparison inline", "Function pointers require their own allocation", "Lambdas are evaluated at compile time"], a: 1, why: "The closure type is baked into the template instantiation, so the comparison is inlined. A function pointer is one opaque type, leaving an indirect call in the inner loop." },
{ t: "cpp-lambdas", d: 2, q: "What does a generic lambda, written with auto parameters, become?", o: ["A template operator() on the closure type", "A separate lambda for each call site", "A std::function taking std::any", "A macro that expands once per argument type"], a: 0, why: "auto in the parameter list makes operator() a member template, so one lambda serves many argument types. C++20 lets you name the parameter explicitly with a template head." },
{ t: "cpp-lambdas", d: 3, q: "Why does an immediately invoked lambda help with const initialisation?", o: ["It runs the initialisation on another thread", "Complex setup can produce a const result", "const objects cannot be initialised otherwise", "It defers the initialisation until first use"], a: 1, why: "You need branching or a loop to compute the value, but you still want the variable const. Wrapping the computation and calling it at once gives you both, without a mutable intermediate." },
{ t: "cpp-lambdas", d: 2, q: "What is a captureless lambda uniquely able to do?", o: ["Convert to an ordinary function pointer", "Outlive the scope it was defined in", "Be invoked from more than one thread at once", "Be stored in a constexpr variable"], a: 0, why: "With no state to carry, the closure converts to a plain function pointer, which is how you pass one to a C callback API. Capturing lambdas cannot, which is why C callbacks take a void* context." },

// ----------------------------------------------------------- cpp-constexpr
{ t: "cpp-constexpr", d: 1, q: "What does constexpr on a function actually promise?", o: ["It always runs at compile time", "It may run at compile time if asked", "It runs faster at run time than normal", "It can only be called from templates"], a: 1, why: "It says the function is capable of constant evaluation given constant arguments. consteval is the one that requires it, and constinit constrains initialisation rather than evaluation." },
{ t: "cpp-constexpr", d: 2, q: "What happens if a constexpr evaluation would be undefined behaviour?", o: ["It is a compile error at that point", "The behaviour is undefined as usual", "The compiler falls back to run time", "The value becomes zero silently"], a: 0, why: "Constant evaluation forbids UB, so an overflow or an out-of-range index becomes a diagnostic. That makes constexpr a surprisingly good static checker for arithmetic you care about." },
{ t: "cpp-constexpr", d: 2, q: "What does consteval add over constexpr?", o: ["Evaluation is required at compile time", "It allows floating point in constant contexts", "It permits allocation during evaluation", "It marks the function as inline as well"], a: 0, why: "Every call must be a constant expression, so the function can never appear at run time. It is the right marker for something like a compile-time format-string check." },
{ t: "cpp-constexpr", d: 3, q: "Why does a constexpr variable at namespace scope help firmware?", o: ["It is placed in read-only memory, not RAM", "It is initialised lazily on first access", "It removes the need for a linker script", "It is faster to read than a runtime value"], a: 0, why: "The value is known at compile time so it lands in flash with no startup code and no RAM cost. A non-constexpr global with a computed initialiser needs both." },
{ t: "cpp-constexpr", d: 2, q: "What does static_assert let you do that a runtime check does not?", o: ["Fail the build rather than the device", "Check a value the user typed in", "Test the same condition much faster", "Verify behaviour across translation units"], a: 0, why: "The condition is evaluated during compilation, so a violated assumption never ships. It costs nothing at run time and takes a message you can write for the next reader." },
{ t: "cpp-constexpr", d: 2, q: "Why is a constexpr lookup table often better than computing at startup?", o: ["It uses less flash than the code would", "No startup cost and no RAM to hold it", "It can be modified later if needed", "The compiler vectorises the accesses"], a: 1, why: "The table is emitted into read-only memory, so there is no init code and no RAM copy. Whether it beats the code on flash depends on the table size, which is worth measuring." },
{ t: "cpp-constexpr", d: 3, q: "What changed for constexpr in C++20?", o: ["Loops became legal for the first time", "Allocation and virtual calls became usable", "It gained the ability to call any function", "Floating point became forbidden in it"], a: 1, why: "Transient allocation, try blocks and virtual calls all became legal in constant evaluation, so std::vector and std::string became usable there. Loops had already arrived in C++14." },
{ t: "cpp-constexpr", d: 2, q: "What does constinit express?", o: ["The variable is constant after init", "Initialisation happens at compile time", "The variable may not be reassigned", "The variable lives in read-only memory"], a: 1, why: "It requires static initialisation, which kills the static initialisation order fiasco for that variable, while leaving it mutable afterwards. constexpr would additionally make it const." },
{ t: "cpp-constexpr", d: 2, q: "Why can a constexpr function still be called with runtime arguments?", o: ["The compiler evaluates it twice", "constexpr constrains the body, not the call", "It silently becomes a template", "The arguments are each converted into constants"], a: 1, why: "The marker says the body could be constant-evaluated; given non-constant arguments it is an ordinary function. That dual use is why so much of the standard library is now marked constexpr." },
{ t: "cpp-constexpr", d: 3, q: "How would you force compile-time evaluation of a constexpr function?", o: ["Mark the call site with static_assert", "Assign the result to a constexpr variable", "Call it inside a template parameter list", "Wrap the call in std::move"], a: 1, why: "Assigning to a constexpr variable, or using the result as a template argument, both require a constant expression. If it cannot be constant-evaluated you get a diagnostic rather than a silent runtime call." },

// ------------------------------------------------------------- cpp-strings
{ t: "cpp-strings", d: 1, q: "What is a std::string_view?", o: ["A copy of a string with a smaller buffer", "A non-owning pointer and length pair", "A reference-counted immutable string", "A string that lives on the stack only"], a: 1, why: "It refers to characters it does not own, so passing one costs two words and no allocation. The lifetime of the underlying buffer is entirely your problem." },
{ t: "cpp-strings", d: 2, q: "What is the danger in returning a string_view from a function?", o: ["It copies the string on return", "It may outlive the buffer it points at", "string_view cannot be returned at all", "The caller cannot read it as const"], a: 1, why: "Returning a view of a local string, or of a temporary built at the call, leaves a dangling view. The rule of thumb is that views are for parameters, not for return values or members." },
{ t: "cpp-strings", d: 2, q: "What is small string optimisation?", o: ["Short strings are stored inside the object", "Short strings all share a single global buffer", "The allocator rounds small sizes up", "Strings under 16 bytes are interned"], a: 0, why: "Implementations keep a small buffer in the string object itself, so short strings need no allocation at all. It is why sizeof(std::string) is larger than you might expect and why moving a short string is not free." },
{ t: "cpp-strings", d: 2, q: "Why does std::string::c_str() guarantee a null terminator but string_view does not?", o: ["string_view stores its length separately", "A view may name part of a larger buffer", "c_str allocates a fresh buffer each time", "string_view is always null-terminated too"], a: 1, why: "A view can point at a substring, so there is no terminator to promise. Passing view.data() to a C function that expects a C string is a common and quiet bug." },
{ t: "cpp-strings", d: 3, q: "What does reserve on a string being built in a loop achieve?", o: ["It fixes the string's length in advance", "One allocation instead of repeated growth", "It makes append operations constant time", "It prevents small string optimisation"], a: 1, why: "Without it the buffer grows geometrically, copying the contents each time. Appends are already amortised constant; what reserve removes is the repeated allocation and copying." },
{ t: "cpp-strings", d: 2, q: "Why is std::stoi a poor choice for parsing untrusted input?", o: ["It cannot parse negative numbers", "It throws, and ignores trailing junk", "It is far slower than a hand-written loop", "It requires a null-terminated buffer"], a: 1, why: "It raises an exception on failure and happily accepts a partial parse. std::from_chars reports both the error and where it stopped, without allocation or locale." },
{ t: "cpp-strings", d: 2, q: "What does std::format offer over a stream chain?", o: ["Compile-time checking of the format string", "Faster output on every platform", "Support for user-defined types only", "Automatic locale-aware grouping of the numbers"], a: 0, why: "The format string is checked during compilation, so an argument mismatch is a build error. It also reads in the order the output appears, which streams do not." },
{ t: "cpp-strings", d: 3, q: "Why is a string comparison sometimes slower than expected?", o: ["Comparison always compares full capacity", "Equal-length strings compare byte by byte", "Every comparison allocates a temporary", "Comparison converts to a C string first"], a: 1, why: "A length check rules out unequal sizes quickly, but two same-length strings that share a long prefix must be walked. That is why hashing, or comparing an interned id, wins in a hot lookup." },
{ t: "cpp-strings", d: 2, q: "What is the practical problem with using std::string in an ISR?", o: ["It cannot be constructed at all there", "It may allocate, with unbounded timing", "Its destructor is not interrupt safe", "Strings are always stored in flash"], a: 1, why: "Any growth beyond the small buffer calls the allocator, whose latency is not bounded and which may take a lock. A fixed char array, or a span over one, keeps the timing predictable." },
{ t: "cpp-strings", d: 2, q: "Why does taking a string parameter by value and moving it sometimes beat a const reference?", o: ["It avoids one copy when the caller passes a temporary", "By-value parameters are never copied at all", "const references force an extra allocation", "It lets the function modify the caller's original string"], a: 0, why: "If the function stores the string anyway, an rvalue argument is moved straight in. For a caller passing an lvalue it is a copy plus a move, so it is a win only where you keep the value." },

// --------------------------------------------------------------- cpp-build
{ t: "cpp-build", d: 1, q: "What does the one-definition rule require of an inline function in a header?", o: ["It must appear in exactly one source file", "Every definition must be token-identical", "It may not be called from more than one file", "It must be declared static in each file"], a: 1, why: "Multiple definitions are allowed provided they are the same; differing ones are undefined behaviour the linker will not catch. That is why a macro that changes a header's meaning per file is so dangerous." },
{ t: "cpp-build", d: 2, q: "What does an unnamed namespace do?", o: ["Gives its contents internal linkage", "Hides the names from the debugger", "Prevents the linker from inlining them", "Marks the contents as deprecated"], a: 0, why: "The names are visible only in that translation unit, which is the C++ spelling of file-static. It avoids symbol clashes and lets the optimiser assume nothing outside can call in." },
{ t: "cpp-build", d: 2, q: "Why does a forward declaration speed up builds?", o: ["It skips parsing the class entirely", "The header need not be included at all", "It marks the type as never changing", "It defers the instantiation to link time"], a: 1, why: "Where only a pointer or reference is needed, declaring the class breaks the include edge, so a change to that header does not rebuild everything downstream. It also breaks cycles between headers." },
{ t: "cpp-build", d: 3, q: "Why does link order matter for static libraries on a Unix toolchain?", o: ["Later libraries override earlier symbols", "The linker pulls only what is unresolved so far", "Libraries are searched alphabetically", "Static libraries must always precede all object files"], a: 1, why: "The traditional linker makes a single pass, taking from each archive only the members that resolve currently outstanding symbols. A library listed before its user contributes nothing." },
{ t: "cpp-build", d: 2, q: "What problem does extern \"C\" solve?", o: ["It compiles the body as C, not C++", "It disables name mangling for linkage", "It allows C++ features inside a C file", "It marks the function as externally visible"], a: 1, why: "The symbol gets a plain C name so a C caller or a dynamic loader can find it. The body is still C++, and it therefore cannot be overloaded." },
{ t: "cpp-build", d: 2, q: "What does target_include_directories with PUBLIC mean in CMake?", o: ["The directory is added for just this target only", "It propagates to anything linking this target", "It is added to every target in the project", "It replaces the global include path"], a: 1, why: "PUBLIC applies to the target and to its consumers, PRIVATE to the target alone, and INTERFACE only to consumers. Getting this right is what makes a library usable without documentation." },
{ t: "cpp-build", d: 3, q: "Two translation units define the same class with different member counts. What is that?", o: ["A link error which the toolchain will duly report", "An ODR violation, and undefined at run time", "Legal, provided both are in headers", "Detected and rejected by the compiler"], a: 1, why: "The linker matches by mangled name and cannot see the layout, so one file writes past the other's object. A guarded macro that changes a struct is the usual cause." },
{ t: "cpp-build", d: 2, q: "What is the advantage of static linking for a deployed embedded binary?", o: ["Smaller binaries in every case", "One self-contained image, no runtime loader", "Automatic updates of any shared components used", "Faster compilation of the project"], a: 1, why: "Everything needed is in the image and only referenced objects are pulled in, so there is no loader and no version skew. You give up sharing the library across processes and patching it independently." },
{ t: "cpp-build", d: 2, q: "Why is a unity build sometimes much faster?", o: ["It skips the preprocessor entirely", "Shared headers are parsed once, not per file", "It disables optimisation for speed", "It compiles each of the functions in parallel"], a: 1, why: "Concatenating sources amortises the cost of the headers they share, which dominates in template-heavy code. It costs you incremental rebuilds and can surface hidden ODR and name-collision bugs." },
{ t: "cpp-build", d: 3, q: "What does link-time optimisation change about the compile step?", o: ["Object files carry an intermediate form", "Optimisation is skipped until linking", "Each object is compiled twice over", "Debug information is discarded entirely"], a: 0, why: "The compiler emits its IR rather than final code, so the linker can inline and propagate constants across translation units. Link times and memory use rise noticeably in exchange." },

// ---------------------------------------------------------------- cpp-perf
{ t: "cpp-perf", d: 1, q: "What is the first step when a program is too slow?", o: ["Rewrite the inner loops by hand", "Measure to find where the time goes", "Enable the highest optimisation level", "Replace containers with raw arrays"], a: 1, why: "Intuition about hotspots is famously unreliable, and every change costs clarity. A profile tells you which five percent is worth spending that clarity on." },
{ t: "cpp-perf", d: 2, q: "Why does a vector usually beat a list even for middle insertion?", o: ["Insertion in a vector is constant time", "Contiguous memory is far friendlier to cache", "Lists must reallocate on every single insertion", "Vector insertion never moves elements"], a: 1, why: "Moving a run of contiguous bytes is fast and predictable, while chasing pointers stalls on misses. The complexity table ignores the constant factor, and here the constant factor decides." },
{ t: "cpp-perf", d: 2, q: "What is the point of structure of arrays over array of structures?", o: ["It reduces the total memory used", "Only the fields you touch enter the cache", "It removes the need for alignment", "It allows new fields to be added later on too"], a: 1, why: "If a loop reads one field of many, AoS drags whole objects through the cache. SoA packs that field contiguously, which also makes vectorisation possible." },
{ t: "cpp-perf", d: 3, q: "Why can a branch in a hot loop be expensive?", o: ["Branches always flush out the whole cache", "A misprediction costs a pipeline refill", "Each branch requires a memory access", "The compiler cannot optimise past one"], a: 1, why: "A predictable branch is nearly free; an unpredictable one costs the depth of the pipeline. Sorting the data, or replacing the branch with arithmetic, is what removes the cost." },
{ t: "cpp-perf", d: 2, q: "What does the optimiser do to a computation whose result is unused?", o: ["Computes it and discards the value", "Deletes it entirely", "Moves it outside the loop", "Evaluates it once at startup"], a: 1, why: "Dead code elimination removes it, which is exactly why naive benchmarks measure nothing. A benchmark library's DoNotOptimize exists to defeat this." },
{ t: "cpp-perf", d: 2, q: "Why does passing a large object by value hurt?", o: ["It forces an allocation on the heap", "It copies the whole object at each call", "The compiler cannot inline such a call", "It disables return value optimisation"], a: 1, why: "Every call constructs a copy, which for a container means an allocation and a deep copy. A const reference costs one pointer, and by-value is right only when you will keep the copy." },
{ t: "cpp-perf", d: 3, q: "What is the effect of marking a virtual function final?", o: ["It prevents the whole class being derived from", "Devirtualisation and inlining become possible", "It moves the function into the vtable", "It forces the function to be inline"], a: 1, why: "The compiler knows no further override can exist, so a call through that type can be resolved statically. final on the class does the same for all its virtuals." },
{ t: "cpp-perf", d: 2, q: "Why is std::endl often slower than a newline character?", o: ["It writes two characters instead of one", "It flushes the stream on every call", "It allocates a temporary string", "It locks the stream for other threads"], a: 1, why: "The flush forces a write syscall per line, which dominates in a loop. Use a plain newline and let the stream flush when it is full or at exit." },
{ t: "cpp-perf", d: 2, q: "What does restrict-like aliasing information let a compiler do?", o: ["Keep values in registers across writes", "Vectorise every loop automatically", "Remove all the bounds checks in the loop", "Allocate the arrays contiguously"], a: 0, why: "If two pointers may alias, a write through one forces a reload through the other. Telling the compiler they do not lets it hoist loads out of the loop, which is often the whole win." },
{ t: "cpp-perf", d: 3, q: "Why does an atomic counter incremented by many threads scale badly?", o: ["The atomic operation is not lock free", "The cache line bounces between cores", "Each increment takes a kernel lock", "Atomics disable the store buffer"], a: 1, why: "Every increment must own the line exclusively, so the line ping-pongs. Per-thread counters summed at the end remove the contention entirely." },

// ----------------------------------------------------------------- cpp-api
{ t: "cpp-api", d: 2, q: "Why should a function that returns a status be marked nodiscard?", o: ["It makes the return value const", "Ignoring the result becomes a warning", "It forces the caller to handle errors", "It prevents the value being copied"], a: 1, why: "The compiler warns when the value is dropped, which is the commonest way an error is lost. It is a warning, not an error, so it guides rather than compels." },
{ t: "cpp-api", d: 2, q: "What does taking a parameter as std::span rather than a container express?", o: ["The function is allowed to resize the whole sequence", "It accepts any contiguous range, and owns none", "The caller must pass a std::vector", "The data will be copied on entry"], a: 1, why: "A vector, an array, or a pointer and length all convert, and the signature says the function does not take ownership. It also stops the accidental copy that a by-value vector parameter causes." },
{ t: "cpp-api", d: 3, q: "What is the pimpl idiom for?", o: ["Hiding implementation and stabilising the ABI", "Making the class faster to construct", "Allowing the whole class to be copied more cheaply", "Removing the need for a destructor"], a: 0, why: "Members move behind an opaque pointer, so the header stops changing when the implementation does, and dependent code need not rebuild. You pay an allocation and an indirection for it." },
{ t: "cpp-api", d: 2, q: "Why is an out-parameter usually worse than a return value?", o: ["Out-parameters cannot be const", "The caller must declare it uninitialised first", "Return values are always faster than out-parameters", "Out-parameters prevent inlining"], a: 1, why: "It forces a default-constructed variable at every call site and hides the data flow. Returning a value, or a struct, reads better and is not slower thanks to elision." },
{ t: "cpp-api", d: 2, q: "What does making a class non-copyable but movable express?", o: ["The object owns a unique resource", "The class is too large to copy", "Copying would be too slow to allow", "The class has no default constructor"], a: 0, why: "Unique ownership is the reason, which is why unique_ptr, thread and lock_guard all behave this way. Cost alone is a weak reason to delete a copy; the type system should express meaning." },
{ t: "cpp-api", d: 2, q: "Why prefer an enum class over a bool parameter in a public API?", o: ["Enums are stored more compactly", "The call site reads as what it means", "bool cannot be used in an interface", "It allows more than two states later"], a: 1, why: "f(true) tells the reader nothing, while f(Mode::Async) does. It also prevents two bool parameters being swapped without a diagnostic." },
{ t: "cpp-api", d: 3, q: "What breaks a library's ABI even though the source still compiles?", o: ["Renaming one of the private member variables", "Adding a member to an exported class", "Adding a new free function", "Marking a function nodiscard"], a: 1, why: "The object's size and member offsets change, so code compiled against the old header reads the wrong bytes. That is exactly the class of change pimpl is designed to absorb." },
{ t: "cpp-api", d: 2, q: "What is the value of returning a strong type instead of a raw int?", o: ["It is faster to pass in registers", "Units and meaning cannot be mixed up", "It permits arithmetic to be overloaded", "It stops the value being copied"], a: 1, why: "Milliseconds and metres both being int is how they get swapped. A distinct type makes the mistake a compile error and costs nothing at run time." },
{ t: "cpp-api", d: 2, q: "Why document a function's preconditions rather than checking them all?", o: ["Checks are impossible in release builds", "Some checks cost more than the function", "The compiler removes the checks anyway", "Preconditions cannot be expressed in code"], a: 1, why: "Verifying that a range is sorted is linear where the function is logarithmic. State the requirement, assert it in debug, and let the caller carry the obligation." },
{ t: "cpp-api", d: 3, q: "What is the practical problem with a header that includes everything it might need?", o: ["It slows every dependent translation unit", "It causes duplicate symbol errors", "It prevents forward declaration entirely", "The linker cannot resolve its symbols"], a: 0, why: "Each consumer pays the parse cost and gains a rebuild dependency on every transitively included header. Include what you use, and forward declare where a reference suffices." },

// ------------------------------------------------------------- cpp-testing
{ t: "cpp-testing", d: 1, q: "What makes a unit test fast enough to run on every save?", o: ["It uses a small input data set", "It touches no file, socket or clock", "It runs with optimisation enabled", "It asserts only one thing per test"], a: 1, why: "The cost is dominated by I/O and by waiting, not by the arithmetic. A test that only calls pure functions runs in microseconds, which is what makes running the whole suite continuously possible." },
{ t: "cpp-testing", d: 2, q: "Why inject a clock rather than call the system clock directly?", o: ["The system clock is not thread safe", "The test can advance time on demand", "System calls are forbidden in tests", "It makes the production code faster"], a: 1, why: "A timeout test that really waits five seconds will not be run. A fake clock the test steps forward makes the behaviour deterministic and instant." },
{ t: "cpp-testing", d: 2, q: "What distinguishes a mock from a stub?", o: ["A mock also asserts on the calls made", "A stub is for classes, a mock for functions", "A mock is generated, a stub is written", "A stub records calls for later inspection"], a: 0, why: "A stub supplies canned answers so the code under test can proceed. A mock additionally has expectations about how it was called, which makes the interaction itself the thing under test." },
{ t: "cpp-testing", d: 2, q: "What does a sanitiser build add that a normal test run does not?", o: ["Coverage measurement of each line", "Detection of leaks and undefined behaviour", "Automatic generation of test cases", "Faster execution of the whole of the test suite"], a: 1, why: "AddressSanitizer and UndefinedBehaviorSanitizer turn silent corruption into a loud failure on code the tests already exercise. They cost roughly a two-fold slowdown, which is cheap for what they catch." },
{ t: "cpp-testing", d: 3, q: "What does high line coverage fail to tell you?", o: ["Which lines the tests executed", "Whether the assertions check anything", "How long the suite takes to run", "Which of the files were compiled at all"], a: 1, why: "A test that calls everything and asserts nothing scores perfectly. Mutation testing, which breaks the code and checks that a test fails, is what actually measures the assertions." },
{ t: "cpp-testing", d: 2, q: "Why is a test that depends on another test's side effects a problem?", o: ["It runs more slowly than an isolated one", "Reordering or filtering breaks it", "The framework refuses to run it", "It cannot assert on shared state"], a: 1, why: "Running one test alone, or in a different order, then fails for reasons unrelated to the code. Shared state between tests is the usual cause and is worth removing on sight." },
{ t: "cpp-testing", d: 2, q: "What is a good candidate for property-based testing?", o: ["A function with a single known fixed output", "A round trip such as encode then decode", "A function that writes to a database", "A function with no arguments at all"], a: 1, why: "Decoding an encoded value must return the original for any input, which is a property rather than a case. The framework then searches the input space and shrinks any failure it finds." },
{ t: "cpp-testing", d: 3, q: "Why is testing a private method usually the wrong instinct?", o: ["Private methods cannot be called at all", "It locks the tests to the implementation", "The compiler forbids friend test classes", "Private methods are always trivial"], a: 1, why: "Tests then break on every refactor that changes nothing observable. If the logic is worth testing directly, it usually wants to be a separate unit with its own public interface." },
{ t: "cpp-testing", d: 2, q: "When should a test use an ASSERT rather than an EXPECT?", o: ["Whenever the check is important", "When continuing would be meaningless", "For every single check in the last test", "When the value is a pointer"], a: 1, why: "ASSERT stops the test, which is right after a null check where continuing would crash. EXPECT keeps going and reports every failure, which gives you more information per run." },
{ t: "cpp-testing", d: 2, q: "What is the point of a test that reproduces a reported bug?", o: ["It documents the fix for the changelog", "It closes that gap in coverage for good", "It measures how long the bug existed", "It proves the original code was wrong"], a: 1, why: "Add the failing case first, then fix it, and the regression cannot return unnoticed. It also forces you to understand the bug well enough to trigger it deliberately." },

]);
