BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// ---------------------------------------------------------------- emb-req
{ t: "emb-req", d: 1, q: "What makes a statement a requirement rather than an aspiration?", o: ["It appears in the specification document", "You can write today the procedure that decides whether it passes", "A manager has signed it off", "It uses the word shall"], a: 1, why: "<p>The word 'shall' and a document number cost nothing and prove nothing. The test is verifiability.</p><p>If you cannot describe the procedure that would decide pass or fail, the decision has been deferred rather than made, and it will be made later by whoever writes the code, alone and unrecorded.</p><p>A good requirement is one where two engineers implementing it independently would produce behaviour you could not tell apart.</p>" },
{ t: "emb-req", d: 1, q: "Which of these is a testable requirement?", o: ["The device shall be responsive to user input", "The LED shall be brighter when the signal is better", "LED duty shall track the quality register at 20 Hz, settling within 200 ms", "The device shall handle sensor errors gracefully"], a: 2, why: "<p>It carries a quantity, a relationship, a rate and a bound, so the verification procedure writes itself.</p><p>'Responsive' has no number. 'Brighter when better' gives a direction but no mapping. 'Gracefully' is the classic hiding place for an unmade decision about what actually happens.</p>" },
{ t: "emb-req", d: 2, q: "Why are words like 'fast', 'robust' and 'approximately' worth hunting for in a brief?", o: ["They are informal", "Each marks a decision that has been deferred rather than made", "They are ambiguous in translation", "They make the document longer"], a: 1, why: "<p>Every one of them will eventually be resolved to a specific number, by someone. The only question is whether that happens now, cheaply, in a conversation, or later, expensively, by an engineer guessing under deadline.</p><p>Finding them and asking the question is often the highest-value thing done on a project, and it costs a morning.</p>" },
{ t: "emb-req", d: 2, q: "Which part of a specification is almost always missing?", o: ["The user interface", "The error and edge cases", "The hardware list", "The performance targets"], a: 1, why: "<p>Sensor disconnected, implausible reading, connection dropped mid-transfer, flash full, battery nearly flat, two commands at once, first boot before calibration.</p><p>All of those will happen in the field, so the behaviour is going to exist regardless. Writing the question down is what turns an accident into a decision.</p><p>It is also where most firmware code volume ends up, so leaving it unspecified leaves most of the work unspecified.</p>" },
{ t: "emb-req", d: 2, q: "What is a non-functional requirement?", o: ["A requirement that was rejected", "A constraint like latency, current, memory or lifetime rather than a behaviour", "Documentation", "A feature nobody uses"], a: 1, why: "<p>Worst-case interrupt latency, average idle current, flash headroom after release, write endurance, time from power-on to first reading.</p><p>These constrain part selection as hard as any behaviour does, and they are the ones discovered late, at the point where the chosen part turns out to be too small or too thirsty.</p>" },
{ t: "emb-req", d: 2, q: "What is the more useful direction to read a traceability matrix?", o: ["Test back to requirement, to satisfy an auditor", "Requirement forward to test, to find requirements nothing verifies", "By author, to assign blame", "By date, to track progress"], a: 1, why: "<p>Read that way it is a coverage report in requirement space rather than code space, and it finds different gaps.</p><p>Code coverage tells you which lines executed. This tells you which promises nobody checks, and that list is always longer than expected.</p>" },
{ t: "emb-req", d: 2, q: "A requirement changes mid-project. What is the actual failure mode?", o: ["Change itself, which should be resisted", "Undocumented change: the code moves but the written requirement and its test do not", "Changing too near the deadline", "Telling the customer about it"], a: 1, why: "<p>Requirements change on every real project and that is normal. The damage comes from a hallway conversation that alters behaviour with nothing recording that the specification moved.</p><p>Six months later nobody can say whether a behaviour is intended or a bug, and no test guards it because nobody knew there was a requirement.</p><p>Move the requirement, the code and the test in the same commit.</p>" },
{ t: "emb-req", d: 2, q: "You believe a stated target cannot be met. What is the professional response?", o: ["Get as close as possible and stay quiet", "Say so early, in writing, with the number and the reason", "Wait until integration to raise it", "Ask for the target to be removed"], a: 1, why: "<p>'The idle target is 40 microamps; with this radio duty cycle the floor is 95, so either the target moves or the duty cycle does.'</p><p>That gives everyone else time to react and it is checkable. Delivering something that misses silently is worse for the project and much worse for the engineer's credibility.</p>" },
{ t: "emb-req", d: 3, q: "Why does 'the system shall handle a lost connection' fail as a requirement?", o: ["It is too short", "Handle could mean retry, reboot, or sit silently, and all three are shippable", "Connections are not testable", "It lacks a shall clause"], a: 1, why: "<p>Words like handle, support and manage read as complete but specify nothing. Three engineers would implement three different products, all of which technically satisfy the sentence.</p><p>The useful version names the behaviour: retry three times at increasing intervals, then report a fault code and continue with the last known configuration.</p>" },
{ t: "emb-req", d: 3, q: "Why write requirements before choosing the microcontroller?", o: ["Purchasing requires it", "The non-functional numbers decide whether a candidate part is viable at all", "It looks better in review", "The compiler needs to be known first"], a: 1, why: "<p>Latency, current budget, flash headroom and boot time are the constraints that eliminate parts. Discovering them after layout means a hardware respin rather than a code change.</p><p>The common failure is selecting on peripheral count and price, then finding the feature set does not fit in the flash or the power budget.</p>" },

// ------------------------------------------------------------- emb-review
{ t: "emb-review", d: 1, q: "What is code review comparatively good at finding?", o: ["Arithmetic overflow in a hot loop", "Error paths nobody exercises and assumptions that only hold today", "Race conditions between two tasks", "Memory corruption under load"], a: 1, why: "<p>Reading is strong on intent, naming, missing cases and design cost, all of which a test cannot easily reach.</p><p>It is weak at anything requiring you to simulate execution in your head, which covers arithmetic, concurrency and memory errors. Those want tests, sanitizers and static analysis, and trying to catch them by reading is how reviews get long and still miss things.</p>" },
{ t: "emb-review", d: 2, q: "Why should formatting never appear in a review comment?", o: ["Style does not matter", "Every comment about a space is one not spent on the missing bounds check", "Reviewers should ignore style entirely", "It is a matter of taste"], a: 1, why: "<p>Attention in a review is a fixed and small budget. Anything a machine can decide belongs in the build, not in a human's list of fifteen comments.</p><p>Warnings as errors, a formatter, and a sanitizer build together buy back that attention for the things only a person can see.</p>" },
{ t: "emb-review", d: 2, q: "Which review comment is more likely to be acted on?", o: ["You should use dependency injection here", "This can only run on this silicon with the part attached, so the error paths can never be tested", "This is not how we usually do it", "Consider refactoring this module"], a: 1, why: "<p>It names a consequence, which is a fact that can be checked, rather than a preference, which invites an argument about taste.</p><p>Pairing it with a specific proposal makes it actionable, and neither of those requires the reviewer to outrank the author.</p>" },
{ t: "emb-review", d: 2, q: "Why label comments as defect, risk, suggestion or question?", o: ["To produce review metrics", "Otherwise a nitpick and a real defect look identical and the author has to guess", "It is required by IEC 61508", "To make the review shorter"], a: 1, why: "<p>Fifteen unlabelled comments all carry the same visual weight, so the important one gets the same treatment as the naming quibble.</p><p>The question category is the underrated one: if a reviewer cannot follow the code, that is data about the code rather than about the reviewer.</p>" },
{ t: "emb-review", d: 2, q: "In a firmware review, what is the first thing to check about a shared variable?", o: ["That it has a comment", "Whether an interrupt touches it, and if so whether every read-modify-write is protected", "That it is not global", "Its alignment"], a: 1, why: "<p><code>volatile</code> alone stops the compiler caching the value. It does nothing about atomicity, so <code>count++</code> shared with an ISR is still a lost-update bug waiting for the wrong interrupt timing.</p><p>This single question catches a large fraction of the intermittent faults that reach the field.</p>" },
{ t: "emb-review", d: 2, q: "Why does a small change get a better review than a large one?", o: ["Reviewers are lazy", "A 2,000-line change gets approved, a 200-line change gets read", "Large changes take longer to merge", "Small changes have fewer bugs per line"], a: 1, why: "<p>Beyond a certain size a reviewer cannot hold the change in their head, so the review degrades into a skim and an approval.</p><p>Small changes also mean a mistake is a small revert rather than an untangling, and the work integrates continuously instead of colliding at the end.</p>" },
{ t: "emb-review", d: 2, q: "What should an author do to make a review more useful?", o: ["Approve their own tests first", "Say what they are unsure about, so attention goes where it is worth spending", "Add more comments to the code", "Split it across several repositories"], a: 1, why: "<p>'I am not confident about the locking in rb_get' directs a reviewer to the part with real risk rather than leaving them to distribute attention evenly across a diff.</p><p>It also signals that you know where your own uncertainty is, which is a large part of being trusted.</p>" },
{ t: "emb-review", d: 2, q: "A reviewer makes a blunt comment you think is wrong. What is the useful response?", o: ["Accept it to avoid conflict", "Answer the fact rather than the tone, and give a reason if you disagree", "Escalate the tone problem", "Ignore it and merge"], a: 1, why: "<p>'The datasheet requires the write before the read' ends a discussion. 'I prefer it this way' does not.</p><p>Accepting every comment is not agreeableness, it is a failure to contribute judgement, and it makes your review approval worth less to everyone.</p>" },
{ t: "emb-review", d: 3, q: "Which of these belongs on a firmware review checklist rather than in tooling?", o: ["Trailing whitespace", "Whether a fixed delay should be polling a status bit with a timeout", "Unused variables", "Missing braces"], a: 1, why: "<p>A compiler cannot tell that <code>delay_ms(50)</code> was a guess about how long a chip takes to settle. A human who has read the datasheet can.</p><p>The other three are all decided by <code>-Wall -Wextra</code> and a formatter, so spending review attention on them is waste.</p>" },
{ t: "emb-review", d: 3, q: "Why does 'is anything here static?' earn a place on the checklist?", o: ["Static is slower", "It can silently prevent a second instance and make the function non-reentrant", "It wastes flash", "Static prevents inlining"], a: 1, why: "<p>A function-local static turns a general routine into one that can only be used by one caller at a time, which usually works right up until a second sensor or a second task appears.</p><p>The failure is late, intermittent and looks like a hardware problem, which is exactly the kind of defect review is best placed to prevent.</p>" },

// ------------------------------------------------------------- emb-safety
{ t: "emb-safety", d: 1, q: "What is the difference between a fault and a hazard?", o: ["They are the same thing", "A fault is a component failing; a hazard is a state that can lead to harm", "A hazard is more likely than a fault", "A fault is detectable and a hazard is not"], a: 1, why: "<p>'The sensor goes open circuit' is a fault. 'The heater stays on with no temperature feedback' is a hazard.</p><p>The distinction matters because many different faults produce the same hazard, so a mitigation aimed at the hazard covers all of them at once. Working upward from components gives a long list that still misses combinations.</p>" },
{ t: "emb-safety", d: 2, q: "Which FMEA column most often changes a design?", o: ["Severity", "Detection", "Failure mode", "Effect"], a: 1, why: "<p>A failure you cannot detect cannot be mitigated, so filling in that column honestly is what forces a plausibility check, a second sensor, or a periodic self-test into the design.</p><p>The other columns describe the problem. This one is where the engineering happens.</p>" },
{ t: "emb-safety", d: 2, q: "Why is a disconnected thermocouple reading 0 degrees especially dangerous?", o: ["Zero is out of range", "It looks like valid data, so nothing detects the failure", "It reads too high", "It damages the input"], a: 1, why: "<p>A failure that produces an implausible value announces itself. A failure that produces a plausible value is acted on as though it were true.</p><p>This is why sensor front ends are often deliberately biased so a disconnection reads out of range: the design converts an undetectable failure into a detectable one.</p>" },
{ t: "emb-safety", d: 2, q: "What two properties should a safe state ideally have?", o: ["Fast to reach and cheap to implement", "Reached with no power, and reachable without depending on the thing that failed", "Software controlled and logged", "Reversible and automatic"], a: 1, why: "<p>If the safe state is what the system settles into with the power removed, it does not depend on software still being alive to get there.</p><p>And if reaching it depends on the failed component, it is not a mitigation. An emergency stop implemented as a function on the processor that just crashed is not a design.</p>" },
{ t: "emb-safety", d: 2, q: "What is the difference between fail-safe and fail-operational?", o: ["Nothing, they are synonyms", "Fail-safe stops and is safe; fail-operational keeps working correctly and needs redundancy", "Fail-safe is for software, fail-operational for hardware", "Fail-operational is cheaper"], a: 1, why: "<p>Fail-safe is right for most equipment and is far cheaper. Fail-operational is what aircraft controls and steer-by-wire need, and it requires two channels, a comparison, and a rule for deciding which to believe.</p><p>Knowing which one the product needs, and saying so early, is more useful than either assuming.</p>" },
{ t: "emb-safety", d: 2, q: "Why run safety self-tests periodically rather than only at start-up?", o: ["Start-up is too busy", "A safety mechanism can fail during operation, which is where most of the hours are", "Flash needs refreshing", "Regulators require it hourly"], a: 1, why: "<p>Testing only at power-on means a fault in the safety mechanism itself goes undetected for the entire operating period, which on many products is months.</p><p>A safety mechanism you cannot confirm is still working is not a mitigation, it is an assumption.</p>" },
{ t: "emb-safety", d: 2, q: "What should a watchdog be fed from?", o: ["A periodic timer interrupt", "A point that only executes when the whole system has demonstrated progress", "The idle task", "The main loop, unconditionally"], a: 1, why: "<p>A timer interrupt keeps feeding the watchdog while every task is deadlocked, which converts a safety device into a decoration.</p><p>The useful pattern is each task setting a flag on completing its cycle, and a single check that feeds only when all flags are set and then clears them.</p>" },
{ t: "emb-safety", d: 3, q: "What question exposes a single point of failure in a mitigation?", o: ["How much does it cost?", "What single thing, if it fails, removes this mitigation?", "How often does it run?", "Who reviewed it?"], a: 1, why: "<p>If the answer is the same processor that runs the control loop, then one channel is wearing two hats and a single fault removes both the control and the protection.</p><p>This is why safety-relevant designs reach for an external watchdog chip, a hardware interlock in series with the drive, or a second small MCU whose only job is to say no.</p>" },
{ t: "emb-safety", d: 3, q: "What is the most valuable content of a hazard log?", o: ["The list of mitigations implemented", "The hazards deliberately not mitigated, and why", "The severity ratings", "The review signatures"], a: 1, why: "<p>The implemented mitigations are visible in the code. What is invisible is the reasoning behind the gaps, and a future engineer who cannot tell an accepted risk from an oversight will either re-argue it or, worse, assume it was covered.</p><p>Recording the decision is what makes it a decision rather than an omission.</p>" },
{ t: "emb-safety", d: 3, q: "Is 'stopped' automatically the safe state for a medical infusion pump?", o: ["Yes, stopping is always safe", "No, because withholding the therapy can itself cause harm", "Yes, if it alarms", "Only if the battery is charged"], a: 1, why: "<p>For a motor or a heater, off is safe. For a pump delivering something the patient needs, stopping trades one harm for another, and the right answer depends on the drug and the clinical context.</p><p>It is the clearest example of why the safe state has to be decided per product rather than assumed.</p>" },

// ---------------------------------------------------------- emb-standards
{ t: "emb-standards", d: 1, q: "Which standard covers medical device software?", o: ["ISO 26262", "IEC 62304", "DO-178C", "EN 50128"], a: 1, why: "<p>IEC 62304, with classes A, B and C set by the harm a failure could cause.</p><p>ISO 26262 is automotive with ASIL A to D, DO-178C is airborne and is where MC/DC coverage comes from, EN 50128 is railway, and IEC 61508 is the generic parent the others derive from.</p>" },
{ t: "emb-standards", d: 1, q: "Which standard is the generic parent that the sector standards derive from?", o: ["ISO 9001", "IEC 61508", "IEC 62304", "ISO 26262"], a: 1, why: "<p>IEC 61508, with SIL 1 to 4. The automotive, medical, railway and process-industry standards are adaptations of the same framework for their own hazards and vocabulary.</p><p>ISO 9001 is quality management generally and says nothing about functional safety.</p>" },
{ t: "emb-standards", d: 2, q: "What does a safety integrity level primarily control?", o: ["The programming language allowed", "The process and the evidence required, rather than the code itself", "The clock speed and margin", "The number of engineers on the project"], a: 1, why: "<p>Requirements traced to tests, structural coverage rising from statement to branch to MC/DC, independence between author and verifier, a coding standard with recorded deviations, tool qualification, and configuration management strong enough to rebuild any release.</p><p>The theme throughout is demonstrating correctness rather than believing it, which is why a project that did everything well but recorded nothing still fails.</p>" },
{ t: "emb-standards", d: 2, q: "In the V-model, what does each level of design correspond to?", o: ["A milestone date", "A matching level of verification", "A separate team", "A document number"], a: 1, why: "<p>Requirements pair with acceptance testing, architecture with integration testing, detailed design with unit testing.</p><p>The point of the pairing is that a requirement with nothing opposite it is a promise nobody checks, which is exactly what a traceability matrix is for finding.</p>" },
{ t: "emb-standards", d: 2, q: "What is tool qualification and why does it exist?", o: ["Training engineers on the toolchain", "Justifying that a tool cannot introduce or hide a fault undetected", "Buying commercial tools only", "Version pinning"], a: 1, why: "<p>If a compiler bug or a test tool defect could put a fault into the product, or could hide one, then the safety argument depends on the tool as much as on the code.</p><p>The mitigation is either evidence about the tool or a process step that would catch its failure, and which one you need depends on the level.</p>" },
{ t: "emb-standards", d: 2, q: "What does independence mean in a verification context?", o: ["The tests run on separate hardware", "The person verifying is not the person who wrote it", "The tests do not share state", "The team reports to a different manager"], a: 1, why: "<p>An author cannot see their own assumption, because the same misunderstanding that produced the code produces the test.</p><p>Higher levels escalate this from a different person, to a different team, to a different organisation, in proportion to the consequence of a missed defect.</p>" },
{ t: "emb-standards", d: 2, q: "Which practice from these standards is worth adopting on unregulated work?", o: ["MC/DC coverage", "Traceability read from requirement to test", "Formal methods", "Full tool qualification"], a: 1, why: "<p>It finds promises nobody verifies, and costs a spreadsheet.</p><p>Along with written testable requirements, independence in review, and being able to rebuild any release exactly, it pays for itself on almost any project. The heavier practices should scale with the consequence of failure, which is precisely what the classification schemes encode.</p>" },
{ t: "emb-standards", d: 3, q: "What is MC/DC coverage?", o: ["Every line executed at least once", "Every condition shown to independently affect the decision outcome", "Every function called", "Every branch taken both ways"], a: 1, why: "<p>Modified Condition/Decision Coverage. For <code>if (a &amp;&amp; b)</code> it is not enough to take the branch both ways: you must show a case where changing <code>a</code> alone flips the result, and one where changing <code>b</code> alone does.</p><p>It comes from DO-178C level A and it is expensive, which is why it sits at the top of the scale rather than being a general recommendation.</p>" },
{ t: "emb-standards", d: 3, q: "A project followed good practice throughout but recorded very little. What happens at audit?", o: ["It passes, since the code is sound", "It fails, because the standards require demonstrated correctness rather than actual correctness", "It passes with observations", "The auditor reviews the code instead"], a: 1, why: "<p>The whole apparatus exists to make claims evidenced rather than asserted, so an unrecorded good decision is indistinguishable from no decision.</p><p>This is the part engineers find hardest to accept, and it is also why the recording has to happen as the work is done rather than reconstructed afterwards.</p>" },
{ t: "emb-standards", d: 3, q: "What determines which class or level a product needs?", o: ["The size of the codebase", "The severity of harm a failure could cause, with exposure and controllability", "The market it sells into", "The processor chosen"], a: 1, why: "<p>Every one of these schemes is a way of scaling rigour to consequence. Automotive ASIL adds exposure, meaning how often the situation arises, and controllability, meaning whether a driver could recover.</p><p>The useful implication is that a toy and an infusion pump should not share a process, so the first question on any project is which kind of thing it is.</p>" },

// ------------------------------------------------------------- emb-config
{ t: "emb-config", d: 1, q: "Why is a tagged commit insufficient to reproduce a released binary?", o: ["Tags can be moved or deleted", "Compiler version, flags, library versions, linker script and component versions all change the output", "Source drifts over time", "Git does not store binaries"], a: 1, why: "<p>The same source produces different machine code under a different toolchain, a different optimisation level, or a different version of a third-party component.</p><p>So the release has to pin all of it. A container image, a lock file, or a documented toolchain version with a checksum all work. Having none of them is the failure.</p>" },
{ t: "emb-config", d: 2, q: "Which archived artefact is most often discarded and most needed later?", o: ["The map file", "The ELF", "The source tag", "The build log"], a: 1, why: "<p>A fault address reported from the field is a bare number. Only the symbols from that exact build turn it into a function and a line.</p><p>Decoding against a slightly different binary is worse than having nothing, because it produces a confident answer pointing at the wrong code.</p>" },
{ t: "emb-config", d: 2, q: "Why include a 'dirty' flag in the build information?", o: ["To detect tampering in the field", "A build from a modified tree cannot be reproduced from the commit, and knowing that at once saves hours", "Git requires it", "For release statistics"], a: 1, why: "<p>Without it you spend a long time trying to understand why the source does not explain the behaviour, when the answer is that the binary was never built from that source.</p><p>It costs one byte and one line in the build script.</p>" },
{ t: "emb-config", d: 2, q: "What is the test that shows where your configuration management really stands?", o: ["Counting branches and tags", "Rebuilding a year-old release on a clean machine and comparing to the archived binary", "A review of the build script", "Checking the tags exist"], a: 1, why: "<p>Most projects fail it the first time, and the failures are exactly the ones you want to find outside an incident: an undeclared tool dependency, a component pulled from a branch rather than a tag, a file that only exists on one laptop.</p>" },
{ t: "emb-config", d: 2, q: "Why should a build for hardware revision B refuse to run on revision A?", o: ["To force upgrades", "Because half working is more dangerous than not working, since it passes casual testing", "To protect intellectual property", "Flash layouts differ"], a: 1, why: "<p>A mismatched build that boots and mostly behaves will get through a quick bench check and fail in the field on the one peripheral that moved.</p><p>Putting a hardware revision field in the image header and checking it at boot converts a subtle field failure into an obvious refusal.</p>" },
{ t: "emb-config", d: 2, q: "What should be logged at every boot?", o: ["The full configuration dump", "Firmware version, build hash and reset reason", "The stack usage", "Nothing, to save power"], a: 1, why: "<p>Those three lines answer the first questions of almost every field investigation: what is it running, was it built from a known commit, and how did it get here.</p><p>They cost almost nothing and their absence is felt every single time a unit comes back.</p>" },
{ t: "emb-config", d: 3, q: "Why keep a maintenance branch per released version in firmware specifically?", o: ["Git performs better", "You will need to ship a fix for 2.3 while 3.0 is in development, and some customers cannot take 3.0 at all", "It is required for tagging", "To avoid merge conflicts"], a: 1, why: "<p>A customer with validated or certified equipment may not be permitted to accept a version with new features, only a targeted fix.</p><p>Everything else about branching can stay boring: a main branch that always builds and passes, short-lived branches for changes, and a tag per release.</p>" },
{ t: "emb-config", d: 3, q: "What is the practical benefit of a byte-identical reproducible build?", o: ["Smaller binaries", "It proves the pinning is complete, because any unrecorded dependency shows up as a difference", "Faster builds", "Better compression"], a: 1, why: "<p>Reproducibility is a test of your configuration management rather than an end in itself. If something drifted that you did not pin, the output changes and you find out.</p><p>The usual obstacles are embedded timestamps and absolute paths, and both have compiler flags to control them.</p>" },
{ t: "emb-config", d: 3, q: "What does an SBOM let you answer that you otherwise cannot?", o: ["How large the binary is", "Whether a newly published vulnerability affects anything you shipped", "Who wrote each module", "How long the build takes"], a: 1, why: "<p>Without a list of components and exact versions, responding to an advisory means every team guessing, which is what made Ripple20 so slow to resolve across the industry.</p><p>It is also becoming a regulatory expectation rather than a nicety.</p>" },
{ t: "emb-config", d: 3, q: "Why does semantic versioning need adjusting for firmware?", o: ["It does not apply at all", "The compatibility that matters is with the protocol and the hardware rather than an API", "Firmware has no minor versions", "Patch numbers are unnecessary"], a: 1, why: "<p>A major bump in firmware usually means the host application or the board revision has to match, not that a function signature changed.</p><p>Making hardware compatibility an explicit field in the image header, checked at boot, is what stops that becoming a field problem.</p>" },

// --------------------------------------------------------------- emb-team
{ t: "emb-team", d: 1, q: "What is the most common complaint about an engineer's work on a team?", o: ["It is too slow", "Nobody knew where it stood", "It is over-engineered", "It has too many bugs"], a: 1, why: "<p>Short, regular, specific updates fix almost all of it: what is finished, what is not, and what somebody else can do about it.</p><p>The part people skip is the last one. An update that does not surface the question you are blocked on leaves the blockage in place.</p>" },
{ t: "emb-team", d: 2, q: "What makes a question easy for a colleague to answer?", o: ["Keeping it short", "Showing what you already tried and ruled out", "Asking in writing", "Asking the most senior person"], a: 1, why: "<p>'The chip ID reads 0xFF; the address is unshifted, pull-ups are 4k7, and the analyser shows a NAK on the address byte' gets an answer in minutes because it eliminates the obvious checks.</p><p>The underlying calculation on a team is an hour of someone's time now against two days of yours going the wrong way.</p>" },
{ t: "emb-team", d: 2, q: "Why agree a definition of done before starting a piece of firmware?", o: ["To produce burndown charts", "Different people assume different answers and the gap surfaces at the worst moment", "It is required by Scrum", "To make estimates accurate"], a: 1, why: "<p>Works on my bench once, works on three boards including the marginal one, has tests running in CI, handles the error paths, documentation and requirement updated, has run overnight.</p><p>Firmware has more ambiguity here than most software, and a short written definition agreed once removes an entire category of disagreement.</p>" },
{ t: "emb-team", d: 2, q: "How should you estimate work that includes hardware bring-up?", o: ["Add a blanket contingency", "Separate what you understand from what is genuinely discovery and estimate them differently", "Estimate the worst case", "Refuse to estimate"], a: 1, why: "<p>'The driver is about two days; the bring-up on the new board I cannot estimate until I have power on it, so give me half a day to find out' is honest and actionable.</p><p>A single blended number hides which half is uncertain, so nobody can plan around it.</p>" },
{ t: "emb-team", d: 2, q: "What should happen when you learn your estimate was wrong?", o: ["Work longer hours to make it", "Re-estimate out loud, with the reason, as soon as you know", "Wait until the deadline to raise it", "Reduce the scope quietly"], a: 1, why: "<p>An estimate that silently doubles is a problem for everyone downstream. One revised on day two with a reason is just information, and information early is what people can act on.</p><p>Quietly cutting scope is the worst of both, because the schedule looks fine and the product is not what was agreed.</p>" },
{ t: "emb-team", d: 2, q: "What is the most valuable part of a handover document?", o: ["The architecture overview", "What you tried that did not work", "The commit history", "The build instructions"], a: 1, why: "<p>It is the part nobody writes down and everybody repeats. A paragraph of dead ends can save the next person a week.</p><p>Close behind it is the non-obvious knowledge: which register needs writing twice, which board has the modification, which test fails for an unrelated reason.</p>" },
{ t: "emb-team", d: 2, q: "What turns a technical stand-off into something resolvable?", o: ["Deferring to seniority", "Saying specifically what evidence would change your mind", "Voting", "Escalating to a manager"], a: 1, why: "<p>'If the measurements show the latency is under 50 microseconds either way, I will drop it' converts an argument about opinions into an experiment with an outcome.</p><p>It also commits you in advance, which is what makes the other person willing to run it.</p>" },
{ t: "emb-team", d: 3, q: "A decision goes against you after a fair discussion. What is the professional response?", o: ["Keep raising it until it changes", "Say so plainly and commit to it", "Implement it badly to prove the point", "Document your objection and disengage"], a: 1, why: "<p>Continuing to relitigate a settled decision costs a team more than the decision usually does, and it makes your genuine objections easier to dismiss next time.</p><p>Disagree strongly during the discussion, then commit once it is made.</p>" },
{ t: "emb-team", d: 3, q: "Why is admitting a mistake quickly a professional skill rather than a weakness?", o: ["It makes people feel better", "Defending an untenable position is expensive for everyone and eventually obvious anyway", "It shortens meetings", "It transfers responsibility"], a: 1, why: "<p>'I was wrong about the interrupt priority, that is the cause, here is the fix' costs a moment and buys a large amount of trust.</p><p>The alternative burns other people's time on a conclusion you have already reached privately, and the delay is what damages credibility rather than the error.</p>" },
{ t: "emb-team", d: 3, q: "Why does accepting every review comment make you less useful?", o: ["It slows the merge", "It is a failure to contribute judgement, and it devalues your approvals too", "It creates more work", "Reviewers dislike it"], a: 1, why: "<p>A reviewer wants to know when they are wrong, because otherwise the code changes for no reason and the misunderstanding survives.</p><p>Pushing back with a reason, such as a datasheet requirement, ends the discussion productively. Agreeing with everything means nobody learns what you actually think.</p>" },

// --------------------------------------------------------- emb-postmortem
{ t: "emb-postmortem", d: 1, q: "Which incident step do engineers most often skip?", o: ["Diagnose", "Communicate", "Contain", "Verify the fix"], a: 1, why: "<p>The instinct is to go straight to root cause, which is the interesting part.</p><p>But a known problem communicated early is a manageable situation, and the same problem discovered by a customer is a completely different conversation with identical technical facts.</p>" },
{ t: "emb-postmortem", d: 1, q: "What is the correct first action when units are failing in the field?", o: ["Find the root cause", "Contain: halt the rollout, disable the feature, revert", "Collect logs from every unit", "Write the incident report"], a: 1, why: "<p>Stop the harm before understanding it. Containment is usually cheap and reversible, and it buys the time to investigate properly rather than under pressure.</p><p>Diagnosis without containment means the population of affected units keeps growing while you work.</p>" },
{ t: "emb-postmortem", d: 2, q: "Why not power up a returned unit immediately?", o: ["It may be damaged", "Doing so can destroy the crash record, the reset reason and the configuration as it was", "It voids the warranty", "It needs decontaminating first"], a: 1, why: "<p>A unit that has been reflashed to see if that fixes it can no longer tell you anything, and there is often exactly one.</p><p>Capture the reset reason, retained-RAM crash record, firmware version and build hash, logs and the current configuration before changing a thing.</p>" },
{ t: "emb-postmortem", d: 2, q: "Why reproduce a fault before fixing it?", o: ["To confirm the customer is right", "Without a reproduction you cannot distinguish a fix from a coincidence", "To measure how many units are affected", "To satisfy the incident process"], a: 1, why: "<p>Many changes alter timing incidentally, so a race can be suppressed rather than fixed and will return when something else shifts.</p><p>'It happened every twenty minutes before and has not in forty-eight hours since' is evidence. 'We changed something and it seems better' is not.</p>" },
{ t: "emb-postmortem", d: 2, q: "What is the technique for making an intermittent fault reproducible?", o: ["Run it for longer", "Raise the rate: faster bus, shorter timeouts, more load, temperature extremes", "Add more logging", "Test on more units"], a: 1, why: "<p>If the cause is a race or a resource limit, increasing the rate turns a weekly failure into a per-minute one, which makes it debuggable in an afternoon.</p><p>It also tends to identify which resource is short, because the thing you had to stress is usually the thing that is marginal.</p>" },
{ t: "emb-postmortem", d: 2, q: "Why keep asking why past the first cause you find?", o: ["To fill in the report", "The first answer is usually a symptom, and only the deeper ones prevent the next incident", "To identify who was responsible", "Auditors require five levels"], a: 1, why: "<p>'An ISR used the blocking semaphore API' produces 'fix that call'. 'There was no review item for interrupt-context calls and configASSERT was off in release builds' produces two changes that also catch the ones you have not found yet.</p><p>Stop when you reach something you can actually change.</p>" },
{ t: "emb-postmortem", d: 2, q: "Why is a blameless postmortem practical rather than merely kind?", o: ["It is not, accountability matters", "If people are blamed, the next incident is reported later or not at all", "It is faster to write", "It satisfies the auditor"], a: 1, why: "<p>The information you need comes from people volunteering what they did, and that supply dries up the first time it is punished.</p><p>The productive assumption is that a person making a mistake is a given, so the question is what let the mistake reach the field. That points at a missing test or check, which you can fix. 'Be more careful' is not a corrective action.</p>" },
{ t: "emb-postmortem", d: 3, q: "What is the part of an incident report most often abandoned?", o: ["The timeline", "The corrective actions with an owner and a date", "The impact assessment", "The root cause"], a: 1, why: "<p>And they are the entire point. A report that produces no change is a document rather than a process, and the same failure recurs with a second document attached.</p><p>An owner and a date are what distinguish an action from an intention.</p>" },
{ t: "emb-postmortem", d: 3, q: "Which design feature most improves your ability to diagnose a field failure?", o: ["More flash", "A crash record in retained RAM, reported on the next boot", "Faster logging", "A second UART"], a: 1, why: "<p>It survives the reset and turns 'it rebooted' into a fault address, a register dump and a stack trace.</p><p>Paired with the reset reason, the build hash, and counters for anything the firmware silently recovers from, it is the difference between a report you can act on and one you can only speculate about.</p>" },
{ t: "emb-postmortem", d: 3, q: "Why keep counters for retries, CRC failures and timeouts the firmware recovers from?", o: ["For performance tuning", "Silent recovery hides a degrading system until it fails outright", "To fill the log", "Regulators require them"], a: 1, why: "<p>A link that retries twice per second still works, right up to the day it does not, and by then the trend that would have explained it was never recorded.</p><p>Exposing the counters through one diagnostic command makes a slow degradation visible while it is still cheap to address.</p>" }

]);
