BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// ----------------------------------------------------------- emb-z-model
{ t: "emb-z-model", d: 1, q: "What is the division of responsibility between devicetree and Kconfig?", o: ["Devicetree is for drivers, Kconfig for the application", "Devicetree describes the hardware and its wiring; Kconfig selects which software is compiled in", "They are interchangeable", "Kconfig covers the board, devicetree the SoC"], a: 1, why: "<p>Almost every early Zephyr frustration is an attempt to fix a hardware-description problem with a CONFIG_ symbol.</p><p>No Kconfig setting will make a node appear if it is missing from the devicetree or is not <code>status = \"okay\"</code>.</p>" },
{ t: "emb-z-model", d: 2, q: "How does Zephyr's devicetree differ from Linux's?", o: ["Different syntax", "Zephyr compiles it to constants at build time, so there is no blob and no runtime parser", "Zephyr parses it at boot", "Zephyr stores it in a separate flash region"], a: 1, why: "<p><code>DT_NODELABEL()</code> resolves during the build, so what reaches the binary is a plain address and a config struct.</p><p>The payoff is no runtime cost and a compile error instead of a boot failure. The cost is that nothing about the hardware can change after the build.</p>" },
{ t: "emb-z-model", d: 2, q: "Which way do Zephyr thread priorities run?", o: ["Higher number is more urgent, as in FreeRTOS", "Lower number is more urgent, and negative values are cooperative", "All threads share one priority", "Priority follows creation order"], a: 1, why: "<p>The opposite of FreeRTOS, which makes it a reliable bug when porting.</p><p>A cooperative thread runs until it yields or blocks and cannot be preempted by another thread, though interrupts still occur.</p>" },
{ t: "emb-z-model", d: 2, q: "What is the structural difference between Zephyr and FreeRTOS?", o: ["Zephyr is faster", "FreeRTOS is a kernel added to a vendor SDK; Zephyr is the whole system including build, config, drivers and subsystems", "FreeRTOS has no threads", "Zephyr has no scheduler"], a: 1, why: "<p>With FreeRTOS you still write against the ST HAL or the Nordic SDK, so porting means rewriting the driver layer.</p><p>In Zephyr the driver layer is the part that ports, which is why the same <code>i2c_write_read()</code> works across vendors.</p>" },
{ t: "emb-z-model", d: 2, q: "Which four files decide most of a Zephyr application's behaviour?", o: ["main.c, Makefile, linker script, startup", "CMakeLists.txt, prj.conf, the devicetree overlay, and the board you build for", "Kconfig, west.yml, main.c, README", "prj.conf alone"], a: 1, why: "<p>Sources come from CMakeLists, features from prj.conf, hardware from the overlay, and the base hardware from the board argument to <code>west build -b</code>.</p>" },
{ t: "emb-z-model", d: 3, q: "What is the honest downside of Zephyr's build-time configuration model?", o: ["Larger binaries", "A steep front-loaded learning curve, and a large share of debugging time spent on the build system rather than the code", "It cannot be used commercially", "It has no driver model"], a: 1, why: "<p>You also inherit someone else's driver bugs rather than your own, which is usually a good trade and occasionally not.</p><p>Saying this plainly in an interview reads better than claiming the curve is gentle.</p>" },
{ t: "emb-z-model", d: 3, q: "What does a cooperative thread in Zephyr guarantee?", o: ["It cannot be interrupted at all", "It will not be preempted by another thread, though interrupts still occur", "It has the highest priority", "It runs on a separate core"], a: 1, why: "<p>Useful for a short critical sequence without a mutex, dangerous for anything long, because nothing else at any priority runs until it yields or blocks.</p>" },
{ t: "emb-z-model", d: 3, q: "Why does Zephyr's driver API make off-target testing easier than a vendor HAL?", o: ["It runs faster on a host", "Drivers reach hardware through a device pointer and an API table, which is already a seam you can substitute", "It has no hardware dependencies", "It uses no pointers"], a: 1, why: "<p>The indirection that exists for portability is exactly the injection point a test needs, so a fake bus can be supplied without changing the driver.</p><p>Zephyr also has a native_sim target that runs the whole application on the host.</p>" },

// ------------------------------------------------------ emb-z-devicetree
{ t: "emb-z-devicetree", d: 1, q: "What does <code>status = \"okay\"</code> control?", o: ["Whether the driver reports errors", "Whether the node is built at all: without it no device instance is generated", "Initialisation order", "Whether the node is documented"], a: 1, why: "<p>It is why a <code>DT_N_...</code> undeclared error means 'does that node exist and is it enabled', rather than anything about your C.</p><p>This is the most common Zephyr build failure by a wide margin.</p>" },
{ t: "emb-z-devicetree", d: 2, q: "What does the <code>compatible</code> property do?", o: ["Records the manufacturer", "Names the binding, which is what selects the driver", "Sets the bus speed", "Declares backwards compatibility"], a: 1, why: "<p>It must match a binding Zephyr knows about, either in-tree or in your application's <code>dts/bindings</code> directory.</p><p>A typo produces a node with no driver behind it and no obvious error.</p>" },
{ t: "emb-z-devicetree", d: 2, q: "What is the difference between the .dts, .dtsi and .overlay layers?", o: ["Nothing, they are aliases", "The .dtsi holds SoC fragments, the .dts is the board, and the .overlay is your application's patch on top", "They are alternatives, only one is used", "The overlay replaces the board file"], a: 1, why: "<p>They compose in that order, so an overlay patches the board rather than replacing it.</p><p>That is why a typical overlay is only a few lines: reopen a node by label and change what you need.</p>" },
{ t: "emb-z-devicetree", d: 2, q: "Why prefer <code>gpio_pin_configure_dt(&amp;spec, ...)</code> over the raw call?", o: ["It is faster", "The device, pin and flags travel together, and GPIO_ACTIVE_LOW is handled for you", "It works without devicetree", "It uses less RAM"], a: 1, why: "<p>Setting the pin <b>active</b> lights the LED whichever way it is wired, so identical code works on boards that differ.</p><p>It also removes the class of bug where the port and the pin number drift out of step.</p>" },
{ t: "emb-z-devicetree", d: 2, q: "An overlay appears not to apply. What do you check first?", o: ["The Kconfig symbols", "build/zephyr/zephyr.dts, the final merged tree", "The linker map", "The board schematic"], a: 1, why: "<p>It answers in seconds whether the file was picked up and what the merged result actually says.</p><p>Overlays are found by filename, so a misnamed board overlay is silently ignored.</p>" },
{ t: "emb-z-devicetree", d: 2, q: "What is the point of <code>DT_ALIAS(led0)</code> rather than a node label?", o: ["It is shorter", "Boards define the aliases, so a portable sample never has to name a pin or a controller", "Aliases are faster to resolve", "Labels cannot be used in C"], a: 1, why: "<p>The board file says which physical LED is <code>led0</code>, and the sample compiles unchanged on any board that defines it.</p><p><code>DT_CHOSEN</code> does the same thing by role, such as which UART is the console.</p>" },
{ t: "emb-z-devicetree", d: 3, q: "A UART is enabled in the devicetree but outputs nothing. What is commonly missing?", o: ["The baud rate", "A pinctrl entry saying which pins it uses, referenced from the peripheral node", "The Kconfig symbol", "A ground connection"], a: 1, why: "<p>On most modern SoCs the peripheral and the pin routing are described separately, so enabling one without the other builds cleanly and does nothing.</p>" },
{ t: "emb-z-devicetree", d: 3, q: "How does a devicetree property name become a C identifier?", o: ["Unchanged", "Hyphens become underscores, so clock-frequency is read as clock_frequency", "It is upper-cased", "It gains a DT_ prefix"], a: 1, why: "<p>So <code>DT_PROP(node, clock_frequency)</code> reads the <code>clock-frequency</code> property.</p><p><code>DT_PROP_OR</code> supplies a default when the property may be absent.</p>" },
{ t: "emb-z-devicetree", d: 3, q: "What does <code>reg</code> mean in a devicetree node?", o: ["A CPU register", "The address on the parent bus: an I2C slave address, or a base address and size for a memory-mapped peripheral", "A registration flag", "The register map version"], a: 1, why: "<p>Its meaning depends on the parent, which is why an I2C child's reg is one cell and a memory-mapped peripheral's is usually two.</p>" },

// --------------------------------------------------------- emb-z-kconfig
{ t: "emb-z-kconfig", d: 1, q: "You add a CONFIG_ symbol to prj.conf and nothing changes. What is the usual cause?", o: ["A typo in the value", "Its dependencies are not met, so Kconfig silently ignores it", "prj.conf is not read", "It needs a power cycle"], a: 1, why: "<p>Kconfig does not warn about this, so the line sits there looking correct while the feature is absent.</p><p>Check <code>build/zephyr/.config</code>: if the symbol is missing or has a different value, something it depends on is not enabled.</p>" },
{ t: "emb-z-kconfig", d: 2, q: "Which file records what the build actually used?", o: ["prj.conf", "build/zephyr/.config", "CMakeLists.txt", "the board .dts"], a: 1, why: "<p>It is the merged result of prj.conf, per-board conf files, Kconfig defaults and any other layers.</p><p>prj.conf is only one input, which is why grepping .config settles arguments that reading prj.conf cannot.</p>" },
{ t: "emb-z-kconfig", d: 2, q: "Why enable CONFIG_ASSERT during development?", o: ["It speeds up the build", "Zephyr's internal __ASSERT checks are compiled out by default, so API misuse it could catch goes unreported", "It enables logging", "The shell requires it"], a: 1, why: "<p>Passing a non-zero timeout to a kernel call from an ISR, for instance, is undefined behaviour that Zephyr can detect and by default says nothing about.</p><p>One line, and a large amount of free diagnosis.</p>" },
{ t: "emb-z-kconfig", d: 2, q: "What is the right use of menuconfig?", o: ["To set the final configuration", "To discover what a symbol depends on, then write the answer into prj.conf", "To edit the devicetree", "To flash the board"], a: 1, why: "<p>Its search shows the dependency chain and what currently blocks a symbol, which is far quicker than reading Kconfig files.</p><p>Its changes go to <code>build/zephyr/.config</code> and are lost on a pristine build, so they are not a place to keep configuration.</p>" },
{ t: "emb-z-kconfig", d: 2, q: "A devicetree node is status okay but the device never initialises. What is likely missing?", o: ["A pull-up resistor", "The Kconfig symbol that compiles the driver in", "An alias", "A pinctrl entry"], a: 1, why: "<p>You need both halves: the node says the hardware exists, the CONFIG_ symbol says the software to drive it should be built.</p><p>The mirror-image failure is a driver selected with no node, which builds a driver with nothing to bind to.</p>" },
{ t: "emb-z-kconfig", d: 3, q: "What does <code>west build -p always</code> do, and when is it worth it?", o: ["Builds faster", "Forces a pristine build, worth it whenever a config or overlay change appears to have no effect", "Enables parallel jobs", "Rebuilds only changed files"], a: 1, why: "<p>Changing prj.conf or an overlay does not always trigger a full reconfigure, and the symptom is a change that seems to be ignored.</p><p>Thirty seconds of rebuild against an afternoon of confusion.</p>" },
{ t: "emb-z-kconfig", d: 3, q: "What does CONFIG_HEAP_MEM_POOL_SIZE control?", o: ["The stack size", "The pool that k_malloc allocates from", "The log buffer", "The Bluetooth buffers"], a: 1, why: "<p>Zephyr has no heap at all unless you ask for one, which is a reasonable default on a microcontroller.</p><p>Subsystems that allocate internally will fail quietly at init if it is zero, which looks like a driver problem.</p>" },
{ t: "emb-z-kconfig", d: 3, q: "Where do per-board Kconfig additions for an application belong?", o: ["Only in prj.conf", "In boards/&lt;board&gt;.conf alongside the application", "In the Zephyr tree", "In CMakeLists.txt"], a: 1, why: "<p>It merges on top of prj.conf for that board only, which is how one application supports several targets without conditionals.</p><p>The same pattern applies to <code>boards/&lt;board&gt;.overlay</code> for devicetree.</p>" },

// --------------------------------------------------------- emb-z-drivers
{ t: "emb-z-drivers", d: 2, q: "Why call <code>device_is_ready()</code> when DEVICE_DT_GET never returns NULL?", o: ["To initialise the device", "It resolves at build time and cannot know whether the device's init function succeeded", "To take a reference count", "Only ISRs need it"], a: 1, why: "<p>A device whose init failed is present but unusable, and calling into it is undefined.</p><p>The check is a load and a compare, and skipping it is the most common Zephyr driver bug.</p>" },
{ t: "emb-z-drivers", d: 2, q: "Why can a PRE_KERNEL init function not sleep?", o: ["It runs too early to be interrupted", "There is no scheduler yet, so there is nothing to sleep on", "Sleeping is forbidden in all drivers", "It runs in an ISR"], a: 1, why: "<p>A sensor needing a settle time therefore initialises at POST_KERNEL, or defers the wait to first use.</p><p>PRE_KERNEL is for clocks, the tick source and early serial, in that order.</p>" },
{ t: "emb-z-drivers", d: 2, q: "What does <code>DT_INST_FOREACH_STATUS_OKAY</code> achieve?", o: ["Checks that all nodes are enabled", "Instantiates the driver once per matching enabled devicetree node", "Iterates devices at runtime", "Validates the bindings"], a: 1, why: "<p>Two identical sensors on the bus gives two instances from one piece of code, with no list to maintain.</p><p>It is the mechanism that makes Zephyr drivers instance-based rather than singletons.</p>" },
{ t: "emb-z-drivers", d: 2, q: "Why is a device's config const and its data not?", o: ["Style convention", "config holds pins and addresses that never change so it lives in flash; data holds runtime state so it must be in RAM", "config is shared between instances", "data is faster to reach"], a: 1, why: "<p>On a part with far more flash than RAM this is not stylistic: a non-const config costs RAM plus a startup copy, for every instance.</p>" },
{ t: "emb-z-drivers", d: 2, q: "What convention do Zephyr APIs use for errors?", o: ["Positive error codes", "Zero for success and negative errno values such as -EIO, -EINVAL and -ENODEV", "A global errno", "Boolean returns"], a: 1, why: "<p>Returning your own scheme from a driver breaks every caller's expectations.</p><p><code>-ENOTSUP</code> for an API call you do not implement is the one people forget.</p>" },
{ t: "emb-z-drivers", d: 3, q: "What makes <code>i2c_write_read()</code> the same call on Nordic and ST silicon?", o: ["A preprocessor switch", "The device's api pointer: the inline function calls through a per-driver function table", "A runtime lookup by name", "Vendor compatibility layers"], a: 1, why: "<p>It is the config and handle pattern with the parts named: a const config in flash, mutable data in RAM, and an api table making it polymorphic.</p>" },
{ t: "emb-z-drivers", d: 3, q: "Where do you put a binding for a part Zephyr does not know about?", o: ["In the Zephyr tree only", "In the application's dts/bindings directory, or a directory named by DTS_ROOT", "In prj.conf", "In CMakeLists.txt"], a: 1, why: "<p>A YAML file describing the compatible string and its properties. Without one, the <code>compatible</code> in your node matches nothing and the node has no driver.</p>" },
{ t: "emb-z-drivers", d: 3, q: "Why does init priority matter within an initialisation level?", o: ["It sets the thread priority", "It orders the init functions, so a driver depending on another must initialise after it", "It affects interrupt latency", "It controls the stack size"], a: 1, why: "<p>A sensor on an I2C bus must come after the bus controller. Getting it wrong shows as <code>device_is_ready()</code> returning false for a device that is otherwise correct.</p>" },

// --------------------------------------------------------- emb-z-threads
{ t: "emb-z-threads", d: 2, q: "What is the danger of <code>k_work_submit()</code>?", o: ["It can fail silently", "It uses the shared system work queue, so blocking in your handler stalls Bluetooth, networking and logging", "It runs in interrupt context", "It allocates memory"], a: 1, why: "<p>The symptoms look unrelated to the change you made: dropped BLE connections, missing log lines, a timer callback that never runs.</p><p>If the handler can block, start your own queue with <code>k_work_queue_start</code> and submit to that.</p>" },
{ t: "emb-z-threads", d: 2, q: "In which context does a <code>k_timer</code> callback run?", o: ["A dedicated thread", "Interrupt context, so every ISR restriction applies", "The system work queue", "The thread that started it"], a: 1, why: "<p>Which is why <code>k_work_delayable</code> is the better default: it runs in a thread and may block.</p><p>Use <code>k_timer</code> only when you genuinely need the lower latency, because the context restriction is easy to forget later.</p>" },
{ t: "emb-z-threads", d: 2, q: "Which kernel call is legal from an ISR?", o: ["k_mutex_lock", "k_sem_give", "k_sleep", "k_msgq_get with a timeout"], a: 1, why: "<p>Anything that can block is forbidden, which rules out mutexes entirely and any call with a non-zero timeout.</p><p><code>k_msgq_put</code> with <code>K_NO_WAIT</code> is fine; the same call with a timeout is not.</p>" },
{ t: "emb-z-threads", d: 2, q: "How should you size a Zephyr thread stack?", o: ["Start at 1024 and raise it if it crashes", "Measure with CONFIG_THREAD_ANALYZER under the worst case you can construct, then add margin", "Use the largest that fits", "Match the other threads"], a: 1, why: "<p>Guessing gives you either waste or a corruption that surfaces as something else entirely.</p><p>Logging and floating point are both large consumers, and the deepest call path is rarely the one you expected.</p>" },
{ t: "emb-z-threads", d: 2, q: "When is k_msgq preferable to k_fifo?", o: ["Never", "When the items are small and fixed size, because copying removes the ownership question", "For large buffers", "When the producer is an ISR"], a: 1, why: "<p><code>k_fifo</code> passes items by reference with no copy, so someone has to own the memory and free it at the right time.</p><p>A message queue trades a copy for that whole class of bug disappearing.</p>" },
{ t: "emb-z-threads", d: 3, q: "What does a mutex give you that a binary semaphore does not?", o: ["Faster locking", "Ownership and priority inheritance, so a low-priority holder is boosted while a high-priority thread waits", "Use from an ISR", "Counting"], a: 1, why: "<p>Priority inversion is the reason: without inheritance, a medium-priority thread can preempt the low-priority holder and block the high-priority waiter indefinitely.</p><p>The ownership rule also means only the locking thread may unlock it.</p>" },
{ t: "emb-z-threads", d: 3, q: "What is <code>k_work_delayable</code> usually used for?", o: ["Long computations", "A timeout or a retry, without dedicating a thread to it", "Interrupt handling", "Memory allocation"], a: 1, why: "<p>Submit it with a delay, cancel it if the thing you were waiting for arrives. It runs in a thread so it may block, unlike a <code>k_timer</code> callback.</p>" },
{ t: "emb-z-threads", d: 3, q: "What does k_poll let you do that a single semaphore cannot?", o: ["Poll faster", "Wait on several objects of different kinds at once, so one thread can service multiple sources", "Avoid blocking", "Work from an ISR"], a: 1, why: "<p>Without it, a thread waiting on a semaphore cannot also notice a message queue, so you end up either polling with timeouts or adding threads.</p><p><code>k_event</code> is the lighter option when the sources are all flags you control.</p>" },

// ----------------------------------------------------------- emb-z-build
{ t: "emb-z-build", d: 1, q: "What are west's two distinct jobs?", o: ["Building and flashing", "A multi-repository manager driven by west.yml, and a build front end wrapping CMake", "Configuring and linking", "Testing and deployment"], a: 1, why: "<p>The manifest pins Zephyr and every module by revision, so a workspace is defined by one file rather than by whatever people happened to clone.</p><p>That is the part that matters for reproducible builds.</p>" },
{ t: "emb-z-build", d: 2, q: "Which build target tells you where the flash went?", o: ["menuconfig", "rom_report", "guiconfig", "usage"], a: 1, why: "<p>It breaks the image down by module and file, and <code>ram_report</code> does the same for RAM.</p><p>They turn 'it does not fit' from a guess into a list, and most people never discover them.</p>" },
{ t: "emb-z-build", d: 2, q: "In a Zephyr CMakeLists.txt, why add sources to <code>app</code> rather than define an executable?", o: ["Convention only", "Zephyr already defines that target, because the link, the linker script and the image layout are its job", "It compiles faster", "CMake requires it"], a: 1, why: "<p>Which is why a Zephyr application's CMakeLists file is about four lines: find the package, name the project, add your sources.</p>" },
{ t: "emb-z-build", d: 2, q: "You see 'undefined reference' to a driver function. What is the usual cause?", o: ["A missing include", "The Kconfig symbol that compiles that driver in is not set", "A devicetree node is disabled", "The linker script is wrong"], a: 1, why: "<p>The driver's source simply is not in the build. Contrast with a <code>DT_N_...</code> undeclared error, which means the node is missing or not okay.</p><p>The two failure shapes point at different files, which is what makes them worth telling apart.</p>" },
{ t: "emb-z-build", d: 2, q: "What is sysbuild for?", o: ["Faster builds", "Building several images together, such as an application plus MCUboot, so signing and partitioning agree", "Static analysis", "Running tests"], a: 1, why: "<p>The bootloader and the application have to agree on partition layout and signing keys, and doing that by hand across two separate builds is error-prone.</p><p>If you are shipping firmware update, you will meet it.</p>" },
{ t: "emb-z-build", d: 3, q: "What does BOARD_ROOT do?", o: ["Sets the build directory", "Points at a directory containing your own board definitions, so -b my_board works like a built-in one", "Selects the toolchain", "Chooses the linker script"], a: 1, why: "<p>A custom board is a directory with a .dts, a Kconfig.board, a _defconfig and a YAML description.</p><p>The frequent failure is the directory name and the .dts name disagreeing, which reports as 'board not found'.</p>" },
{ t: "emb-z-build", d: 3, q: "Which generated files answer most 'why is it doing that' questions?", o: ["The source files", "build/zephyr/zephyr.dts, build/zephyr/.config and the map file", "prj.conf and the overlay", "west.yml"], a: 1, why: "<p>The inputs tell you your intention; the generated output tells you what the build actually concluded.</p><p>Opening them first rather than last is the single biggest time saver in Zephyr work.</p>" },
{ t: "emb-z-build", d: 3, q: "Why does the west manifest matter for reproducibility?", o: ["It caches downloads", "It pins Zephyr and every module to a specific revision, so the whole workspace is defined by one file", "It compresses the tree", "It validates licences"], a: 1, why: "<p>Without it, 'which Zephyr' is answered by whatever each engineer cloned and when.</p><p>It is the Zephyr equivalent of pinning your toolchain, and it belongs in the release archive.</p>" },

// ----------------------------------------------------------- emb-z-debug
{ t: "emb-z-debug", d: 2, q: "Your log stops several lines before a crash. What is the fix?", o: ["Increase the log buffer", "Switch to CONFIG_LOG_MODE_IMMEDIATE, because deferred messages still queued when the fault hits are never printed", "Lower the log level", "Use a faster UART"], a: 1, why: "<p>Deferred logging formats in the log thread, which is cheap at the call site and lossy at exactly the wrong moment.</p><p>Immediate costs performance and changes timing, which is the trade you want while chasing a fault.</p>" },
{ t: "emb-z-debug", d: 2, q: "What does the shell's <code>device list</code> command tell you?", o: ["The devicetree source", "Every device and whether it is ready, which is the fastest answer to 'is my sensor there'", "The Kconfig settings", "Connected USB devices"], a: 1, why: "<p>With <code>i2c scan</code> it replaces the small test program you were about to write, and <code>kernel threads</code> and <code>kernel stacks</code> do the same for thread questions.</p>" },
{ t: "emb-z-debug", d: 2, q: "Why set CONFIG_RESET_ON_FATAL_ERROR=n while developing?", o: ["It boots faster", "Resetting destroys the state you needed, and the device comes back looking healthy while rebooting in a loop", "Logging requires it", "It enables the shell"], a: 1, why: "<p>Staying stopped lets you attach a debugger and look at the actual fault.</p><p>In production you usually want the opposite, so it belongs in a development configuration rather than in prj.conf permanently.</p>" },
{ t: "emb-z-debug", d: 2, q: "How does CONFIG_STACK_SENTINEL help?", o: ["It grows stacks automatically", "It writes a known value at the end of each stack and checks it on context switch, turning silent corruption into a named error", "It measures peak usage", "It relocates stacks"], a: 1, why: "<p>An overflow otherwise corrupts whatever is adjacent, so the symptom is a variable changing on its own or a fault in unrelated code.</p><p>With an MPU, <code>CONFIG_HW_STACK_PROTECTION</code> is better still because it faults at the moment of overflow.</p>" },
{ t: "emb-z-debug", d: 2, q: "Why is RTT worth setting up as a logging backend?", o: ["It is encrypted", "It runs over the debug probe with no extra pins, and is fast enough not to distort timing much", "It works without a debugger", "It compresses the output"], a: 1, why: "<p>Useful when UART pins are scarce, and more importantly when the logging rate is high enough that a UART backend changes the behaviour you are trying to observe.</p>" },
{ t: "emb-z-debug", d: 3, q: "Which two settings most improve a Zephyr fault dump?", o: ["CONFIG_LOG and CONFIG_SHELL", "CONFIG_THREAD_NAME and CONFIG_EXCEPTION_STACK_TRACE", "CONFIG_ASSERT and CONFIG_BT", "CONFIG_NVS and CONFIG_SETTINGS"], a: 1, why: "<p>One names the faulting thread instead of printing an address, the other adds a call trace.</p><p>Then <code>addr2line</code> against the archived ELF for that exact build turns the addresses into files and lines.</p>" },
{ t: "emb-z-debug", d: 3, q: "What is the value of per-module log levels?", o: ["Smaller binaries only", "You can turn one module to debug and leave the rest at warning, so the interesting output is not buried", "Faster logging", "They are required by the subsystem"], a: 1, why: "<p><code>LOG_MODULE_REGISTER(name, CONFIG_..._LOG_LEVEL)</code> is what enables it, and the level can also be changed at runtime from the shell.</p>" },
{ t: "emb-z-debug", d: 3, q: "A variable changes value with nothing writing to it. What should you suspect first on Zephyr?", o: ["A compiler bug", "A stack overflow in an adjacent thread corrupting it", "A missing volatile", "Cache incoherency"], a: 1, why: "<p>Stacks are allocated next to each other, so an overflow lands in whatever follows and the symptom appears far from the cause.</p><p><code>CONFIG_STACK_SENTINEL</code> or hardware stack protection converts it into an immediate named error.</p>" }

]);
