BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// ----------------------------------------------------------- emb-z-model
{ t: "emb-z-model", d: 1, q: "What is the division of responsibility between devicetree and Kconfig?", o: ["Devicetree for drivers, Kconfig for the app", "Hardware wiring, versus what is compiled in", "They are interchangeable in practice", "Kconfig covers the board, devicetree the SoC"], a: 1, why: "<p>Almost every early Zephyr frustration is an attempt to fix a hardware-description problem with a CONFIG_ symbol.</p><p>No Kconfig setting will make a node appear if it is missing from the devicetree or is not <code>status = \"okay\"</code>.</p>" },
{ t: "emb-z-model", d: 2, q: "How does Zephyr's devicetree differ from Linux's?", o: ["The syntax differs between the two", "Zephyr compiles it to constants at build", "Zephyr parses the blob at boot", "Zephyr keeps it in its own flash region"], a: 1, why: "<p><code>DT_NODELABEL()</code> resolves during the build, so what reaches the binary is a plain address and a config struct.</p><p>The payoff is no runtime cost and a compile error instead of a boot failure. The cost is that nothing about the hardware can change after the build.</p>" },
{ t: "emb-z-model", d: 2, q: "Which way do Zephyr thread priorities run?", o: ["A higher number means more urgent, as in FreeRTOS", "Lower is more urgent; negative is cooperative", "All threads share a single priority", "Priority follows the order of creation"], a: 1, why: "<p>The opposite of FreeRTOS, which makes it a reliable bug when porting.</p><p>A cooperative thread runs until it yields or blocks and cannot be preempted by another thread, though interrupts still occur.</p>" },
{ t: "emb-z-model", d: 2, q: "What is the structural difference between Zephyr and FreeRTOS?", o: ["Zephyr is measurably faster in every respect", "FreeRTOS is a kernel; Zephyr is the system", "FreeRTOS has no thread support", "Zephyr has no scheduler of its own"], a: 1, why: "<p>With FreeRTOS you still write against the ST HAL or the Nordic SDK, so porting means rewriting the driver layer.</p><p>In Zephyr the driver layer is the part that ports, which is why the same <code>i2c_write_read()</code> works across vendors.</p>" },
{ t: "emb-z-model", d: 2, q: "Which four files decide most of a Zephyr application's behaviour?", o: ["main.c, Makefile, linker script, startup", "CMakeLists, prj.conf, overlay, board", "Kconfig, west.yml, main.c and README", "prj.conf on its own, mostly"], a: 1, why: "<p>Sources come from CMakeLists, features from prj.conf, hardware from the overlay, and the base hardware from the board argument to <code>west build -b</code>.</p>" },
{ t: "emb-z-model", d: 3, q: "What is the honest downside of Zephyr's build-time configuration model?", o: ["Noticeably larger output binaries", "A steep curve, and build-system debugging", "It cannot be used commercially", "It has no unified driver model"], a: 1, why: "<p>You also inherit someone else's driver bugs rather than your own, which is usually a good trade and occasionally not.</p><p>Saying this plainly in an interview reads better than claiming the curve is gentle.</p>" },
{ t: "emb-z-model", d: 3, q: "What does a cooperative thread in Zephyr guarantee?", o: ["It cannot be interrupted at all", "No thread preempts it; interrupts still do", "It runs at the highest priority", "It is scheduled onto a completely separate core"], a: 1, why: "<p>Useful for a short critical sequence without a mutex, dangerous for anything long, because nothing else at any priority runs until it yields or blocks.</p>" },
{ t: "emb-z-model", d: 3, q: "Why does Zephyr's driver API make off-target testing easier than a vendor HAL?", o: ["It simply runs faster on a host", "A device pointer and API table is a seam", "It has no hardware dependencies whatsoever", "It avoids pointers altogether"], a: 1, why: "<p>The indirection that exists for portability is exactly the injection point a test needs, so a fake bus can be supplied without changing the driver.</p><p>Zephyr also has a native_sim target that runs the whole application on the host.</p>" },

// ------------------------------------------------------ emb-z-devicetree
{ t: "emb-z-devicetree", d: 1, q: "What does <code>status = \"okay\"</code> control?", o: ["Whether the driver reports errors", "Whether the node is built at all", "The order it is initialised in", "Whether the node is documented"], a: 1, why: "<p>It is why a <code>DT_N_...</code> undeclared error means 'does that node exist and is it enabled', rather than anything about your C.</p><p>This is the most common Zephyr build failure by a wide margin.</p>" },
{ t: "emb-z-devicetree", d: 2, q: "What does the <code>compatible</code> property do?", o: ["Records the part's manufacturer", "Names the binding, which picks the driver", "Sets the speed of the bus", "Declares backwards compatibility with older parts"], a: 1, why: "<p>It must match a binding Zephyr knows about, either in-tree or in your application's <code>dts/bindings</code> directory.</p><p>A typo produces a node with no driver behind it and no obvious error.</p>" },
{ t: "emb-z-devicetree", d: 2, q: "What is the difference between the .dts, .dtsi and .overlay layers?", o: ["Nothing: the three are aliases", "SoC fragments, board, your patch", "Alternatives: only one is ever used", "The overlay replaces the board file"], a: 1, why: "<p>They compose in that order, so an overlay patches the board rather than replacing it.</p><p>That is why a typical overlay is only a few lines: reopen a node by label and change what you need.</p>" },
{ t: "emb-z-devicetree", d: 2, q: "Why prefer <code>gpio_pin_configure_dt(&amp;spec, ...)</code> over the raw call?", o: ["It executes faster at run time", "Device, pin and flags travel together", "It works without any devicetree present", "It uses less RAM per pin used"], a: 1, why: "<p>Setting the pin <b>active</b> lights the LED whichever way it is wired, so identical code works on boards that differ.</p><p>It also removes the class of bug where the port and the pin number drift out of step.</p>" },
{ t: "emb-z-devicetree", d: 2, q: "An overlay appears not to apply. What do you check first?", o: ["Which of the Kconfig symbols have been set", "build/zephyr/zephyr.dts, the merged tree", "The linker map for the build", "The schematic for that board"], a: 1, why: "<p>It answers in seconds whether the file was picked up and what the merged result actually says.</p><p>Overlays are found by filename, so a misnamed board overlay is silently ignored.</p>" },
{ t: "emb-z-devicetree", d: 2, q: "What is the point of <code>DT_ALIAS(led0)</code> rather than a node label?", o: ["It is shorter to type than a label", "Boards define aliases, so samples port", "Aliases resolve faster at build time", "Labels cannot be referenced from C"], a: 1, why: "<p>The board file says which physical LED is <code>led0</code>, and the sample compiles unchanged on any board that defines it.</p><p><code>DT_CHOSEN</code> does the same thing by role, such as which UART is the console.</p>" },
{ t: "emb-z-devicetree", d: 3, q: "A UART is enabled in the devicetree but outputs nothing. What is commonly missing?", o: ["The baud rate property is missing", "A pinctrl entry naming the pins", "The Kconfig symbol is not set", "The ground connection is absent"], a: 1, why: "<p>On most modern SoCs the peripheral and the pin routing are described separately, so enabling one without the other builds cleanly and does nothing.</p>" },
{ t: "emb-z-devicetree", d: 3, q: "How does a devicetree property name become a C identifier?", o: ["It is used entirely unchanged", "Hyphens become underscores", "It is converted to upper case", "It gains a DT_ prefix as well"], a: 1, why: "<p>So <code>DT_PROP(node, clock_frequency)</code> reads the <code>clock-frequency</code> property.</p><p><code>DT_PROP_OR</code> supplies a default when the property may be absent.</p>" },
{ t: "emb-z-devicetree", d: 3, q: "What does <code>reg</code> mean in a devicetree node?", o: ["A CPU register number on the core", "The address on the parent bus", "A flag saying it is registered", "The version of the register map"], a: 1, why: "<p>Its meaning depends on the parent, which is why an I2C child's reg is one cell and a memory-mapped peripheral's is usually two.</p>" },

// --------------------------------------------------------- emb-z-kconfig
{ t: "emb-z-kconfig", d: 1, q: "You add a CONFIG_ symbol to prj.conf and nothing changes. What is the usual cause?", o: ["A typo somewhere in the value you set", "Its dependencies are not met", "prj.conf is not being read", "The board needs a power cycle"], a: 1, why: "<p>Kconfig does not warn about this, so the line sits there looking correct while the feature is absent.</p><p>Check <code>build/zephyr/.config</code>: if the symbol is missing or has a different value, something it depends on is not enabled.</p>" },
{ t: "emb-z-kconfig", d: 2, q: "Which file records what the build actually used?", o: ["prj.conf", "build/zephyr/.config", "CMakeLists.txt", "the board .dts"], a: 1, why: "<p>It is the merged result of prj.conf, per-board conf files, Kconfig defaults and any other layers.</p><p>prj.conf is only one input, which is why grepping .config settles arguments that reading prj.conf cannot.</p>" },
{ t: "emb-z-kconfig", d: 2, q: "Why enable CONFIG_ASSERT during development?", o: ["It makes the build finish faster", "__ASSERT is compiled out by default", "It is what enables the logging", "The shell subsystem requires it to be on"], a: 1, why: "<p>Passing a non-zero timeout to a kernel call from an ISR, for instance, is undefined behaviour that Zephyr can detect and by default says nothing about.</p><p>One line, and a large amount of free diagnosis.</p>" },
{ t: "emb-z-kconfig", d: 2, q: "What is the right use of menuconfig?", o: ["To set the final configuration", "To discover dependencies, then write them", "To edit the devicetree overlay", "To flash the board afterwards"], a: 1, why: "<p>Its search shows the dependency chain and what currently blocks a symbol, which is far quicker than reading Kconfig files.</p><p>Its changes go to <code>build/zephyr/.config</code> and are lost on a pristine build, so they are not a place to keep configuration.</p>" },
{ t: "emb-z-kconfig", d: 2, q: "A devicetree node is status okay but the device never initialises. What is likely missing?", o: ["A pull-up resistor missing on the bus", "The Kconfig symbol for the driver", "An alias pointing at the node", "A pinctrl entry for the pins"], a: 1, why: "<p>You need both halves: the node says the hardware exists, the CONFIG_ symbol says the software to drive it should be built.</p><p>The mirror-image failure is a driver selected with no node, which builds a driver with nothing to bind to.</p>" },
{ t: "emb-z-kconfig", d: 3, q: "What does <code>west build -p always</code> do, and when is it worth it?", o: ["It makes the build run faster", "Pristine build, when a change seems ignored", "It enables parallel build jobs", "It rebuilds only the files that changed"], a: 1, why: "<p>Changing prj.conf or an overlay does not always trigger a full reconfigure, and the symptom is a change that seems to be ignored.</p><p>Thirty seconds of rebuild against an afternoon of confusion.</p>" },
{ t: "emb-z-kconfig", d: 3, q: "What does CONFIG_HEAP_MEM_POOL_SIZE control?", o: ["The size of each thread stack", "The pool k_malloc allocates from", "The size of the log buffer", "The Bluetooth controller buffer pool size"], a: 1, why: "<p>Zephyr has no heap at all unless you ask for one, which is a reasonable default on a microcontroller.</p><p>Subsystems that allocate internally will fail quietly at init if it is zero, which looks like a driver problem.</p>" },
{ t: "emb-z-kconfig", d: 3, q: "Where do per-board Kconfig additions for an application belong?", o: ["Only ever in prj.conf itself", "In boards/&lt;board&gt;.conf beside the app", "Somewhere inside the Zephyr tree", "In the application's CMakeLists.txt"], a: 1, why: "<p>It merges on top of prj.conf for that board only, which is how one application supports several targets without conditionals.</p><p>The same pattern applies to <code>boards/&lt;board&gt;.overlay</code> for devicetree.</p>" },

// --------------------------------------------------------- emb-z-drivers
{ t: "emb-z-drivers", d: 2, q: "Why call <code>device_is_ready()</code> when DEVICE_DT_GET never returns NULL?", o: ["It performs the initialisation", "Build-time macros cannot know init failed", "It takes a reference on the device", "Only interrupt handlers ever need to call it"], a: 1, why: "<p>A device whose init failed is present but unusable, and calling into it is undefined.</p><p>The check is a load and a compare, and skipping it is the most common Zephyr driver bug.</p>" },
{ t: "emb-z-drivers", d: 2, q: "Why can a PRE_KERNEL init function not sleep?", o: ["It runs too early to be interrupted", "No scheduler yet, so nothing to sleep on", "Sleeping is forbidden anywhere in driver code", "It runs in an interrupt context"], a: 1, why: "<p>A sensor needing a settle time therefore initialises at POST_KERNEL, or defers the wait to first use.</p><p>PRE_KERNEL is for clocks, the tick source and early serial, in that order.</p>" },
{ t: "emb-z-drivers", d: 2, q: "What does <code>DT_INST_FOREACH_STATUS_OKAY</code> achieve?", o: ["Checks that every node is enabled", "Instantiates once per enabled node", "Iterates the devices at runtime", "Validates the bindings at build"], a: 1, why: "<p>Two identical sensors on the bus gives two instances from one piece of code, with no list to maintain.</p><p>It is the mechanism that makes Zephyr drivers instance-based rather than singletons.</p>" },
{ t: "emb-z-drivers", d: 2, q: "Why is a device's config const and its data not?", o: ["It is purely a style convention", "Pins and addresses in flash; state in RAM", "config is shared between instances", "data is faster for the core to reach in RAM"], a: 1, why: "<p>On a part with far more flash than RAM this is not stylistic: a non-const config costs RAM plus a startup copy, for every instance.</p>" },
{ t: "emb-z-drivers", d: 2, q: "What convention do Zephyr APIs use for errors?", o: ["Positive error codes on failure", "Zero, or negative errno values", "A global errno you then read", "Boolean true or false returns"], a: 1, why: "<p>Returning your own scheme from a driver breaks every caller's expectations.</p><p><code>-ENOTSUP</code> for an API call you do not implement is the one people forget.</p>" },
{ t: "emb-z-drivers", d: 3, q: "What makes <code>i2c_write_read()</code> the same call on Nordic and ST silicon?", o: ["A preprocessor switch per vendor", "The device's api pointer, a call table", "A runtime lookup of the device name", "Vendor-supplied compatibility layers"], a: 1, why: "<p>It is the config and handle pattern with the parts named: a const config in flash, mutable data in RAM, and an api table making it polymorphic.</p>" },
{ t: "emb-z-drivers", d: 3, q: "Where do you put a binding for a part Zephyr does not know about?", o: ["Only inside the Zephyr tree itself", "In dts/bindings, or under DTS_ROOT", "As a line in prj.conf", "In the application CMakeLists.txt"], a: 1, why: "<p>A YAML file describing the compatible string and its properties. Without one, the <code>compatible</code> in your node matches nothing and the node has no driver.</p>" },
{ t: "emb-z-drivers", d: 3, q: "Why does init priority matter within an initialisation level?", o: ["It sets the driver's thread priority", "It orders init within a level", "It affects the interrupt latency", "It controls the init stack size"], a: 1, why: "<p>A sensor on an I2C bus must come after the bus controller. Getting it wrong shows as <code>device_is_ready()</code> returning false for a device that is otherwise correct.</p>" },

// --------------------------------------------------------- emb-z-threads
{ t: "emb-z-threads", d: 2, q: "What is the danger of <code>k_work_submit()</code>?", o: ["It can fail without telling you", "The shared queue: blocking stalls BLE", "The handler runs in interrupt context", "It allocates memory on each submit"], a: 1, why: "<p>The symptoms look unrelated to the change you made: dropped BLE connections, missing log lines, a timer callback that never runs.</p><p>If the handler can block, start your own queue with <code>k_work_queue_start</code> and submit to that.</p>" },
{ t: "emb-z-threads", d: 2, q: "In which context does a <code>k_timer</code> callback run?", o: ["A dedicated timer thread", "Interrupt context, with all that implies", "The system work queue thread", "The thread that originally started the timer"], a: 1, why: "<p>Which is why <code>k_work_delayable</code> is the better default: it runs in a thread and may block.</p><p>Use <code>k_timer</code> only when you genuinely need the lower latency, because the context restriction is easy to forget later.</p>" },
{ t: "emb-z-threads", d: 2, q: "Which kernel call is legal from an ISR?", o: ["k_mutex_lock", "k_sem_give", "k_sleep", "k_msgq_get with a timeout"], a: 1, why: "<p>Anything that can block is forbidden, which rules out mutexes entirely and any call with a non-zero timeout.</p><p><code>k_msgq_put</code> with <code>K_NO_WAIT</code> is fine; the same call with a timeout is not.</p>" },
{ t: "emb-z-threads", d: 2, q: "How should you size a Zephyr thread stack?", o: ["Start at 1024 and raise it if it crashes", "Measure with THREAD_ANALYZER, add margin", "Use the largest that will fit", "Match whatever the other threads use"], a: 1, why: "<p>Guessing gives you either waste or a corruption that surfaces as something else entirely.</p><p>Logging and floating point are both large consumers, and the deepest call path is rarely the one you expected.</p>" },
{ t: "emb-z-threads", d: 2, q: "When is k_msgq preferable to k_fifo?", o: ["Never: k_fifo is always better", "Small fixed items; copying avoids ownership", "Whenever the buffers are large", "When the producer happens to be an ISR handler"], a: 1, why: "<p><code>k_fifo</code> passes items by reference with no copy, so someone has to own the memory and free it at the right time.</p><p>A message queue trades a copy for that whole class of bug disappearing.</p>" },
{ t: "emb-z-threads", d: 3, q: "What does a mutex give you that a binary semaphore does not?", o: ["Locking is measurably faster to acquire", "Ownership and priority inheritance", "It can be used from an ISR", "It can count past one"], a: 1, why: "<p>Priority inversion is the reason: without inheritance, a medium-priority thread can preempt the low-priority holder and block the high-priority waiter indefinitely.</p><p>The ownership rule also means only the locking thread may unlock it.</p>" },
{ t: "emb-z-threads", d: 3, q: "What is <code>k_work_delayable</code> usually used for?", o: ["Running long computations off-thread", "A timeout or retry, with no thread", "Handling interrupts at thread level", "Allocating memory asynchronously"], a: 1, why: "<p>Submit it with a delay, cancel it if the thing you were waiting for arrives. It runs in a thread so it may block, unlike a <code>k_timer</code> callback.</p>" },
{ t: "emb-z-threads", d: 3, q: "What does k_poll let you do that a single semaphore cannot?", o: ["It polls faster than a semaphore", "Wait on several objects at once", "It avoids blocking altogether", "It can be called from an ISR"], a: 1, why: "<p>Without it, a thread waiting on a semaphore cannot also notice a message queue, so you end up either polling with timeouts or adding threads.</p><p><code>k_event</code> is the lighter option when the sources are all flags you control.</p>" },

// ----------------------------------------------------------- emb-z-build
{ t: "emb-z-build", d: 1, q: "What are west's two distinct jobs?", o: ["Building and then flashing the board", "Multi-repo manager, and a build front end", "Configuring, and then linking the final image", "Running the tests and deploying them"], a: 1, why: "<p>The manifest pins Zephyr and every module by revision, so a workspace is defined by one file rather than by whatever people happened to clone.</p><p>That is the part that matters for reproducible builds.</p>" },
{ t: "emb-z-build", d: 2, q: "Which build target tells you where the flash went?", o: ["menuconfig", "rom_report", "guiconfig", "usage"], a: 1, why: "<p>It breaks the image down by module and file, and <code>ram_report</code> does the same for RAM.</p><p>They turn 'it does not fit' from a guess into a list, and most people never discover them.</p>" },
{ t: "emb-z-build", d: 2, q: "In a Zephyr CMakeLists.txt, why add sources to <code>app</code> rather than define an executable?", o: ["It is only a naming convention", "Zephyr already defines that target", "It makes compilation noticeably faster", "CMake requires a predefined target"], a: 1, why: "<p>Which is why a Zephyr application's CMakeLists file is about four lines: find the package, name the project, add your sources.</p>" },
{ t: "emb-z-build", d: 2, q: "You see 'undefined reference' to a driver function. What is the usual cause?", o: ["A header has not been included", "The Kconfig symbol for it is not set", "The devicetree node is disabled", "The linker script is the wrong one"], a: 1, why: "<p>The driver's source simply is not in the build. Contrast with a <code>DT_N_...</code> undeclared error, which means the node is missing or not okay.</p><p>The two failure shapes point at different files, which is what makes them worth telling apart.</p>" },
{ t: "emb-z-build", d: 2, q: "What is sysbuild for?", o: ["It makes builds finish faster", "Building several images together", "Running the static analysers", "Running the test suite on target"], a: 1, why: "<p>The bootloader and the application have to agree on partition layout and signing keys, and doing that by hand across two separate builds is error-prone.</p><p>If you are shipping firmware update, you will meet it.</p>" },
{ t: "emb-z-build", d: 3, q: "What does BOARD_ROOT do?", o: ["Sets where the build output goes", "Points at your own board definitions", "Selects which toolchain is used", "Chooses which linker script will get used"], a: 1, why: "<p>A custom board is a directory with a .dts, a Kconfig.board, a _defconfig and a YAML description.</p><p>The frequent failure is the directory name and the .dts name disagreeing, which reports as 'board not found'.</p>" },
{ t: "emb-z-build", d: 3, q: "Which generated files answer most 'why is it doing that' questions?", o: ["The application's own source files themselves", "zephyr.dts, .config and the map file", "prj.conf and the overlay you wrote", "west.yml and the manifest tree"], a: 1, why: "<p>The inputs tell you your intention; the generated output tells you what the build actually concluded.</p><p>Opening them first rather than last is the single biggest time saver in Zephyr work.</p>" },
{ t: "emb-z-build", d: 3, q: "Why does the west manifest matter for reproducibility?", o: ["It caches the downloads locally", "It pins Zephyr and every module", "It compresses the workspace tree", "It validates the module licences"], a: 1, why: "<p>Without it, 'which Zephyr' is answered by whatever each engineer cloned and when.</p><p>It is the Zephyr equivalent of pinning your toolchain, and it belongs in the release archive.</p>" },

// ----------------------------------------------------------- emb-z-debug
{ t: "emb-z-debug", d: 2, q: "Your log stops several lines before a crash. What is the fix?", o: ["Increase the size of the deferred log buffer", "LOG_MODE_IMMEDIATE: queued lines are lost", "Lower the log level to warnings", "Use a faster UART for the output"], a: 1, why: "<p>Deferred logging formats in the log thread, which is cheap at the call site and lossy at exactly the wrong moment.</p><p>Immediate costs performance and changes timing, which is the trade you want while chasing a fault.</p>" },
{ t: "emb-z-debug", d: 2, q: "What does the shell's <code>device list</code> command tell you?", o: ["The devicetree source it was built from", "Every device, and whether it is ready", "The Kconfig settings that are enabled", "USB devices currently connected to it"], a: 1, why: "<p>With <code>i2c scan</code> it replaces the small test program you were about to write, and <code>kernel threads</code> and <code>kernel stacks</code> do the same for thread questions.</p>" },
{ t: "emb-z-debug", d: 2, q: "Why set CONFIG_RESET_ON_FATAL_ERROR=n while developing?", o: ["The board boots noticeably faster", "A reset destroys the state you needed", "The logging subsystem requires it", "It is what enables the shell"], a: 1, why: "<p>Staying stopped lets you attach a debugger and look at the actual fault.</p><p>In production you usually want the opposite, so it belongs in a development configuration rather than in prj.conf permanently.</p>" },
{ t: "emb-z-debug", d: 2, q: "How does CONFIG_STACK_SENTINEL help?", o: ["It grows the stacks automatically", "A known value, checked on each switch", "It measures the peak stack usage", "It relocates the stacks away from the data"], a: 1, why: "<p>An overflow otherwise corrupts whatever is adjacent, so the symptom is a variable changing on its own or a fault in unrelated code.</p><p>With an MPU, <code>CONFIG_HW_STACK_PROTECTION</code> is better still because it faults at the moment of overflow.</p>" },
{ t: "emb-z-debug", d: 2, q: "Why is RTT worth setting up as a logging backend?", o: ["The output is encrypted in transit", "Over the probe, no pins, barely distorts", "It works with no debug probe attached at all", "It compresses the output stream"], a: 1, why: "<p>Useful when UART pins are scarce, and more importantly when the logging rate is high enough that a UART backend changes the behaviour you are trying to observe.</p>" },
{ t: "emb-z-debug", d: 3, q: "Which two settings most improve a Zephyr fault dump?", o: ["CONFIG_LOG and CONFIG_SHELL", "THREAD_NAME and EXCEPTION_STACK_TRACE", "CONFIG_ASSERT and CONFIG_BT", "CONFIG_NVS and CONFIG_SETTINGS"], a: 1, why: "<p>One names the faulting thread instead of printing an address, the other adds a call trace.</p><p>Then <code>addr2line</code> against the archived ELF for that exact build turns the addresses into files and lines.</p>" },
{ t: "emb-z-debug", d: 3, q: "What is the value of per-module log levels?", o: ["It produces smaller binaries only", "One module at debug, the rest at warning", "Logging runs measurably faster", "The subsystem requires them all to be set"], a: 1, why: "<p><code>LOG_MODULE_REGISTER(name, CONFIG_..._LOG_LEVEL)</code> is what enables it, and the level can also be changed at runtime from the shell.</p>" },
{ t: "emb-z-debug", d: 3, q: "A variable changes value with nothing writing to it. What should you suspect first on Zephyr?", o: ["A bug in the compiler's optimiser", "A stack overflow in another thread", "A missing volatile qualifier", "Cache incoherency on that address"], a: 1, why: "<p>Stacks are allocated next to each other, so an overflow lands in whatever follows and the symptom appears far from the cause.</p><p><code>CONFIG_STACK_SENTINEL</code> or hardware stack protection converts it into an immediate named error.</p>" }

]);
