// Questions for the eight Control lessons that had none.
BANKS["Control"] = BANKS["Control"].concat([

// -------------------------------------------------------------- ct-freq
{ t: "ct-freq", d: 2, q: "A closed loop has 35 Hz bandwidth. What rise time does that imply?", o: ["About 1 ms", "About 10 ms", "About 100 ms", "About 300 ms"], a: 1, why: "Rise time is roughly 0.35 divided by bandwidth in Hz, so 0.35/35 is 10 ms. Bandwidth and rise time are the same fact stated in two domains, which is why you can convert a time-domain requirement into a loop specification immediately." },
{ t: "ct-freq", d: 2, q: "Where is phase margin measured?", o: ["At the resonant peak", "At the gain crossover frequency, where the open-loop magnitude passes 0 dB", "At DC", "At the phase crossover"], a: 1, why: "It is how much extra lag the loop can absorb before the phase reaches -180 degrees there. Gain margin is the complementary number, measured where the phase crosses -180." },
{ t: "ct-freq", d: 2, q: "Why does a mechanical resonance above crossover threaten stability?", o: ["It shifts the crossover frequency", "Its gain peak can push the magnitude back above 0 dB at a frequency where the phase has already fallen past -180", "It adds steady-state error", "It saturates the actuator"], a: 1, why: "The loop then has a second crossing with no margin. The fixes are a notch at the resonance, rolling off harder before it, or stiffening the mechanics to move it further out." },
{ t: "ct-freq", d: 2, q: "In loop-shaping terms, what is integral action for?", o: ["Improving damping", "Very high gain at low frequency, which drives steady-state error to zero", "Increasing bandwidth", "Adding phase lead"], a: 1, why: "It costs 90 degrees of phase lag, which is why too much integral eats phase margin. Derivative or lead action does the opposite: it adds phase near crossover at the cost of noise amplification." },
{ t: "ct-freq", d: 2, q: "What does a resonant peak in the closed-loop magnitude response indicate?", o: ["High bandwidth", "Low damping, which shows as overshoot and ringing in the step response", "Good disturbance rejection", "Integral windup"], a: 1, why: "A peak of about 2.3 dB corresponds to roughly 0.7 damping, which is the usual target. The peak height and the step overshoot are two views of the same pole locations." },
{ t: "ct-freq", d: 3, q: "Why is a sensor's own bandwidth a hard limit on loop bandwidth?", o: ["It is not, only the actuator matters", "Sensor lag appears inside the loop as phase lag near crossover, so you cannot close faster than you can measure", "It only affects noise", "It changes the DC gain"], a: 1, why: "A filter added to clean up sensor noise does the same thing, which is the real cost of that filter. It is why the rule of thumb is a sensor at least five to ten times the intended loop bandwidth." },
{ t: "ct-freq", d: 3, q: "How much phase lag does a pure time delay T contribute at frequency omega?", o: ["A constant 90 degrees", "omega*T radians, growing without bound with frequency", "It contributes gain, not phase", "45 degrees at 1/T"], a: 1, why: "Delay costs phase and nothing else, and it grows linearly, so it sets a hard ceiling on achievable bandwidth. It is why sampling, computation and communication delay all have to be in the budget explicitly." },
{ t: "ct-freq", d: 3, q: "What does the sensitivity function tell you, and what is the waterbed effect?", o: ["Only steady-state error", "How disturbances and reference errors pass through the loop; reducing it at one frequency necessarily raises it elsewhere", "The noise floor", "The actuator range needed"], a: 1, why: "Bode's integral makes the trade formal for most real systems: the area under log sensitivity is conserved. Pushing error down in band is paid for with a peak just above crossover." },

// ------------------------------------------------------------- ct-sysid
{ t: "ct-sysid", d: 2, q: "In a first-order-plus-dead-time fit, what does the ratio of dead time L to time constant tau tell you?", o: ["The steady-state gain", "How hard the loop will be to control: a large L/tau severely limits achievable bandwidth", "The sample rate needed", "The noise level"], a: 1, why: "Below about 0.1 the process is easy and PID does well. Above about 1 it is dead-time dominated, and you need a Smith predictor or you accept a slow loop." },
{ t: "ct-sysid", d: 2, q: "Why does naively fitting a model to data logged under feedback mislead?", o: ["The data is noisier", "The controller correlates the input with the disturbance, so the fit can identify the inverse controller rather than the plant", "Closed-loop data has less bandwidth", "It cannot be done at all"], a: 1, why: "The excitation is not independent of the output. The fixes are injecting an external test signal at the reference or the actuator, or using a closed-loop identification method that accounts for the feedback." },
{ t: "ct-sysid", d: 2, q: "When is a frequency sweep preferred over a step test?", o: ["Always", "When you need accurate dynamics over a band, especially near resonances, and the plant cannot take a large step", "Only for electrical systems", "When you have very little time"], a: 1, why: "A sweep concentrates energy where you are measuring, so the signal-to-noise is far better at each frequency. A step is quick and gives a usable low-order model but resolves resonances poorly." },
{ t: "ct-sysid", d: 2, q: "What is the argument against fitting a sixth-order model to step-test data?", o: ["It takes too long to compute", "A step excites a narrow band, so the extra parameters fit noise rather than dynamics and the model will not generalise", "High-order models are always wrong", "The solver will not converge"], a: 1, why: "The fit looks better because more parameters always fit better. Validating against a different dataset is what exposes it, and it is why model order should be justified rather than maximised." },
{ t: "ct-sysid", d: 2, q: "What makes an input signal persistently exciting?", o: ["A large amplitude", "It contains enough distinct frequencies to identify every parameter in the model", "It is periodic", "It is a step"], a: 1, why: "A single sine identifies at most two parameters, so a constant input identifies nothing dynamic. This is why PRBS and chirps are the standard identification inputs." },
{ t: "ct-sysid", d: 3, q: "How should you validate an identified model?", o: ["Check the fit on the identification data", "Check it against data it has never seen, ideally at a different operating point or excitation", "Compare parameters with the datasheet", "Confirm it is stable"], a: 1, why: "Fit on the training data always improves with model order, so it cannot detect over-fitting. Residuals that still correlate with the input mean there is structure the model has not captured." },
{ t: "ct-sysid", d: 3, q: "Why is a PRBS a good identification input?", o: ["It is easy to generate only", "It is broadband like noise, but deterministic and repeatable, with a controllable amplitude the actuator can take", "It is a pure sine", "It has the highest possible energy"], a: 1, why: "It excites many frequencies at once with modest amplitude, so you get the whole band in one short experiment without pushing the plant far from its operating point. The clock rate sets the bandwidth excited." },
{ t: "ct-sysid", d: 3, q: "Your step response shows an initial dip in the wrong direction. What does that indicate?", o: ["A measurement error", "A right-half-plane zero, which fundamentally limits achievable bandwidth", "Excessive dead time", "Sensor saturation"], a: 1, why: "Non-minimum-phase behaviour cannot be cancelled by a controller, because inverting it would be unstable. Boiler drum level and some flexible structures show it, and the only honest response is a slower loop." },

// ---------------------------------------------------------------- ct-ff
{ t: "ct-ff", d: 2, q: "What is the division of labour between feedforward and feedback?", o: ["Feedforward handles noise, feedback handles setpoints", "Feedforward handles what you can predict; feedback corrects what you got wrong", "They do the same job redundantly", "Feedback is for fast dynamics only"], a: 1, why: "Feedforward acts before the error exists, so it is not limited by stability margins. Feedback is the safety net that covers model error, disturbances and anything unmodelled." },
{ t: "ct-ff", d: 2, q: "Why does acceleration feedforward work on a servo axis?", o: ["It increases loop gain", "Torque required is inertia times acceleration, which is known from the trajectory before the axis moves", "It filters the encoder", "It compensates friction"], a: 1, why: "The feedback loop no longer has to generate an error to produce the torque. Velocity feedforward against viscous friction and a constant term against Coulomb friction complete the usual set." },
{ t: "ct-ff", d: 2, q: "How does a disturbance observer estimate the disturbance?", o: ["From a dedicated sensor", "By comparing measured output with what the nominal plant model predicts from the applied input", "From the setpoint", "By differentiating the error"], a: 1, why: "Whatever the model does not explain is treated as an equivalent input disturbance and subtracted. It is a way of getting disturbance rejection without measuring the disturbance directly." },
{ t: "ct-ff", d: 2, q: "In a system with feedforward, the feedback effort has a persistent nonzero average. What does that mean?", o: ["The loop is unstable", "The feedforward model is systematically wrong, and feedback is quietly making up the difference", "Sensor noise is too high", "The gains are too low"], a: 1, why: "Feedforward should carry the predictable load and leave feedback centred on zero. A standing bias is a free diagnostic that the mass, gain or friction estimate has drifted." },
{ t: "ct-ff", d: 2, q: "What is reference shaping (input shaping) for?", o: ["Making the setpoint arrive faster", "Filtering or splitting the command so it does not excite a known lightly damped resonance", "Reducing sensor noise", "Improving steady-state accuracy"], a: 1, why: "The classic form is two impulses spaced half a resonant period apart, so the second cancels the vibration the first started. Crane and gantry control use it, and it costs a small delay." },
{ t: "ct-ff", d: 3, q: "Why can feedforward be more aggressive than feedback?", o: ["It uses better sensors", "It is outside the loop, so it cannot destabilise it; errors only degrade tracking", "It runs faster", "It has integral action"], a: 1, why: "There is no return path for it to go unstable through. The risk is different: a wrong feedforward can command the actuator beyond its limits, and that saturation does affect the loop." },
{ t: "ct-ff", d: 3, q: "What is a Smith predictor for?", o: ["Estimating unmeasured states", "Controlling a plant with large dead time, by feeding back a model prediction rather than waiting for the delayed measurement", "Cancelling resonances", "Adaptive gain scheduling"], a: 1, why: "It lets you tune as if the delay were not there, then reinserts it. The weakness is well known: it depends heavily on the model, and a delay estimate that is wrong degrades it fast." },
{ t: "ct-ff", d: 3, q: "A feedforward term is derived from a trajectory that is not smooth. What goes wrong?", o: ["Nothing", "Differentiating it produces impulsive commands that saturate the actuator and excite resonances", "Steady-state error rises", "The loop becomes unstable"], a: 1, why: "Acceleration feedforward needs a twice-differentiable path, which is why trajectory generators produce S-curves rather than trapezoidal velocity profiles when jerk matters." },

// --------------------------------------------------------------- ct-lqr
{ t: "ct-lqr", d: 2, q: "In the LQR cost, what does increasing R relative to Q produce?", o: ["Faster response", "A more conservative controller that uses less control effort and responds more slowly", "Higher gain", "More overshoot"], a: 1, why: "Q penalises state error and R penalises control effort, so their ratio is the only real tuning knob. It converts the tuning problem from picking gains to expressing what you care about." },
{ t: "ct-lqr", d: 2, q: "Why is the LQR result u = -Kx notable?", o: ["It is nonlinear", "The optimal solution turns out to be simple constant-gain state feedback, computable offline", "It requires an observer", "It handles constraints"], a: 1, why: "An optimisation over an infinite horizon collapses to a matrix multiply, so it runs on anything. It also comes with guaranteed margins in the full-state-feedback case, which are lost once you add an observer." },
{ t: "ct-lqr", d: 2, q: "Why does MPC apply only the first input of each optimised sequence?", o: ["The rest is discarded to save memory", "Re-solving each step with the latest measurement turns an open-loop plan into feedback", "The later inputs are less accurate", "It is a computational shortcut"], a: 1, why: "This is receding horizon control. Without re-solving, MPC would be open-loop optimal and would drift on any model error or disturbance." },
{ t: "ct-lqr", d: 2, q: "What is the strongest justification for MPC's computational cost?", o: ["Better tracking than PID", "It handles constraints on inputs and states explicitly, optimising right up against them", "It is easier to tune", "It needs no model"], a: 1, why: "Every other method deals with limits by staying away from them or by ad hoc anti-windup. Running a process safely at its constraint is usually where the money is." },
{ t: "ct-lqr", d: 2, q: "What does LQR require that PID does not?", o: ["A faster processor", "A state-space model and measurement of all states, or an observer to estimate them", "Constraint handling", "A nonlinear plant"], a: 1, why: "Full state feedback is the assumption behind the guarantee. Adding a Kalman filter gives LQG, which works well but loses the guaranteed robustness margins, a result that surprised the field when Doyle published it." },
{ t: "ct-lqr", d: 3, q: "How is integral action added to an LQR design?", o: ["By adding an integral gain afterwards", "By augmenting the state with the integral of the tracking error and letting the design weight it", "LQR cannot have integral action", "By increasing Q on all states"], a: 1, why: "The optimiser then treats accumulated error as something to penalise, and the resulting gain includes the integral term. Bolting an integrator on afterwards discards the optimality the method was chosen for." },
{ t: "ct-lqr", d: 3, q: "What makes explicit MPC attractive on embedded hardware?", o: ["It uses a longer horizon", "The optimisation is solved offline into a piecewise-affine lookup, so runtime is a table search rather than a solver", "It removes constraints", "It needs no model"], a: 1, why: "That makes the worst-case execution time bounded and small, which matters for a hard real-time loop. It only works for low state dimensions, because the number of regions grows explosively." },
{ t: "ct-lqr", d: 3, q: "What is the practical risk of a long MPC prediction horizon?", o: ["Instability", "Computation grows and the far end of the horizon is dominated by model error, so you pay for predictions you should not trust", "It cannot handle constraints", "It removes feedback"], a: 1, why: "The horizon should cover the dominant dynamics and little more. Too short is the opposite failure: the controller cannot see a constraint coming and behaves greedily." },

// --------------------------------------------------------- ct-nonlinear
{ t: "ct-nonlinear", d: 2, q: "A servo axis oscillates at small constant amplitude around its setpoint at rest. What is the likely cause?", o: ["Excessive derivative gain", "Stiction combined with integral action: the integrator winds up until it breaks free, overshoots, and repeats", "Sensor noise", "A resonance"], a: 1, why: "It is a limit cycle rather than a linear instability, and reducing gain does not remove it. The usual answers are a small deadband on the integrator, dither, or friction feedforward." },
{ t: "ct-nonlinear", d: 2, q: "Why is backlash a problem in a load-side position loop?", o: ["It adds friction", "The loop loses control authority entirely while crossing the gap, which is a variable delay in the loop", "It reduces gain linearly", "It saturates the actuator"], a: 1, why: "During the crossing the motor moves and the load does not, so feedback acts on nothing. It is why direction reversals are where backlash shows up and why dual-loop or preloaded drives exist." },
{ t: "ct-nonlinear", d: 2, q: "A system is stable for small steps but oscillates for large ones. What does that signature indicate?", o: ["Sensor noise", "Actuator saturation, which reduces effective loop gain and interacts with integral windup", "Backlash", "Dead time"], a: 1, why: "Small-signal linear analysis says nothing about it, because the plant is only linear while the actuator is in range. Anti-windup and rate limiting on the reference are the standard fixes." },
{ t: "ct-nonlinear", d: 2, q: "What does a describing function do?", o: ["Linearises about an operating point", "Represents a nonlinearity by its gain to the fundamental of a sinusoid, giving an amplitude-dependent gain for Nyquist-style analysis", "Models time delay", "Estimates disturbances"], a: 1, why: "It predicts limit cycles by finding where the loop gain crosses -1 for some amplitude. It is approximate, since it assumes the harmonics are filtered out by the plant." },
{ t: "ct-nonlinear", d: 2, q: "When is linearisation about an operating point valid?", o: ["Always", "While excursions stay small enough that the neglected higher-order terms remain negligible", "Only for electrical systems", "Only at steady state"], a: 1, why: "Which is why gain scheduling exists: one linearisation per region. The failure mode is a controller tuned at one operating point behaving badly at another, and it is usually found in commissioning." },
{ t: "ct-nonlinear", d: 3, q: "What is the difference between stiction and Coulomb friction?", o: ["Nothing", "Stiction is the higher force needed to start motion; Coulomb friction is the roughly constant force once moving", "Stiction is velocity dependent", "Coulomb friction only occurs at rest"], a: 1, why: "The drop between them is what makes low-speed motion lurch: the axis breaks free, friction falls, it accelerates, then it stops again. That is stick-slip." },
{ t: "ct-nonlinear", d: 3, q: "What is the practical fix for integral windup during a long saturation?", o: ["Remove the integrator", "Stop integrating, or back-calculate the integral from the saturated output, while the actuator is at its limit", "Increase the proportional gain", "Add derivative action"], a: 1, why: "Without it the integral keeps accumulating during a move it cannot influence, and the axis overshoots badly on arrival because the integrator has to unwind. Back-calculation is the smoother of the two." },
{ t: "ct-nonlinear", d: 3, q: "Why does a deadband in an actuator degrade a position loop specifically?", o: ["It adds noise", "Small commands produce no motion at all, so the loop cannot correct small errors and settles to a range rather than a point", "It saturates the integrator", "It slows the response"], a: 1, why: "Proportional action near the setpoint falls inside the deadband and does nothing. Dither, or an integral term with care, can push through it, but the honest fix is usually mechanical." },

// ----------------------------------------------------------- ct-cascade
{ t: "ct-cascade", d: 2, q: "Why does a load-torque disturbance barely show in position on a cascaded servo?", o: ["The position loop is fast", "The inner current and velocity loops see and reject it long before it integrates into a position error", "The encoder filters it", "Feedforward cancels it"], a: 1, why: "The inner loop runs perhaps ten times faster, so it corrects the disturbance within a fraction of the outer loop's period. Rejecting a disturbance close to where it enters is the core rationale for cascade." },
{ t: "ct-cascade", d: 2, q: "What is the usual bandwidth separation guideline between adjacent loops?", o: ["About 1.5 times", "Roughly a factor of 3 to 10", "A factor of 100", "They should match"], a: 1, why: "Below about 3 the loops interact and the inner one looks like extra lag rather than a fast follower. Far above 10 you are usually wasting inner-loop capability or hitting sensor and actuator limits." },
{ t: "ct-cascade", d: 2, q: "What is the correct tuning order for a position-velocity-current cascade?", o: ["Position first", "Innermost first: current, then velocity, then position", "All simultaneously", "Velocity first, then the others together"], a: 1, why: "Each outer loop is designed against an inner loop that already behaves predictably. Tuning outside in means retuning everything each time you change an inner gain." },
{ t: "ct-cascade", d: 2, q: "When the inner loop saturates, what should the outer loop ideally do?", o: ["Increase its output further", "Stop integrating, because its commands can no longer be followed", "Switch to open loop", "Reduce its setpoint to zero"], a: 1, why: "This is cascade anti-windup: the inner loop tells the outer loop it is at its limit. Without that signal the outer integrator winds up against a limit it cannot see." },
{ t: "ct-cascade", d: 2, q: "What does a cascade need that a single loop does not?", o: ["A faster processor", "An intermediate measurement, such as velocity or current, between the actuator and the final output", "Integral action", "A nonlinear model"], a: 1, why: "Without that sensor there is nothing to close the inner loop on. It is the reason cascade is standard on servos, where current and velocity are cheaply available, and rarer elsewhere." },
{ t: "ct-cascade", d: 3, q: "Two loops in a multivariable plant interact badly. What does the relative gain array tell you?", o: ["The stability margin", "Which input should be paired with which output to minimise interaction", "The required bandwidth", "The model order"], a: 1, why: "Diagonal entries near 1 indicate a good pairing; negative entries indicate a pairing that will fail when the other loop is switched off. It is the standard first check before decoupling." },
{ t: "ct-cascade", d: 3, q: "Why is a cascade more robust to inner-plant variation than a single loop?", o: ["It uses more sensors", "The inner loop linearises and standardises what the outer loop sees, so motor and gain variation is absorbed inside", "Its gains are lower", "It has more integral action"], a: 1, why: "A current loop makes the motor look like a torque source regardless of winding resistance or back-EMF. That is why the same outer tuning can serve several motor variants." },
{ t: "ct-cascade", d: 3, q: "An outer loop is retuned to be almost as fast as its inner loop. What is the risk?", o: ["Nothing, faster is better", "The inner loop's dynamics now appear as significant lag inside the outer loop, eroding phase margin", "Steady-state error rises", "The inner loop saturates"], a: 1, why: "The whole approximation behind cascade is that the inner loop is effectively instantaneous. Once that fails you have to design the outer loop against the inner loop's actual transfer function." },

// ---------------------------------------------------------- ct-adaptive
{ t: "ct-adaptive", d: 2, q: "Why is gain scheduling favoured in certified industries?", o: ["It performs best", "Every gain set is fixed and testable in advance, so the behaviour is deterministic and can be verified", "It adapts fastest", "It needs no model"], a: 1, why: "Nothing changes at runtime except which pretested table entry is selected. True online adaptation has behaviour that depends on operating history, which is far harder to argue in a safety case." },
{ t: "ct-adaptive", d: 2, q: "Why is verifying a gain schedule only at its design points insufficient?", o: ["The points may be wrong", "Interpolated gains between points are untested, and rapid scheduling can destabilise even when every fixed point is stable", "It takes too long", "The sensors drift"], a: 1, why: "Stability at each frozen operating point does not imply stability while moving between them. The usual constraint is to limit how fast the scheduling variable is allowed to change." },
{ t: "ct-adaptive", d: 2, q: "In MRAC, what causes gains to drift during long periods of gentle operation?", o: ["Sensor bias", "Insufficient excitation, so the adaptation law cannot distinguish parameter sets and wanders on noise", "Too small an adaptation gain", "Actuator saturation"], a: 1, why: "Persistent excitation is what pins the parameters down. Without it the standard defences are a dead zone, sigma-modification or projection to keep the gains bounded." },
{ t: "ct-adaptive", d: 2, q: "What is the most defensible way to deploy a learned policy on real hardware?", o: ["Let it control directly and monitor", "Inside a safety envelope, with a verified conventional controller able to take over", "Retrain it online continuously", "Only in simulation"], a: 1, why: "The learned policy provides performance and the conventional layer provides the guarantee. This is the shielding or runtime-assurance pattern, and it is what makes learned control arguable in an audit." },
{ t: "ct-adaptive", d: 2, q: "When is learned control genuinely justified over classical design?", o: ["Whenever data is available", "When the dynamics are hard to model but easy to simulate or sample, and the objective is hard to express analytically", "For any nonlinear plant", "When gains are hard to tune"], a: 1, why: "Contact-rich manipulation and legged locomotion are the honest examples. For a plant you can model and a cost you can write down, LQR or MPC gets there faster and with a stability argument." },
{ t: "ct-adaptive", d: 3, q: "What is the difference between direct and indirect adaptive control?", o: ["Nothing", "Direct adapts the controller gains; indirect identifies the plant parameters and then redesigns the controller", "Direct is faster", "Indirect needs no model"], a: 1, why: "Indirect separates identification from design, so you can inspect the identified model, which is a real practical advantage. Direct is simpler but the gains are harder to sanity-check." },
{ t: "ct-adaptive", d: 3, q: "What should a gain schedule use as its scheduling variable?", o: ["Time", "A measured variable that captures how the dynamics change, and that varies slowly compared with the loop", "The control error", "The setpoint only"], a: 1, why: "Airspeed for an aircraft, or load inertia for an axis. Scheduling on the error itself couples the schedule to the loop's own transients, which is a good way to build an oscillator." },
{ t: "ct-adaptive", d: 3, q: "Why is bumpless transfer needed when switching between controllers?", o: ["To reduce noise", "The two controllers hold different internal states, so switching without initialising the incoming one produces a step in the actuator command", "To preserve stability margins", "To avoid saturation"], a: 1, why: "The integrator is the usual culprit. Initialising the incoming controller's state so its output matches the current command makes the changeover invisible at the plant." },

// ------------------------------------------------------------ ct-faults
{ t: "ct-faults", d: 2, q: "Why design the safe state first?", o: ["It is easier", "Everything else, including fault detection thresholds and degraded modes, is defined by what you are falling back to", "Regulators require it", "It saves memory"], a: 1, why: "Without it, fault handling accretes as a set of special cases with no shared target. It also frequently changes the hardware, since the safe state should ideally be what the system reaches with no power." },
{ t: "ct-faults", d: 2, q: "Why does a stuck-at sensor fault defeat simple range checking?", o: ["The value is noisy", "The frozen value is usually inside the valid range, so nothing flags it", "Range checks are too slow", "It only fails at power-on"], a: 1, why: "The check has to look at behaviour rather than value: no change over a period during which the process must have moved. A completely noise-free reading is itself suspicious on a real sensor." },
{ t: "ct-faults", d: 2, q: "What is often the earliest indicator of a degrading actuator in a well-tuned loop?", o: ["A tracking error", "A rising steady control effort for the same commanded output", "Increased sensor noise", "A change in setpoint"], a: 1, why: "The loop hides the degradation by working harder, so the output looks fine right up until it saturates. Trending the control effort turns a sudden failure into a scheduled maintenance item." },
{ t: "ct-faults", d: 2, q: "What does bumpless transfer to a backup controller require?", o: ["Identical gains", "Initialising the backup's internal states so its output matches the current command at the moment of switching", "A faster sample rate", "Disabling integral action"], a: 1, why: "Otherwise the transfer itself is a disturbance, which is a poor thing to introduce during a fault. In practice the backup is run in tracking mode continuously so it is always ready." },
{ t: "ct-faults", d: 2, q: "What is analytical redundancy?", o: ["A second sensor", "Using a model plus other measurements to predict what a sensor should read, and flagging disagreement", "Duplicated computation", "A redundant actuator"], a: 1, why: "It gives fault detection without paying for a second sensor. The limit is that it inherits the model's accuracy, so the detection threshold has to be wider than the model error." },
{ t: "ct-faults", d: 3, q: "Why should a watchdog be fed only after the control loop has demonstrated progress?", o: ["To reduce CPU load", "Feeding it from a timer keeps it happy while every task is deadlocked, turning a safety device into a decoration", "It is required by IEC 61508", "To synchronise with the loop rate"], a: 1, why: "The usual pattern is each task setting a flag on completing a cycle, with one check that feeds only when all flags are present and then clears them. A windowed watchdog adds an early bound too." },
{ t: "ct-faults", d: 3, q: "What is a degraded mode, and why define it explicitly?", o: ["A failure state", "A reduced-capability operating mode that is still useful and still safe, so a single sensor loss need not stop the machine", "A test mode", "A calibration mode"], a: 1, why: "Without one, every fault results in a full stop, which is often worse than continuing at lower performance. It has to be designed and tested, not improvised when the fault occurs." },
{ t: "ct-faults", d: 3, q: "Two redundant sensors disagree. What is the problem with simple duplication?", o: ["It costs too much", "You can detect the disagreement but not decide which one is right, so you can fail safe but not continue", "It doubles the noise", "The sensors drift together"], a: 1, why: "Duplex gives detection; triple modular redundancy with a majority vote gives identification and continued operation. Which you need follows directly from whether the system is fail-safe or fail-operational." }

]);
