// A second pass over every RTL and Verilog lesson: ten more questions each.
//
// Topic tags are lesson ids, so topicLesson() resolves them by the byId
// fallback and no TOPIC_LESSON entry is needed.
//
// In each block of ten, two or three questions are written so the correct
// option is the longest and the rest so a distractor is, which puts the
// answer-length tell back at chance.
//
// Operators are spelled out in words rather than written as symbols, so that
// nothing in an option can be mistaken for markup when the page renders it.
BANKS["RTL & Verilog"] = BANKS["RTL & Verilog"].concat([

// ------------------------------------------------------------- rtl-verilog
{ t: "rtl-verilog", d: 1, q: "What is the difference between a Verilog wire and a variable?", o: ["A variable holds its value; a wire is continuously driven", "A wire is faster in simulation than a variable of the same width", "Variables may only be used inside a testbench, never in synthesisable code", "A wire can be assigned inside an always block but a variable cannot"], a: 0, why: "Only variables may be targets of procedural assignment, which is why anything driven in an always block must be declared reg or logic. Neither type implies a flip-flop by itself." },
{ t: "rtl-verilog", d: 2, q: "What does a parameter let you do that a localparam does not?", o: ["Override the value at instantiation", "Use the value inside a generate block for elaboration-time decisions", "Declare a constant whose width is inferred from the assigned expression", "Refer to another constant declared earlier in the same module body"], a: 0, why: "That override is the whole point: one parameterised module serves many widths. localparam exists precisely to say that a constant is derived and must not be overridden." },
{ t: "rtl-verilog", d: 2, q: "What happens when a 12-bit expression is assigned to an 8-bit variable?", o: ["The top four bits are silently dropped", "Elaboration fails with a width mismatch, as it would in a strongly typed language", "The variable is automatically widened to hold the whole of the expression", "The value saturates at the largest number the destination can represent"], a: 0, why: "Verilog pads or truncates without complaint, and at best you get a lint warning. That silence is the single biggest difference from VHDL for someone crossing over." },
{ t: "rtl-verilog", d: 2, q: "What does the replication operator do?", o: ["Repeats a bit pattern a fixed number of times to build a wider vector from it", "Copies a module instance right across a whole array of identical positions at once", "Duplicates a signal so it can drive two separate loads", "Repeats a statement for each element of a generate loop"], a: 0, why: "Writing a brace with a count and a value repeats that value, which is how a sign extension or an all-ones mask is written compactly. It is purely a bit-vector operation." },
{ t: "rtl-verilog", d: 3, q: "Why does mixing a signed and an unsigned operand cause trouble?", o: ["The whole expression becomes unsigned", "The signed operand is silently widened to the width of the unsigned one", "The comparison is performed twice and the results are combined", "The tool reports an error and refuses to elaborate the design"], a: 0, why: "It is a whole-expression rule, so one unsigned operand turns a negative value into a large positive one. Declaring everything signed, and using an explicit cast where needed, is the defence." },
{ t: "rtl-verilog", d: 2, q: "What does a reduction operator produce?", o: ["A single bit, formed by applying the operator across all bits", "A vector of the same width with each bit operated on independently", "The number of bits that are set in the operand", "A mask marking the position of the highest set bit"], a: 0, why: "Reduction AND of an eight-bit bus is one bit that is high only if every bit is high. It is the compact way to test for all-ones or all-zeros without writing out the comparison." },
{ t: "rtl-verilog", d: 2, q: "What is the difference between case equality and logical equality?", o: ["Case equality matches X and Z literally", "Case equality is synthesizable in hardware whereas logical equality is not", "Logical equality compares only the least significant bits of each operand", "Case equality ignores the width of the two operands being compared"], a: 0, why: "Logical equality returns X if either side contains X or Z, while case equality gives a definite answer. That makes case equality a simulation construct, not something to synthesise." },
{ t: "rtl-verilog", d: 2, q: "What does a generate for loop with a genvar create?", o: ["Replicated hardware instances or blocks, decided during elaboration and fixed thereafter", "A loop that executes once per clock cycle at run time", "A simulation-only construct that has no effect whatsoever on the final netlist that is produced", "A sequential loop that is unrolled by the synthesis tool"], a: 0, why: "The loop runs at elaboration and emits the hardware, so the count must be a constant. It is the standard way to build an array of identical processing elements." },
{ t: "rtl-verilog", d: 2, q: "What does an implicit net declaration hide?", o: ["A typing mistake becomes a new one-bit wire", "A missing port connection is silently tied to ground", "A module with no ports is instantiated by accident", "The tool infers a latch instead of a flip-flop"], a: 0, why: "Referencing an undeclared name creates a single-bit wire, so a mistyped signal quietly becomes a new one. Turning on default_nettype none makes that an error, which is worth doing in every file." },
{ t: "rtl-verilog", d: 2, q: "What is the value of the literal written as eight, apostrophe, h, A5?", o: ["An eight-bit unsigned hexadecimal value equal to 165 decimal", "A signed eight-bit value equal to minus 91 in two's complement", "A hexadecimal string with no defined numeric width", "An eight-digit hexadecimal constant of 32 bits"], a: 0, why: "The size is the bit width, not the digit count, and the base letter chooses the radix. Sized literals are unsigned unless the base is preceded by s." },

// ----------------------------------------------------------------- rtl-nba
{ t: "rtl-nba", d: 1, q: "What is the coding guideline for assignments in always blocks?", o: ["Non-blocking in clocked blocks, blocking in combinational ones", "Non-blocking everywhere, which avoids every possible race condition", "Blocking everywhere, since it matches the order the code is written in", "Whichever reads more naturally, as the two are equivalent in hardware"], a: 0, why: "Non-blocking models the parallel update of flip-flops on an edge, and blocking models the sequential evaluation of combinational logic. Mixing them within one block is where the trouble starts." },
{ t: "rtl-nba", d: 2, q: "Why does swapping two registers work with non-blocking assignments?", o: ["Every right-hand side is sampled before any update lands", "The simulator recognises the swap and inserts a hidden temporary variable", "The two assignments are executed in the order they appear in the source", "Non-blocking assignments are evaluated twice, once for each direction"], a: 0, why: "All the right-hand sides are read in the active region and the updates happen later in the NBA region. That is exactly what a pair of flip-flops does on a clock edge." },
{ t: "rtl-nba", d: 2, q: "What does a shift register coded with blocking assignments produce?", o: ["The input reaches every stage in one clock", "A correct shift register, since the assignments happen in order anyway", "A latch on every stage rather than an edge-triggered flip-flop", "A design that fails to elaborate because of the ordering"], a: 0, why: "Each blocking assignment completes before the next runs, so the new value propagates through the whole chain immediately. The pipeline collapses to a single register." },
{ t: "rtl-nba", d: 3, q: "What is the race when one clocked block writes a variable with a blocking assignment and another reads it?", o: ["A simulation race: old or new depending on scheduling", "The write is lost because two blocks cannot drive the same variable", "The design will not compile, since blocking assignments are single-block only", "The value becomes X for one cycle before settling to the written value"], a: 0, why: "The order in which the two blocks are scheduled is not defined. Blocking updates land in the active region, where the ordering between processes is not defined. The same source can behave differently in two simulators, and differently again in hardware." },
{ t: "rtl-nba", d: 2, q: "Why does the display task show the pre-update value in a clocked block?", o: ["It runs in the active region, before NBA updates settle", "It prints the value that was on the signal in the previous clock cycle", "Non-blocking targets cannot be printed until the block has finished", "The task samples the signal at the falling edge rather than the rising one"], a: 0, why: "Display executes immediately while the non-blocking update is still pending. The strobe task defers until the end of the time step, which is what you usually want when tracing." },
{ t: "rtl-nba", d: 2, q: "What is the effect of a blocking assignment in a combinational always block?", o: ["It behaves like a wire, which is what you want", "It creates a latch for every variable assigned in the block", "It makes the block sensitive only to the first signal in the list", "It delays the result by one delta cycle in simulation"], a: 0, why: "Combinational logic evaluates in order, so blocking matches it exactly and lets you use intermediate variables. Using non-blocking there gives stale intermediates and a simulation that disagrees with the synthesised result." },
{ t: "rtl-nba", d: 2, q: "Why should a testbench drive DUT inputs away from the active clock edge?", o: ["Driving at the edge races with the design's own sampling", "The design's inputs cannot change while the clock is high", "The simulator ignores any change that occurs on a clock edge", "Signals driven at the edge take an extra delta cycle to propagate"], a: 0, why: "Stimulus applied exactly at the edge may or may not be seen that cycle. Driving with non-blocking assignments, or shifting the stimulus away from the edge, removes the ambiguity." },
{ t: "rtl-nba", d: 3, q: "Why can a clocked block that uses a non-blocking assignment still be read correctly by another clocked block in the same cycle?", o: ["The update is deferred to the NBA region", "Because the simulator serialises the two blocks by declaration order", "Because non-blocking assignments complete before any other statement", "Because the reader is automatically delayed by one clock cycle"], a: 0, why: "Every reader in that time step sees the old value, which is what a real flip-flop does. Deferring the update is what makes the model match hardware, where every flop sees the previous state. It is why non-blocking is the rule for clocked logic." },
{ t: "rtl-nba", d: 2, q: "What does a variable assigned in two different always blocks give you?", o: ["A multiple-driver error or an unpredictable result", "A wired-OR between the two driving expressions", "The value from whichever block executes last in the cycle", "A latch that holds whichever value was written most recently"], a: 0, why: "Two procedural drivers on one variable is illegal for a synthesisable design and gives an unpredictable simulation. Each signal should be driven from exactly one block." },
{ t: "rtl-nba", d: 2, q: "In one clocked block, two blocking assignments set a from b and then b from a. What results?", o: ["Both variables end up holding the original value of b", "Both variables end up holding the original value of a", "The two values are exchanged, as they would be with non-blocking", "The result is undefined and depends on the simulator used"], a: 0, why: "The first assignment overwrites a with b, so the second reads the value just written. The swap needs non-blocking assignments to work." },

// ----------------------------------------------------------------- rtl-fsm
{ t: "rtl-fsm", d: 1, q: "What is the standard two-block state machine structure?", o: ["A clocked block for the state register and a combinational block for next state", "A combinational block for the state and a clocked block for the outputs", "Two clocked blocks, one for the state and one for the outputs", "A single block containing both the state and the output logic"], a: 0, why: "Separating the register from the next-state logic keeps each block's coding style consistent and makes the design easy to read. A third block for registered outputs is the common three-block variant." },
{ t: "rtl-fsm", d: 2, q: "What distinguishes a Moore machine from a Mealy machine?", o: ["Moore outputs depend on state alone", "Moore machines always require more states to do the same job", "Mealy machines cannot be implemented in synchronous logic", "Moore outputs are combinational and Mealy outputs are registered"], a: 0, why: "A Mealy output depends on the inputs as well, so it can respond in the same cycle at the cost of glitching and a harder timing path. A Moore machine is a cycle later but cleaner." },
{ t: "rtl-fsm", d: 2, q: "Why include a default branch in a state machine's case statement?", o: ["It steers illegal states to a safe recovery state", "It reduces the number of logic levels the tool has to build", "It prevents the synthesis tool from inferring a latch on the state", "It makes the state encoding one-hot automatically"], a: 0, why: "An upset or a decoding error can land the machine in an unused encoding, and without a default it may stay there. Recovering deliberately is cheap insurance." },
{ t: "rtl-fsm", d: 3, q: "What is the practical advantage of one-hot encoding on an FPGA?", o: ["Next-state logic becomes a wide shallow OR", "It uses fewer flip-flops than a binary encoding for the same state count", "It makes every illegal state impossible to reach by construction", "It removes the need for a reset, since only one bit is ever set"], a: 0, why: "That maps naturally onto lookup tables and usually meets timing more easily than binary. Registers are plentiful in fabric and the decode is shallow, so one-hot often runs faster. It does use more flops, and it certainly does not make illegal states impossible." },
{ t: "rtl-fsm", d: 2, q: "Why do Mealy outputs glitch more than Moore outputs?", o: ["They are combinational functions of the inputs", "They are registered and therefore delayed by one cycle", "They depend on the state encoding chosen by the tool", "They are driven from more than one always block"], a: 0, why: "Any change on an input propagates straight through the output logic, including the transient hazards. External logic that acts on a level rather than a clocked sample can be fooled by those spikes." },
{ t: "rtl-fsm", d: 2, q: "What does registering a state machine's outputs cost and buy?", o: ["Glitch-free timing-friendly outputs, one cycle later", "A larger state encoding but a shorter combinational path", "Faster response at the cost of extra flip-flops", "Immunity to illegal states at the cost of area"], a: 0, why: "The output comes from a flop, so it is clean and its timing is easy, but it arrives a cycle after the state changes. Decoding from the next state instead recovers the cycle." },
{ t: "rtl-fsm", d: 2, q: "What does a state machine with no reset risk?", o: ["Starting in an unknown state after configuration", "Failing to meet timing on the next-state path", "Inferring latches instead of edge-triggered flip-flops", "Being optimised away entirely by the synthesis tool"], a: 0, why: "On an FPGA the initial value from configuration usually saves you, but in an ASIC the state is genuinely unknown. An explicit reset also makes simulation deterministic from time zero." },
{ t: "rtl-fsm", d: 3, q: "Why is a very long combinational next-state path a problem beyond timing?", o: ["Deep logic leaves the tool little freedom", "It causes the state register to infer latches instead of flops", "It prevents the tool from using one-hot encoding", "The path cannot be constrained by a normal clock definition"], a: 0, why: "Small changes elsewhere can then push it over the limit unpredictably. A critical path with no slack becomes brittle: every unrelated edit reshuffles placement and it fails again. Pipelining it, or simplifying the condition, is more durable than repeated re-runs." },
{ t: "rtl-fsm", d: 2, q: "What is a common cause of a state machine that never leaves its idle state?", o: ["A transition condition that can never be true", "The state register being clocked on the wrong edge", "Too few bits allocated to the state encoding", "The default branch overriding every other case"], a: 0, why: "A condition gated by a signal that is never asserted, or a handshake that is never acknowledged, leaves the machine stuck. Waveform-tracing the condition itself, rather than the state, finds it quickly." },
{ t: "rtl-fsm", d: 2, q: "How would you detect a state machine that has hung in production?", o: ["A watchdog counter that flags too long in one state", "A parity bit across the state register bits", "A second copy of the machine running in lockstep", "A formal proof that the machine is always live"], a: 0, why: "Counting cycles spent in each state and raising an alarm past a bound is cheap and catches both hangs and unexpected loops. Formal liveness proofs are valuable at design time but do not help in the field." },

// ----------------------------------------------------------------- rtl-cdc
{ t: "rtl-cdc", d: 1, q: "What does a two-flop synchroniser actually do?", o: ["Gives the first flop most of a cycle to resolve", "Guarantees that metastability can never occur at all", "Delays the signal by exactly one nanosecond", "Converts the signal into a level rather than a pulse"], a: 0, why: "It does not prevent metastability; it gives it time to settle so the probability of propagating is vanishingly small. That probability is quantified by the mean time between failures." },
{ t: "rtl-cdc", d: 2, q: "Why is a two-flop synchroniser wrong for a multi-bit bus?", o: ["The bits can settle in different cycles, giving an incoherent word", "A synchroniser can only be applied to a signal that changes slowly", "The second flop would need a separate clock for each bit", "Metastability cannot occur on a bus, only on a single signal"], a: 0, why: "Each bit resolves independently, so the receiver may capture a mixture of old and new. Gray coding, or a handshake with a data hold, is what keeps the word coherent." },
{ t: "rtl-cdc", d: 2, q: "Why are Gray-coded pointers used in an asynchronous FIFO?", o: ["Only one bit changes per increment, so a mis-sample is old or new", "Gray code simplifies the arithmetic on the pointers considerably", "Gray code allows the pointers to be compared without synchronising", "It halves the number of bits needed to represent the pointer"], a: 0, why: "A pointer sampled mid-transition can only be the value before or after, never a corrupt combination. That is exactly the property a multi-bit crossing needs." },
{ t: "rtl-cdc", d: 3, q: "Why are an asynchronous FIFO's full and empty flags conservative rather than exact?", o: ["Each side sees a pointer that is always stale", "Because the pointers are Gray coded and cannot be compared exactly", "Because the two clocks may differ in frequency by an unknown amount", "Because the flags are generated combinationally from both pointers"], a: 0, why: "Full can assert early and empty late, but never the reverse. Staleness in the safe direction is the whole design: you may waste a slot but you can never overflow or read empty. Making them exact would require a crossing you cannot have." },
{ t: "rtl-cdc", d: 2, q: "What is a pulse synchroniser for?", o: ["Carrying a single-cycle event to a slower clock domain", "Converting a level into a pulse in the same domain", "Removing metastability from a slowly changing level", "Synchronising two clocks to a common phase"], a: 0, why: "A one-cycle pulse in a fast domain can be missed entirely by a slower one, so it is converted to a toggle, synchronised and edge-detected. The design must also bound how often pulses arrive." },
{ t: "rtl-cdc", d: 2, q: "What is reconvergence in a clock domain crossing?", o: ["Related bits crossing separately then being recombined", "Two clocks converging on the same frequency over time", "A synchroniser whose output feeds back to its input", "Several signals crossing through one shared synchroniser"], a: 0, why: "Each bit takes its own number of cycles, so recombining them downstream can produce a state that never existed. Correct synchronisers on each bit do not help; the bits must cross together." },
{ t: "rtl-cdc", d: 2, q: "Why does simulation usually fail to show a crossing bug?", o: ["The simulator has no model of metastability at all", "Crossings are excluded from the simulation by default", "The testbench cannot drive two clocks at once", "Simulation runs too slowly to reach the failure"], a: 0, why: "The signal simply takes its new value, so the failure only appears in silicon and usually only occasionally. Static CDC analysis, not simulation, is what finds these." },
{ t: "rtl-cdc", d: 2, q: "What does a CDC linting tool check that static timing does not?", o: ["That every crossing has a recognised synchroniser structure", "That the two clocks have a defined phase relationship", "That the synchroniser flops meet setup and hold", "That the design has no combinational loops"], a: 0, why: "Timing analysis on an asynchronous path is meaningless, so those paths are usually excluded from it entirely. The CDC tool is what confirms the structural protection is actually there." },
{ t: "rtl-cdc", d: 3, q: "Why is a handshake crossing slower than a FIFO but still worth using?", o: ["Several cycles per transfer, but no memory needed", "It transfers more data per cycle than a FIFO can manage", "It works even when one of the two clocks is stopped entirely", "It removes the need for synchronisers on the data bits"], a: 0, why: "Each side must see the other's acknowledgement, and it is simple enough to verify by inspection. For occasional control transfers the latency is irrelevant and the simplicity is worth a great deal. For streaming data the round trip per word is unacceptable, which is what a FIFO fixes." },
{ t: "rtl-cdc", d: 2, q: "What must be true of the data when a handshake crossing is used?", o: ["It must be held stable until the acknowledgement returns", "It must be Gray coded before it is presented", "It must be no wider than the synchroniser's flop count", "It must change only on the receiving clock's edge"], a: 0, why: "The request signal crosses through a synchroniser, and the data is sampled once the receiver sees it. Holding the data stable for that whole window is what removes the need to synchronise it." },

// --------------------------------------------------------------- rtl-synth
{ t: "rtl-synth", d: 1, q: "What causes a latch to be inferred in combinational logic?", o: ["An output is not assigned on every path", "The block is sensitive to a clock edge rather than a level", "Blocking assignments are used instead of non-blocking ones", "The output is declared as a wire rather than a variable"], a: 0, why: "If a path leaves the output unassigned, the language says it holds its value, which is a latch. Assigning a default at the top of the block removes every one of them at a stroke." },
{ t: "rtl-synth", d: 2, q: "Why is an inferred latch usually a bug rather than a design choice?", o: ["It is level sensitive, so its timing is hard to close", "Latches cannot be implemented in FPGA fabric at all", "The tool cannot determine the latch's initial value", "A latch consumes far more area than a flip-flop"], a: 0, why: "It can also pass glitches straight through to the output. Static timing analysis of a transparent latch is far harder than of an edge-triggered flop, and most FPGA fabrics implement one inefficiently. Where you genuinely want one, you say so explicitly." },
{ t: "rtl-synth", d: 2, q: "What does a combinational loop in RTL cause?", o: ["An unconstrained path the tool cannot analyse", "The synthesis tool to insert a flip-flop automatically to break it", "A latch to be inferred at the point where the loop closes", "The design to oscillate at exactly the clock frequency"], a: 0, why: "There is no start or end, so timing analysis has nothing to measure and the behaviour depends on delays. The tool will report it, and the fix is always to break the loop with a register." },
{ t: "rtl-synth", d: 3, q: "Why does the tool sometimes refuse to infer a block RAM?", o: ["The code does not match the primitive's timing", "The memory is too small to justify a block RAM primitive", "Block RAM cannot be inferred from behavioural code at all", "The address width does not match the device's native width"], a: 0, why: "Most often the code expects the old data on a write to the same address when the device gives the new. Each family has particular templates for read-first, write-first and no-change behaviour. Matching the vendor's template exactly is the difference between a block RAM and a very large pile of registers." },
{ t: "rtl-synth", d: 2, q: "What does an initial block synthesise to on an FPGA?", o: ["The register's power-up value from the configuration bitstream", "Nothing at all, since initial blocks are simulation only", "A reset circuit that runs once after configuration", "A ROM holding the initial values of every register"], a: 0, why: "SRAM-based FPGAs load flop contents as part of configuration, so an initial value is free. In an ASIC it means nothing, which is why portable code uses an explicit reset." },
{ t: "rtl-synth", d: 2, q: "Why prefer a clock enable to a gated clock in fabric?", o: ["Keep the free-running clock and enable the register instead", "AND the clock with the enable in ordinary fabric logic", "Use a separate clock buffer for each enabled region", "Divide the clock down and select between the two rates"], a: 0, why: "A gate in general logic is not on the clock tree, so its output is skewed and can glitch. Every fabric flip-flop already has an enable input, which costs nothing." },
{ t: "rtl-synth", d: 2, q: "What does casex risk that casez does not?", o: ["An X in the case expression can match any branch", "casex cannot be used with more than four branches", "casex infers a latch when no branch matches", "casex is not supported by most synthesis tools"], a: 0, why: "casex treats X in the expression as a wildcard, so an unexpected X matches the first branch and hides the problem. casez only treats Z as a don't care, which is far safer." },
{ t: "rtl-synth", d: 2, q: "What does the full_case directive actually promise the tool?", o: ["That no other value of the selector will ever occur", "That every branch of the case assigns every output", "That the case will be implemented as a lookup table", "That the selector is one-hot encoded by construction"], a: 0, why: "It lets the tool treat unlisted values as don't care, which is a promise you may not be able to keep. If it is wrong, simulation and hardware diverge, which is why a real default branch is preferred." },
{ t: "rtl-synth", d: 3, q: "Why does a wide multiplexer sometimes fail timing when a case statement does not?", o: ["Priority encoding builds a chain of selections", "Multiplexers cannot be implemented in lookup tables", "The tool always registers the output of a case statement", "A case statement is evaluated at elaboration time"], a: 0, why: "A parallel case decodes in one level, so how the condition is written changes the logic depth. An if-else chain says the first condition wins, which is a priority structure. Where the conditions are mutually exclusive, a case tells the tool it may decode them in parallel." },
{ t: "rtl-synth", d: 2, q: "What is retiming?", o: ["Moving registers across combinational logic to balance path delays", "Adjusting the clock frequency after synthesis has completed", "Re-running synthesis with a different set of timing constraints", "Adding pipeline stages automatically wherever they are needed"], a: 0, why: "The tool relocates existing flops without changing the cycle-level behaviour, so a long path can borrow slack from a short one. It cannot invent latency you did not already have." },

// --------------------------------------------------------------- rtl-verif
{ t: "rtl-verif", d: 1, q: "What does a scoreboard do in a testbench?", o: ["Compares the design's output against a reference model", "Counts how many tests were run during the regression", "Records the coverage achieved by each individual test", "Generates the stimulus that drives the design's inputs"], a: 0, why: "It is the part that decides pass or fail, which is what makes the test meaningful. Everything else, including coverage, only tells you what you exercised." },
{ t: "rtl-verif", d: 2, q: "What does functional coverage measure that code coverage does not?", o: ["Whether the interesting scenarios were actually exercised", "The fraction of lines in the design that were executed", "The number of toggles on each signal in the netlist", "How long the regression took to run to completion"], a: 0, why: "Code coverage tells you the code ran; functional coverage tells you the corner cases you cared about occurred. You need both, and neither guarantees the checks were doing anything." },
{ t: "rtl-verif", d: 2, q: "Why does constrained-random stimulus need legality constraints?", o: ["Illegal input would flag failures that are not real bugs", "Random stimulus cannot be reproduced without them", "Constraints are what make the stimulus cover the state space", "Without them the simulation would never terminate"], a: 0, why: "A protocol has rules, and violating them proves nothing about the design's correct behaviour. The constraints encode what a legal environment can do." },
{ t: "rtl-verif", d: 3, q: "Why is a failing seed more valuable than a passing regression?", o: ["A reproducible case pointing at a real defect", "It proves the constraints are correctly written", "It shows the coverage model is complete", "It means the random generator is working properly"], a: 0, why: "Turn it into a directed test so the bug cannot come back unnoticed once it is fixed. Rerunning with new seeds until it passes discards the one piece of hard information you had. Capture it, fix it, and keep the directed test." },
{ t: "rtl-verif", d: 2, q: "What is an immediate assertion good for?", o: ["Checking a condition at one point in procedural code", "Checking a temporal relationship over several clock cycles", "Proving a property formally without any simulation", "Measuring the coverage of a particular scenario"], a: 0, why: "It is a procedural statement, so it checks something true at that instant. Concurrent assertions are the ones that describe behaviour over time and run continuously." },
{ t: "rtl-verif", d: 2, q: "What does an assertion binding let you do?", o: ["Attach checks to a module without editing its source", "Bind two assertions together so both must hold", "Convert an assertion into a coverage point", "Restrict an assertion to a particular clock domain"], a: 0, why: "You keep the checks in a separate file and attach them to instances, which keeps verification code out of the design. It also lets you add checks to code you are not allowed to modify." },
{ t: "rtl-verif", d: 2, q: "Why should a regression be automated and run continuously?", o: ["A break is found within hours rather than at integration", "It reduces the total simulation time required", "Automated runs give better coverage than manual ones", "It removes the need for a human to look at failures"], a: 0, why: "The cost of a bug rises steeply with how long it sits undetected, and a nightly run bounds that. Keeping regressions manual so that failures get human attention is exactly backwards." },
{ t: "rtl-verif", d: 2, q: "What does a driver do in a layered testbench?", o: ["Turns transactions into pin-level activity on the interface", "It decides whether the design's response was actually correct", "Generates the random transactions to be applied", "Collects coverage from the interface signals"], a: 0, why: "It is the translation layer between the abstract sequence and the wires, which is what lets the sequences stay protocol-agnostic. The monitor does the reverse translation for checking." },
{ t: "rtl-verif", d: 3, q: "What does full code coverage still fail to tell you?", o: ["Whether anything was actually checked", "Which lines of the design were executed", "How many random seeds were used in the run", "Whether the design meets its timing constraints"], a: 0, why: "A test that exercises every line but asserts nothing scores perfectly. Coverage measures stimulus, not checking. Deliberately breaking the design and confirming that a test fails is the only direct measure of whether the checks work." },
{ t: "rtl-verif", d: 2, q: "Why keep the reference model independent of the RTL?", o: ["A shared assumption would be invisible to both", "The model runs faster if it is written separately", "It allows the model to be reused in another project", "The tool requires the two to be in different languages"], a: 0, why: "If the model is derived from the RTL, it inherits the same misunderstanding and the comparison passes. Writing it from the specification is what makes the check meaningful." },

// ------------------------------------------------------------------ rtl-sv
{ t: "rtl-sv", d: 1, q: "What does the SystemVerilog logic type give you over reg?", o: ["One type usable for both procedural and continuous assignment", "A two-state type that simulates considerably faster than reg does", "Automatic initialisation to zero at time zero", "A type that cannot be driven by more than one source"], a: 0, why: "It removes the reg-versus-wire decision for single-driver signals, which is nearly all of them. It is still four-state; bit is the two-state type." },
{ t: "rtl-sv", d: 2, q: "What does always_comb add over always with a wildcard sensitivity list?", o: ["It checks the block really is combinational and runs once at time zero", "It makes the block sensitive to the clock as well", "It allows non-blocking assignments to be used safely", "It prevents every variable in the whole block from ever becoming a latch"], a: 0, why: "The tool errors if you infer a latch or use the wrong assignment style, and it evaluates at time zero so the initial state is settled. It documents intent to both the reader and the tool." },
{ t: "rtl-sv", d: 2, q: "What is the point of always_ff?", o: ["It declares intent, and the tool checks the block really is sequential", "It generates a flip-flop even where the logic is combinational", "It automatically infers the reset behaviour from the sensitivity list", "It allows more than one clock in a single always block"], a: 0, why: "Using a blocking assignment or omitting an edge becomes an error rather than a surprise in the netlist. It costs nothing and catches a whole class of mistakes." },
{ t: "rtl-sv", d: 2, q: "Why prefer a SystemVerilog enum for state encoding over localparam?", o: ["The tool checks assignments and the waveform shows state names", "Enums simulate considerably faster than localparams do", "Only enums can be used in a case statement", "Enums are stored in fewer bits than an equivalent constant"], a: 0, why: "Type checking catches an assignment of a value that is not a state, and the debugger shows names instead of numbers. That second point saves a surprising amount of waveform-reading time." },
{ t: "rtl-sv", d: 3, q: "What is the difference between a packed and an unpacked array?", o: ["Packed is one sliceable vector; unpacked is separate", "Unpacked arrays are synthesizable and packed arrays are not", "Packed arrays may only hold single-bit elements", "Unpacked arrays cannot be passed through a module port"], a: 0, why: "Only packed dimensions can be sliced or used in arithmetic, and both are synthesizable. Packed dimensions go before the name and unpacked after, and only packed ones can be sliced or used in arithmetic. Both are synthesizable, and memories are usually unpacked arrays of packed words." },
{ t: "rtl-sv", d: 2, q: "What does an interface bundle?", o: ["A set of related signals with their direction per module", "Two clock domains and the synchronisers between them", "A protocol checker and the assertions that go with it", "The ports of every module in the design hierarchy"], a: 0, why: "One interface instance replaces a long port list, and a modport declares which direction each signal takes for a given user. It reduces the commonest connection mistakes to a compile error." },
{ t: "rtl-sv", d: 2, q: "What is a struct used for in synthesisable RTL?", o: ["Grouping related fields into one named signal", "Creating a dynamically sized collection of items", "Passing arguments to a task by reference", "Declaring a union of two different types"], a: 0, why: "A packed struct is a vector with named fields, so a bus of address, data and control can travel as one signal. It makes the code readable without changing the hardware at all." },
{ t: "rtl-sv", d: 2, q: "Why is unique or priority on a case statement better than a directive comment?", o: ["The tool checks it in simulation as well as using it in synthesis", "It removes the need for having a default branch of any kind at all", "It makes the case statement formally verified", "It forces the tool to build a parallel decoder"], a: 0, why: "The comment directives told synthesis something simulation ignored, so the two could diverge silently. The keywords are checked at run time, so a violated assumption shows up as a warning." },
{ t: "rtl-sv", d: 2, q: "What does a two-state type such as bit cost you?", o: ["X propagation, so uninitialised logic is no longer visible", "The ability to use the signal in a clocked block", "Compatibility with any Verilog module it connects to", "The option of assigning it a value at time zero"], a: 0, why: "Four-state simulation is what shows you a register you forgot to reset. Two-state runs faster but hides exactly the bug X propagation is there to reveal." },
{ t: "rtl-sv", d: 2, q: "What does a concurrent assertion describe?", o: ["A relationship that must hold over time, checked every clock", "A condition checked once at the point it appears in the code", "A property proved statically before simulation begins", "A coverage point recorded whenever the condition is true"], a: 0, why: "It is clocked and evaluates a sequence across cycles, which is what lets it express a protocol rule. It runs in simulation and can also be handed to a formal tool." },

// ---------------------------------------------------------------- rtl-fpga
{ t: "rtl-fpga", d: 1, q: "What does a lookup table implement?", o: ["Any Boolean function of its inputs", "A memory that can be written at run time by the fabric", "A fixed function chosen when the device is manufactured", "An arithmetic operation on two multi-bit operands"], a: 0, why: "A six-input LUT is a sixty-four-bit truth table, so it can be any function of those six inputs. Larger functions are built by cascading, which is where logic depth comes from." },
{ t: "rtl-fpga", d: 2, q: "What is a DSP slice for?", o: ["A hardened multiply-accumulate unit with pipeline registers", "A dedicated block for implementing floating-point division", "A configurable memory optimised for signal processing data", "A high-speed serial transceiver for streaming samples"], a: 0, why: "It is a fixed multiplier and adder with registers around it, and using those internal registers is what lets it run at full speed. Failing to infer them is the commonest reason a DSP design misses timing." },
{ t: "rtl-fpga", d: 2, q: "Why does a design fail timing after a small unrelated change?", o: ["Placement and routing shift, so a marginal path tips over", "The synthesis tool chooses a different encoding each run", "Small changes always increase the total logic depth", "The timing constraints are re-derived on every build"], a: 0, why: "A path with almost no slack is at the mercy of the placer's randomness. Fixing the path properly, rather than re-running until it passes, is the only stable answer." },
{ t: "rtl-fpga", d: 3, q: "Why should a register be placed in the input output block for an external interface?", o: ["It fixes the delay between the pin and the flop", "IOB registers are internally faster than fabric registers", "It is the only way to drive an output at full voltage", "It removes the need to constrain the input timing"], a: 0, why: "The timing at the connector becomes a specification rather than a placement artefact. A fabric flop's distance from the pin varies from build to build, so the external timing moves with it. Pushing the register into the IOB makes that number constant and reportable." },
{ t: "rtl-fpga", d: 2, q: "What is the practical limit on distributed RAM built from lookup tables?", o: ["It consumes logic resources quickly as it grows", "It cannot be written while the design is running", "It supports only a single read port in every family", "Its contents are lost whenever the clock stops"], a: 0, why: "It is cheap for a few tens of words and very expensive beyond that. Block RAM is the right choice once the array is more than a few hundred bits." },
{ t: "rtl-fpga", d: 2, q: "Why are global clock networks used rather than general routing?", o: ["They give low and closely matched skew to every destination", "They are required by the Verilog language specification", "They allow the clock to run at a higher voltage", "They are the only routing that reaches every region"], a: 0, why: "The tree is balanced so every flop sees the edge at nearly the same time, which is what makes hold analysis tractable. A clock on general routing has uncontrolled skew." },
{ t: "rtl-fpga", d: 2, q: "What does a block RAM's read latency mean for your pipeline?", o: ["The data appears a cycle after the address, so the logic must expect it", "The read must be requested two cycles before it is needed", "Reads always take a fixed time in nanoseconds whatever the clock rate may be", "The address must be held stable until the data is used"], a: 0, why: "A synchronous read registers the address and produces data on the next edge, and an optional output register adds another. Forgetting that latency is a classic off-by-one in an address generator." },
{ t: "rtl-fpga", d: 3, q: "What happens on a simultaneous read and write to the same block RAM address?", o: ["It is family and mode dependent", "The write always wins on every FPGA family", "The read is delayed by one cycle automatically", "The block RAM asserts a collision flag on that port"], a: 0, why: "The port may return old data, new data or an undefined value, and the RTL must describe what the device does. Read-first, write-first and no-change are all offered and they are not interchangeable. Matching the vendor's template is what makes the inference succeed and the simulation match." },
{ t: "rtl-fpga", d: 2, q: "Why does congestion cause timing failure even when logic depth is low?", o: ["Routing detours add delay that logic optimisation cannot remove", "The tool inserts extra buffers onto each and every one of the congested nets", "Congested regions run at a lower clock frequency", "The placer gives up and uses a random placement"], a: 0, why: "Signals forced around a busy region travel far further than their logical distance implies. Floorplanning, replicating high-fanout drivers, or physical optimisation are the usual remedies." },
{ t: "rtl-fpga", d: 2, q: "What does high fanout on a control signal cost?", o: ["A large routing delay unless the driver is replicated", "Extra flip-flops to hold the signal at each destination", "A separate clock domain for each group of loads", "An increase in the design's static power consumption"], a: 0, why: "One driver reaching thousands of loads is a long, slow net, and the tool may or may not replicate it automatically. Duplicating the source register deliberately is the reliable fix." },

// --------------------------------------------------------------- rtl-arith
{ t: "rtl-arith", d: 2, q: "Why does a long ripple-carry adder limit clock frequency?", o: ["The carry must propagate through every bit position", "It uses more lookup tables than a carry-select adder", "The routing between bit slices is unusually long", "It cannot be pipelined in any useful way at all"], a: 0, why: "The delay grows with width, which is why modern fabrics have dedicated fast carry chains. Beyond what those handle, you pipeline the adder or restructure the accumulation." },
{ t: "rtl-arith", d: 2, q: "What is bit growth discipline?", o: ["Tracking how each operation widens the result and deciding where to round", "Simply using the widest available type for each and every intermediate value", "Growing the result width only at the final output stage", "Keeping every signal the same width throughout the datapath"], a: 0, why: "Each addition adds a bit and each multiply adds the operand widths, so the width at every node should be a decision rather than an accident. That is what stops overflow appearing only on a rare input." },
{ t: "rtl-arith", d: 2, q: "Why is truncation a problem in a long filter chain?", o: ["It biases every result towards negative", "It is noticeably slower than rounding to nearest", "It reduces the effective word length by one bit per stage", "It makes the filter's response nonlinear at low amplitudes"], a: 0, why: "Truncation is a floor, so the error is always in the same direction and accumulates as a DC offset. Rounding costs an adder and makes the error zero-mean, which is worth it once stages cascade." },
{ t: "rtl-arith", d: 3, q: "Why is fixed point described as a convention rather than a type?", o: ["The hardware only ever sees integers", "Because the standard has no fixed-point keyword", "Because the position of the point changes at run time", "Because fixed point is only used in simulation"], a: 0, why: "Where the binary point sits exists solely in your documentation and in the shifts you apply. Nothing checks it, so a Q15 value fed to a block expecting Q12 is a silent scaling bug. Naming signals with their format and commenting the alignment at every boundary is the practical discipline." },
{ t: "rtl-arith", d: 2, q: "What does carry-save addition achieve?", o: ["It defers carry propagation, keeping each stage's delay constant", "It removes the need for having any final carry-propagate adder at all", "It halves the number of bits needed to hold the sum", "It handles signed operands better than a normal adder"], a: 0, why: "Each stage reduces three operands to two in constant time, whatever the width. One full adder at the end completes the sum, which is the structure inside a fast multiplier." },
{ t: "rtl-arith", d: 2, q: "Why does saturating arithmetic suit a signal path?", o: ["It clamps at the extreme rather than wrapping to the opposite sign", "It uses fewer resources than wrapping arithmetic", "It prevents overflow from occurring in the first place", "It preserves the exact value even when the range has been exceeded entirely"], a: 0, why: "A wrap turns a large positive into a large negative, which is a violent discontinuity in a filter. Saturation degrades gracefully, which is almost always the behaviour you want." },
{ t: "rtl-arith", d: 2, q: "What does a barrel shifter cost compared with a sequential shifter?", o: ["More logic, but a constant one-cycle shift by any amount", "Less logic, at the cost of several cycles per shift", "The same logic, but a longer combinational path", "More registers, but a shorter critical path"], a: 0, why: "It is a tree of multiplexers, one stage per bit of the shift amount, so it is area for latency. A sequential shifter is tiny and takes as many cycles as places shifted." },
{ t: "rtl-arith", d: 3, q: "Why is division avoided in RTL where possible?", o: ["It has no cheap combinational form", "Division is not supported by the Verilog language", "Divide results cannot be represented in fixed point", "Division always requires a floating-point unit"], a: 0, why: "It costs either many cycles in an iterative unit or a great deal of logic in a pipelined one. Multiplication by a reciprocal, a shift for a power of two, or a lookup table all avoid it. Where a real divide is needed, an iterative unit with a valid handshake is the usual compromise." },
{ t: "rtl-arith", d: 2, q: "What does multiplying two Q15 numbers produce?", o: ["A Q30 result needing a shift to return to Q15", "A Q15 result, since the format is preserved", "A Q16 result, one bit wider than the inputs", "A Q45 result, because the fractions multiply"], a: 0, why: "Fractional bits add, so the product has thirty of them plus the sign bits. Shifting left by one and taking the upper half is the standard way back." },
{ t: "rtl-arith", d: 2, q: "Why does an accumulator need more bits than the values it sums?", o: ["Repeated addition grows the range logarithmically with the count", "The accumulator must hold the product as well as the sum", "Rounding at each step consumes one bit of precision", "The extra bits are required by the multiply-accumulate primitive"], a: 0, why: "Summing N values needs about log2 of N extra bits to avoid overflow in the worst case. Guard bits in the accumulator are cheap; discovering the overflow in the field is not." },

// ---------------------------------------------------------------- rtl-fifo
{ t: "rtl-fifo", d: 1, q: "What does a FIFO decouple?", o: ["Producer and consumer rates, within the depth available", "Two clock domains, without needing any synchronisers", "The read and write widths, which may differ freely", "The design's timing from its physical placement"], a: 0, why: "It absorbs a mismatch in instantaneous rate, but the average rates must still match or it fills or empties. Depth buys you burst tolerance, not a permanent rate conversion." },
{ t: "rtl-fifo", d: 2, q: "How deep must a FIFO be to absorb a burst?", o: ["The burst length minus what the sink drains during it, plus margin", "Exactly the burst length, with no margin required", "Twice the burst length, so as to allow for the entire round trip time", "The product of the burst length and the rate ratio"], a: 0, why: "The sink keeps taking data during the burst, so only the excess needs storing. The margin covers the latency of the flow-control signal getting back to the source." },
{ t: "rtl-fifo", d: 2, q: "What is a skid buffer for?", o: ["Holding the beat that arrives while the stall propagates", "Converting between two entirely different sorts of data width", "Crossing a single beat between clock domains", "Reordering beats that arrive out of sequence"], a: 0, why: "Ready takes a cycle to reach the upstream, so one more beat is already in flight when you stall. One register of storage is enough to catch it without losing throughput." },
{ t: "rtl-fifo", d: 3, q: "Why does registering the ready signal cost throughput unless you are careful?", o: ["A registered ready arrives a cycle late", "Registering ready makes the interface non-compliant", "The ready signal cannot be registered at all", "It forces the FIFO to be twice as deep"], a: 0, why: "The source keeps sending into a stall unless a skid buffer catches the beat. Ready is a combinational path back to the source, and cutting it for timing introduces exactly this problem. The skid buffer is the standard structure that gives you both." },
{ t: "rtl-fifo", d: 2, q: "What does almost-full mean and why does it exist?", o: ["A threshold that warns before the FIFO is full", "A flag indicating the FIFO has more entries than half its depth", "The point at which the FIFO switches to a slower clock", "A signal that the FIFO has been full at some point"], a: 0, why: "A source with pipeline latency then has time to stop before overflowing. If the source needs three cycles to react, full arrives too late. The threshold is set from that latency, which makes it a design parameter rather than a convenience." },
{ t: "rtl-fifo", d: 2, q: "Why must a synchronous FIFO's flags be generated from both pointers?", o: ["Full and empty are relationships between them, not properties of one", "The pointers wrap at different times in each domain", "Only the write pointer is ever made available in the read clock domain", "The flags must be Gray coded before they are used"], a: 0, why: "Empty is pointers equal and full is pointers equal with the wrap bit different, which is why the pointer is one bit wider than the depth requires. Both flags need both values." },
{ t: "rtl-fifo", d: 2, q: "What does a first-word fall-through FIFO give you?", o: ["The first word is visible on the output before any read is asserted", "A lower latency, because the memory itself is entirely combinational", "The ability to read and write on the same cycle", "A guarantee that words are never reordered"], a: 0, why: "The consumer can look at the data and decide, rather than issuing a read and waiting. It costs a little logic on the output path and simplifies a great many consumers." },
{ t: "rtl-fifo", d: 3, q: "What goes wrong if a FIFO's depth is not a power of two?", o: ["Pointer wrapping needs an explicit comparison", "The FIFO cannot be implemented in block RAM", "The Gray coding of the pointers is no longer valid", "The read and write pointers can never be compared"], a: 0, why: "The wrap-bit trick for distinguishing full from empty no longer works. A power of two lets the pointer simply overflow and the extra bit distinguish full from empty. Other depths are perfectly possible but the pointer arithmetic has to be written explicitly." },
{ t: "rtl-fifo", d: 2, q: "Why does a FIFO not fix a permanent rate mismatch?", o: ["It fills or empties and then stalls one side", "The pointers eventually overflow and corrupt the data", "The flags become unreliable once the FIFO has wrapped", "The clock domains drift apart until the crossing fails"], a: 0, why: "Storage buys time, not bandwidth, so a source faster than the sink will eventually back-pressure regardless of depth. Sizing the FIFO for the average rate is a design error." },
{ t: "rtl-fifo", d: 2, q: "What does a FIFO's occupancy count tell you during bring-up?", o: ["Whether the sizing assumption about burstiness was right", "How many clock cycles the data spent inside the FIFO", "Whether the two clock domains are running at the same rate", "The maximum throughput the interface can sustain"], a: 0, why: "Watching the high-water mark under real traffic shows whether the depth was generous or marginal. It is one of the cheapest pieces of instrumentation to add and among the most useful." },

// ----------------------------------------------------------------- rtl-axi
{ t: "rtl-axi", d: 1, q: "When does a transfer occur on a valid and ready interface?", o: ["On the clock edge where both are high", "As soon as valid is asserted by the source", "When ready is asserted, regardless of valid", "One cycle after both signals have been high"], a: 0, why: "Both must be high at the same rising edge, which is what makes the handshake symmetric. Either side may assert first and wait for the other." },
{ t: "rtl-axi", d: 2, q: "What must a source never do once valid is asserted?", o: ["Deassert valid before the transfer completes", "Change ready in the same cycle as valid", "Assert valid for more than one cycle at a time", "Wait for ready before presenting the data"], a: 0, why: "Valid must stay asserted, with the data unchanged, until ready arrives. Withdrawing an offer is the single commonest protocol violation and it deadlocks or corrupts the stream." },
{ t: "rtl-axi", d: 2, q: "What does the last signal mark on a stream?", o: ["The final beat of a packet or frame", "The last transfer before the source stalls", "The end of the current burst of the same address", "The final byte enable of the current beat"], a: 0, why: "It gives the sink a packet boundary without a separate length field. Getting it wrong turns two packets into one, which is a bug that only shows up downstream." },
{ t: "rtl-axi", d: 3, q: "What is the practical difference between a memory-mapped and a stream interface?", o: ["Memory-mapped carries addresses; a stream does not", "Memory-mapped offers no burst support of any kind", "Streams cannot carry more than one beat per packet", "Memory-mapped interfaces cannot be pipelined"], a: 0, why: "Memory-mapped also supports random access with separate read and write channels. The choice follows from whether the consumer needs to address the data or simply receive it in order. Mixing them up leads to an interface that carries an address nobody uses." },
{ t: "rtl-axi", d: 2, q: "Why does a memory-mapped protocol separate address and data channels?", o: ["Addresses can be issued ahead of data, allowing multiple outstanding transactions", "The address bus is wider than the data bus", "It halves the number of wires needed overall", "The address must always be registered somewhere before the data eventually arrives back"], a: 0, why: "Independent channels let the interconnect pipeline requests and reorder responses, which is where the bandwidth comes from. A single combined channel would serialise everything." },
{ t: "rtl-axi", d: 2, q: "What does tkeep indicate on a stream?", o: ["Which bytes of the beat are part of the stream content", "Which bytes have been modified since the last beat", "How many beats remain in the current packet", "Whether the beat should be retained by the sink"], a: 0, why: "It marks the valid bytes, which matters on the last beat of a packet whose length is not a whole number of words. tstrb is the related signal that distinguishes data from position bytes." },
{ t: "rtl-axi", d: 2, q: "Why is a register map often generated from a single description?", o: ["The RTL, the header and the documentation cannot then drift apart", "Generated code is always smaller than any hand-written equivalent is", "It allows the register map to change at run time", "It enables formal verification of the whole design"], a: 0, why: "Hand-maintaining three views guarantees they eventually disagree, and the resulting driver bug is hard to find. One source of truth removes the entire class of problem." },
{ t: "rtl-axi", d: 2, q: "Why should a status register with sticky bits be write-one-to-clear?", o: ["A read-modify-write would destroy a flag that arrived in between", "Writing a zero would be ambiguous whenever several of the bits are set", "It halves the number of bus accesses needed", "Sticky bits cannot be cleared by a normal write"], a: 0, why: "Reading, masking and writing back is not atomic with respect to hardware setting another bit. Writing a one to clear only the bits you have observed avoids the race entirely." },
{ t: "rtl-axi", d: 3, q: "Why is a lightweight control interface usually paired with a stream for data?", o: ["Registers need random access, data needs throughput", "The two interfaces cannot share a clock domain", "A stream interface cannot carry a write response", "Control registers must be in a separate address space"], a: 0, why: "One protocol for both makes the control side heavy or the data side slow. The control path is a few reads and writes and the data path is millions of beats. Matching each to its traffic keeps both simple." },
{ t: "rtl-axi", d: 2, q: "What does interoperability buy you when you adopt a standard interface?", o: ["Existing IP, verification components and interconnect all work with it", "The interface runs at a higher clock frequency", "The design becomes considerably smaller than any custom equivalent would", "Timing closure is guaranteed by the specification"], a: 0, why: "Bus functional models, protocol checkers and interconnect generators all exist already. That reuse is usually worth far more than the handful of gates a custom interface would save." },

// ------------------------------------------------------------- rtl-dspfpga
{ t: "rtl-dspfpga", d: 2, q: "Why is an FPGA good at signal processing?", o: ["Hundreds of multipliers operate simultaneously, so throughput scales with resources", "Its clock frequency is much higher than a processor's", "It has considerably better arithmetic precision than any floating-point unit ever does", "It can change its algorithm on every clock cycle"], a: 0, why: "A processor runs fast but does a few operations per cycle; fabric runs slower but does hundreds. That is why the crossover is about parallelism, not clock rate." },
{ t: "rtl-dspfpga", d: 2, q: "What does folding a filter mean?", o: ["Reusing one arithmetic unit over many cycles", "Splitting the filter into two half-rate paths", "Folding the coefficients about the centre tap", "Combining two filters into a single structure"], a: 0, why: "Less area, but throughput falls and the control logic grows. It is the right trade when the sample rate is far below the clock rate." },
{ t: "rtl-dspfpga", d: 2, q: "How do you exploit symmetry in a linear-phase FIR?", o: ["Pre-add the symmetric sample pair, then multiply once", "Store only half the coefficients and mirror the addresses", "Run the filter twice and average the two results", "Use a half-band structure with alternate zero taps"], a: 0, why: "Symmetric taps share a coefficient, so one multiplier serves two taps. That halves the multiplier count, which on a DSP-slice-limited design is the whole budget." },
{ t: "rtl-dspfpga", d: 3, q: "Why does a transposed FIR structure often meet timing more easily?", o: ["A register between each tap breaks the adder chain", "It uses fewer multipliers than the direct form", "The coefficients can be stored in block RAM", "It removes the need for a pipeline register on the input"], a: 0, why: "There is then no long combinational path however many taps the filter has. In the direct form the sum ripples through every tap combinationally. The transposed form registers between stages, at the cost of a higher fanout on the input sample." },
{ t: "rtl-dspfpga", d: 2, q: "What is a systolic array?", o: ["A chain of identical registered stages with local connections only", "An array of processors sharing a common memory", "A structure that adapts its coefficients while running", "A multiplier tree that reduces partial products in parallel"], a: 0, why: "Data flows rhythmically through neighbouring cells, so routing stays short and local and the clock rate stays high. It is the natural mapping for a convolution onto fabric." },
{ t: "rtl-dspfpga", d: 2, q: "What limits how many DSP slices you can actually use?", o: ["Routing and the ability to feed them with data every cycle", "The number of clock domains the device supports", "The total power the device is permitted to dissipate", "The width of the external memory interface"], a: 0, why: "A slice that is idle because its operands cannot arrive is wasted. Data movement, not arithmetic, is usually what caps a signal processing design in fabric." },
{ t: "rtl-dspfpga", d: 2, q: "Why use the DSP slice's internal pipeline registers?", o: ["Without them the slice runs far below its rated frequency", "They reduce the number of slices the design consumes", "They allow the slice to perform division as well", "They are required for signed arithmetic to work"], a: 0, why: "The rated speed assumes the internal registers are used, and if they are not inferred the tool routes logic around the hard block. Matching the vendor's inference template is what turns them on." },
{ t: "rtl-dspfpga", d: 3, q: "How do you choose between a fully parallel and a time-multiplexed implementation?", o: ["Compare the sample rate with the clock rate", "Always choose parallel, since fabric is cheap", "Base it on the number of coefficients in the filter", "Choose whichever uses fewer block RAMs"], a: 0, why: "The ratio tells you how many cycles are available per sample, and so how much hardware can be shared. Two thousand clock cycles per sample means one multiplier can do the work of two thousand. Working that ratio out first is what makes the architecture decision obvious." },
{ t: "rtl-dspfpga", d: 2, q: "What does a CIC filter give you in fabric?", o: ["Decimation with adders and delays only, no multipliers", "A perfectly flat passband with no compensation needed", "A sharp transition band for very few resources", "Linear phase without any coefficient storage"], a: 0, why: "It suits a very high rate front end where multipliers would be impossible. The sinc-shaped droop is corrected by a short FIR running at the lower rate afterwards." },
{ t: "rtl-dspfpga", d: 2, q: "Why is fixed point still the default in fabric?", o: ["A fixed-point multiplier maps directly onto a DSP slice", "Floating point cannot be implemented in fabric at all", "Fixed point is more accurate than floating point", "Floating-point results are not reproducible run to run"], a: 0, why: "Floating point costs several slices and a good deal of logic per operation, and modern devices with hard floating-point blocks are the exception. Where the dynamic range is known, fixed point is simply cheaper." },

// ----------------------------------------------------------------- rtl-soc
{ t: "rtl-soc", d: 2, q: "Why does a processor read stale data after a DMA transfer?", o: ["The cache holds a copy that predates the write", "The DMA controller wrote to the wrong address", "The transfer completed after the read was issued", "The memory controller reordered the accesses"], a: 0, why: "The DMA writes to memory behind the cache, so the cached line is out of date. Invalidating the range before reading, or using a non-cached buffer, is the fix." },
{ t: "rtl-soc", d: 2, q: "What does a memory barrier do?", o: ["Prevents the processor or compiler reordering accesses across it", "Flushes the entire cache to main memory", "Blocks other bus masters until it completes", "It synchronises the two clock domains right inside the interconnect"], a: 0, why: "It ensures a configuration write really precedes the start command, which is the classic peripheral bug. It says nothing about caches unless the architecture ties the two together." },
{ t: "rtl-soc", d: 2, q: "Why is polling a status register a poor choice with a deadline?", o: ["It costs CPU time and its latency is unbounded", "Status registers cannot be read reliably while running", "Polling requires the peripheral to be in a special mode", "The register value is cached and may be stale"], a: 0, why: "You cannot say when the poll will next run relative to the event. An interrupt or a DMA completion signal gives a bounded response, which is what a deadline needs." },
{ t: "rtl-soc", d: 3, q: "What is the difference between an edge-triggered and a level-triggered interrupt from fabric?", o: ["An edge can be missed; a level must be cleared", "Edge interrupts cannot be shared between devices", "Level interrupts are only supported on some processors", "Edge interrupts always have a lower latency"], a: 0, why: "An edge is lost if the pulse is too short or arrives while masked, and a level re-fires until cleared in fabric. The two failure modes are opposite, and which you choose changes what the handler must do. Level is usually safer, provided the clear path back to fabric actually works." },
{ t: "rtl-soc", d: 2, q: "What is the sensible bring-up order for a new SoC design?", o: ["Clocks and reset, then boot and a serial port, then peripherals one at a time", "The fabric first, and only after all of that the processor and its own software", "The full data path first, since it is the hardest part", "Everything at once, then debug whatever does not work"], a: 0, why: "Each step depends on the one before it, and a serial port gives you a window into everything after. Bringing up several things at once means you cannot attribute a failure." },
{ t: "rtl-soc", d: 2, q: "Why does a register map generated from one description reduce bugs?", o: ["The RTL, the C header and the documentation stay consistent", "Generated registers are faster to access", "It allows the address map to be changed at run time", "It removes the need to verify the register interface"], a: 0, why: "Drift between the three is the usual cause of a driver writing the wrong bit. Generation makes that impossible rather than merely unlikely." },
{ t: "rtl-soc", d: 2, q: "What does a DMA descriptor chain give you?", o: ["Several transfers queued without processor intervention between them", "A guarantee that transfers complete in order", "Automatic cache invalidation after each transfer", "The ability to transfer data directly between any two separate peripherals"], a: 0, why: "The controller follows the chain, so a long sequence of scattered transfers costs one interrupt instead of many. Building the chain correctly, including its terminator, is the fiddly part." },
{ t: "rtl-soc", d: 3, q: "Why is a peripheral's interrupt usually cleared before the handler returns?", o: ["A level source still asserted re-enters the handler", "Because the controller cannot mask the interrupt", "Because the processor clears it automatically otherwise", "Because clearing it later would lose the next event"], a: 0, why: "It looks like a hang, and it is one of the commonest bring-up failures. Reading a status register is often not enough; many peripherals need an explicit write to clear. Checking that in the datasheet before writing the handler saves a long afternoon." },
{ t: "rtl-soc", d: 2, q: "What does an AXI interconnect actually do?", o: ["Routes transactions between masters and slaves and arbitrates between them", "Converts between different clock frequencies only", "Buffers absolutely all of the data passing through it inside one very large FIFO", "Translates virtual addresses into physical ones"], a: 0, why: "It decodes addresses, arbitrates competing masters and may convert width, clock domain and protocol. Understanding its arbitration is what explains an unexpected latency." },
{ t: "rtl-soc", d: 2, q: "Why include a version register readable from software?", o: ["A board in the lab can say exactly which bitstream it is running", "It allows the driver to reconfigure the fabric", "It is required by the AXI specification", "It provides a way of resetting the whole of the fabric from software"], a: 0, why: "A git hash and a dirty flag in a register removes an entire class of confusion about what is actually loaded. It costs a handful of flops." },

// --------------------------------------------------------- rtl-constraints
{ t: "rtl-constraints", d: 1, q: "What is the first thing that must be constrained in any design?", o: ["Every primary clock and every generated clock", "The input and output delays at the pins", "The multicycle and false paths", "The maximum fanout on high-fanout nets"], a: 0, why: "Without a clock definition the tool has no reference and reports nothing, which looks like success. Everything else in the constraint file depends on the clocks being right first." },
{ t: "rtl-constraints", d: 2, q: "What does an input delay constraint describe?", o: ["When the data arrives at the pin relative to the clock", "How long the signal takes to reach the first flop", "The maximum delay the tool may add to the path", "The skew between the input clock and the data"], a: 0, why: "It tells the tool what the outside world does, which is the only way it can check the setup and hold at your first register. Leaving it out means that path is unconstrained and unchecked." },
{ t: "rtl-constraints", d: 2, q: "What is the danger of an unconstrained path?", o: ["It is never analysed, so it shows as no violation", "It is automatically given the tightest possible constraint", "The tool refuses to complete place and route", "It is optimised more aggressively than other paths"], a: 0, why: "No violation and no path are indistinguishable in the report, so the design looks clean. Unconstrained paths are the most likely cause of a board that fails intermittently." },
{ t: "rtl-constraints", d: 3, q: "When is a multicycle path constraint legitimate?", o: ["When the design genuinely allows several cycles", "When a path fails timing by only a small margin", "When the path crosses between two clock domains", "When the path drives an output pin directly"], a: 0, why: "For example behind an enable asserted only every fourth cycle. It is a statement about the design's behaviour, not a way to silence a report. Applying it to a path that really does need one cycle guarantees a hardware failure." },
{ t: "rtl-constraints", d: 2, q: "What does a false path declaration assert?", o: ["That the path can never be active, or is already handled asynchronously", "That the path is not on the critical path", "That the path may be allowed to take absolutely any number of cycles at all", "That the path should be optimised for area"], a: 0, why: "A genuinely asynchronous crossing already protected by a synchroniser, or a path that cannot be exercised, is a false path. Slow paths you intend to fix later are not." },
{ t: "rtl-constraints", d: 2, q: "Why is declaring clock groups asynchronous better than listing paths?", o: ["It covers both directions concisely and is far less error-prone", "It applies only to the generated clocks found within a whole design", "It automatically inserts synchronisers where needed", "It allows the two clocks to share one global buffer"], a: 0, why: "Enumerating every path between two domains is tedious and easy to get incomplete. The group declaration says what you mean, once, in both directions." },
{ t: "rtl-constraints", d: 2, q: "What does clock uncertainty account for?", o: ["Jitter and skew, subtracted from the available period", "The difference between the specified and actual frequency", "The delay through the clock tree to each flop", "The tolerance on the crystal driving the board"], a: 0, why: "It reserves margin so the analysis is not optimistic about the real clock. Insertion delay through the tree is a separate quantity the tool models directly." },
{ t: "rtl-constraints", d: 3, q: "Why does a hold violation not go away when you slow the clock down?", o: ["Hold is checked between edges of the same event", "Because hold checks apply only to asynchronous inputs", "Because the tool ignores hold until the design is routed", "Because slowing the clock increases the hold requirement"], a: 0, why: "It depends on the shortest path delay rather than on the clock period. Setup is a race against the next edge and hold is a race against the same edge. That is why hold failures are fixed in the implementation, not in the constraint." },
{ t: "rtl-constraints", d: 2, q: "What does negative slack on a path mean?", o: ["The path is slower than the constraint allows", "The path has more margin than required", "The constraint on that path is missing", "The path crosses a clock domain boundary"], a: 0, why: "Slack is required time minus arrival time, so negative means it did not make it. The worst negative slack figure is the headline number for whether the design closes." },
{ t: "rtl-constraints", d: 2, q: "Why should constraints be reviewed as carefully as the RTL?", o: ["A wrong constraint hides a real failure or invents a false one", "Constraints determine the resource usage of the design", "The tool cannot parse constraints that are inconsistent", "Constraints are automatically generated from the RTL"], a: 0, why: "The constraint file decides what is checked at all, so an error there is invisible in the timing report. Reviewing it is the only way to know the clean report means anything." },

// -------------------------------------------------------- rtl-lint-formal
{ t: "rtl-lint-formal", d: 2, q: "What does a lint tool catch that simulation does not?", o: ["Structural problems on paths no test happened to exercise", "Functional bugs buried deep in the design's own core algorithm", "Timing failures that only appear after routing", "Protocol violations on the external interfaces"], a: 0, why: "Incomplete sensitivity lists, width mismatches and inferred latches are found by inspection, without needing a stimulus. It is the cheapest verification you can run." },
{ t: "rtl-lint-formal", d: 2, q: "What is formal property checking good at?", o: ["Bounded control logic such as arbiters, FIFOs and protocol interfaces", "Verifying a complete system including its software", "Measuring the coverage achieved by a regression", "Checking that the design really meets every one of its timing constraints"], a: 0, why: "It shines where the state space is large but each property is simple. Data-path-heavy blocks with wide arithmetic are where it usually runs out of capacity." },
{ t: "rtl-lint-formal", d: 3, q: "What does an inconclusive formal result actually mean?", o: ["Neither proved nor disproved in its bounds", "The property is written incorrectly", "The design violates the property somewhere", "The property holds for all reachable states"], a: 0, why: "You have no information either way, and must simplify or accept a bounded proof. It is not a pass and not a fail. Reducing the state space, strengthening the assumptions or accepting a bounded depth are the usual responses." },
{ t: "rtl-lint-formal", d: 2, q: "What is the danger of over-constraining a formal run?", o: ["A property can become vacuously true", "The proof takes far longer to complete", "The tool reports a false counterexample", "The property is checked on fewer clock cycles"], a: 0, why: "An assumption that excludes the very inputs that would break the property makes it pass while proving nothing. Checking for vacuity is part of using the tool properly." },
{ t: "rtl-lint-formal", d: 2, q: "What does equivalence checking confirm?", o: ["That the netlist is functionally identical to the RTL", "That two different designs meet the same specification", "That the design matches its reference model", "That the constraints are consistent with the design"], a: 0, why: "It is the check after synthesis, or after a manual netlist edit, that nothing changed functionally. It is not a substitute for verifying the RTL was right in the first place." },
{ t: "rtl-lint-formal", d: 2, q: "Why does Verilog need lint more than a strongly typed language?", o: ["Implicit nets, width mismatches and truncation are all legal and silent", "Verilog has no support for user-defined types", "Verilog simulators are considerably less accurate than any of the VHDL ones", "Verilog cannot express a design hierarchically"], a: 0, why: "The language accepts a great deal that a strongly typed one would reject at compile time. The lint tool restores the checking that the language chose not to do." },
{ t: "rtl-lint-formal", d: 3, q: "What is the value of writing assertions during design rather than after?", o: ["You capture the assumptions while still in mind", "Assertions written early run faster in simulation", "The tool can only accept assertions written in the design file", "Early assertions are automatically converted to coverage"], a: 0, why: "They then fail the moment somebody violates them, rather than being reverse-engineered later. The interesting assertions are the invariants you believed while writing the logic. Written later, they tend to restate what the code does rather than what it should do." },
{ t: "rtl-lint-formal", d: 2, q: "What does a coverage property record?", o: ["That an interesting scenario actually occurred during the run", "That a required behaviour was never violated", "That a given line of the code was actually executed at least once", "That a signal toggled in both directions"], a: 0, why: "Assertions say something must not happen; coverage says something should happen at least once. A regression where a coverage point is never hit is not exercising what you think." },
{ t: "rtl-lint-formal", d: 2, q: "Why should lint warnings be triaged rather than ignored wholesale?", o: ["A real bug hides among the noise if nobody reads the list", "Lint warnings prevent the design from being synthesised", "Each warning corresponds to a timing violation", "Warnings become errors in the next tool version"], a: 0, why: "A thousand-line warning list is functionally the same as no tool at all. Waiving the categories you have decided about, so that the remaining list is short, is what keeps it useful." },
{ t: "rtl-lint-formal", d: 2, q: "What is a good first property to write for a FIFO?", o: ["It never asserts full and empty at the same time", "Its depth is always a power of two", "The read pointer is always Gray coded", "Its output is always registered on every single read"], a: 0, why: "Mutual exclusion of the flags is simple, catches a real class of pointer bug and is easy for a formal tool to prove. Overflow and underflow properties follow naturally from it." },

// ---------------------------------------------------------------- rtl-flow
{ t: "rtl-flow", d: 2, q: "Why should a build record the exact source revision it came from?", o: ["A board in the lab can be tied back to what built its bitstream", "It reduces the size of the generated bitstream", "The tool requires a revision for incremental builds", "It allows the build to be reproduced on another machine"], a: 0, why: "Without it, a bitstream on a board is an unknown, including whether the tree was clean. A hash and a dirty flag in a readable register cost almost nothing." },
{ t: "rtl-flow", d: 2, q: "Why archive the bitstream rather than plan to rebuild it?", o: ["Synthesis and place and route are not reproducible across tool versions", "Bitstreams compress better than source archives", "Rebuilding it would always require having the original licence file as well", "The source may not compile on a newer machine"], a: 0, why: "The same source and a different tool version gives a different, equally valid, result. If you need the exact image that shipped, the only reliable way is to have kept it." },
{ t: "rtl-flow", d: 2, q: "What should happen the moment a bug is found at integration?", o: ["Add a case to the module's testbench that reproduces it", "Fix it in the integration testbench instead", "Note it and move on if the workaround is simple", "Increase the coverage target for that module"], a: 0, why: "Reproducing it at module level closes the gap permanently and gives you a fast test. Fixing it only at integration leaves the same hole for the next change to fall into." },
{ t: "rtl-flow", d: 3, q: "Why is module-level simulation preferred to top-level for everyday work?", o: ["A module-level failure has a small candidate set", "Top-level simulation cannot use assertions", "Module-level tests give better coverage figures", "Top-level simulation requires the full constraint file"], a: 0, why: "The simulation is also fast enough to run on every change. Fast, narrow tests are what you can afford to run continuously. Top-level runs still matter, but as an integration check rather than a debugging tool." },
{ t: "rtl-flow", d: 2, q: "What is the point of a clean interface specification before implementation?", o: ["Modules can be developed and unit-tested in parallel and still connect", "It satisfies all of the project's own internal documentation requirements", "It allows the tool to generate the interconnect", "It fixes the timing budget for each module"], a: 0, why: "Agreeing the signals and their protocol first is what lets two people work independently. It also forces the data rates and handshakes to be decided while they are still cheap to change." },
{ t: "rtl-flow", d: 2, q: "Why is an integrated logic analyser both useful and risky?", o: ["It captures internal signals but consumes fabric and can change timing", "It only works when the design already meets timing", "It requires the whole design to be re-synthesised for every single probe", "It cannot capture signals inside a block RAM"], a: 0, why: "The instrument is part of the design, so adding it shifts placement and eats block RAM. A design that only works with the analyser instrumented is telling you something." },
{ t: "rtl-flow", d: 3, q: "What should you do first when a path fails timing?", o: ["Look at the path itself before changing anything", "Add pipeline stages more or less everywhere", "Re-run the build with a different seed", "Lower the clock frequency in the constraint file"], a: 0, why: "Is it really needed, is it wrongly constrained, and is there too much logic between registers? Most timing failures are one of those three, and each has a different fix. Re-running with a new seed until it passes leaves a design that fails again on the next edit." },
{ t: "rtl-flow", d: 2, q: "What does a nightly regression give you that a pre-release run does not?", o: ["The break is attributed to a small set of changes", "A more thorough set of tests than a manual run", "Coverage numbers for every module in the design", "Confidence that the design meets its timing"], a: 0, why: "Yesterday's changes are a short list; six weeks of changes are not. The value is in narrowing the search, which is why frequency matters more than thoroughness." },
{ t: "rtl-flow", d: 2, q: "Why review the timing report rather than just the pass or fail line?", o: ["The margin and which paths are marginal tell you how fragile the build is", "The report contains the resource utilisation figures", "The tool only ever reports any of the failures down in the detailed section", "The summary line does not include hold violations"], a: 0, why: "A build that passes by ten picoseconds will fail on the next unrelated edit. Knowing where the margin is thin is what lets you fix it deliberately rather than repeatedly." },
{ t: "rtl-flow", d: 2, q: "What is the practical benefit of keeping the constraint file under review?", o: ["It is the only thing deciding what the timing report checks", "It determines the overall resource usage of the entire design", "It is regenerated automatically on every build", "It cannot be validated by any other means"], a: 0, why: "An error in the constraints makes a clean report meaningless, and nothing else in the flow will catch it. It deserves the same scrutiny as the RTL it constrains." },

]);
