BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// ------------------------------------------------------------- emb-c-decl
{ t: "emb-c-decl", d: 1, q: "Where do you start when reading a C declaration?", o: ["At the leftmost type keyword", "At the identifier, then right when you can and left when you must", "At the semicolon and work backwards", "At the outermost parenthesis"], a: 1, why: "<p>You have to go left sometimes because <code>[]</code> and <code>()</code> bind tighter than <code>*</code>, so they apply first unless parentheses override it.</p><p>That is exactly what the parentheses in <code>char *(*fp[3])(int)</code> are doing: without them the brackets and the parameter list would both bind before the star.</p>" },
{ t: "emb-c-decl", d: 2, q: "What is <code>char *(*fp[3])(int);</code>?", o: ["A function returning an array", "An array of 3 pointers to functions taking an int and returning char *", "A pointer to an array of 3 functions", "An array of 3 char pointers"], a: 1, why: "<p>Right-left from the name: fp, array of 3, pointers to, functions taking an int, returning a pointer to char.</p><p>Arrays of functions are illegal in C, which is why the pointer level is not optional here.</p>" },
{ t: "emb-c-decl", d: 2, q: "What does <code>uint8_t (*rows)[16];</code> declare?", o: ["An array of 16 pointers", "A pointer to an array of 16 bytes, so incrementing it moves 16 bytes", "A 2D array", "A pointer to a pointer"], a: 1, why: "<p>The parentheses are load-bearing. Remove them and <code>uint8_t *rows[16]</code> is an array of 16 pointers, a different object with a different size and different arithmetic.</p><p>This is the type you need to pass a 2D array, because the row width has to be in the type for the compiler to compute offsets.</p>" },
{ t: "emb-c-decl", d: 2, q: "In <code>char * const p;</code>, what may you not do?", o: ["Read *p", "Assign to p", "Assign to *p", "Take &amp;p"], a: 1, why: "<p>const applies to whatever is immediately to its left, or to the right if there is nothing there. Here that is the pointer itself, so the pointer cannot be reseated but the target can be written.</p><p>Writing <code>char const *p</code> rather than <code>const char *p</code> makes the rule exceptionless, which is why some codebases insist on it.</p>" },
{ t: "emb-c-decl", d: 2, q: "What does <code>int* a, b;</code> declare?", o: ["Two pointers to int", "a as a pointer to int and b as a plain int", "Two ints", "A syntax error"], a: 1, why: "<p>The star is part of the declarator for <code>a</code>, not part of a type shared by the line, and the spacing misleads every time.</p><p>One declaration per line removes the problem entirely, which is why coding standards require it.</p>" },
{ t: "emb-c-decl", d: 2, q: "What is the vector table's type on a Cortex-M?", o: ["uint32_t table[48]", "void (*table[48])(void)", "void *table[48]", "void (*table)(void)[48]"], a: 1, why: "<p>An array of pointers to functions taking and returning nothing. In practice it is usually written with a typedef, as <code>typedef void (*isr_fn)(void);</code> followed by <code>isr_fn table[48];</code>.</p><p>The first entry is the initial stack pointer rather than a function, which is why some vendor headers declare it as a union or use a cast.</p>" },
{ t: "emb-c-decl", d: 3, q: "Why is a typedef that hides a pointer risky?", o: ["It cannot be forward declared", "const on a parameter of that type applies to the pointer rather than to what it points at", "It breaks sizeof", "It prevents inlining"], a: 1, why: "<p>Given <code>typedef struct dev_s *handle_t;</code>, a parameter declared <code>const handle_t h</code> means a const pointer to a mutable device, which is almost never what the author meant.</p><p>It is worth doing only when the type is genuinely opaque and callers never dereference it.</p>" },
{ t: "emb-c-decl", d: 3, q: "How do you check a declaration you are unsure about?", o: ["Read it aloud", "Write it as a typedef and let the compiler diagnose the assignment", "Compile with -Wall", "Look it up in the standard"], a: 1, why: "<p>Declaring the typedef and then assigning your function or object to it gives a precise error if the type is wrong, which is faster and more reliable than arguing with yourself about precedence.</p>" },
{ t: "emb-c-decl", d: 3, q: "Why is <code>char *fp[3](int);</code> illegal?", o: ["Too many operators", "It declares an array of functions, which C does not allow", "The return type is wrong", "Arrays cannot hold pointers"], a: 1, why: "<p>You can have an array of pointers to functions, and a function returning a pointer, but not an array of functions, because functions have no size to index by.</p><p>Adding the parentheses to make it <code>char *(*fp[3])(int)</code> inserts the pointer level and makes it legal.</p>" },
{ t: "emb-c-decl", d: 3, q: "What is <code>volatile uint32_t * const REG;</code>?", o: ["A volatile pointer to a constant register", "A constant pointer to a volatile register: the address never changes, the contents do", "A read-only register", "An invalid combination"], a: 1, why: "<p>Which is exactly what a memory-mapped peripheral pointer should be. The const stops the pointer being reseated, and the volatile stops the compiler caching the value it read last time.</p>" },

// ----------------------------------------------------------- emb-c-arrays
{ t: "emb-c-arrays", d: 1, q: "What is array decay?", o: ["An array losing its contents", "An array name converting to a pointer to its first element in most expressions", "An array being freed", "A compiler optimisation"], a: 1, why: "<p>It is a rule about expressions rather than about the object, which is the whole reason arrays and pointers are not the same thing.</p><p>The three exceptions are <code>sizeof</code>, taking the address with <code>&amp;</code>, and initialising a char array from a string literal.</p>" },
{ t: "emb-c-arrays", d: 2, q: "What is the type of <code>&amp;arr</code> where <code>arr</code> is <code>int arr[10]</code>?", o: ["int **", "int (*)[10], a pointer to an array of 10 ints", "int *", "int []"], a: 1, why: "<p>Which means <code>&amp;arr + 1</code> advances 40 bytes while <code>arr + 1</code> advances 4. Both are valid and they mean different things.</p><p>This is one of the three places where decay does not happen.</p>" },
{ t: "emb-c-arrays", d: 2, q: "A file defines <code>char msg[] = \"hello\";</code> and another declares <code>extern char *msg;</code>. What happens?", o: ["A compile error", "It links cleanly and the code loads 'hell' as an address", "A linker error", "It works correctly"], a: 1, why: "<p>The linker matches names, not types, and C has no mangling. The declaring file emits a pointer load, so 0x68656C6C becomes the address.</p><p>The fix is a single shared header included by both files, so the compiler checks the declaration against the definition.</p>" },
{ t: "emb-c-arrays", d: 2, q: "In <code>void f(char buf[64])</code>, what does <code>sizeof buf</code> give?", o: ["64", "The size of a pointer", "1", "A compile error"], a: 1, why: "<p>Array parameters do not exist in C. Any parameter declared as an array is adjusted to a pointer, so the 64 is documentation and nothing checks it.</p><p>This is why a function that takes a buffer must also take its length: there is no other mechanism in the language.</p>" },
{ t: "emb-c-arrays", d: 2, q: "How do you pass <code>uint8_t grid[8][16]</code> to a function?", o: ["uint8_t **g", "uint8_t (*g)[16], or equivalently uint8_t g[][16]", "uint8_t *g[16]", "uint8_t *g"], a: 1, why: "<p>The row width must be in the type, because that is what the compiler uses to compute the offset of <code>g[i][j]</code>.</p><p><code>uint8_t **</code> would be an array of pointers, a completely different layout that happens to share the indexing syntax.</p>" },
{ t: "emb-c-arrays", d: 2, q: "What is the difference between <code>char *p = \"abc\";</code> and <code>char a[] = \"abc\";</code>?", o: ["Nothing", "p points into read-only storage; a is a writable RAM array initialised from the literal", "a is const", "p is longer"], a: 1, why: "<p>Writing through <code>p</code> is undefined and on a microcontroller usually a fault, because the literal lives in flash.</p><p>The array version costs 4 bytes of RAM and a copy at startup, and that is exactly the price of being writable.</p>" },
{ t: "emb-c-arrays", d: 3, q: "Which is NOT one of the three places an array fails to decay?", o: ["sizeof arr", "&amp;arr", "Initialising char s[] from a string literal", "Passing arr to a function"], a: 1, why: "<p>Passing to a function is the ordinary case where decay does happen, which is precisely why the parameter becomes a pointer and the bound is lost.</p>" },
{ t: "emb-c-arrays", d: 3, q: "What does <code>void f(char buf[static 64])</code> mean in C99?", o: ["The buffer is static storage", "The caller promises at least 64 elements, and the compiler may warn if it can see otherwise", "The size is fixed at 64", "It is a syntax error"], a: 1, why: "<p>It is documentation the compiler can sometimes check, and it may let it assume the pointer is non-null.</p><p>It does not make <code>sizeof</code> work, so the honest version still takes an explicit length.</p>" },
{ t: "emb-c-arrays", d: 3, q: "Why does <code>memset(buf, 0, sizeof buf)</code> inside a function taking <code>char buf[64]</code> zero only a few bytes?", o: ["memset is broken", "buf is a pointer, so sizeof gives the pointer size", "The buffer is const", "sizeof needs parentheses"], a: 1, why: "<p>Four bytes on a 32-bit target rather than 64. The code is silently wrong and nothing warns unless <code>-Wsizeof-pointer-memaccess</code> catches it.</p><p>Pass the length and use it.</p>" },
{ t: "emb-c-arrays", d: 3, q: "Why is 'an array is just a pointer' a persistent myth?", o: ["It was true in K&amp;R C", "They behave identically in the common case of passing to a function, which is most of what people see", "Compilers used to implement them the same", "It is true"], a: 1, why: "<p>Decay makes them interchangeable in most expressions, so the difference only surfaces at <code>sizeof</code>, at <code>&amp;</code>, and across translation units, where the mismatch produces no diagnostic at all.</p>" },

// ---------------------------------------------------------- emb-c-linkage
{ t: "emb-c-linkage", d: 1, q: "What is the difference between a declaration and a definition?", o: ["Nothing", "A declaration introduces a name and type; a definition also allocates storage or provides the body", "A definition is in the header", "A declaration must be extern"], a: 1, why: "<p>You may declare a thing many times and define it once. Every 'multiple definition' error is a definition that ended up in a header or in two source files.</p>" },
{ t: "emb-c-linkage", d: 2, q: "What are the two unrelated meanings of <code>static</code>?", o: ["Constant and global", "Internal linkage at file scope, and static storage duration inside a function", "Read-only and cached", "Compile-time and run-time"], a: 1, why: "<p>The file-scope meaning is worth using liberally: it shrinks the surface other code can reach, lets the compiler inline and discard aggressively, and stops two files sharing a name by accident.</p><p>The function-local meaning makes the function non-reentrant and prevents a second instance, so it wants care.</p>" },
{ t: "emb-c-linkage", d: 2, q: "Why did two .c files each containing <code>int count;</code> once link without complaint?", o: ["The linker deduplicates", "Both were tentative definitions merged into a common symbol, before -fno-common became the GCC 10 default", "One was discarded as unused", "It was always an error"], a: 1, why: "<p>Two modules that each believed they owned a variable silently shared it, which is a genuinely nasty class of bug.</p><p>A legacy project that only builds with <code>-fcommon</code> is flagging a real defect rather than a compatibility quirk.</p>" },
{ t: "emb-c-linkage", d: 2, q: "Why can a plain <code>inline</code> function in a C header produce 'undefined reference'?", o: ["inline is not valid C", "In C99 a plain inline definition is not an external definition, so a call the compiler declines to inline has nothing to link against", "The header was not included", "It needs -O2"], a: 1, why: "<p>Which is maddening because the function is visibly right there in the header.</p><p><code>static inline</code> is the firmware answer: each translation unit gets a copy and unused ones are discarded. The alternative is an <code>extern inline</code> declaration in exactly one .c file.</p>" },
{ t: "emb-c-linkage", d: 2, q: "What does the C linker match on?", o: ["Names and types", "Names only, because C has no name mangling", "Mangled signatures", "Names and sizes"], a: 1, why: "<p>So a function defined taking an int and declared taking a long links happily, as does a uint16_t defined and a uint32_t declared.</p><p>Everything that protects you comes from a shared header included on both sides. Nothing else checks.</p>" },
{ t: "emb-c-linkage", d: 2, q: "Why include a module's own header in its .c file?", o: ["For the include guards", "So the compiler checks the declarations against the definitions", "To get the standard library", "It is not necessary"], a: 1, why: "<p>It is the only point at which anything compares the two, since the linker will not. Skipping it is how a signature drifts out of step with its declaration and nobody finds out until runtime.</p>" },
{ t: "emb-c-linkage", d: 3, q: "What is the test that a header is self-contained?", o: ["It compiles in the project", "A .c file containing nothing but that one include compiles", "It has include guards", "It has no other includes"], a: 1, why: "<p>A header that only works because of what happened to be included before it is a maintenance trap, since reordering includes elsewhere breaks it.</p><p>Some projects automate the check by generating exactly that one-line file per header in CI.</p>" },
{ t: "emb-c-linkage", d: 3, q: "What does 'relocation truncated to fit' mean?", o: ["The binary is too large", "The linker script placed caller and callee too far apart for the branch encoding", "A symbol is undefined", "The stack overflowed"], a: 1, why: "<p>A branch instruction encodes a limited signed offset, so a call from flash to a function placed in a distant region cannot be encoded directly.</p><p>The fixes are moving the sections closer, using a long-call veneer, or checking that the memory regions in the linker script are what you think they are.</p>" },
{ t: "emb-c-linkage", d: 3, q: "Why prefer a forward declaration to an include in a header?", o: ["It is shorter", "It cuts rebuild times and breaks dependency cycles, where you only need the pointer type", "Includes are unreliable", "It avoids include guards"], a: 1, why: "<p><code>struct dev_s;</code> is enough to declare functions taking <code>struct dev_s *</code>. Every header that includes another propagates a rebuild to everything downstream.</p>" },
{ t: "emb-c-linkage", d: 3, q: "Where should the definition of a module's global live?", o: ["In the header, so everyone sees it", "In exactly one .c file, with an extern declaration in the header", "In every file that uses it", "In a separate globals.c"], a: 1, why: "<p>A definition in a header is duplicated into every translation unit that includes it, which is a multiple-definition error or, worse, silently merged under <code>-fcommon</code>.</p>" },

// ------------------------------------------------------------- emb-c-expr
{ t: "emb-c-expr", d: 1, q: "What does <code>if (x &amp; MASK == 0)</code> test?", o: ["Whether the masked bits are zero", "x &amp; (MASK == 0), which is x &amp; 0 and always false", "Whether x equals MASK", "It is a syntax error"], a: 1, why: "<p><code>==</code> binds tighter than <code>&amp;</code>. Ritchie later said the precedence of the bitwise operators was a mistake he regretted, which is why compilers warn about this exact shape.</p><p>Parenthesise anything mixing bitwise with comparison and the category disappears.</p>" },
{ t: "emb-c-expr", d: 2, q: "What does <code>a &lt;&lt; 2 + 3</code> evaluate?", o: ["(a &lt;&lt; 2) + 3", "a &lt;&lt; 5, because + binds tighter than the shift", "A syntax error", "a &lt;&lt; 2, with 3 discarded"], a: 1, why: "<p>Shift is lower precedence than addition, which surprises nearly everyone who has written a register field expression.</p><p>The same rule that fixes the bitwise-versus-comparison trap fixes this one: bracket anything mixing shift with arithmetic.</p>" },
{ t: "emb-c-expr", d: 2, q: "Why is <code>a[i] = i++;</code> undefined rather than unspecified?", o: ["It is only unspecified", "Two unsequenced accesses to i with at least one modification makes the whole program undefined, not just the order", "i is uninitialised", "It is well defined"], a: 1, why: "<p>The distinction matters. Unspecified would mean one of several defined outcomes; undefined means the compiler may do anything, including deleting surrounding code it proves unreachable.</p>" },
{ t: "emb-c-expr", d: 2, q: "Which operators guarantee left-to-right sequencing?", o: ["All binary operators", "&amp;&amp;, ||, ?: and the comma operator", "Only assignment", "None"], a: 1, why: "<p>This is why <code>p != NULL &amp;&amp; p-&gt;ready</code> is safe. Write a single <code>&amp;</code> by mistake and both sides evaluate, so the null guard stops guarding.</p><p>That is a real bug pattern, not a theoretical one.</p>" },
{ t: "emb-c-expr", d: 2, q: "In <code>f(get(), put())</code>, which runs first?", o: ["get, always", "Unspecified: compilers differ, and the same compiler differs between optimisation levels", "put, always", "They run in parallel"], a: 1, why: "<p>Any expression whose meaning depends on argument evaluation order is a bug waiting for the next toolchain upgrade.</p><p>If both also modify the same object, it is undefined rather than merely unspecified.</p>" },
{ t: "emb-c-expr", d: 2, q: "How does <code>a---b</code> lex?", o: ["a - (--b)", "(a--) - b, because the lexer takes the longest possible token", "A syntax error", "a - (-(-b))"], a: 1, why: "<p>C tokenises greedily without regard for whether the result parses. The same greed makes <code>x = y/*p;</code> start a comment that swallows the rest of the file.</p><p>That one is the dangerous case, because the error surfaces far away and looks like something else.</p>" },
{ t: "emb-c-expr", d: 2, q: "Which <code>if</code> does an <code>else</code> attach to?", o: ["The one at the same indentation", "The nearest unmatched if, regardless of indentation", "The outermost if", "Whichever the compiler chooses"], a: 1, why: "<p>Braces on every conditional body remove the problem, which is why MISRA requires them.</p><p>It is the same class of defect as Apple's goto fail: the indentation said one thing and the compiler read another.</p>" },
{ t: "emb-c-expr", d: 3, q: "Is <code>x</code> incremented by <code>sizeof(x++)</code>?", o: ["Yes", "No: sizeof does not evaluate its operand, except for a variable-length array", "Only at -O0", "It is undefined"], a: 1, why: "<p>The operand is used only for its type, so any side effect in it never happens. The VLA exception exists because the size genuinely has to be computed at runtime.</p>" },
{ t: "emb-c-expr", d: 3, q: "Why must <code>getchar</code>'s result be stored in an <code>int</code>?", o: ["Performance", "EOF does not fit in a char, so a char cannot distinguish it from a valid byte", "It returns a pointer", "For alignment"], a: 1, why: "<p>EOF is typically -1, and on a platform with unsigned char it can never compare equal after truncation, so the loop never terminates. On signed char, the byte 0xFF is indistinguishable from EOF.</p>" },
{ t: "emb-c-expr", d: 3, q: "How should intentional switch fallthrough be marked?", o: ["It should never be used", "With __attribute__((fallthrough)), the C23 [[fallthrough]], or a comment -Wimplicit-fallthrough recognises", "With a blank line", "With a break"], a: 1, why: "<p>Deliberate fallthrough is legitimate and occasionally the clearest way to write something. Marking it is what makes the accidental ones visible to both the compiler and the reviewer.</p>" },

// ------------------------------------------------------------- emb-c-qual
{ t: "emb-c-qual", d: 1, q: "What does <code>const</code> on a pointer parameter promise?", o: ["The object never changes", "You will not modify it through this name; another path still can", "It lives in flash", "It is reentrant"], a: 1, why: "<p>It constrains the access path, not the object. So it does not let the compiler cache the value across a function call, and it is not a substitute for <code>volatile</code>.</p>" },
{ t: "emb-c-qual", d: 2, q: "Why does <code>static const uint8_t table[256]</code> matter on a small part?", o: ["It indexes faster", "It goes in flash, instead of costing 256 bytes of RAM plus an initialiser and a startup copy", "It prevents aliasing", "It enables inlining"], a: 1, why: "<p>Without the const the table is a mutable object, so it needs RAM, the flash still holds the initial values, and startup copies one to the other.</p><p>On a part with 20 kB of RAM, a handful of lookup tables missing their const is a meaningful fraction of the budget.</p>" },
{ t: "emb-c-qual", d: 2, q: "Is <code>const volatile uint32_t STATUS;</code> a contradiction?", o: ["Yes", "No: read-only to your code, changed by the hardware, which describes a status register exactly", "Only for pointers", "volatile is redundant there"], a: 1, why: "<p>They constrain different parties. The const stops your code writing it; the volatile stops the compiler assuming the value it read last time is still valid.</p>" },
{ t: "emb-c-qual", d: 2, q: "What does <code>restrict</code> promise, and what checks it?", o: ["Non-null, checked at runtime", "That the object is not reached through any other pointer, and nothing checks it", "Alignment, checked by the linker", "Constness, checked by the compiler"], a: 1, why: "<p>If you lie, the behaviour is undefined and the symptom is a wrong answer rather than a crash, which is the worse failure mode.</p><p>It is the entire difference between <code>memcpy</code>, which declares both pointers restrict, and <code>memmove</code>, which does not.</p>" },
{ t: "emb-c-qual", d: 2, q: "What does <code>restrict</code> actually buy the optimiser?", o: ["Smaller code", "It need not reload from the source each iteration in case the write through the destination changed it", "Alignment assumptions", "Automatic vectorisation only"], a: 1, why: "<p>Values stay in registers and the loop can be unrolled or vectorised. On a Cortex-M4 filter loop the difference is often twenty to forty per cent, and occasionally nothing.</p><p>Which is why it is worth measuring rather than assuming.</p>" },
{ t: "emb-c-qual", d: 2, q: "When is <code>restrict</code> a trap for your own users?", o: ["Always", "On an API where a caller might reasonably pass the same buffer for input and output", "On const pointers", "In header files"], a: 1, why: "<p>An in-place filter declaring both pointers restrict looks correct and quietly produces wrong answers when someone does the obvious thing.</p><p>If in-place use is plausible, either do not use restrict or document that it is forbidden.</p>" },
{ t: "emb-c-qual", d: 3, q: "When is casting away <code>const</code> defensible?", o: ["Never", "When you know the object is not actually const and the qualifier came from an interface you do not control", "When performance requires it", "In driver code"], a: 1, why: "<p>If the object really was defined const it may be in flash or a read-only section, and the write is undefined: a fault or silently discarded.</p><p>Anywhere else it is a design problem being papered over, and it deserves a comment saying why.</p>" },
{ t: "emb-c-qual", d: 3, q: "Does <code>const int n = 8;</code> let you write <code>int a[n];</code> as a fixed array?", o: ["Yes", "No: that is a variable-length array, because const in C does not create a compile-time constant", "Only at file scope", "Only with -O2"], a: 1, why: "<p>This is a real difference from C++. For a genuine compile-time constant use an enum or a macro, which is why firmware headers still use both.</p>" },
{ t: "emb-c-qual", d: 3, q: "What does <code>register</code> still do in modern C?", o: ["Forces a register allocation", "Makes it illegal to take the variable's address; the allocation hint is ignored", "Nothing at all", "Disables optimisation"], a: 1, why: "<p>Every modern compiler allocates registers far better than the hint could, so the qualifier survives only for that one side effect, which is occasionally useful and never worth writing.</p>" },
{ t: "emb-c-qual", d: 3, q: "Why is <code>const</code> not a substitute for <code>volatile</code> on a hardware register?", o: ["It is a substitute", "const only says you will not write it; the compiler may still cache the value it read", "const implies volatile", "Registers are always volatile"], a: 1, why: "<p>Reading the same const-qualified location twice may compile to a single load, which for a status register that the hardware updates means an infinite loop.</p><p>The correct type is <code>const volatile</code>.</p>" },

// -------------------------------------------------------------- emb-c-lib
{ t: "emb-c-lib", d: 1, q: "What is wrong with <code>strncpy</code>?", o: ["It is slow", "It does not guarantee a terminator, and it pads the whole destination with zeros", "It allocates", "It is not standard"], a: 1, why: "<p>If the source is n characters or longer, the destination is unterminated and every later <code>strlen</code> walks off the end.</p><p>The padding is the other surprise: copying 3 bytes into a 512-byte buffer writes all 512.</p>" },
{ t: "emb-c-lib", d: 2, q: "What does <code>snprintf</code> return?", o: ["Bytes written", "The length it wanted to write, which is how you detect truncation", "Zero on success", "Remaining space"], a: 1, why: "<p>Comparing the return against the buffer size tells you it was truncated. Using it as the number of bytes written, for instance to advance an offset in a loop, walks past the end of the buffer.</p>" },
{ t: "emb-c-lib", d: 2, q: "What is <code>strncat</code>'s size argument?", o: ["The size of the destination buffer", "The maximum number of characters to append, not the buffer size", "The length of the source", "The offset to append at"], a: 1, why: "<p>Almost everyone reads it as the buffer size, which makes the call an overflow whenever the destination already holds data.</p><p>Tracking the offset yourself and using <code>snprintf</code> is both shorter and correct.</p>" },
{ t: "emb-c-lib", d: 2, q: "Why avoid <code>atoi</code> for parsing input?", o: ["It is slow", "It returns 0 for both \"abc\" and \"0\", with no way to distinguish them and no overflow report", "It is not reentrant", "It allocates"], a: 1, why: "<p><code>strtol</code> gives you an end pointer and sets errno to ERANGE on overflow.</p><p>Checking that the end pointer moved is what separates 'nothing parsed' from 'a zero parsed', and it is the check people omit.</p>" },
{ t: "emb-c-lib", d: 2, q: "Why is <code>strtok</code> a hazard in an RTOS application?", o: ["It is slow", "It keeps static state, so it is not reentrant, cannot be nested, and modifies the string", "It allocates", "It is not standard"], a: 1, why: "<p>Two tasks calling it interleave and both get nonsense. <code>strtok_r</code> takes the state explicitly and fixes that, though the string is still modified in place.</p>" },
{ t: "emb-c-lib", d: 2, q: "When must you use <code>memmove</code> rather than <code>memcpy</code>?", o: ["For large blocks", "When the regions overlap, which memcpy declares undefined", "When the pointers are const", "On unaligned data"], a: 1, why: "<p><code>memcpy</code> declares both pointers restrict. The trap is that it usually appears to work on small sizes and stops working when someone grows the buffer and the implementation switches to a word-wise or backwards path.</p>" },
{ t: "emb-c-lib", d: 2, q: "What is the usual largest flash saving available on a vendor project?", o: ["Turning off debug symbols", "Switching to newlib-nano and only pulling in printf float support where needed", "Enabling -Os", "Removing comments"], a: 1, why: "<p>Full printf with float support can be twenty-five kilobytes and may drag in soft-float too, and most vendor projects link it by default.</p><p>It is a linker flag rather than a code change, which is what makes it the cheapest win.</p>" },
{ t: "emb-c-lib", d: 3, q: "What is the real objection to <code>malloc</code> in long-running firmware?", o: ["Speed", "Fragmentation: a request that fits in the total free space fails because no single block is big enough", "Code size", "It is not standard"], a: 1, why: "<p>The failure arrives after weeks in the field rather than in testing, which is what makes it expensive.</p><p>Fixed-size pools remove it by construction, which is why they are the usual answer when runtime allocation is genuinely needed.</p>" },
{ t: "emb-c-lib", d: 3, q: "Why is <code>rand</code> unacceptable for a nonce or a session key?", o: ["It is too slow", "It is a weak PRNG with a shared seed, so its output is predictable", "It is not reentrant", "It returns only 15 bits"], a: 1, why: "<p>Predictable nonces and keys defeat the construction entirely, and seeding from a serial number or boot time has left real fleets with only a few thousand possible values.</p><p>Use the hardware TRNG.</p>" },
{ t: "emb-c-lib", d: 3, q: "Which of these keeps hidden state between calls?", o: ["memcpy", "strtok, rand, localtime and strerror", "strlen", "snprintf"], a: 1, why: "<p>All of them are reentrancy hazards, and errno itself is one too unless the library was built thread-aware.</p><p>Calling any of them from both a task and an ISR will eventually interleave.</p>" },

// ------------------------------------------------------- emb-c-optimiser
{ t: "emb-c-optimiser", d: 1, q: "What counts as observable behaviour under the as-if rule?", o: ["Everything the program does", "Volatile accesses, file writes and input/output interactions", "Memory contents and timing", "The return value only"], a: 1, why: "<p>Execution time is not on the list, memory contents are not, and the order of two non-volatile writes is not.</p><p>Which is why an empty delay loop may vanish and why a memset that clears a key buffer may be removed if nothing reads it afterwards.</p>" },
{ t: "emb-c-optimiser", d: 2, q: "Why can the compiler delete a null check placed after a dereference?", o: ["A compiler bug", "Dereferencing null is undefined, so a conforming program cannot reach that point with null and the test is provably false", "Only at -O3", "The optimiser is too aggressive"], a: 1, why: "<p>The practical lesson is that a check placed after the thing it was meant to guard is not a weakened check, it is no check at all.</p><p>The same reasoning removes signed overflow tests written as <code>if (a + b &lt; a)</code>.</p>" },
{ t: "emb-c-optimiser", d: 2, q: "What is the correct way to reinterpret a uint32_t's bits as a float?", o: ["*(float *)&amp;u", "memcpy into a float, which every compiler turns into a single move", "A cast to float", "A pointer union cast"], a: 1, why: "<p>The pointer cast violates strict aliasing: it works at -O0 and may be reordered or elided at -O2.</p><p>A union is also defined in C, though not in C++. The char types are exempt from aliasing rules, which is why byte-wise serialisation code is safe.</p>" },
{ t: "emb-c-optimiser", d: 2, q: "Why might <code>memset(key, 0, sizeof key)</code> be removed?", o: ["It never is", "Memory contents are not observable, so if nothing reads key afterwards the write is dead", "key is const", "sizeof is wrong"], a: 1, why: "<p>It is a real security defect with a name, and the fixes are <code>explicit_bzero</code>, <code>memset_s</code>, or writing through a volatile pointer.</p>" },
{ t: "emb-c-optimiser", d: 2, q: "What does <code>volatile</code> guarantee?", o: ["Atomicity", "Every access in the source happens in the machine code, in source order relative to other volatile accesses", "A memory barrier", "Thread safety"], a: 1, why: "<p>That is all it guarantees. It does not order volatile against non-volatile accesses and does not emit a barrier, so on a part with a write buffer you may still need a DMB.</p><p>And <code>count++</code> on a volatile is still read, modify, write, so an interrupt in the middle still loses an update.</p>" },
{ t: "emb-c-optimiser", d: 2, q: "A bug appears only at -O2. What are the four usual causes?", o: ["Compiler bugs", "Missing volatile, exploited undefined behaviour, a deleted timing dependency, or reliance on memory that happened to be zero", "Stack overflow", "Linker script errors"], a: 1, why: "<p>The diagnostic order is UBSan on the host if the code can be built there, then <code>-fno-strict-aliasing</code>.</p><p>If that last one fixes it you have located a type-punning bug rather than found a solution.</p>" },
{ t: "emb-c-optimiser", d: 3, q: "Which types are exempt from the strict aliasing rules?", o: ["All integer types", "char, unsigned char and int8_t, which may alias anything", "Only void *", "None"], a: 1, why: "<p>This is precisely what makes byte-wise serialisation and packet parsing legal: you may always look at any object through a character pointer.</p><p>The reverse does not hold, so viewing a byte buffer as a struct is still an aliasing problem.</p>" },
{ t: "emb-c-optimiser", d: 3, q: "Why is <code>-fno-strict-aliasing</code> a diagnosis rather than a fix?", o: ["It is a fix", "It suppresses the optimisation that exposed a type-punning bug that is still in the code", "It slows the program", "It only works at -O1"], a: 1, why: "<p>The undefined behaviour remains, so a different compiler, a different version, or a nearby edit can bring the symptom back.</p><p>Once it tells you where to look, convert the cast to a memcpy, which every compiler emits as a single move.</p>" },
{ t: "emb-c-optimiser", d: 3, q: "Why can a hardware polling loop hang when <code>volatile</code> is missing?", o: ["The register is unreadable", "The compiler hoists the read out of the loop, so the same value is tested forever", "The optimiser inlines it", "Interrupts are disabled"], a: 1, why: "<p>Nothing in the C abstract machine can change that location, so re-reading it is redundant work the as-if rule permits removing.</p><p>Reading the disassembly and counting the loads settles it in a minute.</p>" },
{ t: "emb-c-optimiser", d: 3, q: "What is the fastest way to settle an argument about what the compiler did?", o: ["Read the standard", "Read the generated assembly, with -S -fverbose-asm or objdump on the ELF", "Try another compiler", "Add print statements"], a: 1, why: "<p>Two things are worth checking directly: whether your register accesses are there and how many, which catches a missing volatile immediately, and whether a barrier or bit-band write survived.</p><p>Reading a hundred lines of Cortex-M assembly is a much smaller skill than it looks.</p>" }

]);
