// A second pass over every Robotics lesson: ten more questions each.
//
// Topic tags are lesson ids, so topicLesson() resolves them by the byId
// fallback and no TOPIC_LESSON entry is needed.
//
// Correct options are kept short and the reasoning put in `why`, which the
// page shows the moment you answer. A distractor is the longest option in
// about three questions out of four, which is chance for four options.
BANKS["Robotics"] = BANKS["Robotics"].concat([

// ---------------------------------------------------------------- rob-ros
{ t: "rob-ros", d: 1, q: "What does a ROS 2 topic provide?", o: ["Anonymous publish and subscribe between nodes", "A request and response call with a guaranteed reply", "A long-running task that reports progress as it goes", "A shared parameter store readable by every node"], a: 0, why: "Publishers and subscribers never learn about each other, which is what makes nodes replaceable. Services are the request-response pattern and actions the long-running one." },
{ t: "rob-ros", d: 2, q: "When should a service be used rather than a topic?", o: ["For a short call where you need the answer", "For streaming sensor data at a high rate", "For a task that takes minutes to complete", "For any communication between two machines"], a: 0, why: "A service blocks until it returns, so it suits a quick query or a configuration change. Anything long-running belongs in an action, which can be cancelled and reports feedback." },
{ t: "rob-ros", d: 2, q: "What does a QoS reliability setting of best effort mean?", o: ["Messages may be dropped rather than retransmitted", "Messages are delivered at most once to each subscriber", "Delivery is retried until the subscriber acknowledges it", "The publisher waits for every subscriber to be ready"], a: 0, why: "It suits high-rate sensor data where a fresh sample beats a retransmitted stale one. Reliable is the right choice for commands and configuration." },
{ t: "rob-ros", d: 3, q: "Why might a subscriber receive nothing despite a publisher being active?", o: ["Their QoS profiles are incompatible", "The two nodes are running in different processes", "The message type has a different field ordering", "The publisher's queue depth is set too small"], a: 0, why: "Reliability, durability and history must be compatible or no connection is formed, and the failure is silent by default. Checking the QoS on both ends is the first thing to do." },
{ t: "rob-ros", d: 2, q: "What does a transform tree describe?", o: ["The relationship between coordinate frames over time", "The hierarchy of nodes in the running system", "The physical joints and links of the robot", "The dependency order in which all the nodes must start"], a: 0, why: "Every sensor reading is in some frame, and the tree is what lets you express one in another. Timestamps matter because the tree changes as the robot moves." },
{ t: "rob-ros", d: 2, q: "Why does a transform lookup need a timestamp?", o: ["The frames move, so the answer depends on when", "The library caches results and needs a key", "Timestamps are used to detect dropped messages", "The lookup would otherwise block indefinitely"], a: 0, why: "Asking where the camera was relative to the base is meaningless without saying when. Using the latest transform for an older measurement is a common and subtle source of error." },
{ t: "rob-ros", d: 2, q: "What does a lifecycle node add?", o: ["Explicit configure, activate and deactivate states", "Automatic restart when the node crashes", "A guarantee that the node runs in real time", "The ability to run the node on a completely different machine"], a: 0, why: "It makes bring-up order controllable, so a node can allocate resources without publishing until the system is ready. That determinism matters a great deal at start-up." },
{ t: "rob-ros", d: 3, q: "Why is a single node with several callbacks not automatically parallel?", o: ["The default executor runs callbacks one at a time", "Callbacks are all serialised by the incoming message queue", "Only one thread is allowed per process", "Parallel callbacks are disabled for safety"], a: 0, why: "A single-threaded executor processes callbacks in turn, so a slow one blocks the rest. A multi-threaded executor with callback groups is what actually gives you concurrency." },
{ t: "rob-ros", d: 2, q: "What does recording a bag give you?", o: ["Replayable data for offline development", "A compressed archive of the node's source", "A snapshot of every parameter's value", "A profile of each node's CPU usage"], a: 0, why: "Most perception and estimation work can be done against recorded data without the robot. It also turns a field failure into something you can debug repeatedly." },
{ t: "rob-ros", d: 2, q: "Why should node parameters be declared rather than read ad hoc?", o: ["Declaration gives types, defaults and validation", "Undeclared parameters cannot be read at all", "It allows the parameters to be changed at run time", "Declared parameters are stored in the bag file"], a: 0, why: "You get a type check, a documented default and a description, which turns a silent misconfiguration into an error at start-up. It is also what makes introspection tools useful." },

// --------------------------------------------------------- rob-kinematics
{ t: "rob-kinematics", d: 1, q: "What does forward kinematics compute?", o: ["End effector pose from the joint angles", "Joint angles needed to reach a desired pose", "The velocity of each joint for a given path", "The torques required to hold a given pose"], a: 0, why: "It is a direct evaluation with one answer, which is why it is the easy direction. The inverse problem may have many solutions or none." },
{ t: "rob-kinematics", d: 2, q: "Why may inverse kinematics have several solutions?", o: ["Different joint configurations reach the same pose", "Floating point rounding is what creates the extra answers", "The end effector pose is over-specified", "The Jacobian is singular at that point"], a: 0, why: "Elbow up and elbow down are the classic pair, and a six-axis arm typically has eight. Choosing between them means adding a criterion such as staying away from joint limits." },
{ t: "rob-kinematics", d: 2, q: "What does a spherical wrist buy you?", o: ["Position and orientation decouple, giving closed form", "A larger workspace for the same link lengths", "Immunity to singularities anywhere in the workspace", "Lower inertia at the end of the kinematic chain"], a: 0, why: "Three axes intersecting at a point lets you solve position from the first three joints and orientation from the last three. Without it you are usually solving numerically." },
{ t: "rob-kinematics", d: 3, q: "What happens near a kinematic singularity?", o: ["Small Cartesian motions demand enormous joint rates", "The arm simply cannot move in any direction whatsoever", "The forward kinematics become undefined", "The joint limits are reached simultaneously"], a: 0, why: "The Jacobian loses rank, so the mapping from joint to Cartesian velocity is not invertible in some direction. The arm lurches or faults on a speed limit." },
{ t: "rob-kinematics", d: 2, q: "What does the manipulability measure tell you?", o: ["How far the current pose is from a singularity", "The maximum payload the arm is able to carry there", "The volume of the reachable workspace", "The stiffness of the arm at that pose"], a: 0, why: "A low value warns of a lurch before the arm gets there, so it can be used as a cost in a planner. It is derived from the Jacobian's singular values." },
{ t: "rob-kinematics", d: 2, q: "What is a redundant manipulator?", o: ["One with more joints than the task needs", "One with two arms working on the same object", "One whose sensors duplicate each other", "One that can reach a pose in two ways"], a: 0, why: "Seven joints for a six-degree-of-freedom task leaves a null space you can use to avoid obstacles or joint limits. The inverse kinematics then has infinitely many solutions, so something must choose." },
{ t: "rob-kinematics", d: 2, q: "What does the Jacobian relate?", o: ["Joint velocities to end effector velocity", "Joint angles to end effector position", "Joint torques to end effector stiffness", "Link masses to the arm's total inertia"], a: 0, why: "It is the derivative of the forward kinematics, so it maps rates. Transposed, it also maps end effector forces to joint torques, which is why it appears in force control." },
{ t: "rob-kinematics", d: 3, q: "Why is a rotation matrix a poor way to store an orientation?", o: ["Nine numbers with six constraints, and drift breaks them", "It cannot represent rotations beyond 180 degrees", "Multiplying two of them together is computationally expensive", "It suffers from gimbal lock like Euler angles"], a: 0, why: "Numerical drift makes it non-orthonormal and it has to be re-orthogonalised. A quaternion needs four numbers and one constraint, which is cheaper to maintain." },
{ t: "rob-kinematics", d: 2, q: "What is gimbal lock?", o: ["Two rotation axes aligning, losing a degree of freedom", "A physical bearing seizing up at any high rotational speed", "A joint reaching its mechanical travel limit", "The wrist axes reaching a singular configuration"], a: 0, why: "It is a property of the three-angle representation, not of the mechanism, and quaternions do not have it. It is why Euler angles are avoided for anything that must pass through vertical." },
{ t: "rob-kinematics", d: 2, q: "Why does negating a quaternion leave the rotation unchanged?", o: ["Both represent the same rotation, from opposite directions", "Quaternion negation is not a defined operation", "The negation only affects the scalar component", "The rotation reverses, but the resulting pose is still identical"], a: 0, why: "The double cover means q and minus q are the same rotation, which is why interpolation must choose the shorter path. Failing to check that gives a robot that takes the long way round." },

// -------------------------------------------------------- rob-locomotion
{ t: "rob-locomotion", d: 1, q: "What makes a differential drive robot non-holonomic?", o: ["It cannot move sideways", "It has fewer wheels than degrees of freedom", "Its wheels can slip under acceleration", "Its motors cannot be driven independently"], a: 0, why: "The constraint is on velocity, not on reachable poses, so it can still reach any pose by manoeuvring. That is precisely why parallel parking needs several moves." },
{ t: "rob-locomotion", d: 2, q: "What does an omnidirectional drive give up?", o: ["Efficiency and traction, for full manoeuvrability", "The ability to rotate on the spot", "Any possibility at all of taking odometry from the wheels", "Precise control of the heading angle"], a: 0, why: "Rollers or a swerve mechanism let you translate in any direction while rotating, at the cost of complexity, slip and lower payload. On rough ground they do poorly." },
{ t: "rob-locomotion", d: 2, q: "What is the zero moment point used for?", o: ["Judging whether a walking robot will tip", "Finding the centre of mass of the robot", "Deciding when to switch the support foot", "Measuring the ground reaction force"], a: 0, why: "If it stays inside the support polygon, the foot does not rotate about its edge and the robot does not fall. It is the standard criterion for dynamic walking." },
{ t: "rob-locomotion", d: 3, q: "What distinguishes a static from a dynamic gait?", o: ["A static gait keeps the centre of mass over the support", "A static gait keeps all feet on the ground", "A dynamic gait always has a flight phase during every stride", "A dynamic gait uses no feedback at all"], a: 0, why: "Stop a static gait at any instant and the robot stands; stop a dynamic one and it falls. Dynamic gaits are faster and need the control loop to be running." },
{ t: "rob-locomotion", d: 2, q: "What is the duty factor of a gait?", o: ["The fraction of the cycle each foot is on the ground", "The ratio of stride length to leg length", "The proportion of torque used against gravity", "The fraction of time the robot is statically stable"], a: 0, why: "Above one half every foot overlaps with another in stance, which allows a static gait. Below one half there is a flight phase, which is a run." },
{ t: "rob-locomotion", d: 2, q: "Why is wheel odometry unreliable on its own?", o: ["Slip accumulates as an unbounded position error", "Encoders lose counts at high rotational speed", "The wheel radius changes with temperature", "Odometry cannot measure heading at all"], a: 0, why: "Every slip is integrated and never corrected, so the estimate drifts without bound. It is excellent over short intervals, which is exactly why it is fused with something absolute." },
{ t: "rob-locomotion", d: 2, q: "What does a suspension do for a wheeled robot's odometry?", o: ["Keeps wheels loaded, reducing slip", "Removes the need to model the wheel radius", "Measures the terrain roughness directly", "Isolates the sensors from vibration only"], a: 0, why: "A wheel that leaves the ground contributes counts with no motion, which is a pure error. Keeping all wheels loaded on uneven ground is as much an odometry decision as a mechanical one." },
{ t: "rob-locomotion", d: 3, q: "Why does a legged robot need a high control bandwidth?", o: ["Balance is an unstable equilibrium needing constant correction", "The legs have very low inertia and move quickly", "Foot contact forces change a great deal faster than a wheel's do", "The gait pattern must be recomputed every cycle"], a: 0, why: "An inverted pendulum diverges on its own, so the loop has to be fast relative to that divergence. A wheeled robot is stable without any control at all." },
{ t: "rob-locomotion", d: 2, q: "What is a capture point?", o: ["Where a foot must land to come to a stop", "The moment when the swing leg touches down", "The point at which the gait becomes unstable", "The centre of pressure under the stance foot"], a: 0, why: "It gives a direct target for the next footstep given the current state, which is why it is used for push recovery. It follows from the linear inverted pendulum model." },
{ t: "rob-locomotion", d: 2, q: "Why is tracked locomotion hard on odometry?", o: ["Turning is inherently a skidding motion", "Tracks stretch and change their effective length", "Track speed cannot be measured accurately", "Tracks cannot be driven independently"], a: 0, why: "A skid steer turns by deliberately slipping, so the wheel-to-ground relationship is not a rolling one. Heading from a gyro is essentially mandatory." },

// -------------------------------------------------------- rob-perception
{ t: "rob-perception", d: 1, q: "How does a stereo camera pair recover depth?", o: ["From the disparity between corresponding points", "From the brightness difference between the images", "From the time light takes to return to each sensor", "From the focus setting at which each point is sharp"], a: 0, why: "Depth is inversely proportional to disparity, scaled by the baseline and focal length. Accuracy therefore falls off as the square of distance." },
{ t: "rob-perception", d: 2, q: "Why does stereo fail on a blank wall?", o: ["There is no texture to match between images", "The wall reflects too much of the projected pattern", "The disparity exceeds the search range", "The wall is outside the calibrated depth range"], a: 0, why: "Matching needs distinguishable features, and a uniform surface offers none. Projecting a random texture is exactly what an active stereo sensor does about it." },
{ t: "rob-perception", d: 2, q: "What limits a time-of-flight camera outdoors?", o: ["Sunlight swamps the returned signal", "The sensor cannot resolve distances beyond a metre", "The modulation frequency aliases in bright light", "Ambient temperature changes the speed of light"], a: 0, why: "The ambient infrared far exceeds the illuminator's return, so the signal to noise ratio collapses. Narrowband filtering and higher illumination power push the limit out but do not remove it." },
{ t: "rob-perception", d: 3, q: "What does lidar measure that a camera does not?", o: ["Range directly, independent of texture and lighting", "Colour information at long distances", "The reflectance spectrum of every surface in the scene", "The velocity of every point in the scene"], a: 0, why: "It is an active range sensor, so it works in the dark and on untextured surfaces. It gives no colour, and most units struggle with glass and very dark matt surfaces." },
{ t: "rob-perception", d: 2, q: "What are camera intrinsics?", o: ["Focal length, principal point and distortion", "The camera's position and orientation in the world", "The exposure and gain settings currently in use", "The mapping between two cameras in a stereo pair"], a: 0, why: "They describe the projection from the camera frame onto the image plane. Extrinsics are the pose, and getting the two confused is a classic calibration mistake." },
{ t: "rob-perception", d: 2, q: "What does a poorly estimated principal point cause?", o: ["A systematic bias in the reconstructed geometry", "A uniform blur across the whole image", "An error in the image's own overall colour balance", "A change in the camera's field of view"], a: 0, why: "It shifts the ray directions, so the error grows with distance from the image centre. It shows up as a bend in what should be a straight reconstruction." },
{ t: "rob-perception", d: 2, q: "Why is a rolling shutter a problem on a moving robot?", o: ["Each row is exposed at a different time", "The exposure time is too long for fast motion", "The sensor cannot be synchronised to the lidar", "The frame rate falls as the robot speeds up"], a: 0, why: "A moving camera distorts the geometry the estimator assumes, so straight lines bend and features shift. A global shutter costs more and removes the problem entirely." },
{ t: "rob-perception", d: 3, q: "Why is time synchronisation between camera and lidar critical?", o: ["Fusing them assumes both saw the same instant", "The two sensors run at incompatible frame rates", "The lidar's timestamps are in a different epoch", "The camera cannot be triggered externally"], a: 0, why: "At a metre per second, ten milliseconds of skew is a centimetre of misregistration. Hardware triggering, or at least a common clock, is what makes the fusion honest." },
{ t: "rob-perception", d: 2, q: "What does a point cloud lack that an image has?", o: ["Dense colour and texture information", "Any notion of the sensor's viewpoint", "Metric scale in the measurements", "Coverage of the whole field of view"], a: 0, why: "Fusing the two gives geometry from the lidar and appearance from the camera, which is why they are so often paired. The registration between them has to be calibrated." },
{ t: "rob-perception", d: 2, q: "Why does a retroreflective marker help a vision system?", o: ["It returns light along the incoming path, so it is bright", "It emits its own light at a known wavelength", "It changes colour with the viewing angle", "It reflects the infrared light uniformly in every direction"], a: 0, why: "With a ring light around the lens it appears far brighter than the scene, which makes segmentation trivial. That reliability is why motion capture uses them." },

// --------------------------------------------------------------- rob-slam
{ t: "rob-slam", d: 1, q: "What does SLAM solve?", o: ["Building a map while localising within it", "Localising within a map that is already known", "Building a map from a known set of poses", "Planning a path through an unknown environment"], a: 0, why: "The two are coupled: the map depends on the poses and the poses depend on the map. Solving either alone is a much easier problem." },
{ t: "rob-slam", d: 2, q: "What does loop closure correct?", o: ["Accumulated drift, when a place is recognised again", "The scale ambiguity in a monocular system", "The distortion in the camera's lens model", "The bias present in the inertial sensor's own readings"], a: 0, why: "Recognising a previously visited place adds a constraint that pulls the whole trajectory into consistency. Without it the map slowly bends." },
{ t: "rob-slam", d: 2, q: "What is a false loop closure?", o: ["Matching two places that only look similar", "Failing to recognise a place already visited", "Closing a loop before the robot has returned", "Detecting a loop in a featureless corridor"], a: 0, why: "It is far more damaging than a missed one, because it drags the map into an impossible shape. That is why matches are verified geometrically before being accepted." },
{ t: "rob-slam", d: 3, q: "What does a pose graph represent?", o: ["Poses as nodes and relative measurements as edges", "The map itself, as a grid of occupied and free cells", "The uncertainty of each landmark's position", "The sequence of control inputs applied"], a: 0, why: "Optimising it finds the poses that best satisfy all the constraints, including loop closures. It scales far better than keeping a full covariance over every landmark." },
{ t: "rob-slam", d: 2, q: "What does an occupancy grid cell store?", o: ["The probability that the cell is occupied", "The number of times the robot visited the cell", "The height of the terrain at that location", "The distance to the nearest obstacle"], a: 0, why: "Storing it as a log-odds value makes the update a simple addition. A distance field is a different structure, built from the grid for planning." },
{ t: "rob-slam", d: 2, q: "Why does a particle filter suit global localisation?", o: ["It can represent several hypotheses at once", "It needs less computation than a Kalman filter", "It is immune to errors in the motion model", "It converges in a fixed number of updates"], a: 0, why: "A robot that does not know where it is has a multi-modal belief that a single Gaussian cannot express. The cost is that particle count grows badly with dimension." },
{ t: "rob-slam", d: 2, q: "What is particle deprivation?", o: ["All particles converge away from the true state", "The filter runs out of memory for particles", "Particles spread out until the estimate is useless", "The resampling step removes every particle"], a: 0, why: "Resampling kills off the correct hypothesis, and no particle can recover it. Injecting a few random particles each step is the standard, if inelegant, defence." },
{ t: "rob-slam", d: 3, q: "Why is the last pose usually fixed when optimising a pose graph?", o: ["The problem is otherwise only defined up to a global transform", "The last pose is the most accurately known", "It reduces the size of the optimisation problem", "The optimiser simply cannot handle any free-floating graph at all"], a: 0, why: "Only relative measurements exist, so the whole graph can slide and rotate freely. Fixing one node, usually the first, anchors it; which one you fix is a convention." },
{ t: "rob-slam", d: 2, q: "What does a submap approach buy you?", o: ["Local consistency without optimising everything each time", "A guarantee that every loop closure will always be found in time", "Immunity to drift within each submap", "A smaller map file for the same environment"], a: 0, why: "Building locally consistent pieces and then optimising the relations between them keeps the problem tractable. It is how large-scale mapping stays real time." },
{ t: "rob-slam", d: 2, q: "Why is a repetitive environment hard for SLAM?", o: ["Many places look alike, inviting false matches", "There are too few features to track reliably", "The lidar returns are too strong to process", "Odometry drifts faster in corridors"], a: 0, why: "A corridor of identical doors gives many plausible matches, and accepting the wrong one folds the map. Requiring geometric consistency across a sequence, rather than a single match, is what helps." },

// ---------------------------------------------------------- rob-actuators
{ t: "rob-actuators", d: 1, q: "What does a gearbox do to the reflected inertia at the motor?", o: ["Divides the load inertia by the ratio squared", "Multiplies the load inertia by the ratio", "Leaves the inertia unchanged but scales the torque", "Divides the inertia by the ratio directly"], a: 0, why: "That is why a high ratio makes the load feel light to the motor, and why the motor's own inertia can then dominate. Matching the two is the classic sizing exercise." },
{ t: "rob-actuators", d: 2, q: "Why is a high-ratio gearbox bad for force control?", o: ["Reflected inertia and friction make it non-backdrivable", "The gearbox simply cannot transmit any torque in the reverse direction", "The output torque ripple becomes too large", "The gear teeth cannot survive reversing loads"], a: 0, why: "Impacts are transmitted rather than absorbed, and you cannot sense force through the drive. That is why direct drive and series elastic actuators exist." },
{ t: "rob-actuators", d: 2, q: "What is a series elastic actuator for?", o: ["Measuring and controlling force through a known spring", "Storing energy to improve the actuator's efficiency", "Absorbing shock loads to protect the gearbox", "Allowing the joint to be backdriven by hand"], a: 0, why: "The spring deflection is a direct force measurement, and it makes the actuator inherently compliant. The cost is bandwidth, because the spring is a low-pass filter." },
{ t: "rob-actuators", d: 3, q: "Which torque figure should size a motor for a duty cycle?", o: ["The RMS torque over the cycle", "The peak torque required at any instant", "The stall torque from the datasheet", "The average of the peak and holding torques"], a: 0, why: "Heating goes as current squared, so the RMS value is what determines the thermal limit. The peak still has to be within the motor's and drive's instantaneous capability." },
{ t: "rob-actuators", d: 2, q: "Why is a stalled motor a thermal hazard?", o: ["No back-EMF means current is limited only by resistance", "The bearings overheat when they are not rotating", "The magnetic field collapses and induces eddy currents", "The winding inductance rises sharply at zero speed"], a: 0, why: "Stall current can be many times the running current and it flows indefinitely. A current limit or a stall timeout in firmware is what protects the winding." },
{ t: "rob-actuators", d: 2, q: "What does the torque constant tell you?", o: ["Torque produced per amp of current", "The maximum torque before the motor stalls", "How torque falls as the speed increases", "The efficiency of the motor at rated load"], a: 0, why: "In SI units it equals the back-EMF constant numerically, because the machine is reversible and energy conserving. That identity is a useful sanity check on a datasheet." },
{ t: "rob-actuators", d: 2, q: "What causes cogging torque?", o: ["Interaction between magnets and stator teeth", "Friction in the bearings at any very low speed", "Ripple in the drive's current control", "Misalignment between rotor and stator"], a: 0, why: "It is a position-dependent torque present even with no current, and it is worst at low speed. Slotless or skewed designs reduce it at some cost in torque density." },
{ t: "rob-actuators", d: 3, q: "Why does harmonic drive backlash matter less than its compliance?", o: ["Backlash is near zero but torsional stiffness is finite", "Backlash is compensated automatically by the controller", "Compliance only matters at very high speeds", "Backlash cannot be measured on a harmonic drive"], a: 0, why: "The wave generator gives essentially no backlash, which is why it is chosen, but the flexspline twists under load. That compliance shows up as a resonance in the control loop." },
{ t: "rob-actuators", d: 2, q: "What limits how quickly a pneumatic actuator can be controlled?", o: ["Air is compressible, so force and position are coupled slowly", "The valves cannot be switched fast enough", "The supply pressure simply varies far too much to control reliably", "Pneumatic cylinders have very high friction"], a: 0, why: "The compressibility introduces a slow, nonlinear dynamic between valve command and force. It is why pneumatics suit binary motion far better than precise servo control." },
{ t: "rob-actuators", d: 2, q: "Why does adding mass at the end of an arm cost so much?", o: ["It raises inertia for every joint upstream", "It reduces the reach of the manipulator", "It increases the friction in the wrist joints", "It changes the arm's kinematic parameters"], a: 0, why: "The base joint sees it multiplied by the square of the distance, so a light gripper is worth a great deal. That is why cabling and sensors are moved down the chain wherever possible." },

// --------------------------------------------------------- rob-estimation
{ t: "rob-estimation", d: 2, q: "What does an accelerometer actually measure?", o: ["Specific force, which is acceleration plus gravity", "The absolute acceleration measured in the world frame", "The tilt angle relative to the horizontal", "The rate of change of the vehicle's velocity"], a: 0, why: "In free fall it reads zero, and at rest it reads one g upward. That is why it gives attitude only when the vehicle is not accelerating." },
{ t: "rob-estimation", d: 2, q: "Why does a gyroscope's bias matter so much?", o: ["It integrates into an unbounded angle error", "It saturates the sensor at high rotation rates", "It makes the scale factor temperature dependent", "It prevents the sensor from measuring slow rotation"], a: 0, why: "A small constant offset becomes a steadily growing heading error. Estimating it as a state, corrected by an absolute reference, is the standard treatment." },
{ t: "rob-estimation", d: 2, q: "What does a gyro's scale factor error produce?", o: ["An error proportional to the rotation rate", "A constant offset, regardless of the motion involved", "Noise that grows with temperature", "A delay between motion and measurement"], a: 0, why: "Unlike bias, it only shows up when you are turning, so it is invisible on a stationary calibration. A rotation through a known angle is what reveals it." },
{ t: "rob-estimation", d: 3, q: "Why is a magnetometer troublesome on a robot?", o: ["Nearby iron and motor currents distort the field", "It only works above a certain sample rate", "It cannot resolve heading near the equator", "Its output is simply too noisy to be useful at all"], a: 0, why: "Hard and soft iron effects from the robot itself are usually larger than the earth's field variation. Calibrating them out, and re-calibrating when the payload changes, is essential." },
{ t: "rob-estimation", d: 2, q: "What does a zero-velocity update give a pedestrian or legged system?", o: ["A chance to correct drift when a foot is stationary", "A measurement of the terrain's slope", "A way of detecting whenever the robot has fallen over", "An estimate of the sensor's scale factor"], a: 0, why: "Knowing the velocity is exactly zero is a strong constraint that bounds the drift. It is why foot-mounted inertial navigation works far better than it has any right to." },
{ t: "rob-estimation", d: 2, q: "Why fuse inertial data with vision rather than use either alone?", o: ["Inertial is good short-term, vision is drift-free", "Vision is faster and inertial is more accurate", "Inertial data has no noise to speak of", "Vision provides the scale that inertial lacks"], a: 0, why: "The inertial sensor drifts over long intervals but is excellent between frames, while vision is absolutely referenced but fails during fast motion and in low texture. They fail in complementary ways." },
{ t: "rob-estimation", d: 2, q: "What is the observability problem with monocular visual odometry?", o: ["Scale is not determined without another source", "Rotation cannot be recovered from images alone", "Depth is ambiguous for distant features only", "The camera's intrinsics cannot be estimated"], a: 0, why: "A large scene far away looks the same as a small one nearby. An inertial sensor, a stereo baseline or a known object size resolves it." },
{ t: "rob-estimation", d: 3, q: "Why is a static bias calibration insufficient for a MEMS gyro?", o: ["The bias moves with temperature and over time", "The calibration cannot be performed accurately enough", "Static calibration measures the scale factor instead", "The bias is different for each axis"], a: 0, why: "Turn-on to turn-on repeatability and in-run drift are both specified, and both defeat a one-off calibration. That is why the bias belongs in the filter's state." },
{ t: "rob-estimation", d: 2, q: "Why does doubling process noise as a fix usually go wrong?", o: ["It masks a modelling error rather than fixing it", "It makes the filter diverge immediately", "It reduces the update rate of the filter", "It prevents the covariance from ever converging at all"], a: 0, why: "Turning up Q makes the filter trust measurements more and hides the symptom of a wrong model. Diagnosing why the innovation is not white is the honest route." },
{ t: "rob-estimation", d: 2, q: "What does a chi-squared test on the innovation give you?", o: ["A principled outlier gate scaled by the covariance", "A measure of how well the filter has actually converged", "The optimal value of the Kalman gain", "A test of whether the model order is correct"], a: 0, why: "It normalises the innovation by its expected covariance, so the threshold means the same thing whatever the current uncertainty. A fixed threshold in metres does not." },

// ----------------------------------------------------------------- rob-sim
{ t: "rob-sim", d: 1, q: "What is the sim-to-real gap?", o: ["The difference between simulated and real dynamics", "The time lag between simulation and hardware runs", "The difference in sensor resolution between the two", "The gap between simulated and real compute budgets"], a: 0, why: "A policy trained only in simulation may have exploited details that do not hold in the world. Domain randomisation is the usual attempt to close it." },
{ t: "rob-sim", d: 2, q: "What does domain randomisation do?", o: ["Varies simulator parameters so the policy must be robust", "Randomises the order in which episodes are run", "It adds noise to the reward in order to prevent overfitting", "Selects a random subset of sensors each episode"], a: 0, why: "If the policy must work across a wide range of masses, frictions and delays, the real values usually lie inside that range. Too wide a range and nothing learns at all." },
{ t: "rob-sim", d: 2, q: "Why does contact modelling dominate simulation fidelity?", o: ["Contacts are stiff, discontinuous and hard to integrate", "Contact forces are the largest in the system", "Most robots spend all their time in contact", "Contact models are simply the slowest part of all to compute"], a: 0, why: "A rigid contact is effectively an infinitely stiff spring, so the solver must approximate. Friction, restitution and penetration handling are where simulators differ most." },
{ t: "rob-sim", d: 3, q: "Why does a smaller simulation timestep not always help?", o: ["It costs time and may not fix a modelling error", "Smaller steps make the solver less stable", "The physics engine ignores steps below a limit", "Sensor models cannot be evaluated that often"], a: 0, why: "If the answer changes materially when you halve the step, the result is not converged. If it does not, the remaining error is in the model, not the integrator." },
{ t: "rob-sim", d: 2, q: "What should be checked before trusting a simulator's inertia values?", o: ["That they are consistent with the CAD model", "That they are the same for every link", "That they match the manufacturer's datasheet", "That they produce a stable simulation"], a: 0, why: "Simulators will happily load physically impossible inertia tensors and produce plausible-looking nonsense. Checking the triangle inequality on the principal moments catches the worst of it." },
{ t: "rob-sim", d: 2, q: "Why simulate sensor noise and latency rather than ideal sensors?", o: ["The controller must cope with them on the real robot", "It makes the simulation run faster overall", "Ideal sensors cause the physics engine to diverge", "Noise is needed for the optimiser to converge"], a: 0, why: "A controller tuned against perfect, instantaneous measurements is tuned for a robot that does not exist. Latency in particular changes the achievable bandwidth." },
{ t: "rob-sim", d: 2, q: "What is the value of replaying recorded data through the stack?", o: ["It tests the software against real sensor behaviour", "It measures the simulator's own accuracy quite directly", "It removes the need for a physics engine", "It allows the controller to be tuned offline"], a: 0, why: "Recorded data has the noise, dropouts and timing of the real world without needing the robot. It is the cheapest high-fidelity test available." },
{ t: "rob-sim", d: 3, q: "Why is a hardware abstraction layer worth building early?", o: ["The stack can run against simulated or recorded hardware", "It reduces the total amount of code that has to be written", "It makes the controller run faster on the target", "It is required by most robotics middleware"], a: 0, why: "Most software can then be developed and tested without the robot, which is usually the scarce resource. It also makes swapping a sensor a contained change." },
{ t: "rob-sim", d: 2, q: "What does a deterministic simulation buy you?", o: ["A failure can be reproduced exactly", "A more accurate model of the physics", "Faster execution on multiple cores", "Immunity to floating point rounding"], a: 0, why: "Debugging a stochastic failure that never recurs is close to impossible. Fixing the seed and the thread scheduling is what makes a bug investigable." },
{ t: "rob-sim", d: 2, q: "Why should a policy be tested on a simulator it was not trained on?", o: ["It reveals reliance on one engine's quirks", "It measures the training time more fairly", "It is required before deploying to hardware", "Different engines run at different speeds"], a: 0, why: "A policy that only works in the engine that trained it has learned that engine, not the task. Cross-engine evaluation is a cheap proxy for the reality gap." },

// -------------------------------------------------------------- rob-manip
{ t: "rob-manip", d: 2, q: "What does form closure mean for a grasp?", o: ["The object is constrained by geometry alone", "The fingers apply enough force to prevent slip", "The grasp is stable under gravity only", "The object is held against a fixed surface"], a: 0, why: "It holds regardless of friction, which makes it the stronger condition. Force closure relies on friction and is far more common in practice." },
{ t: "rob-manip", d: 2, q: "Why is compliance useful during insertion?", o: ["Position error is inevitable, so compliance absorbs it", "It reduces the force needed to insert the part", "It allows the gripper to be positioned rather more slowly", "It compensates for errors in the object's model"], a: 0, why: "Without it a small misalignment generates very large contact forces. A remote centre of compliance device does this passively and works remarkably well." },
{ t: "rob-manip", d: 3, q: "What does impedance control regulate?", o: ["The relationship between motion and contact force", "The exact position of the end effector, very precisely", "The force applied regardless of position", "The stiffness of the manipulator's joints"], a: 0, why: "It specifies how the arm should behave when pushed, rather than commanding one or the other. Stability requires knowing the environment's stiffness well enough." },
{ t: "rob-manip", d: 2, q: "What does a force-torque sensor at the wrist let you do?", o: ["Detect contact and control interaction forces", "Measure the mass of the object being held", "Estimate the joint torques more accurately", "Compensate for gravity on the arm's links"], a: 0, why: "It measures the interaction directly rather than inferring it through the drive, which a high-ratio gearbox makes impossible. It also needs the tool's own weight compensating." },
{ t: "rob-manip", d: 2, q: "Why does a suction gripper struggle with porous objects?", o: ["Air leaks through, so the vacuum cannot be held", "The object deforms under the applied pressure", "The suction cup cannot seal on a rough surface", "The vacuum pump cannot reach the needed pressure"], a: 0, why: "Cardboard, fabric and foam all leak faster than a small pump can compensate. A higher-flow venturi, or a different gripper, is the answer." },
{ t: "rob-manip", d: 2, q: "What is the advantage of an underactuated gripper?", o: ["It conforms to shape with fewer actuators", "It applies a precisely controlled force per finger", "It can be modelled exactly for planning", "It grips faster than a fully actuated hand"], a: 0, why: "Linkages and springs let the fingers wrap around whatever they meet, which handles variety well. You give up precise control of the grasp configuration." },
{ t: "rob-manip", d: 3, q: "Why is grasp planning hard even with a perfect point cloud?", o: ["Mass, friction and contents are not visible", "The point cloud is too dense to search quickly", "The gripper's kinematics are not known exactly", "Point clouds cannot represent concave shapes"], a: 0, why: "Geometry tells you where you could grip, not whether it will hold. A closed box gives no clue where its centre of mass is." },
{ t: "rob-manip", d: 2, q: "What does a remote centre of compliance do?", o: ["Puts the compliant centre at the part's tip", "Removes all compliance from the wrist", "Measures the contact force during insertion", "Aligns the gripper before contact is made"], a: 0, why: "Placing the compliance centre at the insertion point turns a lateral error into a rotation that helps rather than jams. It is a purely mechanical solution to a hard control problem." },
{ t: "rob-manip", d: 2, q: "Why does a peg-in-hole task benefit from a spiral search?", o: ["It covers the uncertainty region systematically", "It reduces the contact force during insertion", "It compensates for the gripper's compliance", "It aligns the peg's axis with the hole"], a: 0, why: "Combined with a downward force and a stop on displacement, it finds the hole without needing to see it. It is the standard fallback when vision is not accurate enough." },
{ t: "rob-manip", d: 2, q: "What does hybrid position and force control separate?", o: ["Directions controlled by position from those by force", "The arm's fast and slow dynamics", "The gripper's control from the arm's", "The planning from the execution inside the controller itself"], a: 0, why: "Sliding along a surface wants force control normal to it and position control along it. The selection matrix is what encodes which is which." },

// ------------------------------------------------------------ rob-dynamics
{ t: "rob-dynamics", d: 2, q: "What does the inertia matrix of a manipulator depend on?", o: ["The current joint configuration", "The joint velocities at that instant", "The payload's mass alone", "The gravity vector's direction"], a: 0, why: "The effective inertia at a joint changes as the arm folds, which is why fixed gains cannot be optimal everywhere. It is also why gain scheduling on pose is common." },
{ t: "rob-dynamics", d: 2, q: "What are Coriolis and centrifugal terms proportional to?", o: ["Products of joint velocities", "The joint accelerations", "The gravitational constant", "The payload mass only"], a: 0, why: "They only appear when the arm is moving, and they grow with the square of speed. That is why a slow arm can ignore them and a fast one cannot." },
{ t: "rob-dynamics", d: 3, q: "What does computed torque control require?", o: ["A dynamic model good enough to cancel the nonlinearity", "A force sensor at every joint of the arm", "A much higher sample rate than PID control", "A linear plant with no coupling at all between the joints"], a: 0, why: "It inverts the dynamics so an outer linear controller sees a decoupled double integrator. Its performance is exactly as good as the model." },
{ t: "rob-dynamics", d: 2, q: "Why is gravity compensation such a good first step?", o: ["It removes a large, known, configuration-dependent torque", "It is the only term that can be computed in real time at all", "It eliminates the need for joint position feedback", "It reduces the inertia the motors have to accelerate"], a: 0, why: "Taking it out of the feedback loop's job means the gains can be tuned for dynamics rather than for holding. It is cheap to compute and immediately visible in performance." },
{ t: "rob-dynamics", d: 2, q: "What does joint friction do to a dynamic model's accuracy?", o: ["It is large, nonlinear and hard to identify", "It only matters at very high joint speeds", "It can be measured once and treated as constant", "It cancels out when the arm moves symmetrically"], a: 0, why: "Gearbox efficiency, seal drag and cable stiffness all contribute, plus the Coulomb term that must be overcome to start moving. It is usually the biggest unmodelled term." },
{ t: "rob-dynamics", d: 2, q: "What is the recursive Newton-Euler algorithm used for?", o: ["Computing joint torques from a desired motion", "Solving the inverse kinematics numerically", "Finding the arm's natural frequencies", "Estimating the payload's mass from measurements"], a: 0, why: "It propagates velocities and accelerations outward and forces inward, in linear time in the number of links. That efficiency is what makes real-time computed torque possible." },
{ t: "rob-dynamics", d: 3, q: "Why does link flexibility complicate control?", o: ["The tip and the joint no longer move together", "It changes the arm's kinematics under load", "The joint sensors stop working correctly", "Flexible links cannot be modelled at all"], a: 0, why: "Controlling the joint no longer controls the tip, and the flexible mode is a lightly damped resonance in the loop. Tip sensing, or a bandwidth below the mode, are the options." },
{ t: "rob-dynamics", d: 2, q: "What does a payload change do to a tuned controller?", o: ["It changes the effective inertia and detunes the loop", "It only ever affects the gravity compensation term itself", "It changes the kinematics of the manipulator", "It has no effect if the arm moves slowly"], a: 0, why: "Both the inertia and the gravity torque change, so gains tuned for one payload are wrong for another. Identifying the payload and scheduling on it is the systematic answer." },
{ t: "rob-dynamics", d: 2, q: "Why is the motor's own inertia significant with a high gear ratio?", o: ["Reflected load inertia shrinks by the ratio squared", "The motor accelerates considerably faster than the load", "The gearbox adds inertia of its own", "The motor's inertia rises with temperature"], a: 0, why: "Past a certain ratio the motor is mostly accelerating itself, so more ratio stops helping. The optimum matches reflected load inertia to rotor inertia." },
{ t: "rob-dynamics", d: 2, q: "What does energy-based analysis give you for a manipulator?", o: ["A route to stability proofs without linearising", "An exact solution to the inverse dynamics", "The minimum energy trajectory between any two poses", "The natural frequencies of each link"], a: 0, why: "A Lyapunov function built from kinetic and potential energy can prove stability for the full nonlinear system. It is how passivity-based controllers are justified." },

// ------------------------------------------------------------ rob-planning
{ t: "rob-planning", d: 1, q: "What is configuration space?", o: ["The space of joint values, in which the robot is a point", "The three-dimensional physical space that the robot occupies", "The set of poses the end effector can reach", "The space of velocities the robot can achieve"], a: 0, why: "The robot becomes a point and the obstacles become complicated regions, which is what makes planning tractable. Building the obstacle regions explicitly is usually infeasible." },
{ t: "rob-planning", d: 2, q: "Why do sampling-based planners avoid building the obstacle regions?", o: ["The space grows exponentially with dimension", "The obstacles move too quickly to represent", "Collision checking is cheaper than representation", "The regions cannot be expressed analytically"], a: 0, why: "A grid at useful resolution over a seven-joint arm is astronomically large. Sampling and checking individual configurations sidesteps the representation entirely." },
{ t: "rob-planning", d: 2, q: "What does probabilistic completeness guarantee?", o: ["If a solution exists it will be found eventually", "A solution will always be found within a fixed time", "The solution found is the shortest one", "Failure proves that no solution exists"], a: 0, why: "The probability approaches one as samples increase, but failure is never proof there is none. That asymmetry matters when a planner returns nothing." },
{ t: "rob-planning", d: 3, q: "What does RRT-star add over RRT?", o: ["Asymptotic optimality, by rewiring the tree", "A guarantee of finding a solution faster", "The ability to handle dynamic constraints", "Support for multiple goal configurations"], a: 0, why: "It reconsiders connections as samples accumulate, so the path converges towards optimal. Plain RRT finds a path quickly and it may be very poor." },
{ t: "rob-planning", d: 2, q: "Why do sampling-based paths need post-processing?", o: ["They are feasible but jagged and unnecessarily long", "They violate the robot's joint limits", "They contain configurations that are in collision", "They do not reach the goal exactly"], a: 0, why: "Random samples connected by straight lines have no reason to be smooth. Shortcutting and then fitting a smooth trajectory is the standard second stage." },
{ t: "rob-planning", d: 2, q: "When is a PRM preferable to an RRT?", o: ["When many queries share one static environment", "When the environment changes on every query", "When the robot has very few degrees of freedom", "When only one path is ever needed"], a: 0, why: "Building the roadmap is expensive but amortises over many start and goal pairs. RRT grows a tree towards a single goal, which suits a one-off query." },
{ t: "rob-planning", d: 2, q: "What does a heuristic contribute to A-star?", o: ["An estimate of remaining cost that focuses the search", "A guarantee that the path it finds is always the optimal one", "A way of handling dynamic obstacles", "A reduction in the memory the search needs"], a: 0, why: "An admissible heuristic never overestimates, which preserves optimality while pruning the search. A zero heuristic reduces A-star to Dijkstra." },
{ t: "rob-planning", d: 3, q: "When does a geometric path need to become a trajectory?", o: ["When velocity or acceleration limits constrain the motion", "Whenever the robot happens to have more than three joints at all", "Only when obstacles are moving in the scene", "When the path passes near a singularity"], a: 0, why: "A geometric path says where to go, not how fast, and the robot cannot follow an arbitrary path at arbitrary speed. Non-holonomic constraints force the same distinction." },
{ t: "rob-planning", d: 2, q: "What does inflating obstacles in a costmap achieve?", o: ["The planner keeps clearance without modelling the robot's shape", "It simulates the obstacles growing over time", "It compensates for any errors there are in the map's own resolution", "It marks regions the sensor could not observe"], a: 0, why: "Growing the obstacle by the robot's radius turns a shaped robot into a point. It is the cheapest possible configuration-space construction." },
{ t: "rob-planning", d: 2, q: "Why does a local planner exist alongside a global one?", o: ["It reacts to obstacles the map does not contain", "It runs on a separate processor for speed", "It plans in configuration space rather than the map", "It optimises the path the global planner returns"], a: 0, why: "The global plan is computed against a map that is already out of date. The local planner handles what appears in front of the robot now, within the global plan's guidance." },

// ------------------------------------------------------------------ rob-vo
{ t: "rob-vo", d: 2, q: "Why does pure rotation break monocular visual odometry?", o: ["Without translation there is no parallax", "The image blurs too much to track features", "Rotation cannot be estimated from images", "The features leave the field of view too quickly"], a: 0, why: "No depth information is available, so triangulation fails. Detecting the case and handling it separately is what a robust system does." },
{ t: "rob-vo", d: 2, q: "Why is RANSAC used in feature matching?", o: ["Correspondences always contain gross outliers", "It speeds up the matching process considerably", "It calibrates the camera as a side effect", "It compensates for the rolling shutter"], a: 0, why: "Least squares is destroyed by even a few wrong matches, and there are always wrong matches. Fitting to random minimal subsets and counting inliers finds the consensus." },
{ t: "rob-vo", d: 2, q: "What does bundle adjustment optimise?", o: ["Camera poses and landmark positions together", "Only the camera poses, holding landmarks fixed", "The camera's intrinsic parameters alone", "The order in which frames were captured"], a: 0, why: "Minimising reprojection error over both is what makes the reconstruction consistent. It is expensive, which is why it is usually run over a sliding window." },
{ t: "rob-vo", d: 3, q: "What is a keyframe and why use one?", o: ["A selected frame kept for optimisation, to bound cost", "The first frame of every new sequence", "A frame in which some kind of loop closure was detected", "A frame with the largest number of features"], a: 0, why: "Optimising every frame is unaffordable, so a subset with sufficient baseline is kept. Choosing them by parallax rather than by time is what keeps the triangulation well conditioned." },
{ t: "rob-vo", d: 2, q: "What is scale drift in monocular systems?", o: ["The estimated scale slowly changes over the trajectory", "The camera's own focal length changes with the temperature", "Features are detected at inconsistent scales", "The map's resolution degrades over time"], a: 0, why: "Monocular reconstruction is only defined up to a scale factor, and that factor drifts as the estimate propagates. A loop closure or an absolute sensor is what corrects it." },
{ t: "rob-vo", d: 2, q: "Why does visual odometry struggle in a dark tunnel?", o: ["Too few reliable features to track", "The camera's exposure time becomes too short", "The lens distortion changes in low light", "Motion blur increases the feature count"], a: 0, why: "Texture-poor, low-light scenes give nothing to match, and increasing exposure adds motion blur. That is exactly where an inertial sensor has to carry the estimate." },
{ t: "rob-vo", d: 2, q: "What does a direct method use instead of features?", o: ["Pixel intensities compared between images", "The edges detected in each frame", "The optical flow field computed densely", "The depth map from a stereo pair"], a: 0, why: "It minimises photometric error directly, which uses more of the image and copes better with low texture. It is more sensitive to lighting changes and to a poor initialisation." },
{ t: "rob-vo", d: 3, q: "Why does tight coupling of inertial and visual data beat loose coupling?", o: ["The inertial data constrains the visual optimisation itself", "It requires a good deal less computation than loose coupling does", "Loose coupling cannot estimate scale at all", "Tight coupling removes the need for calibration"], a: 0, why: "Using the inertial measurements inside the same optimisation lets each correct the other, rather than fusing two independent estimates afterwards. It is harder to implement and noticeably more accurate." },
{ t: "rob-vo", d: 2, q: "What does the reprojection error measure?", o: ["The pixel distance between a predicted and observed feature", "The difference between any two consecutive camera poses taken", "The uncertainty in a landmark's estimated depth", "The distortion introduced by the camera lens"], a: 0, why: "It is the natural residual because it is measured where the noise actually is, in the image. Minimising it is what bundle adjustment does." },
{ t: "rob-vo", d: 2, q: "Why must the camera-to-inertial extrinsics be calibrated carefully?", o: ["A small rotation error biases the whole estimate", "The two sensors cannot otherwise be synchronised", "The camera's intrinsics depend on the extrinsics", "The inertial sensor cannot be mounted rigidly"], a: 0, why: "The gravity direction and the rotation rates are expressed in the wrong frame, which biases everything downstream. Self-calibrating the extrinsics online is common for this reason." },

// --------------------------------------------------------------- rob-comms
{ t: "rob-comms", d: 2, q: "Why is CAN still used for robot joints?", o: ["Bounded latency and priority-based arbitration", "It carries more data per second than Ethernet", "It requires no termination or wiring care", "It supports far more nodes than any alternative"], a: 0, why: "Telemetry and commands are mostly small scalars, and the low overhead plus prioritisation matters more than payload size. The highest-priority message suffers no delay from a collision." },
{ t: "rob-comms", d: 2, q: "Why is plain Ethernet awkward for a control loop?", o: ["Latency is unbounded under contention", "Ethernet cannot carry small messages efficiently", "The cabling is too heavy for a moving joint", "It requires a real-time operating system"], a: 0, why: "Retries and contention give a long tail, and a control loop needs a deadline rather than an average. EtherCAT and similar protocols exist precisely to fix that." },
{ t: "rob-comms", d: 3, q: "What does a node's transmit error counter exceeding its limit cause on CAN?", o: ["The node removes itself from the bus", "The bus resets and all nodes re-arbitrate", "The message is retried at a lower priority", "The controller switches to a backup bus"], a: 0, why: "Bus-off stops a faulty node jamming the bus for everyone, which is a genuine safety feature. Recovering from it requires deliberate action by the software." },
{ t: "rob-comms", d: 2, q: "Why should every message carry a timestamp and sequence number?", o: ["Loss, reordering and delay become detectable afterwards", "They are required by almost all of the middleware libraries", "They allow the message to be compressed better", "They identify which node sent the message"], a: 0, why: "Without them a dropped or delayed packet is invisible in the log. It is a few bytes that makes post-mortem analysis possible." },
{ t: "rob-comms", d: 2, q: "Why is UDP often preferred to TCP for telemetry?", o: ["Stale data blocks fresh data under TCP", "UDP guarantees delivery in order", "TCP cannot carry binary payloads", "UDP uses less bandwidth per message"], a: 0, why: "Retransmission and in-order delivery mean an old packet holds up newer ones, and for telemetry the newest sample matters more than a complete history. Control commands may want the opposite." },
{ t: "rob-comms", d: 2, q: "What should a robot do when a command link goes silent?", o: ["Enter a predefined safe state after a short timeout", "Continue executing the last received command", "Stop instantly, with no controlled deceleration at all", "Retry the connection until it is restored"], a: 0, why: "Typically that means stopping in a controlled way, and the timeout is a designed number rather than a guess. Continuing on the last command is how a runaway happens." },
{ t: "rob-comms", d: 3, q: "Why does wireless control need a different failure model?", o: ["Dropouts are expected, not exceptional", "Wireless links have lower bandwidth than wired", "Encryption adds unpredictable latency", "Radio interference cannot be detected"], a: 0, why: "A wired link failing usually means something broke; a wireless one dropping is normal. The design has to make a dropout uneventful rather than treating it as a fault." },
{ t: "rob-comms", d: 2, q: "What does time synchronisation across nodes enable?", o: ["Measurements from different nodes can be fused", "Nodes can share a single processor's clock", "The bus can run at a higher data rate", "Messages can be compressed more effectively"], a: 0, why: "Fusion assumes the measurements refer to the same instant, and a few milliseconds of skew is metres of error at speed. PTP or a hardware sync line is what provides it." },
{ t: "rob-comms", d: 2, q: "Why keep the safety chain separate from the data network?", o: ["It must work when the software has failed", "It needs a higher bandwidth than the data network", "The safety signals are analogue rather than digital", "Regulations forbid sharing a physical medium"], a: 0, why: "A hardwired emergency stop does not depend on any software or protocol being healthy. That independence is the entire point." },
{ t: "rob-comms", d: 2, q: "What does message rate tell you during integration?", o: ["Whether a node is keeping up or falling behind", "The bandwidth remaining on the physical link", "Which node has the highest priority", "The latency between command and response"], a: 0, why: "A publisher running at half its nominal rate is a symptom worth chasing before it becomes a failure. It is one of the cheapest health signals to monitor." },

// -------------------------------------------------------------- rob-safety
{ t: "rob-safety", d: 2, q: "What does a category 0 stop do?", o: ["Removes power immediately", "Decelerates under control then removes power", "Stops motion but keeps the drives energised", "Reduces speed to a safe level and holds"], a: 0, why: "It is an uncontrolled stop, which can be the wrong answer for a robot holding a load. A category 1 stop decelerates first and then removes power." },
{ t: "rob-safety", d: 2, q: "What does safe torque off guarantee?", o: ["The drive cannot produce torque, without cutting the supply", "The motor is actively held at exactly zero speed by the controller", "The brake is applied and the axis is locked", "The drive's outputs are shorted together"], a: 0, why: "It is a certified hardware path that removes the gate drive, so no software fault can command torque. The axis can still coast or be moved by gravity." },
{ t: "rob-safety", d: 3, q: "Why is a risk assessment done before the design, not after?", o: ["The required mitigations shape the architecture", "It is required by the certification body's schedule", "It is cheaper to document early in the project", "The hazards cannot be identified once built"], a: 0, why: "Discovering that you need a dual-channel safety chain after the electronics are laid out is expensive. The assessment drives topology, sensor choice and even the mechanism." },
{ t: "rob-safety", d: 2, q: "What does a dual-channel safety input protect against?", o: ["A single fault leaving the safety function unavailable", "Electrical noise causing an occasional spurious trip somewhere", "Operators bypassing the emergency stop", "The controller losing power unexpectedly"], a: 0, why: "Two independent channels, cross-monitored, mean one failure is detected rather than hidden. Discrepancy between them is itself an alarm." },
{ t: "rob-safety", d: 2, q: "What is a safety-rated monitored stop?", o: ["The robot holds position with power on, monitored", "The robot decelerates and then removes power", "The robot moves at a reduced speed under supervision", "The robot stops only when a person is detected"], a: 0, why: "It allows a person to approach while the robot is stationary but still energised. The monitoring is what makes it safe rather than merely stopped." },
{ t: "rob-safety", d: 2, q: "Why is speed and separation monitoring useful in collaborative work?", o: ["It scales the allowed speed with the distance to a person", "It stops the robot whenever a person is present", "It limits the force that the robot is able to apply on contact", "It requires the person to wear a tracked marker"], a: 0, why: "It lets the robot work at full speed when nobody is near and slow down as they approach. Power and force limiting is the different approach where contact is permitted." },
{ t: "rob-safety", d: 3, q: "Why can a watchdog fed by a timer be worse than none?", o: ["It gives false confidence while every task is deadlocked", "It consumes a hardware timer that is needed elsewhere", "It resets the system more often than necessary", "It cannot be certified for safety use"], a: 0, why: "The device appears to be protecting you and is not, which is worse than knowing you have no protection. Feeding it only from evidence of task progress is what makes it real." },
{ t: "rob-safety", d: 2, q: "What must be true of a safety function's response time?", o: ["It must be bounded and verified, not just typical", "It must be faster than the control loop period", "It must be the same for every fault condition", "It must be measured in software at run time"], a: 0, why: "The stopping distance follows from the response time, so an unbounded worst case means an unbounded distance. Measuring the actual worst case is part of the validation." },
{ t: "rob-safety", d: 2, q: "Why should the safety system be independent of the control software?", o: ["A software fault must not disable the protection", "The safety system runs at a higher priority", "It allows the control software to be updated freely", "The two use incompatible programming languages"], a: 0, why: "If the same code that failed is also the code that is meant to stop you, there is no protection. Independence is the whole basis of the architecture." },
{ t: "rob-safety", d: 2, q: "What does testing the safety chain regularly achieve?", o: ["It proves the protection still works after changes", "It satisfies the insurance requirements", "It measures the wear on the contactors", "It calibrates all of the safety sensors' own thresholds"], a: 0, why: "Safety functions are rarely exercised in normal operation, so a broken one can stay broken indefinitely. A documented periodic proof test is what catches it." },

// ------------------------------------------------------------------ rob-rl
{ t: "rob-rl", d: 2, q: "What does the discount factor control?", o: ["How far ahead the policy effectively plans", "The learning rate of the value function", "How much exploration the agent performs", "The magnitude of the reward signal"], a: 0, why: "Near one values long-term return and lower values act greedily. It also bounds the value function, which matters for stability of the learning." },
{ t: "rob-rl", d: 2, q: "What is reward hacking?", o: ["Scoring highly while defeating the intent", "Modifying the reward function during training", "Exploiting a bug in the simulator's physics", "Learning a policy that maximises reward too slowly"], a: 0, why: "The policy satisfies the reward exactly as written, which is rarely what you meant. It is a specification failure rather than a learning failure." },
{ t: "rob-rl", d: 3, q: "What does a sparse reward make difficult?", o: ["Random exploration almost never reaches the reward", "The value function becomes impossible to represent", "The policy converges to a deterministic action", "The discount factor has to be set very low"], a: 0, why: "With no gradient to follow, learning stalls. Shaping, curricula or demonstrations are the standard ways to provide intermediate signal." },
{ t: "rob-rl", d: 2, q: "Why must everything the decision depends on be in the state?", o: ["Otherwise the problem is partially observed", "The state must be fully observable for any algorithm", "The policy cannot handle continuous variables", "The value function requires a Markov state"], a: 0, why: "The policy is a function of the state, so anything omitted simply cannot influence the action. Stacking recent observations, or using a recurrent policy, is how partial observability is handled." },
{ t: "rob-rl", d: 2, q: "What is the exploration-exploitation trade?", o: ["Trying new actions against using what works", "Balancing simulation time against real-robot time", "Choosing between on-policy and off-policy learning", "Trading sample efficiency for final performance"], a: 0, why: "Too little exploration and the agent settles for a mediocre policy; too much and it never converges. Entropy regularisation and epsilon-greedy are two common mechanisms." },
{ t: "rob-rl", d: 2, q: "Why is sample efficiency so important for real robots?", o: ["Real interaction is slow and wears out hardware", "The learning algorithms are computationally limited", "Real robots have noisier sensors than simulators", "The reward is harder to compute on hardware"], a: 0, why: "A million simulated episodes are cheap and a million real ones are not. That gap is why so much effort goes into training in simulation and transferring." },
{ t: "rob-rl", d: 3, q: "What makes an action space safe enough to explore on hardware?", o: ["Bounded actions with a supervisory layer able to override", "A very small learning rate during exploration", "Actions that are always smaller than the immediately previous one", "A simulator that has been validated beforehand"], a: 0, why: "The worst commanded action has to be survivable, because during exploration it will be commanded. Torque limits, joint limits and a hardware stop are what make that true." },
{ t: "rob-rl", d: 2, q: "What does behaviour cloning need that reinforcement learning does not?", o: ["Demonstrations of the desired behaviour", "A reward function specified in advance", "A simulator of the environment", "A model of the system's dynamics"], a: 0, why: "It is supervised learning on state-action pairs, so the expert has to exist. It also suffers from compounding error once the policy leaves the demonstrated distribution." },
{ t: "rob-rl", d: 2, q: "Why is a learned policy hard to certify?", o: ["Its behaviour outside the training distribution is unknown", "The network's own weights keep on changing during deployment", "Learned policies cannot be tested at all", "The training data cannot be reproduced exactly"], a: 0, why: "You cannot enumerate what it will do on an input it never saw. Wrapping it in a verified envelope, rather than certifying it directly, is the practical approach." },
{ t: "rob-rl", d: 2, q: "When is reinforcement learning genuinely the right tool?", o: ["When the dynamics are hard to model but easy to sample", "Whenever the control gains are hard to tune", "When the system has more than six degrees of freedom", "When a simulator of the robot already exists"], a: 0, why: "Contact-rich manipulation and legged locomotion fit, because writing the model is harder than trying things. A well-modelled linear plant does not." },

// ----------------------------------------------------------- rob-integration
{ t: "rob-integration", d: 2, q: "What is the right bring-up order for a new robot?", o: ["Power, then comms, then each sensor and actuator alone", "The full autonomy stack first, then the hardware", "Everything all at once, and then debug whatever does not work", "The mechanical assembly last, after the software"], a: 0, why: "Each layer depends on the one below, so a failure is attributable. Bringing several up together means you cannot tell which is at fault." },
{ t: "rob-integration", d: 2, q: "What does integration testing actually mean for a robot?", o: ["Running the full demo end to end, repeatedly, on the hardware", "Testing each module against its own unit tests", "Running the whole of the stack in simulation until it finally passes", "Checking that every interface compiles together"], a: 0, why: "The failures that matter are the ones between modules, under real timing and real conditions. Repetition is what turns an intermittent failure into a measurable rate." },
{ t: "rob-integration", d: 3, q: "Why does logging need designing rather than adding later?", o: ["Bandwidth, storage, timestamping and completeness all need planning", "Log files are hard to change once written", "The logging library must be chosen at compile time", "Logging always affects the real-time behaviour of the whole software stack"], a: 0, why: "The first field failure is too late to discover a gap in what you recorded. Deciding what constitutes a complete record is a design activity." },
{ t: "rob-integration", d: 2, q: "What should you log to debug an intermittent failure?", o: ["Enough state to replay the decision offline", "Only the error messages and their timestamps", "The full sensor stream at maximum rate", "The operator's actions during the run"], a: 0, why: "Inputs, internal state and outputs with consistent timestamps let you reconstruct what happened. Human readability is a distant second to completeness." },
{ t: "rob-integration", d: 2, q: "Why raise the rate of a suspected cause when hunting a rare bug?", o: ["It converts a rare event into a frequent one", "It reduces the load on the logging system", "It makes the failure less severe when it occurs", "It confirms the timing of the failure exactly"], a: 0, why: "Waiting for a once-a-week failure is not a debugging strategy. Making the suspect condition happen constantly either reproduces it quickly or exonerates it." },
{ t: "rob-integration", d: 2, q: "What does a version register or build hash on the robot give you?", o: ["A field failure can be tied to an exact build", "A way to update the software remotely", "Protection against any unauthorised firmware builds", "A measure of how long the robot has run"], a: 0, why: "It covers firmware, software and configuration together, including whether the tree was dirty. Without it you are guessing what was actually running." },
{ t: "rob-integration", d: 3, q: "Why is a hardware-in-the-loop rig worth building?", o: ["It exercises real timing and interfaces without the whole robot", "It is considerably cheaper than building a full simulation environment", "It removes the need for integration testing", "It guarantees the software will work on hardware"], a: 0, why: "Real buses, real drivers and real latency, with the mechanics replaced by a model, catches a class of bug simulation misses. It also runs unattended overnight." },
{ t: "rob-integration", d: 2, q: "What is the value of a repeatable demo scenario?", o: ["Changes can be compared against a known baseline", "It satisfies the customer's acceptance criteria", "It reduces the time spent on integration", "It exercises every code path in the stack"], a: 0, why: "Without a fixed scenario, every run differs and you cannot tell whether a change helped. It is the robotics equivalent of a benchmark." },
{ t: "rob-integration", d: 2, q: "Why measure end-to-end latency rather than each stage?", o: ["The total is what the control loop actually sees", "Individual stages cannot be measured accurately", "The stages interact in ways that cancel out", "It is the only number the customer cares about"], a: 0, why: "Queueing and scheduling between stages adds delay that per-stage measurement misses. Timestamping at the sensor and again at the actuator is what gives the true figure." },
{ t: "rob-integration", d: 2, q: "What does a soak test reveal that a functional test does not?", o: ["Slow leaks, drift and rare timing failures", "Whether each feature meets its specification", "The system's behaviour at the limits of its range", "Which modules consume the most CPU"], a: 0, why: "Memory growth, thermal drift and once-an-hour races only appear over time. Running for days, with the logs kept, is the only way to find them." },

]);
