// Questions for the eight RTL & Verilog lessons that had none.
BANKS["RTL & Verilog"] = BANKS["RTL & Verilog"].concat([

// ------------------------------------------------------------ rtl-arith
{ t: "rtl-arith", d: 2, q: "You multiply two 18-bit signed values. How many bits does the full product need?", o: ["18", "36", "35", "19"], a: 1, why: "Signed times signed gives the sum of the widths, so 36 bits. Truncating before you have decided the scaling is how a datapath silently loses its top bits or its precision." },
{ t: "rtl-arith", d: 2, q: "A pipelined multiply keeps failing timing despite targeting a DSP slice. What is the most likely cause?", o: ["The clock is far too fast for the fabric to keep up with reliably", "The DSP's internal pipeline registers are not being inferred", "The operands are too wide", "The multiplier is unsigned"], a: 1, why: "Logic ends up routed around the hard block. A DSP48 reaches its rated speed only when its input, pipeline and output registers are used. Registers placed a few levels of logic away from the block do not get absorbed into it." },
{ t: "rtl-arith", d: 2, q: "Why does truncation cause trouble in long filter chains?", o: ["It is noticeably slower than rounding to nearest", "It biases every result towards negative", "It loses more bits", "It breaks the sign"], a: 1, why: "The bias accumulates through the chain as a DC offset. Truncation is a floor, so the error is always in the same direction. Rounding costs an adder and makes the error zero-mean, which is why it is worth it once several stages cascade." },
{ t: "rtl-arith", d: 2, q: "In Verilog, what happens if one operand in an otherwise signed expression is unsigned?", o: ["It is sign-extended", "The whole expression is evaluated as unsigned", "A compile error", "The result stays signed right through"], a: 1, why: "Negative values become large positives. It is a silent, whole-expression rule and a classic source of a filter that works in simulation for positive input only. Declaring everything signed and using $signed() deliberately is the defence." },
{ t: "rtl-arith", d: 2, q: "Why is fixed point described as a convention rather than a type in RTL?", o: ["Tools do not support it", "The hardware only sees integers", "It is only used in simulation", "SystemVerilog added a real type for exactly this"], a: 1, why: "Where the binary point sits exists solely in your documentation and shift choices. Nothing checks it, so a Q15 value fed into a block expecting Q12 is a silent scaling bug. Naming signals with their format and commenting the alignment at every boundary is the practical discipline." },
{ t: "rtl-arith", d: 3, q: "Why does a long ripple-carry adder limit clock frequency in fabric?", o: ["It uses too many LUTs", "The carry must propagate through every bit position", "It needs more routing", "It simply cannot be pipelined in any useful way at all"], a: 1, why: "Delay grows with width. Modern FPGAs have dedicated fast carry chains that make this acceptable up to substantial widths. Beyond that the answers are pipelining the adder or using a carry-save structure for accumulation." },
{ t: "rtl-arith", d: 3, q: "What is bit growth discipline?", o: ["Minimising register width", "Tracking how each operation widens the result", "Using the widest type everywhere", "Growing the widths only at the very output stage"], a: 1, why: "You decide deliberately where to round or saturate, rather than letting the tool truncate. Each addition adds one bit and each multiply adds the operand widths. Deciding the width at every node in advance is what stops overflow appearing only on a rare input pattern." },
{ t: "rtl-arith", d: 3, q: "Why use carry-save addition when summing many partial products?", o: ["It uses fewer bits", "It defers carry propagation, keeping stage delay constant", "It is more accurate", "It handles signed values considerably better than a ripple carry"], a: 1, why: "One full adder at the end completes the sum. Each stage reduces three operands to two in constant time. It is the structure inside a Wallace tree multiplier, and it is why hardware multipliers are fast despite their apparent complexity." },

// ------------------------------------------------------------ rtl-fifo
{ t: "rtl-fifo", d: 1, q: "On a valid/ready interface, when does a transfer occur?", o: ["Whenever valid is asserted by the source", "On the edge where valid and ready are both high", "When ready is asserted", "When valid rises"], a: 1, why: "Both must be high simultaneously. The critical rule is that valid must not be withdrawn once asserted until the transfer completes, or the source can lose data." },
{ t: "rtl-fifo", d: 2, q: "You register ready on its way upstream for timing. What extra hardware do you now need?", o: ["A wider FIFO", "A skid buffer, to hold the beat that arrives late", "An extra clock domain in order to absorb the extra beat", "A larger counter"], a: 1, why: "It holds the beat arriving in the cycle before the upstream sees the deassertion. Registering ready adds a cycle of latency to the backpressure, so one more beat can arrive than you were ready for. The skid buffer's one-deep storage absorbs exactly that." },
{ t: "rtl-fifo", d: 2, q: "A FIFO's full flag reaches the source through three register stages. What minimum extra depth does that demand?", o: ["One word", "Three words, one per cycle of latency", "Six words, two for each cycle of latency", "None"], a: 1, why: "That is one for each cycle of latency in the backpressure path. The source keeps sending for three more cycles after the FIFO is actually full. Pipelining a flow-control signal always costs depth, and forgetting it produces overflow only under sustained load." },
{ t: "rtl-fifo", d: 2, q: "Which behaviour violates the valid/ready contract?", o: ["Ready asserted before valid", "Deasserting valid before the transfer completes", "Valid asserted for many cycles", "Ready being deasserted for many cycles"], a: 1, why: "Ready may be withdrawn freely; valid may not. The asymmetry exists so the source is never left uncertain whether its data was taken." },
{ t: "rtl-fifo", d: 2, q: "How do you size a FIFO for a bursty source and a steady sink?", o: ["Match the burst length exactly, with no margin at all", "From the burst length minus what the sink drains", "Twice the burst length", "By the clock ratio only"], a: 1, why: "Add margin for flow-control latency. If the average source rate exceeds the sink rate, no depth is sufficient and you need backpressure or a faster sink. The FIFO only absorbs bursts, never a rate mismatch." },
{ t: "rtl-fifo", d: 3, q: "Why does an asynchronous FIFO use Gray-coded pointers?", o: ["To save bits", "Only one bit changes per increment", "To simplify comparing the two pointers", "For error detection"], a: 1, why: "A pointer sampled mid-transition can only be the old or the new value, never a corrupt combination. A binary pointer crossing from 0111 to 1000 could be sampled as any of several wrong values. Gray coding makes the cross-domain sample always yield a valid, at-worst-stale pointer." },
{ t: "rtl-fifo", d: 3, q: "Why must a FIFO's full and empty flags be generated conservatively across clock domains?", o: ["To reduce logic", "The pointer from the other domain is always stale", "To meet timing", "To simplify the Gray code conversion logic considerably"], a: 1, why: "Full may be asserted early and empty late, never the reverse. A pessimistic flag costs a little capacity; an optimistic one corrupts data. Full is computed against a possibly-stale read pointer and empty against a possibly-stale write pointer for exactly this reason." },
{ t: "rtl-fifo", d: 3, q: "What does end-to-end backpressure buy over dropping data at a bottleneck?", o: ["Noticeably higher throughput overall in every case", "Lossless behaviour under backpressure", "Lower latency", "Simpler design"], a: 1, why: "The whole chain slows to the slowest stage rather than silently discarding samples. The cost is that the slowest stage dictates the system rate and that stalls propagate. Where data loss is acceptable, dropping is simpler and keeps the rest of the chain running." },

// ------------------------------------------------------------- rtl-axi
{ t: "rtl-axi", d: 2, q: "What is tlast for on AXI-Stream?", o: ["Flow control", "Marking the final beat of a packet or frame", "Indicating an error", "Signalling which is the last byte enable"], a: 1, why: "The sink then knows where a burst ends. Without it a stream is an unbounded sequence with no structure. Getting tlast wrong is the most common cause of a downstream block, such as a DMA, hanging waiting for an end that never arrives." },
{ t: "rtl-axi", d: 2, q: "Your block needs CPU-configurable coefficients and a high-rate sample pipeline. What is the clean architecture?", o: ["One AXI4 memory-mapped interface used for both of the jobs", "AXI4-Lite for control and status, AXI-Stream for data", "AXI-Stream for both", "A custom bus for the data"], a: 1, why: "The two have completely different needs: control is low-rate and random-access, data is high-rate and sequential. Forcing one interface to do both makes both jobs worse." },
{ t: "rtl-axi", d: 2, q: "What is the strongest engineering argument for a standard bus over a hand-rolled one?", o: ["Better performance", "Interoperability and reuse of existing IP", "Lower resource usage", "It is simply required by all of the vendor tools"], a: 1, why: "IP blocks, verification components, interconnect and debug tooling all exist already. A custom bus means you also write the interconnect, the checkers, the monitors and the documentation. The standard's overhead is usually far less than that work." },
{ t: "rtl-axi", d: 2, q: "Why should event flags in a memory-mapped register block be write-one-to-clear?", o: ["It saves registers", "A read-modify-write would destroy a flag arriving in between", "It is faster to decode", "It simplifies the driver code quite considerably in practice"], a: 1, why: "Writing a 1 to a specific bit clears only that bit, and hardware can set others concurrently without a race. It is the standard interrupt-status pattern for exactly this reason." },
{ t: "rtl-axi", d: 2, q: "What distinguishes memory-mapped AXI from AXI-Stream?", o: ["Data width", "Memory-mapped carries addresses; stream is address-free", "Stream is slower", "Memory-mapped offers no burst support of any kind whatsoever"], a: 1, why: "Memory-mapped supports random access with separate read and write channels, while a stream is sequential. Streams suit continuous data such as samples or video, memory-mapped suits registers and memory. A DMA engine is the bridge between the two worlds." },
{ t: "rtl-axi", d: 3, q: "Why does AXI separate its read and write address channels from its data channels?", o: ["To reduce wire count", "So addresses can be issued ahead of the data", "To simplify arbitration", "For crossing between clock domains"], a: 1, why: "That allows multiple outstanding transactions and pipelining. It is what lets AXI hide memory latency: several reads can be in flight at once. The cost is five channels to implement and verify rather than one." },
{ t: "rtl-axi", d: 3, q: "What is tkeep for, and how does it differ from tstrb?", o: ["They are identical", "tkeep marks which bytes are content", "tkeep is for errors", "tstrb is the one used for flow control"], a: 1, why: "tstrb distinguishes data bytes from position bytes. In practice most designs use tkeep alone, for null bytes at the end of a packet that does not fill the final beat. Ignoring it on a byte-oriented stream produces trailing garbage." },
{ t: "rtl-axi", d: 3, q: "Why does a register map generated from a single source description matter?", o: ["It is faster to write", "The RTL, the C header and the docs cannot drift apart", "It reduces gate count", "It enables formal verification of the entire design block"], a: 1, why: "Drift is the usual cause of a driver writing the wrong bit. Hand-maintaining three views of the same map guarantees they diverge. IP-XACT or SystemRDL generating all three from one file removes an entire class of integration bug." },

// -------------------------------------------------------- rtl-dspfpga
{ t: "rtl-dspfpga", d: 2, q: "100 MHz fabric clock, 50 kHz sample rate, 64-tap FIR. What is the natural architecture?", o: ["64 parallel multipliers", "A single time-multiplexed MAC", "Two multipliers with a small pipeline", "A systolic array of 64 stages"], a: 1, why: "2000 clock cycles are available per sample. 100 MHz over 50 kHz gives 2000 cycles per sample against 64 needed. Instantiating 64 multipliers wastes DSP slices that could serve other channels, so folding is the right trade." },
{ t: "rtl-dspfpga", d: 2, q: "Why is the transposed FIR form friendly to FPGA timing?", o: ["It uses considerably fewer multipliers than the direct form", "The adder chain is broken by a register between taps", "It needs less memory", "It has lower latency"], a: 1, why: "There is no long combinational path left. The direct form has an adder tree or a long chain summing all taps in one cycle. The transposed form's cost is that the input fans out to every multiplier, which needs pipelining on wide filters." },
{ t: "rtl-dspfpga", d: 2, q: "How should a 1024-sample delay line be implemented?", o: ["A shift register in fabric flip-flops", "A block RAM addressed as a circular buffer", "A chain of distributed RAM", "Registers with a multiplexer"], a: 1, why: "1024 flip-flops per bit of width is an enormous waste of fabric. A block RAM with read and write pointers costs one primitive and leaves the flip-flops for logic." },
{ t: "rtl-dspfpga", d: 2, q: "What is CORDIC's defining property?", o: ["It uses no multipliers, computing trig and vector rotations from shifts and adds", "It is faster than a lookup table", "It gives exact results", "It works only on angles"], a: 1, why: "It suits fabric precisely because shifts are free routing and adds are cheap. It costs one iteration per bit of precision, so the trade is latency against DSP slices." },
{ t: "rtl-dspfpga", d: 2, q: "What is the folding trade in an FPGA datapath?", o: ["Area against power", "Reusing one arithmetic unit over many cycles", "Latency against accuracy", "Clock speed traded off against arithmetic precision"], a: 1, why: "Less area, but throughput falls and control logic grows. It only works when the clock is much faster than the data rate. The extra address and state machine logic is the hidden cost, and it can exceed the savings on small operators." },
{ t: "rtl-dspfpga", d: 3, q: "What does systolic thinking mean in an FPGA DSP design?", o: ["Using a system clock", "Data flows through a chain of identical registered stages", "Sharing one bus between stages", "Synchronising the whole design to an external clock source"], a: 1, why: "The stages are locally connected, so routing stays short. It avoids the long global routes that kill timing in fabric. The transposed FIR and the systolic matrix multiply are both instances of the same principle." },
{ t: "rtl-dspfpga", d: 3, q: "Why does symmetry in a linear-phase FIR halve the multiplier count?", o: ["The coefficients are smaller", "Symmetric taps share a coefficient", "Half the taps are zero", "It uses a shorter delay line"], a: 1, why: "Pre-add the two samples, then multiply once. DSP slices even have a dedicated pre-adder for exactly this. It is one of the highest-value optimisations available on a long filter, and it costs nothing in response." },
{ t: "rtl-dspfpga", d: 3, q: "Why does an FPGA often beat a DSP processor for multichannel filtering?", o: ["Higher clock speed", "Genuine parallelism across hundreds of DSP slices", "Noticeably better arithmetic precision all the way through", "Lower latency memory"], a: 1, why: "Throughput scales with resources rather than with clock rate. A DSP core runs at a much higher clock but processes one or a few MACs per cycle. The FPGA wins on aggregate throughput and deterministic latency, and loses on flexibility and development time." },

// ------------------------------------------------------------- rtl-soc
{ t: "rtl-soc", d: 2, q: "In a Zynq-style motion controller, why does the current loop belong in fabric?", o: ["It uses less power", "It needs deterministic microsecond-scale timing", "The CPU is simply not able to do the arithmetic at all", "Fabric has better ADC access"], a: 1, why: "A processor with interrupts and caches cannot guarantee it. The split heuristic is hard deterministic timing and high data rates in fabric, decisions and connectivity in software. Position and trajectory planning sit comfortably on the CPU." },
{ t: "rtl-soc", d: 2, q: "The CPU reads a DMA buffer and finds stale data although the transfer completed. What is the classic cause?", o: ["A DMA configuration error somewhere in the setup code", "The cache: the CPU is reading a stale cached copy", "The interrupt fired early", "The buffer is misaligned"], a: 1, why: "The cached copy predates the DMA write. You must invalidate the cache range before reading a DMA-filled buffer, and clean it after filling a buffer for DMA to send. Non-cacheable buffers avoid it at a performance cost." },
{ t: "rtl-soc", d: 2, q: "What is the right interrupt granularity for a sampled datapath?", o: ["One interrupt for every single sample", "One per block or buffer, with DMA moving samples", "One per second", "Polling instead"], a: 1, why: "Per-sample interrupts at any real rate spend all the CPU time in entry and exit overhead. DMA plus a half-buffer and full-buffer interrupt is the standard pattern." },
{ t: "rtl-soc", d: 2, q: "Why generate the register map RTL and the C header from one shared source?", o: ["It is noticeably faster to compile the whole design", "Hand-maintaining both guarantees they disagree", "It reduces fabric usage", "It is required by AXI"], a: 1, why: "The resulting driver bug is hard to find. The failure looks like a hardware fault: the driver writes a bit that moved. Generating both, plus the documentation, from one description removes the possibility." },
{ t: "rtl-soc", d: 2, q: "What is a sensible bring-up order for an SoC design?", o: ["Full system, then debug", "Clocks and reset, then boot and a UART, then peripherals", "The fabric first, and only then the processor and its software", "DMA first"], a: 1, why: "Then DMA, and only then the full datapath. Each step gives you a working observation point for the next. Without a UART or a debug link early, every later failure is silent and you have nothing to instrument with." },
{ t: "rtl-soc", d: 3, q: "Why is a status register read a poor way to detect completion of a fabric operation?", o: ["It is too slow", "Polling costs CPU time and its latency is unbounded", "Registers simply cannot be read reliably while running", "It requires a lock"], a: 1, why: "An interrupt or a DMA completion signal is better for anything with a deadline. Polling is fine for slow, rare operations and for bring-up. For a repeating datapath it wastes the processor and couples your response time to the scheduler." },
{ t: "rtl-soc", d: 3, q: "What does a memory barrier do in a driver writing to fabric registers?", o: ["Flushes the cache", "Prevents the processor or compiler reordering accesses", "Disables interrupts", "It synchronises the two clock domains safely with each other"], a: 1, why: "A configuration write then really does precede the start command. Write buffers and out-of-order execution can reorder device accesses that must be ordered. volatile stops the compiler reordering but not the hardware, which is why both are needed." },
{ t: "rtl-soc", d: 3, q: "Why does the fabric-to-processor interrupt path need care about level versus edge?", o: ["Edge is always faster", "An edge interrupt can be missed; a level one re-fires", "Level-triggered interrupts are simply not supported at all", "Edge interrupts cannot be shared"], a: 1, why: "An edge can be missed if the pulse is too short or arrives while masked, and a level interrupt must be cleared in fabric. Both failure modes are common in bring-up: the missed interrupt looks like a dead datapath, and the uncleared level interrupt looks like a hung processor. Getting the clear path right is part of the register map design." },

// ------------------------------------------------------ rtl-constraints
{ t: "rtl-constraints", d: 2, q: "An internal clock divider flop feeds logic with no create_generated_clock. What follows?", o: ["The tool infers it automatically", "That logic is effectively unconstrained", "The design will not synthesise", "It is constrained by the source clock"], a: 1, why: "Timing is never checked on it, and the design may fail silently in hardware. Unconstrained paths are reported as met because they are not analysed at all. Dividing a clock in fabric also has other problems, which is why a clock enable or a clocking primitive is usually preferred." },
{ t: "rtl-constraints", d: 2, q: "set_input_delay 4 on a 10 ns clock means your internal logic has how long?", o: ["10 ns", "6 ns", "4 ns", "14 ns"], a: 1, why: "The external world consumes 4 ns of the period before the data arrives at the pin, leaving 6 ns for the path to the capturing flop. Getting the sign or reference clock wrong here silently shifts the whole budget." },
{ t: "rtl-constraints", d: 2, q: "What is a legitimate use of set_false_path?", o: ["Any path that fails timing", "A genuinely asynchronous crossing already synchronised", "Paths through DSP slices", "Slow paths that you are planning to go back and fix later"], a: 1, why: "Or a path that can never be active. It removes the path from analysis entirely, so misusing it hides a real violation. A path that is simply slow wants a multicycle constraint or pipelining, not a false path." },
{ t: "rtl-constraints", d: 2, q: "Why do unconstrained paths deserve a dedicated report at sign-off?", o: ["They slow down the tool", "They are never analysed, so they show as no violation", "They consume a good deal of extra fabric resources as well", "They cannot be routed"], a: 1, why: "They are the most likely cause of a board that fails intermittently. A clean timing report proves nothing if half the design was not in it. check_timing and an unconstrained-path report are what turn 'met' into a meaningful statement." },
{ t: "rtl-constraints", d: 2, q: "What must be constrained before anything else?", o: ["I/O delays", "The clocks: every primary and generated clock", "False paths", "The multicycle paths in the design"], a: 1, why: "Every other constraint is expressed relative to a clock, so an undefined clock leaves everything it touches unanalysed. It is the first thing to check when timing looks implausibly good." },
{ t: "rtl-constraints", d: 3, q: "When is set_multicycle_path appropriate?", o: ["When a path fails its timing by only a very small margin", "When the design genuinely allows several clock cycles", "For all asynchronous paths", "To speed up compilation"], a: 1, why: "Such as behind an enable that is asserted every fourth cycle. It must reflect real behaviour, and both setup and hold need consideration, because relaxing setup without adjusting hold can create a hold violation. Applying it to make a report pass is how a design fails in the lab." },
{ t: "rtl-constraints", d: 3, q: "Why does set_clock_groups -asynchronous differ from a blanket false path?", o: ["It is the same", "It declares whole clock domains mutually asynchronous", "It applies only to the generated clocks within a design", "It affects placement"], a: 1, why: "That is more concise and less error-prone than enumerating paths, and it covers both directions. Enumerating individual false paths between two domains is easy to do incompletely. Declaring the groups covers everything, including paths added later." },
{ t: "rtl-constraints", d: 3, q: "What does clock uncertainty in a constraint represent?", o: ["The tolerance on the clock frequency", "Jitter and skew margin subtracted from the period", "The setup time of the flop", "The routing delay"], a: 1, why: "The analysis is then not optimistic. Tools set a default from the PLL and clock tree, and you can add margin for board-level jitter. Setting it to zero to make timing close is self-deception, since the physical uncertainty does not go away." },

// ---------------------------------------------------- rtl-lint-formal
{ t: "rtl-lint-formal", d: 2, q: "Why is a missing CDC synchroniser typically invisible in RTL simulation?", o: ["Simulators simply skip over the clock crossings entirely", "Simulation has no notion of metastability at all", "The testbench masks it", "It only fails at temperature"], a: 1, why: "The signal just takes its new value, so the failure only appears in silicon. Metastability is an analogue phenomenon of setup and hold violation, and the RTL event model has no way to express it. This is precisely why CDC checking is structural rather than dynamic." },
{ t: "rtl-lint-formal", d: 2, q: "What is the essential difference between a formal proof and a passing simulation regression?", o: ["Formal is faster", "A proof covers all legal input sequences", "Formal needs no testbench", "Simulation is more accurate"], a: 1, why: "Simulation covers only the sequences you actually ran. A regression that passes says nothing about the case you did not think of, which is where the bugs live. Formal either proves the property, gives a counterexample, or reports that it is inconclusive." },
{ t: "rtl-lint-formal", d: 2, q: "Why does lint matter more when moving from VHDL to Verilog?", o: ["Verilog has more features", "Verilog is far more permissive about types", "VHDL tools have no lint", "Verilog synthesises rather differently from VHDL"], a: 1, why: "Implicit nets, width mismatches and truncation are legal and silent, where VHDL's strong typing would reject them. A typo in a signal name creates a new one-bit wire rather than an error. Lint restores the class of checking that the language does not do for you." },
{ t: "rtl-lint-formal", d: 2, q: "What is the everyday role of logical equivalence checking?", o: ["Proving the design meets the spec", "Confirming the netlist is functionally identical to the RTL", "Checking timing", "Comparing the performance of two different designs against each other"], a: 1, why: "That covers the netlist after synthesis, or after a manual edit. It catches synthesis pragmas doing something unexpected and post-synthesis ECOs going wrong. It says nothing about whether the RTL itself is correct." },
{ t: "rtl-lint-formal", d: 2, q: "Where does formal beat simulation most concretely?", o: ["Full-chip system tests", "Bounded control logic: arbiters, FIFOs, protocol interfaces", "Analogue interfaces", "Performance measurement taken across the whole of a large design"], a: 1, why: "Also FSM deadlock, where the state space is large but the property is simple. An arbiter's fairness property over all input sequences is impossible to cover by simulation and routine for formal. It scales badly on wide datapaths, which is where simulation remains the tool." },
{ t: "rtl-lint-formal", d: 3, q: "What does an inconclusive formal result mean?", o: ["The property is false", "The tool could not prove or disprove it in its bounds", "The design has a bug", "The property itself must have been malformed in some way"], a: 1, why: "You have no information either way. It is the most misread result in formal verification: a green summary line may hide bounded proofs that reached only a few cycles deep. The proof depth has to be reported alongside the result." },
{ t: "rtl-lint-formal", d: 3, q: "Why do assumptions in a formal setup need review as carefully as the properties?", o: ["They slow the tool", "It can make a property vacuously true", "They affect coverage only", "They are optional"], a: 1, why: "An over-constraining assumption excludes the very inputs that would break it. Assume the input is never zero and you have proved nothing about zero. Formal tools provide vacuity and reachability checks precisely because this failure is easy and silent." },
{ t: "rtl-lint-formal", d: 3, q: "What does a CDC tool check for beyond the presence of synchronisers?", o: ["Timing closure", "Convergence and reconvergence of separately crossed bits", "The relationship between the two clock frequencies involved", "Power consumption"], a: 1, why: "Bits crossing separately then recombining lose their relationship even with correct synchronisers. Two-flop synchronisers on each bit of a bus is a classic wrong answer, because the bits arrive on different cycles. Gray coding or a handshake preserves the relationship, and that is what the tool is looking for." },

// ------------------------------------------------------------ rtl-flow
{ t: "rtl-flow", d: 2, q: "Integration simulation reveals a bug inside a module whose own testbench passed. What is best practice?", o: ["Fix it in the integration testbench rather than lower down", "Add a case to the module's testbench that reproduces it", "Fix it in the RTL and move on", "Disable the module's testbench"], a: 1, why: "Then fix it, so the gap in coverage is closed permanently. The bug found the hole in the unit test, so the fix should include the test that would have caught it. Otherwise the same class of bug returns and the unit testbench keeps giving false confidence." },
{ t: "rtl-flow", d: 2, q: "In the timing-closure loop, what is the first remedy for a failing path?", o: ["Raise the effort level", "Look at the path first, before changing anything", "Add a good many more pipeline stages more or less everywhere", "Lower the clock frequency"], a: 1, why: "Is it really needed, is it unconstrained or wrongly constrained, and does the RTL have too much logic between registers. Tool effort and floorplanning are late-stage remedies with small returns. Most failing paths are an RTL structure problem or a constraint problem, and both are cheaper to fix." },
{ t: "rtl-flow", d: 2, q: "Why embed the git hash in a readable version register?", o: ["For licensing", "So a board in the lab can tell you what built its bitstream", "To detect tampering", "To speed up the bring-up process in the laboratory"], a: 1, why: "That includes whether the tree was dirty. Bitstreams are easy to confuse and impossible to inspect. It is the same reasoning as build info in firmware, and it saves the whole class of debugging a version you were not actually running." },
{ t: "rtl-flow", d: 2, q: "What is the main purpose of freezing interface contracts before writing module internals?", o: ["To satisfy the project's own internal documentation requirements", "So modules can be developed and unit-tested in parallel", "To speed up synthesis", "To fix timing early"], a: 1, why: "They still connect at integration. Interfaces are where integration fails, and changing one late invalidates every testbench that used it. Signal names, widths, handshake and reset behaviour all belong in the contract." },
{ t: "rtl-flow", d: 2, q: "Why write the spec and block diagram before RTL?", o: ["It is required by the process standards", "It forces rates and interfaces to be decided early", "It helps documentation later", "It improves timing"], a: 1, why: "They are decided while they are still cheap to change. Discovering at integration that two blocks assumed different sample rates costs far more than the afternoon the diagram takes. It is also what makes the module boundaries testable." },
{ t: "rtl-flow", d: 3, q: "What is an ILA good for, and what is its main limitation?", o: ["Full visibility with no cost", "Capturing internal signals in the running design", "Replacing the simulation step with it entirely instead", "Measuring power"], a: 1, why: "It consumes fabric and block RAM, and can itself change timing. The capture depth is limited by block RAM, so triggering is what makes it useful. It is also worth remembering that inserting one can shift a marginal timing path and mask the fault you are chasing." },
{ t: "rtl-flow", d: 3, q: "Why version bitstreams as build artefacts rather than rebuilding on demand?", o: ["Builds are slow", "Synthesis and place-and-route are not reproducible", "To save a considerable amount of disk space", "Tools require it"], a: 1, why: "Across tool versions, so the only way to get an exact bitstream back is to have kept it. Even the same tool version can differ with a different seed or host. Keeping the bitstream alongside its source hash and tool version is the FPGA equivalent of archiving the ELF." },
{ t: "rtl-flow", d: 3, q: "Why run module-level testbenches before integration simulation rather than only at the top level?", o: ["Top-level simulation is too slow", "A failure at module level has a small candidate set", "Integration testing then becomes entirely unnecessary", "Tools require it"], a: 1, why: "A top-level failure could originate anywhere, and module simulation is fast enough to run on every change. It is the same argument as unit testing in software. Integration still finds the interface and timing assumptions no module test can, so both are needed rather than either alone." }

]);
