/* Practical code questions for the Embedded C track.
   Three flavours, tagged in the question text:
     READ THIS CODE  - what does it do / what is the value
     SPOT THE BUG    - what is wrong with it
     WRITE IT        - which implementation is correct
   Topic ids match lesson ids, so the "Read the lesson" panel works as normal. */

BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// ============================================================ READ THIS CODE

{ t: "emb-types", d: 2, q: "<span class='qtag'>Read this code</span>What does this print?<pre>uint8_t a = 0xFF;\nprintf(\"%08lX\\n\", (unsigned long)~a);</pre>", o: ["000000FF", "00000000", "FFFFFF00", "0000FF00"], a: 2, why: "<p>a is promoted to int before ~ is applied. So the operand is 0x000000FF, and the complement is 0xFFFFFF00.</p><p>People expect 0x00 because they read <code>~a</code> as an 8-bit operation. There is no such thing: every operator promotes anything narrower than int first.</p><p>To get byte behaviour you must mask back down yourself: <code>(uint8_t)(~a)</code> or <code>(~a &amp; 0xFF)</code>, both of which give 0x00.</p>" },

{ t: "emb-types", d: 3, q: "<span class='qtag'>Read this code</span>What is the value of n?<pre>uint8_t  x = 200, y = 100;\nint      n = (x + y &gt; 255);</pre>", o: ["0", "1", "Undefined", "Implementation-defined"], a: 1, why: "<p>Both operands promote to int, so the addition happens in int arithmetic and yields 300. 300 &gt; 255 is true, so n is 1.</p><p>The trap is that people write exactly this expression as an overflow check, expecting the sum to wrap to 44 and the test to be false. It never wraps, because the arithmetic was never 8-bit.</p><p>Wrapping only happens at the point of storing into a narrow type: <code>uint8_t z = x + y;</code> gives 44. So whether you see wrapping depends on where the result lands, not on the operand types.</p>" },

{ t: "emb-ub", d: 3, q: "<span class='qtag'>Read this code</span>start is 0xFFFFFF00 and the tick counter has since wrapped to 200. What does elapsed hold?<pre>uint32_t start   = 0xFFFFFF00;\nuint32_t now     = 200;\nuint32_t elapsed = now - start;</pre>", o: ["A huge number, about 4.29 billion", "456", "Undefined behaviour", "0"], a: 1, why: "<p>200 - 0xFFFFFF00 in unsigned 32-bit arithmetic is 200 + 256 = 456, which is the true number of ticks elapsed across the wrap.</p><p>It works because unsigned overflow is <b>defined</b> to wrap modulo 2^32. The subtraction is modular and the difference comes out correct.</p><p>This is why <code>(now - start) &lt; timeout</code> is the safe idiom and <code>now &lt; (start + timeout)</code> is not: the addition form overflows the comparison value and the test becomes false immediately. Both variables must be unsigned, because signed overflow is undefined.</p>" },

{ t: "emb-bits", d: 2, q: "<span class='qtag'>Read this code</span>status is 0x04 and READY is (1u &lt;&lt; 2). Does the body run?<pre>if (status &amp; READY == 0) {\n    handle_not_ready();\n}</pre>", o: ["Yes, because bit 2 is set", "No, and it can never run for any value of status", "Yes, but only when status is zero", "It fails to compile"], a: 1, why: "<p>== binds tighter than &amp;, so this parses as <code>status &amp; (READY == 0)</code>. READY is 4, so <code>READY == 0</code> is 0, and <code>status &amp; 0</code> is 0 for every possible status.</p><p>The body is unreachable, silently, for all inputs. Nothing about the code looks wrong at a glance.</p><p>Ritchie later called this precedence a mistake, inherited from B where &amp; and &amp;&amp; were not distinguished. GCC warns under -Wall (-Wparentheses). The habit that removes it is to parenthesise every bitwise operation without pausing to decide whether this one needs it.</p>" },

{ t: "emb-structs", d: 2, q: "<span class='qtag'>Read this code</span>On 32-bit ARM, what is sizeof(sample_t)?<pre>typedef struct {\n    uint8_t  id;\n    uint32_t timestamp;\n    uint16_t value;\n} sample_t;</pre>", o: ["7", "8", "12", "16"], a: 2, why: "<p>Walk the offsets. id at 0. timestamp needs 4-byte alignment, so three padding bytes follow and it lands at 4. value lands at 8. The struct's own alignment is 4, so the size must round up to a multiple of 4, adding two bytes of tail padding.</p><p>Total 12, against 7 bytes of actual members. Nearly half is padding.</p><p>Reordering largest first gives timestamp at 0, value at 4, id at 6, one tail byte, total 8. The tail padding exists so that in an array, every element's timestamp stays 4-byte aligned.</p>" },

{ t: "emb-pointers", d: 2, q: "<span class='qtag'>Read this code</span>How many bytes does this clear on a 32-bit target?<pre>void clear(uint8_t buf[64])\n{\n    memset(buf, 0, sizeof(buf));\n}</pre>", o: ["64", "4", "0", "Undefined"], a: 1, why: "<p>An array parameter is always adjusted to a pointer. <code>uint8_t buf[64]</code> as a parameter is identical to <code>uint8_t *buf</code>, and the 64 is documentation the compiler discards entirely.</p><p>So sizeof(buf) is the size of a pointer, 4 on a 32-bit target, and the function clears four bytes while reading as though it clears sixty-four.</p><p>GCC catches this exact pattern under -Wall as -Wsizeof-pointer-memaccess. The general fix is the rule that any function writing into a caller's buffer must take an explicit length, because the size information is genuinely gone at the boundary.</p>" },

{ t: "emb-preproc", d: 2, q: "<span class='qtag'>Read this code</span>What does x hold?<pre>#define SQUARE(v) v * v\n\nint x = SQUARE(2 + 3);</pre>", o: ["25", "11", "10", "13"], a: 1, why: "<p>The preprocessor substitutes text with no understanding of precedence, so the expansion is <code>2 + 3 * 2 + 3</code>. Multiplication binds tighter, giving 2 + 6 + 3 = 11.</p><p>Two fixes are needed and both matter: parenthesise each parameter, and parenthesise the whole body. <code>((v) * (v))</code> expands to <code>((2 + 3) * (2 + 3))</code> and gives 25.</p><p>Apply both mechanically rather than deciding case by case, because the one you skip is the one that bites. Better still, use <code>static inline int square(int v)</code>, which cannot have this problem at all.</p>" },

{ t: "emb-preproc", d: 3, q: "<span class='qtag'>Read this code</span>i starts at 5. What is i afterwards, and what does x hold?<pre>#define MAX(a, b) ((a) &gt; (b) ? (a) : (b))\n\nint i = 5, j = 4;\nint x = MAX(i++, j);</pre>", o: ["i is 6, x is 5", "i is 7, x is 6", "i is 6, x is 6", "Undefined behaviour"], a: 1, why: "<p>The argument text appears twice in the body, so the expansion is <code>((i++) &gt; (j) ? (i++) : (j))</code>.</p><p>The comparison evaluates i++ once: it yields 5, compares 5 &gt; 4 as true, and leaves i at 6. The true branch then evaluates i++ again: it yields 6 and leaves i at 7.</p><p>So x gets 6, which is not the value that was compared, and i has been incremented twice. Any macro using a parameter more than once is unsafe with any argument that has a side effect, and the answer is an inline function.</p>" },

{ t: "emb-preproc", d: 3, q: "<span class='qtag'>Read this code</span>UART_DR is a read-to-clear status register. Why is this worse than the i++ version of the same bug?<pre>#define MAX(a, b) ((a) &gt; (b) ? (a) : (b))\n\nint level = MAX(read_status(), 10);</pre>", o: ["It is not worse", "The register is read twice, so the first read clears flags the second never sees", "It is slower", "It allocates memory"], a: 1, why: "<p>The double evaluation reaches hardware rather than a local variable. Two calls to read_status() are two bus transactions against the peripheral.</p><p>On a read-to-clear register the first read clears the flags, so the second returns something different and the event is gone. On a FIFO data register you pop two bytes and throw one away.</p><p>The i++ version corrupts a variable you can inspect. This version silently destroys hardware events, and nothing in the call site suggests a macro is responsible. It is the strongest single argument for preferring inline functions.</p>" },

{ t: "emb-memory", d: 2, q: "<span class='qtag'>Read this code</span>Which sections do these four occupy, in order?<pre>uint8_t       a[1024];\nuint8_t       b[1024] = { 1 };\nconst uint8_t c[1024] = { 2 };\nstatic void f(void) { uint8_t d[1024]; (void)d; }</pre>", o: [".bss, .data, .rodata, stack", ".data, .bss, .text, heap", ".bss, .bss, .rodata, heap", ".data, .data, .rodata, stack"], a: 0, why: "<p>a is an uninitialised global: .bss, so 1 kB of RAM and no flash, because startup just zeroes the region.</p><p>b is initialised: .data, so 1 kB of flash for the initial image <b>and</b> 1 kB of RAM, with startup copying one to the other.</p><p>c is const: .rodata, so 1 kB of flash only and no RAM at all. That single keyword is the difference between costing RAM and not.</p><p>d is a non-static local: the stack, allocated on entry and released on return. On a 2 kB task stack, this one would overflow it.</p>" },

{ t: "emb-fixedpoint", d: 3, q: "<span class='qtag'>Read this code</span>Q is 16. Both inputs are valid Q16.16 values. What is wrong with the result?<pre>int32_t mul_q16(int32_t a, int32_t b)\n{\n    return (a * b) &gt;&gt; 16;\n}</pre>", o: ["Nothing", "The intermediate needs 64 bits: a * b overflows int32_t", "The shift should be 32", "The result should be unsigned"], a: 1, why: "<p>Two values with 16 fractional bits each produce 32 fractional bits, so the true product is Q32.32 and needs 64 bits to hold. Computing it in int32_t overflows, which for signed types is undefined behaviour.</p><p>The fix widens before multiplying: <code>(int32_t)(((int64_t)a * b) &gt;&gt; 16)</code>. Note the cast must be on an operand, not on the product, or the overflow has already happened.</p><p>Worth adding rounding too: <code>+ (1 &lt;&lt; 15)</code> before the shift, because truncation always biases towards negative infinity and that bias accumulates visibly in a filter or an integrator.</p>" },

{ t: "emb-serial", d: 2, q: "<span class='qtag'>Read this code</span>buf holds { 0x34, 0x12 } from a little-endian sensor. What does v hold, and is the code sound?<pre>uint8_t buf[2] = { 0x34, 0x12 };\nint16_t v = (int16_t)((uint16_t)buf[1] &lt;&lt; 8 | buf[0]);</pre>", o: ["0x1234, and the code is sound", "0x3412, and the code is sound", "0x1234, but it violates strict aliasing", "Undefined behaviour"], a: 0, why: "<p>buf[1] is the high byte, so 0x12 &lt;&lt; 8 gives 0x1200, ORed with 0x34 gives 0x1234. Correct.</p><p>The code is sound because it does three things right at once. It builds the value in unsigned arithmetic, so nothing goes out of range before the single cast at the end. It only ever reads bytes, so there is no alignment requirement. And it never accesses the buffer through a different pointer type, so strict aliasing is respected.</p><p>Compare with <code>*(int16_t *)buf</code>, which has all three faults and additionally depends on the CPU's byte order matching the sensor's.</p>" },

{ t: "emb-fsm", d: 2, q: "<span class='qtag'>Read this code</span>What does this state machine do when it receives EV_TIMEOUT while in ST_IDLE?<pre>switch (st) {\ncase ST_IDLE:\n    if (ev == EV_START) st = ST_RUN;\n    break;\ncase ST_RUN:\n    if (ev == EV_STOP)  st = ST_IDLE;\n    break;\n}</pre>", o: ["Faults", "Nothing at all, silently", "Returns to ST_IDLE", "Queues the event"], a: 1, why: "<p>ST_IDLE matches, the if is false, and break exits. The event is discarded with no record that it ever arrived.</p><p>Silence may well be the right behaviour here, but it is a decision nobody made and nobody wrote down. A reader cannot tell whether ignoring EV_TIMEOUT in ST_IDLE is intended or an omission.</p><p>Two things fix it. Be explicit per state about whether an unexpected event is ignored, logged or an error. And add a <code>default:</code> for the state itself, because reaching an unlisted state means either memory corruption or a state added without handling, and both should be loud.</p>" },

{ t: "emb-rtos", d: 2, q: "<span class='qtag'>Read this code</span>Assume the buffer is 2048 bytes elsewhere. What is the stack of this task, in bytes, under standard FreeRTOS?<pre>xTaskCreate(worker, \"worker\", 1024, NULL, 5, NULL);</pre>", o: ["1024", "4096", "2048", "512"], a: 1, why: "<p>Standard FreeRTOS xTaskCreate takes the depth in <b>words</b>, so 1024 words on a 32-bit part is 4096 bytes.</p><p>Some ports and wrappers take bytes instead, notably ESP-IDF's. Move code between them without noticing and a comfortable 4 kB stack silently becomes 1 kB.</p><p>Nothing warns you, and the failure is memory corruption in unrelated data, appearing only when a deep path runs. Always check the units in the port you are using, then confirm with uxTaskGetStackHighWaterMark under worst-case load.</p>" },

// ============================================================ SPOT THE BUG

{ t: "emb-volatile", d: 2, q: "<span class='qtag'>Spot the bug</span>This works at -O0 and hangs at -O2. Why?<pre>#define SR (*(uint32_t *)0x40004000)\n\nvoid wait_ready(void)\n{\n    while (!(SR &amp; 0x01)) { }\n}</pre>", o: ["The address is wrong", "SR is not volatile, so the read is hoisted out of the loop", "It needs a memory barrier", "The mask should be 0x02"], a: 1, why: "<p>At -O2 the compiler analyses the loop body, sees nothing that could change the memory being read, and concludes the value is loop-invariant. It reads once and emits an unconditional branch to itself.</p><p>Debug builds skip that analysis, which is why the same source works at -O0. Debug-works-release-hangs is the signature of this fault and of undefined behaviour generally.</p><p>The fix is <code>#define SR (*(volatile uint32_t *)0x40004000)</code>. A barrier would not help: the problem is not ordering, it is that the read never happens again. And this loop should also have a timeout, because an unbounded wait is a hang waiting for a trigger.</p>" },

{ t: "emb-volatile", d: 3, q: "<span class='qtag'>Spot the bug</span>reg is correctly declared volatile. An interrupt handler also sets bits in it. What is still wrong?<pre>reg |= (1u &lt;&lt; 3);</pre>", o: ["Nothing, volatile makes it atomic", "It is read, modify, write: an interrupt between the read and the write loses that handler's change", "The shift should be 1", "volatile prevents the write"], a: 1, why: "<p>volatile guarantees the accesses happen and are not reordered with respect to each other. It says nothing about them being indivisible.</p><p>The line compiles to a load, an OR and a store. If the handler fires between the load and the store and sets a different bit, your stale value is written back over it and that bit is silently lost.</p><p>Three fixes, in order of preference: use hardware set and clear registers if the peripheral has them, so no read is needed at all; use an atomic operation; or take a critical section. Note that a critical section is the only one of these that also works when the shared thing is a plain variable rather than a register.</p>" },

{ t: "emb-bits", d: 3, q: "<span class='qtag'>Spot the bug</span>ICR is a write-1-to-clear interrupt status register. What does this line actually do?<pre>ICR |= (1u &lt;&lt; 3);</pre>", o: ["Clears interrupt 3 only", "Clears interrupt 3 and every other interrupt that was pending", "Sets interrupt 3", "Nothing"], a: 1, why: "<p>The read picks up the register's current contents, including every flag that has latched. The OR adds bit 3. The write puts that whole value back.</p><p>On a write-1-to-clear register, writing a 1 clears that bit. So every flag that was set gets cleared, and you have silently acknowledged interrupts and errors that nothing handled.</p><p>The correct form is <code>ICR = (1u &lt;&lt; 3);</code> with no read at all. The wider rule: read-modify-write is wrong on any register whose read has a side effect, which the datasheet's access column tells you. Read-to-clear registers and FIFO data registers are the other two cases.</p>" },

{ t: "emb-bits", d: 2, q: "<span class='qtag'>Spot the bug</span>Bits 6:4 are a 3-bit mode field. What is wrong here?<pre>reg |= (mode &lt;&lt; 4);</pre>", o: ["Nothing", "It can only set bits, never clear them, and an out-of-range mode spills into bit 7", "The shift should be 6", "It needs to be volatile"], a: 1, why: "<p>Two faults. OR can only turn bits on, so a field currently holding 7 stays 7 no matter what mode you pass. You need clear-then-set: <code>reg = (reg &amp; ~(7u &lt;&lt; 4)) | ((mode &amp; 7u) &lt;&lt; 4);</code></p><p>And there is no mask on mode. Pass 9 and <code>9 &lt;&lt; 4</code> is 0x90, which sets bit 7 as well. Bit 7 belongs to something else and you have just changed it.</p><p>The mask matters because it confines a bad argument to a wrong value in the right place, rather than corruption somewhere unrelated. Where an interface can be misused, prefer making the misuse harmless over documenting that it must not happen.</p>" },

{ t: "emb-isr", d: 2, q: "<span class='qtag'>Spot the bug</span>The peripheral also has an overrun flag, enabled and currently latched. What happens?<pre>void uart_isr(void)\n{\n    if (SR &amp; SR_RXNE) {\n        rx_buf[head++] = DR;\n    }\n}</pre>", o: ["Data is lost but the system continues", "The interrupt re-asserts immediately and forever, so nothing else runs", "The peripheral resets itself", "The overrun flag clears on the next read"], a: 1, why: "<p>The peripheral asserts its interrupt line while <b>any</b> enabled condition is pending, and the overrun flag is one such condition.</p><p>Your handler runs, tests only RXNE, finds it clear, does nothing and returns. The line is still asserted, so the handler is entered again immediately. The CPU never returns to any other work.</p><p>What makes this confusing is that it is not a hang in your code: the handler is executing continuously and correctly. Always handle or at least clear every enabled error condition, and count them, so a marginal link is visible rather than silent. There is a second bug here too: head is never bounded against the buffer size.</p>" },

{ t: "emb-isr", d: 3, q: "<span class='qtag'>Spot the bug</span>This function is called from a task and also from an ISR. What is the problem?<pre>const char *next_field(char *line)\n{\n    static char *pos;\n    if (line) pos = line;\n    ...\n    return pos;\n}</pre>", o: ["static is not allowed in C", "The static local is shared, so the ISR corrupts the state the interrupted call was using", "It should return char *", "It uses too much stack"], a: 1, why: "<p>A function with only automatic locals is safe under concurrency because every call gets its own stack frame. A static local is shared by every caller in the program.</p><p>So if the interrupt preempts this function partway through and calls it again, the second call overwrites pos, and when the first resumes it continues from the wrong place.</p><p>It does not take two tasks: one task plus one interrupt is enough. This is exactly why strtok, rand and printf are unsafe in an ISR, and why reentrant variants such as strtok_r exist, taking the state as a caller-supplied parameter instead.</p>" },

{ t: "emb-concurrency", d: 3, q: "<span class='qtag'>Spot the bug</span>rx_len and rx_buf are written by the UART ISR. Name both faults.<pre>int get_message(uint8_t *dst)\n{\n    int n = rx_len;\n    memcpy(dst, rx_buf, n);\n    rx_len = 0;\n    return n;\n}</pre>", o: ["Only that rx_len needs volatile", "The ISR can write into rx_buf during the memcpy, and bytes arriving after n was read are destroyed by the zeroing", "Only that dst has no length parameter", "Nothing, it is correct"], a: 1, why: "<p>Two distinct faults in three lines. The ISR can fire during the memcpy and write into the buffer being copied, so the message tears: part old, part new. And any bytes that arrive after rx_len was read into n are destroyed when rx_len is unconditionally set to zero.</p><p>Marking rx_len volatile fixes neither, because the problem is that there are two writers and the sequence is not atomic.</p><p>The fixes are a critical section around all three lines, or restructuring so each side owns its own index, which is what a single-producer single-consumer ring buffer does. There is a third fault worth naming: dst has no length, so a caller with a smaller buffer gets silently overrun.</p>" },

{ t: "emb-concurrency", d: 2, q: "<span class='qtag'>Spot the bug</span>Two FreeRTOS tasks call this for two different devices, and each gets the other's data. The I2C driver itself is thread-safe. Why?<pre>Wire.beginTransmission(addr);\nWire.write(reg);\nWire.endTransmission(false);\nWire.requestFrom(addr, len);</pre>", o: ["The two devices share an address", "Wire holds one static transmit buffer, so the tasks overwrite each other in RAM before anything reaches the wire", "The bus is too slow", "endTransmission(false) is wrong"], a: 1, why: "<p>Wire keeps a single static transmit buffer per instance, not one per device. beginTransmission resets it, write fills it, endTransmission sends it.</p><p>If task A calls beginTransmission and write, then task B calls beginTransmission before A reaches endTransmission, B has reset the buffer underneath A. A then transmits B's bytes to A's device.</p><p>The corruption happens entirely in library memory before a bit reaches the bus, which is why a logic analyser shows perfectly valid, correctly addressed transactions carrying the wrong payload. Recognising that observation is what identifies this class of fault. The fix is a mutex around the whole sequence, not around each call.</p>" },

{ t: "emb-pointers", d: 2, q: "<span class='qtag'>Spot the bug</span>Why does this appear to work in testing and fail later?<pre>const char *status_text(int code)\n{\n    char buf[32];\n    snprintf(buf, sizeof buf, \"code %d\", code);\n    return buf;\n}</pre>", o: ["snprintf is unsafe", "It returns a pointer to a stack frame that no longer exists", "sizeof buf is wrong", "It should be static const"], a: 1, why: "<p>When the function returns, the stack pointer moves back but nothing erases the bytes. If the caller reads them before anything pushes a new frame over that region, the text is still intact.</p><p>So it works in a simple test and fails later, when another call, a different optimisation level, or an interrupt reuses the frame. On a microcontroller an interrupt uses the same stack and can land there at a moment you cannot predict.</p><p>It is undefined behaviour, so both working and not working are permitted and neither is a guarantee. Fixes: take a caller-supplied buffer and a length, return a string literal, or use a static buffer with the reentrancy caveat that implies.</p>" },

{ t: "emb-pointers", d: 3, q: "<span class='qtag'>Spot the bug</span>The task reads its parameter as an int. What is wrong?<pre>void start_sensor(void)\n{\n    int channel = 3;\n    xTaskCreate(sensor_task, \"sensor\", 2048, &amp;channel, 5, NULL);\n}</pre>", o: ["The stack size is too small", "&amp;channel points into a stack frame that is released when start_sensor returns", "xTaskCreate cannot take a pointer", "channel should be volatile"], a: 1, why: "<p>The address refers to start_sensor's stack frame, which is released the moment it returns. The task then reads memory belonging to whatever ran next.</p><p>It very often appears to work, because a newly created task at priority 5 may run immediately and copy the value before start_sensor returns. Change a priority, add a line after the create call, or run on a different scheduler configuration, and it breaks.</p><p>Fixes: make channel static, pass the value itself cast through the void pointer if it fits, or allocate it and have the task free it. This is the classic RTOS beginner bug and worth being able to spot instantly.</p>" },

{ t: "emb-preproc", d: 2, q: "<span class='qtag'>Spot the bug</span>The error is reported at the if, not at the define. Why?<pre>#define ERR_BASE = 0x8000;\n\nif (rc == ERR_BASE) { ... }</pre>", o: ["The value is too large", "A define is text substitution: it takes no equals sign and no semicolon", "It needs parentheses", "ERR_BASE must be an enum"], a: 1, why: "<p><code>#define NAME replacement</code> substitutes everything after the name. Here the replacement text is literally <code>= 0x8000;</code>.</p><p>So the if expands to <code>if (rc == = 0x8000;)</code>, which is a syntax error at the use site. The definition itself is perfectly legal preprocessor input, which is why the diagnostic points somewhere confusing.</p><p>The correct form is <code>#define ERR_BASE 0x8000</code>. Anything derived from it needs parentheses: <code>#define ERR_WRONG_PART (ERR_BASE + 1)</code>, otherwise <code>ERR_WRONG_PART * 2</code> expands to <code>0x8000 + 1 * 2</code>.</p>" },

{ t: "emb-preproc", d: 3, q: "<span class='qtag'>Spot the bug</span>This is in a header included by three .c files. Why does the count never reach 3?<pre>static int boot_count = 0;</pre>", o: ["static means it is not initialised", "Each translation unit gets its own private copy, so there are three separate counters", "It should be const", "Headers cannot hold variables"], a: 1, why: "<p>#include is a paste, so each of the three translation units gets its own definition, and static gives each one internal linkage. The result is three independent variables that happen to share a name.</p><p>The insidious part is that static <b>suppresses</b> the duplicate-symbol link error that would otherwise have caught this immediately. Remove it and the linker tells you at once.</p><p>To share one variable, put <code>extern int boot_count;</code> in the header and <code>int boot_count = 0;</code> in exactly one .c file. Better still, keep it static inside the one file that owns it and expose a function, so there is a single owner rather than a shared global.</p>" },

{ t: "emb-errors", d: 2, q: "<span class='qtag'>Spot the bug</span>What does the caller lose here?<pre>int sensor_read(sensor_t *s, int16_t *out)\n{\n    if (bus_read(s-&gt;io, REG_DATA, buf, 2) != 0)\n        return -1;\n    *out = (int16_t)(buf[1] &lt;&lt; 8 | buf[0]);\n    return 0;\n}</pre>", o: ["Nothing", "The bus layer's specific error is flattened, so a timeout and a NAK become indistinguishable", "The return type should be void", "out is not checked"], a: 1, why: "<p>bus_read knew something specific: the transfer timed out, or nothing acknowledged the address. Collapsing both to -1 destroys information that only existed at that point.</p><p>Those failures send an engineer to different places. A timeout points at wiring, pull-ups or a stuck slave. A NAK points at the wrong address or a part that is not fitted.</p><p>Propagate the callee's error unchanged unless you know something it did not: <code>int rc = bus_read(...); if (rc) return rc;</code>. Add your own code only where you have real context the lower layer lacked, such as a read that succeeded but returned the wrong chip ID. There is also a second fault: s and out are never validated, and this is an API boundary.</p>" },

{ t: "emb-drivers", d: 2, q: "<span class='qtag'>Spot the bug</span>The datasheet gives a maximum reset time of 5 ms. What is wrong with this?<pre>write_reg(dev, REG_SYS_TRIGGER, RST_BIT);\nvTaskDelay(pdMS_TO_TICKS(10));\nconfigure(dev);</pre>", o: ["10 ms is not long enough", "A maximum is not a duration: poll the self-clearing reset bit with a timeout instead", "vTaskDelay should be vTaskDelayUntil", "The reset bit is wrong"], a: 1, why: "<p>A maximum is a bound under specified conditions, not a wait to perform. Polling the bit the device clears when it is ready is faster in the normal case and correct in the abnormal one.</p><p>It survives the part being slower at temperature, the clock changing so the delay is not what it claims, and the tick rate making pdMS_TO_TICKS(10) round to something unexpected.</p><p>There is a second, structural fault: calling vTaskDelay puts a FreeRTOS dependency inside the driver. That is what the delay_ms function pointer in an injected transport is for. It also means a test can advance time instantly rather than really waiting several seconds per timeout test.</p>" },

{ t: "emb-dma", d: 3, q: "<span class='qtag'>Spot the bug</span>DMA fills buf, then the function processes it. Name the fault.<pre>void read_block(void)\n{\n    uint8_t buf[256];\n    dma_start(buf, sizeof buf);\n    while (!dma_done) { }\n    process(buf, sizeof buf);\n}\n</pre>", o: ["buf should be volatile", "dma_done needs volatile, and a stack buffer is the wrong place for a DMA target", "sizeof buf is wrong", "process should take a pointer"], a: 1, why: "<p>dma_done is polled in a loop with nothing in the body that could change it, so at -O2 the compiler hoists the read and the loop never exits. It needs volatile.</p><p>The buffer is the more interesting fault. It happens to survive here because the function waits, but any change that returns before completion leaves the controller writing into a stack frame that belongs to something else. DMA buffers belong in .bss, a static pool, or the heap.</p><p>Marking buf itself volatile is the wrong instinct: it fixes nothing here and forces every byte of process() into a separate load. On a part with a data cache you would also need an invalidate before reading, and cache-line alignment so the invalidate does not discard neighbouring variables.</p>" },

{ t: "emb-faults", d: 2, q: "<span class='qtag'>Spot the bug</span>Every task is deadlocked and the board never resets. Why not?<pre>void timer_cb(TimerHandle_t t)\n{\n    (void)t;\n    watchdog_feed();\n}</pre>", o: ["The timer period is too short", "The callback runs regardless of system health, so it reports health that does not exist", "watchdog_feed is not ISR-safe", "The timer needs a higher priority"], a: 1, why: "<p>The timer keeps firing whether or not any task is making progress. Deadlock every task in the system and this callback still runs, still feeds the watchdog, and the board never resets.</p><p>That is precisely the situation the watchdog was installed to catch, and this makes it invisible.</p><p>The correct pattern: each monitored task sets a flag when it completes a cycle, and a supervisor feeds the watchdog only when every flag is set, clearing them afterwards. Then feeding it is evidence that the system is genuinely working. The general rule is that any change making the watchdog less likely to fire is making it worse at its only job.</p>" },

{ t: "emb-defensive", d: 2, q: "<span class='qtag'>Spot the bug</span>verify() is never called. Why?<pre>if (hash_ok(a, b))\n    goto fail;\n    goto fail;\n\nverify(cert);\nfail:\n    return err;</pre>", o: ["hash_ok is inverted", "The second goto is outside the unbraced if, so it always executes", "goto cannot be used twice", "fail: is in the wrong place"], a: 1, why: "<p>The if has no braces, so it governs only the first statement. The second goto is unconditional, and control jumps to fail every time regardless of the hash result.</p><p>The indentation makes it read as though both lines are inside the if, which is exactly why it survived review.</p><p>This is Apple's goto fail bug, which shipped and skipped TLS signature verification. Two characters, a pair of braces, remove the entire class. -Wmisleading-indentation catches many instances but not all, so brace every body regardless of the flag.</p>" },

{ t: "emb-memory", d: 3, q: "<span class='qtag'>Spot the bug</span>This links cleanly, then the board crashes shortly after boot. Why?<pre>/* added to an existing project with 32 kB RAM */\nuint8_t scratch[8192];\n\n/* elsewhere, unchanged and previously working */\nxTaskCreate(worker, \"w\", 1024, NULL, 5, NULL);\n</pre>", o: ["scratch overflowed the RAM region", "scratch consumed 8 kB of .bss, shrinking the heap, so the task stack allocation now fails", "scratch landed in .text", "The linker script is wrong"], a: 1, why: "<p>The linker places .data and .bss and checks them against the declared RAM region. Whatever remains becomes the heap at run time, and nothing checks that.</p><p>So 8 kB of new .bss silently removes 8 kB of heap. xTaskCreate takes its 4 kB stack from the heap, that allocation now fails, and the return value is not checked, so the task simply does not exist.</p><p>The fact that it linked is the clue: had scratch genuinely overflowed the region you would have seen 'region RAM overflowed' at build time. The map file tells you where the RAM went, and checking every xTaskCreate return turns a mysterious crash into a clean diagnostic.</p>" },

{ t: "emb-flash", d: 3, q: "<span class='qtag'>Spot the bug</span>settings_save is called once a minute. Name both failures.<pre>void settings_save(const settings_t *s)\n{\n    flash_erase_sector(SETTINGS_SECTOR);\n    flash_write(SETTINGS_ADDR, s, sizeof *s);\n}</pre>", o: ["It is slow and uses RAM", "The sector wears out in weeks, and a power loss between erase and write loses everything", "It cannot be called from a task", "sizeof *s is wrong"], a: 1, why: "<p>Endurance is per sector, commonly 10,000 to 100,000 erase cycles. At one erase per minute you reach 100,000 in about ten weeks, and the product fails while the rest of the flash is untouched.</p><p>And there is an interval between the erase completing and the write completing in which neither the old settings nor the new ones exist. A power cut there loses the lot.</p><p>A log-structured store fixes both: append records and only erase when the sector fills, which multiplies life by the number of records per sector and leaves the previous record valid until compaction. Write the data before the validity marker, so a half-written record is invisible rather than corrupt. In practice use LittleFS or an NVS rather than writing this yourself.</p>" },

// ============================================================ WRITE IT

{ t: "emb-volatile", d: 2, q: "<span class='qtag'>Write it</span>Declare a pointer to a read-only 32-bit hardware register at 0x40021000, where the pointer itself never changes.", o: ["<pre>const uint32_t *reg =\n  (const uint32_t *)0x40021000;</pre>", "<pre>volatile uint32_t *reg =\n  (volatile uint32_t *)0x40021000;</pre>", "<pre>volatile const uint32_t * const reg =\n  (volatile const uint32_t *)0x40021000;</pre>", "<pre>uint32_t * const reg =\n  (uint32_t *)0x40021000;</pre>"], a: 2, why: "<p>Three qualifiers, each doing a separate job. <b>volatile</b> because the peripheral updates it without your involvement, so every read must be a real load. <b>const</b> left of the star because writing this register is forbidden. <b>const</b> right of the star because the pointer never points anywhere else.</p><p>Option 1 has no volatile, so the read can be optimised away entirely. Option 2 permits writes to a read-only register. Option 4 protects only the pointer and neither qualifies the pointee nor prevents the read being cached.</p><p>Note the cast must carry the same qualifiers as the target, or you get a diagnostic about discarding qualifiers. The reliable habit is to copy the type from the left of the equals sign and append a star.</p>" },

{ t: "emb-bits", d: 2, q: "<span class='qtag'>Write it</span>Bits 6:4 hold a 3-bit mode. Set the field to mode without disturbing any other bit, and without letting a bad argument escape the field.", o: ["<pre>reg |= (mode &lt;&lt; 4);</pre>", "<pre>reg = (reg &amp; ~(7u &lt;&lt; 4))\n    | ((mode &amp; 7u) &lt;&lt; 4);</pre>", "<pre>reg = (mode &lt;&lt; 4);</pre>", "<pre>reg ^= (mode &lt;&lt; 4);</pre>"], a: 1, why: "<p>Three things have to happen. <code>~(7u &lt;&lt; 4)</code> clears the three-bit field while preserving every other bit. <code>mode &amp; 7u</code> confines a bad argument to the field. The OR then writes the value into the space just cleared.</p><p>Option 1 can only set bits, so a field holding 7 stays 7. Option 3 destroys every other bit in the register. Option 4 XORs, giving whatever the previous value happens to combine to.</p><p>One caveat that applies to all four: this is a read-modify-write, so it is wrong on a read-to-clear or write-1-to-clear register, and it is not atomic against an interrupt that touches the same register.</p>" },

{ t: "emb-serial", d: 2, q: "<span class='qtag'>Write it</span>buf holds two bytes from a sensor, low byte first, representing a signed 16-bit value. Which assembles it correctly and safely?", o: ["<pre>int16_t v = *(int16_t *)buf;</pre>", "<pre>int16_t v = (int16_t)\n  ((uint16_t)buf[1] &lt;&lt; 8 | buf[0]);</pre>", "<pre>int16_t v = (int16_t)\n  (buf[1] &lt;&lt; 8 | buf[0]);</pre>", "<pre>int16_t v = buf[0] + buf[1] * 256;</pre>"], a: 1, why: "<p>Option 2 builds the value in unsigned arithmetic, so nothing goes out of range, then casts once at the end.</p><p>Option 1 has three faults at once: it assumes the CPU's byte order matches the sensor's, it may perform an unaligned access which faults on Cortex-M0, and it violates strict aliasing, which at -O2 lets the compiler reorder or discard accesses.</p><p>Option 3 assembles directly into signed arithmetic, and converting an out-of-range value to a signed type is implementation-defined above 0x7FFF. Option 4 produces the right number but reads as arithmetic rather than byte assembly, and hides the byte order from anyone maintaining it.</p>" },

{ t: "emb-drivers", d: 3, q: "<span class='qtag'>Write it</span>Which transport struct makes a driver testable on a host with no vendor SDK?", o: ["<pre>typedef struct {\n    I2C_HandleTypeDef *hi2c;\n    uint8_t addr;\n} dev_io_t;</pre>", "<pre>typedef struct {\n    int  (*read) (void *, uint8_t, uint8_t *, size_t);\n    int  (*write)(void *, uint8_t, const uint8_t *, size_t);\n    void (*delay_ms)(void *, uint32_t);\n    void *ctx;\n} dev_io_t;</pre>", "<pre>typedef struct {\n    int (*transfer)(uint8_t *, size_t);\n} dev_io_t;</pre>", "<pre>typedef struct {\n    int port;\n    int addr;\n} dev_io_t;</pre>"], a: 1, why: "<p>Option 2 names only what the driver actually needs and nothing about how it happens. The register number is separate from the buffer, so the adapter decides how that becomes I2C framing or a SPI command byte, which is why one driver can serve both.</p><p>delay_ms is there because timing is a platform dependency too, and because a test needs to advance time instantly rather than really waiting through every timeout.</p><p>void *ctx is passed back untouched on every call, so the adapter can hold its port handle and address without globals, which is what allows more than one instance.</p><p>Option 1 puts an ST type in the header, so the driver cannot compile without the SDK. Option 3 loses the register abstraction and the context. Option 4 describes configuration, not an interface.</p>" },

{ t: "emb-errors", d: 2, q: "<span class='qtag'>Write it</span>init acquires a handle, then a buffer, then configures the device. Which cleanup structure is right?", o: ["<pre>if (!h) return -1;\nif (!buf) { free_h(h); return -1; }\nif (cfg()) { free(buf); free_h(h); return -1; }\nreturn 0;</pre>", "<pre>if (!h)   { rc = -1; goto out; }\nif (!buf) { rc = -1; goto free_h; }\nif (cfg()){ rc = -1; goto free_buf; }\nreturn 0;\nfree_buf: free(buf);\nfree_h:   free_h(h);\nout:      return rc;</pre>", "<pre>if (!h || !buf || cfg())\n    return -1;\nreturn 0;</pre>", "<pre>atexit(cleanup);\nreturn 0;</pre>"], a: 1, why: "<p>Option 2 gives exactly one unwind path, with each early exit jumping to the label that releases precisely what it had acquired. Add a fourth resource and you add one label, not four new cleanup lines.</p><p>Option 1 is correct as written but duplicates the cleanup at every exit, which is where leaks come from: someone adds a resource and updates three of the five paths.</p><p>Option 3 leaks both the handle and the buffer, because short-circuit evaluation skips the later tests without releasing what earlier ones acquired. Option 4 is not a C mechanism that applies here.</p><p>The rule that keeps this safe is forward-only jumps to labels at the end of the function. Backward jumps and jumps into blocks are what gave goto its reputation. The Linux kernel uses this pattern throughout.</p>" },

{ t: "emb-concurrency", d: 3, q: "<span class='qtag'>Write it</span>One producer in an ISR, one consumer in a task. Which full test keeps the ring buffer lock-free?", o: ["<pre>/* shared count, both sides write it */\nfull  = (count == SIZE);\nempty = (count == 0);</pre>", "<pre>/* sacrifice one slot */\nfull  = ((head + 1) % SIZE == tail);\nempty = (head == tail);</pre>", "<pre>full  = (head == tail);\nempty = (head == tail);</pre>", "<pre>taskENTER_CRITICAL();\nfull = (head == tail);\ntaskEXIT_CRITICAL();</pre>"], a: 1, why: "<p>With one slot sacrificed, the producer writes only head and the consumer writes only tail. Neither ever writes the other's variable, so on a machine with atomic word writes no lock is needed at all.</p><p>Option 1 has both sides writing count, which reintroduces exactly the shared mutable state you were trying to avoid, and therefore needs protecting.</p><p>Option 3 is the ambiguity itself: head == tail means both empty and full, and you cannot tell them apart.</p><p>Option 4 works but is a lock, so it costs interrupt latency on every access. A third design, used by Zephyr, is free-running indices that never wrap, deriving the offset by subtraction: that uses the whole buffer, at the cost of limiting the size to half the index range.</p>" },

{ t: "emb-rtos", d: 2, q: "<span class='qtag'>Write it</span>An ISR must hand a byte to a task. Which is correct?", o: ["<pre>void isr(void) {\n    xQueueSend(q, &amp;b, portMAX_DELAY);\n}</pre>", "<pre>void isr(void) {\n    BaseType_t woken = pdFALSE;\n    xQueueSendFromISR(q, &amp;b, &amp;woken);\n    portYIELD_FROM_ISR(woken);\n}</pre>", "<pre>void isr(void) {\n    xSemaphoreTake(m, portMAX_DELAY);\n    buf[i++] = b;\n    xSemaphoreGive(m);\n}</pre>", "<pre>void isr(void) {\n    while (queue_full) { }\n    push(b);\n}</pre>"], a: 1, why: "<p>The FromISR variant never blocks: it returns a failure instead of waiting, which is the only sane behaviour in interrupt context.</p><p>The woken flag is the part people omit. If the send unblocked a task more important than the one that was interrupted, portYIELD_FROM_ISR switches to it immediately rather than waiting for the next tick, which is often the difference between meeting and missing a deadline.</p><p>Option 1 calls a blocking API from an ISR, which frequently corrupts kernel state rather than failing cleanly. Option 3 blocks on a mutex, which nothing can release while the handler holds the CPU: guaranteed deadlock. Option 4 spins forever for the same reason.</p>" },

{ t: "emb-fixedpoint", d: 3, q: "<span class='qtag'>Write it</span>Multiply two Q16.16 values correctly, with rounding.", o: ["<pre>return (a * b) &gt;&gt; 16;</pre>", "<pre>return (int32_t)((((int64_t)a * b)\n         + (1 &lt;&lt; 15)) &gt;&gt; 16);</pre>", "<pre>return ((a &gt;&gt; 8) * (b &gt;&gt; 8));</pre>", "<pre>return (int32_t)(((int64_t)a * b) &gt;&gt; 32);</pre>"], a: 1, why: "<p>Widen first so the Q32.32 intermediate fits, add half a least-significant bit to round to nearest, then shift back by Q to return to Q16.16.</p><p>The cast must be on an operand, not on the product: <code>(int64_t)a * b</code> promotes b too, whereas <code>(int64_t)(a * b)</code> would have already overflowed.</p><p>Option 1 overflows the intermediate, which for a signed type is undefined behaviour. Option 3 shifts first, discarding exactly the precision you were trying to keep. Option 4 shifts by the wrong amount and leaves the result in the wrong format.</p><p>The rounding matters more than it looks: truncation always rounds towards negative infinity, and in a filter or an integrator that bias accumulates into a visible offset.</p>" },

{ t: "emb-structs", d: 2, q: "<span class='qtag'>Write it</span>A peripheral has CTRL at 0x00, STATUS at 0x04, nothing at 0x08, and DATA at 0x0C. Which register map is right?", o: ["<pre>typedef struct __attribute__((packed)) {\n    uint32_t CTRL;\n    uint32_t STATUS;\n    uint32_t DATA;\n} periph_t;</pre>", "<pre>typedef struct {\n    volatile uint32_t CTRL;\n    volatile uint32_t STATUS;\n    volatile uint32_t RESERVED0;\n    volatile uint32_t DATA;\n} periph_t;\n_Static_assert(sizeof(periph_t) == 16, \"\");</pre>", "<pre>typedef struct {\n    uint8_t CTRL;\n    uint8_t STATUS;\n    uint8_t DATA;\n} periph_t;</pre>", "<pre>typedef struct {\n    volatile uint32_t CTRL;\n    volatile uint32_t STATUS;\n    volatile uint32_t DATA;\n} periph_t;</pre>"], a: 1, why: "<p>The named reserved member states the gap in the source, so the offsets are what you wrote rather than what the compiler chose. The static assert makes a future edit break the build instead of silently pointing at the wrong addresses, and it costs no code.</p><p>volatile is needed because the peripheral changes these without your involvement.</p><p>Option 4 omits the gap, so DATA lands at 0x08 and every access hits the wrong register. Option 3 declares byte-wide registers, and many peripheral buses do not decode byte accesses at all. Option 1 is the worst: packing makes the compiler emit byte-wise sequences, which on a read-to-clear register clears the flags on the first byte and on a FIFO pops four times.</p>" },

{ t: "emb-pointers", d: 2, q: "<span class='qtag'>Write it</span>Which signature is right for a function that fills a caller-supplied buffer with a name?", o: ["<pre>void get_name(char *out);</pre>", "<pre>size_t get_name(char *out, size_t cap);</pre>", "<pre>char *get_name(void);</pre>", "<pre>void get_name(char out[64]);</pre>"], a: 1, why: "<p>Once an array crosses a function boundary it is a pointer, and the size information is gone. Without a capacity parameter the callee has no way to discover how much room it was given, and the first caller with a smaller buffer gets silently corrupted.</p><p>Returning size_t lets the caller learn how much was written, or how much would have been needed, which is the snprintf convention.</p><p>Option 4 looks safer but is identical to option 1 to the compiler: the 64 is discarded. It is still worth writing as documentation of the expectation, but it enforces nothing.</p><p>Option 3 has to return either a static buffer, which is not reentrant, or allocated memory, which transfers an ownership obligation that must then be documented.</p>" },

{ t: "emb-testing", d: 2, q: "<span class='qtag'>Write it</span>You need to test that init returns a distinct error when the chip ID is wrong. Which double do you need?", o: ["<pre>/* stub: fixed return */\nint read(void *c, uint8_t r,\n         uint8_t *b, size_t n)\n{ b[0] = 0xA0; return 0; }</pre>", "<pre>/* fake: register array you preload */\nstatic uint8_t regs[256];\nint read(void *c, uint8_t r,\n         uint8_t *b, size_t n)\n{ memcpy(b, &amp;regs[r], n); return 0; }</pre>", "<pre>/* spy: records the calls */\nint read(void *c, uint8_t r,\n         uint8_t *b, size_t n)\n{ log_call(r, n); return 0; }</pre>", "<pre>/* run it on the real board */</pre>"], a: 1, why: "<p>A fake lets the test preload regs[CHIP_ID] with a wrong value and then exercise the real driver logic all the way to the error return. It behaves coherently, so sequences where a later step depends on an earlier write also work.</p><p>The stub returns one fixed value, so it cannot express a different ID per test without becoming a fake anyway. The spy records interactions but does not answer questions, so the driver has nothing to compare against.</p><p>Real hardware cannot do this at all: you cannot make a real part report that it is a different device. That is why this whole class of error path is untestable without doubles, and why those paths so often ship having never executed.</p><p>Use a spy for the different question of whether init wrote CTRL1 <b>after</b> the reset, because ordering is a property of the interaction rather than of the result.</p>" },

{ t: "emb-fsm", d: 2, q: "<span class='qtag'>Write it</span>Which switch structure is the safer default for a state machine?", o: ["<pre>switch (st) {\ncase ST_IDLE: ... break;\ncase ST_RUN:  ... break;\n}</pre>", "<pre>switch (st) {\ncase ST_IDLE: ... break;\ncase ST_RUN:  ... break;\ndefault:\n    log_fault(\"bad state %d\", st);\n    st = ST_FAULT;\n    break;\n}</pre>", "<pre>if (st == ST_IDLE) { ... }\nif (st == ST_RUN)  { ... }</pre>", "<pre>switch (st) {\ncase ST_IDLE:\ncase ST_RUN:  ... break;\n}</pre>"], a: 1, why: "<p>Reaching an unlisted state means either memory corruption or a state added without updating this switch. Both are worth knowing about, and both are invisible without a default.</p><p>Without one, an unhandled value falls straight through and the machine does nothing, which is a decision nobody made and is indistinguishable from correct behaviour.</p><p>Option 3 additionally allows a transition made by the first if to be seen by the second, so one event can drive two transitions.</p><p>One genuine tension: -Wswitch-enum warns about missing enum cases only when there is <b>no</b> default, so some projects deliberately omit it on enum switches to keep that compile-time check, and rely on the compiler instead of a runtime branch.</p>" },

{ t: "emb-defensive", d: 2, q: "<span class='qtag'>Write it</span>You need to guarantee a register map's size never drifts. Which check?", o: ["<pre>assert(sizeof(periph_t) == 16);</pre>", "<pre>_Static_assert(sizeof(periph_t) == 16,\n    \"periph_t layout changed\");\n_Static_assert(offsetof(periph_t, DATA) == 12,\n    \"DATA moved\");</pre>", "<pre>/* periph_t must be 16 bytes */</pre>", "<pre>if (sizeof(periph_t) != 16)\n    return -1;</pre>"], a: 1, why: "<p>A static assert is evaluated by the compiler. It generates no instructions, occupies no flash, cannot be disabled by NDEBUG, and a failing one never ships because the binary does not exist.</p><p>sizeof alone catches the total drifting. The offsetof check catches the more insidious case where the total is still right but a field moved, which happens when someone changes a type or reorders members.</p><p>Option 1 costs code and can abort in front of a customer, and is compiled out in release builds exactly where it would matter. Option 4 wastes flash checking something that was fixed at compile time. Option 3 protects nothing.</p>" },

{ t: "emb-errors", d: 2, q: "<span class='qtag'>Write it</span>Rewrite this unbounded wait safely.<pre>while (!(SR &amp; SR_READY)) { }</pre>", o: ["<pre>while (!(SR &amp; SR_READY))\n    vTaskDelay(1);</pre>", "<pre>uint32_t t0 = now_ms();\nwhile (!(SR &amp; SR_READY)) {\n    if (now_ms() - t0 &gt; TIMEOUT_MS)\n        return -ETIMEDOUT;\n}\nreturn 0;</pre>", "<pre>for (int i = 0; i &lt; 100000; i++)\n    if (SR &amp; SR_READY) break;</pre>", "<pre>vTaskDelay(pdMS_TO_TICKS(50));</pre>"], a: 1, why: "<p>A bounded wait converts a permanent hang into a returned error the caller can act on: retry, reset the device, report it absent, or let the watchdog handle it. All of those beat stopping.</p><p>Note the elapsed test is written as <code>now - t0 &gt; TIMEOUT</code>, not <code>now &gt; t0 + TIMEOUT</code>. The subtraction form stays correct across a counter wrap because unsigned overflow is defined to wrap; the addition form overflows and the condition becomes false immediately.</p><p>Option 1 still waits forever, just more politely. Option 3 is calibrated to one clock speed and one optimisation level. Option 4 is a fixed delay, which is both slower than necessary when the device is ready and wrong when it is not.</p>" }

]);
