// Questions for the six C++ lessons that had none.
// Topic tags are lesson ids, so topicLesson() resolves them by the byId fallback.
BANKS["C++"] = BANKS["C++"].concat([

// ------------------------------------------------------------- cpp-errors
{ t: "cpp-errors", d: 2, q: "What does the basic exception guarantee promise?", o: ["The operation cannot throw at all", "No leaks and a valid object, though its state may have changed", "The operation completes or has no effect", "Errors are reported by return code"], a: 1, why: "Basic is the floor: invariants hold and nothing leaks, but you cannot assume the value is unchanged. Strong adds rollback (complete or no effect), and nothrow promises it cannot throw." },
{ t: "cpp-errors", d: 2, q: "Why does std::vector check whether the element's move constructor is noexcept before reallocating?", o: ["To choose a bigger growth factor", "Without noexcept it copies instead, so a throw mid-way leaves the original intact", "noexcept moves are faster to execute", "It is a debug-build assertion only"], a: 1, why: "Reallocation must give the strong guarantee. A throwing move halfway through would leave elements already moved out of the old buffer with no way back, so the library falls back to copying." },
{ t: "cpp-errors", d: 2, q: "What is the practical difference between std::optional and std::expected?", o: ["expected can hold more values", "optional says a value is absent; expected also carries a typed reason why", "optional is faster", "expected always allocates"], a: 1, why: "Use optional when 'not found' needs no explanation, such as a map lookup. Use expected when the caller has to act differently depending on the failure, which is most I/O and parsing." },
{ t: "cpp-errors", d: 2, q: "What happens if a destructor throws while an exception is already propagating?", o: ["The second exception is ignored", "std::terminate is called", "Both propagate together", "The first exception is replaced"], a: 1, why: "This is why destructors are implicitly noexcept since C++11 and why cleanup that can fail needs an explicit close() the caller can check, with the destructor swallowing errors as a last resort." },
{ t: "cpp-errors", d: 2, q: "On a typical modern implementation, what does a try block cost when no exception is thrown?", o: ["A branch per entry", "Essentially nothing at runtime; the cost is in binary size and in the throw path", "A heap allocation", "A stack frame copy"], a: 1, why: "Table-driven unwinding puts the work in cold metadata, so the happy path is free. That is why the embedded objection to exceptions is about the flash cost of the tables and the unbounded throw path, not about steady-state speed." },
{ t: "cpp-errors", d: 3, q: "What breaks in a codebase built with -fno-exceptions?", o: ["Nothing, it is fully compatible", "Anything that throws, including operator new on failure and at(), std::stoi and standard containers", "Only user-written throws", "Templates stop compiling"], a: 1, why: "The library still contains throw sites, so calls that would throw terminate instead. That means checking allocation yourself with the nothrow new, and avoiding at(), stoi and similar." },
{ t: "cpp-errors", d: 3, q: "Why is RAII the thing that makes exception safety tractable?", o: ["It removes the need for destructors", "Cleanup happens during unwinding, so there is no path where a manual free is skipped", "It converts exceptions to error codes", "It makes all operations noexcept"], a: 1, why: "With manual cleanup, every early exit needs its own release and an exception skips all of them. Tying the resource to an object's lifetime makes the correct thing automatic on every path." },
{ t: "cpp-errors", d: 3, q: "A driver function can fail for six distinct reasons the caller must distinguish. Which return design fits best?", o: ["bool, with a global errno", "std::expected with a scoped enum error type", "Throwing six exception classes", "int, with negative values meaning failure"], a: 1, why: "The enum makes the set exhaustive and switchable, and expected forces the caller to look at it. A bool plus global state is not thread-safe and negative ints have no type checking." },

// ------------------------------------------------------------ cpp-lambdas
{ t: "cpp-lambdas", d: 1, q: "What is a lambda, in terms of what the compiler generates?", o: ["A function pointer", "A unique unnamed class type with an operator(), holding the captures as members", "A std::function object", "A macro expansion"], a: 1, why: "Each lambda has its own distinct type, which is why two identical-looking lambdas are not interchangeable and why you need auto, a template parameter or std::function to store one." },
{ t: "cpp-lambdas", d: 2, q: "In a member function, what does capturing with [=] actually capture when the body uses a data member?", o: ["A copy of the member", "The this pointer, so the member is reached through it", "Nothing; it is a compile error", "A reference to the member"], a: 1, why: "So the lambda dangles if it outlives the object, despite the by-value-looking capture. C++17 added [*this] to capture a copy of the whole object, and C++20 deprecated the implicit this capture in [=]." },
{ t: "cpp-lambdas", d: 2, q: "What does the mutable keyword do on a lambda?", o: ["Allows it to modify captured references", "Allows it to modify its own by-value copies", "Makes it thread-safe", "Allows capture of non-const variables"], a: 1, why: "operator() is const by default, so by-value captures are read-only inside the body. mutable drops that const, and the change persists in the closure between calls." },
{ t: "cpp-lambdas", d: 2, q: "How do you capture a std::unique_ptr into a lambda?", o: ["By reference, with [&p]", "With an init capture, [p = std::move(p)]", "By value, with [p]", "It cannot be done"], a: 1, why: "A plain by-value capture would need a copy, which unique_ptr does not have. Init capture (C++14) lets you move it in, or construct an entirely new member from an expression." },
{ t: "cpp-lambdas", d: 2, q: "Why is passing a lambda to std::sort usually faster than passing a function pointer?", o: ["Lambdas use less stack", "The lambda's type is unique, so the comparison inlines; a function pointer is an indirect call", "std::sort special-cases lambdas", "Function pointers require a heap allocation"], a: 1, why: "This is the classic reason C++ sort beats C qsort: the comparator becomes part of the instantiated template rather than something called through a pointer the optimiser cannot see through." },
{ t: "cpp-lambdas", d: 2, q: "What does std::function cost that a raw lambda does not?", o: ["Nothing measurable", "Type erasure: an indirect call, possibly a heap allocation, and no inlining", "Extra template instantiations", "A virtual base class"], a: 1, why: "Small closures may fit in its internal buffer and avoid the allocation, but the indirect call remains. In a per-sample hot loop prefer a template parameter or auto." },
{ t: "cpp-lambdas", d: 3, q: "Why can a captureless lambda convert to a plain function pointer?", o: ["The compiler special-cases it", "With no state to carry, its operator() needs no object, so a static function can do the job", "All lambdas convert", "Only with an explicit cast"], a: 1, why: "This is the standard way to hand a callback to a C SDK. As soon as it captures anything there is state to carry and the conversion disappears, which is why C APIs pair a function pointer with a void* context." },
{ t: "cpp-lambdas", d: 3, q: "A lambda capturing by reference is posted to a thread pool and runs later. What is the defect?", o: ["Copies are too expensive", "The referenced locals may be destroyed before it runs", "std::function cannot store it", "Reference captures are not thread-safe by definition"], a: 1, why: "Reference capture is safe only when the lambda is consumed before the enclosing scope exits, as in an algorithm call. For anything deferred, capture by value or with an init capture that moves ownership in." },

// ---------------------------------------------------------- cpp-constexpr
{ t: "cpp-constexpr", d: 1, q: "What is the difference between const and constexpr on a variable?", o: ["None", "const means it is not modified; constexpr means its value is known at compile time", "constexpr means it lives in flash", "const is C++11, constexpr is C++20"], a: 1, why: "A const initialised from a runtime value is still const. Only constexpr guarantees usability as an array bound, a template argument or a case label." },
{ t: "cpp-constexpr", d: 2, q: "What does if constexpr do that a plain if does not?", o: ["It runs faster", "The discarded branch is not instantiated, so it may contain code invalid for that type", "It evaluates at link time", "It works only on integers"], a: 1, why: "Which is what makes it a replacement for tag dispatch and SFINAE. A regular if still requires both branches to compile for every instantiation." },
{ t: "cpp-constexpr", d: 2, q: "Where does a constexpr lookup table typically end up in a firmware image?", o: ["The stack", "A read-only section in flash, with no startup copy and no RAM cost", "The heap", "Initialised RAM"], a: 1, why: "That is the main practical payoff on a small part: the table is materialised by the compiler rather than computed at boot, and it costs no RAM because it is never written." },
{ t: "cpp-constexpr", d: 2, q: "What happens if signed integer overflow occurs while evaluating a constant expression?", o: ["It wraps silently", "It is a compile error, because UB is not permitted in a constant expression", "It saturates", "It is undefined at runtime"], a: 1, why: "This is a genuinely useful side effect: moving arithmetic to compile time turns a class of undefined behaviour into a diagnostic, since the evaluator must reject anything it cannot define." },
{ t: "cpp-constexpr", d: 2, q: "What does consteval add over constexpr on a function?", o: ["It is faster", "Every call must be a constant expression, so it can never run at runtime", "It allows floating point", "It implies inline"], a: 1, why: "constexpr means 'may run at compile time'; a call with runtime arguments quietly becomes an ordinary call. consteval makes that a compile error, which is what you want for a compile-time-only helper." },
{ t: "cpp-constexpr", d: 2, q: "When does static_assert fire?", o: ["At program start", "At compile time, when the condition is a false constant expression", "On the first call", "In debug builds only"], a: 1, why: "Which makes it the right tool for checking struct sizes against a wire format, or that a type is trivially copyable before you memcpy it. It costs nothing in the binary." },
{ t: "cpp-constexpr", d: 3, q: "Why is constexpr generally preferred over template metaprogramming for compile-time computation?", o: ["It is more powerful", "It is written as ordinary code, so it is readable, debuggable and reusable at runtime", "Templates were deprecated", "It compiles faster in all cases"], a: 1, why: "The same function serves both, and the errors are normal errors rather than pages of instantiation backtrace. Templates remain necessary for type-level work rather than value-level work." },
{ t: "cpp-constexpr", d: 3, q: "A constexpr function is called with a runtime argument. What happens?", o: ["A compile error", "It runs at runtime like any ordinary function", "It returns a default value", "The argument is converted to a constant"], a: 1, why: "constexpr is a permission, not an obligation. If you need the guarantee, use consteval, or force it by assigning the result to a constexpr variable." },

// -------------------------------------------------------------- cpp-build
{ t: "cpp-build", d: 2, q: "Why are most ODR violations described as ill-formed, no diagnostic required?", o: ["The standard is vague", "The conflict spans translation units, which no single compilation sees, and the linker matches names only", "Compilers choose not to report them", "They only occur in templates"], a: 1, why: "Two files defining the same class differently each compile cleanly, and the linker keeps one arbitrarily. The symptom is a corrupted object at runtime, so the discipline is one header, included everywhere." },
{ t: "cpp-build", d: 2, q: "What does the inline keyword primarily mean in modern C++?", o: ["Expand this call site", "This definition may appear in multiple translation units and they must be identical", "Optimise this function", "Place it in flash"], a: 1, why: "The inlining hint is essentially ignored; the ODR exemption is the real meaning. It is why header-only libraries work and why C++17 added inline variables." },
{ t: "cpp-build", d: 2, q: "What does extern \"C\" actually change?", o: ["The calling convention only", "It disables name mangling, so the symbol is linkable from C", "It makes the function static", "It forces C semantics on the body"], a: 1, why: "C++ encodes parameter types into the symbol name to support overloading, and C linkers know nothing about that. It is why every C header meant for C++ callers is wrapped in it." },
{ t: "cpp-build", d: 2, q: "Why does the order of static libraries on the link line matter with GNU ld?", o: ["It does not", "The linker takes one pass, pulling only objects that resolve symbols outstanding at that point", "Later libraries override earlier ones", "Alphabetical order is required"], a: 1, why: "So a library must appear after everything that needs it. The usual fixes are correct ordering, repeating a library, or wrapping the group in --start-group and --end-group." },
{ t: "cpp-build", d: 2, q: "In a C++ header, when can a forward declaration replace an include?", o: ["It compiles more correctly", "It cuts rebuild cascades and breaks dependency cycles when only the pointer or reference type is needed", "Includes are unreliable", "It reduces binary size"], a: 1, why: "Every header that includes another propagates a rebuild to everything downstream. A declaration of the class name is enough to declare functions taking pointers or references to it." },
{ t: "cpp-build", d: 3, q: "What is the modern CMake idiom that replaces global include_directories?", o: ["Setting CMAKE_CXX_FLAGS", "target_include_directories with PUBLIC, PRIVATE or INTERFACE", "add_definitions", "link_directories"], a: 1, why: "Target-based usage requirements propagate to consumers automatically and only to consumers that need them, which is what stops one library's private include path leaking across the whole project." },
{ t: "cpp-build", d: 3, q: "Two .cpp files include the same struct, but one is compiled with a macro that adds a member. What is this?", o: ["Fine, if both are recompiled", "An ODR violation, and the sizes disagree so one file writes past the other's object", "A linker error", "A warning only"], a: 1, why: "It links, because the symbol names match. It is the classic cause of a build that works until someone changes a compile definition in one target and not another." },
{ t: "cpp-build", d: 3, q: "What does static linking give you that dynamic linking does not, on an embedded target?", o: ["A smaller image", "One self-contained image with no runtime loader, and only the objects you reference pulled in", "Faster compilation", "Automatic security updates"], a: 1, why: "There is usually no loader or filesystem to hold a shared object. The trade is that a library fix means reflashing everything rather than replacing one file." },

// --------------------------------------------------------------- cpp-perf
{ t: "cpp-perf", d: 2, q: "Why can a microbenchmark of a pure computation report near-zero time?", o: ["The timer resolution is too coarse", "The result is unused, so the optimiser deletes the work entirely", "Caches make it free", "The compiler precomputes it at link time"], a: 1, why: "The fix is a sink the optimiser cannot see through, such as benchmark::DoNotOptimize or writing to a volatile. Without it you are timing an empty loop." },
{ t: "cpp-perf", d: 2, q: "Why is traversing a std::vector usually much faster than a std::list of the same length?", o: ["list has more overhead per operation", "Contiguous storage means each cache line fetch brings several elements and the prefetcher can predict the pattern", "vector is better optimised in the library", "list uses virtual calls"], a: 1, why: "A list node is a separate allocation reached by pointer, so most accesses are cache misses the hardware cannot anticipate. The asymptotic costs say nothing about this." },
{ t: "cpp-perf", d: 2, q: "Sorting the input made a branchy filtering loop several times faster. Why?", o: ["Sorted data compresses better", "Branches became predictable, so the pipeline stopped flushing on mispredictions", "The comparison got cheaper", "Fewer elements passed the filter"], a: 1, why: "A mispredicted branch costs on the order of fifteen to twenty cycles. On unsorted data the condition is a coin flip; on sorted data it is a long run of one outcome then the other." },
{ t: "cpp-perf", d: 2, q: "What is false sharing?", o: ["Two threads reading the same variable", "Two threads writing different variables that share a cache line, forcing the line to bounce between cores", "Sharing a lock unnecessarily", "Copying data between threads"], a: 1, why: "The variables are logically independent but the coherency protocol works in whole lines. The fix is padding or aligning each to its own line, usually 64 bytes." },
{ t: "cpp-perf", d: 2, q: "You will push_back a known number of elements into a vector. What is the cheap win?", o: ["Use a list instead", "Call reserve first, so there is one allocation and no reallocation copies", "Use emplace_back", "Disable exceptions"], a: 1, why: "Growth reallocates and moves everything, repeatedly. reserve turns an amortised sequence of copies into a single allocation, and it is one line." },
{ t: "cpp-perf", d: 3, q: "What does Amdahl's law tell you before you start optimising?", o: ["Parallel code is always faster", "Speedup is capped by the fraction you do not improve, so a 5 percent hotspot can never give more than about 5 percent", "Optimisation is linear in effort", "Caches dominate everything"], a: 1, why: "It is the argument for profiling first. Time spent making a cold function twice as fast is time spent for nothing, however satisfying the improvement looks in isolation." },
{ t: "cpp-perf", d: 3, q: "Why is std::endl often a performance problem in logging?", o: ["It writes two characters", "It flushes the stream on every call, forcing a syscall per line", "It is not thread safe", "It allocates"], a: 1, why: "A newline character alone lets the buffer fill and flush in blocks. On an embedded UART or a file this is frequently the difference between a log that keeps up and one that dominates the profile." },
{ t: "cpp-perf", d: 3, q: "What is the small string optimisation?", o: ["Compressing string contents", "Storing short strings inside the object itself, avoiding a heap allocation", "Interning duplicate strings", "Using string_view instead"], a: 1, why: "Typically around 15 to 22 characters depending on the implementation. It means short strings cost nothing to allocate, and it is why sizeof(std::string) is 32 bytes rather than a pointer." },

// ------------------------------------------------------------ cpp-testing
{ t: "cpp-testing", d: 2, q: "What distinguishes a mock from a stub?", o: ["Nothing, the terms are interchangeable", "A stub supplies canned answers; a mock also asserts on how it was called", "A mock is generated, a stub is written", "A stub is for classes, a mock for functions"], a: 1, why: "Over-using mocks couples tests to the implementation, so a refactor breaks them even when behaviour is unchanged. Prefer a stub unless the interaction itself is the thing under test." },
{ t: "cpp-testing", d: 2, q: "Which seam for injecting a fake bus into a driver has zero runtime cost?", o: ["A virtual interface", "A template parameter for the transport type", "std::function members", "A global function pointer"], a: 1, why: "The fake is substituted at compile time and the calls inline away. A virtual interface is more flexible and easier to read, so the choice depends on whether the call is in a hot path." },
{ t: "cpp-testing", d: 2, q: "How do you make code that depends on the current time testable?", o: ["Sleep in the test", "Inject a clock, so the test supplies a fake that advances on demand", "Use a longer timeout", "Mock the operating system"], a: 1, why: "It removes the two worst properties of time-dependent tests at once: they stop being slow and they stop being flaky. The same argument applies to randomness and to file paths." },
{ t: "cpp-testing", d: 2, q: "Why run the unit test suite under ASan and UBSan in CI?", o: ["They make tests faster", "They turn silent memory and undefined-behaviour bugs into loud failures on code the tests already exercise", "They replace the need for tests", "They check code coverage"], a: 1, why: "A test can pass while writing one byte past a buffer. The sanitizers cost roughly two to three times the runtime and find the class of defect that reading and unit tests both miss." },
{ t: "cpp-testing", d: 2, q: "Which code is the strongest candidate for fuzzing?", o: ["A pure arithmetic helper", "A parser that consumes untrusted input, such as a protocol frame decoder", "A logging function", "A getter"], a: 1, why: "Fuzzing needs a function that takes bytes and can crash. Combined with a sanitizer it finds the malformed-length and truncated-frame cases nobody thinks to write by hand." },
{ t: "cpp-testing", d: 3, q: "A test passes alone and fails when the suite runs. What is the usual cause?", o: ["A compiler bug", "Shared state between tests, or an order dependency", "Insufficient timeout", "Missing assertions"], a: 1, why: "Statics, singletons and files left behind are the usual culprits. Running the suite in a shuffled order in CI is what surfaces it, rather than discovering it months later." },
{ t: "cpp-testing", d: 3, q: "Line coverage is 95 percent. What does that not tell you?", o: ["Which lines ran", "Whether the assertions actually check anything, or whether the untested 5 percent is the error handling", "How long the tests take", "Whether the code compiles"], a: 1, why: "Coverage measures execution, not verification: a test with no assertions covers plenty. The uncovered remainder is also rarely random, and is usually exactly the error paths." },
{ t: "cpp-testing", d: 3, q: "When is a fatal (REQUIRE-style) assertion preferable to a non-fatal one?", o: ["Always", "When continuing would crash or make the rest of the test meaningless, such as after a null check", "In performance tests", "Never, they hide failures"], a: 1, why: "Checking a pointer before dereferencing it is the clear case. For independent checks on a result, non-fatal assertions report every failure in one run rather than only the first." }

]);
