// Questions for the eight Electronics lessons that had none.
BANKS["Electronics"] = BANKS["Electronics"].concat([

// ---------------------------------------------------------- el-mosfets
{ t: "el-mosfets", d: 2, q: "A 3.3 V GPIO drives a power MOSFET with 30 nC gate charge directly at 100 kHz. What is the main problem?", o: ["The gate leaks too much", "The GPIO cannot supply the peak current, so switching is slow and the device spends too long in linear operation", "The gate voltage is too high", "The MOSFET oscillates"], a: 1, why: "Switching loss happens during the transition, when there is both voltage across the device and current through it. A slow edge multiplies that overlap by 100,000 times a second, and 3.3 V may not fully enhance the gate either." },
{ t: "el-mosfets", d: 2, q: "Why does an N-channel high-side switch need a bootstrap or charge pump?", o: ["To limit inrush", "The gate must sit above the source, which is at the supply rail when the device is on, so the drive voltage must exceed the rail", "To protect the gate oxide", "To reduce Rds(on)"], a: 1, why: "N-channel devices need Vgs positive with respect to the source. A P-channel high-side switch avoids the problem entirely, at the cost of worse Rds(on) for the same die area." },
{ t: "el-mosfets", d: 2, q: "Rds(on) is 10 mOhm at 25 C. What should you expect at a junction temperature of 125 C?", o: ["Roughly the same", "Roughly 15 to 20 mOhm, since Rds(on) rises substantially with temperature", "About 5 mOhm", "It becomes undefined"], a: 1, why: "Typically 1.5 to 2 times over that range. This is thermal runaway in the conduction sense: more resistance means more heating means more resistance, so the thermal design must use the hot number, not the datasheet headline." },
{ t: "el-mosfets", d: 2, q: "During dead time in a synchronous buck, where does the inductor current flow?", o: ["Through the high-side channel", "Through the low-side MOSFET's body diode", "It stops", "Through the output capacitor only"], a: 1, why: "The inductor will not allow its current to stop, so it forces a path. The body diode conducts with about 0.7 V across it, so long dead time wastes power and is why dead time is set as short as safety allows." },
{ t: "el-mosfets", d: 2, q: "What is the purpose of a gate resistor?", o: ["To limit steady-state current", "To slow the edge deliberately, damping ringing and reducing EMI at the cost of switching loss", "To protect against ESD", "To set the threshold voltage"], a: 1, why: "The gate is capacitive, so in steady state no current flows. The resistor with the gate capacitance sets the slew rate, which is the direct trade between emissions and efficiency." },
{ t: "el-mosfets", d: 3, q: "What is the Miller plateau, and why does it dominate switching time?", o: ["A voltage regulation artefact", "The flat region of the gate waveform where drain-gate capacitance is being charged while Vds swings, so gate voltage stalls", "The threshold region", "A thermal effect"], a: 1, why: "All the driver current goes into Cgd rather than raising Vgs, so the transition takes as long as it takes to move that charge. It is why gate drive current, not voltage, sets switching speed." },
{ t: "el-mosfets", d: 3, q: "Why can a MOSFET fail when switched with a very long, slow gate edge in a bridge?", o: ["The gate oxide breaks down", "It dwells in the linear region dissipating heavily, and dv/dt on the other device can turn it on parasitically through Cgd", "The body diode fails", "Rds(on) rises"], a: 1, why: "The second effect is Miller turn-on: fast dv/dt couples through the drain-gate capacitance and lifts the gate of the supposedly-off device. A negative off-bias or a low-impedance pull-down defeats it." },
{ t: "el-mosfets", d: 3, q: "Why parallel MOSFETs share current reasonably well without ballast resistors?", o: ["They are matched at manufacture", "Rds(on) has a positive temperature coefficient, so the hotter device takes less current", "The gate drive equalises it", "They do not share; it is a myth"], a: 1, why: "The same property that makes thermal design harder makes paralleling easy. Bipolar transistors have the opposite coefficient, which is why they need emitter ballast resistors to share." },

// ------------------------------------------------------ el-comparators
{ t: "el-comparators", d: 2, q: "Why does an op-amp make a poor comparator?", o: ["Its gain is too low", "It is compensated for closed-loop stability, so it is slow to recover from saturation, and its output may not reach the rails", "It has too much offset", "Its inputs cannot handle the range"], a: 1, why: "Internal compensation and saturation recovery mean microseconds of delay where a comparator takes nanoseconds. Some op-amps also suffer phase inversion if an input goes outside the common-mode range." },
{ t: "el-comparators", d: 2, q: "A comparator output chatters as a slow signal crosses the threshold. What is the fix?", o: ["A faster comparator", "Positive feedback to add hysteresis, so the threshold moves after each transition", "More supply decoupling", "A lower gain"], a: 1, why: "With no hysteresis, noise of any amplitude crosses the threshold repeatedly during a slow transition. The hysteresis band must exceed the noise, and it costs you accuracy at the switching point." },
{ t: "el-comparators", d: 2, q: "Two open-drain comparator outputs share a pull-up. When is the line high?", o: ["When either output is inactive", "Only when both outputs are inactive, since either can pull it low", "Always", "Never"], a: 1, why: "That is a wired-AND, and it makes an implicit alarm bus: any fault pulls the shared line low. The pull-up value trades rise time against current, which is why open-drain buses are slow." },
{ t: "el-comparators", d: 2, q: "A comparator runs from 12 V and must drive a 3.3 V microcontroller input. What is the cleanest option?", o: ["A resistor divider on the output", "An open-drain comparator with the pull-up to 3.3 V", "A series resistor into the pin", "Rely on the input clamp diodes"], a: 1, why: "The output never sources, so the pull-up rail alone sets the high level. A divider works but slows the edge and wastes current, and relying on clamp diodes injects current into the microcontroller's rail." },
{ t: "el-comparators", d: 2, q: "What does a window comparator do?", o: ["Compares two signals", "Flags whether a signal lies between an upper and a lower threshold, using two comparators", "Adds hysteresis automatically", "Detects zero crossings"], a: 1, why: "Wiring the two open-drain outputs together gives a single in-range signal for free. It is the standard supply-supervisor and sensor-plausibility building block." },
{ t: "el-comparators", d: 3, q: "How do you calculate the hysteresis band for a non-inverting comparator with positive feedback?", o: ["It equals the supply voltage", "From the divider ratio of the feedback resistor against the input resistor, times the output swing", "It is fixed by the device", "From the input capacitance"], a: 1, why: "The feedback resistor injects a fraction of the output back to the non-inverting input, shifting the threshold by that fraction of the swing. Make the feedback resistor much larger than the source impedance or you load the signal." },
{ t: "el-comparators", d: 3, q: "Why does a comparator with a very slow input edge sometimes emit a runt pulse even with hysteresis?", o: ["The hysteresis is negative", "The hysteresis is smaller than the noise on the input at that moment", "The comparator is too fast", "The pull-up is too weak"], a: 1, why: "Hysteresis only helps if the band exceeds the noise amplitude. The alternatives are more hysteresis, filtering the input before the comparator, or debouncing in firmware." },
{ t: "el-comparators", d: 3, q: "What is the risk of a rail-to-rail comparator input near the supply rail?", o: ["Latch-up", "Many rail-to-rail input stages switch between two internal transistor pairs, causing an offset step mid-range", "The output inverts", "Input current reverses"], a: 1, why: "The crossover produces a small discontinuity in offset voltage exactly where the datasheet's typical figures look fine. In precision threshold work it is worth keeping the operating point away from the transition." },

// -------------------------------------------------------- el-precision
{ t: "el-precision", d: 2, q: "An amplifier with 1 nA input bias current measures a sensor with 1 MOhm source impedance. What error does that give?", o: ["1 microvolt", "1 millivolt", "1 volt", "Negligible"], a: 1, why: "1 nA times 1 MOhm is 1 mV, which swamps most precision specifications. It is why high-impedance sources need FET or CMOS input amplifiers with picoamp bias currents." },
{ t: "el-precision", d: 2, q: "How does a chopper amplifier achieve microvolt offsets?", o: ["By laser trimming", "It modulates the signal above the flicker-noise region, amplifies, then demodulates, so offset and 1/f noise are moved away and filtered out", "By using larger transistors", "By cooling the die"], a: 1, why: "The cost is switching artefacts at the chopping frequency and, in some devices, higher input bias current. For DC and very low-frequency measurement the trade is usually worth it." },
{ t: "el-precision", d: 2, q: "Why does a guard ring around a high-impedance node work?", o: ["It shields against RF", "It is driven to the same potential as the node, so there is no voltage across the surface leakage path and no leakage current", "It adds capacitance to ground", "It provides a return path"], a: 1, why: "Leakage is driven by voltage, so removing the voltage removes the current. It has to be driven by a low-impedance buffer at the node's potential, not simply connected to ground." },
{ t: "el-precision", d: 2, q: "A gain stage uses two ordinary 100 ppm/C resistors. Over a 40 C rise, what is the worst-case gain drift?", o: ["About 100 ppm", "About 8000 ppm, or 0.8 percent, if they drift in opposite directions", "About 4000 ppm", "Negligible"], a: 1, why: "Each can move 4000 ppm, and the worst case is opposite directions. A matched resistor network in one package with a tight ratio tempco is the fix, because only the ratio matters for gain." },
{ t: "el-precision", d: 2, q: "What causes thermocouple effects on a precision board?", o: ["Faulty solder", "Junctions of dissimilar metals at different temperatures generate microvolts, which appear as a drifting offset", "Ground loops", "Input bias current"], a: 1, why: "A solder-to-copper junction gives a few microvolts per kelvin. The mitigations are keeping matched junction pairs at the same temperature and keeping heat sources away from the input path." },
{ t: "el-precision", d: 3, q: "Why is a ratiometric measurement immune to reference drift?", o: ["It uses a better reference", "The same reference excites the sensor and sets the ADC full scale, so the reference cancels in the ratio", "It averages more samples", "It uses differential inputs"], a: 1, why: "A bridge or potentiometric divider driven from the ADC reference is the standard case. It converts an absolute accuracy problem into a matching problem, which is far cheaper to solve." },
{ t: "el-precision", d: 3, q: "In an error budget, why combine independent error terms in quadrature rather than adding them?", o: ["It gives a smaller number", "Independent random errors add as the root sum of squares; only correlated or systematic terms add linearly", "It is a convention", "It accounts for temperature"], a: 1, why: "Adding everything linearly gives a worst case that is real but very pessimistic. The discipline is to separate systematic terms, which add, from random ones, which combine in quadrature." },
{ t: "el-precision", d: 3, q: "Where does precision most often actually die on a real board?", o: ["In the amplifier's datasheet specifications", "In the layout and mechanics: leakage, thermocouples, thermal gradients, flux residue and coupling", "In the ADC resolution", "In the firmware averaging"], a: 1, why: "The silicon is usually far better than the board around it. Cleaning flux, keeping the input path short and guarded, and thinking about where the heat goes buys more than a better part number." },

// ------------------------------------------------------------- el-emc
{ t: "el-emc", d: 2, q: "Below a few hundred MHz, what is the dominant radiator in most products?", o: ["The PCB traces", "Cables attached to the box, acting as antennas driven by common-mode currents", "The enclosure seams", "The switching transistor"], a: 1, why: "A one-metre cable is resonant around 75 MHz and radiates far better than any trace. It is why cable termination and common-mode chokes matter more than trace-level fixes at those frequencies." },
{ t: "el-emc", d: 2, q: "Why does loop area matter so much for emissions?", o: ["It sets the resistance", "Radiated field from a current loop is proportional to its area, so a large loop is an efficient antenna", "It affects impedance only", "It changes the resonant frequency"], a: 1, why: "This applies to both the signal path and its return. It is the physical reason a solid reference plane is so effective: the return current flows directly under the trace, making the loop area almost nothing." },
{ t: "el-emc", d: 2, q: "Slowing a digital edge from 1 ns to 10 ns helps emissions mainly because it does what?", o: ["Reduces the fundamental", "Moves the spectral knee down by a decade, so high-frequency harmonic content falls sharply", "Reduces the current", "Improves the impedance match"], a: 1, why: "The knee is roughly 0.35 divided by rise time, so 350 MHz becomes 35 MHz. Above the knee the envelope falls faster, which is why edge rate is the cheapest emissions control available." },
{ t: "el-emc", d: 2, q: "A shielded cable is terminated to chassis with a 5 cm pigtail. What happens above a few MHz?", o: ["It works better", "The pigtail's inductance makes the shield connection high-impedance, so the shield stops working", "It only affects DC", "It improves immunity"], a: 1, why: "5 cm is roughly 50 nH, which is over 30 ohms at 100 MHz. A 360-degree termination to the connector shell is the fix, and it is one of the most common EMC failures found at test." },
{ t: "el-emc", d: 2, q: "What is the highest-priority layout region for EMC in a switching converter?", o: ["The output filter", "The high di/dt loop: input capacitor, switch and diode or synchronous FET", "The feedback divider", "The inductor"], a: 1, why: "That loop carries a current that switches in nanoseconds, so its area sets the radiated field. Minimising it, with the input capacitor right at the switch, is the single most effective thing you can do." },
{ t: "el-emc", d: 3, q: "What is the difference between common-mode and differential-mode noise?", o: ["Frequency", "Differential flows out on one conductor and back on the other; common-mode flows the same direction on all conductors and returns through the chassis or free space", "Amplitude", "Common-mode is always higher frequency"], a: 1, why: "They need different filters: an X capacitor across the lines for differential, a common-mode choke and Y capacitors for common-mode. Common-mode radiates far more, because there is no cancelling return." },
{ t: "el-emc", d: 3, q: "Why is pre-compliance testing worth doing even with a cheap near-field probe?", o: ["It gives certifiable results", "It finds which part of the board is the source, which is what full compliance testing does not tell you", "It replaces the test house", "It is required by CE marking"], a: 1, why: "A formal test tells you that you failed at 137 MHz, and nothing more. A near-field probe over the board finds the offender in minutes, and a full retest costs both days and money." },
{ t: "el-emc", d: 3, q: "Why does spread-spectrum clocking help an emissions measurement?", o: ["It reduces the total emitted energy", "It spreads the same energy over a wider band, lowering the peak in the receiver's resolution bandwidth", "It cancels harmonics", "It shifts the fundamental down"], a: 1, why: "The total energy is unchanged, so it is arguably gaming the measurement rather than fixing the product. It is legitimate and widely used, but it will not rescue a design with a genuinely large radiating loop." },

// ------------------------------------------------------- el-protection
{ t: "el-protection", d: 2, q: "Best reverse-polarity protection for a 3 A battery instrument that must waste minimal voltage?", o: ["A series Schottky diode", "A P-channel MOSFET in series, with its body diode oriented to conduct in the correct polarity", "A fuse and a parallel diode", "A bridge rectifier"], a: 1, why: "The MOSFET drops only I times Rds(on), a few tens of millivolts, against 0.3 to 0.5 V for a Schottky and 3 A. A parallel crowbar diode plus fuse is cheap but destructive and needs a fuse replacement." },
{ t: "el-protection", d: 2, q: "A TVS clamps poorly in testing despite a good datasheet clamping voltage. What is the likely cause?", o: ["The wrong part was fitted", "Layout inductance: the loop from the connector pin through the TVS to ground adds L*di/dt during the fast ESD edge", "The TVS is too large", "The supply is too low"], a: 1, why: "An ESD pulse rises in under a nanosecond, so even a few nanohenries adds volts. The TVS must be right at the connector with the shortest possible path to the reference plane." },
{ t: "el-protection", d: 2, q: "Compared with a PTC polyfuse, what does an eFuse mainly buy you?", o: ["Lower cost", "A fast, precise and repeatable current limit, plus features like soft-start and fault reporting", "Higher current capability", "No need for a MOSFET"], a: 1, why: "A PTC trips slowly, has a wide tolerance, and its trip point drifts with ambient temperature and with age. The eFuse is an active device and costs more, but it is predictable." },
{ t: "el-protection", d: 2, q: "Hot-plugging a large discharged bulk capacitor onto a live 24 V rail causes what?", o: ["A slow voltage rise", "A very large inrush current spike, which can weld connector contacts and drag down the rail", "Reverse current", "Nothing significant"], a: 1, why: "A discharged capacitor is momentarily a short circuit. The fixes are an inrush limiter such as an NTC, or a soft-start circuit that ramps a series MOSFET's gate to control the charging rate." },
{ t: "el-protection", d: 2, q: "Why must a TVS diode's standoff voltage be above the maximum normal operating voltage?", o: ["To reduce capacitance", "Otherwise it conducts continuously in normal operation and overheats", "To improve clamping", "To meet ESD standards"], a: 1, why: "The standoff is where it starts to conduct meaningfully. It must sit above the highest normal rail including tolerance and ripple, while its clamping voltage stays below what the protected part can survive." },
{ t: "el-protection", d: 3, q: "Why does a TVS on a high-speed data line need low capacitance?", o: ["To respond faster", "Its capacitance loads the line, degrading edges and causing reflections", "To reduce leakage", "To improve clamping"], a: 1, why: "A general-purpose TVS might be hundreds of picofarads, which is fatal for USB or Ethernet. Low-capacitance parts use a steering-diode topology to keep line capacitance to a picofarad or so." },
{ t: "el-protection", d: 3, q: "What is the risk of relying on a microcontroller pin's internal clamp diodes for protection?", o: ["They are too slow", "Injected current can lift the internal rail, disturbing other circuits or causing latch-up, and the diodes have a low current rating", "They add capacitance", "They only work on inputs"], a: 1, why: "The clamps are for incidental overshoot, not for external fault energy. A series resistor to limit injected current to the datasheet figure, plus an external clamp, is the correct arrangement." },
{ t: "el-protection", d: 3, q: "Why is an NTC inrush limiter a poor choice for equipment that may be power-cycled quickly?", o: ["It is too slow to respond", "It stays hot and low-resistance after operation, so it provides no limiting on an immediate restart", "It fails short", "It cannot handle DC"], a: 1, why: "The device needs tens of seconds to cool. Where fast recycling matters, an active soft-start with a MOSFET, or a relay that bypasses a resistor after charging, is the reliable answer." },

// ----------------------------------------------------------- el-clocks
{ t: "el-clocks", d: 2, q: "A crystal specifies CL of 12.5 pF and the board contributes 3 pF of stray. What should each load capacitor be?", o: ["12.5 pF", "About 19 pF", "About 6 pF", "About 25 pF"], a: 1, why: "CL is the series combination of the two capacitors plus stray, so C = 2*(CL - Cstray) = 2*(12.5-3) = 19 pF. Getting this wrong pulls the frequency, which is a common source of a clock that is out by tens of ppm." },
{ t: "el-clocks", d: 2, q: "What does probing a crystal pin directly with a standard 10 pF scope probe do?", o: ["Nothing measurable", "Adds capacitance that shifts the frequency and can stop oscillation altogether", "Shorts the oscillator", "Improves stability"], a: 1, why: "You are adding most of a load capacitor to a circuit tuned around a few picofarads. Probe the buffered clock output instead, or use a high-impedance active probe on the drive pin only." },
{ t: "el-clocks", d: 2, q: "An RTC crystal is rated 20 ppm. How much can it gain or lose per day?", o: ["About 0.2 seconds", "About 1.7 seconds", "About 20 seconds", "About 1 minute"], a: 1, why: "20 ppm of 86,400 seconds is 1.73 s per day, so around ten minutes a year. That is why anything needing better either calibrates against a network time source or uses a temperature-compensated part." },
{ t: "el-clocks", d: 2, q: "What is the strongest reason to specify a TCXO over a plain crystal?", o: ["Lower phase noise", "Frequency stability over temperature, when the product must hold accuracy across its full operating range", "Faster startup", "Lower cost"], a: 1, why: "A plain crystal can drift tens of ppm across temperature, dwarfing its initial tolerance. A TCXO compensates that, and is why radio and timing-critical products carry the extra cost." },
{ t: "el-clocks", d: 2, q: "What is the difference between jitter and frequency stability?", o: ["They are the same", "Jitter is short-term cycle-to-cycle variation; stability is long-term average frequency accuracy", "Jitter is measured in ppm", "Stability only matters for RTCs"], a: 1, why: "They have different customers: an ADC clock cares about jitter because it converts directly to sampling noise, while an RTC cares about stability. A part can be excellent at one and poor at the other." },
{ t: "el-clocks", d: 3, q: "A crystal oscillator sometimes fails to start at cold temperatures. What is the likely cause?", o: ["The load capacitors are too small", "Insufficient negative resistance margin, from too high a series resistance, too much load capacitance, or too low a drive level", "The crystal is cracked", "The supply is too high"], a: 1, why: "The rule of thumb is at least five times the crystal's maximum ESR in negative resistance. Cold raises ESR and reduces gain, which is why marginal designs start at room temperature and fail on the line." },
{ t: "el-clocks", d: 3, q: "Why can excessive crystal drive level be as bad as too little?", o: ["It raises the frequency", "It ages the crystal and can crack it, causing long-term drift or outright failure", "It increases jitter only", "It has no effect"], a: 1, why: "Datasheets give a maximum drive level in microwatts, and a series resistor on the drive pin is the usual way to limit it. Too little drive fails to start; too much shortens life, so both ends need checking." },
{ t: "el-clocks", d: 3, q: "Why does clock jitter set a hard limit on ADC performance at high input frequencies?", o: ["It changes the reference", "Timing uncertainty on a fast-slewing signal becomes amplitude error, so SNR is capped at -20*log10(2*pi*f*jitter)", "It aliases the input", "It affects only the digital output"], a: 1, why: "At 10 MHz input, 1 ps of jitter caps SNR around 84 dB regardless of how many bits the converter has. It is why high-speed converters specify clock jitter as tightly as their own noise." },

// ------------------------------------------------------ el-motor-drive
{ t: "el-motor-drive", d: 2, q: "What is shoot-through in an H-bridge leg?", o: ["Current flowing to the motor", "Both devices in one leg conducting simultaneously, shorting the supply through them", "Reverse current from the motor", "Regenerative braking"], a: 1, why: "It happens during switching, because turn-off is slower than turn-on. Dead time between the two commands prevents it, at the cost of body-diode conduction and a small output distortion." },
{ t: "el-motor-drive", d: 2, q: "What is the main limitation of a low-side shunt for motor current measurement?", o: ["It is too noisy", "It only sees current when the low-side device conducts, so it cannot measure continuously in all PWM states", "It needs an isolated amplifier", "It has too much loss"], a: 1, why: "The measurement has to be synchronised with the PWM, which constrains the minimum duty cycle you can measure at. In-line phase shunts see the current continuously but need a high-common-mode amplifier." },
{ t: "el-motor-drive", d: 2, q: "Decelerating a high-inertia load from a bench supply makes the bus voltage rise. Why?", o: ["The supply regulates poorly", "The motor acts as a generator and returns energy, but a bench supply cannot sink current, so the bus capacitance charges", "The bridge leaks", "Back-EMF exceeds the supply"], a: 1, why: "This is bus pumping, and it can exceed the capacitor and device ratings. A braking chopper that dumps the energy into a resistor, or a supply that can sink, is the fix." },
{ t: "el-motor-drive", d: 2, q: "A stepper rated at 2.8 V per winding is run from 24 V. Why?", o: ["To get more torque at standstill", "To force current into the winding inductance quickly, maintaining torque at speed, with a chopper drive limiting the current", "Because the rating is nominal", "To reduce heating"], a: 1, why: "The voltage rating is only the DC figure for rated current. At speed the inductance dominates, so a high supply and current-mode chopping is what keeps the current rising fast enough each step." },
{ t: "el-motor-drive", d: 2, q: "Why does an inductive load need a flyback path?", o: ["To reduce EMI", "The current cannot stop instantly, so without a path the voltage rises until something breaks down", "To improve efficiency", "To limit inrush"], a: 1, why: "V = L di/dt with a very large di/dt gives hundreds of volts. A diode across the load is the simple answer; a diode plus zener releases the energy faster at higher voltage, which matters for relay release time." },
{ t: "el-motor-drive", d: 3, q: "What does space vector modulation buy over sine PWM in a three-phase drive?", o: ["Lower switching frequency", "About 15 percent more usable bus voltage, by exploiting that only line-to-line voltages matter", "Simpler computation", "Lower current ripple only"], a: 1, why: "Adding a common-mode third-harmonic component shifts all three phases together, which the motor does not see, so more of the bus is available differentially. It is why SVM is standard in modern drives." },
{ t: "el-motor-drive", d: 3, q: "Why does a brushed DC motor's current spike at stall?", o: ["The inductance falls", "With no rotation there is no back-EMF, so current is limited only by winding resistance", "The commutator shorts", "The supply sags"], a: 1, why: "Stall current can be ten to fifty times the running current. It is why current limiting is not optional and why the drive must be rated for stall, not for nominal running." },
{ t: "el-motor-drive", d: 3, q: "In field-oriented control, what do the d and q axis currents represent?", o: ["Two phases of the supply", "d is the flux-producing component and q is the torque-producing component, in a rotor-aligned frame", "Direct and quadrature voltages", "Positive and negative sequence"], a: 1, why: "Holding d at zero and controlling q gives torque control as direct as a brushed motor. It needs rotor position, which is why FOC pairs with an encoder or a position observer." },

// ---------------------------------------------------------- el-layout
{ t: "el-layout", d: 2, q: "Above about 100 kHz, where does return current for a trace over a solid plane flow?", o: ["By the shortest path to the supply", "Directly beneath the trace, because that path has the lowest loop inductance", "Spread evenly across the plane", "Through the nearest via"], a: 1, why: "At low frequency it takes the lowest-resistance path; at high frequency inductance dominates. It is the whole reason a plane split under a high-speed trace is so damaging: the return has to detour." },
{ t: "el-layout", d: 2, q: "What is the modern recommendation for the ground under a precision ADC on a mixed-signal board?", o: ["A split plane with a single bridge at the ADC", "One solid unbroken plane, with placement and partitioning used to separate the noisy and quiet regions", "Separate planes joined by a ferrite", "No plane under the ADC"], a: 1, why: "Splitting creates a slot that return currents must go around, generating exactly the coupling it was meant to prevent. Control where currents flow by placement, not by cutting the plane." },
{ t: "el-layout", d: 2, q: "Moving a 100 nF decoupling capacitor from vias-in-pad at the IC to the end of a 5 mm thin trace does what?", o: ["Nothing measurable", "Adds series inductance, lowering its self-resonant frequency so it stops decoupling where it is needed", "Reduces its capacitance", "Improves the DC rail"], a: 1, why: "A few nanohenries of loop inductance dominates above a few tens of MHz. The loop through the capacitor and its vias is what matters, not the trace length alone, which is why via placement is the critical detail." },
{ t: "el-layout", d: 2, q: "When is the best time to stop a noisy buck converter polluting a precision front end?", o: ["During routing", "During placement, by physically separating them and orienting the switching loop away", "After the first EMC test", "With extra decoupling at the end"], a: 1, why: "Once the parts are placed, the coupling is largely decided; routing only tidies it. It is why placement deserves the majority of the layout effort and why autorouting a mixed-signal board rarely works." },
{ t: "el-layout", d: 2, q: "Why does a four-layer stackup usually outperform two layers for signal integrity?", o: ["It is thicker", "It provides adjacent reference planes, so every signal has a low-inductance return directly beneath it", "It has more copper for current", "It allows finer traces"], a: 1, why: "A two-layer board has no continuous reference, so loop areas are large and uncontrolled. The extra cost of four layers is usually less than the cost of one EMC retest." },
{ t: "el-layout", d: 3, q: "Why is a via in a high-speed signal path a problem beyond its inductance?", o: ["It adds resistance", "The unused portion forms a stub that resonates, and the return current must find a nearby ground via to change reference planes", "It weakens the board", "It increases capacitance only"], a: 1, why: "That is why back-drilling exists on very high-speed boards and why a stitching ground via next to every signal via matters: without it, the return has to detour to the nearest one." },
{ t: "el-layout", d: 3, q: "Why place an analogue island at the board edge near its connector?", o: ["For mechanical strength", "It keeps the sensitive path short and stops noisy return currents from elsewhere crossing under it", "It improves thermal performance", "It simplifies routing"], a: 1, why: "You are controlling which currents share the region, not isolating the ground. The connector location dictates the whole placement, which is a reason to fix connectors early." },
{ t: "el-layout", d: 3, q: "Why does the impedance of a trace depend on its distance to the reference plane?", o: ["It does not", "Impedance is set by the geometry of the conductor and its return path, so plane spacing and trace width together determine it", "Only trace width matters", "Only dielectric constant matters"], a: 1, why: "Width, height above the plane and dielectric constant together give the characteristic impedance. It is why the stackup must be fixed before controlled-impedance routing starts, not after." }

]);
