BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// -------------------------------------------------------------- emb-gdb
{ t: "emb-gdb", d: 2, q: "A variable is corrupted and you cannot find the writer. Which gdb feature answers it?", o: ["A breakpoint on every function", "A watchpoint on the variable, which stops on the write and gives you a backtrace", "More logging", "Single-stepping from main"], a: 1, why: "<p><code>watch rx_len</code>, continue, and the next stop is the culprit with a full call stack.</p><p>Cortex-M implements them in the DWT unit, so there are typically four and they want aligned addresses of 1, 2 or 4 bytes.</p>" },
{ t: "emb-gdb", d: 2, q: "You ask for more watchpoints than the hardware has. What happens?", o: ["gdb refuses", "It falls back to single-stepping the whole program, which is thousands of times slower and looks like a hang", "The oldest one is dropped", "It uses breakpoints instead"], a: 1, why: "<p>The failure presents as the debugger freezing rather than as an error, which is why knowing the DWT limit is worth having in your head.</p>" },
{ t: "emb-gdb", d: 2, q: "gdb prints &lt;optimized out&gt; and stepping jumps around. What does that indicate?", o: ["A broken debugger", "The build is optimised, so the machine code no longer corresponds to the source line by line", "The ELF does not match the flashed image", "The probe speed is too high"], a: 1, why: "<p>It is an accurate view rather than a fault. <code>-Og</code> is the development setting: it optimises but keeps the debug view honest.</p><p>Recognising it out loud is worth more in an interview than being puzzled by it.</p>" },
{ t: "emb-gdb", d: 2, q: "What does the <code>monitor</code> command do?", o: ["Watches a variable continuously", "Passes the rest of the line to the probe server rather than to gdb", "Displays memory as it changes", "Starts tracing"], a: 1, why: "<p>It is how you reach OpenOCD or J-Link commands such as <code>reset halt</code>, <code>reset init</code> and flash operations, which gdb itself knows nothing about.</p>" },
{ t: "emb-gdb", d: 2, q: "Which command reads a peripheral register block?", o: ["p reg", "x/8xw 0x40021000", "info registers", "ptype reg"], a: 1, why: "<p>Examine eight words in hex from that address, which answers 'did that write actually land' in one line.</p><p><code>info registers</code> shows the CPU's registers, not the peripheral's.</p>" },
{ t: "emb-gdb", d: 3, q: "On a Cortex-M fault, where is the PC of the faulting instruction?", o: ["In the PC register", "In the stacked exception frame, the seventh word from the frame base", "In BFAR", "In the LR"], a: 1, why: "<p>The frame holds R0 to R3, R12, LR, PC and xPSR. The live PC is inside the handler, so it tells you nothing about the fault.</p><p><code>x/8xw $sp</code> then <code>addr2line</code> against the ELF for that exact build gives you the line.</p>" },
{ t: "emb-gdb", d: 3, q: "Which register tells you what kind of Cortex-M fault occurred?", o: ["BFAR at 0xE000ED38", "CFSR at 0xE000ED28", "VTOR", "xPSR"], a: 1, why: "<p>The Configurable Fault Status Register splits into memory-manage, bus and usage fault bytes.</p><p>BFAR and MMFAR hold the offending <b>address</b>, and only when the corresponding valid bit in CFSR is set.</p>" },
{ t: "emb-gdb", d: 3, q: "Why is a conditional breakpoint often better than a plain one?", o: ["It is faster", "It fires only on the case you care about, which is what makes an intermittent bug findable", "It uses less hardware", "It works at -O2"], a: 1, why: "<p><code>b uart.c:214 if len &gt; 64</code> skips the thousands of ordinary passes.</p><p>Note that it is evaluated by gdb on the host, so the target halts every time and it is slow in a hot path.</p>" },

// ------------------------------------------------------------ emb-design
{ t: "emb-design", d: 2, q: "How should you open an answer to a system design question?", o: ["By choosing a microcontroller", "By asking what it has to do, in numbers rather than adjectives", "By drawing a block diagram", "By listing peripherals"], a: 1, why: "<p>Starting with a part number reveals that you have chosen before you have constrained.</p><p>Three or four well-chosen questions is enough; running through a checklist mechanically is its own kind of failure.</p>" },
{ t: "emb-design", d: 2, q: "For a battery product, which calculation changes the whole design?", o: ["Flash usage", "The average current budget from cell capacity and target life", "Clock speed", "Radio throughput"], a: 1, why: "<p>2000 mAh over a year is about 228 microamps average, and once you have that number the radio and sampling turn out to be rounding errors while sleep current is the design.</p><p>One calculation out loud is worth ten minutes of block diagram.</p>" },
{ t: "emb-design", d: 2, q: "What is the strongest unprompted signal in a design answer?", o: ["Naming the right part", "Naming the failure modes and what you would do about each", "A neat diagram", "Citing a standard"], a: 1, why: "<p>Flash wear, power loss mid-write, a dropped upload, clock drift, battery ageing under load, a bad update.</p><p>Each one is evidence you have shipped something rather than only designed it.</p>" },
{ t: "emb-design", d: 2, q: "Asked what you would build first, what is the best kind of answer?", o: ["The hardest subsystem", "A measurement that would invalidate the design if it came out wrong, such as real sleep current", "The user interface", "The communications stack"], a: 1, why: "<p>Building the feature first and discovering the constraint later is exactly the mistake the question probes for.</p>" },
{ t: "emb-design", d: 2, q: "A logger writes one record per second for a year. What does that force?", o: ["A bigger flash part", "Wear levelling or a log-structured store, because 31 million writes will exhaust a sector", "A faster bus", "Compression"], a: 1, why: "<p>Flash endurance is quoted per sector, typically 10,000 to 100,000 erase cycles, so erasing in place at that rate fails in weeks.</p><p>Appending records and compacting occasionally spreads the wear by construction.</p>" },
{ t: "emb-design", d: 3, q: "Why not erase logged data as soon as you have transmitted it?", o: ["Erasing is slow", "The transfer may not have arrived; wait for the peer to acknowledge so the worst case is a duplicate rather than a hole", "Flash needs time to settle", "It wastes power"], a: 1, why: "<p>Choosing which failure you prefer is the design decision, and a duplicate the consumer can discard is almost always better than data that no longer exists anywhere.</p>" },
{ t: "emb-design", d: 3, q: "Why can a battery that measures fine at rest still brown out during a radio burst?", o: ["The measurement is wrong", "Internal resistance rises with age and cold, so the load current pulls the terminal voltage down", "The radio draws more than rated", "Capacity is temperature dependent only"], a: 1, why: "<p>It is why a bulk capacitor near the radio and a brownout threshold that accounts for the burst both belong in the design.</p><p>Testing only at room temperature on a fresh cell misses it entirely.</p>" },
{ t: "emb-design", d: 3, q: "What is the second failure mode of a design answer, after starting with a part number?", o: ["Talking too long", "Refusing to commit: after asking the questions you have to pick something and defend it", "Drawing too much", "Asking questions"], a: 1, why: "<p>'I would use an RTOS because the BLE stack requires one, and I would keep the thread count small' is an answer. 'It depends' is not.</p>" },

// -------------------------------------------------------- emb-buildtools
{ t: "emb-buildtools", d: 2, q: "A Makefile rebuilds nothing when you edit a header. What is missing?", o: ["A clean target", "Header dependency generation: -MMD -MP and an -include of the generated .d files", "A .PHONY declaration", "Tab indentation"], a: 1, why: "<p>Without it make has no idea an object depends on a header, so you debug a stale object and lose an afternoon.</p><p>Two lines, and it is the difference between a Makefile that works and one that lies.</p>" },
{ t: "emb-buildtools", d: 2, q: "What does <code>-ffunction-sections</code> achieve on its own?", o: ["Smaller code immediately", "Little: it needs the linker's --gc-sections to discard the unreferenced sections", "Faster linking", "Better debug info"], a: 1, why: "<p>It places each function in its own section so the linker can drop the ones nothing references. The two only pay off together, which is why they are always quoted as a pair.</p>" },
{ t: "emb-buildtools", d: 2, q: "In modern CMake, what do PRIVATE, PUBLIC and INTERFACE control?", o: ["Symbol visibility in the binary", "Who inherits a setting: this target, consumers, or both", "Access to the source files", "Whether an option is required"], a: 1, why: "<p>It is what stops one library's private include path leaking across the project.</p><p>The old global commands, <code>include_directories</code> and <code>add_definitions</code>, applied to everything, which is exactly the problem the target commands replaced.</p>" },
{ t: "emb-buildtools", d: 2, q: "A compile flag seems to have no effect. What do you do first?", o: ["make clean", "Read the compile line that actually ran, with cmake --build -v or make -n", "Reinstall the toolchain", "Check the documentation"], a: 1, why: "<p>The build files tell you your intention; the compile line tells you the result.</p><p>Almost every case is a target-versus-global scope mistake, and reading the line exposes it in seconds.</p>" },
{ t: "emb-buildtools", d: 2, q: "Why must -mfloat-abi agree across every object and library?", o: ["It only affects speed", "It decides whether floats pass in FPU registers or core registers, so a mismatch fails to link or silently passes arguments in the wrong place", "It sets the FPU clock", "It is a warning only"], a: 1, why: "<p>The link error is the good outcome. The bad one is a mixed build that runs and produces nonsense from any function taking a float.</p>" },
{ t: "emb-buildtools", d: 3, q: "Why does a bare-metal CMake toolchain file need CMAKE_TRY_COMPILE_TARGET_TYPE set to STATIC_LIBRARY?", o: ["To build faster", "Otherwise CMake tries to link a test executable during configure, which fails with no startup code or linker script", "It selects the archiver", "It disables optimisation"], a: 1, why: "<p>Configure-time compiler detection assumes a hosted environment. Telling it to stop at a static library skips the link.</p><p><code>CMAKE_SYSTEM_NAME Generic</code> is the other half: it says there is no operating system.</p>" },
{ t: "emb-buildtools", d: 3, q: "Why is <code>.PHONY: clean</code> needed?", o: ["It runs clean first", "So make does not skip the recipe if a file named clean happens to exist", "It suppresses output", "It makes clean run in parallel"], a: 1, why: "<p>make decides by comparing timestamps of files, so a target that is not a file has to be declared as such, or an unrelated file with that name silently disables it.</p>" },
{ t: "emb-buildtools", d: 3, q: "What does -g3 cost in the flashed image?", o: ["Roughly 20 percent", "Nothing: debug information lives in the ELF and is not part of the binary you flash", "It doubles the size", "It prevents optimisation"], a: 1, why: "<p>Which is why there is no reason to build a release without it, provided you archive the ELF. A fault address from the field only decodes against the symbols from that exact build.</p>" }

]);
