// Questions for the seven Robotics lessons that had none.
BANKS["Robotics"] = BANKS["Robotics"].concat([

// ------------------------------------------------------------ rob-manip
{ t: "rob-manip", d: 2, q: "What is an arm's dexterous workspace?", o: ["Everywhere the tool tip can reach", "The points it can reach in any orientation", "The region free of singularities", "The volume within the first joint's range"], a: 1, why: "It is a strict subset of the reachable workspace and is usually much smaller. Quoting reachable workspace in a specification while the application needs arbitrary orientation is a classic sizing mistake." },
{ t: "rob-manip", d: 2, q: "How many distinct IK solutions does a typical 6R arm with a spherical wrist have for one tool pose?", o: ["One", "Up to eight", "Two", "Infinitely many"], a: 1, why: "Shoulder left or right, elbow up or down, wrist flipped or not: two cubed. The controller must choose deliberately, because switching branch mid-trajectory means a large unplanned motion." },
{ t: "rob-manip", d: 2, q: "What is the practical symptom of approaching a singularity?", o: ["The arm stops", "Small Cartesian motions demand enormous joint velocities, so the arm lurches or faults on a speed limit", "Position accuracy improves", "Torque falls to zero"], a: 1, why: "The Jacobian loses rank, so its inverse blows up in one direction. Damped least squares limits the velocity at the cost of tracking error, which is the usual practical compromise." },
{ t: "rob-manip", d: 2, q: "Why add compliance at the gripper?", o: ["To increase speed", "Position error is inevitable, so compliance absorbs it instead of generating large contact forces", "To reduce weight", "To simplify kinematics"], a: 1, why: "A stiff arm with millimetre error against a rigid part generates enormous force. Passive compliance such as an RCC device, or active force control, is what makes assembly tolerant of that error." },
{ t: "rob-manip", d: 2, q: "What does force control require that position control does not?", o: ["A faster processor", "A measurement of contact force, and an environment whose stiffness is known well enough to remain stable", "More degrees of freedom", "Higher gear ratios"], a: 1, why: "Contact with a stiff environment closes a very high-gain loop through the mechanics, which readily goes unstable. It is why impedance control, which regulates the relationship rather than the force directly, is often preferred." },
{ t: "rob-manip", d: 3, q: "What does a form closure grasp guarantee that a force closure grasp does not?", o: ["Higher grip force", "The object is geometrically constrained regardless of friction", "Faster grasping", "Lower contact stress"], a: 1, why: "Form closure survives a slippery or unknown surface, which is why it is preferred for safety-critical handling. Force closure needs fewer contacts but depends on a friction coefficient you rarely know accurately." },
{ t: "rob-manip", d: 3, q: "Why is the manipulability index worth computing along a planned path?", o: ["It predicts cycle time", "It measures distance from singularity, so a low value warns of a lurch before the arm gets there", "It estimates payload", "It checks joint limits"], a: 1, why: "It is essentially the product of the Jacobian's singular values. Planning to keep it above a threshold avoids the region rather than handling the symptom with velocity damping." },
{ t: "rob-manip", d: 3, q: "Why does a redundant (7-DOF) arm need a secondary objective?", o: ["To improve accuracy", "The IK has infinitely many solutions, so something must select among them, such as avoiding joint limits or obstacles", "To reduce cost", "To handle singularities"], a: 1, why: "Null-space motion changes the elbow position without moving the tool, which is exactly what lets a 7-DOF arm reach around obstacles. Without a criterion, the solver's choice is arbitrary and possibly unrepeatable." },

// -------------------------------------------------------- rob-dynamics
{ t: "rob-dynamics", d: 2, q: "Load inertia seen at the motor through an N:1 gearbox is what?", o: ["N times the load inertia", "The load inertia divided by N squared", "N squared times the load inertia", "Unchanged"], a: 1, why: "Reflected inertia scales as 1/N^2, which is why gearing makes a large load look manageable. It is also why a high ratio makes the motor dominate and the load feel disconnected." },
{ t: "rob-dynamics", d: 2, q: "Which torque figure should size a motor's continuous rating?", o: ["Peak torque", "The RMS torque over the duty cycle, since heating goes as current squared", "Mean torque", "Stall torque"], a: 1, why: "Copper loss is I^2*R, so it is the RMS current that determines steady temperature. Peak torque sizes the drive and the demagnetisation limit, but not the thermal rating." },
{ t: "rob-dynamics", d: 2, q: "Why is a very high gear ratio problematic on a legged robot?", o: ["It is too heavy", "Reflected motor inertia and friction make the joint non-backdrivable, so impacts are transmitted rather than absorbed", "It reduces torque", "It slows control loops"], a: 1, why: "Legged robots need to sense and yield to contact. High-ratio drives hide the load from the motor and the motor from the load, which is why quasi-direct-drive with ratios under about 10 became standard." },
{ t: "rob-dynamics", d: 2, q: "What does oversizing a wrist motor on a small arm typically cause?", o: ["Better performance", "Extra mass at the end of the chain, which raises inertia for every upstream joint and slows the whole arm", "Lower efficiency only", "Nothing measurable"], a: 1, why: "Distal mass is the most expensive mass on a manipulator. It is why arms taper and why wrist actuators are sometimes moved to the base and driven by belts or cables." },
{ t: "rob-dynamics", d: 2, q: "What does a friction budget need to include beyond bearing friction?", o: ["Only viscous drag", "Gearbox efficiency, seal drag, cable and hose stiffness, and the Coulomb term that must be overcome to start moving", "Air resistance", "Electrical losses"], a: 1, why: "Cable carriers and seals are routinely underestimated and can dominate on a small joint. The breakaway term is the one that determines whether fine positioning is even possible." },
{ t: "rob-dynamics", d: 3, q: "Why does gravity compensation improve a manipulator's control performance?", o: ["It reduces motor current only", "It removes a large, known, configuration-dependent torque from the feedback loop's job, so the gains can be tuned for dynamics rather than for holding", "It linearises the kinematics", "It eliminates friction"], a: 1, why: "It is feedforward from a model you already have. Without it the integrator carries the gravity load, which means large standing effort and poor response to real disturbances." },
{ t: "rob-dynamics", d: 3, q: "What is the practical significance of the mass matrix being configuration dependent?", o: ["It complicates simulation only", "The effective inertia at a joint changes as the arm moves, so a single set of fixed gains cannot be optimal everywhere", "It causes singularities", "It affects only heavy arms"], a: 1, why: "An arm extended has far more inertia about the base than one folded. Gain scheduling on configuration, or computed-torque control that inverts the model, is the response." },
{ t: "rob-dynamics", d: 3, q: "Why does back-EMF constant relate directly to torque constant in a DC motor?", o: ["Coincidence of units", "They are the same physical constant in SI units, because the machine is reversible and energy conserving", "Only for brushless motors", "They are unrelated"], a: 1, why: "Ke in V*s/rad equals Kt in N*m/A. It gives you a free cross-check on a datasheet and a way to estimate one when only the other is quoted." },

// -------------------------------------------------------- rob-planning
{ t: "rob-planning", d: 2, q: "Why do grid-based planners become impractical for a 6-DOF arm?", o: ["They are too slow to initialise", "The configuration space grows exponentially with dimension, so a grid at useful resolution is astronomically large", "They cannot handle obstacles", "They give suboptimal paths"], a: 1, why: "Ten cells per axis over six axes is a million states, and ten is a very coarse resolution for a joint. Sampling-based planners avoid building the space at all." },
{ t: "rob-planning", d: 2, q: "What is the main structural difference between PRM and RRT?", o: ["PRM is faster", "PRM builds a reusable roadmap of the whole space up front; RRT grows a tree from the start towards the goal for a single query", "RRT is optimal", "PRM handles dynamics"], a: 1, why: "PRM amortises across many queries in a static environment, which suits a fixed workcell. RRT suits single queries and changing environments, which is why mobile robots favour it." },
{ t: "rob-planning", d: 2, q: "Why are raw paths from sampling planners jagged?", o: ["Poor collision checking", "They connect random samples, so the path is feasible but has no reason to be smooth or short", "The resolution is too low", "The goal bias is wrong"], a: 1, why: "Feasibility is all the planner promises. Shortcutting, which repeatedly tries to connect non-adjacent waypoints directly, plus spline fitting, is the standard post-process." },
{ t: "rob-planning", d: 2, q: "When is kinodynamic planning required?", o: ["For all mobile robots", "When the system cannot follow an arbitrary geometric path, because of velocity, acceleration or non-holonomic constraints", "For arms only", "When obstacles move"], a: 1, why: "A car cannot move sideways and a quadrotor cannot stop instantly. Planning geometrically then hoping the controller copes fails exactly when the path violates those constraints." },
{ t: "rob-planning", d: 2, q: "What is configuration space?", o: ["The robot's workspace", "The space of joint values, in which the robot is a point and obstacles become complicated regions", "The space of possible velocities", "The map of the environment"], a: 1, why: "The trade is that collision checking becomes hard while path finding becomes easy. It is the central idea that makes motion planning tractable at all." },
{ t: "rob-planning", d: 3, q: "What does RRT* add over RRT?", o: ["Faster first solution", "Asymptotic optimality: it rewires the tree as samples accumulate, so the path converges towards optimal", "Handling of dynamics", "Guaranteed completeness"], a: 1, why: "Plain RRT finds a feasible path quickly and it may be poor. RRT* costs more per sample and gives a path that keeps improving with time, which suits an anytime planner." },
{ t: "rob-planning", d: 3, q: "Where is the boundary between planning and control?", o: ["Planning is offline, control is online", "Planning produces a reference the controller must track; the controller handles disturbance and model error along it", "Planning handles obstacles, control handles speed", "There is no boundary"], a: 1, why: "The interface is a trajectory, and its properties matter: it must be dynamically feasible and smooth enough to differentiate for feedforward. Blur the boundary and you get a planner that oscillates or a controller that cuts corners into obstacles." },
{ t: "rob-planning", d: 3, q: "What does probabilistic completeness mean for a sampling planner?", o: ["It always finds the optimal path", "If a solution exists, the probability of finding it approaches 1 as samples increase, but failure is never proof there is none", "It fails at most 5 percent of the time", "It is complete only in low dimensions"], a: 1, why: "So a timeout tells you nothing definite, which matters when the answer feeds a safety decision. Narrow passages are where the sample count required becomes impractical." },

// -------------------------------------------------------------- rob-vo
{ t: "rob-vo", d: 2, q: "For fixed pixel matching error, how does stereo depth error grow with distance?", o: ["Linearly", "With the square of the distance", "As the square root", "It is constant"], a: 1, why: "Depth is baseline times focal length over disparity, and disparity falls as 1/Z, so the error in Z goes as Z^2. It is why stereo is excellent close in and nearly useless far out for a given baseline." },
{ t: "rob-vo", d: 2, q: "What can monocular visual odometry fundamentally not recover?", o: ["Rotation", "Absolute scale", "Direction of travel", "Feature correspondence"], a: 1, why: "A large scene far away looks identical to a small one nearby. The fixes are a second camera, an IMU whose accelerometer provides metric scale, a wheel odometer, or a known object size." },
{ t: "rob-vo", d: 2, q: "Why is pure rotation a degenerate case for monocular VO?", o: ["Features move too fast", "Without translation there is no parallax, so no depth information is available and triangulation fails", "The images blur", "Rotation is hard to estimate"], a: 1, why: "The homography relating the views has no depth content at all. A robot that turns on the spot is exactly this case, which is why VO systems detect it and skip triangulation rather than producing nonsense." },
{ t: "rob-vo", d: 2, q: "How is accumulated VO drift best cancelled?", o: ["Better feature detection", "Loop closure, recognising a previously visited place and correcting the whole trajectory", "Higher frame rate", "A longer baseline"], a: 1, why: "Drift is integrated error, so it grows without bound whatever the per-frame accuracy. Loop closure is what makes VO into SLAM, and it is why place recognition matters as much as the front end." },
{ t: "rob-vo", d: 2, q: "What is the classic failure mode of feature-based VO?", o: ["Too many features", "Texture-poor scenes such as a blank wall, plus motion blur, repetitive patterns and rapid lighting changes", "High frame rates", "Wide-angle lenses"], a: 1, why: "No features means no correspondences and no estimate at all. Direct methods that use intensity gradients rather than sparse features cope better in low texture but are more sensitive to exposure changes." },
{ t: "rob-vo", d: 3, q: "Why does RANSAC appear in nearly every VO pipeline?", o: ["To speed up matching", "Feature correspondences always contain gross outliers, and least squares is destroyed by even a few", "To detect features", "To calibrate the camera"], a: 1, why: "It fits a model to random minimal subsets and keeps the one with most inliers, so mismatches are rejected rather than averaged in. Any estimation on real correspondences without it is fragile." },
{ t: "rob-vo", d: 3, q: "Why does an IMU complement a camera so well in visual-inertial odometry?", o: ["It is cheaper", "The IMU is accurate over short intervals and drifts over long ones, while vision is drift-free but fails during fast motion and in low texture", "It measures depth", "It removes the need for calibration"], a: 1, why: "Their failure modes are almost disjoint. The IMU also resolves monocular scale and gives a gravity direction, which fixes roll and pitch absolutely." },
{ t: "rob-vo", d: 3, q: "Why does a rolling-shutter camera degrade VO?", o: ["Lower resolution", "Each row is exposed at a different time, so a moving camera distorts the geometry the estimator assumes", "It is noisier", "Frame rate is lower"], a: 1, why: "The pinhole model assumes one instant per image. Global shutter avoids it, or the rolling-shutter timing must be modelled explicitly, which most simple pipelines do not do." },

// ----------------------------------------------------------- rob-comms
{ t: "rob-comms", d: 2, q: "How does CAN bus arbitration work?", o: ["Time slots assigned in advance", "Bitwise: nodes transmit identifiers and monitor the bus, and a node writing recessive while reading dominant backs off", "A token passes between nodes", "The master polls each node"], a: 1, why: "The lowest numeric identifier wins and its message is undamaged, so the highest-priority frame suffers no delay from the collision. It is why CAN is deterministic for high-priority traffic." },
{ t: "rob-comms", d: 2, q: "What is the strongest reason to keep motor control loops off a WiFi link?", o: ["Bandwidth", "Latency is unbounded: retries and contention give a long tail, and a control loop needs a deadline not an average", "Encryption overhead", "Range"], a: 1, why: "The median latency may look fine while the 99.9th percentile is hundreds of milliseconds. Control loops belong local to the actuator, with the network carrying setpoints and telemetry." },
{ t: "rob-comms", d: 2, q: "What should every telemetry packet carry?", o: ["A checksum only", "A timestamp and a sequence number, so you can detect loss, reordering and delay after the fact", "The full system state", "A device serial number"], a: 1, why: "Without a sequence number you cannot tell a dropped packet from a slow one, and without a timestamp you cannot align it with other sensors. They cost a few bytes and make field debugging possible." },
{ t: "rob-comms", d: 2, q: "When the teleoperation link drops, what should the robot do?", o: ["Continue the last command", "Enter a predefined safe state after a short timeout, typically stopping in a controlled way", "Stop instantly with no ramp", "Return to base autonomously"], a: 1, why: "Continuing the last command is how a driverless vehicle keeps going into an obstacle. The behaviour has to be designed and tested, and an abrupt stop can itself be unsafe on a heavy machine." },
{ t: "rob-comms", d: 2, q: "Why is CAN's 8-byte payload (in classic CAN) not the limitation it sounds?", o: ["It is easily extended", "Robot telemetry and commands are mostly small scalars, and the low overhead plus prioritisation matters more than payload size", "Compression is used", "Most nodes send less than 8 bytes"], a: 1, why: "A joint command or an encoder reading fits comfortably. CAN FD raises it to 64 bytes where needed, and bulk data belongs on Ethernet anyway." },
{ t: "rob-comms", d: 3, q: "Why does a CAN node go bus-off, and what does it protect?", o: ["A wiring fault only", "Its transmit error counter exceeded 255, so it removes itself to stop a faulty node jamming the bus for everyone", "The bus is idle too long", "Arbitration was lost too often"], a: 1, why: "It is the fault-confinement mechanism, and the recovery must be deliberate: automatic re-enable can produce a node that repeatedly disrupts the bus. Log every occurrence rather than silently recovering." },
{ t: "rob-comms", d: 3, q: "Why does time synchronisation matter across robot subsystems?", o: ["For logging tidiness", "Fusion requires knowing when each measurement was taken; a few milliseconds of skew is metres of error at speed", "To reduce bandwidth", "To order CAN frames"], a: 1, why: "At 10 m/s, 5 ms is 50 mm. PTP, or timestamping at the sensor against a shared clock, is what makes lidar, camera and IMU data combinable at all." },
{ t: "rob-comms", d: 3, q: "Why prefer UDP over TCP for high-rate robot telemetry?", o: ["It is more reliable", "TCP's retransmission and in-order delivery mean stale data blocks fresh data; for telemetry the newest sample matters more than a complete history", "It is encrypted", "It uses less bandwidth"], a: 1, why: "Head-of-line blocking is the specific problem: one lost packet stalls everything behind it. For commands that must not be lost, the answer is application-level acknowledgement, not TCP." },

// -------------------------------------------------------------- rob-rl
{ t: "rob-rl", d: 2, q: "What is reward hacking?", o: ["Tampering with the reward function", "The policy finds a way to score highly that satisfies the reward while defeating the intent behind it", "Rewards becoming unstable during training", "Overfitting to the training environment"], a: 1, why: "A walking robot that learns to fall forward repeatedly because forward displacement is rewarded is the standard example. It is a specification failure, and it is why reward design takes longer than training." },
{ t: "rob-rl", d: 2, q: "What is domain randomisation for?", o: ["Speeding up training", "Varying simulator parameters so the policy must be robust across them, which usually includes the real values", "Generating more data", "Preventing reward hacking"], a: 1, why: "You randomise mass, friction, latency, sensor noise and delays. The policy learns a behaviour that works for a family of dynamics rather than exploiting one exact model." },
{ t: "rob-rl", d: 2, q: "Before closing the loop with a trained policy on hardware, what is the most critical check?", o: ["Training reward converged", "That the action space is limited and a supervisory layer can override, so the worst commanded action is survivable", "The simulator matched reality closely", "The policy is deterministic"], a: 1, why: "A policy encountering an unseen state can output anything. The bound has to be enforced outside the policy, by torque limits, rate limits and a controller that can take over." },
{ t: "rob-rl", d: 2, q: "Which task does classical control clearly win over RL?", o: ["Legged locomotion on rough ground", "Regulating a well-modelled linear system, such as a motor current loop", "Dexterous in-hand manipulation", "Vision-based grasping"], a: 1, why: "The model is known, the objective is expressible and the result is provable. Using RL there costs enormously more and gives up the stability argument for no benefit." },
{ t: "rob-rl", d: 2, q: "What is the sim-to-real gap?", o: ["Slower execution on hardware", "The difference between simulated and real dynamics, which a policy trained only in simulation may have exploited", "Sensor noise", "Latency in the control loop"], a: 1, why: "The classic offenders are contact and friction models, actuator dynamics and unmodelled delay. Domain randomisation, system identification and fine-tuning on hardware are the standard responses." },
{ t: "rob-rl", d: 3, q: "Why does the MDP framing require the state to be Markovian?", o: ["To make training faster", "The policy maps state to action, so anything the decision depends on must be in the state, or the problem is partially observed", "To guarantee convergence", "To allow discounting"], a: 1, why: "Velocity, contact state and recent history frequently have to be included explicitly. Getting this wrong makes a task look unlearnable when the real problem is an inadequate observation." },
{ t: "rob-rl", d: 3, q: "What does the discount factor gamma control?", o: ["Learning rate", "How far ahead the policy effectively plans; near 1 values long-term return, lower values act greedily", "Exploration", "Reward magnitude"], a: 1, why: "It also bounds the value function, which helps numerically. Too low gives short-sighted behaviour; too close to 1 makes credit assignment over long horizons very hard." },
{ t: "rob-rl", d: 3, q: "Why is sparse reward hard, and what is the honest fix?", o: ["It trains slowly; use a bigger network", "Random exploration almost never reaches the reward, so there is no gradient; the fixes are shaping, curricula or demonstrations", "It causes overfitting; add regularisation", "It is not a real problem"], a: 1, why: "Shaping risks reward hacking, so it needs care. Demonstrations or a curriculum of progressively harder tasks are often more robust than inventing intermediate rewards." },

// ------------------------------------------------------ rob-integration
{ t: "rob-integration", d: 2, q: "When should sensor data be timestamped?", o: ["When it is logged", "At acquisition, as close to the sensor as possible, against a shared clock", "When it is received by the fusion node", "It does not matter if rates are known"], a: 1, why: "Anything later includes transport and scheduling delay that varies unpredictably. Fusion is only as good as the timing, and a variable stamp is worse than a known constant offset." },
{ t: "rob-integration", d: 2, q: "What is the most valuable property of a robot's logs for field debugging?", o: ["Small size", "Enough to replay the decision: inputs, internal state and outputs together with consistent timestamps", "High frequency", "Human readability"], a: 1, why: "Logging only the outputs tells you what happened and never why. Being able to feed the recorded inputs back through the same code offline is what turns a field report into a fixable bug." },
{ t: "rob-integration", d: 2, q: "What is a sound integration order?", o: ["Everything at once, then debug", "Bottom up: power, then comms, then each sensor and actuator alone, then closed loops, then autonomy", "Autonomy first, hardware last", "Alphabetically by subsystem"], a: 1, why: "Each stage rests on something already proven, so a new fault has a small candidate set. Integrating everything at once means every symptom has dozens of possible causes." },
{ t: "rob-integration", d: 2, q: "The day before a demo, what is the highest-value activity?", o: ["Adding the last feature", "Running the full demo end to end, repeatedly, on the actual hardware in the actual conditions", "Refactoring the code", "Writing documentation"], a: 1, why: "Almost every demo failure is something that was never rehearsed in full: a battery, a network, a startup order, a lighting condition. New features the night before are how demos get broken." },
{ t: "rob-integration", d: 2, q: "Why does logging need to be designed rather than added later?", o: ["It affects performance", "Bandwidth, storage, timestamping and what constitutes a complete record all have to be planned, and the first field failure is too late to discover a gap", "Log formats are hard to change", "It is required by standards"], a: 1, why: "The moment you need the log is the moment you cannot add to it. Deciding what a replayable record contains is a design activity with real cost in bandwidth and storage." },
{ t: "rob-integration", d: 3, q: "How do you reproduce a field failure that happens once a week?", o: ["Run it for a week", "Capture enough logged state to replay it offline, and raise the rate of the suspected cause to make it frequent", "Add more sensors", "Increase the log level and wait"], a: 1, why: "Replay converts an intermittent field problem into a deterministic desktop one. Where replay is impossible, stressing the suspected mechanism, such as load, temperature or network loss, is the alternative." },
{ t: "rob-integration", d: 3, q: "Why is a hardware abstraction layer worth its cost on a robot?", o: ["It improves performance", "It lets the whole stack run against simulated or recorded hardware, so most software can be developed and tested without the robot", "It reduces code size", "It is required by ROS"], a: 1, why: "Robot hardware is scarce, fragile and shared. Being able to test perception and planning against recorded data while someone else has the robot is usually the difference between one team member working and all of them." },
{ t: "rob-integration", d: 3, q: "Why should subsystem versions be logged at every startup?", o: ["For licensing", "So a field failure can be tied to an exact combination of firmware, software and configuration", "To detect tampering", "To measure uptime"], a: 1, why: "A robot is many independently versioned parts, and the interesting failures often come from a combination rather than one component. Without the record, reproduction starts with guessing what was installed." }

]);
