// Questions for the eight Control lessons that had none.
BANKS["Control"] = BANKS["Control"].concat([

// -------------------------------------------------------------- ct-freq
{ t: "ct-freq", d: 2, q: "A closed loop has 35 Hz bandwidth. What rise time does that imply?", o: ["About 1 ms", "About 10 ms", "About 100 ms", "About 300 ms"], a: 1, why: "Rise time is roughly 0.35 divided by bandwidth in Hz, so 0.35/35 is 10 ms. Bandwidth and rise time are the same fact stated in two domains, which is why you can convert a time-domain requirement into a loop specification immediately." },
{ t: "ct-freq", d: 2, q: "Where is phase margin measured?", o: ["At the resonant peak", "At the gain crossover frequency", "At DC", "At the phase crossover frequency instead"], a: 1, why: "That is where the open-loop magnitude passes 0 dB. It is how much extra lag the loop can absorb before the phase reaches -180 degrees there. Gain margin is the complementary number, measured where the phase crosses -180." },
{ t: "ct-freq", d: 2, q: "Why does a mechanical resonance above crossover threaten stability?", o: ["It shifts the crossover frequency", "Its gain peak can push the magnitude above 0 dB again", "It adds steady-state error", "It saturates the actuator"], a: 1, why: "That happens at a frequency where the phase has already fallen past -180. The loop then has a second crossing with no margin. The fixes are a notch at the resonance, rolling off harder before it, or stiffening the mechanics to move it further out." },
{ t: "ct-freq", d: 2, q: "In loop-shaping terms, what is integral action for?", o: ["Improving damping", "Very high gain at low frequency", "An increasing bandwidth as a result", "Adding phase lead"], a: 1, why: "That drives the steady-state error to zero. It costs 90 degrees of phase lag, which is why too much integral eats phase margin. Derivative or lead action does the opposite: it adds phase near crossover at the cost of noise amplification." },
{ t: "ct-freq", d: 2, q: "What does a resonant peak in the closed-loop magnitude response indicate?", o: ["High bandwidth", "Low damping in the closed loop", "Particularly good disturbance rejection", "Integral windup"], a: 1, why: "It shows as overshoot and ringing in the step response. A peak of about 2.3 dB corresponds to roughly 0.7 damping, which is the usual target. The peak height and the step overshoot are two views of the same pole locations." },
{ t: "ct-freq", d: 3, q: "Why is a sensor's own bandwidth a hard limit on loop bandwidth?", o: ["It is not, only the actuator matters", "Sensor lag appears inside the loop as phase lag", "It only affects noise", "It changes the DC gain"], a: 1, why: "You cannot close the loop faster than you can measure. A filter added to clean up sensor noise does the same thing, which is the real cost of that filter. It is why the rule of thumb is a sensor at least five to ten times the intended loop bandwidth." },
{ t: "ct-freq", d: 3, q: "How much phase lag does a pure time delay T contribute at frequency omega?", o: ["A constant 90 degrees", "omega*T radians", "It contributes gain, not phase", "45 degrees at 1/T"], a: 1, why: "It grows without bound with frequency. Delay costs phase and nothing else, and it grows linearly, so it sets a hard ceiling on achievable bandwidth. It is why sampling, computation and communication delay all have to be in the budget explicitly." },
{ t: "ct-freq", d: 3, q: "What does the sensitivity function tell you, and what is the waterbed effect?", o: ["Only steady-state error", "How disturbances and reference errors pass through", "The noise floor", "The actuator range that is going to be needed for it"], a: 1, why: "Reducing it at one frequency necessarily raises it elsewhere. Bode's integral makes the trade formal for most real systems: the area under log sensitivity is conserved. Pushing error down in band is paid for with a peak just above crossover." },

// ------------------------------------------------------------- ct-sysid
{ t: "ct-sysid", d: 2, q: "In a first-order-plus-dead-time fit, what does the ratio of dead time L to time constant tau tell you?", o: ["The steady-state gain", "How hard the loop will be to control", "The sample rate that is going to be needed", "The noise level"], a: 1, why: "A large L/tau severely limits achievable bandwidth. Below about 0.1 the process is easy and PID does well. Above about 1 it is dead-time dominated, and you need a Smith predictor or you accept a slow loop." },
{ t: "ct-sysid", d: 2, q: "Why does naively fitting a model to data logged under feedback mislead?", o: ["The data is noisier", "The controller correlates the input with the disturbance", "Closed-loop data simply has a good deal less bandwidth to it", "It cannot be done at all"], a: 1, why: "The fit can then identify the inverse controller rather than the plant. The excitation is not independent of the output. The fixes are injecting an external test signal at the reference or the actuator, or using a closed-loop identification method that accounts for the feedback." },
{ t: "ct-sysid", d: 2, q: "When is a frequency sweep preferred over a step test?", o: ["Always", "When you need accurate dynamics over a band", "Only for electrical systems", "When you have only very little time available"], a: 1, why: "Especially near resonances, and when the plant cannot take a large step. A sweep concentrates energy where you are measuring, so the signal-to-noise is far better at each frequency. A step is quick and gives a usable low-order model but resolves resonances poorly." },
{ t: "ct-sysid", d: 2, q: "What is the argument against fitting a sixth-order model to step-test data?", o: ["It takes too long to compute", "A step only ever excites a narrow band", "High-order models are always wrong", "The solver will not converge"], a: 1, why: "The extra parameters fit noise rather than dynamics, so the model will not generalise. The fit looks better because more parameters always fit better. Validating against a different dataset is what exposes it, and it is why model order should be justified rather than maximised." },
{ t: "ct-sysid", d: 2, q: "What makes an input signal persistently exciting?", o: ["A sufficiently large amplitude throughout", "It contains enough distinct frequencies", "It is periodic", "It is a step"], a: 1, why: "That identifies every parameter in the model. A single sine identifies at most two parameters, so a constant input identifies nothing dynamic. This is why PRBS and chirps are the standard identification inputs." },
{ t: "ct-sysid", d: 3, q: "How should you validate an identified model?", o: ["Check the fit on the identification data", "Check it against data that it has never seen", "Compare parameters with the datasheet", "Confirm it is stable"], a: 1, why: "Ideally at a different operating point or excitation. Fit on the training data always improves with model order, so it cannot detect over-fitting. Residuals that still correlate with the input mean there is structure the model has not captured." },
{ t: "ct-sysid", d: 3, q: "Why is a PRBS a good identification input?", o: ["It is easy to generate only", "It is broadband like noise, but deterministic", "It is a pure sine", "It has the highest possible energy"], a: 1, why: "It is repeatable, with a controllable amplitude the actuator can take. It excites many frequencies at once with modest amplitude, so you get the whole band in one short experiment without pushing the plant far from its operating point. The clock rate sets the bandwidth excited." },
{ t: "ct-sysid", d: 3, q: "Your step response shows an initial dip in the wrong direction. What does that indicate?", o: ["A measurement error somewhere", "A right-half-plane zero", "Excessive dead time", "Sensor saturation"], a: 1, why: "It fundamentally limits achievable bandwidth. Non-minimum-phase behaviour cannot be cancelled by a controller, because inverting it would be unstable. Boiler drum level and some flexible structures show it, and the only honest response is a slower loop." },

// ---------------------------------------------------------------- ct-ff
{ t: "ct-ff", d: 2, q: "What is the division of labour between feedforward and feedback?", o: ["Feedforward handles noise, feedback handles setpoints", "Feedforward handles what you can predict, feedback the rest", "They do the same job redundantly", "Feedback is for fast dynamics only"], a: 1, why: "Feedback corrects what you got wrong. Feedforward acts before the error exists, so it is not limited by stability margins. Feedback is the safety net that covers model error, disturbances and anything unmodelled." },
{ t: "ct-ff", d: 2, q: "Why does acceleration feedforward work on a servo axis?", o: ["It increases loop gain", "Torque required is inertia times acceleration", "It filters the encoder", "It compensates for the friction in the drive train"], a: 1, why: "It is known from the trajectory before the axis moves. The feedback loop no longer has to generate an error to produce the torque. Velocity feedforward against viscous friction and a constant term against Coulomb friction complete the usual set." },
{ t: "ct-ff", d: 2, q: "How does a disturbance observer estimate the disturbance?", o: ["From a dedicated sensor", "By comparing measured output with the model's prediction", "From the setpoint", "By differentiating the error signal with respect to the time"], a: 1, why: "The nominal plant model predicts it from the applied input. Whatever the model does not explain is treated as an equivalent input disturbance and subtracted. It is a way of getting disturbance rejection without measuring the disturbance directly." },
{ t: "ct-ff", d: 2, q: "In a system with feedforward, the feedback effort has a persistent nonzero average. What does that mean?", o: ["The loop is unstable", "The feedforward model is systematically wrong", "The sensor noise is simply far too high in this case", "The gains are too low"], a: 1, why: "Feedback is quietly making up the difference. Feedforward should carry the predictable load and leave feedback centred on zero. A standing bias is a free diagnostic that the mass, gain or friction estimate has drifted." },
{ t: "ct-ff", d: 2, q: "What is reference shaping (input shaping) for?", o: ["Making the setpoint arrive faster", "Filtering or splitting the command signal", "Reducing sensor noise", "Improving steady-state accuracy"], a: 1, why: "It stops the command exciting a known lightly damped resonance. The classic form is two impulses spaced half a resonant period apart, so the second cancels the vibration the first started. Crane and gantry control use it, and it costs a small delay." },
{ t: "ct-ff", d: 3, q: "Why can feedforward be more aggressive than feedback?", o: ["It uses considerably better sensors all the way through", "It is outside the loop, so it cannot destabilise it", "It runs faster", "It has integral action"], a: 1, why: "Errors only degrade tracking. There is no return path for it to go unstable through. The risk is different: a wrong feedforward can command the actuator beyond its limits, and that saturation does affect the loop." },
{ t: "ct-ff", d: 3, q: "What is a Smith predictor for?", o: ["Estimating all of the unmeasured states too", "Controlling a plant with large dead time", "Cancelling resonances", "Adaptive gain scheduling"], a: 1, why: "It feeds back a model prediction rather than waiting for the delayed measurement. It lets you tune as if the delay were not there, then reinserts it. The weakness is well known: it depends heavily on the model, and a delay estimate that is wrong degrades it fast." },
{ t: "ct-ff", d: 3, q: "A feedforward term is derived from a trajectory that is not smooth. What goes wrong?", o: ["Nothing", "Differentiating it produces impulsive commands", "Steady-state error rises", "The whole loop simply becomes unstable straight away"], a: 1, why: "They saturate the actuator and excite resonances. Acceleration feedforward needs a twice-differentiable path, which is why trajectory generators produce S-curves rather than trapezoidal velocity profiles when jerk matters." },

// --------------------------------------------------------------- ct-lqr
{ t: "ct-lqr", d: 2, q: "In the LQR cost, what does increasing R relative to Q produce?", o: ["A rather faster response overall", "A more conservative controller", "Higher gain", "More overshoot"], a: 1, why: "It uses less control effort and responds more slowly. Q penalises state error and R penalises control effort, so their ratio is the only real tuning knob. It converts the tuning problem from picking gains to expressing what you care about." },
{ t: "ct-lqr", d: 2, q: "Why is the LQR result u = -Kx notable?", o: ["It is nonlinear", "The optimal solution is constant-gain state feedback", "It requires a full state observer to be built as well", "It handles constraints"], a: 1, why: "It is computable offline. An optimisation over an infinite horizon collapses to a matrix multiply, so it runs on anything. It also comes with guaranteed margins in the full-state-feedback case, which are lost once you add an observer." },
{ t: "ct-lqr", d: 2, q: "Why does MPC apply only the first input of each optimised sequence?", o: ["The rest is discarded to save memory", "Re-solving each step turns a plan into feedback", "The later inputs are less accurate", "It is a computational shortcut"], a: 1, why: "It uses the latest measurement each time. This is receding horizon control. Without re-solving, MPC would be open-loop optimal and would drift on any model error or disturbance." },
{ t: "ct-lqr", d: 2, q: "What is the strongest justification for MPC's computational cost?", o: ["Rather better tracking than a PID gives", "It handles constraints explicitly", "It is easier to tune", "It needs no model"], a: 1, why: "It optimises right up against them. Every other method deals with limits by staying away from them or by ad hoc anti-windup. Running a process safely at its constraint is usually where the money is." },
{ t: "ct-lqr", d: 2, q: "What does LQR require that PID does not?", o: ["A faster processor", "A state-space model and all the states", "Explicit handling of the constraints as well", "A nonlinear plant"], a: 1, why: "Or an observer to estimate the states. Full state feedback is the assumption behind the guarantee. Adding a Kalman filter gives LQG, which works well but loses the guaranteed robustness margins, a result that surprised the field when Doyle published it." },
{ t: "ct-lqr", d: 3, q: "How is integral action added to an LQR design?", o: ["By adding an integral gain afterwards", "By augmenting the state with the integral of the error", "LQR cannot have integral action", "By increasing Q on all states"], a: 1, why: "The design then weights it. The optimiser then treats accumulated error as something to penalise, and the resulting gain includes the integral term. Bolting an integrator on afterwards discards the optimality the method was chosen for." },
{ t: "ct-lqr", d: 3, q: "What makes explicit MPC attractive on embedded hardware?", o: ["It uses a considerably longer horizon than before", "The optimisation is solved offline into a lookup", "It removes constraints", "It needs no model"], a: 1, why: "Runtime is then a table search rather than a solver. That makes the worst-case execution time bounded and small, which matters for a hard real-time loop. It only works for low state dimensions, because the number of regions grows explosively." },
{ t: "ct-lqr", d: 3, q: "What is the practical risk of a long MPC prediction horizon?", o: ["Instability", "Computation grows and model error dominates", "It simply cannot handle any constraints at all", "It removes feedback"], a: 1, why: "You pay for predictions you should not trust. The horizon should cover the dominant dynamics and little more. Too short is the opposite failure: the controller cannot see a constraint coming and behaves greedily." },

// --------------------------------------------------------- ct-nonlinear
{ t: "ct-nonlinear", d: 2, q: "A servo axis oscillates at small constant amplitude around its setpoint at rest. What is the likely cause?", o: ["An excessively high derivative gain setting", "Stiction combined with integral action", "Sensor noise", "A resonance"], a: 1, why: "The integrator winds up until it breaks free, overshoots, and repeats. It is a limit cycle rather than a linear instability, and reducing gain does not remove it. The usual answers are a small deadband on the integrator, dither, or friction feedforward." },
{ t: "ct-nonlinear", d: 2, q: "Why is backlash a problem in a load-side position loop?", o: ["It adds friction", "The loop loses control authority entirely", "It reduces gain linearly", "It simply saturates the actuator completely"], a: 1, why: "Crossing the gap is a variable delay in the loop. During the crossing the motor moves and the load does not, so feedback acts on nothing. It is why direction reversals are where backlash shows up and why dual-loop or preloaded drives exist." },
{ t: "ct-nonlinear", d: 2, q: "A system is stable for small steps but oscillates for large ones. What does that signature indicate?", o: ["The sensor noise present", "Actuator saturation", "Backlash", "Dead time"], a: 1, why: "It reduces effective loop gain and interacts with integral windup. Small-signal linear analysis says nothing about it, because the plant is only linear while the actuator is in range. Anti-windup and rate limiting on the reference are the standard fixes." },
{ t: "ct-nonlinear", d: 2, q: "What does a describing function do?", o: ["Linearises about an operating point", "Represents a nonlinearity by its gain to a sinusoid", "Models time delay", "Estimates disturbances"], a: 1, why: "That gives an amplitude-dependent gain for Nyquist-style analysis. It predicts limit cycles by finding where the loop gain crosses -1 for some amplitude. It is approximate, since it assumes the harmonics are filtered out by the plant." },
{ t: "ct-nonlinear", d: 2, q: "When is linearisation about an operating point valid?", o: ["Always", "While excursions stay small enough", "Only ever for the electrical systems", "Only at steady state"], a: 1, why: "The neglected higher-order terms must remain negligible. Which is why gain scheduling exists: one linearisation per region. The failure mode is a controller tuned at one operating point behaving badly at another, and it is usually found in commissioning." },
{ t: "ct-nonlinear", d: 3, q: "What is the difference between stiction and Coulomb friction?", o: ["Nothing", "Stiction is the force needed to start motion", "Stiction is velocity dependent", "Coulomb friction only occurs at rest"], a: 1, why: "Coulomb friction is the roughly constant force once moving. The drop between them is what makes low-speed motion lurch: the axis breaks free, friction falls, it accelerates, then it stops again. That is stick-slip." },
{ t: "ct-nonlinear", d: 3, q: "What is the practical fix for integral windup during a long saturation?", o: ["Remove the integrator", "Stop integrating while the actuator is at its limit", "Increase the proportional gain a good deal further instead", "Add derivative action"], a: 1, why: "Or back-calculate the integral from the saturated output. Without it the integral keeps accumulating during a move it cannot influence, and the axis overshoots badly on arrival because the integrator has to unwind. Back-calculation is the smoother of the two." },
{ t: "ct-nonlinear", d: 3, q: "Why does a deadband in an actuator degrade a position loop specifically?", o: ["It adds noise", "Small commands produce no motion at all", "It simply saturates the integrator instead", "It slows the response"], a: 1, why: "The loop cannot correct small errors, so it settles to a range rather than a point. Proportional action near the setpoint falls inside the deadband and does nothing. Dither, or an integral term with care, can push through it, but the honest fix is usually mechanical." },

// ----------------------------------------------------------- ct-cascade
{ t: "ct-cascade", d: 2, q: "Why does a load-torque disturbance barely show in position on a cascaded servo?", o: ["The position loop is simply a very fast one", "The inner loops see and reject it first", "The encoder filters it", "Feedforward cancels it"], a: 1, why: "They act long before it integrates into a position error. The inner loop runs perhaps ten times faster, so it corrects the disturbance within a fraction of the outer loop's period. Rejecting a disturbance close to where it enters is the core rationale for cascade." },
{ t: "ct-cascade", d: 2, q: "What is the usual bandwidth separation guideline between adjacent loops?", o: ["About 1.5 times", "Roughly a factor of 3 to 10", "A factor of 100", "They should match"], a: 1, why: "Below about 3 the loops interact and the inner one looks like extra lag rather than a fast follower. Far above 10 you are usually wasting inner-loop capability or hitting sensor and actuator limits." },
{ t: "ct-cascade", d: 2, q: "What is the correct tuning order for a position-velocity-current cascade?", o: ["Position first", "Innermost first: current, velocity, position", "All simultaneously", "Velocity first, then the others together"], a: 1, why: "Each outer loop is designed against an inner loop that already behaves predictably. Tuning outside in means retuning everything each time you change an inner gain." },
{ t: "ct-cascade", d: 2, q: "When the inner loop saturates, what should the outer loop ideally do?", o: ["Increase its output further", "Stop integrating", "Switch to open loop", "Reduce its setpoint to zero"], a: 1, why: "Its commands can no longer be followed. This is cascade anti-windup: the inner loop tells the outer loop it is at its limit. Without that signal the outer integrator winds up against a limit it cannot see." },
{ t: "ct-cascade", d: 2, q: "What does a cascade need that a single loop does not?", o: ["A considerably faster processor than the present one", "An intermediate measurement, such as velocity", "Integral action", "A nonlinear model"], a: 1, why: "It sits between the actuator and the final output. Without that sensor there is nothing to close the inner loop on. It is the reason cascade is standard on servos, where current and velocity are cheaply available, and rarer elsewhere." },
{ t: "ct-cascade", d: 3, q: "Two loops in a multivariable plant interact badly. What does the relative gain array tell you?", o: ["The stability margin", "Which input to pair with which output", "The required bandwidth", "The model order"], a: 1, why: "The aim is to minimise interaction. Diagonal entries near 1 indicate a good pairing; negative entries indicate a pairing that will fail when the other loop is switched off. It is the standard first check before decoupling." },
{ t: "ct-cascade", d: 3, q: "Why is a cascade more robust to inner-plant variation than a single loop?", o: ["It uses more sensors", "The inner loop linearises what the outer loop sees", "Its gains are lower", "It has a good deal more integral action in it as well"], a: 1, why: "Motor and gain variation is absorbed inside. A current loop makes the motor look like a torque source regardless of winding resistance or back-EMF. That is why the same outer tuning can serve several motor variants." },
{ t: "ct-cascade", d: 3, q: "An outer loop is retuned to be almost as fast as its inner loop. What is the risk?", o: ["Nothing at all happens, since faster is better", "The inner loop's dynamics appear as lag", "Steady-state error rises", "The inner loop saturates"], a: 1, why: "That lag sits inside the outer loop and erodes phase margin. The whole approximation behind cascade is that the inner loop is effectively instantaneous. Once that fails you have to design the outer loop against the inner loop's actual transfer function." },

// ---------------------------------------------------------- ct-adaptive
{ t: "ct-adaptive", d: 2, q: "Why is gain scheduling favoured in certified industries?", o: ["It performs best", "Every gain set is fixed and testable in advance", "It adapts the fastest out of all of the approaches", "It needs no model"], a: 1, why: "The behaviour is deterministic and can be verified. Nothing changes at runtime except which pretested table entry is selected. True online adaptation has behaviour that depends on operating history, which is far harder to argue in a safety case." },
{ t: "ct-adaptive", d: 2, q: "Why is verifying a gain schedule only at its design points insufficient?", o: ["The chosen operating points may themselves be wrong", "Interpolated gains between points are untested", "It takes too long", "The sensors drift"], a: 1, why: "Rapid scheduling can destabilise even when every fixed point is stable. Stability at each frozen operating point does not imply stability while moving between them. The usual constraint is to limit how fast the scheduling variable is allowed to change." },
{ t: "ct-adaptive", d: 2, q: "In MRAC, what causes gains to drift during long periods of gentle operation?", o: ["Sensor bias", "Insufficient excitation in the signal", "Far too small an adaptation gain used", "Actuator saturation"], a: 1, why: "The adaptation law cannot distinguish parameter sets and wanders on noise. Persistent excitation is what pins the parameters down. Without it the standard defences are a dead zone, sigma-modification or projection to keep the gains bounded." },
{ t: "ct-adaptive", d: 2, q: "What is the most defensible way to deploy a learned policy on real hardware?", o: ["Let it control directly and monitor", "Inside a safety envelope, with a fallback", "Retrain it online continuously", "Only in simulation"], a: 1, why: "A verified conventional controller must be able to take over. The learned policy provides performance and the conventional layer provides the guarantee. This is the shielding or runtime-assurance pattern, and it is what makes learned control arguable in an audit." },
{ t: "ct-adaptive", d: 2, q: "When is learned control genuinely justified over classical design?", o: ["Whenever data is available", "When the dynamics are hard to model but easy to simulate", "For any nonlinear plant", "When the gains are simply rather hard to tune by hand at all"], a: 1, why: "And when the objective is hard to express analytically. Contact-rich manipulation and legged locomotion are the honest examples. For a plant you can model and a cost you can write down, LQR or MPC gets there faster and with a stability argument." },
{ t: "ct-adaptive", d: 3, q: "What is the difference between direct and indirect adaptive control?", o: ["Nothing", "Direct adapts the gains; indirect identifies the plant", "Direct is faster", "The indirect approach needs no plant model of any kind at all"], a: 1, why: "Indirect then redesigns the controller. Indirect separates identification from design, so you can inspect the identified model, which is a real practical advantage. Direct is simpler but the gains are harder to sanity-check." },
{ t: "ct-adaptive", d: 3, q: "What should a gain schedule use as its scheduling variable?", o: ["Time", "A measured variable that captures the change", "The control error signal itself, as it is measured", "The setpoint only"], a: 1, why: "It must vary slowly compared with the loop. Airspeed for an aircraft, or load inertia for an axis. Scheduling on the error itself couples the schedule to the loop's own transients, which is a good way to build an oscillator." },
{ t: "ct-adaptive", d: 3, q: "Why is bumpless transfer needed when switching between controllers?", o: ["To reduce noise", "The two controllers hold different internal states", "To preserve all of the stability margins that exist", "To avoid saturation"], a: 1, why: "Switching without initialising the incoming one produces a step in the actuator command. The integrator is the usual culprit. Initialising the incoming controller's state so its output matches the current command makes the changeover invisible at the plant." },

// ------------------------------------------------------------ ct-faults
{ t: "ct-faults", d: 2, q: "Why design the safe state first?", o: ["It is easier", "Everything else is defined by it", "The regulators simply all require it", "It saves memory"], a: 1, why: "That includes fault detection thresholds and degraded modes. Without it, fault handling accretes as a set of special cases with no shared target. It also frequently changes the hardware, since the safe state should ideally be what the system reaches with no power." },
{ t: "ct-faults", d: 2, q: "Why does a stuck-at sensor fault defeat simple range checking?", o: ["The value is noisy", "The frozen value is usually inside the valid range", "The range checks are simply far too slow to catch it", "It only fails at power-on"], a: 1, why: "So nothing flags it. The check has to look at behaviour rather than value: no change over a period during which the process must have moved. A completely noise-free reading is itself suspicious on a real sensor." },
{ t: "ct-faults", d: 2, q: "What is often the earliest indicator of a degrading actuator in a well-tuned loop?", o: ["A tracking error", "A rising steady control effort", "An increased amount of sensor noise", "A change in setpoint"], a: 1, why: "That is for the same commanded output. The loop hides the degradation by working harder, so the output looks fine right up until it saturates. Trending the control effort turns a sudden failure into a scheduled maintenance item." },
{ t: "ct-faults", d: 2, q: "What does bumpless transfer to a backup controller require?", o: ["Identical gains", "Initialising the backup's internal states", "A faster sample rate", "Disabling the integral action entirely first"], a: 1, why: "Its output then matches the current command at the moment of switching. Otherwise the transfer itself is a disturbance, which is a poor thing to introduce during a fault. In practice the backup is run in tracking mode continuously so it is always ready." },
{ t: "ct-faults", d: 2, q: "What is analytical redundancy?", o: ["A second sensor", "Using a model to predict what a sensor should read", "Fully duplicated computation on a second channel too", "A redundant actuator"], a: 1, why: "Other measurements feed the model, and disagreement is flagged. It gives fault detection without paying for a second sensor. The limit is that it inherits the model's accuracy, so the detection threshold has to be wider than the model error." },
{ t: "ct-faults", d: 3, q: "Why should a watchdog be fed only after the control loop has demonstrated progress?", o: ["To reduce CPU load", "Feeding it from a timer keeps it happy regardless", "It is required by IEC 61508", "To synchronise with the loop rate"], a: 1, why: "It stays happy while every task is deadlocked, turning a safety device into a decoration. The usual pattern is each task setting a flag on completing a cycle, with one check that feeds only when all flags are present and then clears them. A windowed watchdog adds an early bound too." },
{ t: "ct-faults", d: 3, q: "What is a degraded mode, and why define it explicitly?", o: ["A failure state", "A reduced-capability mode that is still safe", "A test mode", "A dedicated calibration mode of some sort or other"], a: 1, why: "It is still useful, so a single sensor loss need not stop the machine. Without one, every fault results in a full stop, which is often worse than continuing at lower performance. It has to be designed and tested, not improvised when the fault occurs." },
{ t: "ct-faults", d: 3, q: "Two redundant sensors disagree. What is the problem with simple duplication?", o: ["It costs too much", "You can detect the disagreement but not resolve it", "It doubles the noise", "The two sensors will simply drift together in step anyway"], a: 1, why: "You can fail safe, but not continue. Duplex gives detection; triple modular redundancy with a majority vote gives identification and continued operation. Which you need follows directly from whether the system is fail-safe or fail-operational." }

]);
