BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// ---------------------------------------------------------- emb-fsm
{ t: "emb-fsm", d: 1, q: "Why is a named state enum better than four boolean flags?", o: ["It uses less RAM", "Four booleans allow sixteen combinations of which most are illegal and none are named", "Enums are faster", "Flags cannot be tested"], a: 1, why: "The enum makes only legal states representable. Every extra flag doubles a combination space nobody has enumerated or documented." },
{ t: "emb-fsm", d: 2, q: "What should the default case of a state switch do?", o: ["Nothing", "Treat the impossible value as a fault", "Return to the previous state", "Retry the event"], a: 1, why: "Reaching an unlisted state means memory was corrupted or a state was added without handling it. Both should be loud rather than silently ignored." },
{ t: "emb-fsm", d: 2, q: "What property can you check on a table-driven machine that you cannot check on a switch?", o: ["Execution speed", "That every state is reachable and none is a dead end", "Stack usage", "Interrupt latency"], a: 1, why: "The table is data, so a test can walk it. A switch spread across a function only tells you about the transitions you happen to read." },
{ t: "emb-fsm", d: 2, q: "Where should the state variable be assigned?", o: ["Wherever convenient", "In one place only", "In the ISR", "In every handler"], a: 1, why: "Scattered assignments recreate the problem the machine was meant to solve: you can no longer say what causes a transition." },
{ t: "emb-fsm", d: 2, q: "Why do explicit state machines test well without hardware?", o: ["They are small", "You feed a sequence of events and assert state and actions, with no peripherals or timing", "They avoid interrupts", "They use no RAM"], a: 1, why: "Same argument as an injected transport: pushing logic behind a plain function boundary makes it exercisable on a host." },
{ t: "emb-fsm", d: 1, q: "Why should state machine actions be non-blocking?", o: ["For power", "A machine that blocks stops responding to events and is no longer a state machine", "The compiler requires it", "To reduce flash"], a: 1, why: "Blocking inside a transition means events queue up or are lost, and the machine's behaviour becomes timing-dependent rather than event-driven." },
{ t: "emb-fsm", d: 3, q: "What does a hierarchical state machine give you?", o: ["Faster transitions", "A parent state can hold behaviour common to its children, so shared transitions are written once", "Fewer states", "Automatic testing"], a: 1, why: "Useful when many states respond identically to something like a reset event. Usually overkill below about a dozen states." },
{ t: "emb-fsm", d: 2, q: "An event arrives that the current state does not expect. What is the right handling?", o: ["Always ignore it", "Always fault", "Decide per state: ignore, error or transition, and write it down", "Queue it for later"], a: 2, why: "Silence is a decision you did not make. Being explicit is what stops an unexpected event producing undefined behaviour later." },
{ t: "emb-fsm", d: 3, q: "Why place the transition table in flash as const?", o: ["It is faster", "It costs no RAM and cannot be corrupted at run time", "C requires it", "For alignment"], a: 1, why: "The machine's definition is not data that should ever change, so putting it in .rodata saves RAM and removes a class of corruption." },
{ t: "emb-fsm", d: 2, q: "Where do entry and exit actions belong?", o: ["At every call site causing the transition", "Inside the state machine", "In the ISR", "In main"], a: 1, why: "Scattering them means a new transition can forget one. Keeping them in the machine makes them a property of the state rather than of the caller." },

// ---------------------------------------------------------- emb-fixedpoint
{ t: "emb-fixedpoint", d: 1, q: "What does Q16.16 mean?", o: ["16-bit integers only", "16 integer bits and 16 fractional bits, scale factor 2^16", "16 values per unit", "A 16-byte type"], a: 1, why: "The binary point is implicit and agreed by convention. In an int32_t that gives roughly plus or minus 32768 with a resolution near 0.000015." },
{ t: "emb-fixedpoint", d: 2, q: "You multiply two Q16.16 values in int32_t. What goes wrong?", o: ["Nothing", "The intermediate is Q32.32 and overflows, so you must widen to 64 bits first", "The result is Q16.16 already", "The sign is lost"], a: 1, why: "Two values with 16 fractional bits each give 32 fractional bits. Widen, multiply, then shift right by Q to return to the original format." },
{ t: "emb-fixedpoint", d: 2, q: "Why add (1 << (Q-1)) before the final right shift?", o: ["To avoid overflow", "To round to nearest instead of truncating, which biases results downward", "To preserve sign", "It is required"], a: 1, why: "Truncation always rounds towards negative infinity, and in a filter or integrator that bias accumulates into a visible offset." },
{ t: "emb-fixedpoint", d: 2, q: "Why saturate rather than wrap a motor command?", o: ["It is faster", "Wrapping turns full forward into full reverse", "It uses less code", "Wrapping is undefined"], a: 1, why: "Clamping degrades gracefully at the limit. Wrapping produces a large value of the opposite sign, which for an actuator is a safety issue." },
{ t: "emb-fixedpoint", d: 3, q: "When is fixed point the wrong choice?", o: ["When precision matters", "On a part with a hardware FPU and no hard timing constraint", "In control loops", "When reading sensors"], a: 1, why: "Floats are simpler and less error-prone where supported. Reaching for fixed point by habit adds risk for no benefit." },
{ t: "emb-fixedpoint", d: 2, q: "Why is the order (a * b) >> Q rather than (a >> Q) * b?", o: ["It is faster", "Shifting first discards the precision you were trying to keep", "It avoids overflow", "They are equivalent"], a: 1, why: "Multiply before you divide or shift, to preserve significant bits, but widen the intermediate first so the multiply itself cannot overflow." },
{ t: "emb-fixedpoint", d: 3, q: "Why is right-shifting a negative signed value a caution in older C standards?", o: ["It is undefined", "It is implementation-defined, although every real compiler does an arithmetic shift", "It rounds up", "It is always zero"], a: 1, why: "If it matters for portability, use a division or cast explicitly rather than relying on the near-universal behaviour." },
{ t: "emb-fixedpoint", d: 2, q: "How should a fixed-point variable be named?", o: ["Whatever is shortest", "With its Q format, such as angle_q16", "With units only", "By its type"], a: 1, why: "The scaling is invisible in the type, so it has to live in the name or a reader cannot know what the number means." },
{ t: "emb-fixedpoint", d: 3, q: "Best way to validate a fixed-point implementation?", o: ["Inspect the code", "A host test comparing against double precision over the full input range", "Test on hardware", "Trust the maths"], a: 1, why: "The failure is usually an intermediate overflowing on a specific input, which inspection misses and a sweep across the range finds." },
{ t: "emb-fixedpoint", d: 1, q: "Why does fixed point help interrupt latency on some parts?", o: ["Integer ops are simpler", "Using the FPU in an ISR may require saving and restoring its context", "It uses less stack", "Interrupts cannot use floats"], a: 1, why: "FPU context is additional state that must be preserved on entry, which adds cycles to every interrupt that touches it." },

// ---------------------------------------------------------- emb-bootloader
{ t: "emb-bootloader", d: 2, q: "What is the main argument for A/B slots?", o: ["Faster writes", "There is no window in which a power failure leaves the device unbootable", "Less flash used", "No CRC needed"], a: 1, why: "The running image is untouched until the new one is complete and verified. Erasing in place has an interval where a power cut is fatal." },
{ t: "emb-bootloader", d: 3, q: "Why must the bootloader set the vector table offset before jumping to the application?", o: ["To enable interrupts", "Otherwise every interrupt dispatches into the bootloader's handlers", "To relocate the stack", "It is optional"], a: 1, why: "The vector table base determines where the core finds every exception handler, and getting it wrong produces bewildering faults much later." },
{ t: "emb-bootloader", d: 2, q: "A CRC over an image proves what?", o: ["Authenticity", "Integrity only: nothing about origin", "Compatibility", "That it will boot"], a: 1, why: "An attacker can recompute a CRC. Rejecting firmware you did not produce needs a signature, which is a different mechanism entirely." },
{ t: "emb-bootloader", d: 3, q: "Why mark a new image pending and require the application to confirm itself?", o: ["To save flash", "So an image that is intact but broken is rolled back automatically", "To speed boot", "For versioning"], a: 1, why: "Integrity checks catch corruption, not bugs. Confirmation turns a bad update into a self-healing event rather than a field failure." },
{ t: "emb-bootloader", d: 3, q: "Anti-rollback and rollback protection conflict. Why?", o: ["They do not", "One prevents downgrade for security, the other permits revert for reliability", "Both need fuses", "They use the same counter"], a: 1, why: "A monotonic version counter that blocks reinstating a vulnerable image also blocks reverting a broken one, so the policy has to be reconciled deliberately." },
{ t: "emb-bootloader", d: 2, q: "What should the bootloader do before jumping to the application?", o: ["Nothing", "Deinitialise peripherals, disable interrupts and leave clocks in a documented state", "Erase its own sector", "Enable the watchdog"], a: 1, why: "The application initialises from whatever it inherits, so undocumented leftover configuration produces faults that look like application bugs." },
{ t: "emb-bootloader", d: 2, q: "Why is updating the bootloader itself in the field risky?", o: ["It is large", "It is the one operation with no safety net if it is interrupted", "It needs a signature", "Flash is slow"], a: 1, why: "Everything else can fall back to the bootloader. If the bootloader is half-written there is nothing left to recover with." },
{ t: "emb-bootloader", d: 2, q: "Why include a hardware revision field in the image header?", o: ["For statistics", "So an image built for a different variant refuses to run rather than half working", "To speed verification", "For the CRC"], a: 1, why: "Half working is the dangerous outcome, because it passes casual testing and fails in the field in ways nobody connects to the wrong image." },
{ t: "emb-bootloader", d: 3, q: "Why re-verify the image hash on every boot rather than only after writing?", o: ["It is free", "Flash bits degrade over time, so an image that was valid may not stay valid", "The bootloader may change", "For logging"], a: 1, why: "Retention is finite, particularly at temperature. Checking once at write time proves nothing about a device three years later." },
{ t: "emb-bootloader", d: 2, q: "Why must the partition table and linker script agree?", o: ["The build fails otherwise", "They are two descriptions of the same layout and drift silently", "One generates the other", "For OTA only"], a: 1, why: "Nothing checks them against each other by default, and disagreement produces an image that flashes cleanly and boots into the wrong place." },

// ---------------------------------------------------------- emb-flash
{ t: "emb-flash", d: 1, q: "Why can you not simply overwrite a byte in flash?", o: ["It is read-only", "Writing can only change 1s to 0s; going back needs a sector erase", "It needs a special instruction", "The address is protected"], a: 1, why: "That asymmetry sets erase granularity at a sector and is exactly what log-structured storage exploits by only ever appending." },
{ t: "emb-flash", d: 2, q: "Typical flash endurance is measured in:", o: ["Total bytes written", "Erase cycles per sector, commonly 10,000 to 100,000", "Years of storage", "Power cycles"], a: 1, why: "It is per sector rather than per device, which is why a scheme that hammers one sector kills the product while the rest of the flash is untouched." },
{ t: "emb-flash", d: 2, q: "A settings save erases then writes a sector every minute. Name both failures.", o: ["Slow and RAM-hungry", "The sector wears out in weeks, and a power loss between erase and write loses everything", "It corrupts RAM and is slow", "It cannot be interrupted"], a: 1, why: "At 100,000 cycles a per-minute erase exhausts the sector in about ten weeks, and there is an interval where neither old nor new settings exist." },
{ t: "emb-flash", d: 2, q: "How does a log-structured store improve endurance?", o: ["It compresses data", "It appends and erases only when the sector fills, multiplying life by records per sector", "It writes to RAM", "It uses smaller sectors"], a: 1, why: "Erases become rare rather than per-save, and the previous record survives until compaction so there is never a moment with no valid copy." },
{ t: "emb-flash", d: 3, q: "Why write the data before the validity marker?", o: ["It is faster", "A record whose marker is missing is ignored, so a half-written record is invisible rather than corrupt", "Markers must be last in flash", "To align the record"], a: 1, why: "Ordering is what makes the scheme power-fail safe: the record only becomes visible at the instant it is known to be complete." },
{ t: "emb-flash", d: 2, q: "Why might a time-critical ISR need to live in RAM?", o: ["RAM is faster", "Flash erase or program can stall instruction fetch for tens of milliseconds", "Interrupts cannot run from flash", "To save power"], a: 1, why: "A handler in flash simply cannot execute while the controller is busy, so latency guarantees are void during any settings write or update." },
{ t: "emb-flash", d: 3, q: "What can a power loss during an erase leave behind?", o: ["The old data intact", "A partially erased sector that reads as neither old data nor 0xFF", "A blank sector", "Nothing unusual"], a: 1, why: "Design assuming it happens: the recovery logic must cope with a sector in an indeterminate state rather than only with clean old or clean new." },
{ t: "emb-flash", d: 2, q: "Why read back and verify after a flash write?", o: ["To measure speed", "A write can fail silently on a worn sector", "The standard requires it", "To flush the cache"], a: 1, why: "Endurance degrades gradually rather than all at once, so late-life writes can partially fail with no error reported by the controller." },
{ t: "emb-flash", d: 2, q: "What is wear levelling?", o: ["Compressing data", "Spreading writes across sectors so no single one wears out first", "Verifying writes", "Erasing in the background"], a: 1, why: "Without it, a hot record concentrates every erase on one sector, which dies long before the rest of the device is exhausted." },
{ t: "emb-flash", d: 1, q: "Why prefer LittleFS or an NVS over writing your own store?", o: ["They are faster", "The power-fail and wear failure modes are subtle and only appear after months in the field", "They use less flash", "They are required"], a: 1, why: "Every one of these schemes looks correct on a bench. The difference shows up in a fleet, which is exactly when you cannot fix it cheaply." },

// ---------------------------------------------------------- emb-debugarch
{ t: "emb-debugarch", d: 1, q: "What is SWD?", o: ["A trace protocol", "ARM's two-wire debug interface: a clock and a bidirectional data line", "A UART bootloader", "A flash programmer"], a: 1, why: "It replaces the wider JTAG interface and matters when pins are scarce, while offering the same halt, step, breakpoint and memory access facilities." },
{ t: "emb-debugarch", d: 2, q: "Why are hardware breakpoints limited in number?", o: ["Licensing", "They are implemented by a comparator unit in silicon, typically about six", "Flash size", "The protocol"], a: 1, why: "Software breakpoints have no such limit but work by replacing an instruction, so they only apply to code in RAM." },
{ t: "emb-debugarch", d: 2, q: "You need to find what corrupts a variable. Which tool?", o: ["printf on every write", "A data watchpoint", "A logic analyser", "More tests"], a: 1, why: "A watchpoint halts on access to that address and names the offending code immediately, rather than requiring you to instrument every candidate." },
{ t: "emb-debugarch", d: 2, q: "Why is ITM better than printf for real-time debugging?", o: ["More output", "Writing to a stimulus port costs a few cycles, so it does not move the timing under investigation", "No probe needed", "Easier setup"], a: 1, why: "A UART printf takes long enough to change behaviour, which is why faults often vanish the moment you instrument them." },
{ t: "emb-debugarch", d: 2, q: "What does the DWT cycle counter give you?", o: ["Instruction trace", "A free-running cycle count, the cheapest accurate way to time a function", "Watchpoints", "Flash timing"], a: 1, why: "Repeatable, high resolution and available without external tooling, which makes it the default for measuring worst-case execution time." },
{ t: "emb-debugarch", d: 3, q: "What does ETM provide that ITM does not?", o: ["Lower overhead", "A record of the actual instruction stream, so you can reconstruct what executed before a crash", "More stimulus ports", "Flash programming"], a: 1, why: "ITM is instrumentation you insert. ETM records execution itself, which is what you want when the fault leaves no clue behind." },
{ t: "emb-debugarch", d: 1, q: "Cheapest timing measurement available on any part?", o: ["ETM", "Toggle a spare GPIO and watch it on a scope", "printf timestamps", "A cycle-accurate simulator"], a: 1, why: "Sub-microsecond resolution, no tooling, and it shows jitter as well as duration, which is often the number that actually matters." },
{ t: "emb-debugarch", d: 2, q: "Why can a low-power mode drop the debug connection?", o: ["The probe times out", "The debug block is clocked too, and most parts have a bit to keep it alive in sleep", "SWD does not work below a voltage", "The cache is disabled"], a: 1, why: "Without that bit, entering sleep looks exactly like a crash or a broken probe, which wastes a lot of time during low-power bring-up." },
{ t: "emb-debugarch", d: 2, q: "Why do watchdogs need to freeze on halt?", o: ["They do not", "Otherwise the watchdog fires while you are stopped at a breakpoint", "To save power", "To keep time accurate"], a: 1, why: "It is usually one configuration bit, and without it every debugging session ends in a reset a few seconds after you halt." },
{ t: "emb-debugarch", d: 2, q: "Why use -Og rather than -O2 while debugging?", o: ["It is faster to compile", "It keeps most optimisation while preserving a sensible line order and variable visibility", "It disables warnings", "It removes volatile"], a: 1, why: "-O2 inlines and reorders so the debugger shows a sequence that did not happen, while -O0 may hide the fault entirely." },

// ---------------------------------------------------------- emb-realtime
{ t: "emb-realtime", d: 1, q: "What does hard real time mean?", o: ["Very fast", "A missed deadline is a system failure", "Written in assembly", "Nanosecond precision"], a: 1, why: "It is about consequence rather than speed. A slow system with a guaranteed deadline is hard real time; a fast one with no guarantee is not." },
{ t: "emb-realtime", d: 2, q: "Why does a long critical section in one module break timing elsewhere?", o: ["It uses more CPU", "Disabling interrupts adds directly to the worst-case latency of every interrupt in the system", "It fragments the heap", "It changes priority"], a: 1, why: "Interrupt latency is a global property, so a well-meaning module that masks interrupts for 200 microseconds has spent everyone else's budget." },
{ t: "emb-realtime", d: 2, q: "Under rate monotonic scheduling, which task gets the highest priority?", o: ["The most important", "The one with the shortest period", "The longest running", "The one created first"], a: 1, why: "Priority follows frequency rather than perceived importance, and this is provably optimal among fixed-priority policies for independent periodic tasks." },
{ t: "emb-realtime", d: 3, q: "The classic rate monotonic utilisation bound is approximately:", o: ["50%", "69%", "85%", "100%"], a: 1, why: "Below about 69 per cent a set of independent periodic tasks is guaranteed schedulable. Above it you may still be fine, but you must analyse rather than assume." },
{ t: "emb-realtime", d: 2, q: "Why measure worst-case rather than average execution time?", o: ["It is easier", "A deadline is missed by the worst case, not the average", "Averages are unreliable", "It is faster"], a: 1, why: "Meeting a deadline on average means missing it regularly, and the measurement has to be made under worst-case conditions to mean anything." },
{ t: "emb-realtime", d: 2, q: "Which conditions define a worst-case timing measurement?", o: ["Idle system, warm cache", "Cold cache, every branch taken, flash busy, all interrupts enabled", "Debugger attached", "Lowest clock speed"], a: 1, why: "Measuring on an idle bench gives you a number that has no relationship to the situation in which the deadline will actually be missed." },
{ t: "emb-realtime", d: 3, q: "Which two things break rate monotonic analysis?", o: ["Too many tasks and too little RAM", "Priority inversion and unbounded work", "Interrupts and DMA", "Caches and pipelines"], a: 1, why: "Both make a task's effective duration unpredictable: inversion by blocking on a lower priority holder, unbounded work by depending on data." },
{ t: "emb-realtime", d: 2, q: "Why does jitter often matter more than latency in a control loop?", o: ["It is larger", "A varying sample interval corrupts the maths the controller depends on", "It is easier to measure", "It affects power"], a: 1, why: "Most control algorithms assume a fixed timestep. A consistent delay can be compensated; a varying one cannot." },
{ t: "emb-realtime", d: 2, q: "Why is dynamic allocation banned on real-time paths?", o: ["It uses RAM", "Allocation time is not bounded", "It is not reentrant", "It fragments flash"], a: 1, why: "The allocator may walk free lists or coalesce blocks, so the worst case is unpredictable and cannot be included in a timing analysis." },
{ t: "emb-realtime", d: 3, q: "Why expose the maximum observed execution time as a counter?", o: ["For benchmarking", "So creeping degradation is visible before a deadline is actually missed", "To trigger the watchdog", "For certification only"], a: 1, why: "Timing regressions arrive gradually as features are added. A visible maximum turns that into an observation rather than an eventual field failure." },

// ---------------------------------------------------------- emb-dma
{ t: "emb-dma", d: 1, q: "What is the main reason DMA helps a battery device?", o: ["Faster code", "The core can sleep while the transfer proceeds", "Less RAM", "Simpler drivers"], a: 1, why: "Active current dominates the average on most battery products, so anything that lets the CPU stay asleep during data movement is a direct win." },
{ t: "emb-dma", d: 2, q: "What does marking a DMA buffer volatile actually fix?", o: ["Cache coherency", "The compiler caching a value in a register, and nothing else", "Write buffering", "All coherency problems"], a: 1, why: "volatile is an instruction to the compiler. It has no effect on a data cache or a write buffer, which is why 'DMA means volatile' is the wrong model." },
{ t: "emb-dma", d: 2, q: "Why must a DMA buffer not be a local variable?", o: ["Locals cannot align", "The transfer outlives the function and the stack frame does not", "The stack is too small", "DMA cannot reach the stack"], a: 1, why: "The controller writes into that memory after the function has returned, by which point the frame belongs to something else entirely." },
{ t: "emb-dma", d: 3, q: "Why does a DMA buffer often need cache-line alignment?", o: ["Speed", "Invalidating a line that partly contains other variables destroys them", "The controller requires it", "For power"], a: 1, why: "Cache maintenance works on whole lines, so a buffer sharing a line with other data discards that neighbour's cached value when you invalidate." },
{ t: "emb-dma", d: 2, q: "What is circular mode with half and full interrupts used for?", o: ["Error detection", "Processing one half of a buffer while the hardware fills the other", "Reducing interrupt count only", "Aligning transfers"], a: 1, why: "It is how continuous audio and ADC streams are handled, and it removes the possibility of missing a sample between transfers." },
{ t: "emb-dma", d: 3, q: "In circular mode, what happens if your processing is too slow?", o: ["An overrun interrupt fires", "The hardware overwrites data you have not read, producing torn data with no error", "The transfer stops", "The buffer grows"], a: 1, why: "There is no protection by default, which is why you instrument the margin rather than assuming the processing finishes in time." },
{ t: "emb-dma", d: 2, q: "Data is wrong until you add a printf, then correct. What does that suggest?", o: ["A compiler bug", "A coherency or timing problem: the delay lets the cache or write buffer settle", "Stack overflow", "Wrong channel"], a: 1, why: "Any fault that disappears when the code is slowed down is timing-related, and with DMA the usual cause is a missing invalidate or barrier." },
{ t: "emb-dma", d: 2, q: "The first DMA transfer works and later ones do not. Most likely cause?", o: ["Wrong alignment", "The completion flag is not cleared, or the descriptor is not reloaded", "Cache coherency", "Buffer too small"], a: 1, why: "A latched completion condition prevents the next request being serviced, which looks like the controller having stopped working." },
{ t: "emb-dma", d: 3, q: "Why does disabling interrupts not protect a buffer from DMA?", o: ["It does", "DMA moves data without CPU involvement, so masking interrupts does not stop it", "Interrupts are not maskable", "DMA runs at higher priority"], a: 1, why: "It is a genuine second master. Coordination needs the completion mechanism plus barriers and cache maintenance, not interrupt masking." },
{ t: "emb-dma", d: 2, q: "Before letting DMA read a buffer you have written, what may be required?", o: ["An invalidate", "A cache clean, so your writes reach actual memory", "Nothing", "A barrier only"], a: 1, why: "Clean pushes dirty cache lines out to memory for DMA to read; invalidate discards stale lines so the CPU re-reads what DMA wrote. The two directions need different operations." }

]);
