BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// -------------------------------------------------------- emb-test-first
{ t: "emb-test-first", d: 1, q: "Why must you see each assertion fail before trusting it?", o: ["It is a convention", "A test that cannot fail reports success forever and you believe it", "To measure coverage", "The framework requires it"], a: 1, why: "<p>Break the implementation deliberately and confirm the assertion catches it.</p><p>Every assertion should have been red at least once, or you do not actually know it is connected to the thing it claims to check.</p>" },
{ t: "emb-test-first", d: 2, q: "Why does a test program's exit code matter?", o: ["It is logged", "Non-zero means failure, which is what make and CI act on", "It sets main's return value", "It selects the output format"], a: 1, why: "<p>Anything that prints FAILED and returns zero stays green in CI forever.</p><p>The exit code is the interface between the test and everything that runs it.</p>" },
{ t: "emb-test-first", d: 2, q: "Which compiler builds a host unit test for firmware logic?", o: ["The cross compiler for the target", "The host compiler, so it runs on your machine in milliseconds with no board", "Either", "A dedicated test compiler"], a: 1, why: "<p>That is the entire point: the logic is exercised in a fast loop without hardware.</p><p>Running on target is a separate and also necessary activity, not a replacement.</p>" },
{ t: "emb-test-first", d: 2, q: "Why run the unit suite under -fsanitize=address,undefined?", o: ["It speeds the tests up", "It turns a one-byte overrun or a signed overflow from a silent pass into a loud failure with a stack trace", "It replaces the need for tests", "It measures coverage"], a: 1, why: "<p>A few times the runtime is nothing on a test suite.</p><p>On firmware it is the highest-value setting available, because the same overrun on target corrupts something unrelated and reaches the field as a mystery.</p>" },
{ t: "emb-test-first", d: 2, q: "What does <code>#cond</code> do in a CHECK macro?", o: ["Evaluates the condition twice", "Stringises it, so the output names the expression without writing it twice", "Comments it out", "Checks it at compile time"], a: 1, why: "<p>It is most of what a real framework's assertion macros do, which is why twenty lines of your own macro is a legitimate way to start.</p>" },
{ t: "emb-test-first", d: 3, q: "Why should a test contain no branches?", o: ["Branches are slow", "An if means it checks different things on different runs, which is how a test quietly stops testing", "Coverage tools cannot handle them", "It breaks the framework"], a: 1, why: "<p>If two cases need different assertions, that is two tests. A conditional assertion can be satisfied by the branch you never take.</p>" },
{ t: "emb-test-first", d: 3, q: "Which values should a test target?", o: ["The middle of the valid range", "The boundaries: zero, one, full scale, and one past full scale", "Random values", "Whatever the datasheet gives"], a: 1, why: "<p>The middle of the range almost never finds anything, because that is the case the implementation was written against.</p><p>Off-by-one and range-check bugs live at the edges by definition.</p>" },
{ t: "emb-test-first", d: 3, q: "When is it worth moving from a hand-written macro to a framework?", o: ["Immediately, always", "When you want per-test isolation, setup and teardown, or a report format CI can parse", "Only for large projects", "Never"], a: 1, why: "<p>Per-test isolation is the main one: without it a crash in one test takes the rest of the run with it.</p><p>Starting without a framework is still right, because it removes the excuse that you cannot test until the tooling is set up.</p>" },

// --------------------------------------------------------- emb-test-fake
{ t: "emb-test-fake", d: 2, q: "Why can a driver that calls the vendor HAL directly not be unit tested?", o: ["The HAL is too slow", "There is nothing to substitute: the call goes straight to hardware that is not there", "The HAL is closed source", "It requires an RTOS"], a: 1, why: "<p>The fix is a seam: a struct of function pointers plus a context, so the driver reaches the bus through something a test can replace.</p><p>In Zephyr the device pointer and the <code>i2c_dt_spec</code> already are that seam.</p>" },
{ t: "emb-test-fake", d: 2, q: "Why should a fake record delays rather than actually sleeping?", o: ["Sleeping is not portable", "It keeps the suite instant, and lets you assert that a timeout was bounded", "The delay function is unavailable on a host", "To save power"], a: 1, why: "<p>A driver retrying with 50 ms waits would make the suite crawl.</p><p>Recording the total also converts 'does it give up within a second' from a hope into an assertion.</p>" },
{ t: "emb-test-fake", d: 2, q: "What makes a fake more useful than a stub returning zero?", o: ["It is faster", "It can be told to fail on a chosen transfer, which makes the error paths reachable", "It uses less memory", "It is generated automatically"], a: 1, why: "<p>On real hardware you cannot make the third transfer fail. In a fake it is one variable.</p><p>Since the error paths are the ones nobody exercises until a customer does, that is where the value is.</p>" },
{ t: "emb-test-fake", d: 2, q: "Which driver tests are worth writing first?", o: ["The happy path, thoroughly", "The error paths: wrong identity, a transfer failing at each point, a status bit that never clears", "Performance tests", "Tests of the fake itself"], a: 1, why: "<p>The happy path is exercised by everyone all the time and usually already works.</p><p>The error paths are the code that runs on the worst day and has never been run at all.</p>" },
{ t: "emb-test-fake", d: 2, q: "Why must a fake reset between tests?", o: ["To free memory", "Otherwise one test's state leaks into the next, and the suite passes or fails depending on order", "For accurate timing", "It is required by the framework"], a: 1, why: "<p>Order dependence is the classic flaky test: it passes alone and fails in the suite, or vice versa.</p><p>Running the suite in a shuffled order in CI is what surfaces it.</p>" },
{ t: "emb-test-fake", d: 3, q: "Why test the register write ORDER, not just the values?", o: ["Order does not matter", "A driver writing the right values in the wrong order works on the bench and fails on a different silicon revision", "It is faster to check", "The datasheet requires it"], a: 1, why: "<p>Many parts require a specific sequence: unlock, configure, then enable. A spy that records the order turns that from a datasheet promise into a checked property.</p>" },
{ t: "emb-test-fake", d: 3, q: "What does a passing suite against a fake NOT prove?", o: ["That the logic is right", "Timing, your reading of the datasheet, or anything about the real silicon", "That the error paths work", "That memory is freed"], a: 1, why: "<p>If the fake and the driver share the same misunderstanding, both are wrong together and every test passes.</p><p>That is exactly why the pyramid keeps a hardware tier at the top.</p>" },
{ t: "emb-test-fake", d: 3, q: "How do you test that an error path does not leak?", o: ["Read the code carefully", "Count allocations in the fake and assert the count is back to zero after a failed init", "Run it under a profiler", "Use a garbage collector"], a: 1, why: "<p>Wrapping the allocator in the test build makes leak detection an assertion rather than an inspection.</p><p>It is the error paths that leak, because they are the paths nobody walked.</p>" },

// -------------------------------------------------------- emb-test-ztest
{ t: "emb-test-ztest", d: 2, q: "What does Zephyr's <code>native_sim</code> give you?", o: ["A cycle-accurate simulator", "The whole application including the kernel, as a native executable that runs in milliseconds", "A remote debug server", "A device emulator only"], a: 1, why: "<p>Threads, semaphores, work queues and timers all behave.</p><p>It is why dual targeting is easier in Zephyr than almost anywhere else, and why an untested Zephyr code base has no excuse.</p>" },
{ t: "emb-test-ztest", d: 2, q: "What does twister do?", o: ["Builds the application", "Reads every testcase.yaml, builds each test for each platform, runs them and reports", "Flashes the board", "Generates coverage only"], a: 1, why: "<p>It reduces the whole CI test job to one command.</p><p>The <code>tags</code> field is what lets you run fast unit tests on every commit and the hardware set overnight.</p>" },
{ t: "emb-test-ztest", d: 2, q: "What is Zephyr's EMUL layer for?", o: ["Emulating the CPU", "A fake device registered against a devicetree node, so a driver's bus calls reach it instead of silicon", "Emulating the kernel", "Modelling timing"], a: 1, why: "<p>The driver is completely unmodified: it still calls <code>i2c_burst_read_dt</code> and the emulator answers.</p><p>It is the right mechanism when the thing under test is the driver itself.</p>" },
{ t: "emb-test-ztest", d: 2, q: "What does a passing native_sim suite not prove?", o: ["That the logic works", "Timing, interrupt latency, real stack usage, the actual peripheral, or that it fits in flash", "That kernel APIs are used correctly", "That there are no memory errors"], a: 1, why: "<p>Which is why twister supports device testing, and why the answer is both tiers rather than either.</p><p>A host pass is a statement about your logic, not about your product.</p>" },
{ t: "emb-test-ztest", d: 2, q: "What are the five NULLs in <code>ZTEST_SUITE(name, ...)</code>?", o: ["Unused padding", "The predicate, setup, before, after and teardown hooks, which most suites do not need", "Five test cases", "Platform filters"], a: 1, why: "<p>The predicate decides whether the suite runs at all, which is how a suite is limited to particular platforms.</p><p>Most unit suites need none of them, which is why they are usually all NULL.</p>" },
{ t: "emb-test-ztest", d: 3, q: "Why pass the optional message to <code>zassert_equal</code>?", o: ["It is required", "A bare failure tells you the values and not the intent", "It speeds up the test", "It affects the exit code"], a: 1, why: "<p>'expected full scale to equal vref' turns a failure into a diagnosis.</p><p>It is a few seconds while writing and it pays back the first time the test fails in CI rather than at your desk.</p>" },
{ t: "emb-test-ztest", d: 3, q: "Which prj.conf symbol turns on ztest?", o: ["CONFIG_TEST=y", "CONFIG_ZTEST=y", "CONFIG_UNITTEST=y", "CONFIG_ASSERT=y"], a: 1, why: "<p>Along with a <code>testcase.yaml</code> so twister can find the test, and a CMakeLists adding both the test source and the code under test.</p>" },
{ t: "emb-test-ztest", d: 3, q: "Where should a test's devicetree changes live?", o: ["In the product's overlay", "In a test-only overlay under the test directory, so the product's hardware description stays clean", "In the board's .dts", "In prj.conf"], a: 1, why: "<p>A node that exists only for the test, or one repointed at an emulator, belongs with the test rather than with the product.</p><p>Zephyr picks up <code>boards/&lt;board&gt;.overlay</code> under the test directory automatically.</p>" }

]);
