// Operating Systems bank, part 1: Fundamentals.
//
// Topics are lesson ids, which topicLesson() resolves directly, so no
// TOPIC_LESSON entry is needed for this track.
//
// Option lengths are deliberately balanced. The correct answer is the longest
// in roughly a quarter of these, which is chance; see tools/verify.js, which
// measures it on every run.

BANKS["Operating Systems"] = [

// ---------------------------------------------------------------- os-proc
{ t: "os-proc", d: 1, q: "What does a thread own privately?", o: ["Its heap, and the globals it touches", "Its stack and its register state", "Its own file descriptor table", "Its own copy of the program code"], a: 1, why: "Everything else is shared with the other threads in the process, which is exactly why two of them touching one variable need a mutex." },
{ t: "os-proc", d: 1, q: "A FreeRTOS task is most like which Linux concept?", o: ["A process, since it has its own stack", "A thread inside a single process", "A kernel module loaded at boot", "A signal handler run asynchronously"], a: 1, why: "Own stack and registers, everything else shared. That is a thread, and it is why FreeRTOS has no processes: there is one address space." },
{ t: "os-proc", d: 2, q: "What does a process have that a thread does not?", o: ["A stack of its own to run on", "A private address space and resources", "A priority the scheduler respects", "An entry in the run queue"], a: 1, why: "Threads have stacks and priorities too. The address space, plus file descriptors, working directory and user id, is what makes it a process." },
{ t: "os-proc", d: 2, q: "Why does a Cortex-M have no processes?", o: ["Its clock speed is too low for them", "No MMU, so no address translation", "FreeRTOS does not implement the concept", "It has too little RAM to hold two"], a: 1, why: "The MPU can forbid an access but cannot make one address refer to different memory for different code, so there is nothing for a process to be." },
{ t: "os-proc", d: 2, q: "Which is more expensive, and why?", o: ["Thread switch, because of the larger frame", "Process switch, because page tables change", "They cost the same on modern hardware", "Process switch, because of the scheduler"], a: 1, why: "Both save registers. Only the process switch invalidates cached translations and leaves the caches cold, which is where the order of magnitude comes from." },
{ t: "os-proc", d: 2, q: "How do two threads in one process communicate?", o: ["Through a pipe the kernel provides", "By writing to memory they both see", "Using a socket bound to localhost", "Via shared memory they must request"], a: 1, why: "They already share everything, so communication is just a write, and that is precisely why it needs a lock. Processes are the ones that must ask for shared memory." },
{ t: "os-proc", d: 2, q: "What is an ASID for?", o: ["Identifying a thread within a process", "Tagging TLB entries with their owner", "Assigning a scheduling priority band", "Naming a shared memory segment"], a: 1, why: "It lets translations for several processes coexist in the TLB, so a context switch need not flush the whole thing. It is a direct attack on the cost above." },
{ t: "os-proc", d: 3, q: "One thread dereferences null. What happens to the others?", o: ["Only that thread is terminated", "The whole process dies with it", "The kernel restarts that thread", "Nothing, if it has a handler"], a: 1, why: "SIGSEGV kills the process, not the thread. That blast radius is the actual reason to pay for processes rather than threads." },
{ t: "os-proc", d: 3, q: "Why does a browser give each tab its own process?", o: ["Tabs render measurably faster that way", "One crashing must not take the rest", "It reduces the total memory used", "The scheduler handles them more fairly"], a: 1, why: "Processes cost more on nearly every axis. What you buy is isolation, so a bad page or a renderer bug kills one tab rather than the browser." },
{ t: "os-proc", d: 3, q: "Which is NOT normally shared between threads of a process?", o: ["The heap they allocate from", "The stack each one runs on", "The open file descriptors", "The signal handler table"], a: 1, why: "Each thread gets its own stack; that plus registers is the whole of what is private. Overrunning it corrupts a neighbour rather than faulting cleanly." },

// ------------------------------------------------------------------ os-vm
{ t: "os-vm", d: 1, q: "What does the MMU do that an MPU cannot?", o: ["Refuse an access that is not permitted", "Translate a virtual address to physical", "Detect a null pointer dereference", "Enforce a no-execute region"], a: 1, why: "Both enforce permissions, which is why an MPU catches a null dereference. Only translation lets two programs disagree about what an address means." },
{ t: "os-vm", d: 1, q: "What is the usual page size on ARM64 Linux?", o: ["512 bytes", "4 kB", "64 kB", "1 MB"], a: 1, why: "4 kB is the common default, so the low 12 bits of an address are the offset within the page and pass through translation untouched." },
{ t: "os-vm", d: 2, q: "What does the TLB cache?", o: ["Recently used memory contents", "Recent address translations", "The page tables themselves", "Pending page fault addresses"], a: 1, why: "A miss means walking the page tables, which is why locality matters for translation as well as for data, and why flushing it on a context switch is expensive." },
{ t: "os-vm", d: 2, q: "A page fault has occurred. Is that an error?", o: ["Yes, it always indicates a bug", "Usually not: it is how paging works", "Only if the process is not root", "Only on a write, not on a read"], a: 1, why: "Demand paging, lazy allocation and copy-on-write are all implemented by faulting deliberately. Only an access with no legitimate mapping becomes SIGSEGV." },
{ t: "os-vm", d: 2, q: "What does malloc of 1 GB actually cost immediately?", o: ["A gigabyte of physical memory", "Almost nothing until it is touched", "A gigabyte of swap being reserved", "It fails on a machine with less RAM"], a: 1, why: "The mapping is created and pages are backed on first write. It is why overcommit exists, and why a program can allocate more than the machine has." },
{ t: "os-vm", d: 2, q: "What makes fork() cheap?", o: ["The child shares the parent's stack", "Pages are shared copy-on-write", "Only the code segment is duplicated", "The kernel defers it until exec"], a: 1, why: "Both processes point at the same physical pages marked read-only, and a copy happens per page on the first write. Nothing is duplicated up front." },
{ t: "os-vm", d: 2, q: "Why does virtual memory remove heap fragmentation worries?", o: ["The allocator compacts the heap for you", "Scattered frames can look contiguous", "The kernel defragments memory nightly", "Allocations are rounded to page size"], a: 1, why: "A large allocation maps non-adjacent physical frames into a contiguous virtual range, so the failure that kills a long-running bare-metal heap does not arise." },
{ t: "os-vm", d: 3, q: "Why does hard real-time code call mlockall()?", o: ["To reserve memory ahead of other processes", "A page fault has unbounded latency", "It makes memory accesses measurably faster", "The real-time scheduler requires it"], a: 1, why: "A fault might take a microsecond or wait on a disk, which destroys any worst-case execution time you calculated. Pinning the pages removes the possibility." },
{ t: "os-vm", d: 3, q: "Which is true of an MPU compared with an MMU?", o: ["It has finer granularity than pages", "It costs far less silicon and power", "It supports per-process address spaces", "It removes the need for a linker script"], a: 1, why: "A handful of regions and no translation hardware, which is exactly why a small microcontroller can afford one and cannot afford the other." },
{ t: "os-vm", d: 3, q: "Two processes both hold the pointer 0x00400000. What does that mean?", o: ["They are sharing that memory", "They see completely different RAM", "One of them will fault on access", "The addresses must have been mapped"], a: 1, why: "Each has its own page tables, so the same virtual address translates to different physical frames. Sharing has to be arranged explicitly." },

// ---------------------------------------------------------------- os-mode
{ t: "os-mode", d: 1, q: "What enforces the boundary between user and kernel mode?", o: ["The compiler, when it builds the code", "The CPU, in hardware", "The linker, through section attributes", "The C library, by checking calls"], a: 1, why: "It is a privilege level in the processor. That is why a userspace bug cannot reach the hardware however it is written, and why the boundary is trustworthy." },
{ t: "os-mode", d: 1, q: "Which instruction crosses into the kernel on ARM?", o: ["bl, branching with link", "svc, the supervisor call", "wfi, waiting for interrupt", "isb, the instruction barrier"], a: 1, why: "The same instruction an RTOS uses for a kernel call. It traps to one fixed handler, so userspace never chooses where in the kernel it lands." },
{ t: "os-mode", d: 2, q: "Why can userspace not simply call a kernel function?", o: ["The symbol is not exported to it", "It would choose its own entry point", "The calling convention differs", "The addresses are not known to it"], a: 1, why: "Entering anywhere it liked would make the boundary meaningless. The trap enters at one handler which then validates the request." },
{ t: "os-mode", d: 2, q: "Why does the kernel use copy_from_user() on your pointer?", o: ["To stop the processor caches from being flushed", "It might be null, unmapped or kernel memory", "Because the address space differs", "To avoid taking a page fault"], a: 1, why: "Everything from userspace is hostile until checked. Dereferencing it directly is the classic route from a driver bug to a privilege escalation." },
{ t: "os-mode", d: 2, q: "Roughly what does a system call cost?", o: ["A few cycles, like a function call", "Hundreds of cycles, plus cache damage", "Tens of microseconds, always", "A full context switch to another process"], a: 1, why: "The mode switch, the validation, and the branch predictor and cache effects. It is why stdio buffers and why epoll exists at all." },
{ t: "os-mode", d: 2, q: "What is the vDSO for?", o: ["Loading shared libraries at startup", "Serving some calls without a trap", "Isolating drivers from the kernel", "Verifying a binary's signature"], a: 1, why: "Kernel code mapped into every process, so gettimeofday costs a function call rather than a mode switch. A direct response to the cost above." },
{ t: "os-mode", d: 2, q: "Is printf a system call?", o: ["Yes, it traps straight into the kernel itself", "No, a library function that calls write", "Only when writing to a terminal", "Only when the stream is unbuffered"], a: 1, why: "It formats and buffers in userspace, then writes when the buffer fills or is flushed. It is why strace shows far fewer lines than the source suggests." },
{ t: "os-mode", d: 3, q: "What does a futex do on an uncontended lock?", o: ["Enters the kernel to record the owner", "Nothing: it is a compare-and-swap", "Spins until the scheduler intervenes", "Raises the caller's priority briefly"], a: 1, why: "The syscall happens only when the lock is genuinely contended, so the common path costs a few cycles and you pay only when about to wait anyway." },
{ t: "os-mode", d: 3, q: "Which Cortex-M feature is the closest analogue?", o: ["The NVIC priority grouping", "The CONTROL register and SVC", "The MPU region configuration", "The PendSV exception handler"], a: 1, why: "CONTROL selects whether thread mode is privileged and SVC is the trap into privileged code. The mechanism is familiar; the difference is that bare metal has no boundary by default." },
{ t: "os-mode", d: 3, q: "Why does epoll exist?", o: ["It polls file descriptors more accurately", "One call can cover thousands of them", "It works on descriptors select cannot", "It avoids blocking the calling thread"], a: 1, why: "Checking each descriptor with its own syscall does not scale when the mode switch dominates. The API shape is a direct consequence of what a trap costs." },

// --------------------------------------------------------------- os-sched
{ t: "os-sched", d: 1, q: "What is a fixed-priority preemptive scheduler optimising?", o: ["Total throughput across all tasks", "Worst-case latency at the top", "Fairness between the ready tasks", "Average response time overall"], a: 1, why: "It will starve everything below indefinitely to keep the important task on time, and that single-mindedness is what makes the worst case provable." },
{ t: "os-sched", d: 1, q: "What is Linux's default scheduler for normal processes?", o: ["Round robin with a fixed quantum", "CFS, by accumulated runtime", "Earliest deadline first", "Fixed priority, 1 to 99"], a: 1, why: "It runs whichever thread has the lowest virtual runtime, weighted by nice, so the one that has had least CPU goes next and nothing ever starves." },
{ t: "os-sched", d: 2, q: "What does nice actually change under CFS?", o: ["A hard priority over other threads", "How fast virtual runtime accrues", "The size of the thread's time slice", "The core the thread is pinned to"], a: 1, why: "A nice-19 thread still runs, it is simply chosen less often. Nothing starves, which is the property that makes CFS wrong for a hard deadline." },
{ t: "os-sched", d: 2, q: "Which Linux class behaves like a FreeRTOS task?", o: ["SCHED_OTHER at nice -20", "SCHED_FIFO at a real-time priority", "SCHED_BATCH, for long-running background work", "SCHED_IDLE, run when free"], a: 1, why: "Fixed priority 1 to 99, preempting every CFS thread, running until it blocks or yields. It will hang the machine if it spins, hence the default runtime throttle." },
{ t: "os-sched", d: 2, q: "Under rate monotonic assignment, who gets top priority?", o: ["The task with the shortest period", "The task most important to the product", "The task with the longest runtime", "The task created earliest at boot"], a: 0, why: "A mathematical assignment rather than a judgement, and it comes with a utilisation bound near 69% below which the set is provably schedulable." },
{ t: "os-sched", d: 2, q: "What is the difference between SCHED_FIFO and SCHED_RR?", o: ["RR uses a completely different queue", "RR time-slices between equal priorities", "FIFO cannot be preempted at all", "FIFO is limited to a single core"], a: 1, why: "Both are fixed priority and both outrank CFS. FIFO runs until it blocks or yields; RR shares the CPU round robin among threads at the same priority." },
{ t: "os-sched", d: 2, q: "Why is plain round robin unsuitable for real time?", o: ["It cannot preempt a running task", "Response depends on how many exist", "It needs a tick that is too coarse", "It cannot express task importance"], a: 1, why: "Adding one more task changes everyone's worst case, so nothing can be proved in advance. Priority is what breaks that coupling." },
{ t: "os-sched", d: 3, q: "What is the real-time throttle in Linux for?", o: ["Capping how many RT threads exist", "Stopping a spinning RT thread hanging the box", "Limiting RT threads to certain cores", "Preventing priority inversion between real-time threads"], a: 1, why: "A SCHED_FIFO thread that never blocks would lock out everything below it forever, including your shell. By default the kernel reserves a slice for the rest." },
{ t: "os-sched", d: 3, q: "What does SCHED_DEADLINE add over SCHED_FIFO?", o: ["A higher maximum priority value", "Earliest deadline first, with admission control", "Guaranteed cache and TLB residency", "Automatic pinning to an isolated core, with its cache reserved"], a: 1, why: "You declare a runtime, period and deadline, and the kernel refuses the thread if the set is not schedulable. It is closer to rate monotonic analysis than to a priority." },
{ t: "os-sched", d: 3, q: "You want RTOS behaviour under Linux. What else beyond SCHED_FIFO?", o: ["Raise the nice value to -20", "Pin the core and mlockall the memory", "Disable the watchdog and the tick", "Run the process as root only"], a: 1, why: "The scheduler guarantee is worthless if a page fault or a migration intervenes, so the memory is pinned and the thread is kept on an isolated core." },

// ---------------------------------------------------------------- os-sync
{ t: "os-sync", d: 1, q: "What is the essential difference between a mutex and a semaphore?", o: ["A semaphore can count above one", "A mutex has an owner and a semaphore has none", "A mutex is faster to acquire", "A semaphore can only be used between separate processes"], a: 1, why: "Counting is a consequence. Ownership is what lets the kernel boost the holder, which is why only a mutex can offer priority inheritance." },
{ t: "os-sync", d: 1, q: "Which primitive should protect a shared data structure?", o: ["A binary semaphore, taken and given", "A mutex", "A condition variable, waited on", "An atomic flag, tested and set"], a: 1, why: "Anything else loses priority inheritance or is not mutual exclusion at all. Semaphores are for signalling and counting, not for guarding data." },
{ t: "os-sync", d: 2, q: "Why is a binary semaphore a poor mutex?", o: ["It is measurably slower to take and to give back", "No owner, so no priority inheritance", "It cannot be taken from a task", "Only one waiter may block on it"], a: 1, why: "The code compiles, runs and looks right, and you have quietly reintroduced unbounded priority inversion. That is the Mars Pathfinder failure." },
{ t: "os-sync", d: 2, q: "An ISR needs to tell a task that data arrived. Use what?", o: ["A mutex the handler takes", "A semaphore the handler gives", "A spinlock held across both", "A condition variable it signals"], a: 1, why: "A handler cannot own or block, and a give has no owner so it is legal. It is why RTOS APIs carry FromISR variants that never wait." },
{ t: "os-sync", d: 2, q: "What is priority inversion?", o: ["A high task running below a low one", "A medium task preempting the lock holder", "The scheduler reversing two priorities", "A task inheriting the wrong priority"], a: 1, why: "The high-priority thread waits on a lock held by a low-priority thread that cannot run, because an unrelated medium-priority thread is using the CPU." },
{ t: "os-sync", d: 2, q: "Why wait on a condition variable in a while loop?", o: ["The mutex must be reacquired each time", "Wakeups can be spurious or already taken", "It reduces load on the scheduler", "POSIX mandates that structure"], a: 1, why: "You can wake without the predicate being true, or another thread can consume the condition first. Re-checking is the only safe form." },
{ t: "os-sync", d: 2, q: "When is a spinlock the right choice?", o: ["Whenever contention is expected to be low", "Where you cannot sleep and holds are tiny", "In userspace, to avoid syscall overhead", "When several readers need concurrent access"], a: 1, why: "Inside the kernel or an interrupt handler, where blocking is impossible and the hold time is shorter than a context switch. In userspace it is nearly always wrong." },
{ t: "os-sync", d: 3, q: "When is a read-write lock worth its cost?", o: ["Whenever more than one reader exists", "Only when reads massively dominate", "For any structure larger than a word", "When writers must never be starved"], a: 1, why: "The bookkeeping is dearer than a plain mutex, so a modest read majority makes it slower rather than faster, and it can starve writers." },
{ t: "os-sync", d: 3, q: "What can an atomic replace, and what can it not?", o: ["Any mutex, if the data is small", "A counter or flag, not a critical section", "A semaphore, but not a mutex", "A spinlock, provided it is held in interrupt context"], a: 1, why: "One word updated indivisibly. The moment two values must change together, or an invariant spans them, you are back to needing a lock." },
{ t: "os-sync", d: 3, q: "Does priority inheritance fully solve priority inversion?", o: ["Yes, the problem is eliminated", "It bounds the delay rather than removing it", "Only when there is exactly one mutex involved in the chain", "Only under a real-time scheduler"], a: 1, why: "The high-priority thread still waits for the holder to finish its critical section. What inheritance removes is the unbounded part, where unrelated threads extend the wait." },

// ------------------------------------------------------------ os-deadlock
{ t: "os-deadlock", d: 1, q: "How many of Coffman's conditions must hold at once?", o: ["Any single one of the four", "All four", "At least two of the four", "Three, circular wait optional"], a: 1, why: "Which is exactly why prevention works: break any one and deadlock becomes impossible, and lock ordering breaks circular wait for free." },
{ t: "os-deadlock", d: 1, q: "Which is NOT one of Coffman's four conditions?", o: ["Hold and wait on another resource", "Priority inheritance", "Circular wait", "No preemption"], a: 1, why: "The four are mutual exclusion, hold and wait, no preemption and circular wait. Priority inheritance is a fix for inversion, which is a different problem entirely." },
{ t: "os-deadlock", d: 2, q: "What is the standard practical defence?", o: ["Detecting cycles in a wait-for graph", "A global lock ordering by rank", "Banker's algorithm on declared claims", "Timeouts on every acquisition"], a: 1, why: "Every lock gets a rank and threads acquire in increasing rank, breaking circular wait at no runtime cost. Timeouts help you notice, they do not prevent." },
{ t: "os-deadlock", d: 2, q: "What does Linux's lockdep do?", o: ["Detects a deadlock once it happens", "Watches acquisition order and warns", "Enforces a timeout on every lock", "Serialises all locks through one path"], a: 1, why: "It builds the ordering it observes and complains the first time two threads disagree, so the bug is reported before the two paths ever run concurrently." },
{ t: "os-deadlock", d: 2, q: "Threads are running hard and achieving nothing. What is it?", o: ["Deadlock, since no work completes", "Livelock", "Starvation of the lowest priority", "Priority inversion on a held lock"], a: 1, why: "Deadlock is blocked and idle. Livelock is busy and useless, like two people repeatedly stepping aside for each other, and a random backoff usually breaks it." },
{ t: "os-deadlock", d: 2, q: "Why is priority inversion not deadlock?", o: ["It involves only two threads", "There is no cycle, and it resolves", "The scheduler detects and clears it", "It cannot happen on one core"], a: 1, why: "The holder finishes eventually so the waiter does run, possibly far too late. Nothing is circular, and the fix is inheritance rather than lock ordering." },
{ t: "os-deadlock", d: 2, q: "What is starvation, as distinct from deadlock?", o: ["A thread waiting on a lock forever", "A thread never scheduled, with no cycle", "A process denied memory it requested", "Two threads each holding the other's lock"], a: 1, why: "Nothing is stuck in a cycle; the policy simply never picks it. It is why CFS refuses to starve anything, at the cost of guaranteeing nothing." },
{ t: "os-deadlock", d: 3, q: "Which condition does lock ordering break?", o: ["Mutual exclusion", "Circular wait", "Hold and wait", "No preemption"], a: 1, why: "If every thread acquires in increasing rank, a cycle cannot form, because forming one would require somebody to acquire downwards." },
{ t: "os-deadlock", d: 3, q: "Why is Banker's algorithm essentially never used?", o: ["It is far too slow to run on every single request", "Threads must declare maximum claims up front", "It requires a single global lock", "It only works with two processes"], a: 1, why: "Knowing every resource a thread could ever want, before it starts, is not information real software has. Prevention by ordering needs no such declaration." },
{ t: "os-deadlock", d: 3, q: "What does a timeout on a lock acquisition buy you?", o: ["It prevents the deadlock from ever occurring", "Visibility: a stuck thread is not silent", "Automatic release of the other lock", "A guarantee of forward progress"], a: 1, why: "The cycle can still form; the timeout only means somebody notices. It pairs with a watchdog so a deadlocked product reboots rather than sitting there." }

];
