/* Options here are deliberately balanced in length, and each distractor is a
 * real misconception rather than a throwaway fragment. The correct answer
 * being reliably the longest makes a bank guessable without knowing anything,
 * and the reasoning belongs in `why` rather than in the option. */

BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// -------------------------------------------------------------- emb-gdb
{ t: "emb-gdb", d: 2, q: "A variable is corrupted and you cannot find the writer. Which gdb feature answers it?", o: ["A breakpoint on every function that could plausibly touch it", "A watchpoint on the variable, which halts on the write", "Logging at each assignment, correlated afterwards", "Single-stepping from main until the value visibly changes"], a: 1, why: "<p><code>watch rx_len</code>, continue, and the next stop is the culprit with a full call stack.</p><p>Cortex-M implements watchpoints in the DWT unit, so there are typically four and they want aligned addresses of 1, 2 or 4 bytes.</p>" },
{ t: "emb-gdb", d: 2, q: "You ask for more watchpoints than the hardware has. What happens?", o: ["gdb refuses, and tells you no hardware slots remain", "It falls back to single-stepping, which looks like a hang", "The oldest watchpoint is silently dropped to make room", "They become breakpoints, halting on execution not access"], a: 1, why: "<p>Single-stepping the whole program is thousands of times slower, so the failure presents as the debugger freezing rather than as an error.</p><p>That is why the DWT limit is worth carrying in your head.</p>" },
{ t: "emb-gdb", d: 2, q: "gdb prints &lt;optimized out&gt; and stepping jumps around. What does that indicate?", o: ["The debugger has lost sync and needs reattaching", "The build is optimised: the code no longer matches the source", "The ELF does not match the image actually on the board", "The probe clock is too fast, so register reads are garbage"], a: 1, why: "<p>It is an accurate view rather than a fault. <code>-Og</code> is the development setting: it optimises but keeps the debug view honest.</p><p>Recognising it out loud is worth more in an interview than being puzzled by it.</p>" },
{ t: "emb-gdb", d: 2, q: "What does the <code>monitor</code> command do?", o: ["Watches a variable and prints it each time it changes", "Passes the rest of the line to the probe server, not gdb", "Displays a memory region continuously as the program runs", "Starts an instruction trace through the ITM or ETM unit"], a: 1, why: "<p>It is how you reach OpenOCD or J-Link commands such as <code>reset halt</code>, <code>reset init</code> and flash operations, which gdb itself knows nothing about.</p>" },
{ t: "emb-gdb", d: 2, q: "Which command reads a peripheral register block?", o: ["p reg, having declared reg as a volatile pointer", "x/8xw 0x40021000", "info registers, which dumps everything the core knows", "ptype reg, then read the members it reports"], a: 1, why: "<p>Examine eight words in hex from that address, which answers 'did that write actually land' in one line.</p><p><code>info registers</code> shows the CPU's registers, not the peripheral's.</p>" },
{ t: "emb-gdb", d: 3, q: "On a Cortex-M fault, where is the PC of the faulting instruction?", o: ["In the PC register, which the fault handler preserves", "In the stacked exception frame, seventh word from the base", "In BFAR, alongside the address that actually caused the fault", "In the link register, which holds EXC_RETURN on entry"], a: 1, why: "<p>The frame holds R0 to R3, R12, LR, PC and xPSR. The live PC is inside the handler, so it tells you nothing about the fault.</p><p><code>x/8xw $sp</code>, then <code>addr2line</code> against the ELF for that exact build, gives you the line.</p>" },
{ t: "emb-gdb", d: 3, q: "Which register tells you what kind of Cortex-M fault occurred?", o: ["BFAR at 0xE000ED38, which holds the faulting address", "CFSR at 0xE000ED28", "VTOR, which points at the vector table currently in use", "xPSR, whose exception number field names the handler"], a: 1, why: "<p>The Configurable Fault Status Register splits into memory-manage, bus and usage fault bytes.</p><p>BFAR and MMFAR hold the offending <b>address</b>, and only when the corresponding valid bit in CFSR is set.</p>" },
{ t: "emb-gdb", d: 3, q: "Why is a conditional breakpoint often better than a plain one?", o: ["It halts the target less often, so the session stays responsive", "It fires only on the case you care about", "It uses a comparator rather than a hardware breakpoint slot", "It survives optimisation, where a plain breakpoint may not"], a: 1, why: "<p><code>b uart.c:214 if len &gt; 64</code> skips the thousands of ordinary passes, which is what makes an intermittent bug findable.</p><p>Note that gdb evaluates the condition on the host, so the target halts every time and it is slow in a hot path.</p>" },

// ------------------------------------------------------------ emb-design
{ t: "emb-design", d: 2, q: "How should you open an answer to a system design question?", o: ["By naming a microcontroller that fits the obvious requirements", "By asking what it has to do, in numbers rather than adjectives", "By drawing the block diagram so everyone shares a picture", "By listing the peripherals the product will obviously need"], a: 1, why: "<p>Starting with a part number reveals that you have chosen before you have constrained.</p><p>Three or four well-chosen questions is enough; running through a checklist mechanically is its own kind of failure.</p>" },
{ t: "emb-design", d: 2, q: "For a battery product, which calculation changes the whole design?", o: ["Flash usage, since the logging format decides the part you need", "The average current budget, from capacity and target life", "Clock speed, since it sets both throughput and consumption", "Radio throughput, which decides how long the link is active"], a: 1, why: "<p>2000 mAh over a year is about 228 microamps average. Once you have that number the radio and the sampling turn out to be rounding errors, and sleep current is the design.</p><p>One calculation out loud is worth ten minutes of block diagram.</p>" },
{ t: "emb-design", d: 2, q: "What is the strongest unprompted signal in a design answer?", o: ["Choosing a part that comfortably exceeds every requirement", "Naming the failure modes, and what you would do about each", "A clear block diagram that everyone in the room can follow", "Citing the standard the product will have to be certified to"], a: 1, why: "<p>Flash wear, power loss mid-write, a dropped upload, clock drift, battery ageing under load, a bad update.</p><p>Each one is evidence you have shipped something rather than only designed it.</p>" },
{ t: "emb-design", d: 2, q: "Asked what you would build first, what is the best kind of answer?", o: ["The hardest subsystem, so the risk is retired early", "The measurement that could invalidate the whole design", "The user interface, so there is something to demonstrate", "The communications stack, since everything else depends on it"], a: 1, why: "<p>Putting the part in its deepest sleep and measuring the real current, before building any feature, is the answer of someone who has watched a power budget fail.</p><p>Building the feature first and discovering the constraint later is exactly the mistake the question probes for.</p>" },
{ t: "emb-design", d: 2, q: "A logger writes one record per second for a year. What does that force?", o: ["A larger flash part, so there is room for a year of records", "Wear levelling, or a log-structured store that appends", "A faster bus, so each write occupies the part for less time", "Compression, so that fewer bytes are committed per record"], a: 1, why: "<p>31 million writes against an endurance quoted per sector, typically 10,000 to 100,000 erase cycles, so erasing in place at that rate fails in weeks.</p><p>Appending records and compacting occasionally spreads the wear by construction.</p>" },
{ t: "emb-design", d: 3, q: "Why not erase logged data as soon as you have transmitted it?", o: ["Erasing is slow, so batching it saves both power and time", "It may not have arrived: wait for the peer to acknowledge", "Flash needs time to settle before a sector can be reused", "It wastes power, since the radio and the erase overlap badly"], a: 1, why: "<p>Choosing which failure you prefer is the design decision, and a duplicate the consumer can discard is almost always better than data that no longer exists anywhere.</p>" },
{ t: "emb-design", d: 3, q: "Why can a battery that measures fine at rest still brown out during a radio burst?", o: ["The resting measurement is wrong, because of ADC settling", "Internal resistance rises with age and cold", "The radio draws considerably more than its datasheet rating", "Capacity falls with temperature, so the cell empties sooner"], a: 1, why: "<p>The load current then pulls the terminal voltage down, which a resting measurement cannot show.</p><p>It is why a bulk capacitor near the radio and a brownout threshold that accounts for the burst both belong in the design, and why testing at room temperature on a fresh cell misses it entirely.</p>" },
{ t: "emb-design", d: 3, q: "What is the second failure mode of a design answer, after starting with a part number?", o: ["Talking for too long without reaching a concrete proposal", "Refusing to commit after you have asked the questions", "Drawing so much detail that the discussion never leaves it", "Asking so many questions that you never get to an answer"], a: 1, why: "<p>'I would use an RTOS because the BLE stack requires one, and I would keep the thread count small' is an answer. 'It depends' is not.</p>" },

// -------------------------------------------------------- emb-buildtools
{ t: "emb-buildtools", d: 2, q: "A Makefile rebuilds nothing when you edit a header. What is missing?", o: ["A clean target, so a stale object cannot survive a rebuild", "Header dependency generation, with -MMD and -include", "A .PHONY declaration on the objects as well as the targets", "Tab indentation, which make requires on every recipe line"], a: 1, why: "<p>Without it make has no idea an object depends on a header, so you debug a stale object and lose an afternoon.</p><p><code>-MMD -MP</code> makes the compiler emit a <code>.d</code> file per object, and <code>-include</code> pulls them in. Two lines.</p>" },
{ t: "emb-buildtools", d: 2, q: "What does <code>-ffunction-sections</code> achieve on its own?", o: ["Smaller code straight away, since functions are packed tight", "Little on its own: it needs the linker's --gc-sections", "Faster linking, because the linker can parallelise sections", "Better debug information, since symbols keep their own space"], a: 1, why: "<p>It places each function in its own section so the linker can drop the ones nothing references.</p><p>The two only pay off together, which is why they are always quoted as a pair.</p>" },
{ t: "emb-buildtools", d: 2, q: "In modern CMake, what do PRIVATE, PUBLIC and INTERFACE control?", o: ["Symbol visibility in the binary, as -fvisibility would", "Who inherits it: this target, consumers, or both", "Which targets are permitted to include the source files", "Whether the option is required or may be silently skipped"], a: 1, why: "<p>It is what stops one library's private include path leaking across the project.</p><p>The old global commands, <code>include_directories</code> and <code>add_definitions</code>, applied to everything, which is exactly the problem the target commands replaced.</p>" },
{ t: "emb-buildtools", d: 2, q: "A compile flag seems to have no effect. What do you do first?", o: ["Run make clean and rebuild, in case an object is stale", "Read the compile line that actually ran, with -v or make -n", "Reinstall the toolchain, since a flag it rejects is ignored", "Check the documentation for the flag's exact spelling"], a: 1, why: "<p>The build files tell you your intention; the compile line tells you the result.</p><p>Almost every case is a target-versus-global scope mistake, and reading the line exposes it in seconds.</p>" },
{ t: "emb-buildtools", d: 2, q: "Why must -mfloat-abi agree across every object and library?", o: ["It only affects speed, so a mismatch costs performance", "It decides whether floats pass in FPU or core registers", "It sets the FPU clock divider, which must match the core", "It is only a warning, and the linker resolves it either way"], a: 1, why: "<p>The link error is the good outcome. The bad one is a mixed build that runs and produces nonsense from any function taking a float.</p>" },
{ t: "emb-buildtools", d: 3, q: "Why does a bare-metal CMake toolchain file set CMAKE_TRY_COMPILE_TARGET_TYPE to STATIC_LIBRARY?", o: ["To make the configure step finish noticeably faster", "Otherwise CMake tries to link a test executable, and fails", "It selects the archiver rather than the linker for libraries", "It disables optimisation during compiler feature detection"], a: 1, why: "<p>Configure-time compiler detection assumes a hosted environment, and a bare-metal target has no startup code or linker script yet. Stopping at a static library skips the link.</p><p><code>CMAKE_SYSTEM_NAME Generic</code> is the other half: it says there is no operating system.</p>" },
{ t: "emb-buildtools", d: 3, q: "Why is <code>.PHONY: clean</code> needed?", o: ["It makes clean run before every other target in the file", "So make does not skip it when a file named clean exists", "It suppresses the echo of the recipe as make runs it", "It allows the target to be run in parallel with the others"], a: 1, why: "<p>make decides by comparing file timestamps, so a target that is not a file has to be declared as such, or an unrelated file with that name silently disables it.</p>" },
{ t: "emb-buildtools", d: 3, q: "What does -g3 cost in the flashed image?", o: ["Roughly 20 percent, which matters on a small part", "Nothing: it lives in the ELF, not the flashed binary", "It roughly doubles the image, so release builds omit it", "It prevents optimisation, so the image grows for that reason"], a: 1, why: "<p>Which is why there is no reason to build a release without it, provided you archive the ELF.</p><p>A fault address from the field only decodes against the symbols from that exact build.</p>" }

]);
