// A second pass over every Control lesson: ten more questions each.
//
// Topic tags are lesson ids, so topicLesson() resolves them by the byId
// fallback and no TOPIC_LESSON entry is needed.
//
// Correct options are kept short and the reasoning put in `why`, which the
// page shows the moment you answer. A distractor is the longest option in
// about three questions out of four, which is chance for four options.
BANKS["Control"] = BANKS["Control"].concat([

// ------------------------------------------------------------------- pid
{ t: "pid", d: 1, q: "What does the integral term of a PID controller remove?", o: ["Steady-state error", "The overshoot that the proportional term would otherwise produce", "High-frequency noise appearing on the measurement signal", "The delay between the command and the plant's response"], a: 0, why: "Proportional action needs a non-zero error to produce any output, so a constant load leaves a constant offset. The integrator accumulates until that offset is gone." },
{ t: "pid", d: 2, q: "What is integral windup?", o: ["The integrator accumulating while the actuator is saturated", "The integral gain drifting upward as the controller runs", "An oscillation caused by too large an integral gain setting", "The integrator saturating at its own numerical limit"], a: 0, why: "While the output is clamped the error persists, so the integrator keeps growing and then has to unwind before the actuator comes off the limit. That unwinding is the long overshoot you see." },
{ t: "pid", d: 2, q: "What is the standard cure for windup?", o: ["Stop integrating while the actuator is at its limit", "Reduce the integral gain until saturation never occurs at all", "Add a derivative term to anticipate the approaching limit", "Reset the integrator to zero on every setpoint change"], a: 0, why: "Conditional integration, or back-calculating the integral from the saturated output, both work. Turning the gain down instead gives up performance everywhere to fix a problem at the limit." },
{ t: "pid", d: 2, q: "Why is derivative action taken on the measurement rather than the error?", o: ["A setpoint step would otherwise produce an impulse", "The measurement is less noisy than the error signal", "It makes the derivative term easier to compute digitally", "The error is not available until the setpoint has settled"], a: 0, why: "Differentiating a step gives a spike that saturates the actuator and excites resonances for no benefit. Using the measurement gives the same disturbance rejection without the kick." },
{ t: "pid", d: 2, q: "Why must a derivative term be filtered?", o: ["Differentiation amplifies high-frequency noise", "The derivative would otherwise introduce a steady-state error", "An unfiltered derivative cannot be implemented in discrete time", "The term would otherwise respond before the error occurs"], a: 0, why: "The gain of a differentiator rises with frequency, so measurement noise dominates the output. A first-order filter bounds that gain, and its time constant is a real tuning parameter." },
{ t: "pid", d: 3, q: "What does increasing proportional gain do to a loop?", o: ["Faster response and less margin", "Slower response but a smaller steady-state error at the output", "Faster response with no effect on the stability margin at all", "A reduction in the sensitivity to measurement noise"], a: 0, why: "It raises the loop gain, which speeds the response and reduces the offset, and it moves the gain crossover to a frequency with less phase margin. Somewhere past that the loop rings and then oscillates." },
{ t: "pid", d: 2, q: "What is bumpless transfer?", o: ["Switching modes without a step in the actuator command", "Changing the setpoint slowly enough that the plant can follow", "Transferring control between two machines without stopping", "Switching the controller off without disturbing the plant"], a: 0, why: "Two controllers hold different internal states, so switching without initialising the incoming one produces a jump. Pre-loading its integrator to match the current output removes it." },
{ t: "pid", d: 2, q: "What does setpoint weighting achieve?", o: ["Different response to a command and to a disturbance", "A faster settling time for every kind of input", "Removal of the steady-state error without an integrator", "Automatic adjustment of the gains as the setpoint changes"], a: 0, why: "Applying only a fraction of the setpoint to the proportional term softens the command response while leaving disturbance rejection alone. It is the two-degree-of-freedom idea in its simplest form." },
{ t: "pid", d: 2, q: "Why is a PID controller often enough in practice?", o: ["Most plants behave like a first or second order system near crossover", "PID is provably optimal for any linear plant", "It is the only structure that guarantees zero steady-state error at all", "More complex controllers cannot be implemented in fixed point"], a: 0, why: "What matters is the behaviour around the crossover frequency, and three terms shape that adequately for a great many processes. Where the plant has significant delay or resonance, it starts to run out." },
{ t: "pid", d: 2, q: "What does the Ziegler-Nichols method need from the plant?", o: ["A step response or the gain at which it oscillates", "A complete state-space model of the whole system", "The plant's transfer function in analytic form", "A frequency response measured over three decades"], a: 0, why: "It is a rule of thumb from two easily measured numbers, which is its whole appeal. The tunings it gives are aggressive and usually need detuning for anything that must not overshoot." },

// ---------------------------------------------------------------- kalman
{ t: "kalman", d: 1, q: "What does a Kalman filter maintain?", o: ["A state estimate and its covariance", "A history of every measurement taken so far", "A set of candidate states weighted by likelihood", "The difference between the model and the plant"], a: 0, why: "The covariance is what lets it weigh new measurements against the prediction. Without it there is no principled way to decide how much to trust each." },
{ t: "kalman", d: 2, q: "What does the predict step do?", o: ["Propagates the state and grows the covariance", "Corrects the state using the newest measurement", "Computes the gain to be applied at the next update", "Resets the covariance to its initial value"], a: 0, why: "It applies the motion model and adds the process noise, so uncertainty always increases between measurements. The update is the step that shrinks it again." },
{ t: "kalman", d: 2, q: "What does a large measurement noise covariance tell the filter?", o: ["Trust the model more than the measurement", "The sensor is sampling too slowly to be useful", "The state should be reinitialised from the measurement", "The process noise must be increased to match"], a: 0, why: "R and Q together set the balance, so raising R makes the filter smoother and slower to follow the sensor. Tuning that ratio is most of what filter tuning actually is." },
{ t: "kalman", d: 3, q: "Why is the Kalman gain independent of the measurements?", o: ["It depends only on the covariances and the model", "The measurements are assumed to be noise-free", "The gain is recomputed from scratch on every step", "It is fixed at design time and never changes"], a: 0, why: "The covariance recursion involves only the model and the noise statistics, so the gain sequence can be computed offline for a time-invariant system. That is why a steady-state gain is often used instead." },
{ t: "kalman", d: 2, q: "What is the innovation?", o: ["The difference between the measurement and its prediction", "The change in the state estimate between two steps", "The amount of new information that the measurement actually carries", "The correction applied to the covariance matrix"], a: 0, why: "It is the part of the measurement the filter did not expect, and multiplying it by the gain gives the correction. Monitoring its statistics is the standard way to detect a badly tuned or diverging filter." },
{ t: "kalman", d: 2, q: "What does an innovation sequence that is not white indicate?", o: ["The model or the noise assumptions are wrong", "The sensor is failing and should be discarded", "The filter has converged and can be simplified", "The sample rate is too high for the dynamics"], a: 0, why: "A correctly tuned filter should leave nothing predictable in the residual. Correlation in it means there is structure the model is not capturing." },
{ t: "kalman", d: 2, q: "What does an extended Kalman filter do about nonlinearity?", o: ["Linearises about the current estimate at each step", "Runs several linear filters and blends their outputs", "Samples the distribution and propagates the points", "Ignores it, provided the nonlinearity is small"], a: 0, why: "It computes a Jacobian at the operating point and uses the linear equations there. The unscented filter instead propagates chosen sample points, which handles stronger nonlinearity without Jacobians." },
{ t: "kalman", d: 3, q: "Why can a Kalman filter diverge even when the model is right?", o: ["Too little process noise makes it stop believing measurements", "The covariance grows without bound between updates", "The gain becomes negative whenever the innovation is very large", "Numerical error accumulates in the state vector"], a: 0, why: "If Q is too small the covariance shrinks towards zero, the gain follows, and the filter ignores the sensor while the true state drifts away. A small floor on Q, or a square-root formulation, keeps it honest." },
{ t: "kalman", d: 2, q: "What is a complementary filter, compared with a Kalman filter?", o: ["A fixed-gain blend of two sensors by frequency", "A Kalman filter with the covariance update removed", "A filter that switches between two sensors on a threshold", "A Kalman filter for systems with no process noise"], a: 0, why: "Low-pass one sensor, high-pass the other and add, which is a Kalman filter with a fixed gain chosen by hand. On a small processor it is often entirely adequate." },
{ t: "kalman", d: 2, q: "Why does gating the innovation help in practice?", o: ["It rejects outliers before they corrupt the estimate", "It reduces the computation needed for each update", "It compensates for a measurement that arrives late", "It prevents the covariance from becoming singular"], a: 0, why: "A single wild measurement can move the state a long way, and a threshold on the normalised innovation discards it. Set the gate too tight and the filter ignores genuine manoeuvres." },

// ---------------------------------------------------------- ct-stability
{ t: "ct-stability", d: 1, q: "Where is phase margin measured?", o: ["At the gain crossover frequency", "At the frequency where the phase passes minus 180 degrees", "At the peak of the closed-loop frequency response", "At the frequency of the dominant closed-loop pole"], a: 0, why: "It is how much extra phase lag would take you to minus 180 where the magnitude is one. Gain margin is the complementary figure, measured at the phase crossover." },
{ t: "ct-stability", d: 2, q: "What does a phase margin of about 60 degrees usually give?", o: ["A well-damped step response with little overshoot", "The fastest possible response for that particular plant", "Zero steady-state error to a ramp input", "Immunity to any change in the plant's gain"], a: 0, why: "It corresponds to a damping ratio around 0.6, which is the usual compromise between speed and overshoot. Below about 30 degrees the response rings badly." },
{ t: "ct-stability", d: 2, q: "What does the Nyquist criterion count?", o: ["Encirclements of the minus one point", "The number of poles in the right half plane", "Crossings of the unit circle by the open-loop response", "The frequencies at which the gain exceeds unity"], a: 0, why: "It relates encirclements of minus one to the open-loop and closed-loop right-half-plane poles, so it works for plants that are already unstable. Bode's simpler reading assumes a stable, minimum-phase plant." },
{ t: "ct-stability", d: 2, q: "Why does a time delay reduce phase margin?", o: ["It adds phase lag proportional to frequency", "It reduces the gain at the crossover frequency", "It moves the plant's poles towards the imaginary axis", "It adds an integrator to the loop transfer function"], a: 0, why: "The lag is omega times the delay, so it grows without bound with frequency and eats the margin at crossover. It is why the achievable bandwidth is capped by the delay." },
{ t: "ct-stability", d: 3, q: "What does a right-half-plane zero do to achievable performance?", o: ["It fundamentally limits the closed-loop bandwidth", "It makes the plant unstable in open loop", "It removes the steady-state error at DC", "It can be cancelled by a matching controller pole"], a: 0, why: "It gives an initial response in the wrong direction, and no controller can remove it because cancelling it would need an unstable pole. Pushing the bandwidth past it makes the undershoot worse." },
{ t: "ct-stability", d: 2, q: "What does a lightly damped resonance in the plant require?", o: ["Either a notch or a bandwidth well below it", "A higher proportional gain to overpower it", "An integrator to remove its steady-state effect", "A faster sample rate to observe it correctly"], a: 0, why: "If the resonance sits near crossover, the loop excites it and the phase around it destroys the margin. Notching it out or rolling off well before it are the two honest options." },
{ t: "ct-stability", d: 2, q: "What does the sensitivity function describe?", o: ["How disturbances and reference errors pass through the loop", "The change in the plant's output for a change in gain", "The controller's response to a unit step in the setpoint", "The ratio of measurement noise to process noise"], a: 0, why: "Reducing it at one frequency necessarily raises it elsewhere, which is Bode's integral constraint. That is why disturbance rejection improves in one band at the cost of another." },
{ t: "ct-stability", d: 2, q: "What is a gain margin of 6 dB telling you?", o: ["The gain can double before the loop becomes unstable", "The loop gain falls by 6 dB at the crossover frequency", "The plant's gain varies by 6 dB over its operating range", "The controller has 6 dB of headroom before saturating"], a: 0, why: "It is the factor by which the open-loop gain may rise before the Nyquist plot reaches minus one. Six decibels is a factor of two, which is modest for a plant whose gain varies with operating point." },
{ t: "ct-stability", d: 3, q: "Why is a lead compensator used?", o: ["It adds phase near crossover to restore margin", "It increases the gain at low frequency for accuracy", "It attenuates the high-frequency measurement noise", "It removes a right-half-plane zero from the plant"], a: 0, why: "The zero comes before the pole, so it contributes phase lead in a band you place around crossover. The cost is higher gain at high frequency, which amplifies noise." },
{ t: "ct-stability", d: 2, q: "What does a lag compensator do?", o: ["Raises low-frequency gain without changing crossover much", "It adds phase lead in the whole region right around crossover", "Removes the plant's resonance from the loop", "Increases the bandwidth of the closed loop"], a: 0, why: "The pole comes first, so it lifts the gain at low frequency for better steady-state accuracy and leaves the crossover region nearly alone. Its phase lag has to be kept away from crossover." },

// ----------------------------------------------------------- ct-discrete
{ t: "ct-discrete", d: 1, q: "What is a sensible sample rate for a control loop?", o: ["Ten to twenty times the closed-loop bandwidth", "Exactly twice the closed-loop bandwidth, by Nyquist", "As fast as the processor will allow in every case", "The same as the plant's fastest mechanical resonance"], a: 0, why: "Nyquist is the limit for reconstruction, not for control, where the sampling delay eats phase margin. Ten to twenty times keeps that delay small compared with the loop's own dynamics." },
{ t: "ct-discrete", d: 2, q: "What does sampling add to the loop, from a stability point of view?", o: ["An effective delay of about half a sample", "A gain reduction of one half at every frequency", "A pole at the Nyquist frequency", "An integrator that must be compensated"], a: 0, why: "Zero-order hold behaves approximately as a half-sample delay, whose phase lag grows with frequency. That is the phase margin sampling costs you." },
{ t: "ct-discrete", d: 2, q: "Where are the poles of a stable discrete-time system?", o: ["Inside the unit circle", "In the left half of the complex plane", "Outside the unit circle but within radius two", "On the positive real axis"], a: 0, why: "The left-half-plane condition maps to the unit disc under the z transform. A pole at radius one is marginally stable and rings for ever." },
{ t: "ct-discrete", d: 2, q: "Why must jitter in the control loop's timing be controlled?", o: ["It varies the effective delay and the integrator's step", "It changes the plant's transfer function directly", "It causes the analogue-to-digital converter to alias", "It makes the derivative term overflow"], a: 0, why: "A loop that runs late has more phase lag that cycle, and a fixed integral gain assumes a fixed interval. Running the loop from a hardware timer rather than a software delay is the fix." },
{ t: "ct-discrete", d: 3, q: "Why does discretising a controller change its behaviour?", o: ["The mapping is approximate and frequency dependent", "Discrete controllers cannot include derivative terms", "The gains must be scaled by the sample period", "Fixed-point arithmetic changes the pole locations"], a: 0, why: "Tustin, backward difference and zero-order hold all give slightly different results, and they diverge as you approach Nyquist. Verifying the discrete design rather than trusting the continuous one is the discipline." },
{ t: "ct-discrete", d: 2, q: "What does the bilinear transform preserve?", o: ["Stability, mapping the left half plane into the disc", "The exact frequency response at every single frequency", "The impulse response of the continuous system", "The DC gain and the phase margin together"], a: 0, why: "Every stable continuous pole maps to a stable discrete one, which is why it is the default. The price is frequency warping, corrected by pre-warping the critical frequencies." },
{ t: "ct-discrete", d: 2, q: "How should an integrator be implemented in discrete time?", o: ["Accumulate the error times the sample period", "Sum the errors without scaling by the period", "Difference the error between successive samples", "Multiply the error by the integral gain only"], a: 0, why: "Omitting the period makes the effective integral gain depend on the sample rate, so changing the rate silently retunes the loop. Trapezoidal accumulation is a little more accurate than rectangular." },
{ t: "ct-discrete", d: 2, q: "What is the effect of computational delay in a digital loop?", o: ["It adds to the sampling delay and costs phase margin", "It changes the controller's gain but not its phase", "It only matters if it exceeds one sample period", "It is removed automatically by the zero-order hold"], a: 0, why: "Reading the sensor, computing and writing the actuator all take time, and that delay is in the loop. Doing the output computation first, and the housekeeping afterwards, minimises it." },
{ t: "ct-discrete", d: 3, q: "Why can a discrete controller behave badly between samples?", o: ["Intersample ripple is invisible to the discrete model", "The plant is nonlinear between the sampling instants", "The zero-order hold introduces harmonics of the sample rate", "The controller's state is undefined between updates"], a: 0, why: "A design checked only at the sampling instants can hide oscillation in between, especially with a fast plant and a slow loop. Simulating the continuous plant with the discrete controller is what reveals it." },
{ t: "ct-discrete", d: 2, q: "What is deadbeat control?", o: ["Driving the error to zero in a fixed number of samples", "A controller with no derivative or integral action", "A design that ignores the plant between samples", "Control that stops updating once the error is small"], a: 0, why: "It places all the closed-loop poles at the origin, so the response settles in as many steps as the plant has states. It demands large actuator effort and is very sensitive to model error." },

// ---------------------------------------------------------- ct-statespace
{ t: "ct-statespace", d: 1, q: "What does the state vector of a system represent?", o: ["Enough information to predict the future given the input", "The list of every single sensor reading currently available", "The difference between the plant and its model", "The inputs and outputs of the system combined"], a: 0, why: "It is the minimal memory of the system, which is why its dimension is the system's order. Anything the future depends on must be in it." },
{ t: "ct-statespace", d: 2, q: "What does controllability mean?", o: ["Every state can be reached using the input", "Every state can be measured from the outputs", "The plant is stable in open loop", "The input has enough authority to hold any state"], a: 0, why: "It says the input can drive the state anywhere in finite time. An uncontrollable mode cannot be moved by feedback, so its natural dynamics are what you get." },
{ t: "ct-statespace", d: 2, q: "What does observability mean?", o: ["Every state can be reconstructed from the outputs", "Every single state is directly measured by a sensor", "The output depends on every state variable", "The system has as many outputs as states"], a: 0, why: "It says the output history is enough to determine the state, which is what an observer needs. An unobservable mode is invisible, so no estimator can track it." },
{ t: "ct-statespace", d: 2, q: "What does the D matrix represent?", o: ["Direct feedthrough from input to output", "The damping of each mode of the system", "The disturbance entering the plant", "The derivative of the state vector"], a: 0, why: "A non-zero D means an input change appears instantly at the output, with no state in between. Most physical plants have D equal to zero, which is why it is so often omitted." },
{ t: "ct-statespace", d: 3, q: "What does pole placement by state feedback require?", o: ["A controllable system and a measurement of every state", "A plant that happens to be already stable when in open loop", "More inputs than states in the system", "A model with no direct feedthrough term"], a: 0, why: "Controllability is what makes arbitrary placement possible, and the feedback needs the state. Where the state is not measured, an observer supplies it and the separation principle lets you design the two independently." },
{ t: "ct-statespace", d: 2, q: "What is an observer for?", o: ["Estimating states that are not directly measured", "Filtering the noise from the measured outputs", "Detecting when a sensor has failed", "Compensating for the plant's time delay"], a: 0, why: "It runs a model of the plant driven by the same input and corrected by the output error. Its gain sets how quickly the estimate converges against how much measurement noise it lets through." },
{ t: "ct-statespace", d: 2, q: "What does the separation principle say?", o: ["The controller and observer can be designed independently", "The state and the output can always be separated by a filter", "Fast and slow dynamics can be designed separately", "The plant and the sensor can be modelled apart"], a: 0, why: "The closed-loop poles are the union of the two designs, so you can place them separately. It holds exactly for the linear case, and only approximately once saturation or nonlinearity appear." },
{ t: "ct-statespace", d: 2, q: "How do you get zero steady-state error with state feedback?", o: ["Augment the state with the integral of the error", "Increase the feedback gain until the error is negligible", "Add a feedforward term equal to the setpoint", "Place one closed-loop pole exactly at the origin"], a: 0, why: "Adding the integral as an extra state and including it in the design gives the same effect as integral action in PID. Simply raising the gain leaves an offset that shrinks but never vanishes." },
{ t: "ct-statespace", d: 3, q: "Why does observer gain trade against noise?", o: ["A fast observer follows the measurement, noise included", "A fast observer needs a higher sample rate to be stable", "A slow observer cannot track the plant's true state", "The gain affects only the transient, not the noise"], a: 0, why: "High gain means the estimate tracks the sensor closely, which is exactly what you want for a fast correction and exactly what passes the noise through. It is the same trade the Kalman gain makes formally." },
{ t: "ct-statespace", d: 2, q: "What is a minimal realisation?", o: ["A model that is both controllable and observable", "The model with the fewest inputs and outputs", "A state-space form with a diagonal A matrix", "The lowest-order model that matches the step response"], a: 0, why: "Any uncontrollable or unobservable mode is redundant to the input-output behaviour and can be removed. The remaining order is the true order of the transfer function." },

// ------------------------------------------------------------- ct-fusion
{ t: "ct-fusion", d: 1, q: "Why fuse a gyroscope with an accelerometer?", o: ["The gyro drifts and the accelerometer is noisy", "The two sensors measure the same quantity twice for redundancy", "The accelerometer has a much higher bandwidth than the gyro", "The gyro cannot measure rotation about the vertical axis"], a: 0, why: "Integrating the gyro gives a smooth angle that drifts, while the accelerometer gives an absolute reference corrupted by motion. Combining them by frequency gets both properties." },
{ t: "ct-fusion", d: 2, q: "How does a complementary filter combine them?", o: ["High-pass the integrated rate, low-pass the accelerometer", "Average the two estimates with equal weight", "Switch to whichever sensor has the lower noise", "Multiply the two signals together and then take the square root"], a: 0, why: "The two filters sum to one at every frequency, so the estimate is unbiased. The crossover frequency is the single tuning parameter and sets where drift gives way to noise." },
{ t: "ct-fusion", d: 2, q: "Why does an accelerometer give a poor attitude estimate during motion?", o: ["It measures acceleration plus gravity, not gravity alone", "Its bandwidth is simply far too low to follow the movement", "It saturates at the accelerations involved", "Its noise increases with the vehicle's speed"], a: 0, why: "In free fall it reads nothing, and under acceleration the vector it senses is not vertical. Weighting it down when the measured magnitude departs from one g is the usual defence." },
{ t: "ct-fusion", d: 3, q: "Why must sensors be timestamped at acquisition?", o: ["Fusion needs to know when each measurement was taken", "The processor cannot otherwise order the data correctly", "Timestamps are required by most sensor protocols", "It allows the sample rate to be verified afterwards"], a: 0, why: "A few milliseconds of skew at speed is metres of position error, and stamping at the fusion node measures the queue rather than the sensor. Stamp as close to the sensor as possible, against a shared clock." },
{ t: "ct-fusion", d: 2, q: "What does a magnetometer add to an inertial estimate?", o: ["An absolute heading reference", "A measurement of the vertical acceleration", "A redundant estimate of the roll angle", "A correction for the gyro's scale factor"], a: 0, why: "Gravity fixes roll and pitch but says nothing about heading, so yaw drifts without an external reference. The magnetometer supplies it, at the cost of sensitivity to nearby iron and currents." },
{ t: "ct-fusion", d: 2, q: "Why is gyro bias estimated as a state?", o: ["It drifts slowly and must be tracked, not assumed", "It is too large to be removed by calibration", "It changes discontinuously with temperature", "It cannot be measured while the device is still"], a: 0, why: "A constant offset integrates into a growing angle error, and the bias itself wanders with temperature and time. Including it in the state lets the absolute reference correct it continuously." },
{ t: "ct-fusion", d: 2, q: "What happens if one sensor's noise covariance is set far too low?", o: ["The filter follows that sensor and ignores the others", "The filter becomes unstable and diverges immediately", "The estimate becomes smoother than it should be", "The other sensors' biases grow without bound"], a: 0, why: "The gain for that measurement approaches one, so its noise appears directly in the estimate. Tuning the covariances against measured sensor noise, rather than by feel, avoids it." },
{ t: "ct-fusion", d: 3, q: "Why is a measurement that arrives late a problem?", o: ["It applies a correction from the past to the present state", "It cannot be used because the filter has moved on", "It forces the filter to run at the slowest sensor's rate", "It makes the covariance matrix lose symmetry"], a: 0, why: "The innovation was computed against an older state, so applying it now is wrong. Buffering and replaying from the timestamp, or a delayed-state formulation, handles it properly." },
{ t: "ct-fusion", d: 2, q: "What does sensor redundancy give you beyond accuracy?", o: ["The ability to detect that one has failed", "A guarantee that the estimate is unbiased", "A lower computational load for the same result", "Immunity to the effects of temperature drift"], a: 0, why: "Two sensors let you see a disagreement; three let you decide which is wrong. With two you can fail safe but not continue, which is a genuine architectural distinction." },
{ t: "ct-fusion", d: 2, q: "Why check the magnitude of the accelerometer vector during fusion?", o: ["It shows whether the reading is gravity alone", "It detects saturation of the sensor's range", "It measures the temperature of the device", "It reveals misalignment between the axes"], a: 0, why: "A magnitude far from one g means the vehicle is accelerating, so the vertical reference is unreliable just then. Down-weighting the measurement in that window is a cheap and effective gate." },

// ------------------------------------------------------------- ct-motion
{ t: "ct-motion", d: 1, q: "What does a trapezoidal velocity profile consist of?", o: ["Constant acceleration, constant velocity, constant deceleration", "A perfectly sinusoidal velocity throughout the entire length of the move", "A constant jerk applied over the entire motion", "A velocity proportional to the remaining distance"], a: 0, why: "It is the time-optimal profile subject to velocity and acceleration limits. Its discontinuous acceleration excites resonances, which is what an S-curve fixes." },
{ t: "ct-motion", d: 2, q: "What does an S-curve profile limit that a trapezoid does not?", o: ["Jerk, the rate of change of acceleration", "The peak velocity reached during the move", "The total energy consumed by the move", "The following error during the constant-velocity phase"], a: 0, why: "Bounding jerk smooths the acceleration steps, which stops the mechanism ringing. It costs a little more time for the same limits." },
{ t: "ct-motion", d: 2, q: "Why does a trapezoidal profile excite resonance?", o: ["Its acceleration steps contain broadband energy", "Its constant-velocity phase matches the natural frequency", "The deceleration phase reverses the motor's torque", "It commands a velocity the motor cannot follow"], a: 0, why: "A step in acceleration has energy at all frequencies, including the structure's resonance. Shaping the command, whether by S-curve or input shaping, removes the content at that frequency." },
{ t: "ct-motion", d: 3, q: "What does input shaping do?", o: ["Splits the command so the resonance cancels itself", "Filters the command through a low-pass filter", "Slows the move until the resonance is not excited", "Adds a notch filter in the feedback path"], a: 0, why: "Two or more scaled and delayed copies of the command are timed so the vibration each excites cancels. It needs a reasonable estimate of the resonant frequency and damping." },
{ t: "ct-motion", d: 2, q: "What is following error?", o: ["The difference between commanded and actual position", "The error remaining once the move has settled", "The accumulated error over the whole of the trajectory", "The difference between two axes' positions"], a: 0, why: "It is the instantaneous tracking error during the move, and it grows with commanded velocity in a proportional loop. Velocity feedforward is what removes most of it." },
{ t: "ct-motion", d: 2, q: "Why does velocity feedforward reduce following error?", o: ["It supplies the command the feedback would have to generate", "It increases the loop gain at high frequency", "It removes the integrator's phase lag", "It compensates for the encoder's own quantisation error as well"], a: 0, why: "A proportional loop needs an error to produce an output, so tracking a ramp leaves a steady offset. Feeding the demanded velocity forward means the feedback only handles what the model got wrong." },
{ t: "ct-motion", d: 2, q: "What does acceleration feedforward compensate for?", o: ["The torque needed to accelerate the inertia", "The friction force that always opposes the motion", "The gravity load on a vertical axis", "The backlash in the drive train"], a: 0, why: "Torque is inertia times acceleration, and the trajectory knows the acceleration before the axis moves. That term is entirely predictable and so belongs in feedforward." },
{ t: "ct-motion", d: 3, q: "Why is backlash particularly awkward for a position loop?", o: ["The loop loses authority entirely while crossing the gap", "It increases the effective inertia of the load", "It introduces a constant offset into the measured position", "It reduces the resolution of the encoder"], a: 0, why: "During the crossing the motor moves and the load does not, which is a variable delay in the loop. Dual encoders, or a controller that anticipates the reversal, are the usual answers." },
{ t: "ct-motion", d: 2, q: "What is the point of homing an axis?", o: ["Establishing the absolute position reference", "Removing the backlash before a move", "Calibrating the encoder's line count", "Charging up the encoder's own internal backup battery"], a: 0, why: "An incremental encoder only measures change, so a known physical reference is needed at start-up. An absolute encoder removes the requirement at extra cost." },
{ t: "ct-motion", d: 2, q: "Why interpolate a multi-axis move rather than command each axis separately?", o: ["The path between the endpoints would otherwise be uncontrolled", "Each axis would otherwise reach its limit at a different time", "The axes would draw more current than the supply allows", "The controller cannot command two axes simultaneously"], a: 0, why: "Independent moves give a path that depends on each axis's dynamics, which is fine for a point-to-point move and not for cutting a straight line. Coordinated interpolation is what makes the path itself the specification." },

// ------------------------------------------------------------- ct-robust
{ t: "ct-robust", d: 2, q: "What does robustness mean for a control loop?", o: ["It still works when the plant is not exactly the model", "It never saturates the actuator under any conditions", "It rejects every disturbance completely", "It has the fastest possible response time"], a: 0, why: "Every model is wrong somewhere, and gain and phase margin are the simplest measures of how wrong it can be. A design with no margin is a design that only works on paper." },
{ t: "ct-robust", d: 2, q: "Why is a very high-gain loop fragile?", o: ["Small model errors near crossover become large errors", "The actuator will always saturate when the gain is high", "The integrator winds up more quickly", "The sample rate must rise in proportion"], a: 0, why: "High gain pushes crossover to a frequency where the model is least trustworthy, typically near unmodelled resonances or delays. That is where the margin evaporates." },
{ t: "ct-robust", d: 2, q: "What is gain scheduling?", o: ["Changing the controller gains with operating point", "Ramping the gains up slowly after start-up", "Reducing the gains when the error is large", "Switching between two controllers on a fixed timer instead"], a: 0, why: "A plant whose dynamics change with speed, load or temperature can be handled by a family of linear designs. The interpolation between design points is untested, which is the standard criticism." },
{ t: "ct-robust", d: 3, q: "What is the danger of gain scheduling?", o: ["Interpolated gains are untested and rapid switching can destabilise", "The schedule must be recomputed at every sample", "It cannot be applied to a nonlinear plant", "The scheduling variable must always be measured exactly on every occasion"], a: 0, why: "Every fixed point being stable does not make the trajectory between them stable, especially if the scheduling variable moves quickly. Slowing the schedule relative to the loop is the practical mitigation." },
{ t: "ct-robust", d: 2, q: "Why should the scheduling variable vary slowly?", o: ["Fast variation makes the frozen-point analysis invalid", "The controller cannot compute new gains quickly enough", "It would otherwise couple into the measurement noise", "The gains would exceed their stored range"], a: 0, why: "The whole design rests on treating the system as linear at each operating point, which requires the point to move slowly compared with the loop. Otherwise the switching itself is a dynamic effect." },
{ t: "ct-robust", d: 2, q: "What does the small gain theorem give you?", o: ["A sufficient condition for stability under uncertainty", "The exact stability margin of a nonlinear loop", "A method for computing the optimal controller gain directly", "A bound on the steady-state error"], a: 0, why: "If the loop gain of the uncertainty and the nominal system is below one, stability is guaranteed. It is sufficient rather than necessary, so it can be conservative." },
{ t: "ct-robust", d: 2, q: "Why is a notch filter a fragile way to handle a resonance?", o: ["The resonance moves and the notch does not", "It adds phase lag across the whole passband", "It cannot be implemented in fixed point", "It reduces the loop's steady-state accuracy"], a: 0, why: "Temperature, load and wear all shift the resonant frequency, and a narrow notch that misses is worse than none. A wider notch, or a bandwidth well below the resonance, is more durable." },
{ t: "ct-robust", d: 3, q: "What does an unmodelled high-frequency mode do to a fast loop?", o: ["It appears near crossover and destroys the margin", "It slows the response but is otherwise harmless", "It adds a steady-state error proportional to gain", "It is filtered out by the anti-alias filter"], a: 0, why: "Models are usually accurate at low frequency and wrong at high frequency, so pushing bandwidth up walks into the errors. That is the fundamental reason not to make a loop faster than you have to." },
{ t: "ct-robust", d: 2, q: "Why test a controller at the extremes of its operating range?", o: ["The plant's gain and dynamics vary across it", "The processor's timing changes with temperature", "The sensors are least accurate at the extremes", "The actuator saturates only at the extremes"], a: 0, why: "A loop tuned at one operating point can be unstable at another, and the extremes are where the model is least representative. Hot, cold, loaded and unloaded is the minimum matrix." },
{ t: "ct-robust", d: 2, q: "What does a disturbance observer do?", o: ["Estimates the disturbance and cancels it", "Measures the disturbance with an extra sensor", "Filters the disturbance out of the measurement", "Detects when a disturbance has occurred"], a: 0, why: "It infers the difference between the nominal plant's expected output and the actual one, and feeds it back. It makes the plant look more like the model, which is a robustness gain as much as a performance one." },

// --------------------------------------------------------------- ct-freq
{ t: "ct-freq", d: 2, q: "What does a Bode plot show?", o: ["Magnitude and phase against frequency", "The closed-loop poles as a gain is varied", "The output response to a step input", "The relationship between two state variables"], a: 0, why: "It is the open-loop frequency response, which is where phase and gain margin are read off. A root locus is the plot that shows pole movement with gain." },
{ t: "ct-freq", d: 2, q: "What does an integrator look like on a Bode plot?", o: ["Minus 20 dB per decade with 90 degrees of lag", "A flat magnitude with a constant phase shift", "Plus 20 dB per decade with 90 degrees of lead", "A resonant peak at the integrator's frequency"], a: 0, why: "Recognising slopes and phase contributions by eye is most of what makes Bode plots useful. Two integrators give minus 40 dB per decade and 180 degrees of lag, which is already marginal." },
{ t: "ct-freq", d: 2, q: "How is a plant's frequency response measured in practice?", o: ["Inject a swept sine and measure amplitude and phase", "Apply a step and differentiate the response", "Measure the impulse response and then transform it afterwards", "Compare the input and output power spectra"], a: 0, why: "A stepped or swept sine gives an excellent signal to noise ratio at each frequency, at the cost of time. A broadband excitation with an FFT is faster and noisier." },
{ t: "ct-freq", d: 3, q: "Why measure the plant in closed loop for an unstable system?", o: ["It cannot be excited safely in open loop", "Closed-loop measurements have less noise", "The controller's dynamics must be included", "Open-loop measurement needs a special instrument"], a: 0, why: "An unstable plant runs away without feedback, so the measurement has to be taken around the loop and the controller's contribution removed. The correlation the controller introduces is what makes identification harder." },
{ t: "ct-freq", d: 2, q: "What does a resonant peak in the open-loop response threaten?", o: ["It can push the magnitude back above one past minus 180", "It reduces the steady-state accuracy of the loop", "It causes the actuator to saturate at that frequency", "It aliases into the loop at the sample rate"], a: 0, why: "If the peak lifts the gain above unity at a frequency where the phase has already passed minus 180, the loop is unstable. That is why a resonance well below crossover is far safer than one just above." },
{ t: "ct-freq", d: 2, q: "What does the complementary sensitivity function describe?", o: ["How measurement noise reaches the output", "How disturbances at the plant input are rejected", "The plant's response to its own initial conditions", "The controller's gain at the crossover frequency"], a: 0, why: "It is one minus the sensitivity, so pushing one down raises the other. Good tracking and noise rejection therefore cannot both be had in the same band." },
{ t: "ct-freq", d: 2, q: "What is the bandwidth of a closed loop, roughly?", o: ["The frequency where the closed-loop gain falls 3 dB", "The frequency of the plant's fastest pole", "The sample rate divided by twenty", "The frequency at which the phase reaches minus 90"], a: 0, why: "It is close to the open-loop crossover frequency for a well-damped loop, which is why crossover is the number people quote. It sets how fast the loop can respond and reject." },
{ t: "ct-freq", d: 3, q: "Why does adding gain not always increase bandwidth?", o: ["Crossover moves into a region of falling phase", "The plant's poles do not move with gain", "The actuator saturates before the gain takes effect", "The sensor's bandwidth caps the loop's"], a: 0, why: "Bandwidth is limited by where the phase runs out, not by how much gain you apply. Past that point more gain buys oscillation rather than speed." },
{ t: "ct-freq", d: 2, q: "What is the value of a coherence measurement during identification?", o: ["It shows which frequencies the data can be trusted at", "It measures the plant's gain more accurately", "It removes the effect of the controller from the data", "It indicates whether the plant is minimum phase"], a: 0, why: "Low coherence means noise, nonlinearity or another input is involved, so the response at that frequency is not reliable. Fitting a model through low-coherence regions is how bad models get made." },
{ t: "ct-freq", d: 2, q: "Why is a logarithmic frequency axis used?", o: ["Systems behave in decades, and slopes become straight lines", "It compresses the plot to fit on one page", "Phase is only meaningful on a log scale", "The measurement itself is always taken at logarithmic intervals"], a: 0, why: "Poles and zeros contribute constant slopes per decade, so the asymptotic sketch becomes a set of straight lines. That is what makes the plot readable by eye." },

// -------------------------------------------------------------- ct-sysid
{ t: "ct-sysid", d: 2, q: "What does a step response tell you quickly?", o: ["Gain, dominant time constant and any dead time", "The full frequency response of the plant", "The plant's order and every one of its pole locations", "Whether the plant is minimum phase"], a: 0, why: "Three numbers from one experiment are enough for a first-cut PID tuning. It is a narrowband excitation, so it cannot support a high-order model." },
{ t: "ct-sysid", d: 2, q: "Why is a step a poor excitation for a high-order model?", o: ["It excites a narrow band, so extra parameters fit noise", "The step amplitude is always limited by the actuator itself", "Steps cannot be applied to an unstable plant", "The response is too fast to sample adequately"], a: 0, why: "Identification needs the input to be rich enough to distinguish the parameters, and a step is not. The model will fit the data and fail to generalise." },
{ t: "ct-sysid", d: 2, q: "What makes a signal persistently exciting?", o: ["It contains enough distinct frequencies", "It has a large enough amplitude", "It lasts for many time constants", "It is entirely uncorrelated with the output"], a: 0, why: "You need at least as many distinct frequencies as parameters to identify. That is why a single sine, however long you apply it, cannot identify a second-order model." },
{ t: "ct-sysid", d: 3, q: "Why is a PRBS a good identification input?", o: ["Broadband like noise, but repeatable and amplitude-limited", "It has the very highest possible energy for its given amplitude", "It excites only the frequencies you select", "It cannot excite the plant's resonances"], a: 0, why: "Its spectrum is nearly flat over a chosen band, and being deterministic it can be averaged over repeats. The amplitude is bounded, which matters when the actuator has limits." },
{ t: "ct-sysid", d: 2, q: "How should an identified model be validated?", o: ["Against data it has never seen", "By checking the fit on the identification data", "By comparing its order with the physical model", "By confirming it is stable in closed loop"], a: 0, why: "A model with enough parameters will fit anything, including the noise. Cross-validation, ideally at a different operating point, is what shows it generalises." },
{ t: "ct-sysid", d: 2, q: "Why is closed-loop identification harder?", o: ["The controller correlates the input with the disturbance", "The plant simply cannot be excited while the loop is closed", "The measurements are noisier in closed loop", "The controller's own dynamics cannot be removed"], a: 0, why: "Because the input depends on the output, the fit can identify the inverse controller rather than the plant. Injecting an external excitation and using the right method avoids it." },
{ t: "ct-sysid", d: 2, q: "What does a plant's dead time to time constant ratio tell you?", o: ["How hard the loop will be to control", "The sample rate the loop will need", "The order of the model you should fit", "The steady-state gain of the plant"], a: 0, why: "A large ratio severely limits achievable bandwidth, because the delay's phase lag arrives before the loop can act. It is the single most useful number from a step test." },
{ t: "ct-sysid", d: 3, q: "Why does over-fitting show up as poor prediction?", o: ["Extra parameters absorb noise rather than dynamics", "The model becomes numerically ill-conditioned instead", "The optimiser converges to a local minimum", "The model's order exceeds the plant's order"], a: 0, why: "The fit improves monotonically with parameters, so the residual is not a measure of quality. Information criteria, or simply cross-validation, are what choose the order." },
{ t: "ct-sysid", d: 2, q: "What does a nonlinear plant do to a linear identification?", o: ["The model is only valid near the operating point", "The identification will simply fail to converge at all", "The residual will be white but large", "The model order will be overestimated"], a: 0, why: "Linear identification gives a local approximation, which is exactly what a linear controller needs. Identifying at several operating points is how gain scheduling is designed." },
{ t: "ct-sysid", d: 2, q: "Why record the excitation amplitude used during identification?", o: ["A nonlinear plant gives a different model at each level", "The model must be scaled by it afterwards", "It determines the sample rate required", "The controller's own gains all depend upon it quite directly"], a: 0, why: "Friction and saturation make the apparent gain amplitude dependent, so a model identified with small signals may not describe large ones. Recording it makes the model's domain of validity explicit." },

// ----------------------------------------------------------------- ct-ff
{ t: "ct-ff", d: 1, q: "What is feedforward good at that feedback is not?", o: ["Acting before the error appears", "Correcting for an unmodelled disturbance", "Removing steady-state error completely", "Guaranteeing stability of the loop"], a: 0, why: "It uses knowledge of the command or a measured disturbance to act in advance. It cannot correct what it does not know about, which is precisely what feedback is for." },
{ t: "ct-ff", d: 2, q: "Why can feedforward not destabilise a loop?", o: ["It is outside the feedback path", "Its gain is always less than one", "It acts only during transients", "It is applied to the setpoint, not the plant"], a: 0, why: "There is no loop through it, so errors in the feedforward model degrade tracking without affecting stability. That makes it a low-risk place to put model knowledge." },
{ t: "ct-ff", d: 2, q: "What does a persistent feedback effort alongside feedforward indicate?", o: ["The feedforward model is systematically wrong", "The disturbance is simply much larger than expected", "The sensor noise is too high", "The loop bandwidth is set too low"], a: 0, why: "If the feedforward were right, the feedback would only handle the residual and would average to nothing. A steady contribution means feedback is quietly making up the difference." },
{ t: "ct-ff", d: 3, q: "Why is inverting the plant for feedforward often impractical?", o: ["The inverse is usually improper or unstable", "The plant model is never accurate enough", "It requires measuring every state", "The inverse cannot be computed in real time"], a: 0, why: "A plant with more poles than zeros has an improper inverse, and a non-minimum-phase zero gives an unstable one. A filtered or approximate inverse is what is used in practice." },
{ t: "ct-ff", d: 2, q: "What can be fed forward in a temperature control loop?", o: ["A measured change in ambient or in load", "The integral of the temperature error", "The derivative of the setpoint only", "The heater's own resistance"], a: 0, why: "Any disturbance you can measure before it affects the output is a candidate. Ambient temperature and a known load change are the classic examples." },
{ t: "ct-ff", d: 2, q: "Why filter a feedforward command?", o: ["A raw derivative would be impulsive and saturate", "The command would otherwise be delayed", "Filtering improves the model's accuracy", "It prevents the feedback from responding to it at all"], a: 0, why: "Differentiating a step command produces an impulse that saturates the actuator and excites resonances. Shaping the command first is a better answer than filtering afterwards." },
{ t: "ct-ff", d: 2, q: "What is the two-degree-of-freedom structure for?", o: ["Tuning command response and disturbance rejection separately", "Controlling two entirely separate axes with one controller", "Using two sensors on the same plant", "Switching between two controllers safely"], a: 0, why: "A single PID couples the two, so making tracking crisp also makes disturbance response twitchy. Separating the paths lets each be tuned for its job." },
{ t: "ct-ff", d: 3, q: "Why does feedforward help most on a plant with significant delay?", o: ["Feedback cannot react until the delay has elapsed", "The delay reduces the feedback gain that is available", "Feedforward removes the delay from the loop", "The delay makes the plant non-minimum phase"], a: 0, why: "Feedback is inherently reactive and the delay bounds how fast it can be. Acting on the command before the plant responds sidesteps that limit entirely." },
{ t: "ct-ff", d: 2, q: "What does gravity compensation on a robot arm amount to?", o: ["Feedforward of a torque computed from the pose", "An integrator with a very long time constant", "A bias added to the encoder reading", "A reduction in the proportional gain when lifting"], a: 0, why: "The holding torque is a known function of the joint angles, so it can be supplied directly rather than generated by an error. The feedback gains can then be tuned for dynamics rather than for holding." },
{ t: "ct-ff", d: 2, q: "What limits how much feedforward can help?", o: ["The accuracy of the model it is based on", "The bandwidth of the feedback controller", "The resolution of the actuator command", "The sample rate of the control loop"], a: 0, why: "Feedforward is open loop, so its benefit is exactly as good as the model. That is why it is paired with feedback rather than used alone." },

// ---------------------------------------------------------------- ct-lqr
{ t: "ct-lqr", d: 2, q: "What does an LQR design minimise?", o: ["A weighted sum of state error and control effort", "The settling time of the closed-loop response", "The peak overshoot for a step input", "The sensitivity to plant parameter changes"], a: 0, why: "The Q and R matrices encode how much you care about deviation versus effort. The solution turns out to be constant-gain state feedback, computable offline." },
{ t: "ct-lqr", d: 2, q: "What does increasing R relative to Q give you?", o: ["A more conservative controller using less effort", "A rather faster response with a good deal more overshoot", "Better rejection of measurement noise", "A higher closed-loop bandwidth"], a: 0, why: "Penalising the input more heavily makes the optimiser spend less of it, so the response is gentler. It is the single most intuitive knob in the design." },
{ t: "ct-lqr", d: 2, q: "What does LQR require that PID does not?", o: ["A state-space model and access to the states", "A plant that is stable in open loop", "A sample rate somewhere above the Nyquist limit", "A measurement of the disturbance"], a: 0, why: "It is a full state feedback method, so an observer is needed where states are not measured. That extra machinery is what buys the systematic multi-input handling." },
{ t: "ct-lqr", d: 3, q: "What is the appeal of LQR being solvable offline?", o: ["The gain is constant, so runtime cost is trivial", "It guarantees the very fastest possible response there is", "It removes the need for any tuning", "The design cannot become unstable"], a: 0, why: "Solving the Riccati equation once gives a fixed gain matrix, so the controller is a matrix multiply. MPC, by contrast, solves an optimisation every sample." },
{ t: "ct-lqr", d: 2, q: "How do you add integral action to an LQR design?", o: ["Augment the state with the integral of the error", "Add an integrator in series after the controller", "Increase the Q weighting on the output state", "Apply a feedforward term equal to the setpoint"], a: 0, why: "Including the integral as an extra state lets the design weight it like any other. Bolting an integrator on afterwards is not part of the optimisation and can spoil the margins." },
{ t: "ct-lqr", d: 2, q: "What does LQG add to LQR?", o: ["A Kalman filter to estimate the states", "An integral term for steady-state accuracy", "Constraint handling on the inputs", "Robustness to unmodelled dynamics"], a: 0, why: "It is LQR plus an optimal observer, joined by the separation principle. Notably it does not inherit LQR's famous robustness margins, which is why loop transfer recovery exists." },
{ t: "ct-lqr", d: 2, q: "How are Q and R usually chosen in practice?", o: ["By iteration, starting from the inverse squared maxima", "Analytically, direct from the plant's own transfer function", "By measuring the disturbance covariances", "From the desired closed-loop pole locations"], a: 0, why: "Bryson's rule, using the reciprocal of the square of each acceptable maximum, gives a sane starting point. From there it is iteration against simulated responses." },
{ t: "ct-lqr", d: 3, q: "Why is LQR not automatically robust once an observer is added?", o: ["The observer's dynamics change the loop transfer function", "The observer introduces a delay in the feedback", "The Kalman gain is computed from a different set of weights", "The separation principle does not hold for gains"], a: 0, why: "State feedback alone has guaranteed margins, and inserting an estimator between the plant and the gain destroys that guarantee. Loop transfer recovery deliberately detunes the observer to get some of it back." },
{ t: "ct-lqr", d: 2, q: "What does the Q matrix weight?", o: ["Deviation of each state from its target", "The magnitude of each control input", "The measurement noise on each sensor", "The uncertainty in each model parameter"], a: 0, why: "It is the penalty on state error, and its diagonal entries let you say which states matter. R is the corresponding penalty on effort." },
{ t: "ct-lqr", d: 2, q: "Why is LQR attractive for a multi-input plant?", o: ["It coordinates the inputs systematically", "It requires fewer measurements than PID", "It handles nonlinearity automatically", "It needs no model of the plant"], a: 0, why: "Tuning several interacting PID loops by hand is genuinely hard, and the optimisation does the coordination for you. That is the practical reason it appears in aerospace and robotics." },

// ------------------------------------------------------------ ct-nonlinear
{ t: "ct-nonlinear", d: 2, q: "When is linearisation about an operating point valid?", o: ["While excursions stay small enough", "Whenever the plant has no discontinuities", "Only for electrical systems", "Provided the sample rate is high enough"], a: 0, why: "The neglected higher-order terms must remain negligible over the range you actually operate in. Checking the excursion against that assumption is part of the design, not an afterthought." },
{ t: "ct-nonlinear", d: 2, q: "What is a describing function?", o: ["A nonlinearity's gain to the fundamental of a sinusoid", "The plant's transfer function at one operating point", "The relationship between input and output amplitude", "A polynomial approximation to a nonlinear element"], a: 0, why: "It gives an amplitude-dependent gain that can be used in a Nyquist-style analysis to predict limit cycles. It assumes the rest of the loop filters the harmonics, which is usually reasonable." },
{ t: "ct-nonlinear", d: 2, q: "What is stiction and how does it differ from Coulomb friction?", o: ["Stiction is the higher force needed to start moving", "Stiction acts only at high velocity", "Coulomb friction only occurs at rest", "They are the very same effect, simply measured differently"], a: 0, why: "Once moving, Coulomb friction is a roughly constant opposing force. The step down from stiction to Coulomb is what makes low-speed motion jerky." },
{ t: "ct-nonlinear", d: 3, q: "Why does stiction with integral action cause a slow oscillation?", o: ["The integrator winds up until it breaks free, then overshoots", "The derivative term amplifies the friction step", "The proportional gain is simply far too low at any low velocity", "The friction changes sign at zero velocity"], a: 0, why: "The axis sticks, the error persists, the integrator grows, the axis breaks free and overshoots, and the cycle repeats. It is a classic hunting behaviour and is why dither or a friction feedforward is used." },
{ t: "ct-nonlinear", d: 2, q: "What does a deadband in the actuator cause?", o: ["Small commands produce no motion at all", "The actuator saturates at a lower level", "The loop gain rises near zero error", "The response becomes faster for small errors"], a: 0, why: "The loop cannot correct errors smaller than the deadband, so it settles to a range rather than a point. Compensating by adding the deadband width to the command is the usual fix." },
{ t: "ct-nonlinear", d: 2, q: "What does actuator saturation do to a loop's effective gain?", o: ["It reduces it, since the output stops responding", "It increases it, because the output is at maximum", "It leaves it unchanged but adds a delay", "It makes the loop gain frequency dependent"], a: 0, why: "Beyond the limit an increase in demand produces no increase in output, so the incremental gain falls to zero. Combined with integral action, that is exactly the windup mechanism." },
{ t: "ct-nonlinear", d: 2, q: "What is sliding mode control's characteristic behaviour?", o: ["Switching rapidly to hold the state on a surface", "Smoothly interpolating between two controllers", "Adapting its gains to the measured plant", "Predicting the future state and optimising"], a: 0, why: "It is very robust to matched uncertainty, and the switching produces chatter that can excite unmodelled dynamics. Boundary-layer smoothing trades some robustness for less chatter." },
{ t: "ct-nonlinear", d: 3, q: "Why is a limit cycle not always a stability failure?", o: ["A small bounded oscillation may be acceptable", "Limit cycles decay to zero eventually", "They only occur in simulation, not hardware", "They indicate the loop gain is too low"], a: 0, why: "A bounded oscillation is not divergence, and a few least significant bits of hunting may be entirely tolerable. Whether it matters is a specification question, not a stability one." },
{ t: "ct-nonlinear", d: 2, q: "What does feedback linearisation do?", o: ["Cancels the nonlinearity using a model of it", "Linearises the plant about several operating points", "Replaces the nonlinear plant with a linear one", "Restricts the input so the plant stays linear"], a: 0, why: "An inner loop inverts the known nonlinearity so an outer linear controller sees a linear plant. It depends entirely on the model being right, which is its weakness." },
{ t: "ct-nonlinear", d: 2, q: "Why does a nonlinear plant break the superposition assumption?", o: ["Responses to two inputs do not add", "The plant's gain changes with frequency", "The output depends on past inputs", "The plant has more than one input"], a: 0, why: "Superposition is what makes transfer functions and frequency response meaningful at all. Without it, a single Bode plot cannot describe the system." },

// ------------------------------------------------------------ ct-cascade
{ t: "ct-cascade", d: 1, q: "What is the point of a cascaded loop?", o: ["An inner fast loop rejects disturbances before they propagate", "It reduces the number of sensors required", "It allows two entirely separate controllers to share one actuator", "It removes the need for an integrator"], a: 0, why: "The inner current or velocity loop sees and rejects a disturbance long before it integrates into a position error. That is why motion controllers are almost always cascaded." },
{ t: "ct-cascade", d: 2, q: "In what order should cascaded loops be tuned?", o: ["Innermost first: current, then velocity, then position", "Outermost first, then work inward", "All of them simultaneously, using one single optimisation", "Velocity first, then the others together"], a: 0, why: "Each outer loop sees the closed inner loop as its plant, so the inner one must be settled first. Tuning outward is a reliable procedure; tuning inward is not." },
{ t: "ct-cascade", d: 2, q: "How much faster should the inner loop be?", o: ["Roughly a factor of three to ten", "Exactly twice as fast", "At least a hundred times faster", "The same speed, so they track together"], a: 0, why: "Enough separation that the outer loop sees the inner as nearly instantaneous, without needing an impractical bandwidth. Below about three the inner dynamics erode the outer loop's phase margin." },
{ t: "ct-cascade", d: 2, q: "What does an inner loop do for the outer loop's plant model?", o: ["It linearises and standardises what the outer loop sees", "It removes the need for a model altogether", "It adds an integrator to the outer plant", "It simply doubles the outer loop's own achievable bandwidth"], a: 0, why: "Motor constant variation, supply voltage and friction are all absorbed inside the current loop. The outer loop then sees something much closer to its nominal model." },
{ t: "ct-cascade", d: 3, q: "What goes wrong if the inner loop is too slow?", o: ["Its dynamics appear as lag inside the outer loop", "The inner loop saturates before the outer responds", "The outer loop's integrator winds up permanently", "The two loops fight for the same actuator"], a: 0, why: "The inner loop's phase lag is inside the outer loop's path and erodes its margin. That is why the answer to a marginal outer loop is often to speed up the inner one." },
{ t: "ct-cascade", d: 2, q: "What should the inner loop do when the outer loop saturates?", o: ["Stop integrating, since its commands cannot be followed", "Increase its own output still further to compensate for it", "Switch to a feedforward-only mode", "Reduce its gain until saturation clears"], a: 0, why: "Anti-windup has to be coordinated across the cascade, or the outer integrator keeps growing against a limit it cannot influence. Back-calculating from the actual actuator output is the general approach." },
{ t: "ct-cascade", d: 2, q: "What does the inner loop need in the way of a sensor?", o: ["An intermediate measurement such as current or velocity", "A second position sensor with higher resolution", "No sensor, since it is driven by the outer loop", "The same sensor as the outer loop uses, just sampled faster"], a: 0, why: "The whole structure depends on measuring something between the actuator and the final output. Without that measurement there is no inner loop to close." },
{ t: "ct-cascade", d: 3, q: "Why is a current loop closed in hardware or at very high rate?", o: ["Electrical dynamics are much faster than mechanical", "The current sensor is noisier than the position sensor", "It reduces the load on the main processor", "The current loop needs no tuning"], a: 0, why: "The winding's electrical time constant is orders of magnitude below the mechanical one, so the loop has to run correspondingly faster. That is why it often lives in a dedicated peripheral or in fabric." },
{ t: "ct-cascade", d: 2, q: "What does cascading cost you?", o: ["More sensors, more tuning and more complexity", "Bandwidth in the outer loop", "The ability to use feedforward", "Some steady-state accuracy right at the final output"], a: 0, why: "Each loop needs its own measurement and its own tuning, and the interaction has to be understood. For a simple plant a single loop is often the better engineering answer." },
{ t: "ct-cascade", d: 2, q: "What does the outer loop's output become?", o: ["The setpoint for the inner loop", "A direct command to the actuator", "A correction added to the inner loop's output", "A gain applied to the inner loop"], a: 0, why: "That is the defining structure: position commands velocity, velocity commands current, current commands voltage. Each layer's output is the next layer's reference." },

// ----------------------------------------------------------- ct-adaptive
{ t: "ct-adaptive", d: 2, q: "What does an adaptive controller change at run time?", o: ["Its own parameters, based on observed behaviour", "The plant's parameters, by physical adjustment", "The setpoint, to keep the plant in range", "The sample rate, to match the dynamics"], a: 0, why: "It estimates something about the plant and retunes itself, which suits a plant whose dynamics genuinely change. It also means the controller's behaviour is no longer fixed at design time." },
{ t: "ct-adaptive", d: 2, q: "What is the difference between direct and indirect adaptive control?", o: ["Direct adapts the gains; indirect identifies the plant first", "Direct uses feedback, whereas indirect uses feedforward instead", "Direct runs online and indirect runs offline", "Indirect needs no model of the plant"], a: 0, why: "Indirect estimates plant parameters and then redesigns the controller from them, so the intermediate model is visible and can be sanity-checked. Direct skips that step." },
{ t: "ct-adaptive", d: 3, q: "Why does adaptation need persistent excitation?", o: ["Without it the estimator cannot distinguish parameter sets", "The adaptation gain would otherwise have to be set to exactly zero", "The plant would not respond to the controller", "The estimator would converge too quickly"], a: 0, why: "If the input is not rich enough, many parameter sets explain the data equally well and the estimate wanders on noise. That drift is the classic failure mode of an adaptive loop left running on a quiet plant." },
{ t: "ct-adaptive", d: 2, q: "What does a leakage or projection term prevent?", o: ["Parameter drift when excitation is absent", "The controller from saturating the actuator", "The estimate converging to the wrong value", "The adaptation from running too quickly"], a: 0, why: "It bounds the parameters so they cannot wander to dangerous values during quiet periods. The cost is a small bias in the converged estimate." },
{ t: "ct-adaptive", d: 2, q: "What is the safe way to deploy an adaptive controller?", o: ["Inside a safety envelope, with a verified fallback", "Only after the plant has been fully identified", "With the adaptation rate set as high as possible", "In open loop, so it cannot destabilise anything"], a: 0, why: "A conventional controller able to take over, plus bounds on the adapted parameters, makes the failure mode survivable. Letting it control directly and simply monitoring is not the same thing." },
{ t: "ct-adaptive", d: 2, q: "Why is a slow adaptation rate usually chosen?", o: ["Fast adaptation interacts with the loop dynamics", "The estimator cannot compute faster", "The sensors cannot be sampled quickly enough", "Slow adaptation converges to a better estimate"], a: 0, why: "The adaptation is itself a feedback loop, and if it is fast enough to interact with the control loop the combination can be unstable. Separating the timescales is the standard assumption." },
{ t: "ct-adaptive", d: 2, q: "What does model reference adaptive control try to achieve?", o: ["Making the plant behave like a chosen reference model", "Identifying the plant's own true parameters quite exactly", "Minimising the control effort for a given error", "Guaranteeing stability under any uncertainty"], a: 0, why: "The adaptation drives the error between the plant and the reference model to zero. What the parameters converge to is secondary and may not be physically meaningful." },
{ t: "ct-adaptive", d: 3, q: "Why is gain scheduling often preferred to true adaptation?", o: ["Every gain set is fixed and testable in advance", "It adapts faster than an estimator can", "It needs no measurement of the operating point", "It cannot become unstable under any conditions"], a: 0, why: "The behaviour is deterministic and can be verified point by point, which matters enormously for certification. Adaptation's behaviour depends on the data it happens to see." },
{ t: "ct-adaptive", d: 2, q: "What should be monitored while an adaptive loop runs?", o: ["The parameter estimates and whether they stay bounded", "Only the tracking error at the output", "The processor's own execution time taken during each cycle", "The setpoint's rate of change"], a: 0, why: "Parameters heading for their bounds is the early warning that excitation has been lost or the plant has changed unexpectedly. Watching only the error hides that until it is too late." },
{ t: "ct-adaptive", d: 2, q: "When is adaptation genuinely worth the complexity?", o: ["When the plant changes more than the margins allow", "Whenever the plant's own model is not precisely known", "When the loop must run at a very high rate", "When several sensors are available"], a: 0, why: "A robust fixed controller handles ordinary uncertainty perfectly well. Adaptation earns its place when the variation is genuinely large, such as a payload changing by an order of magnitude." },

// ------------------------------------------------------------- ct-faults
{ t: "ct-faults", d: 2, q: "What is the practical problem with a frozen sensor reading?", o: ["The value is usually inside the valid range", "The value goes outside the range and is rejected", "The controller detects it as a step disturbance", "The reading becomes noisy rather than constant"], a: 0, why: "A range check cannot see it because nothing is obviously wrong with the number. Checking for a value that has not changed for longer than the physics allows is what catches it." },
{ t: "ct-faults", d: 2, q: "What does a rising steady control effort suggest?", o: ["Something is degrading, such as friction or a blockage", "The sensor has simply failed to some fixed value instead", "The setpoint has been changed recently", "The loop's gains have been retuned"], a: 0, why: "Holding the same output with more effort is a trend, not an event, and it usually precedes a failure. Logging the effort as a health signal turns it into a warning rather than a surprise." },
{ t: "ct-faults", d: 2, q: "What is analytical redundancy?", o: ["Predicting a sensor from a model and other sensors", "Fitting two identical sensors and comparing them", "Storing a redundant copy of the calibration data", "Running the control law twice and comparing"], a: 0, why: "It gives a cross-check without the cost of duplicate hardware, and it can catch faults a duplicate would share. The quality of the check is limited by the quality of the model." },
{ t: "ct-faults", d: 3, q: "Why can two sensors detect a fault but not identify which failed?", o: ["Disagreement says one is wrong, not which", "Two sensors always fail in the same way", "The comparison is not sensitive enough", "One sensor is always designated as primary"], a: 0, why: "You can fail safe on a disagreement but you cannot continue. Three sensors let a majority vote isolate the faulty one, which is why triple redundancy exists." },
{ t: "ct-faults", d: 2, q: "What should a watchdog actually be fed from?", o: ["Evidence that every critical task is making progress", "A hardware timer that simply runs entirely independently", "The main loop, once per iteration", "The highest-priority interrupt handler"], a: 0, why: "Feeding it from a timer keeps it happy while every task is deadlocked, which turns a safety device into a decoration. A supervisor that checks each task's heartbeat is what gives it meaning." },
{ t: "ct-faults", d: 2, q: "What is a limp-home mode?", o: ["A reduced-capability mode that is still useful and safe", "A mode that stops the machine as quickly as possible", "A diagnostic mode used only during servicing", "A mode that ignores all sensor faults"], a: 0, why: "A single sensor loss need not stop the machine if a degraded but safe operation is defined. Designing it deliberately is what avoids a binary choice between full function and a hard stop." },
{ t: "ct-faults", d: 2, q: "What must happen when switching to a backup controller?", o: ["Its internal states are initialised to match the current output", "It is started from zero to avoid inheriting a fault", "The actuator is disabled during the transfer", "The setpoint is ramped slowly across to the new controller's target"], a: 0, why: "Otherwise the output jumps, which is a disturbance at the worst possible moment. It is the same bumpless transfer problem as any mode change." },
{ t: "ct-faults", d: 3, q: "Why should fault detection thresholds be derived from the failure mode?", o: ["A threshold set by feel either misses faults or cries wolf", "The standards require documented thresholds", "The processor simply cannot evaluate any arbitrary thresholds", "Thresholds must match the sensor's resolution"], a: 0, why: "Knowing what you are falling back to defines what has to be detected and how quickly. That, rather than intuition, is what sets the number." },
{ t: "ct-faults", d: 2, q: "What does logging the innovation or residual give you after a failure?", o: ["Evidence of what the estimator saw before it failed", "A direct measurement of the sensor's own noise floor level", "The exact time the fault occurred", "A way to recalibrate the sensor remotely"], a: 0, why: "The residual usually starts misbehaving before the failure becomes obvious, so the log contains the early warning. Enough logged state to replay the decision offline is the general principle." },
{ t: "ct-faults", d: 2, q: "Why test fault handling deliberately rather than waiting for a fault?", o: ["Untested fault paths are usually the least reliable code", "Faults are too rare to occur during development", "The standards require a fault injection report", "It is the only way to measure the detection latency at all"], a: 0, why: "Fault-handling code runs least and is tested least, so it is where the bugs live. Injecting faults on purpose, including disconnecting sensors on a running rig, is what exercises it." },

]);
