// A second pass over every Electronics lesson: ten more questions each.
//
// Topic tags are lesson ids, so topicLesson() resolves them by the byId
// fallback and no TOPIC_LESSON entry is needed.
//
// Option lengths are deliberately mixed: in about three questions in four the
// longest option is a distractor, so the correct answer is longest only about
// a quarter of the time, which is chance for a four-option question.
BANKS["Electronics"] = BANKS["Electronics"].concat([

// --------------------------------------------------------------- frontend
{ t: "frontend", d: 1, q: "What does a transimpedance amplifier convert?", o: ["A current into a proportional voltage", "A voltage into a proportional current, which suits a photodiode", "One voltage into a larger voltage", "An impedance into a measurable resistance"], a: 0, why: "The photodiode is a current source, and the op-amp holds its terminals at a virtual short while the feedback resistor develops the output voltage. The gain is that resistor, in volts per amp." },
{ t: "frontend", d: 2, q: "Why does a transimpedance stage need a capacitor across the feedback resistor?", o: ["To block the DC offset of the photodiode", "To compensate the pole formed with the input capacitance and stop peaking", "To increase the closed-loop gain at DC", "To filter out any of the supply noise reaching the amplifier's own input stage"], a: 1, why: "Diode and input capacitance with the feedback resistor make a pole inside the loop, which erodes phase margin and rings. The feedback capacitor adds a zero that restores it, at the cost of bandwidth." },
{ t: "frontend", d: 2, q: "What dominates the noise of a high-gain transimpedance stage at low frequency?", o: ["The Johnson noise of the feedback resistor", "The op-amp's slew rate limit at the output stage", "The photodiode's junction capacitance", "The supply rejection of the regulator"], a: 0, why: "Resistor thermal noise scales as the square root of R while the signal scales as R, so a larger resistor improves signal to noise. At high frequency the amplifier's voltage noise, multiplied by the noise gain, takes over." },
{ t: "frontend", d: 2, q: "Why is a differential input stage preferred for a long sensor cable?", o: ["It rejects interference common to both wires", "It doubles the available signal amplitude at the analog to digital converter", "It removes the need for any shielding", "It gives a lower input impedance to the source"], a: 0, why: "Pickup appears almost equally on both conductors, and the amplifier responds only to the difference. A twisted pair is what makes the two conductors see the same field." },
{ t: "frontend", d: 3, q: "What sets the common-mode rejection of a discrete three-op-amp instrumentation amplifier?", o: ["The matching of the output stage resistor ratios", "The open-loop gain of the very first amplifier", "The supply voltage headroom available", "The value of the gain-setting resistor"], a: 0, why: "The difference amplifier at the output only rejects common mode as well as its two resistor ratios match. That is why a monolithic part, with laser-trimmed resistors on one die, beats a discrete build." },
{ t: "frontend", d: 2, q: "What does an op-amp's input bias current do in a high-impedance front end?", o: ["It develops an offset across the source resistance", "It limits the maximum output swing available at the load", "It sets the amplifier's slew rate directly", "It determines the input capacitance of the stage"], a: 0, why: "Bias current times source resistance is an input offset voltage that drifts with temperature. Matching the resistance seen by both inputs cancels the common part, and a FET-input part reduces the current itself." },
{ t: "frontend", d: 2, q: "Why does a charge amplifier suit a piezoelectric sensor?", o: ["Its output depends on charge, not on cable capacitance", "It provides the bias voltage the crystal requires to operate", "It converts the crystal's resistance into a voltage", "It eliminates the resonance of the crystal element"], a: 0, why: "A voltage amplifier's gain would depend on the cable capacitance in parallel with the crystal, so the calibration would change with the lead. A charge amplifier holds the input at a virtual earth, so the cable no longer matters." },
{ t: "frontend", d: 3, q: "What is the effect of stray capacitance across a large feedback resistor?", o: ["It sets an unintended upper cutoff frequency", "It raises the DC gain of the stage considerably above design", "It increases the resistor's thermal noise", "It shifts the amplifier's input offset voltage"], a: 0, why: "A few tenths of a picofarad across a megohm is already a pole in the audio band. Guard traces and a physically long resistor keep the stray small enough to be designed around." },
{ t: "frontend", d: 2, q: "Why place the first gain stage as close to the sensor as possible?", o: ["Interference added later is amplified less", "The cable capacitance is reduced by the shorter run", "It lowers the noise of the amplifier itself", "It removes the need for a differential pair"], a: 0, why: "Once the signal is large, pickup downstream is a smaller fraction of it. Nothing later in the chain can improve the signal to noise ratio set at the front." },
{ t: "frontend", d: 2, q: "What does an anti-alias filter have to do before the sampler?", o: ["Attenuate everything above half the sample rate", "Remove the DC component so the converter is not saturated", "Flatten the passband to within one decibel", "Match the impedance of the driving source"], a: 0, why: "Anything above Nyquist folds back into the band and is then indistinguishable from real signal. It has to be analogue, because after sampling the damage cannot be undone." },

// --------------------------------------------------------------- embedded
{ t: "embedded", d: 1, q: "Why is a decoupling capacitor placed close to a supply pin?", o: ["To keep the loop area of the transient current small", "To increase the total capacitance seen by the regulator output", "To filter the analogue signal entering that pin", "To provide a discharge path at power-down"], a: 0, why: "The inductance of the path, not the capacitance, limits how fast charge arrives. A short loop from pin to capacitor to ground plane is what keeps the local rail from sagging on a switching edge." },
{ t: "embedded", d: 2, q: "What does a pull-up resistor on a reset line actually do?", o: ["Holds the line at a defined level when nothing drives it", "Limits the current the reset controller can sink to a safe value", "Speeds up the falling edge of the reset pulse", "Prevents the reset line from being driven low at all"], a: 0, why: "An undriven CMOS input floats and can pick up enough noise to toggle. The resistor defines the idle state and still allows an open-drain source to pull it down." },
{ t: "embedded", d: 2, q: "Why does a microcontroller need a separate analogue supply pin?", o: ["To keep digital switching noise out of the converter reference", "Because the analogue section needs a higher voltage to work", "To allow the analogue block to be powered down alone", "Because the two sections use different logic families"], a: 0, why: "The converter measures against its supply and reference, so noise there appears directly in the result. A ferrite and its own decoupling let the analogue rail stay quiet while the core switches." },
{ t: "embedded", d: 2, q: "What is the purpose of a series resistor on a fast digital output?", o: ["To damp the ringing by matching the trace impedance", "To limit the steady-state current the pin has to supply", "To protect the pin from an accidental short circuit", "To slow the internal logic of the output driver"], a: 0, why: "The driver's output impedance is usually well below the trace's, so the edge reflects. A resistor that brings the total up to roughly the line impedance absorbs the reflection and cuts the radiated emission." },
{ t: "embedded", d: 3, q: "Why can a floating unused input pin raise a device's current consumption?", o: ["The input sits near the switching threshold and both transistors conduct", "The pin's own protection diodes leak continuously into the main supply rail", "An undriven pin oscillates and clocks the internal logic", "The input buffer defaults to its highest drive strength"], a: 0, why: "A CMOS input near midway leaves both the pull-up and pull-down partly on, so current flows straight through. Tying the pin, or configuring it as an output, closes that path." },
{ t: "embedded", d: 2, q: "What does a bulk capacitor do that a small ceramic near the pin cannot?", o: ["Supply charge over a longer, lower-frequency transient", "Present a lower impedance at the highest frequencies", "Reduce the inductance of the supply path", "Filter noise coupled onto the ground plane"], a: 0, why: "The ceramic handles the fast edge because it has low inductance, and the bulk part carries the slower demand because it holds far more charge. Neither substitutes for the other." },
{ t: "embedded", d: 2, q: "Why is a crystal placed close to its microcontroller pins?", o: ["To keep the sensitive high-impedance nodes short", "Because the crystal needs the shortest possible thermal path", "To reduce the load capacitance the crystal sees", "To let the oscillator start at a lower supply voltage"], a: 0, why: "The oscillator nodes are high impedance and low amplitude, so a long trace both picks up noise and adds stray capacitance that shifts the frequency. A guard ring and a local ground pour help further." },
{ t: "embedded", d: 2, q: "What is the risk of powering a 3.3 V part from a 5 V signal source?", o: ["Current flows through the protection diode into the rail", "The signal is simply clipped at the lower supply voltage", "The input threshold moves and the level is misread", "The pin's input capacitance rises with the voltage"], a: 0, why: "The clamp diode conducts into the 3.3 V rail and can hold the part partly powered or exceed the diode's rating. A level shifter, or a divider with a series resistor, is the fix." },
{ t: "embedded", d: 3, q: "Why does a brownout detector matter even when the supply looks clean?", o: ["A slow rail collapse can leave the core running on invalid data", "It prevents the regulator from oscillating when it is at a low load", "It resets the device whenever the clock stops", "It protects the flash from over-voltage during writes"], a: 0, why: "Below the guaranteed operating voltage, the core may execute wrongly and corrupt flash or EEPROM before it stops. The detector forces a clean reset before that window opens." },
{ t: "embedded", d: 2, q: "What does a watchdog fed from a hardware timer fail to catch?", o: ["A deadlock in the application while the timer still runs", "A complete loss of the main system clock source", "A supply voltage dropping below the operating range", "An infinite loop inside an interrupt service routine"], a: 0, why: "If the feed does not depend on the tasks making progress, the watchdog is satisfied while the application is stuck. Feeding it only from a supervisor that checks each task's heartbeat is what gives it meaning." },

// ----------------------------------------------------------------- el-adc
{ t: "el-adc", d: 1, q: "What does an ADC's resolution actually tell you?", o: ["How many codes span the full-scale input range", "How accurately the converter tracks the true input voltage", "The smallest change the converter can detect reliably", "How fast the converter can complete a conversion"], a: 0, why: "It is the code count and nothing more. Accuracy comes from linearity, offset, gain and noise, which is why a 24-bit part may have only 20 noise-free bits." },
{ t: "el-adc", d: 2, q: "What is the effective number of bits of a converter?", o: ["The resolution implied by its measured signal to noise ratio", "The number of bits that never change during a conversion", "The width of the output register minus the sign bit", "The count of bits guaranteed monotonic by the datasheet"], a: 0, why: "It is derived from the measured SINAD, so it folds noise and distortion into one figure. It is the number to compare across parts, because the register width is free to be optimistic." },
{ t: "el-adc", d: 2, q: "Why does a successive-approximation ADC want a low source impedance?", o: ["Its sampling capacitor must charge fully within the acquisition window", "Because its own internal reference is derived from the input source itself", "A high impedance would overheat the input protection diodes", "The converter's linearity depends on the source resistance"], a: 0, why: "Each conversion connects a capacitor to the input, and it must settle to well within half a least significant bit. A buffer, or a small capacitor at the pin to supply the charge, solves it." },
{ t: "el-adc", d: 3, q: "What does oversampling and averaging buy you, and at what cost?", o: ["Roughly one extra bit per fourfold rate increase, costing bandwidth", "A complete removal of quantisation error, costing only time", "Better linearity across the whole transfer function, costing power", "Immunity to reference drift, costing extra memory for the samples"], a: 0, why: "Averaging N samples reduces uncorrelated noise as the square root of N, which is half a bit per doubling. It does nothing for a systematic error such as integral nonlinearity." },
{ t: "el-adc", d: 2, q: "Why is dither sometimes added deliberately before a converter?", o: ["It decorrelates the quantisation error from the signal", "It increases the amplitude so the converter is fully loaded", "It compensates the converter's differential nonlinearity", "It shifts the signal away from the reference voltage"], a: 0, why: "Without it, quantisation on a small periodic signal produces harmonics rather than a noise floor. A little noise turns those tones into broadband noise you can then average away." },
{ t: "el-adc", d: 2, q: "What is the main advantage of a delta-sigma converter?", o: ["Very high resolution at low bandwidth, with noise shaped away", "A conversion latency of exactly one clock cycle in every mode", "The ability to sample many channels through one multiplexer", "Operation without any anti-alias filtering at the input"], a: 0, why: "It trades speed for resolution by oversampling heavily and pushing quantisation noise out of band, where a digital filter removes it. Its latency and its settling after a channel change are the costs." },
{ t: "el-adc", d: 3, q: "Why does the reference voltage deserve as much care as the signal path?", o: ["The conversion is a ratio, so reference noise appears in the result", "The reference sets the converter's maximum sampling rate", "A noisy reference raises the converter's own overall power consumption", "The reference determines the input impedance of the part"], a: 0, why: "The code is the input divided by the reference, so a one part in ten thousand wobble on the reference is a one part in ten thousand error. It needs its own decoupling and often its own buffer." },
{ t: "el-adc", d: 2, q: "What does differential nonlinearity of more than one least significant bit imply?", o: ["A code may be missing entirely from the transfer function", "The converter's gain error exceeds its specified limit", "The full-scale range is smaller than the datasheet states", "The converter cannot settle within its acquisition time"], a: 0, why: "DNL is the deviation of each step from its ideal width, so a step wider than two bits means a code that never appears. Monotonicity is the weaker guarantee that the output never goes backwards." },
{ t: "el-adc", d: 2, q: "Why can multiplexing several channels into one converter cause crosstalk?", o: ["The sampling capacitor retains charge from the previous channel", "The multiplexer adds a gain error that cannot be calibrated out", "Each channel sees a different reference voltage in turn", "The converter's linearity changes with the selected channel"], a: 0, why: "Insufficient acquisition time after the switch leaves residue from the last input. Allowing full settling, or converting a dummy sample after switching, removes it." },
{ t: "el-adc", d: 2, q: "What is aperture jitter and when does it matter?", o: ["Variation in sampling instant, which matters on fast-slewing inputs", "Variation in the converter's gain between successive conversions", "Uncertainty in the reference voltage during the hold phase", "Drift in the acquisition time as the part warms up"], a: 0, why: "On a rapidly changing signal, an uncertain sampling instant becomes an amplitude error, so the achievable signal to noise ratio is capped by the jitter and the input frequency. At DC it does not matter at all." },

// --------------------------------------------------------------- el-noise
{ t: "el-noise", d: 1, q: "What is Johnson noise proportional to?", o: ["The resistance, the bandwidth and the absolute temperature", "The current flowing through the resistor at the time", "The voltage across the resistor and its power rating", "The resistor's tolerance and its physical package size"], a: 0, why: "It is thermal agitation of the carriers, so it exists in an ideal resistor carrying no current at all. Halving the bandwidth cuts the noise voltage by root two." },
{ t: "el-noise", d: 2, q: "What distinguishes shot noise from thermal noise?", o: ["Shot noise needs a current flowing across a barrier", "Shot noise depends on temperature and thermal noise does not", "Shot noise is only present in resistive elements", "Shot noise falls as the square of frequency"], a: 0, why: "It comes from the discreteness of charge crossing a junction, so it scales as the square root of the current. A resistor at equilibrium has thermal noise but no shot noise." },
{ t: "el-noise", d: 2, q: "Why is 1/f noise a problem for a DC measurement?", o: ["Its power rises as the measurement time gets longer", "It is entirely removed by any averaging you apply", "It only appears above the amplifier's cutoff frequency", "It scales with the square of the supply voltage"], a: 0, why: "Averaging for longer moves you into the region where flicker noise dominates, so the result stops improving. Chopping or auto-zeroing modulates the signal above the flicker corner and brings the noise back down." },
{ t: "el-noise", d: 3, q: "What does an amplifier's noise figure describe?", o: ["How much the stage degrades the signal to noise ratio", "The total noise voltage referred to the amplifier's output", "The ratio of the amplifier's noise to its own gain", "The bandwidth over which the noise is specified"], a: 0, why: "It compares the output signal to noise ratio with the input's, in decibels. A perfect amplifier has a noise figure of zero, and the first stage dominates the chain's total." },
{ t: "el-noise", d: 2, q: "Why does the first stage dominate a chain's noise?", o: ["Later stages amplify its noise along with the signal", "Later stages are always designed with lower gain", "The first stage runs at the highest current", "Noise adds linearly, so the first term is largest"], a: 0, why: "Friis' formula divides each later stage's noise contribution by the gain ahead of it. That is why a low-noise preamplifier close to the sensor is worth more than anything downstream." },
{ t: "el-noise", d: 2, q: "How do two independent noise sources combine?", o: ["As the square root of the sum of their squares", "By simple addition of their peak-to-peak voltages", "By taking whichever of the two happens to be larger", "As the product of their individual power spectral densities"], a: 0, why: "Uncorrelated sources add in power, so the voltages add in quadrature. That is why a source ten decibels below another contributes only about half a decibel to the total." },
{ t: "el-noise", d: 2, q: "What does a ground loop actually cause?", o: ["Current in the ground path develops a voltage between references", "The circuit's ground potential rises above the supply voltage", "The return current takes a longer path than intended", "The shield is left floating at one end of the cable"], a: 0, why: "Two earthing points at different potentials drive current through the ground conductor, and its impedance turns that into a difference between the two circuits' references. Breaking the loop, or making the connection differential, removes it." },
{ t: "el-noise", d: 3, q: "Why does a shield need to be grounded at one end only for low-frequency signals?", o: ["Grounding both ends creates a loop that carries current", "A single ground gives the shield a lower total impedance", "Two grounds would short the signal to the chassis", "The shield only works when it is left floating at the source"], a: 0, why: "Two grounds close a loop, and the current in it couples straight back into the signal. At radio frequencies the choice reverses, because the shield needs to be an equipotential over its length." },
{ t: "el-noise", d: 2, q: "What is the practical way to find whether noise is conducted or radiated?", o: ["Change the cable routing and see whether the noise follows", "Increase the gain and see whether the noise grows with it", "Measure the noise with the supply disconnected entirely", "Compare the noise floor against the amplifier's datasheet"], a: 0, why: "Moving, shortening or re-routing the cable changes the coupling if it is radiated and leaves it alone if it is conducted. It is a five-minute test that saves a day of guessing." },
{ t: "el-noise", d: 2, q: "Why does narrowing the measurement bandwidth improve signal to noise ratio?", o: ["Noise power scales with bandwidth while the signal does not", "A narrower filter has a much lower insertion loss overall too", "The amplifier's gain rises as the bandwidth falls", "Narrow filters remove the quantisation noise as well"], a: 0, why: "Broadband noise is spread over frequency, so halving the bandwidth halves its power while a narrowband signal is untouched. A lock-in amplifier is that idea taken to its limit." },

// --------------------------------------------------------------- el-power
{ t: "el-power", d: 1, q: "What is the fundamental efficiency limit of a linear regulator?", o: ["Output voltage divided by input voltage", "The ratio of the load current to the quiescent current", "Roughly ninety percent, set by the pass transistor", "It depends only on the load, not on the voltages"], a: 0, why: "The pass element drops the difference at the full load current, so that power becomes heat. Dropping five volts to three at one amp wastes two watts however good the part is." },
{ t: "el-power", d: 2, q: "Why does a buck converter need a minimum load in some designs?", o: ["To keep it out of discontinuous mode where regulation degrades", "Because the inductor saturates when the current is too small", "To prevent the output capacitor from discharging completely", "Because the feedback divider needs a current to function"], a: 0, why: "At light load the inductor current reaches zero each cycle, and the control loop behaves differently. Modern parts handle this with pulse skipping, at the cost of a larger ripple." },
{ t: "el-power", d: 2, q: "What does the low ESR of a ceramic output capacitor cost you?", o: ["Loop stability, since some controllers need the ESR zero", "Ripple performance, because ESR normally reduces the ripple", "Transient response, which depends on a higher ESR", "Lifetime, because ceramics degrade faster than electrolytics"], a: 0, why: "Older voltage-mode controllers rely on the zero the ESR forms to get phase margin. Replacing an electrolytic with a ceramic can turn a stable supply into an oscillator." },
{ t: "el-power", d: 3, q: "Which loop should be kept smallest in a buck converter layout?", o: ["Input capacitor, high-side switch and low-side device", "The inductor, the output capacitor and then the load itself", "Feedback divider back to the control pin", "Bootstrap capacitor and the gate drive return"], a: 0, why: "That loop carries the fast switched current, so its area sets the radiated emission and the switch-node overshoot. The output loop carries a much smoother current and matters far less." },
{ t: "el-power", d: 2, q: "Why does an inductor's saturation current matter more than its rating in amps?", o: ["Above it the inductance collapses and current runs away", "It sets the maximum steady temperature the part can reach", "It determines the converter's switching frequency directly", "It fixes the minimum load the converter can regulate at"], a: 0, why: "The RMS rating is a thermal limit, while saturation is a magnetic one. Past saturation the inductance falls, so the current ramps far faster and the switch can fail within a cycle." },
{ t: "el-power", d: 2, q: "What is the point of a soft-start on a power supply?", o: ["It limits inrush by ramping the output slowly", "It delays the supply until the input has stabilised fully", "It reduces the switching noise during normal operation", "It protects the output capacitor from reverse voltage"], a: 0, why: "Charging a large output capacitance at full current draws an enormous surge that can weld connector contacts and drag down the source. Ramping the reference spreads that charge over time." },
{ t: "el-power", d: 3, q: "Why can a bench supply misbehave when driving a motor that decelerates?", o: ["The motor returns energy and the supply cannot sink current", "The motor's inductance oscillates with the supply's output capacitor", "The supply's current limit trips on the reduced load", "The motor's back-EMF exceeds the supply's input voltage"], a: 0, why: "Regenerated energy has nowhere to go, so the bus capacitance charges and the voltage rises. A brake resistor, or a supply that can sink, is what absorbs it." },
{ t: "el-power", d: 2, q: "What does a low-dropout regulator's dropout voltage specify?", o: ["The minimum input-to-output difference for regulation", "The voltage lost across the output capacitor at full load", "How far the output may sag during a load transient", "The difference between the reference and the output"], a: 0, why: "Below that difference the pass device is fully on and the output simply follows the input. It rises with load current, which is what catches people out at the end of a battery discharge." },
{ t: "el-power", d: 2, q: "Why is power sequencing between rails sometimes mandatory?", o: ["An I/O rail up before the core can forward-bias internal diodes", "The regulators would otherwise oscillate against each other", "The rails share a common feedback divider network", "Later rails need the earlier ones to provide their reference"], a: 0, why: "Many devices specify that the core must not lag the I/O rail, or current flows through the substrate and can latch the part up. The datasheet's sequencing section is not advisory." },
{ t: "el-power", d: 2, q: "What does measuring supply ripple with a long ground lead show you?", o: ["Mostly the loop the probe lead itself is picking up", "The true ripple, since the lead has negligible impedance", "Only the low-frequency component of the ripple", "An attenuated version of the actual waveform"], a: 0, why: "The lead and the loop it forms pick up the switching field, so you measure the probe rather than the rail. A spring ground tip, or a probe soldered across the capacitor, gives the real answer." },

// ------------------------------------------------------------- el-sensors
{ t: "el-sensors", d: 1, q: "Why is a resistance temperature detector usually driven with a constant current?", o: ["It turns the resistance change directly into a voltage", "Because a constant voltage would overheat the element", "It removes the need for a reference voltage entirely", "Because the element is nonlinear under constant voltage"], a: 0, why: "With a fixed excitation current the voltage is proportional to resistance, so the reading is linear in the element. The current must be small enough that self-heating does not shift the reading." },
{ t: "el-sensors", d: 2, q: "What does a thermocouple actually produce?", o: ["A small voltage set by the temperature difference between its junctions", "A resistance that varies quite predictably with the absolute temperature", "A current proportional to the temperature at the hot junction", "A frequency shift measured against a reference oscillator"], a: 0, why: "It is a difference measurement, so you need to know the cold junction temperature to recover the hot one. That is why a separate sensor at the terminal block accompanies every thermocouple input." },
{ t: "el-sensors", d: 2, q: "Why is a strain gauge normally used in a bridge?", o: ["The bridge cancels the large unstrained resistance", "A bridge provides the excitation the gauge needs to work", "It removes the need for any bonding adhesive", "The bridge linearises the gauge's response to strain"], a: 0, why: "The strained change is a tiny fraction of the gauge resistance, so measuring it directly means finding a part in ten thousand on a large value. The bridge subtracts the bulk and leaves the difference." },
{ t: "el-sensors", d: 3, q: "What does a ratiometric measurement mean for a bridge sensor?", o: ["The same reference excites the bridge and sets the converter's full scale", "The bridge output is divided by the supply before conversion", "Two converters measure each of the two halves of the bridge quite separately", "The measurement is taken as a ratio of two successive samples"], a: 0, why: "Because both the excitation and the converter scale with the same reference, the reference cancels in the ratio. Its absolute accuracy and drift then stop mattering almost entirely." },
{ t: "el-sensors", d: 2, q: "Why does a Hall effect sensor need temperature compensation?", o: ["Its sensitivity and offset both drift with temperature", "The magnetic field itself changes as the part warms", "The supply current rises and shifts the output level", "Its output impedance falls as temperature increases"], a: 0, why: "Both the Hall coefficient and the built-in offset move, so an uncompensated part can drift by several percent. Integrated sensors trim both on chip, which is a large part of what you pay for." },
{ t: "el-sensors", d: 2, q: "What limits how fast a thermistor can follow a temperature change?", o: ["Its thermal mass and the path to the medium being measured", "The electrical bandwidth of the amplifier reading it", "The resolution of the analog to digital converter used", "The self-heating produced by the excitation current"], a: 0, why: "The time constant is thermal, not electrical, so a bead in still air is slow whatever the electronics do. Improving the coupling, or shrinking the mass, is the only real fix." },
{ t: "el-sensors", d: 2, q: "Why does self-heating matter when reading a temperature sensor?", o: ["The excitation power raises the element above the true temperature", "It reduces the sensor's resistance below its usable measurement range", "It causes the sensor's calibration to expire prematurely", "It couples supply noise directly into the measurement"], a: 0, why: "The dissipated power times the thermal resistance to ambient is a fixed offset in the reading. Pulsing the excitation, or reducing it, trades noise against that error." },
{ t: "el-sensors", d: 3, q: "What is the advantage of a sensor with a digital output over an analogue one?", o: ["The signal is immune to pickup along the cable run", "Digital sensors are inherently more accurate than analogue ones", "It removes the need for any calibration of the device", "The output can be read without a clock or protocol"], a: 0, why: "The conversion happens at the sensor, so what travels is a bit pattern that noise cannot subtly bias. It costs you a protocol, a clock, and a latency you have to characterise." },
{ t: "el-sensors", d: 2, q: "Why is a capacitive sensor sensitive to humidity and contamination?", o: ["Both change the dielectric constant between the plates", "They increase the leakage current through the amplifier", "They alter the mechanical spacing of the electrodes", "They shift the excitation frequency of the oscillator"], a: 0, why: "The measurement is of a capacitance, and anything that changes the permittivity in the field changes the reading. Guarding, conformal coating and a differential arrangement all help." },
{ t: "el-sensors", d: 2, q: "What does a sensor's cross-sensitivity specification tell you?", o: ["How much it responds to a quantity you are not measuring", "The spread in sensitivity between units of the same part", "How the sensitivity changes over the operating range", "The coupling between two channels of the same device"], a: 0, why: "A pressure sensor that also responds to temperature has a cross-sensitivity, and unless you measure and correct for it the error looks like signal. It is often the dominant term in a real system." },

// --------------------------------------------------------------- el-buses
{ t: "el-buses", d: 1, q: "Why does I2C need pull-up resistors?", o: ["The devices only pull the line low, never high", "Because the bus is differential and needs a bias point", "To terminate the reflections on a long bus", "To set the logic threshold for each device"], a: 0, why: "Both lines are open-drain, so the resistor provides the rising edge. Its value trades power against rise time, which is what limits the practical bus capacitance." },
{ t: "el-buses", d: 2, q: "What is clock stretching in I2C?", o: ["A slave holding SCL low until it is ready to continue", "The master slowing the clock when the bus is loaded", "A deliberate lengthening of the start condition", "The pull-up resistor slowing the rising edge"], a: 0, why: "It is flow control by the slave, and a master that does not support it will read garbage from a device that needs it. Some hardware peripherals implement it poorly, which is a classic integration problem." },
{ t: "el-buses", d: 2, q: "What does SPI mode describe?", o: ["The clock's idle polarity and which edge samples the data", "The number of data lines the transfer uses", "The maximum clock frequency the slave supports", "Whether the transfer is most or least significant bit first"], a: 0, why: "The two bits are clock polarity and clock phase, giving four combinations. A mismatch usually shows as data shifted by one bit, which is a good clue when debugging." },
{ t: "el-buses", d: 2, q: "Why does CAN use a differential pair with a dominant and recessive state?", o: ["It allows non-destructive arbitration between nodes", "It doubles the data rate compared with a single wire", "It removes the need for termination at the ends", "It lets each node be addressed by its voltage level"], a: 0, why: "A node writing recessive while reading dominant knows it lost and backs off without corrupting the frame. That is why the highest-priority message suffers no delay from a collision." },
{ t: "el-buses", d: 3, q: "What determines CAN's maximum bus length at a given bit rate?", o: ["The signal must reach the far end within one bit time for arbitration", "The total capacitance of the transceivers on the bus", "The total resistance of the twisted pair measured over the whole distance", "The number of nodes sharing the same physical segment"], a: 0, why: "Arbitration needs every node to see the bus state within the same bit, so propagation delay caps the product of rate and length. That is why one megabit is limited to a few tens of metres." },
{ t: "el-buses", d: 2, q: "Why is RS-485 preferred over RS-232 for a long industrial link?", o: ["It is differential and multi-drop, so it tolerates ground shift", "It uses a much higher voltage swing that therefore carries further", "It includes error correction in the physical layer", "It requires no ground connection between the ends"], a: 0, why: "The receiver looks at the difference, so a common-mode offset of several volts between ends does not matter. Single-ended RS-232 fails as soon as the grounds differ." },
{ t: "el-buses", d: 2, q: "What does a UART's baud rate mismatch of two percent typically cause?", o: ["Occasional framing errors as the sampling point drifts", "A complete failure to detect the start bit at all", "Every byte to arrive with its bits reversed", "The line to be held permanently in the break state"], a: 0, why: "The receiver resynchronises on each start bit and then samples at fixed intervals, so error accumulates across the ten bits. Beyond roughly three percent the last bit is sampled in the wrong cell." },
{ t: "el-buses", d: 2, q: "Why does SPI usually outrun I2C by a wide margin?", o: ["Push-pull drivers give fast edges, and there is no addressing overhead", "SPI transfers simply use a good many fewer bits to carry the same payload", "I2C devices are built on a slower process node", "SPI has error checking that allows a higher rate"], a: 0, why: "I2C's open-drain rising edge is set by a resistor and the bus capacitance, and every transfer carries an address and acknowledgements. SPI drives both edges actively and selects with a dedicated pin." },
{ t: "el-buses", d: 3, q: "What is the practical consequence of I2C having no framing or checksum?", o: ["A glitch can leave the bus stuck and go undetected", "Transfers silently fall back to a lower speed", "The master cannot tell how many bytes arrived", "Addresses are assigned dynamically at power-up"], a: 0, why: "A slave interrupted mid-byte may hold SDA low indefinitely, and nothing in the protocol reports it. Recovery means clocking SCL manually until the slave releases, which the driver has to implement." },
{ t: "el-buses", d: 2, q: "Why is bus termination needed on a fast SPI link but not a slow I2C one?", o: ["Fast edges make the trace behave as a transmission line", "SPI carries more current and needs a load resistor", "I2C's pull-ups already act as a termination", "Termination is only required for differential signalling"], a: 0, why: "What matters is the edge rate against the round-trip delay, not the clock frequency. A series resistor at the driver damps the reflection without the DC cost of a parallel termination." },

// --------------------------------------------------------------- el-debug
{ t: "el-debug", d: 1, q: "What is the first measurement to take on a board that does nothing?", o: ["Every supply rail, at the pins of the parts that use them", "The clock frequency measured at the microcontroller's crystal", "The reset line's voltage during and after power-up", "The current drawn from the bench supply on power-up"], a: 0, why: "Almost everything downstream depends on the rails, and measuring at the regulator rather than the load hides drops and opens. Current is a good second check, because it separates a short from an open." },
{ t: "el-debug", d: 2, q: "Why measure a supply rail at the load rather than at the regulator?", o: ["Trace and connector resistance drops voltage under load", "The regulator's output is filtered and hides the ripple", "The load's decoupling makes the reading more stable", "Measurement at the regulator disturbs the feedback loop"], a: 0, why: "Milliohms times an amp is millivolts, and across a connector it can be far more. That is exactly the drop that pushes a part below its brownout threshold under peak demand." },
{ t: "el-debug", d: 2, q: "What does a scope's 10x probe give you over a 1x probe?", o: ["Lower capacitive loading and more bandwidth, at less sensitivity", "A ten times larger displayed signal for exactly the same input level", "Immunity to ground loops through the probe lead", "Automatic compensation for the cable's length"], a: 0, why: "The divider reduces the capacitance the circuit sees, which is what preserves the edge you are trying to look at. You pay ten decibels of sensitivity for it." },
{ t: "el-debug", d: 3, q: "Why does an uncompensated probe distort a square wave?", o: ["Its capacitance and the input capacitance form a mismatched divider", "The probe's own resistance changes with whatever frequency is applied", "The ground lead resonates with the probe's own tip", "The attenuator introduces a fixed delay in the path"], a: 0, why: "The divider must divide equally at DC and at high frequency, and the trimmer is what matches them. Overshoot or a sagging top is the standard picture of getting it wrong." },
{ t: "el-debug", d: 2, q: "What is the value of toggling a spare GPIO inside a routine?", o: ["It shows the routine's real timing on a scope", "It confirms the compiler has not removed the code", "It provides a trigger for the logic analyser only", "It measures the interrupt latency of the processor"], a: 0, why: "Setting the pin on entry and clearing it on exit turns execution time into a pulse width you can watch under realistic load. Watching the widest pulse over a long run is how you find the worst case." },
{ t: "el-debug", d: 2, q: "Why is a logic analyser better than a scope for a protocol problem?", o: ["It captures many lines together and decodes the traffic", "It has a much higher bandwidth available on every channel", "It shows the analogue quality of each edge", "It can inject test patterns onto the bus"], a: 0, why: "Protocol bugs are about the relationship between clock, data and select over many bytes. A scope is what you reach for once you suspect the edges themselves." },
{ t: "el-debug", d: 2, q: "What does an infrared camera tell you about a powered board?", o: ["Where the power is being dissipated, including unintended places", "Which components are outside their voltage ratings", "The exact junction temperature inside every one of the semiconductors", "Whether a solder joint is cracked beneath a package"], a: 0, why: "A short or a part in the wrong orientation shows as a hot spot within seconds. It is the fastest way to find a fault that draws current without any obvious signal." },
{ t: "el-debug", d: 3, q: "Why does an intermittent fault often point at mechanical stress?", o: ["Flexing changes a marginal joint or a hairline crack", "Thermal cycling always shifts a component's value", "Intermittent faults are usually software timing races", "Vibration changes the dielectric constant of the board"], a: 0, why: "Pressing, twisting or heating specific areas while watching the symptom localises it quickly. A joint that is barely wetted, or a crack under a large connector, is the common culprit." },
{ t: "el-debug", d: 2, q: "What is wrong with debugging by changing several things at once?", o: ["You cannot attribute the change to any single cause", "It takes more time than changing one at a time", "The board may not survive that many rework cycles", "The compiler may optimise the changes differently"], a: 0, why: "If it works you do not know why, and if it does not you have added variables. One change and one measurement per iteration is slower per step and far faster overall." },
{ t: "el-debug", d: 2, q: "Why record the conditions when an intermittent fault occurs?", o: ["The pattern often identifies the cause faster than probing", "It satisfies the requirements of the design review process", "It lets you calculate the mean time between failures", "It shows whether the fault is in hardware or firmware"], a: 0, why: "Correlation with temperature, supply, a particular message or time since power-up narrows the search enormously. A fault that only happens after twenty minutes is telling you something specific." },

// ------------------------------------------------------------ el-mosfets
{ t: "el-mosfets", d: 1, q: "What does a MOSFET's Rds(on) determine?", o: ["The conduction loss when the device is fully turned on", "The maximum voltage the device is able to block when off", "The speed at which the device can switch states", "The gate charge needed to turn the device on"], a: 0, why: "Loss is the current squared times that resistance, so it dominates at high current and low switching frequency. It rises substantially with temperature, which is what makes thermal runaway a design concern." },
{ t: "el-mosfets", d: 2, q: "Why does a MOSFET dissipate most of its switching loss during the transition?", o: ["Voltage and current are both large while it crosses the linear region", "The gate driver's current peaks at that moment", "The body diode goes on conducting throughout the whole of the transition", "The device's capacitance discharges into the load"], a: 0, why: "Fully on there is little voltage across it, and fully off little current through it. In between both are substantial, so the loss is the area of that overlap times the switching frequency." },
{ t: "el-mosfets", d: 2, q: "What is the Miller plateau on a gate waveform?", o: ["The flat region where drain-gate capacitance is being charged", "The point at which the gate reaches its threshold voltage", "A voltage regulation artefact of the gate driver", "The interval when the body diode is conducting"], a: 0, why: "While the drain voltage swings, the gate drive current goes into Cgd rather than raising the gate voltage, so the gate stalls. The length of that plateau is what sets the switching time." },
{ t: "el-mosfets", d: 3, q: "Why does a high-side N-channel MOSFET need a bootstrap or isolated supply?", o: ["Its gate must sit above the source, which rises to the rail", "Because the device blocks current in the reverse direction", "To supply the steady current the gate leaks when on", "Because the body diode must be reverse biased first"], a: 0, why: "When the device is on, the source is at the supply rail, so the gate must be driven above it. The bootstrap capacitor is charged while the switch node is low and then rides up with it." },
{ t: "el-mosfets", d: 2, q: "What does a gate resistor trade off?", o: ["Switching loss against ringing and radiated emission", "Conduction loss against the device's temperature rise", "Threshold voltage against the drain leakage current", "Gate charge against the maximum operating frequency"], a: 0, why: "A larger resistor slows the edge, which damps the ringing and cuts the emission but increases the time spent in the lossy transition. It is one of the few genuinely two-sided choices in a converter." },
{ t: "el-mosfets", d: 2, q: "Why do two MOSFETs in parallel share current reasonably well?", o: ["Rds(on) has a positive temperature coefficient", "Their threshold voltages are matched at manufacture", "The gate driver balances the current between them", "The body diodes equalise the current when conducting"], a: 0, why: "The hotter device becomes more resistive and takes less current, which is a stabilising feedback. Bipolar transistors have the opposite behaviour, which is why they need emitter ballast resistors." },
{ t: "el-mosfets", d: 3, q: "What is shoot-through in a half bridge?", o: ["Both devices conducting at once, shorting the supply", "The high-side device turning on before its bootstrap charges", "Current flowing backwards through the body diode", "The load current exceeding the devices' pulsed rating"], a: 0, why: "Even a few tens of nanoseconds of overlap puts the full supply across two on devices. Dead time between turning one off and the other on is the standard defence." },
{ t: "el-mosfets", d: 2, q: "Why is a MOSFET's body diode worth paying attention to in a bridge?", o: ["It conducts during dead time and its recovery causes loss", "It sets the maximum blocking voltage of the device", "It clamps the gate voltage during fast transitions", "It provides the only path for the gate charge to leave"], a: 0, why: "It carries the inductive current while both devices are off, and its reverse recovery charge is dumped when the opposite device turns on. Synchronous rectification exists partly to shorten that interval." },
{ t: "el-mosfets", d: 2, q: "What does driving a MOSFET gate from a microcontroller pin directly usually cause?", o: ["Slow switching, because the pin cannot supply the peak current", "Immediate destruction of the gate oxide caused by an over-voltage", "The device to remain permanently in the off state", "Excessive standby current through the gate resistance"], a: 0, why: "The gate is a capacitor of a few nanofarads, and charging it quickly needs an amp or more. A weak drive stretches the transition, so the device spends far too long in the lossy linear region." },
{ t: "el-mosfets", d: 3, q: "Why can dv/dt on one device turn the other one on in a bridge?", o: ["Current through Cgd raises the gate above threshold", "The shared supply rail sags and shifts the reference", "The body diode injects charge into the gate node", "The gate driver's output impedance rises with frequency"], a: 0, why: "A fast swing on the drain couples through the drain-gate capacitance into the gate, and if the drive impedance is high enough the gate lifts. A negative off-state bias, or a low-impedance pull-down, prevents it." },

// -------------------------------------------------------- el-comparators
{ t: "el-comparators", d: 1, q: "Why does a comparator need hysteresis on a slowly changing input?", o: ["Noise near the threshold would otherwise cause multiple transitions", "The output would otherwise settle at some intermediate voltage instead", "Hysteresis increases the comparator's switching speed", "It prevents the input from exceeding the supply rails"], a: 0, why: "A slow crossing means the input dwells near the threshold, and any noise there produces a burst of edges. Positive feedback moves the threshold after each transition so the input has to travel back." },
{ t: "el-comparators", d: 2, q: "How is hysteresis usually added to a comparator?", o: ["Positive feedback from the output back to the input", "A capacitor placed across the comparator's two inputs", "A resistor divider on the output stage", "An RC filter placed ahead of the input"], a: 0, why: "A resistor from output to the non-inverting input shifts the threshold by a fraction of the output swing. The amount is set by the divider ratio against the output swing." },
{ t: "el-comparators", d: 2, q: "What is the practical difference between a comparator and an op-amp?", o: ["A comparator is designed to saturate quickly and is not compensated", "A comparator has a much higher open-loop gain", "An op-amp cannot drive a digital logic input", "A comparator has essentially no input offset voltage at all to speak of"], a: 0, why: "The op-amp's compensation makes it stable in a feedback loop but slow to recover from saturation, and its output may not reach the rails. Using one as a comparator is a classic source of sluggish, ringing edges." },
{ t: "el-comparators", d: 2, q: "Why is an open-drain comparator output often convenient?", o: ["It can be pulled to any logic level and wired-OR with others", "It switches considerably faster than any push-pull output stage", "It draws no current when the output is low", "It provides built-in short-circuit protection"], a: 0, why: "A single pull-up sets the logic level, so a 5 V comparator can drive 3.3 V logic. Several outputs on one pull-up also give you a wired-OR alarm line for free." },
{ t: "el-comparators", d: 3, q: "What sets a window comparator's two thresholds?", o: ["Two comparators sharing a divider that fixes upper and lower limits", "A single comparator with its hysteresis set to the whole window width", "The supply voltage and the input's common-mode range", "A resistor in series with the comparator's output"], a: 0, why: "One comparator flags above the upper limit and the other below the lower, and their outputs are combined. It is the standard way to say whether a signal is inside a band." },
{ t: "el-comparators", d: 2, q: "Why does comparator output ringing sometimes appear on the supply?", o: ["The fast edge draws a current spike through the supply inductance", "The comparator's own reference is derived from the main supply rail", "The output stage shorts the supply during the transition", "The input signal couples through the substrate to the rail"], a: 0, why: "A sharp edge into a capacitive load is a large di/dt, and the supply path's inductance turns that into a voltage spike. Local decoupling right at the pin is what keeps it out of the rest of the board." },
{ t: "el-comparators", d: 2, q: "What does a comparator's propagation delay depend on?", o: ["The overdrive, so a small input step takes longer", "Only the supply voltage and the load capacitance", "The number of times it has switched recently", "The value of the hysteresis resistor used"], a: 0, why: "Datasheets quote delay at a stated overdrive because a barely-crossing input takes far longer to resolve. That dependence matters when you are timing a slow ramp." },
{ t: "el-comparators", d: 2, q: "Why might a comparator oscillate with no hysteresis and a clean input?", o: ["Output edges couple back to the input through layout capacitance", "The comparator's internal gain is too low to resolve the input", "The supply decoupling raises the loop gain above unity", "The input impedance falls as the output switches"], a: 0, why: "A few tenths of a picofarad from the output track to the input track is enough positive feedback at high slew rates. Separating the tracks, and adding deliberate hysteresis, both help." },
{ t: "el-comparators", d: 3, q: "What is the risk of driving a comparator's input beyond its common-mode range?", o: ["The output can invert or latch, giving a wrong answer", "The input protection diodes will fail immediately", "The propagation delay increases by a fixed amount", "The hysteresis threshold shifts permanently"], a: 0, why: "Outside the specified range the internal stage may saturate in a way that reverses the sense of the comparison. Some parts specify phase reversal explicitly; others simply leave it undefined." },
{ t: "el-comparators", d: 2, q: "Why is a comparator used to build a relaxation oscillator?", o: ["Its hysteresis plus an RC gives a repeating charge and discharge", "It generates a pure sinusoid whenever its own loop gain exceeds unity", "It divides an existing clock down by a fixed factor", "It amplifies thermal noise into a periodic waveform"], a: 0, why: "The capacitor charges towards the output rail until it crosses the threshold, the output flips, and it charges the other way. The period is set by the RC and the hysteresis fraction." },

// --------------------------------------------------------- el-precision
{ t: "el-precision", d: 2, q: "What is the difference between offset and drift in a precision amplifier?", o: ["Offset is a fixed error you can null; drift changes with temperature", "Offset is random and drift is systematic in every part", "Offset applies to current and drift only to voltage", "Drift is measured in volts, whereas the offset is in volts per degree C"], a: 0, why: "You can trim an offset once at a known temperature, but drift moves the trim as the board warms. That is why the drift specification, not the offset, usually decides the part." },
{ t: "el-precision", d: 2, q: "How does a chopper-stabilised amplifier reduce offset and 1/f noise?", o: ["It modulates the signal above the flicker region, amplifies, then demodulates", "It averages many samples of the input over a long interval", "It simply uses considerably larger input transistors to reduce the noise density", "It nulls the offset once at power-up and holds the value"], a: 0, why: "The offset and flicker noise stay at low frequency while the signal is moved up and back, so they end up out of band and are filtered out. The cost is switching artefacts at the chopping frequency." },
{ t: "el-precision", d: 3, q: "Why do thermocouple effects matter in a microvolt measurement?", o: ["Dissimilar metal junctions at different temperatures generate microvolts", "Copper tracks change their own resistance quite measurably with temperature", "The solder joints rectify high-frequency interference", "The board's dielectric absorbs and releases charge slowly"], a: 0, why: "Every solder joint and connector is a junction of dissimilar metals, so a thermal gradient across the board becomes a drifting offset. Symmetric layout, so that pairs of junctions cancel, is the standard defence." },
{ t: "el-precision", d: 2, q: "What does a guard trace driven at the same potential as a node achieve?", o: ["No voltage across the surface path, so no leakage current", "A lower capacitance between the node and the ground plane", "Shielding of the node from radiated interference", "A defined return path for the node's signal current"], a: 0, why: "Surface leakage is driven by the voltage across the insulator, so removing that voltage removes the current. Guarding is what makes picoampere measurements possible on ordinary board material." },
{ t: "el-precision", d: 2, q: "Why does flux residue matter in a high-impedance circuit?", o: ["It provides a leakage path across the insulating surface", "It changes the dielectric constant of the board substrate itself", "It corrodes the pads over the life of the product", "It absorbs moisture and shifts component values"], a: 0, why: "At gigohm impedances a residue path of a few hundred megohms is a large error. Thorough cleaning, and conformal coating afterwards, is part of the design rather than an afterthought." },
{ t: "el-precision", d: 3, q: "What does a four-wire, or Kelvin, connection eliminate?", o: ["The voltage drop in the leads carrying the excitation current", "The thermal noise that is generated by the sense resistor itself", "The offset voltage of the measuring amplifier", "The capacitance between the leads and the enclosure"], a: 0, why: "Current flows in one pair and voltage is measured on another that carries essentially none, so the lead resistance drops out. It is what makes a milliohm shunt measurable at all." },
{ t: "el-precision", d: 2, q: "Why is a voltage reference's long-term drift quoted in parts per million per root hour?", o: ["The drift is a random walk, so it grows with the square root of time", "The specification is only valid during the very first hour of operation", "It allows comparison between references of different voltages", "Drift is measured hourly and averaged over the test period"], a: 0, why: "The ageing mechanism behaves as a random walk rather than a steady ramp, so a thousand hours gives about thirty times the one-hour figure. That is why periodic recalibration beats extrapolation." },
{ t: "el-precision", d: 2, q: "What does averaging fail to remove from a precision measurement?", o: ["Any systematic offset or gain error in the chain", "Uncorrelated noise from the amplifier's input stage", "Quantisation noise from the analog to digital converter", "Interference at frequencies above the sample rate"], a: 0, why: "Averaging attacks the random part and leaves anything constant exactly where it was. Separating the two means measuring a known input, which is what calibration is." },
{ t: "el-precision", d: 2, q: "Why is a low-noise amplifier not automatically a precision amplifier?", o: ["Low noise says nothing about offset, drift or linearity", "Precision parts always have a lower noise density", "Noise and drift are the same specification in different units", "Low-noise parts cannot be used at low frequency"], a: 0, why: "A part optimised for noise at a kilohertz may have a poor offset and a large temperature coefficient. Which specification matters follows from whether you are measuring a small signal or an absolute level." },
{ t: "el-precision", d: 3, q: "What is the point of measuring a known reference through the same signal path?", o: ["It separates the chain's error from the quantity being measured", "It confirms the analog to digital converter is not saturated", "It provides a trigger for synchronising the measurement", "It removes the need for a calibrated instrument entirely"], a: 0, why: "Switching between the unknown and a reference through identical electronics cancels the gain and offset that are common to both. It is why a self-calibrating instrument has an internal standard." },

// ----------------------------------------------------------------- el-emc
{ t: "el-emc", d: 1, q: "What is the difference between differential-mode and common-mode current?", o: ["Differential goes out on one conductor and back on the other", "Differential mode is always at a higher frequency", "Common mode flows only in the shield of a cable", "Common mode is the part that actually carries the useful signal"], a: 0, why: "Common mode flows the same direction on every conductor and returns through the chassis or free space. That is why it radiates so much better and why a common-mode choke is a distinct component." },
{ t: "el-emc", d: 2, q: "Why is loop area the key variable for radiated emission?", o: ["Radiated field from a current loop is proportional to its area", "A larger loop has a higher resistance and dissipates more", "Loop area determines the resonant frequency of the circuit", "The loop's inductance sets the maximum switching speed"], a: 0, why: "The loop is a small magnetic antenna, and its effective aperture is its area. Running the return directly under the signal is the cheapest possible fix." },
{ t: "el-emc", d: 2, q: "What does slowing an edge achieve for emissions?", o: ["It moves the spectral knee down, cutting the high harmonics", "It reduces the fundamental frequency of the driving signal itself", "It lowers the total energy the signal contains", "It improves the impedance match to the trace"], a: 0, why: "The spectrum's second break frequency is set by the rise time, so a slower edge drops the high-frequency content sharply. Use the slowest edge the timing budget will tolerate." },
{ t: "el-emc", d: 3, q: "Why is a pigtail on a cable shield so damaging at high frequency?", o: ["Its inductance makes the shield connection high impedance", "It increases the capacitance between shield and chassis", "It creates a differential-mode path around the shield", "It reduces the shield's coverage of the conductors"], a: 0, why: "A few centimetres of wire is tens of nanohenries, which at a hundred megahertz is a substantial impedance in the one place you needed none. A 360-degree backshell termination is what actually works." },
{ t: "el-emc", d: 2, q: "What does a common-mode choke do?", o: ["Presents high impedance to common mode and almost none to differential", "Filters the supply rail without affecting the signal", "It blocks the direct current while passing the alternating signal through", "Matches the impedance of the cable to the driver"], a: 0, why: "The differential currents' fluxes cancel in the core while the common-mode currents' fluxes add. That is why it can be placed in a signal path without degrading the signal." },
{ t: "el-emc", d: 2, q: "Why does a near-field probe help even though it is not a compliance measurement?", o: ["It finds which part of the board is the source", "It gives a calibrated field strength in volts per metre", "It measures the emission at the standard three-metre distance", "It replaces the need for a chamber test entirely"], a: 0, why: "A compliance test tells you that you failed and at what frequency, not where on the board. A hand probe over the layout finds the offending loop in minutes." },
{ t: "el-emc", d: 2, q: "What does spread-spectrum clocking actually do to emissions?", o: ["Spreads the energy over a wider band, lowering the measured peak", "Reduces the total emitted energy from the clock", "Moves all the clock's harmonics outside the measured frequency range", "Cancels the clock's radiation with an antiphase signal"], a: 0, why: "The same energy occupies more bandwidth, so less falls in the receiver's resolution bandwidth. It helps you pass the test and does not help a victim that integrates over the whole band." },
{ t: "el-emc", d: 3, q: "Why can a split ground plane make emissions worse rather than better?", o: ["Return current crossing the gap takes a long detour", "The two halves resonate against each other at high frequency", "The split increases the plane's total inductance", "Splitting doubles the number of ground reference points"], a: 0, why: "The return follows the signal at high frequency, and a slot forces it around the end of the gap, creating exactly the large loop you were trying to avoid. One solid plane with careful placement is almost always better." },
{ t: "el-emc", d: 2, q: "What is the purpose of a ferrite bead on a supply line?", o: ["It presents a lossy impedance at high frequency, damping noise", "It stores up energy so as to supply the load during any transients", "It provides reverse polarity protection for the rail", "It matches the impedance between two supply domains"], a: 0, why: "Above its resonance it is effectively a resistor, so it dissipates rather than reflects. Choosing one by its impedance at the frequency of interest, not by its DC resistance, is the trick." },
{ t: "el-emc", d: 2, q: "Why does a heatsink sometimes need bonding to chassis ground?", o: ["Left floating it is a plate antenna driven by the device", "It provides a return path for the device's supply current", "Bonding improves the thermal conductivity to the chassis", "It prevents static charge damaging the semiconductor"], a: 0, why: "The switch node couples capacitively into the heatsink, and an isolated conductor of that size radiates efficiently. Bonding it, or adding an earthed insulating pad, removes the antenna." },

// ---------------------------------------------------------- el-protection
{ t: "el-protection", d: 1, q: "What does a TVS diode do in an ESD path?", o: ["Clamps the voltage by conducting the surge to ground", "Blocks the surge current from entering the circuit", "Absorbs the energy and dissipates it as heat over time", "Opens the connection until the surge has passed"], a: 0, why: "It is a fast avalanche device that turns on above its standoff voltage and shunts the current away. The clamping voltage, not the standoff voltage, is what the protected part actually sees." },
{ t: "el-protection", d: 2, q: "Why does layout matter as much as the TVS part itself?", o: ["The loop through the TVS adds L*di/dt during the fast edge", "The board material determines the clamping voltage", "The trace resistance limits the surge current available", "A long trace changes the TVS's standoff voltage"], a: 0, why: "An ESD edge is amps in a nanosecond, so even a short loop develops a substantial voltage that appears across the protected pin. The TVS belongs at the connector, with the shortest possible path to the plane." },
{ t: "el-protection", d: 2, q: "What does a resettable polyfuse actually do?", o: ["Heats up and becomes high resistance until the fault clears", "Opens a mechanical contact that closes again on cooling", "Limits current to a fixed value indefinitely", "Diverts the excess current to the ground plane"], a: 0, why: "It is a positive temperature coefficient device that self-heats into a high-resistance state. It stays hot and low-resistance right after tripping, so it offers no protection on an immediate restart." },
{ t: "el-protection", d: 3, q: "Why is a series resistor often added ahead of a clamp diode?", o: ["It limits the current the clamp has to carry", "It slows the edge so the clamp has time to respond", "It sets the voltage at which the clamp conducts", "It prevents the clamp from leaking when off"], a: 0, why: "Injected current through the clamp can lift the internal rail and disturb other circuits, and the on-chip diodes have a low rating. A modest series resistance keeps that current within what the part tolerates." },
{ t: "el-protection", d: 2, q: "What is the point of reverse polarity protection with a P-channel MOSFET?", o: ["Very low drop compared with a series diode, in the right orientation", "It disconnects the load faster than any fuse can", "It clamps the reverse voltage to a safe level", "It also provides current limiting as well as full reverse polarity blocking"], a: 0, why: "The body diode is oriented to conduct in the correct polarity and the channel then shorts it out, so the drop is a few tens of millivolts rather than several hundred. A series Schottky wastes far more at any real current." },
{ t: "el-protection", d: 2, q: "Why does a capacitive touch or antenna pin complicate ESD protection?", o: ["The protection device's capacitance loads the signal", "The pin cannot tolerate any series resistance at all", "Clamps do not work at the frequencies involved", "The pin is already protected by its internal diodes"], a: 0, why: "A general-purpose TVS may add several picofarads, which degrades edges or detunes an antenna. Low-capacitance parts exist precisely for this and cost more for that reason." },
{ t: "el-protection", d: 2, q: "What does an inrush limiter protect against?", o: ["The surge that charges a large capacitance at power-up", "A short circuit that develops during normal operation", "Over-voltage arriving from the supply side", "Reverse current when the supply is removed"], a: 0, why: "Charging bulk capacitance from a stiff source is a very large momentary current that can weld connector contacts and drag the rail down. A negative temperature coefficient thermistor or a controlled soft-start spreads it out." },
{ t: "el-protection", d: 3, q: "Why is over-voltage protection on a load switch not the same as a crowbar?", o: ["A switch disconnects the load; a crowbar shorts the supply to blow a fuse", "A crowbar limits the voltage, whereas a load switch limits only the current", "A switch responds faster than any crowbar arrangement", "A crowbar is only usable on the low-voltage side"], a: 0, why: "The crowbar is a deliberate destructive short that guarantees the fuse opens, which suits a rail that must never exceed a limit. A load switch is recoverable and leaves the supply intact." },
{ t: "el-protection", d: 2, q: "What is latch-up and why does injected current cause it?", o: ["A parasitic thyristor turns on and shorts the rails until power cycles", "The device's clock stops and the core stops responding", "The output driver simply holds its state after the input has been removed", "The gate oxide breaks down and the device leaks permanently"], a: 0, why: "The parasitic structure in a CMOS process can be triggered by current injected through a pin, and it stays on until the supply is removed. Limiting injection current is the reason for the series resistor on exposed pins." },
{ t: "el-protection", d: 2, q: "Why should protection be tested rather than assumed?", o: ["Real events involve layout, connectors and grounding, not just the part", "Simulation models of these TVS devices are always rather inaccurate anyway", "The clamping voltage varies between production batches", "Standards require a test report before any deployment"], a: 0, why: "The part is usually the least uncertain element; the loop, the connector and the return path are what decide the outcome. An ESD gun and a repeatable procedure turn an opinion into a measurement." },

// --------------------------------------------------------------- el-clocks
{ t: "el-clocks", d: 1, q: "What does a crystal's load capacitance specification mean?", o: ["The capacitance the crystal must see to oscillate at its stated frequency", "The maximum capacitance that the crystal is able to drive on its own output", "The capacitance internal to the crystal package itself", "The value of capacitor to place across the supply pins"], a: 0, why: "The oscillator's two capacitors, plus stray, must present that value or the frequency shifts. Getting it wrong by a few picofarads is tens of parts per million of error." },
{ t: "el-clocks", d: 2, q: "Why does adding a scope probe to a crystal pin often stop the oscillator?", o: ["The probe's capacitance shifts the frequency and can kill oscillation", "The probe loads the supply rail and browns the whole oscillator out entirely", "The probe's ground lead shorts the crystal to chassis", "The probe injects noise that swamps the small signal"], a: 0, why: "The oscillator node is high impedance and a probe adds several picofarads plus loss. Probing the buffered clock output, or using an active low-capacitance probe, avoids the problem." },
{ t: "el-clocks", d: 2, q: "What is the difference between jitter and frequency stability?", o: ["Jitter is short-term cycle-to-cycle; stability is long-term accuracy", "Jitter applies only to crystals, while stability applies to oscillators", "Stability is measured in seconds and jitter in hertz", "They are the same quantity measured at different times"], a: 0, why: "A part can have excellent jitter and drift badly over temperature, or the reverse. Which matters depends on whether you are sampling a fast signal or holding time over hours." },
{ t: "el-clocks", d: 3, q: "Why does clock jitter cap the signal to noise ratio of a fast converter?", o: ["Timing uncertainty on a slewing signal becomes amplitude error", "Jitter modulates the converter's reference voltage directly", "It causes the converter to skip conversions occasionally", "The digital filter cannot track a jittery sample clock"], a: 0, why: "Sampling a moment early or late reads a different voltage, and the error grows with the input's slew rate. The limit is roughly minus twenty log of two pi times frequency times jitter." },
{ t: "el-clocks", d: 2, q: "What does an oscillator's negative resistance margin describe?", o: ["How much more gain the circuit has than the crystal's losses need", "The maximum resistance that may be placed in series", "The difference between the start-up and the running frequencies alone", "The impedance the oscillator presents to its load"], a: 0, why: "Reliable starting needs several times more negative resistance than the crystal's equivalent series resistance. Too high a series resistor, too much load capacitance, or too low a drive level all erode it." },
{ t: "el-clocks", d: 2, q: "Why is driving a crystal too hard a problem?", o: ["It ages the crystal and can crack it, causing drift or failure", "It causes the whole oscillator to run at some other harmonic instead", "It increases the load capacitance the crystal sees", "It prevents the oscillator from ever starting again"], a: 0, why: "Excess drive level is a mechanical stress on the quartz, so the frequency ages faster and the part can fail outright. The datasheet's drive level figure is a real limit, not a suggestion." },
{ t: "el-clocks", d: 2, q: "What does a phase-locked loop's loop bandwidth control?", o: ["How much of the reference's jitter is passed and how much is filtered", "The maximum output frequency that the whole loop is able to generate at all", "The time the loop takes to power up from cold", "The division ratio between reference and output"], a: 0, why: "Inside the bandwidth the output follows the reference, including its noise, and outside it the oscillator's own noise dominates. Choosing the crossover is the main design decision in a clean-up loop." },
{ t: "el-clocks", d: 3, q: "Why is a clock distributed on a dedicated global network in an FPGA?", o: ["It gives low, matched skew to every destination", "The Verilog language requires clocks to use them", "It reduces the clock's power consumption substantially", "General routing cannot carry a signal that fast"], a: 0, why: "The dedicated tree is balanced, so every flop sees the edge at nearly the same time. Routing a clock through general fabric gives uncontrolled skew and makes hold analysis a nightmare." },
{ t: "el-clocks", d: 2, q: "What is the practical reason to prefer a clock enable over gating a clock?", o: ["Gating in fabric adds skew and glitch risk that timing tools dislike", "A clock enable simply uses far fewer logic resources in every single case", "Gated clocks cannot be simulated accurately at all", "An enable reduces the power more than gating does"], a: 0, why: "A gate in ordinary logic is not on the clock tree, so its output arrives late and can glitch. ASICs use dedicated integrated clock-gating cells; on an FPGA the free-running clock with an enable is the safe idiom." },
{ t: "el-clocks", d: 2, q: "Why does a real-time clock crystal need particular care?", o: ["A 32 kHz crystal has very low drive and high impedance", "It runs at a higher voltage than the main oscillator", "Its accuracy depends on the supply voltage directly", "It must be placed far from the main crystal to avoid pulling"], a: 0, why: "The tiny drive level and megohm-scale impedance make it exquisitely sensitive to leakage and stray capacitance. Board contamination near those pins shows up as a clock that runs slow." },

// ---------------------------------------------------------- el-motor-drive
{ t: "el-motor-drive", d: 1, q: "Why does a brushed DC motor need a flyback path?", o: ["The winding inductance cannot stop conducting instantly", "The commutator would otherwise arc at every transition", "The motor generates a back-EMF that must be dissipated", "The supply cannot absorb the motor's inrush current"], a: 0, why: "Interrupting current in an inductor makes the voltage rise until something breaks down. A diode, or the body diodes of a bridge, gives that current somewhere to go." },
{ t: "el-motor-drive", d: 2, q: "What is dead time in a bridge and why is it needed?", o: ["A gap between one device turning off and the other on, preventing shoot-through", "A delay after start-up before the bridge is enabled", "The interval when the motor current is zero each cycle", "The length of time that the controller waits before it reverses the direction of travel"], a: 0, why: "Devices do not switch instantaneously, so without a gap both can conduct and short the supply. Too much dead time distorts the output, so it is tuned to the actual switching times." },
{ t: "el-motor-drive", d: 2, q: "Why is current sensing on the low side simpler but less complete?", o: ["It sits at ground potential but only sees current when the low device conducts", "It requires an isolated amplifier that adds cost and delay", "It measures the total supply current rather than any of the actual phase currents", "It cannot resolve currents below about one ampere"], a: 0, why: "A ground-referenced shunt is easy to amplify, but the current is only visible in certain PWM states. In-line phase sensing sees it continuously and needs a high common-mode amplifier." },
{ t: "el-motor-drive", d: 3, q: "What does field-oriented control actually compute?", o: ["Flux-producing and torque-producing current components in a rotor frame", "The optimal switching frequency for the present speed", "The back-EMF constant derived from every one of the measured phase voltages", "The mechanical resonance of the motor and its load"], a: 0, why: "Transforming into a frame aligned with the rotor turns the sinusoidal phase currents into two DC-like quantities that can be regulated independently. That is what gives a brushless motor the control feel of a brushed one." },
{ t: "el-motor-drive", d: 2, q: "Why does a stepper motor lose torque as step rate rises?", o: ["There is less time to force current into the winding inductance", "The rotor's inertia cannot follow the commanded steps", "The driver's own supply voltage sags away at the higher frequencies", "The magnetic material saturates at higher frequencies"], a: 0, why: "Current rise is limited by the winding's L over R, so at speed the current never reaches its target. A chopper drive with a much higher supply voltage forces it in faster and holds the torque up." },
{ t: "el-motor-drive", d: 2, q: "What does microstepping actually improve?", o: ["Smoothness and resolution, though holding torque per step falls", "The motor's own maximum speed at any given supply voltage whatsoever", "The absolute positional accuracy of each full step", "The efficiency of the drive at low speeds"], a: 0, why: "Intermediate current ratios place the rotor between full-step positions, which reduces resonance and audible noise. The restoring torque at those positions is weaker, so accuracy under load does not improve." },
{ t: "el-motor-drive", d: 2, q: "Why is a stalled brushed motor a thermal risk?", o: ["With no rotation there is no back-EMF, so current is limited only by resistance", "The commutator brushes lose contact and arc continuously", "The winding's own inductance rises very sharply as soon as the rotor comes to a stop", "The motor's cooling fan stops turning at zero speed"], a: 0, why: "Stall current can be many times the running current, and it flows indefinitely. A current limit, or a stall timeout in firmware, is what keeps the winding from cooking." },
{ t: "el-motor-drive", d: 3, q: "What does space vector modulation gain over sinusoidal PWM?", o: ["About fifteen percent more usable bus voltage", "A lower switching frequency for the same ripple", "Elimination of the need for dead time entirely", "Direct measurement of the rotor position"], a: 0, why: "It exploits the fact that only line-to-line voltages matter, so it can push the phase voltages beyond the naive limit. That extra headroom is worth real speed from the same battery." },
{ t: "el-motor-drive", d: 2, q: "Why does regenerative braking need somewhere for the energy to go?", o: ["The motor becomes a generator and charges the bus capacitance", "The braking torque is directly proportional to the stored energy", "The controller cannot switch fast enough to absorb it", "The motor's inductance resonates with the supply"], a: 0, why: "If the supply cannot sink current, the returned energy raises the bus voltage until something fails. A brake resistor, or a battery that can accept charge, is what absorbs it." },
{ t: "el-motor-drive", d: 2, q: "What causes audible whine from a motor drive?", o: ["Switching frequency components exciting mechanical structure", "The motor's bearings running dry at speed", "Harmonics of the mains frequency in the supply", "The controller's own software loop simply running far too slowly"], a: 0, why: "PWM in the audible band drives magnetostriction in the laminations and vibration in the windings. Moving the carrier above twenty kilohertz removes it, at the cost of higher switching loss." },

// -------------------------------------------------------------- el-layout
{ t: "el-layout", d: 1, q: "Why does a return current at high frequency follow the signal trace?", o: ["It takes the path of least inductance, which is the smallest loop", "The plane's own resistance is at its lowest directly under the trace", "Capacitive coupling forces it into that region", "The plane is designed with a channel under each trace"], a: 0, why: "At low frequency the return spreads to minimise resistance; above a few tens of kilohertz inductance dominates and it hugs the signal. That is why a slot in the plane is so damaging." },
{ t: "el-layout", d: 2, q: "What is the practical reason to keep a four-layer stackup over two layers?", o: ["It gives adjacent reference planes so every signal has a close return", "It allows twice as many components to be placed", "It reduces the board's overall manufacturing cost really quite noticeably", "It removes the need for decoupling capacitors"], a: 0, why: "A signal layer next to a solid plane has a low-inductance return directly beneath it, which fixes both emissions and susceptibility. Two-layer boards force long return detours around the components." },
{ t: "el-layout", d: 2, q: "Why should a decoupling capacitor's via be close to its pad?", o: ["Via inductance is in series and undoes the capacitor's benefit", "A short trace reduces the capacitor's equivalent series resistance", "The via would otherwise couple noise into other layers", "Longer traces change the capacitor's resonant frequency upward"], a: 0, why: "A via is roughly a nanohenry, and two of them plus a trace easily exceed the capacitor's own inductance. The loop from pin to capacitor to plane and back is the thing to minimise." },
{ t: "el-layout", d: 3, q: "Why does an unused portion of a through-hole via matter at high speed?", o: ["It forms a stub that resonates at some frequency", "It increases the via's capacitance to the planes", "It weakens the board mechanically at that point", "It prevents the via from carrying enough current"], a: 0, why: "The leftover barrel is an open-circuited transmission line that resonates and puts a notch in the channel. Back-drilling or blind vias remove it, which is why high-speed boards specify them." },
{ t: "el-layout", d: 2, q: "What does keeping analogue and digital sections apart by placement achieve?", o: ["Noisy return currents stop crossing under the sensitive traces", "It allows two entirely separate ground planes to be used quite safely", "It reduces the total trace length on the board", "It makes the layout easier to inspect visually"], a: 0, why: "Partitioning by placement, over one solid plane, keeps the digital return currents in the digital region without cutting the plane. Splitting the plane instead usually makes matters worse." },
{ t: "el-layout", d: 2, q: "Why does a thermal relief pad exist on a plane connection?", o: ["It slows heat flow into the plane so the joint can be soldered", "It reduces the current the connection can carry deliberately", "It insulates the pad electrically from the plane", "It provides a mechanical stress relief for the joint"], a: 0, why: "A pad connected directly into a large copper pour wicks heat away and gives a cold joint. The spokes make it solderable, at the cost of some resistance and inductance." },
{ t: "el-layout", d: 3, q: "What sets a trace's characteristic impedance?", o: ["The conductor's geometry and its spacing from the return plane", "The dielectric constant of the material alone", "The trace's total length together with the frequency of operation", "The copper weight and the surface finish used"], a: 0, why: "Width, thickness, height above the plane and the dielectric constant together determine it. Changing layers, and hence the plane spacing, changes the impedance unless the width changes too." },
{ t: "el-layout", d: 2, q: "Why is a via stitching pattern used around a board's edge?", o: ["It ties the planes together and stops edge radiation", "It improves the mechanical strength of the board edge", "It provides mounting points for the enclosure", "It reduces the board's overall capacitance"], a: 0, why: "The gap between two planes at the board edge is a radiating slot at high frequency. Stitching vias at a fraction of a wavelength short the planes together and close it." },
{ t: "el-layout", d: 2, q: "What is the risk of routing a sensitive trace next to a switching node?", o: ["Capacitive coupling injects the switching edge into the signal", "The two traces will short together during assembly", "The switching node's heat changes the signal trace's resistance", "The traces will have different impedances along their length"], a: 0, why: "The switch node has the largest dv/dt on the board, and coupling scales with that and with the parallel run length. Separation, a ground trace between them, or routing on different layers all help." },
{ t: "el-layout", d: 2, q: "Why place the crystal's load capacitors close to the crystal itself?", o: ["Stray capacitance in a longer trace adds to the intended load", "The capacitors would otherwise pick up interference", "It shortens the return path back to the microcontroller's own pins", "It reduces the crystal's equivalent series resistance"], a: 0, why: "The oscillator sees the load capacitors plus everything stray, so extra track is extra load and a frequency shift. A local ground pour under the whole oscillator keeps it repeatable." },

]);
