// Questions for the six Acoustics lessons that had none.
BANKS["Acoustics"] = BANKS["Acoustics"].concat([

// --------------------------------------------------------- ac-radiation
{ t: "ac-radiation", d: 1, q: "A source is much smaller than a wavelength. What is its radiation pattern?", o: ["A narrow beam", "Essentially omnidirectional", "Two lobes", "A null on axis"], a: 1, why: "Directivity comes from path-length differences across the aperture, and when ka is small there are none worth speaking of. It is why a 40 kHz transducer 10 mm across is directional and a 100 Hz source of the same size is not." },
{ t: "ac-radiation", d: 2, q: "For a baffled circular piston of radius a, where does the first off-axis null fall?", o: ["sin(theta) = 0.5*lambda/a", "sin(theta) = 0.61*lambda/a", "sin(theta) = lambda/a", "sin(theta) = 2*lambda/a"], a: 1, why: "The 0.61 comes from the first zero of the J1 Bessel function at 3.83 divided by pi. The rectangular-aperture equivalent uses 1.0 instead, which is the more familiar result and a common slip." },
{ t: "ac-radiation", d: 2, q: "Why is an unbaffled cone a poor low-frequency radiator?", o: ["It is too heavy", "Front and rear radiation are out of phase and cancel by diffracting round the edge when the cone is small compared with a wavelength", "The cone material absorbs", "It has too much mass reactance"], a: 1, why: "This is acoustic short-circuiting, and it is the entire reason loudspeakers need a baffle or a sealed box. The cancellation weakens as the wavelength shortens relative to the baffle." },
{ t: "ac-radiation", d: 2, q: "How does the radiation resistance of a small source scale with ka?", o: ["Linearly", "As (ka)^2, so it is very small below ka = 1", "As 1/ka", "It is constant"], a: 1, why: "The source moves a lot of air and radiates very little power, which is why small low-frequency sources are so inefficient. Above about ka = 1 the resistance flattens to the piston's plane-wave value." },
{ t: "ac-radiation", d: 2, q: "Where does the last axial maximum of a circular piston sit?", o: ["At the face", "At about a^2/lambda, which marks the start of the far field", "At 2a", "At infinity"], a: 1, why: "That is the natural focus of an unfocused element and where the beam is narrowest. Inside it the axial pressure oscillates through maxima and minima, so amplitude measurements there are unreliable." },
{ t: "ac-radiation", d: 3, q: "What distinguishes a monopole from a dipole source?", o: ["Frequency", "A monopole pulsates and radiates omnidirectionally; a dipole oscillates and has a figure-of-eight pattern with a null broadside", "Amplitude only", "A dipole is always louder"], a: 1, why: "A dipole is two opposed monopoles, so it is a far weaker radiator at low frequency, falling as (ka)^4 rather than (ka)^2. An unbaffled speaker is effectively a dipole, which is the same story as acoustic short-circuiting." },
{ t: "ac-radiation", d: 3, q: "Why does a piston's mass reactance matter at low ka?", o: ["It heats the transducer", "The radiation impedance is dominated by reactance, so the source moves entrained air rather than radiating power", "It sets the resonant frequency only", "It reduces bandwidth"], a: 1, why: "The entrained air acts as an added mass that lowers the resonance and stores rather than radiates energy. Efficiency only improves once the resistive part of the radiation impedance becomes comparable." },
{ t: "ac-radiation", d: 3, q: "You need a wider beam from a fixed-frequency transducer. What do you change?", o: ["Increase the drive voltage", "Reduce the aperture, since beamwidth scales with lambda/a", "Add a matching layer", "Increase the pulse length"], a: 1, why: "Directivity is set by aperture in wavelengths, and nothing else. The cost is less radiated power and a shorter near field, which is the usual trade in air-coupled work." },

// --------------------------------------------------------- ac-nonlinear
{ t: "ac-nonlinear", d: 2, q: "Why does a finite-amplitude wave steepen as it propagates?", o: ["Attenuation is frequency dependent", "Compressions travel slightly faster than rarefactions, so the peaks catch up with the troughs", "Diffraction focuses the peaks", "The medium heats up"], a: 1, why: "Local sound speed depends on particle velocity and on the pressure-dependent stiffness of the medium. The waveform tends towards a sawtooth, which in the frequency domain is the growth of harmonics." },
{ t: "ac-nonlinear", d: 2, q: "What does the parameter B/A describe?", o: ["The attenuation coefficient", "The medium's acoustic nonlinearity, from the second-order term in its pressure-density relation", "The impedance ratio", "The beam width"], a: 1, why: "Water is about 5, soft tissues 6 to 11, and fatty tissue higher still. It feeds directly into the coefficient of nonlinearity beta = 1 + B/2A that governs harmonic growth." },
{ t: "ac-nonlinear", d: 2, q: "How does second-harmonic amplitude grow with source pressure before shock formation?", o: ["Linearly", "As the square of the source pressure", "As the square root", "It is independent of it"], a: 1, why: "So doubling the drive quadruples the second harmonic while the fundamental only doubles, which is why harmonic imaging needs a reasonably high output. The growth is also roughly linear with distance in that region." },
{ t: "ac-nonlinear", d: 2, q: "In tissue harmonic imaging, why are clutter and reverberation suppressed?", o: ["Harmonics attenuate more", "The harmonic builds up along the beam, so it is weak in the near field and in the low-amplitude off-axis lobes where clutter originates", "The transducer filters them", "Harmonics travel faster"], a: 1, why: "Body-wall aberration and side-lobe energy are both low amplitude, so they generate almost no harmonic. The harmonic beam is also narrower, which improves lateral resolution as a side effect." },
{ t: "ac-nonlinear", d: 2, q: "The shock parameter sigma is proportional to what?", o: ["Frequency only", "The product of beta, source pressure, frequency and distance", "The inverse of the wavelength", "Attenuation times distance"], a: 1, why: "Sigma = 1 marks shock formation. It says that higher frequency, higher amplitude and longer path all bring shock closer, which is why high-frequency high-amplitude beams shock within a few centimetres in water." },
{ t: "ac-nonlinear", d: 3, q: "Why does a parametric array produce a highly directional low-frequency beam?", o: ["It uses a large aperture at low frequency", "Two high-frequency beams mix nonlinearly in the overlap volume, and the difference frequency inherits the narrow high-frequency beam geometry", "It uses phased steering", "The low frequency is filtered from noise"], a: 1, why: "The virtual end-fire array formed in the water column is what gives the directivity, not the physical aperture. The price is very low conversion efficiency." },
{ t: "ac-nonlinear", d: 3, q: "Why does nonlinear propagation matter when calibrating high-amplitude fields?", o: ["It does not", "Energy shifted into harmonics is attenuated far more strongly, so linear extrapolation from low-amplitude measurements overestimates the field", "Hydrophones cannot measure it", "It changes the frequency of the source"], a: 1, why: "Absorption rises roughly with frequency, so the harmonics deposit their energy locally. It is why derated intensity calculations exist in the safety standards and why measurements should be made at the drive level of interest." },
{ t: "ac-nonlinear", d: 3, q: "What does pulse inversion achieve in harmonic imaging?", o: ["It doubles the frame rate", "Transmitting a pulse and its inverse and summing the echoes cancels the linear response and leaves the even harmonics", "It removes speckle", "It suppresses all harmonics"], a: 1, why: "The linear component is odd about inversion and cancels; the second-harmonic term is even and survives. The cost is two transmissions per line, so frame rate halves and motion causes artefacts." },

// -------------------------------------------------------- ac-cavitation
{ t: "ac-cavitation", d: 2, q: "What defines inertial cavitation?", o: ["Bubbles oscillating steadily about an equilibrium radius", "A bubble grows then collapses violently, driven by the inertia of the surrounding liquid", "Bubble formation only", "Bubbles dissolving"], a: 1, why: "The collapse concentrates energy enormously, giving local temperatures of thousands of kelvin, free radicals, light emission and mechanical damage. Stable cavitation is the gentler oscillatory regime." },
{ t: "ac-cavitation", d: 2, q: "How is the mechanical index defined?", o: ["Intensity divided by frequency", "Peak negative pressure in MPa divided by the square root of centre frequency in MHz", "Peak positive pressure times frequency", "Total energy per pulse"], a: 1, why: "It is a screening number for the likelihood of inertial cavitation, and diagnostic scanners are limited to 1.9. It uses the rarefactional pressure because that is what pulls a bubble open." },
{ t: "ac-cavitation", d: 2, q: "What acoustic emission signature indicates inertial collapse?", o: ["A stronger fundamental", "Broadband noise across the spectrum", "A pure second harmonic", "Reduced total emission"], a: 1, why: "The collapse is an impulsive event, and impulses are broadband. Subharmonics and ultraharmonics indicate stable cavitation, so passive cavitation detection distinguishes the two by spectrum." },
{ t: "ac-cavitation", d: 2, q: "What drives Eckart streaming?", o: ["Bubble oscillation", "Absorption of the beam, which transfers momentum to the fluid and drives a bulk jet", "Surface tension gradients", "Thermal convection"], a: 1, why: "It scales with attenuation and intensity, so it is strongest in absorbing media and high-power beams. Rayleigh and Schlichting streaming are the boundary-layer scale phenomena instead." },
{ t: "ac-cavitation", d: 3, q: "Why does cavitation threshold rise with frequency?", o: ["Higher frequencies are absorbed more", "The rarefaction half-cycle is shorter, so there is less time for a nucleus to grow before the pressure reverses", "Bubbles are smaller", "Attenuation prevents it"], a: 1, why: "It is the physical reason the mechanical index divides by the square root of frequency. It is also why lithotripsy and sonochemistry work at low frequencies and diagnostic imaging at high ones." },
{ t: "ac-cavitation", d: 3, q: "What is the resonant size of a free bubble at 40 kHz in water?", o: ["About 8 micrometres", "About 80 micrometres in radius", "About 0.8 mm", "About 8 mm"], a: 1, why: "The Minnaert relation gives roughly 3 metres per second divided by frequency for the resonant radius, so 3/40000 is about 75 micrometres. It is why cleaning baths at that frequency produce bubbles you can see." },
{ t: "ac-cavitation", d: 3, q: "In an ultrasonic cleaning bath, which regime does the useful work?", o: ["Stable cavitation only", "Inertial collapse near the surface, producing microjets that dislodge contamination", "Acoustic streaming only", "Thermal heating"], a: 1, why: "A collapse near a boundary is asymmetric and drives a jet at the surface. Streaming helps by transporting contamination away, and too much gas in the liquid cushions the collapse and reduces cleaning." },
{ t: "ac-cavitation", d: 3, q: "Why is degassing a liquid before an experiment often necessary?", o: ["To reduce attenuation only", "Dissolved gas seeds cavitation and cushions collapses, so results depend on gas content rather than on the acoustics", "To improve coupling", "To lower the temperature"], a: 1, why: "It is one of the main reasons cavitation experiments are hard to reproduce between laboratories. Reporting dissolved oxygen alongside the acoustic parameters is what makes results comparable." },

// ------------------------------------------------------------ ac-guided
{ t: "ac-guided", d: 2, q: "At low frequency-thickness, how does the A0 Lamb mode behave?", o: ["Non-dispersive and fast", "Strongly dispersive and slow, becoming a flexural plate wave", "The same as S0", "It does not propagate"], a: 1, why: "S0 is the extensional mode and is nearly non-dispersive at low frequency-thickness, which is why it is often preferred for long-range screening. A0 is more sensitive to surface condition and to loading." },
{ t: "ac-guided", d: 2, q: "Why are Lamb dispersion curves plotted against frequency times thickness?", o: ["Convention", "The physics depends on thickness in wavelengths, so the product collapses all thicknesses onto one set of curves", "Thickness is hard to measure", "It linearises the axes"], a: 1, why: "A 1 mm plate at 2 MHz behaves like a 2 mm plate at 1 MHz. It means one chart serves every plate of that material, and it is what you use to pick a mode and a frequency together." },
{ t: "ac-guided", d: 2, q: "Why do guided waves screen long ranges economically?", o: ["They do not attenuate", "The energy is confined by the structure's boundaries and spreads in one or two dimensions rather than three", "They travel faster", "They use higher power"], a: 1, why: "A pipe or plate acts as a waveguide, so one transducer ring can interrogate tens of metres. The trade is that interpretation is far harder and defect sizing is much less direct than pulse-echo." },
{ t: "ac-guided", d: 2, q: "You must inspect a plate with water on one side. Which mode choice is sensible?", o: ["A0, because it is slower", "S0 at low frequency-thickness, because its mostly in-plane motion leaks far less into the fluid", "Any mode, loading does not matter", "The highest available mode"], a: 1, why: "A0 has large out-of-plane displacement, which couples strongly into the liquid and attenuates severely. Leakage, not material damping, dominates the loss for a loaded plate." },
{ t: "ac-guided", d: 3, q: "What does dispersion do to a guided-wave pulse over distance?", o: ["Attenuates it uniformly", "Spreads it, because different frequency components travel at different speeds, degrading resolution and amplitude", "Shifts its centre frequency", "Nothing measurable"], a: 1, why: "It is the defining complication of guided-wave testing. Mitigations are narrowband excitation with a tone burst, operating where the curve is flat, or compensating computationally with the known dispersion relation." },
{ t: "ac-guided", d: 3, q: "How many Lamb modes exist at a given frequency-thickness product?", o: ["Always two", "At least two (S0 and A0), with more appearing above successive cut-off frequencies", "Exactly one", "It depends only on the material"], a: 1, why: "S0 and A0 exist all the way down to zero. Working below the next cut-off keeps the received signal interpretable, because several simultaneous modes overlap and are hard to separate." },
{ t: "ac-guided", d: 3, q: "How are specific Lamb modes usually excited selectively?", o: ["By changing the drive voltage", "By matching the excitation wavelength and angle to the mode, using a wedge at the right angle or a comb or EMAT with the right spacing", "By filtering the received signal", "By using a wider bandwidth"], a: 1, why: "Snell's law relates the wedge angle to the phase velocity you want, so choosing the angle picks the point on the dispersion curve. Comb transducers set the wavelength spatially instead." },
{ t: "ac-guided", d: 3, q: "What are Rayleigh waves, in relation to Lamb waves?", o: ["The same thing", "The surface-wave limit: when the plate is many wavelengths thick, S0 and A0 converge to a wave confined near each surface", "A higher-order Lamb mode", "A bulk wave"], a: 1, why: "The two surfaces stop interacting and each supports its own wave, with energy within roughly one wavelength of the surface. It is why Rayleigh waves are used for surface-breaking crack detection." },

// ----------------------------------------------------------- ac-imaging
{ t: "ac-imaging", d: 2, q: "What does dynamic receive focusing mean?", o: ["Moving the transducer", "The receive delay law is updated continuously with depth, so every depth is focused on receive", "Focusing only at one depth", "Focusing the transmit beam"], a: 1, why: "Transmit can only be focused at one depth per firing, so the transmit focus is the depth where the image is sharpest. Receive costs nothing extra because the data is already in hand." },
{ t: "ac-imaging", d: 2, q: "What does full matrix capture record?", o: ["One A-scan per element", "Every transmit-receive element pair, giving an N by N set of A-scans", "The beamformed image only", "The envelope of each line"], a: 1, why: "It captures everything the array can measure, so any focusing law can be applied afterwards in software. For 64 elements that is 4096 A-scans per position, which is what makes it data-heavy and slow." },
{ t: "ac-imaging", d: 2, q: "Which quantity primarily sets axial resolution?", o: ["Aperture size", "Pulse bandwidth, or equivalently the spatial pulse length", "Focal depth", "Element pitch"], a: 1, why: "Roughly half the spatial pulse length, so shorter pulses resolve better. Lateral resolution is the one set by aperture and wavelength, and the two are limited by different things." },
{ t: "ac-imaging", d: 2, q: "What is the main practical weakness of TFM in the field?", o: ["Poor resolution", "The data volume and computation, which limit inspection speed", "It cannot focus", "It needs a single element"], a: 1, why: "Every pixel sums contributions from every transmit-receive pair. GPUs and FPGAs make it real time in the lab, but on a battery-powered field instrument it is still a coverage-rate problem." },
{ t: "ac-imaging", d: 2, q: "What causes grating lobes in a phased array?", o: ["Too many elements", "Element pitch greater than half a wavelength, allowing constructive addition in unwanted directions", "Insufficient gain", "Too short a pulse"], a: 1, why: "It is spatial aliasing: the array samples the wavefront, and pitch above lambda/2 breaks the Nyquist condition when steering. Sub-wavelength pitch, or limiting the steering angle, avoids it." },
{ t: "ac-imaging", d: 3, q: "Why does apodisation reduce side lobes, and what does it cost?", o: ["It increases gain, and costs nothing", "Tapering the aperture weights suppresses side lobes at the price of a wider main lobe and less sensitivity", "It sharpens the beam at no cost", "It only affects axial resolution"], a: 1, why: "It is the same trade as windowing an FFT, in the spatial domain. Uniform weighting gives the narrowest main lobe and the worst side lobes." },
{ t: "ac-imaging", d: 3, q: "What is plane wave imaging, and why is it fast?", o: ["Imaging with a single element", "Insonifying the whole field with unfocused plane waves and beamforming in software, so one transmission produces a whole frame", "Imaging without a transducer", "Using continuous wave excitation"], a: 1, why: "Frame rates in the thousands per second become possible, which is what enables shear-wave elastography and ultrafast Doppler. Coherently compounding a few steered angles recovers the contrast lost by not focusing on transmit." },
{ t: "ac-imaging", d: 3, q: "Why does speckle appear in a B-mode image, and what is it not?", o: ["Electronic noise, which averaging removes", "Coherent interference from sub-resolution scatterers: it is deterministic for a fixed geometry, not random noise", "A transducer fault", "An artefact of log compression"], a: 1, why: "Repeating the measurement gives the same speckle, so temporal averaging does not remove it. Spatial or frequency compounding does, by combining looks that have decorrelated speckle but the same underlying structure." },

// ----------------------------------------------------------- ac-inverse
{ t: "ac-inverse", d: 2, q: "In time-of-flight tomography, how is each measured travel time modelled?", o: ["As a single average speed", "As a line integral of slowness along the ray path", "As a frequency shift", "As an amplitude ratio"], a: 1, why: "Slowness, the reciprocal of speed, makes the relation linear in the unknown, which is why the reconstruction resembles X-ray CT. The complication is that the rays bend, so path and speed are coupled." },
{ t: "ac-inverse", d: 2, q: "When does cycle skipping occur in full waveform inversion?", o: ["When the source is too weak", "When the starting model is wrong enough that predicted and observed waveforms are more than half a period apart, so the gradient pushes towards the wrong cycle", "When the data is noisy", "When the mesh is too fine"], a: 1, why: "The inversion then converges confidently to a wrong local minimum. Multiscale strategies starting from the lowest usable frequency are the standard defence, because half a period is longer there." },
{ t: "ac-inverse", d: 2, q: "What makes an inverse problem ill-posed?", o: ["It has no solution algorithm", "The solution may not exist, may not be unique, or may not depend continuously on the data", "The forward model is nonlinear", "The data is undersampled"], a: 1, why: "It is Hadamard's definition, and the third condition matters most in practice: small data noise producing large solution changes is what makes an unregularised inversion useless." },
{ t: "ac-inverse", d: 2, q: "What is regularisation, honestly described?", o: ["A numerical trick to speed convergence", "Adding prior assumptions, such as smoothness or sparsity, to make an underdetermined problem tractable", "Removing noisy data", "Increasing the number of measurements"], a: 1, why: "It biases the answer towards what you already believed, which is why the choice of regulariser and its weight should be reported. Trading variance for bias is the whole mechanism." },
{ t: "ac-inverse", d: 2, q: "Why is delay-and-sum a crude inverse rather than a true reconstruction?", o: ["It is too slow", "It is the adjoint rather than the inverse, so it backprojects energy without accounting for the forward operator's amplitude and multiple scattering", "It ignores geometry", "It only works in one dimension"], a: 1, why: "The adjoint gives you a correctly located but incorrectly weighted image, which is why it produces good geometry and unreliable quantitative values. FWI iterates to fix exactly that." },
{ t: "ac-inverse", d: 3, q: "What does the L-curve help you choose?", o: ["The mesh size", "The regularisation weight, at the corner where residual and solution norm trade off", "The frequency band", "The number of iterations only"], a: 1, why: "Plotting solution norm against residual norm on log axes usually shows a corner: below it you are fitting noise, above it you are over-smoothing. Generalised cross-validation is the alternative when there is no clear corner." },
{ t: "ac-inverse", d: 3, q: "Why does full waveform inversion resolve finer detail than travel-time tomography?", o: ["It uses more transducers", "It uses the whole waveform, including amplitude and phase of scattered arrivals, rather than only first-arrival times", "It runs more iterations", "It uses higher frequencies only"], a: 1, why: "Ray-based tomography discards nearly all the information in the record. The price is a forward model that has to be solved repeatedly and a far greater sensitivity to the starting model." },
{ t: "ac-inverse", d: 3, q: "Why does the adjoint-state method matter for FWI?", o: ["It parallelises well", "It computes the gradient for the cost of roughly two forward simulations, independent of the number of model parameters", "It removes the need for regularisation", "It guarantees the global minimum"], a: 1, why: "Finite-difference gradients would need one simulation per parameter, and models have millions. Without it, gradient-based inversion of a large model is simply not computable." }

]);
