// Questions for the eight DSP lessons that had none.
BANKS["DSP"] = BANKS["DSP"].concat([

// ------------------------------------------------------------ dsp-zdomain
{ t: "dsp-zdomain", d: 1, q: "What does the unit circle in the z-plane represent?", o: ["The stability boundary only", "The frequency axis", "The impulse response", "The sample rate"], a: 1, why: "z = e^(j*omega) traces DC at +1 round to Nyquist at -1. Evaluating the transfer function along it gives the frequency response directly, which is why a zero on the circle is a perfect null and a pole near it is a resonance." },
{ t: "dsp-zdomain", d: 2, q: "What does the radius of a pole control?", o: ["The centre frequency of it", "How long the mode rings", "The passband gain", "The filter order"], a: 1, why: "Closer to the circle means slower decay. The envelope decays as r^n, so a pole at 0.9 falls to about 10 percent in roughly 22 samples and one at 0.99 takes about 230. The angle sets the frequency, the radius sets the Q." },
{ t: "dsp-zdomain", d: 2, q: "Where must the poles of a stable causal IIR filter lie?", o: ["Outside the unit circle", "Strictly inside the unit circle", "On the unit circle", "In the left half plane"], a: 1, why: "Inside the circle means r < 1, so r^n decays. The left half plane is the continuous-time condition; mapping s to z sends it to the interior of the unit circle." },
{ t: "dsp-zdomain", d: 2, q: "How do you build a 50 Hz notch from scratch in the z-domain?", o: ["One pole at the origin", "Zeros on the unit circle at the 50 Hz angle", "A single real zero placed exactly at z equals 1", "Poles on the unit circle"], a: 1, why: "Poles sit just inside at the same angle. The zeros create the null and the poles pull the response back to unity either side, so the notch stays narrow. Pole radius sets the width, and 0.95 to 0.99 is the usual range." },
{ t: "dsp-zdomain", d: 2, q: "What does a zero at z = 1 do?", o: ["Blocks Nyquist", "Blocks DC", "Adds a resonance", "Doubles the gain"], a: 1, why: "z = 1 is the DC point on the unit circle. It is the whole content of a first-order difference y[n] = x[n] - x[n-1], which is why differencing removes a baseline offset and why a zero at z = -1 kills Nyquist instead." },
{ t: "dsp-zdomain", d: 3, q: "Why do real-coefficient filters always have poles and zeros in conjugate pairs?", o: ["Convention", "A real impulse response needs the complex terms to cancel", "To guarantee the stability of the whole of the filter design", "For linear phase"], a: 1, why: "That only happens in conjugate pairs. An isolated complex pole would give a complex-valued output. It is also why second-order sections are the natural building block: each holds exactly one conjugate pair." },
{ t: "dsp-zdomain", d: 3, q: "A pole-zero plot shows a pole at radius 0.99 and angle 0.1*pi. What do you say about it?", o: ["It is unstable", "A high-Q resonance at 5 percent of the sample rate", "A fairly wideband lowpass response of some kind or other", "A notch at DC"], a: 1, why: "It rings for hundreds of samples and is sensitive to coefficient quantisation. Angle over pi times the Nyquist frequency gives the centre. The radius warns you twice: long settling, and a pole so close to the circle that rounding the coefficients can push it outside." },
{ t: "dsp-zdomain", d: 3, q: "What does a zero outside the unit circle imply?", o: ["Instability", "A non-minimum-phase filter", "The filter must simply be FIR", "Nothing at all"], a: 1, why: "The magnitude response is achievable but the phase lag is larger than necessary. Only poles decide stability. Reflecting an outside zero to 1/r conjugate leaves the magnitude unchanged and reduces the group delay, which is what minimum-phase design does." },

// --------------------------------------------------------- dsp-fir-design
{ t: "dsp-fir-design", d: 2, q: "For fixed stopband attenuation, halving an FIR's transition width does what to the tap count?", o: ["Halves it", "Roughly doubles it", "Leaves it unchanged", "Quadruples it"], a: 1, why: "Order is approximately attenuation in dB minus 8, divided by 14.6 times the normalised transition width. Taps are inversely proportional to transition width, so sharpness is the expensive axis, not attenuation." },
{ t: "dsp-fir-design", d: 2, q: "How does a Parks-McClellan design compare with a window design meeting the same spec?", o: ["It needs more taps", "It needs fewer taps", "It is not linear phase", "It cannot do bandpass"], a: 1, why: "The error is spread evenly rather than peaking at the band edge. Equiripple means no part of the response is better than it needs to be. The window method wastes taps making the middle of the stopband far quieter than required." },
{ t: "dsp-fir-design", d: 2, q: "What delay does a 101-tap symmetric FIR introduce?", o: ["101 samples", "50 samples, which is (N-1)/2", "1 sample", "It depends on frequency"], a: 1, why: "Constant across all frequencies, which is exactly what linear phase means. Odd tap counts give a whole-sample delay; even counts give a half-sample delay that can complicate alignment." },
{ t: "dsp-fir-design", d: 2, q: "What is special about a half-band filter?", o: ["It has half the taps", "Roughly half its coefficients are exactly zero", "It halves the sample rate automatically", "It has no delay"], a: 1, why: "So a decimate-by-two costs about half the multiplies. Every other tap vanishes apart from the centre, because the cutoff sits at a quarter of the sample rate with a symmetric response. It is the standard building block of multirate chains." },
{ t: "dsp-fir-design", d: 2, q: "Why does a rectangular window give poor stopband attenuation whatever the length?", o: ["It is too short", "Truncation is a discontinuity", "It is not symmetric", "It ends up with non-linear phase"], a: 1, why: "Its sidelobes stay at about -13 dB regardless of length. More taps narrow the mainlobe but do not lower the sidelobes: this is the Gibbs phenomenon. Tapering with Hamming, Blackman or Kaiser trades mainlobe width for sidelobe suppression." },
{ t: "dsp-fir-design", d: 3, q: "You need a linear-phase highpass. Which FIR type must you avoid?", o: ["Type I", "Type II", "Type III", "Any type works"], a: 1, why: "It is forced to have a zero at Nyquist. Even length with even symmetry always nulls Nyquist, so it cannot pass the top of the band. Type I (odd length, even symmetry) is the safe general-purpose choice." },
{ t: "dsp-fir-design", d: 3, q: "What does the Kaiser window's beta parameter control?", o: ["The filter length", "The trade between mainlobe width and sidelobes", "The cutoff frequency of the whole filter itself", "The phase response"], a: 1, why: "It gives one knob for attenuation. With the accompanying formulas for beta and order from a target attenuation and transition width, it makes the window method into something you can design to spec rather than by trial." },
{ t: "dsp-fir-design", d: 3, q: "Your FIR meets spec in floating point but not in 16-bit fixed point. What is the first thing to check?", o: ["The sample rate", "Coefficient quantisation", "The window type", "Only the input scaling used"], a: 1, why: "Especially on a long filter with a small transition width. FIRs are far more tolerant here than IIRs because there is no feedback to amplify the error, but a 300-tap sharp design still loses stopband depth. Quantise then re-plot rather than assuming." },

// --------------------------------------------------------- dsp-iir-design
{ t: "dsp-iir-design", d: 2, q: "Why is prewarping needed with the bilinear transform?", o: ["To fix the gain", "The frequency mapping is nonlinear", "To make the filter causal", "To avoid aliasing in the passband"], a: 1, why: "Critical frequencies must be pre-distorted to land where you want. The transform compresses the infinite analogue axis onto the finite digital one, so the error grows towards Nyquist. Prewarping is exact at one chosen frequency, usually the cutoff." },
{ t: "dsp-iir-design", d: 2, q: "Why implement a high-order IIR as cascaded biquads rather than one direct-form polynomial?", o: ["It is faster", "The root sensitivity of a high-order polynomial", "It uses less memory", "It gives you a fully linear phase response as well"], a: 1, why: "Coefficient rounding is extreme there, and second-order sections are well conditioned. An eighth-order polynomial can move its roots outside the unit circle from tiny coefficient changes, so the filter can become unstable purely from quantisation. Each biquad holds one conjugate pair and stays robust." },
{ t: "dsp-iir-design", d: 2, q: "What is a sensible rule for ordering biquad sections in a cascade?", o: ["Highest Q first, always", "Pair each pole with its nearest zero", "Random order", "In strict alphabetical order by frequency"], a: 1, why: "Order the sections to keep intermediate signals within range. Pairing keeps each section's gain close to flat, and ordering controls where the peaks occur. In fixed point the wrong order overflows an intermediate even though the overall response is fine." },
{ t: "dsp-iir-design", d: 2, q: "Compared with a linear-phase FIR meeting the same magnitude spec, an IIR typically offers what?", o: ["Better phase", "Far fewer coefficients and lower delay", "Guaranteed stability", "Simpler fixed-point implementation"], a: 1, why: "At the cost of non-linear phase and possible instability. An order-6 elliptic can match a 200-tap FIR in magnitude. You give up constant group delay and the unconditional stability that comes from having no feedback." },
{ t: "dsp-iir-design", d: 2, q: "Which classical IIR prototype has ripple in both passband and stopband?", o: ["Butterworth", "Elliptic (Cauer)", "Chebyshev type I", "Bessel"], a: 1, why: "Which is why it gives the sharpest transition for a given order. Butterworth is maximally flat with no ripple, Chebyshev I ripples in the passband only, and Bessel optimises group delay flatness instead." },
{ t: "dsp-iir-design", d: 3, q: "Why is Direct Form II Transposed usually preferred for a fixed-point biquad?", o: ["It uses considerably fewer multiplies", "It has better numerical behaviour", "It is linear phase", "It cannot overflow"], a: 1, why: "It needs only two state variables. All forms use the same five coefficients and two states, but the transposed structure keeps the accumulator behaviour more favourable and is what CMSIS-DSP and most libraries implement." },
{ t: "dsp-iir-design", d: 3, q: "You need a filter whose group delay is as flat as possible. Which prototype?", o: ["Elliptic", "Bessel", "Chebyshev type II", "Butterworth"], a: 1, why: "Bessel is designed for maximally flat group delay, so pulses keep their shape. The price is a very gentle magnitude rolloff, which is why it appears in pulse and audio crossover work rather than in sharp filtering." },
{ t: "dsp-iir-design", d: 3, q: "An IIR designed at 1 kHz sample rate is reused at 48 kHz without redesign. What happens?", o: ["Nothing, coefficients are dimensionless", "The cutoff moves with the sample rate, so it changes", "It becomes unstable", "It becomes an FIR"], a: 1, why: "It now sits 48 times higher in Hz. Coefficients encode a normalised frequency, not a frequency in Hz. Any change of sample rate needs a redesign, which is why filter code should store the design parameters rather than only the coefficients." },

// ------------------------------------------------------------- dsp-fixed
{ t: "dsp-fixed", d: 2, q: "Multiplying two Q15 values gives a result in which format?", o: ["Q15 throughout the whole thing", "Q30 in a 32-bit accumulator", "Q31", "Q16"], a: 1, why: "It needs a shift to return to Q15. Fractional bits add, so the redundant sign bit at position 30 is why the conventional correction is a left shift by one then take the top 16 bits, or equivalently a right shift by 15." },
{ t: "dsp-fixed", d: 2, q: "What does saturating arithmetic do that wraparound does not?", o: ["It is faster", "It clamps at the extreme", "It uses fewer bits", "It prevents overflow occurring"], a: 1, why: "It does not jump to the opposite sign, so overload degrades gracefully. Wraparound turns a slightly-too-large positive peak into a large negative one, which sounds and looks catastrophic. Saturation flattens the peak instead, which is merely distortion." },
{ t: "dsp-fixed", d: 2, q: "Coefficient quantisation is most dangerous in which case?", o: ["Short FIR filters", "High-Q IIR poles near the unit circle", "Any FIR", "Filters that use only integer arithmetic"], a: 1, why: "A tiny coefficient change moves the pole, and a pole at radius 0.999 has very little margin before it lands outside. FIRs have no feedback, so quantisation degrades the response rather than threatening stability." },
{ t: "dsp-fixed", d: 2, q: "What is a limit cycle in a fixed-point IIR?", o: ["A stable oscillation the filter enters with zero input, caused by rounding in the feedback path", "An overflow", "A clock domain issue", "A coefficient error"], a: 1, why: "The rounding error feeds back and sustains itself, so the output never quite reaches zero. The usual mitigations are more accumulator bits, error feedback, or dithering the truncation." },
{ t: "dsp-fixed", d: 2, q: "What is the first step in a fixed-point design, before writing any code?", o: ["Choosing the word length", "Deciding the scaling strategy", "Picking saturating instructions", "Measuring the noise floor"], a: 1, why: "That means the expected range at every node in the signal path. Fixed point is bookkeeping about where the binary point sits. Working that out after the code exists means chasing overflows empirically, which converges slowly and never proves anything." },
{ t: "dsp-fixed", d: 3, q: "Why does a Cortex-M4 with an FPU not automatically make float the right choice?", o: ["The FPU is slow", "Divides and transcendentals are still multi-cycle", "Floats use more RAM", "The FPU is simply not fully IEEE 754 compliant at all"], a: 1, why: "Float in an ISR may also need extra context save. For a MAC-heavy filter the M4's fixed-point SIMD instructions can still win. The honest answer is that float removes a whole class of scaling bugs and is usually right unless measurement says otherwise." },
{ t: "dsp-fixed", d: 3, q: "Why does a 32-bit accumulator help a long fixed-point FIR?", o: ["It is faster", "Rounding once at the end, not after every tap", "It allows more taps", "It avoids saturation happening anywhere at all"], a: 1, why: "That keeps the accumulated error far smaller. Rounding per tap makes the error grow with the number of taps. Accumulating at full width and rounding once is why DSP cores provide guard bits above the natural word size." },
{ t: "dsp-fixed", d: 3, q: "What is the ideal SNR limit set by an N-bit quantiser on a full-scale sine?", o: ["About 3 dB for every bit", "About 6.02N + 1.76 dB", "20N dB", "N squared dB"], a: 1, why: "Each bit halves the step size, which is 6 dB. The 1.76 comes from comparing a sine's RMS to the uniform error distribution, and measured ENOB is always below this because of noise and distortion." },

// ---------------------------------------------------------- dsp-adaptive
{ t: "dsp-adaptive", d: 2, q: "What is the LMS update w += mu * e * x doing, conceptually?", o: ["Averaging the input", "A gradient descent step on the squared error", "A least-squares solve", "Normalising each one of the weights that are involved"], a: 1, why: "It uses the instantaneous gradient as an estimate. The true gradient needs an expectation, so LMS substitutes the current sample. That is why it is cheap and why its convergence is noisy rather than smooth." },
{ t: "dsp-adaptive", d: 2, q: "What happens if mu is set too large?", o: ["Slow convergence", "The weights either diverge or oscillate", "The filter becomes an FIR", "Nothing, it just uses more power"], a: 1, why: "Each step overshoots the minimum. Stability requires mu below roughly 2 over the input power times the filter length. Too small is the opposite failure: stable but too slow to track anything that changes." },
{ t: "dsp-adaptive", d: 2, q: "How does NLMS improve on plain LMS?", o: ["It uses a longer filter", "It divides the step size by the input power", "It computes the exact gradient", "It removes the need for a desired signal"], a: 1, why: "Convergence no longer depends on signal level. With plain LMS a mu tuned for speech at one volume diverges when the level rises. Normalising makes the effective step scale-invariant, which is why it is what actually gets deployed." },
{ t: "dsp-adaptive", d: 2, q: "In an acoustic echo canceller, what does the adaptive filter converge to?", o: ["The near-end speech", "An estimate of the acoustic impulse response", "The noise floor", "The inverse of the room response"], a: 1, why: "That is the loudspeaker-to-microphone path. It models the echo path so the predicted echo can be subtracted. It is why the canceller has to re-converge whenever someone moves or a door opens, and why double-talk detection is needed." },
{ t: "dsp-adaptive", d: 2, q: "Where does the desired signal come from in adaptive noise cancellation?", o: ["A stored reference", "The primary sensor carries signal plus noise", "It is generated entirely internally somewhere instead", "The filter output"], a: 1, why: "A reference sensor carries correlated noise alone. The filter learns to map the reference onto the noise in the primary, and the error output is the cleaned signal. It fails if the reference picks up any of the wanted signal, which cancels it too." },
{ t: "dsp-adaptive", d: 3, q: "What does eigenvalue spread of the input autocorrelation matrix predict?", o: ["The final error", "Convergence speed", "The filter length needed", "Stability only"], a: 1, why: "A large spread means some modes converge far more slowly than others. White input has a spread of one and converges fastest. Strongly coloured input, such as speech, has a large spread, which is the main reason RLS or transform-domain methods are sometimes worth their cost." },
{ t: "dsp-adaptive", d: 3, q: "What does RLS buy over NLMS, and what does it cost?", o: ["Nothing useful", "Much faster convergence", "Lower steady-state error only", "Guaranteed stability"], a: 1, why: "Especially on coloured input, at O(N^2) per sample instead of O(N). RLS solves a running least-squares problem rather than taking a gradient step. The quadratic cost and its numerical fragility in finite precision are why NLMS remains the default in embedded work." },
{ t: "dsp-adaptive", d: 3, q: "What is misadjustment in an adaptive filter?", o: ["A plain coefficient error of some kind or other", "The excess steady-state error from jitter", "A tracking delay", "Divergence"], a: 1, why: "The weights jitter around the optimum, and it is proportional to mu. It is the direct statement of the step-size trade-off: larger mu tracks changes faster and settles noisier. Some designs anneal mu downward once converged to get both." },

// --------------------------------------------------------- dsp-detection
{ t: "dsp-detection", d: 1, q: "What happens when you raise a detector's threshold?", o: ["Both error types fall", "False alarms fall, missed detections rise", "Both error types rise", "Only the noise floor itself ends up changing"], a: 1, why: "There is no setting that reduces both; the threshold only moves along the trade. Which error is worse is a system decision, and it is what the operating point on the ROC encodes." },
{ t: "dsp-detection", d: 2, q: "What does each point on an ROC curve represent?", o: ["A different signal level", "One threshold setting", "A different detector", "One noise realisation"], a: 1, why: "It is plotted as probability of detection against probability of false alarm. The curve is the detector; the point is your choice. Area under the curve summarises the detector independently of threshold, which is why it is the honest way to compare two algorithms." },
{ t: "dsp-detection", d: 2, q: "In what sense is the matched filter optimal?", o: ["It minimises computation", "It maximises output SNR in white noise", "It gives the best time resolution", "It removes all noise"], a: 1, why: "That holds for a known signal shape. Its impulse response is the time-reversed conjugate of the expected signal. It says nothing about resolution or about coloured noise, where a whitening stage is needed first." },
{ t: "dsp-detection", d: 2, q: "How does cell-averaging CFAR set its threshold?", o: ["From a fixed constant", "From the mean of nearby reference cells", "From the peak of the record", "From some prior calibration measurement"], a: 1, why: "The threshold then follows the local noise level. That keeps the false alarm rate constant as the noise floor varies with range or gain. Guard cells either side of the cell under test stop a strong target inflating its own threshold." },
{ t: "dsp-detection", d: 2, q: "What is the failure mode of cell-averaging CFAR?", o: ["It is too slow", "A second strong target in the reference window", "It simply cannot handle any white noise whatsoever", "It needs a matched filter"], a: 1, why: "It raises the threshold and masks the first. This is target masking, and it is why ordered-statistic CFAR exists: taking a percentile of the reference cells rather than the mean makes it robust to a few contaminated cells." },
{ t: "dsp-detection", d: 3, q: "What does the Neyman-Pearson criterion say?", o: ["Minimise total error", "Maximise detection at a fixed false alarm rate", "Weight errors equally", "Always use the matched filter, whatever happens"], a: 1, why: "It uses a likelihood ratio test. It is the formal justification for how detectors are actually specified in radar and sonar: fix the false alarm rate the system can tolerate, then get the best detection you can within it." },
{ t: "dsp-detection", d: 3, q: "Why does coherent averaging of M records improve SNR by 10*log10(M) dB?", o: ["It filters the noise", "Amplitudes add linearly, noise adds in RMS", "It removes DC", "It increases the overall resolution considerably"], a: 1, why: "Noise adds as the square root of M. Amplitude ratio improves as sqrt(M), which is a factor of M in power. It requires the signal to repeat with stable phase, so trigger jitter destroys exactly this gain." },
{ t: "dsp-detection", d: 3, q: "Your detector's ROC is close to the diagonal. What does that mean?", o: ["It is perfectly calibrated", "It is performing at chance", "It has too many false alarms", "The threshold is too high"], a: 1, why: "No threshold choice will help. The diagonal is the coin flip. Tuning is pointless: the fix is more signal, a better feature, or a longer integration, not a different operating point." },

// ------------------------------------------------------------- dsp-phase
{ t: "dsp-phase", d: 2, q: "What does a frequency-dependent group delay do to a pulse?", o: ["The phase at DC", "The negative derivative of phase with frequency", "The total filter delay", "The delay applied to the very first sample alone"], a: 1, why: "It is the delay applied to the envelope at that frequency. Constant group delay means every frequency is delayed equally, so a pulse keeps its shape. Where it varies, the components arrive at different times and the pulse smears." },
{ t: "dsp-phase", d: 2, q: "How does a minimum-phase filter compare with a linear-phase filter of the same magnitude response?", o: ["It has more delay", "Less delay, with energy early in the response", "Otherwise entirely identical behaviour throughout", "It cannot be causal"], a: 1, why: "But the group delay is not constant. Minimum phase is the smallest possible phase lag for that magnitude, which matters in a control loop where delay costs phase margin. Linear phase is what you want when waveform shape must be preserved." },
{ t: "dsp-phase", d: 2, q: "How is the envelope of an RF echo obtained from the analytic signal?", o: ["By squaring it", "The magnitude of the analytic signal", "By low-pass filtering it", "By differentiating the phase instead"], a: 1, why: "The Hilbert transform supplies the quadrature component, and the magnitude of the resulting complex signal is the envelope. The derivative of its phase gives instantaneous frequency instead." },
{ t: "dsp-phase", d: 2, q: "When does phase unwrapping fail?", o: ["At DC only", "When the phase changes by more than pi", "Whenever the signal happens to be a real one", "On short records"], a: 1, why: "The algorithm cannot then tell which way it went. Noise near a null causes the same problem, since the phase there is meaningless and can jump arbitrarily. Denser frequency sampling or a coarse model-based estimate is the usual defence." },
{ t: "dsp-phase", d: 2, q: "What does the Hilbert transform do to a signal?", o: ["Doubles its frequency", "Shifts every component by -90 degrees", "It removes the DC component from it entirely", "Reverses it in time"], a: 1, why: "Magnitudes are left unchanged. Adding j times the result to the original cancels the negative frequencies, giving the one-sided analytic signal. An ideal one is non-causal, so practical versions are FIR approximations with delay." },
{ t: "dsp-phase", d: 3, q: "Why is zero-phase (forward-backward) filtering unavailable in a real-time system?", o: ["It is too slow", "It requires the whole record", "It is numerically unstable", "It only works on FIR filters"], a: 1, why: "The backward pass runs from the end. It also squares the magnitude response, so the design must account for that. In real time you use a linear-phase FIR and accept the constant delay instead." },
{ t: "dsp-phase", d: 3, q: "Why does an all-pass filter exist if it does not change the magnitude response?", o: ["It does not, it is a mathematical curiosity", "It shapes only the phase or the group delay alone", "It improves SNR", "It removes DC"], a: 1, why: "It is used for delay equalisation and in filter banks. Any filter factors into a minimum-phase part and an all-pass part, which is why the two-part description is useful: magnitude and phase can be reasoned about separately." },
{ t: "dsp-phase", d: 3, q: "Measuring time of flight by cross-correlation gives an ambiguous result. What is the likely cause?", o: ["Insufficient averaging", "A narrowband signal", "Wrong sample rate", "A DC offset"], a: 1, why: "Its correlation peak repeats every cycle, so the envelope cannot pick a cycle. The envelope locates the arrival coarsely and the carrier phase refines it, but only if the coarse estimate is within half a cycle. Broader bandwidth, or a chirp, narrows the envelope and removes the ambiguity." },

// ---------------------------------------------------------- dsp-realtime
{ t: "dsp-realtime", d: 1, q: "What buffering delay does a 256-sample block at 48 kHz add?", o: ["About 0.5 ms", "About 5.3 ms", "About 21 ms", "About 256 ms"], a: 1, why: "256 divided by 48000 is 5.33 ms, and that is only the input block. A double-buffered pipeline typically costs about twice that end to end before any algorithmic delay." },
{ t: "dsp-realtime", d: 2, q: "Why do overlap-add and overlap-save exist?", o: ["To reduce latency", "To apply FFT convolution to a continuous stream", "To avoid windowing", "To improve the frequency resolution that is obtained"], a: 1, why: "A finite FFT implies circular rather than linear convolution. Without them the tail of each block wraps around and corrupts the start. Overlap-add keeps and sums the tails; overlap-save discards the corrupted region and keeps the valid part." },
{ t: "dsp-realtime", d: 2, q: "What is the hard real-time contract in a double-buffered DMA scheme?", o: ["Average processing time under the block period", "Worst-case processing of one block must beat the fill", "Interrupts must be disabled", "Buffers must be a power of two"], a: 1, why: "It must finish before the other buffer fills. Meeting it on average is not meeting it: one late block means the DMA overwrites data you have not read. That is why the budget is worst case and why the margin is worth measuring." },
{ t: "dsp-realtime", d: 2, q: "What should real-time capacity be budgeted against?", o: ["Average load", "Worst-case load", "Typical load plus 10 percent", "Measured peak over one minute"], a: 1, why: "That includes the most expensive branch and any interrupt that can preempt. The expensive path is often rare, such as a resync, a recalibration or a full-table update. Averaging hides exactly the case that breaks the system." },
{ t: "dsp-realtime", d: 2, q: "Why should the DSP block never call malloc?", o: ["It is too slow only", "Its timing is unbounded", "It is not thread safe", "It simply uses too much flash"], a: 1, why: "It can also fail after fragmentation, so it breaks the worst-case guarantee. Allocate everything before the stream starts. The same reasoning bans unbounded loops, blocking I/O and printf from the processing path." },
{ t: "dsp-realtime", d: 3, q: "What is the trade when you shorten the block size?", o: ["Nothing, shorter is better", "Lower latency but higher per-sample overhead", "Better frequency resolution", "Less memory used, but rather more latency as well"], a: 1, why: "Fixed per-block costs are amortised over fewer samples. Interrupt entry, cache effects and FFT setup are all per block. Latency-critical work uses short blocks and pays for it; throughput-critical work uses long ones." },
{ t: "dsp-realtime", d: 3, q: "How would you measure a DSP loop's true worst-case execution time on a microcontroller?", o: ["Average a printf timestamp", "Toggle a GPIO and watch the widest pulse", "Count instructions in the source", "Use the debugger's step timer"], a: 1, why: "Watch it on a scope over a long run with realistic input. A GPIO and a scope cost nothing and perturb nothing, and the scope's infinite-persistence mode shows the tail directly. A cycle counter read into a running maximum works too." },
{ t: "dsp-realtime", d: 3, q: "Processing occasionally overruns by a few percent. What is the correct response?", o: ["Increase the buffer size to hide it", "Find and then bound the worst-case path", "Raise the task priority", "Reduce the sample rate"], a: 1, why: "A bigger buffer only delays the failure and adds latency. If the average load exceeds capacity, no buffer is large enough. If it is a rare spike, the buffer buys time but you still need to know what the spike is before trusting it." }

]);
