BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// ---------------------------------------------------------- emb-fsm
{ t: "emb-fsm", d: 1, q: "Why is a named state enum better than four boolean flags?", o: ["It uses less RAM than four separate flags", "Sixteen combinations, most illegal, none named", "Enums compare faster than four booleans", "Flags cannot be tested in a switch"], a: 1, why: "The enum makes only legal states representable. Every extra flag doubles a combination space nobody has enumerated or documented." },
{ t: "emb-fsm", d: 2, q: "What should the default case of a state switch do?", o: ["Nothing at all: the value cannot occur", "Treat the impossible value as a fault", "Return to the previous known state", "Retry the event in the same state"], a: 1, why: "Reaching an unlisted state means memory was corrupted or a state was added without handling it. Both should be loud rather than silently ignored." },
{ t: "emb-fsm", d: 2, q: "What property can you check on a table-driven machine that you cannot check on a switch?", o: ["How fast the machine executes a single step", "That every state is reachable, none dead", "How much stack the handlers consume", "The interrupt latency of a transition"], a: 1, why: "The table is data, so a test can walk it. A switch spread across a function only tells you about the transitions you happen to read." },
{ t: "emb-fsm", d: 2, q: "Where should the state variable be assigned?", o: ["Wherever convenient", "In one place only", "In the ISR", "In every handler"], a: 1, why: "Scattered assignments recreate the problem the machine was meant to solve: you can no longer say what causes a transition." },
{ t: "emb-fsm", d: 2, q: "Why do explicit state machines test well without hardware?", o: ["They are small enough to read entirely", "Feed events, assert state and actions", "They avoid interrupts altogether", "They use no RAM worth speaking of"], a: 1, why: "Same argument as an injected transport: pushing logic behind a plain function boundary makes it exercisable on a host." },
{ t: "emb-fsm", d: 1, q: "Why should state machine actions be non-blocking?", o: ["Blocking costs power while it waits", "A machine that blocks stops responding", "The compiler requires a return path", "It reduces the flash the machine occupies"], a: 1, why: "Blocking inside a transition means events queue up or are lost, and the machine's behaviour becomes timing-dependent rather than event-driven." },
{ t: "emb-fsm", d: 3, q: "What does a hierarchical state machine give you?", o: ["Transitions dispatch faster than flat", "A parent holds behaviour common to children", "It needs fewer states overall", "It generates its own tests automatically"], a: 1, why: "Useful when many states respond identically to something like a reset event. Usually overkill below about a dozen states." },
{ t: "emb-fsm", d: 2, q: "An event arrives that the current state does not expect. What is the right handling?", o: ["Always ignore it and stay where you are", "Always treat it as a hard fault", "Decide per state, and write it down", "Queue it and replay it on the next event"], a: 2, why: "Silence is a decision you did not make. Being explicit is what stops an unexpected event producing undefined behaviour later." },
{ t: "emb-fsm", d: 3, q: "Why place the transition table in flash as const?", o: ["It dispatches faster when it is held in flash", "No RAM cost, and it cannot be corrupted", "C requires a table to be const", "It guarantees the table's alignment"], a: 1, why: "The machine's definition is not data that should ever change, so putting it in .rodata saves RAM and removes a class of corruption." },
{ t: "emb-fsm", d: 2, q: "Where do entry and exit actions belong?", o: ["At every call site causing the transition", "Inside the state machine", "In the ISR", "In main"], a: 1, why: "Scattering them means a new transition can forget one. Keeping them in the machine makes them a property of the state rather than of the caller." },

// ---------------------------------------------------------- emb-fixedpoint
{ t: "emb-fixedpoint", d: 1, q: "What does Q16.16 mean?", o: ["16-bit integers, no fraction at all", "16 integer bits, 16 fractional bits", "16 discrete values per whole unit", "A 16-byte fixed-point type"], a: 1, why: "The binary point is implicit and agreed by convention. In an int32_t that gives roughly plus or minus 32768 with a resolution near 0.000015." },
{ t: "emb-fixedpoint", d: 2, q: "You multiply two Q16.16 values in int32_t. What goes wrong?", o: ["Nothing: the result is still Q16.16", "The intermediate is Q32.32 and overflows", "The result comes out as Q32.16", "The sign bit is lost in the shift"], a: 1, why: "Two values with 16 fractional bits each give 32 fractional bits. Widen, multiply, then shift right by Q to return to the original format." },
{ t: "emb-fixedpoint", d: 2, q: "Why add (1 << (Q-1)) before the final right shift?", o: ["To stop the shift from overflowing", "To round to nearest, not truncate", "To preserve the sign through the shift", "The standard requires it for shifts"], a: 1, why: "Truncation always rounds towards negative infinity, and in a filter or integrator that bias accumulates into a visible offset." },
{ t: "emb-fixedpoint", d: 2, q: "Why saturate rather than wrap a motor command?", o: ["Saturating is faster than wrapping round", "Wrapping turns full forward into reverse", "It generates less code than a wrap", "Wrapping a signed value is undefined behaviour"], a: 1, why: "Clamping degrades gracefully at the limit. Wrapping produces a large value of the opposite sign, which for an actuator is a safety issue." },
{ t: "emb-fixedpoint", d: 3, q: "When is fixed point the wrong choice?", o: ["Whenever numerical precision genuinely matters", "On a part with an FPU and no hard timing", "Inside any kind of control loop", "When reading and scaling sensors"], a: 1, why: "Floats are simpler and less error-prone where supported. Reaching for fixed point by habit adds risk for no benefit." },
{ t: "emb-fixedpoint", d: 2, q: "Why is the order (a * b) >> Q rather than (a >> Q) * b?", o: ["The first form is faster to execute", "Shifting first discards the precision", "The second form can overflow instead", "They are equivalent for unsigned types"], a: 1, why: "Multiply before you divide or shift, to preserve significant bits, but widen the intermediate first so the multiply itself cannot overflow." },
{ t: "emb-fixedpoint", d: 3, q: "Why is right-shifting a negative signed value a caution in older C standards?", o: ["It is undefined behaviour in both C99 and C11", "Implementation-defined, not undefined", "It rounds up rather than toward zero", "It always produces zero for negatives"], a: 1, why: "If it matters for portability, use a division or cast explicitly rather than relying on the near-universal behaviour." },
{ t: "emb-fixedpoint", d: 2, q: "How should a fixed-point variable be named?", o: ["Whatever name is shortest to type", "With its Q format, such as angle_q16", "With the units, such as angle_deg", "By its C type, such as angle_i32"], a: 1, why: "The scaling is invisible in the type, so it has to live in the name or a reader cannot know what the number means." },
{ t: "emb-fixedpoint", d: 3, q: "Best way to validate a fixed-point implementation?", o: ["Inspect the code and check every shift by hand", "Host test against double over the range", "Test it on the target hardware", "Trust the maths and move on"], a: 1, why: "The failure is usually an intermediate overflowing on a specific input, which inspection misses and a sweep across the range finds." },
{ t: "emb-fixedpoint", d: 1, q: "Why does fixed point help interrupt latency on some parts?", o: ["Integer operations are simply faster", "Using the FPU in an ISR means saving it", "It uses less stack in the handler", "Interrupts cannot use floats at all"], a: 1, why: "FPU context is additional state that must be preserved on entry, which adds cycles to every interrupt that touches it." },

// ---------------------------------------------------------- emb-bootloader
{ t: "emb-bootloader", d: 2, q: "What is the main argument for A/B slots?", o: ["Writes go faster into a completely unused slot", "No window where a power cut bricks it", "It uses less flash than one slot", "No CRC is needed on either image"], a: 1, why: "The running image is untouched until the new one is complete and verified. Erasing in place has an interval where a power cut is fatal." },
{ t: "emb-bootloader", d: 3, q: "Why must the bootloader set the vector table offset before jumping to the application?", o: ["Interrupts stay disabled without setting it", "Interrupts dispatch into the bootloader", "The stack pointer is not relocated", "It is optional on Cortex-M parts"], a: 1, why: "The vector table base determines where the core finds every exception handler, and getting it wrong produces bewildering faults much later." },
{ t: "emb-bootloader", d: 2, q: "A CRC over an image proves what?", o: ["Authenticity of the image's origin", "Integrity only, nothing about origin", "Compatibility with this hardware", "That the image will actually boot"], a: 1, why: "An attacker can recompute a CRC. Rejecting firmware you did not produce needs a signature, which is a different mechanism entirely." },
{ t: "emb-bootloader", d: 3, q: "Why mark a new image pending and require the application to confirm itself?", o: ["It saves an entire flash sector of storage", "An intact but broken image rolls back", "It makes the boot measurably faster", "It is how the version is recorded"], a: 1, why: "Integrity checks catch corruption, not bugs. Confirmation turns a bad update into a self-healing event rather than a field failure." },
{ t: "emb-bootloader", d: 3, q: "Anti-rollback and rollback protection conflict. Why?", o: ["They do not conflict in practice", "One blocks downgrade, the other allows it", "Both need one-time programmable fuses", "They share the same version counter"], a: 1, why: "A monotonic version counter that blocks reinstating a vulnerable image also blocks reverting a broken one, so the policy has to be reconciled deliberately." },
{ t: "emb-bootloader", d: 2, q: "What should the bootloader do before jumping to the application?", o: ["Nothing at all beyond setting the stack", "Deinit peripherals, disable interrupts", "Erase its own sector to save flash", "Enable the watchdog for the app"], a: 1, why: "The application initialises from whatever it inherits, so undocumented leftover configuration produces faults that look like application bugs." },
{ t: "emb-bootloader", d: 2, q: "Why is updating the bootloader itself in the field risky?", o: ["It is large and takes several sectors", "It is the one step with no safety net", "It needs a signature the app lacks", "Flash writes are slow at that size"], a: 1, why: "Everything else can fall back to the bootloader. If the bootloader is half-written there is nothing left to recover with." },
{ t: "emb-bootloader", d: 2, q: "Why include a hardware revision field in the image header?", o: ["It is useful for gathering fleet statistics", "A wrong-variant image refuses to run", "It speeds up the verification step", "It is included in the CRC coverage"], a: 1, why: "Half working is the dangerous outcome, because it passes casual testing and fails in the field in ways nobody connects to the wrong image." },
{ t: "emb-bootloader", d: 3, q: "Why re-verify the image hash on every boot rather than only after writing?", o: ["The check is essentially free anyway", "Flash bits degrade, so validity expires", "The bootloader itself may have changed", "It gives something to log at boot"], a: 1, why: "Retention is finite, particularly at temperature. Checking once at write time proves nothing about a device three years later." },
{ t: "emb-bootloader", d: 2, q: "Why must the partition table and linker script agree?", o: ["The build simply fails if they disagree", "Two descriptions of one layout, drifting", "One is generated from the other", "It only matters for OTA updates"], a: 1, why: "Nothing checks them against each other by default, and disagreement produces an image that flashes cleanly and boots into the wrong place." },

// ---------------------------------------------------------- emb-flash
{ t: "emb-flash", d: 1, q: "Why can you not simply overwrite a byte in flash?", o: ["Flash is read-only once programmed", "Writes clear bits; only erase sets them", "It needs a special unlock instruction", "The address range is write-protected"], a: 1, why: "That asymmetry sets erase granularity at a sector and is exactly what log-structured storage exploits by only ever appending." },
{ t: "emb-flash", d: 2, q: "Typical flash endurance is measured in:", o: ["In total bytes written over its life", "Erase cycles per sector, 10k to 100k", "In years of guaranteed data retention", "In power cycles of the whole part"], a: 1, why: "It is per sector rather than per device, which is why a scheme that hammers one sector kills the product while the rest of the flash is untouched." },
{ t: "emb-flash", d: 2, q: "A settings save erases then writes a sector every minute. Name both failures.", o: ["It is slow and it uses a lot of RAM", "It wears out in weeks, and can lose all", "It corrupts RAM and is slow to run", "The write cannot safely be interrupted"], a: 1, why: "At 100,000 cycles a per-minute erase exhausts the sector in about ten weeks, and there is an interval where neither old nor new settings exist." },
{ t: "emb-flash", d: 2, q: "How does a log-structured store improve endurance?", o: ["It compresses each record before writing it", "Appends, erasing only when the sector fills", "It buffers all the writes in RAM until shutdown", "It uses a part with smaller sectors"], a: 1, why: "Erases become rare rather than per-save, and the previous record survives until compaction so there is never a moment with no valid copy." },
{ t: "emb-flash", d: 3, q: "Why write the data before the validity marker?", o: ["Writing the marker first is slower", "A record with no marker is ignored", "Markers must come last in a flash page", "It keeps the record correctly aligned"], a: 1, why: "Ordering is what makes the scheme power-fail safe: the record only becomes visible at the instant it is known to be complete." },
{ t: "emb-flash", d: 2, q: "Why might a time-critical ISR need to live in RAM?", o: ["RAM is faster to fetch from than flash", "Flash erase can stall instruction fetch", "Interrupts cannot be serviced from flash", "It saves power on the flash controller"], a: 1, why: "A handler in flash simply cannot execute while the controller is busy, so latency guarantees are void during any settings write or update." },
{ t: "emb-flash", d: 3, q: "What can a power loss during an erase leave behind?", o: ["The old data, left completely intact", "A sector reading neither old data nor 0xFF", "A cleanly blank sector, all 0xFF", "Nothing unusual: erase is atomic"], a: 1, why: "Design assuming it happens: the recovery logic must cope with a sector in an indeterminate state rather than only with clean old or clean new." },
{ t: "emb-flash", d: 2, q: "Why read back and verify after a flash write?", o: ["To measure how fast the write actually was", "A write can fail silently on a worn sector", "The flash standard requires a verify", "It flushes the flash controller's write cache"], a: 1, why: "Endurance degrades gradually rather than all at once, so late-life writes can partially fail with no error reported by the controller." },
{ t: "emb-flash", d: 2, q: "What is wear levelling?", o: ["Compressing data so less is written", "Spreading writes so no sector leads", "Verifying every write after the fact", "Erasing sectors in the background"], a: 1, why: "Without it, a hot record concentrates every erase on one sector, which dies long before the rest of the device is exhausted." },
{ t: "emb-flash", d: 1, q: "Why prefer LittleFS or an NVS over writing your own store?", o: ["They are faster than a hand-rolled store", "The power-fail modes only appear months in", "They occupy less flash than your own", "Certification requires a named filesystem"], a: 1, why: "Every one of these schemes looks correct on a bench. The difference shows up in a fleet, which is exactly when you cannot fix it cheaply." },

// ---------------------------------------------------------- emb-debugarch
{ t: "emb-debugarch", d: 1, q: "What is SWD?", o: ["A trace protocol for instruction flow", "ARM's two-wire debug: clock and data", "A UART-based bootloader protocol", "A standalone flash programmer tool"], a: 1, why: "It replaces the wider JTAG interface and matters when pins are scarce, while offering the same halt, step, breakpoint and memory access facilities." },
{ t: "emb-debugarch", d: 2, q: "Why are hardware breakpoints limited in number?", o: ["The debug probe's licence limits the count", "A comparator unit in silicon, about six", "The flash size caps how many fit", "The SWD protocol allows only four"], a: 1, why: "Software breakpoints have no such limit but work by replacing an instruction, so they only apply to code in RAM." },
{ t: "emb-debugarch", d: 2, q: "You need to find what corrupts a variable. Which tool?", o: ["printf on every write", "A data watchpoint", "A logic analyser", "More tests"], a: 1, why: "A watchpoint halts on access to that address and names the offending code immediately, rather than requiring you to instrument every candidate." },
{ t: "emb-debugarch", d: 2, q: "Why is ITM better than printf for real-time debugging?", o: ["It produces considerably more output", "A stimulus port write costs a few cycles", "It needs no debug probe attached", "It is easier to set up than a UART"], a: 1, why: "A UART printf takes long enough to change behaviour, which is why faults often vanish the moment you instrument them." },
{ t: "emb-debugarch", d: 2, q: "What does the DWT cycle counter give you?", o: ["A full instruction trace of the core", "A free-running cycle count", "Hardware watchpoints on addresses", "The timing of each flash access"], a: 1, why: "Repeatable, high resolution and available without external tooling, which makes it the default for measuring worst-case execution time." },
{ t: "emb-debugarch", d: 3, q: "What does ETM provide that ITM does not?", o: ["Noticeably lower runtime overhead", "A record of the actual instruction stream", "More stimulus ports to write to", "The ability to program flash too"], a: 1, why: "ITM is instrumentation you insert. ETM records execution itself, which is what you want when the fault leaves no clue behind." },
{ t: "emb-debugarch", d: 1, q: "Cheapest timing measurement available on any part?", o: ["The ETM instruction trace unit on the part", "Toggle a spare GPIO, watch it on a scope", "printf with a timestamp on each line", "A cycle-accurate instruction simulator"], a: 1, why: "Sub-microsecond resolution, no tooling, and it shows jitter as well as duration, which is often the number that actually matters." },
{ t: "emb-debugarch", d: 2, q: "Why can a low-power mode drop the debug connection?", o: ["The probe times out and disconnects", "The debug block is clocked too", "SWD stops working below about 2 V", "The instruction cache is disabled"], a: 1, why: "Without that bit, entering sleep looks exactly like a crash or a broken probe, which wastes a lot of time during low-power bring-up." },
{ t: "emb-debugarch", d: 2, q: "Why do watchdogs need to freeze on halt?", o: ["They do not need to; it keeps counting", "It fires while you sit at a breakpoint", "To save power while the core is stopped", "To keep the RTOS tick count accurate"], a: 1, why: "It is usually one configuration bit, and without it every debugging session ends in a reset a few seconds after you halt." },
{ t: "emb-debugarch", d: 2, q: "Why use -Og rather than -O2 while debugging?", o: ["It compiles a great deal faster than -O2 does", "Optimised, but line order stays sensible", "It turns most warnings off for speed", "It removes the need for volatile"], a: 1, why: "-O2 inlines and reorders so the debugger shows a sequence that did not happen, while -O0 may hide the fault entirely." },

// ---------------------------------------------------------- emb-realtime
{ t: "emb-realtime", d: 1, q: "What does hard real time mean?", o: ["The system runs very fast indeed", "A missed deadline is a system failure", "The critical path is in assembly", "Timing is precise to the nanosecond"], a: 1, why: "It is about consequence rather than speed. A slow system with a guaranteed deadline is hard real time; a fast one with no guarantee is not." },
{ t: "emb-realtime", d: 2, q: "Why does a long critical section in one module break timing elsewhere?", o: ["It consumes more CPU time overall", "Interrupts off adds to every latency", "It fragments the heap while it holds", "It temporarily changes task priority"], a: 1, why: "Interrupt latency is a global property, so a well-meaning module that masks interrupts for 200 microseconds has spent everyone else's budget." },
{ t: "emb-realtime", d: 2, q: "Under rate monotonic scheduling, which task gets the highest priority?", o: ["Whichever task is judged most important", "The one with the shortest period", "The one that runs the longest", "The one created first at startup"], a: 1, why: "Priority follows frequency rather than perceived importance, and this is provably optimal among fixed-priority policies for independent periodic tasks." },
{ t: "emb-realtime", d: 3, q: "The classic rate monotonic utilisation bound is approximately:", o: ["50%", "69%", "85%", "100%"], a: 1, why: "Below about 69 per cent a set of independent periodic tasks is guaranteed schedulable. Above it you may still be fine, but you must analyse rather than assume." },
{ t: "emb-realtime", d: 2, q: "Why measure worst-case rather than average execution time?", o: ["The worst case is much easier to measure", "A deadline is missed by the worst case", "Averages are unreliable on a cache", "The worst case is faster to compute"], a: 1, why: "Meeting a deadline on average means missing it regularly, and the measurement has to be made under worst-case conditions to mean anything." },
{ t: "emb-realtime", d: 2, q: "Which conditions define a worst-case timing measurement?", o: ["An idle system with a warm cache", "Cold cache, all branches, flash busy", "With the debugger attached and halted", "At the lowest supported clock speed"], a: 1, why: "Measuring on an idle bench gives you a number that has no relationship to the situation in which the deadline will actually be missed." },
{ t: "emb-realtime", d: 3, q: "Which two things break rate monotonic analysis?", o: ["Too many tasks and too little RAM", "Priority inversion and unbounded work", "Interrupts and DMA stealing cycles", "Caches and pipelines making it vary"], a: 1, why: "Both make a task's effective duration unpredictable: inversion by blocking on a lower priority holder, unbounded work by depending on data." },
{ t: "emb-realtime", d: 2, q: "Why does jitter often matter more than latency in a control loop?", o: ["Jitter is usually the larger of the two", "A varying interval corrupts the maths", "Jitter is much easier to measure", "Jitter dominates the power budget"], a: 1, why: "Most control algorithms assume a fixed timestep. A consistent delay can be compensated; a varying one cannot." },
{ t: "emb-realtime", d: 2, q: "Why is dynamic allocation banned on real-time paths?", o: ["It uses RAM you have not budgeted", "Allocation time is not bounded", "The allocator is not reentrant", "It fragments flash as well as RAM"], a: 1, why: "The allocator may walk free lists or coalesce blocks, so the worst case is unpredictable and cannot be included in a timing analysis." },
{ t: "emb-realtime", d: 3, q: "Why expose the maximum observed execution time as a counter?", o: ["It is useful for benchmarking runs", "Creeping degradation becomes visible", "It can be used to trip the watchdog", "Certification bodies require it"], a: 1, why: "Timing regressions arrive gradually as features are added. A visible maximum turns that into an observation rather than an eventual field failure." },

// ---------------------------------------------------------- emb-dma
{ t: "emb-dma", d: 1, q: "What is the main reason DMA helps a battery device?", o: ["The application code itself executes faster", "The core can sleep during the transfer", "It uses less RAM than a copy loop", "It makes the drivers simpler to write"], a: 1, why: "Active current dominates the average on most battery products, so anything that lets the CPU stay asleep during data movement is a direct win." },
{ t: "emb-dma", d: 2, q: "What does marking a DMA buffer volatile actually fix?", o: ["Cache coherency between core and DMA", "The compiler caching it in a register", "The write buffer draining too late", "Every coherency problem there is"], a: 1, why: "volatile is an instruction to the compiler. It has no effect on a data cache or a write buffer, which is why 'DMA means volatile' is the wrong model." },
{ t: "emb-dma", d: 2, q: "Why must a DMA buffer not be a local variable?", o: ["Locals cannot be aligned correctly", "The transfer outlives the stack frame", "The task stack is generally too small", "DMA cannot address the stack region"], a: 1, why: "The controller writes into that memory after the function has returned, by which point the frame belongs to something else entirely." },
{ t: "emb-dma", d: 3, q: "Why does a DMA buffer often need cache-line alignment?", o: ["It makes the transfer measurably faster", "Invalidating a line destroys its neighbours", "The DMA controller requires the alignment", "It reduces the power the transfer costs"], a: 1, why: "Cache maintenance works on whole lines, so a buffer sharing a line with other data discards that neighbour's cached value when you invalidate." },
{ t: "emb-dma", d: 2, q: "What is circular mode with half and full interrupts used for?", o: ["Detecting an error partway through", "Process one half as hardware fills the other", "Halving the number of interrupts that are taken", "Keeping transfers aligned to the buffer"], a: 1, why: "It is how continuous audio and ADC streams are handled, and it removes the possibility of missing a sample between transfers." },
{ t: "emb-dma", d: 3, q: "In circular mode, what happens if your processing is too slow?", o: ["An overrun interrupt fires to warn you", "Hardware overwrites unread data, silently", "The transfer stops and flags an error", "The buffer grows to hold the backlog"], a: 1, why: "There is no protection by default, which is why you instrument the margin rather than assuming the processing finishes in time." },
{ t: "emb-dma", d: 2, q: "Data is wrong until you add a printf, then correct. What does that suggest?", o: ["A compiler bug in the optimiser", "Coherency or timing: the delay helps", "A stack overflow that printf masks", "The wrong DMA channel is configured"], a: 1, why: "Any fault that disappears when the code is slowed down is timing-related, and with DMA the usual cause is a missing invalidate or barrier." },
{ t: "emb-dma", d: 2, q: "The first DMA transfer works and later ones do not. Most likely cause?", o: ["The buffer alignment is wrong for it", "The completion flag is not cleared", "A cache coherency problem on reload", "The buffer is too small for the data"], a: 1, why: "A latched completion condition prevents the next request being serviced, which looks like the controller having stopped working." },
{ t: "emb-dma", d: 3, q: "Why does disabling interrupts not protect a buffer from DMA?", o: ["It does protect it, if done properly", "DMA moves data without the CPU", "Those interrupts are not maskable", "DMA runs at a higher bus priority"], a: 1, why: "It is a genuine second master. Coordination needs the completion mechanism plus barriers and cache maintenance, not interrupt masking." },
{ t: "emb-dma", d: 2, q: "Before letting DMA read a buffer you have written, what may be required?", o: ["A cache invalidate of the region", "A cache clean, so writes reach memory", "Nothing: the write buffer handles it", "A memory barrier and nothing more"], a: 1, why: "Clean pushes dirty cache lines out to memory for DMA to read; invalidate discards stale lines so the CPU re-reads what DMA wrote. The two directions need different operations." },

// ---------------------------------------------------------- emb-crc
{ t: "emb-crc", d: 1, q: "What does a CRC compute?", o: ["A running sum of all the bytes", "A division remainder, XOR for subtract", "A cryptographic hash of the data", "A count of the set bits in the data"], a: 1, why: "<p>The message is treated as one enormous binary number and divided by a fixed constant, the polynomial. The CRC is what is left over.</p><p>XOR replaces subtraction because binary arithmetic without carries is what hardware can do in a single gate, which is why the whole thing reduces to a shift register and a conditional XOR.</p><p>Everything else in a CRC specification is bookkeeping about which conventions the two ends agreed to.</p>" },
{ t: "emb-crc", d: 2, q: "In the bitwise algorithm, where does each byte enter the register?", o: ["The bottom eight bits", "The top eight bits", "It is added, not XORed", "It replaces the register"], a: 1, why: "<p><code>crc ^= (uint16_t)data[i] &lt;&lt; 8;</code> puts the byte into the top half of a 16-bit register.</p><p>That is what makes this a division worked from the most significant end downward, the same direction as long division on paper. The inner loop then tests the top bit, shifts left, and XORs the polynomial when that bit was set.</p><p>Reflected variants such as CRC-32 do the mirror image: the byte enters at the bottom, the loop tests bit 0 and shifts right. Which one you have is one of the parameters that must be agreed.</p>" },
{ t: "emb-crc", d: 2, q: "What is a CRC's published check value?", o: ["The polynomial, written out in hex", "The CRC of the string 123456789", "The register's documented initial value", "The value XORed in at the end"], a: 1, why: "<p>Every CRC in the catalogue publishes the result of running it over 123456789. CRC-16/CCITT-FALSE gives 0x29B1, CRC-32 gives 0xCBF43926.</p><p>Running your implementation against it tells you immediately whether every parameter matches, because getting any one of them wrong changes the answer.</p><p>It should be the first unit test you write, before any protocol code, and it needs no hardware so it runs on a host on every commit.</p>" },
{ t: "emb-crc", d: 3, q: "You append the CRC to a frame, then run the CRC over the whole frame including those bytes. What do you get?", o: ["The CRC again", "Zero", "The init value", "It is not meaningful"], a: 1, why: "<p>Zero. Appending the remainder makes the whole number exactly divisible, so the new remainder is zero.</p><p>That turns the receive check into one line, <code>if (crc16(frame, len) != 0) reject();</code>, which works for any frame length with no separate comparison and no chance of comparing the wrong bytes.</p><p>It depends on appending the CRC in the byte order the algorithm expects, which for a most-significant-first variant means high byte first. Get that backwards and the result is not zero.</p>" },
{ t: "emb-crc", d: 2, q: "Two implementations share a polynomial and disagree on the answer. Which list covers the likely causes?", o: ["Endianness and the compiler version", "Init, reflection, final XOR, coverage", "The clock speed and the buffer size", "The optimisation level of the build"], a: 1, why: "<p>A CRC is defined by six things, not one: width, polynomial, init, reflection, final XOR, and coverage.</p><p>Coverage is the one most often left undocumented, and it is not part of the algorithm at all. Does the CRC include the header? The length field? The start delimiter? Two correct implementations of the same algorithm will still disagree if they answer that differently.</p><p>Write all six into the protocol document, and add one worked example frame in hex with its CRC. That example settles more integration arguments than any amount of prose.</p>" },
{ t: "emb-crc", d: 2, q: "A checksum and a CRC are both 16 bits. Why is the CRC stronger?", o: ["The CRC is faster to compute in software", "A sum is blind to reordering", "The CRC is shorter on the wire", "The CRC authenticates the sender"], a: 1, why: "<p>Addition is commutative, so swapping two bytes leaves the sum unchanged. A whole class of real errors is therefore invisible to it.</p><p>A CRC is chosen so that the error patterns physical layers actually produce, particularly bursts, are guaranteed detectable up to a known length. For the same field width the detection is far better.</p><p>Nor is it slower in any way that matters: a table makes it one operation per byte, and most parts have a hardware CRC unit that does a word at a time.</p>" },
{ t: "emb-crc", d: 3, q: "Does keeping your CRC polynomial secret give you security?", o: ["Yes, it works as a kind of shared key", "No: it is recoverable from a few pairs", "Only for CRC-32, which is long", "Only if the init value is secret too"], a: 1, why: "<p>The polynomial is not a key and a CRC is not a keyed function. A handful of known message and CRC pairs is enough to solve for it.</p><p>More fundamentally, an attacker who can modify a message can recompute any keyless check over the modified message, producing something indistinguishable from a valid frame.</p><p>Integrity against an adversary needs an HMAC, or a signature where the receiver verifies origin without holding the secret. This is exactly the difference between a bootloader checking a CRC, which catches a corrupted download, and verifying a signature, which refuses firmware you did not produce.</p>" },
{ t: "emb-crc", d: 2, q: "How does the table-driven version relate to the bitwise one?", o: ["It uses a slightly different polynomial internally", "The table holds the inner loop's result", "It is a fast approximation of it", "It only works for CRC-32 variants"], a: 1, why: "<p>Each of the 256 entries is what the bitwise inner loop produces for that byte value. The main loop then does one table lookup per byte instead of eight iterations.</p><p>So the bitwise version remains the definition, and it is what generates the table. That is worth knowing because it means you can always fall back to the slow version to check the fast one.</p><p>The cost is 512 bytes for a 16-bit CRC. Declare the table const so it lives in flash rather than consuming RAM.</p>" },
{ t: "emb-crc", d: 1, q: "What should you check before writing any CRC code at all?", o: ["Which compiler version is in use", "Whether the part has a CRC peripheral", "How much stack the routine needs", "Which optimisation level is set"], a: 1, why: "<p>Most STM32s and the ESP32 have one. It reduces the whole thing to a register write per word, with no table and no loop.</p><p>The catch is that a hardware unit implements one specific parameter set, often CRC-32 with a fixed polynomial, and some parts have quirks about reflection and word ordering. So check that it matches the protocol you have to speak before committing to it.</p><p>Keep the software version anyway as the reference your host tests run against, since the peripheral cannot be exercised off-target.</p>" },
{ t: "emb-crc", d: 3, q: "Why is the coverage question separate from the other five CRC parameters?", o: ["It is not; there are six parameters", "Five define the algorithm; coverage is yours", "Coverage only matters for CRC-32", "Coverage is fixed by the hardware unit"], a: 1, why: "<p>Width, polynomial, init, reflection and final XOR are properties of the algorithm, and looking up a catalogue entry pins all five at once.</p><p>Coverage is a property of your protocol. Whether the CRC includes the start delimiter, the header, or the length field is a decision only your specification can record, and no amount of naming the algorithm communicates it.</p><p>That is why it is the parameter most likely to be missing from a document and most likely to cost a day during integration. Stating it plainly, and giving a worked example frame, costs two lines.</p>" }

]);
