// Questions for the nine CS & Maths lessons that had none.
BANKS["CS & Maths"] = BANKS["CS & Maths"].concat([

// -------------------------------------------------------------- cm-hash
{ t: "cm-hash", d: 2, q: "A hash map's load factor is 0.9 and rising. What is the main risk?", o: ["Memory exhaustion", "Collisions rise sharply, so lookups degrade towards a linear scan of a bucket", "Hash values collide by definition", "Iteration order changes"], a: 1, why: "The average probe length grows steeply as the table fills, particularly with open addressing where clustering compounds it. Most implementations rehash around 0.7 to 0.75 for exactly this reason." },
{ t: "cm-hash", d: 2, q: "What does amortised O(1) insertion actually promise?", o: ["Every insertion is constant time", "The average over a long sequence is constant, but individual insertions can be O(n) when the table rehashes", "It is constant on average inputs", "Constant time after warm-up"], a: 1, why: "The guarantee is about the total, not about any single operation. That distinction is exactly why it is unacceptable inside a hard real-time loop, where the worst case is what matters." },
{ t: "cm-hash", d: 2, q: "You look up one of 16 fixed channel names in a tight acquisition loop. What is fastest in practice?", o: ["A std::unordered_map", "A small array of strings scanned linearly, or better, an enum index computed once outside the loop", "A std::map", "A perfect hash"], a: 1, why: "Sixteen contiguous entries fit in a couple of cache lines, while a hash map costs a hash, an indirection and a probable cache miss. Better still, resolve the name to an index once at setup and never do it in the loop." },
{ t: "cm-hash", d: 2, q: "How do you avoid a rehash latency spike during a timed acquisition run?", o: ["Use a smaller load factor threshold", "Reserve the final capacity before the run starts", "Use a std::map instead", "Disable rehashing"], a: 1, why: "reserve does the allocation and rehashing up front, so the timed section never pays for growth. The same argument applies to vector, and it is the standard fix for latency spikes in real-time code." },
{ t: "cm-hash", d: 2, q: "When does a hash map's O(1) lose to a vector's O(n)?", o: ["Never", "At small n, where the constant factors of hashing and pointer chasing exceed a cache-friendly linear scan", "Only with bad hash functions", "Only for string keys"], a: 1, why: "The crossover is often surprisingly high, in the tens or low hundreds of elements. Big-O describes growth, not cost, and it deliberately hides the constant that dominates at small sizes." },
{ t: "cm-hash", d: 3, q: "What is the difference between separate chaining and open addressing?", o: ["Only the hash function", "Chaining stores collisions in a per-bucket list; open addressing probes for another slot in the same array", "Chaining is always faster", "Open addressing cannot resize"], a: 1, why: "Open addressing has better cache behaviour because everything lives in one array, but it degrades faster at high load factor and deletion needs tombstones. Chaining tolerates load above 1 at the cost of indirection." },
{ t: "cm-hash", d: 3, q: "What makes a hash function good for a hash map?", o: ["Cryptographic strength", "Distributing keys uniformly across buckets, cheaply, so similar keys do not cluster", "Producing large values", "Being reversible"], a: 1, why: "Cryptographic hashes are uniform but far too slow for a container. The classic failure is a hash that ignores part of the key, so structured keys such as sequential ids all land in a few buckets." },
{ t: "cm-hash", d: 3, q: "Why choose a sorted array over a hash map for a lookup table that never changes?", o: ["It uses less code", "Contiguous memory, cache-friendly binary search, no hashing cost, and it can be built at compile time", "Binary search is asymptotically faster", "Hash maps cannot be const"], a: 1, why: "For a fixed set, O(log n) on contiguous data frequently beats O(1) with a cache miss. It also has no allocation, which matters on a microcontroller." },

// ----------------------------------------------------------- cm-sorting
{ t: "cm-sorting", d: 2, q: "How is std::sort typically implemented?", o: ["Pure quicksort", "Introsort: quicksort, switching to heapsort at excessive depth and to insertion sort for small ranges", "Merge sort", "Heapsort only"], a: 1, why: "The heapsort fallback is what guarantees O(n log n) worst case rather than quicksort's O(n^2). The insertion-sort tail exploits the fact that insertion sort wins on small, nearly-sorted ranges." },
{ t: "cm-sorting", d: 2, q: "What does a stable sort guarantee?", o: ["It never crashes", "Elements comparing equal keep their original relative order", "The same result on every run", "O(n log n) worst case"], a: 1, why: "It is what makes multi-key sorting work by sorting on the least significant key first. std::stable_sort provides it, usually at the cost of extra memory." },
{ t: "cm-sorting", d: 2, q: "What is the best tool for the median of a million unsorted floats?", o: ["std::sort then index", "std::nth_element, which partitions in O(n) without fully sorting", "A priority queue", "A hash map"], a: 1, why: "You only need one element in its correct place, and nth_element does exactly that with average linear time. Fully sorting does far more work than the question requires." },
{ t: "cm-sorting", d: 2, q: "About how many comparisons does binary search need on 1,000,000 sorted elements?", o: ["About 1000", "About 20", "About 100", "About 5"], a: 1, why: "log2 of a million is just under 20. It is worth knowing cold, because it is what makes a sorted array competitive with a hash map even at large sizes." },
{ t: "cm-sorting", d: 2, q: "What is the classic binary search bug?", o: ["Off-by-one in the loop condition only", "Computing the midpoint as (low + high) / 2, which overflows for large indices", "Using the wrong comparison", "Not checking for an empty array"], a: 1, why: "low + (high - low) / 2 avoids it. It survived in the JDK for nine years, which is the usual example of how a well-understood algorithm still needs care in implementation." },
{ t: "cm-sorting", d: 3, q: "When does insertion sort beat quicksort?", o: ["Never", "On small or nearly-sorted ranges, where its low constant factor and O(n) best case win", "On large random data", "On strings only"], a: 1, why: "It is why every good sort implementation switches to it below some threshold, typically 16 to 32 elements. Adaptive sorts such as Timsort exploit existing runs in the data for the same reason." },
{ t: "cm-sorting", d: 3, q: "Why does quicksort degrade to O(n^2), and how is it prevented in practice?", o: ["Random data causes it; use merge sort", "Consistently bad pivots, such as sorted input with a first-element pivot; prevented by median-of-three, randomisation or a heapsort fallback", "It never degrades", "Too many duplicate keys only"], a: 1, why: "Adversarial or already-sorted input was a real denial-of-service vector in older implementations. Introsort's depth-limited fallback removes the worst case entirely." },
{ t: "cm-sorting", d: 3, q: "What is the information-theoretic lower bound for comparison sorting?", o: ["O(n)", "Omega(n log n)", "O(log n)", "O(n^2)"], a: 1, why: "There are n! orderings and each comparison gives one bit, so log2(n!) is about n log n. Counting or radix sorts beat it only by not comparing, which requires assumptions about the keys." },

// ------------------------------------------------------------ cm-graphs
{ t: "cm-graphs", d: 2, q: "In an unweighted graph, what has BFS found the first time it reaches a node?", o: ["Any valid path", "The shortest path in number of edges", "The cheapest path by weight", "A spanning tree edge only"], a: 1, why: "BFS explores in order of distance, so the first arrival is minimal. Swap the queue for a stack and you have DFS, which finds a path but says nothing about its length." },
{ t: "cm-graphs", d: 2, q: "When does Dijkstra's algorithm fail?", o: ["On dense graphs", "When edge weights can be negative", "On directed graphs", "When the graph is disconnected"], a: 1, why: "It commits to a node as final once popped, which a later negative edge could invalidate. Bellman-Ford handles negatives at O(V*E) and detects negative cycles." },
{ t: "cm-graphs", d: 2, q: "In a binary heap of a million elements, what does inserting one element cost?", o: ["About a million operations", "About 20 comparisons, since it sifts up at most log2(n) levels", "Constant time always", "It depends on the value"], a: 1, why: "The heap is a complete binary tree of depth log2(n). Extracting the minimum costs the same, which is what gives priority-queue-driven algorithms their O(E log V) behaviour." },
{ t: "cm-graphs", d: 2, q: "Kahn's algorithm stops with nodes remaining but none of in-degree zero. What does that prove?", o: ["The graph is disconnected", "There is a cycle among the remaining nodes", "The input was malformed", "There are multiple valid orderings"], a: 1, why: "Every remaining node depends on another remaining node, which is exactly a cycle. It is why topological sort doubles as cycle detection in build systems and dependency resolvers." },
{ t: "cm-graphs", d: 2, q: "When is an adjacency matrix preferable to an adjacency list?", o: ["Always", "For dense graphs, or when you need constant-time edge existence queries", "For very large sparse graphs", "When memory is tight"], a: 1, why: "It costs V^2 regardless of edge count, so it is wasteful for sparse graphs. The list costs V + E and is what almost all real graph code uses." },
{ t: "cm-graphs", d: 3, q: "What does A* add over Dijkstra?", o: ["Support for negative weights", "A heuristic estimate of remaining cost, which focuses the search towards the goal", "Guaranteed linear time", "Handling of cycles"], a: 1, why: "With an admissible heuristic, meaning one that never overestimates, the result is still optimal but far fewer nodes are expanded. A zero heuristic reduces it exactly to Dijkstra." },
{ t: "cm-graphs", d: 3, q: "Why is a binary heap usually preferred to a balanced binary search tree for a priority queue?", o: ["Better asymptotic complexity", "It is an implicit structure in a flat array, so it has no pointers, better cache behaviour and far less overhead", "It supports search", "It is stable"], a: 1, why: "The tree offers ordered traversal and search, which a priority queue does not need. Paying for capability you do not use is the usual reason a theoretically equivalent structure loses in practice." },
{ t: "cm-graphs", d: 3, q: "Which everyday engineering problem is a topological sort?", o: ["Route planning", "Determining build order from a dependency graph, or initialisation order of subsystems", "Load balancing", "Cache eviction"], a: 1, why: "Any 'this must happen before that' set of constraints is a DAG. Make, package managers and driver initialisation sequences all reduce to it, and the cycle case is the meaningful error." },

// ---------------------------------------------------------- cm-numerics
{ t: "cm-numerics", d: 2, q: "Halving the step size of an RK4 integration reduces global error by roughly what factor?", o: ["2", "16", "4", "8"], a: 1, why: "RK4 is fourth-order globally, so error scales as h^4 and halving h gives 2^4. It is why RK4 beats Euler on accuracy per function call despite costing four evaluations per step." },
{ t: "cm-numerics", d: 2, q: "Your adaptive explicit solver takes absurdly tiny steps although the solution looks smooth. What is happening?", o: ["The tolerance is too loose", "The system is stiff: a fast decaying mode forces tiny steps for stability, not accuracy", "The derivative function is wrong", "Round-off is dominating"], a: 1, why: "The fast mode has already decayed to nothing but the explicit method's stability region still constrains h. An implicit solver such as BDF or a Rosenbrock method removes the constraint." },
{ t: "cm-numerics", d: 2, q: "What happens to an undamped pendulum simulated with forward Euler?", o: ["It decays to rest", "Its amplitude grows steadily, because forward Euler adds energy each step", "It stays exactly constant", "It oscillates chaotically"], a: 1, why: "Energy drift is the symptom worth memorising, and its direction identifies the method: forward Euler gains energy, backward Euler loses it. Symplectic integrators keep it bounded, which is why they are used for orbital and molecular work." },
{ t: "cm-numerics", d: 2, q: "For an explicit 1D wave-equation scheme, refining dx by a factor of 2 requires dt to do what?", o: ["Stay the same", "Halve, to keep the CFL condition satisfied", "Quarter", "Double"], a: 1, why: "The CFL condition requires c*dt/dx below a constant, so dt must scale with dx. It is why doubling the resolution of a 3D explicit simulation costs about sixteen times the work, not eight." },
{ t: "cm-numerics", d: 2, q: "What does step-size control in an adaptive solver actually compare?", o: ["The solution against an analytic result", "Two estimates of the same step at different orders, using their difference as a local error estimate", "Successive derivative values", "Energy before and after"], a: 1, why: "Embedded pairs such as RK45 compute both orders from mostly shared function evaluations, so the estimate is nearly free. The step is then accepted or retried against a tolerance." },
{ t: "cm-numerics", d: 3, q: "What is the trade-off of an implicit solver?", o: ["It is less accurate", "It is stable at much larger steps but must solve a nonlinear system each step, usually needing a Jacobian", "It only works on linear systems", "It cannot be adaptive"], a: 1, why: "For a stiff problem the larger steps more than pay for the per-step cost. For a non-stiff problem the extra work is pure loss, which is why the choice depends on the problem's stiffness." },
{ t: "cm-numerics", d: 3, q: "Why does adding more digits of precision not fix an unstable numerical scheme?", o: ["It does fix it", "Instability amplifies whatever error exists, so a smaller starting error just delays the blow-up", "Precision is unrelated to error", "The scheme becomes stable at double precision"], a: 1, why: "Growth is exponential in the number of steps, so extra digits buy you a linear number of extra steps. Stability is a property of the scheme and step size, not of the arithmetic." },
{ t: "cm-numerics", d: 3, q: "Why is comparing two step sizes a useful sanity check on any simulation?", o: ["It is faster", "If the answer changes materially when you halve the step, the result is not converged and the physics conclusion is unsafe", "It tests the compiler", "It reveals stiffness only"], a: 1, why: "It is the cheapest validation available and it catches both too-large steps and outright scheme errors. The same logic applies to mesh refinement in space." },

// ------------------------------------------------------------ cm-interp
{ t: "cm-interp", d: 2, q: "What is the Runge phenomenon?", o: ["Aliasing in resampling", "High-degree polynomial interpolation on equally spaced points oscillating wildly near the interval ends", "Loss of precision in the fit", "Instability in spline solvers"], a: 1, why: "More points make it worse, not better, which is counterintuitive. The practical answers are low-degree piecewise interpolation such as splines, or Chebyshev-spaced nodes clustered at the ends." },
{ t: "cm-interp", d: 2, q: "When does sinc interpolation reconstruct a sampled signal exactly?", o: ["Always", "When the signal is bandlimited below Nyquist and infinitely many samples are available", "For any smooth signal", "When oversampled twice"], a: 1, why: "It is the sampling theorem stated as a reconstruction formula. Real implementations truncate and window the sinc, which is why practical resamplers trade passband ripple against kernel length." },
{ t: "cm-interp", d: 2, q: "Three samples around a peak are 2, 5 and 4. Where does parabolic refinement place the true peak?", o: ["Exactly at the centre sample", "Slightly after the centre sample, at about +0.17 samples", "Slightly before the centre sample", "It cannot be determined"], a: 1, why: "The offset is 0.5*(y[-1]-y[1])/(y[-1]-2*y[0]+y[1]) = 0.5*(2-4)/(2-10+4) = 0.25. The larger neighbour is the later one, so the peak shifts towards it, giving sub-sample resolution from three points." },
{ t: "cm-interp", d: 2, q: "How does shape-preserving cubic (PCHIP) differ from a global cubic spline?", o: ["It is faster only", "It avoids overshoot by not enforcing second-derivative continuity, so it never invents extrema between data points", "It is less accurate everywhere", "It requires equal spacing"], a: 1, why: "A natural spline is smoother but can overshoot, which is unacceptable when the data is physically bounded, such as a concentration or a probability. PCHIP trades smoothness for monotonicity." },
{ t: "cm-interp", d: 2, q: "Why does linear interpolation act as a low-pass filter on resampled data?", o: ["It removes DC", "Its kernel is a triangle, whose transform is a sinc squared, attenuating high frequencies", "It averages neighbouring samples equally", "It does not"], a: 1, why: "The droop near Nyquist is why upsampling by linear interpolation softens a signal. Higher-order kernels have flatter passbands, which is what a good resampler is really buying you." },
{ t: "cm-interp", d: 3, q: "Why is upsampling before interpolation often better than interpolating directly?", o: ["It is cheaper", "A polyphase interpolation filter can be designed to a spec, whereas a simple kernel's frequency response is fixed and often poor", "It avoids aliasing entirely", "It preserves phase better"], a: 1, why: "You get explicit control of passband ripple and stopband attenuation. It is the difference between resampling that meets a specification and resampling that happens to look acceptable." },
{ t: "cm-interp", d: 3, q: "What must you do before decimating a signal, and why?", o: ["Nothing", "Low-pass filter below the new Nyquist, or aliased content folds into the band and cannot be removed afterwards", "Upsample first", "Remove the DC offset"], a: 1, why: "Discarding samples is sampling again, so the same rule applies. Once folded, the aliased energy is indistinguishable from real signal, which is why the order of operations is not negotiable." },
{ t: "cm-interp", d: 3, q: "Why is a cubic spline's smoothness sometimes a liability in measurement data?", o: ["It is too slow", "Continuous second derivative means a change anywhere propagates, and it can invent oscillation between noisy points", "It cannot handle unequal spacing", "It has no closed form"], a: 1, why: "For noisy data a smoothing spline or a fit is more honest, because interpolation forces the curve through every point including the errors. The question is whether you believe each sample exactly." },

// ----------------------------------------------------------- cm-fourier
{ t: "cm-fourier", d: 2, q: "What does sampling a signal in time do to its spectrum?", o: ["Scales it", "Makes it periodic, repeating at multiples of the sample rate", "Shifts it", "Makes it continuous"], a: 1, why: "The four-transform map is one duality: discrete in one domain means periodic in the other. Aliasing is simply those repeats overlapping." },
{ t: "cm-fourier", d: 2, q: "Convolution in time corresponds to what in frequency?", o: ["Convolution", "Multiplication", "Addition", "Correlation"], a: 1, why: "And the dual holds: multiplying in time, as when windowing, convolves in frequency, which is exactly why windowing smears a spectral line into the window's shape." },
{ t: "cm-fourier", d: 2, q: "Which shape is its own Fourier transform?", o: ["The rectangle", "The Gaussian", "The triangle", "The sinc"], a: 1, why: "It is why the Gaussian achieves the minimum time-bandwidth product and why Gabor atoms are the optimal compromise in time-frequency analysis. Rectangle and sinc are a transform pair, not self-transforms." },
{ t: "cm-fourier", d: 2, q: "How does Parseval's theorem let you check an FFT pipeline?", o: ["By comparing phase", "Total energy in time must equal total energy in frequency, up to the known scaling factor", "By checking symmetry", "By counting bins"], a: 1, why: "It catches scaling errors immediately, which is the most common FFT integration bug given how many conventions exist for where the 1/N goes. Two lines of code and it either matches or it does not." },
{ t: "cm-fourier", d: 2, q: "What is the duality trade you cannot escape?", o: ["Accuracy against speed", "Narrow in one domain means wide in the other, so short pulses have broad spectra", "Amplitude against phase", "Real against complex"], a: 1, why: "It is why a sharper filter needs a longer impulse response and why resolving two close frequencies needs a longer record. Every windowing and resolution decision in DSP is a version of this." },
{ t: "cm-fourier", d: 3, q: "What is the DFT, viewed as a matrix operation?", o: ["A rotation", "A projection onto a basis of complex exponentials, expressed as multiplication by an N by N matrix of roots of unity", "A convolution matrix", "A permutation"], a: 1, why: "Each output bin is an inner product with one basis vector. The FFT exploits the structure of that matrix to do the same product in N log N instead of N^2." },
{ t: "cm-fourier", d: 3, q: "Why is the spectrum of a real-valued signal conjugate symmetric?", o: ["It is a numerical artefact", "The negative-frequency components must cancel the imaginary parts, so X(-f) is the conjugate of X(f)", "Only for periodic signals", "It is not"], a: 1, why: "It means half the FFT output of a real signal is redundant, which real-input FFT routines exploit for roughly a factor of two in cost and memory." },
{ t: "cm-fourier", d: 3, q: "Which transform pair is worth having memorised for pulse work?", o: ["Gaussian and triangle", "Rectangle in time gives a sinc in frequency, with the first null at 1/T", "Sinc and sinc", "Impulse and impulse"], a: 1, why: "It gives you the bandwidth of any gated tone burst immediately: a 10 microsecond gate has its first null 100 kHz from the carrier. That is the number that decides filter and sample rate choices." },

// ------------------------------------------------------------- cm-opt2
{ t: "cm-opt2", d: 2, q: "At a constrained optimum with a single equality constraint, what is true of the objective's gradient?", o: ["It is zero", "It is parallel to the constraint's gradient, the ratio being the Lagrange multiplier", "It is perpendicular to the constraint", "It is undefined"], a: 1, why: "If it had any component along the constraint surface you could move that way and improve. The multiplier itself has meaning: it is the sensitivity of the optimum to relaxing the constraint." },
{ t: "cm-opt2", d: 2, q: "Which regulariser tends to drive parameters exactly to zero?", o: ["L2 (ridge)", "L1 (lasso)", "Both equally", "Neither"], a: 1, why: "The L1 ball has corners on the axes, so the optimum often lands on one, producing sparsity and hence feature selection. L2 shrinks everything smoothly towards zero without reaching it." },
{ t: "cm-opt2", d: 2, q: "As the penalty weight grows very large in a quadratic penalty method, what happens to the subproblem?", o: ["It becomes easier", "It becomes badly ill-conditioned, so the solver struggles numerically", "It becomes linear", "It becomes unconstrained"], a: 1, why: "The Hessian's condition number grows with the penalty, which is why augmented Lagrangian methods exist: they add explicit multiplier estimates so the penalty need not go to infinity." },
{ t: "cm-opt2", d: 2, q: "Your fitted parameter sits exactly on the bound you gave it. What is the healthiest interpretation?", o: ["The fit converged well", "The data wants to push it further, so the bound is doing the fitting rather than the data", "The bound is correct", "The model is over-parameterised"], a: 1, why: "It is a signal to check whether the bound is physically justified or was just a guess. An active bound also means the reported uncertainty on that parameter is meaningless." },
{ t: "cm-opt2", d: 2, q: "What is at stake in the convex versus nonconvex distinction?", o: ["Speed only", "For convex problems any local minimum is global; for nonconvex ones the answer depends on where you started", "Whether constraints are allowed", "Whether gradients exist"], a: 1, why: "It changes what you can claim. On a nonconvex problem the honest report includes the starting point and, ideally, several restarts showing the answer is reproducible." },
{ t: "cm-opt2", d: 3, q: "What does Tikhonov regularisation do to an ill-conditioned least-squares problem?", o: ["Removes bad data", "Adds a term that bounds the solution norm, damping the amplification of noise by small singular values", "Increases the rank", "Makes it nonlinear"], a: 1, why: "In SVD terms it replaces 1/sigma with sigma/(sigma^2 + lambda^2), so tiny singular values stop dominating. Choosing lambda is the whole game, and the L-curve is the usual tool." },
{ t: "cm-opt2", d: 3, q: "Why standardise features before applying an L1 or L2 penalty?", o: ["To speed up convergence only", "The penalty treats all coefficients on the same scale, so unscaled features are penalised in proportion to their units", "It is not necessary", "To make the problem convex"], a: 1, why: "A feature measured in millimetres gets a coefficient a thousand times larger than the same feature in metres, and the penalty punishes it accordingly. The regularised solution would otherwise depend on your unit choices." },
{ t: "cm-opt2", d: 3, q: "What do the KKT conditions generalise?", o: ["Gradient descent", "Lagrange multipliers, extending them to inequality constraints with complementary slackness", "Newton's method", "Convexity"], a: 1, why: "Complementary slackness says each inequality is either active with a nonnegative multiplier, or inactive with a zero multiplier. It is the formal statement of 'only the binding constraints matter'." },

// ------------------------------------------------------------ cm-bayes
{ t: "cm-bayes", d: 2, q: "Fault rate 1 percent, sensitivity 99 percent, false positive rate 5 percent. A board tests positive. Roughly what fraction are truly faulty?", o: ["About 99 percent", "About 17 percent", "About 50 percent", "About 90 percent"], a: 1, why: "Of 1000 boards, 10 are faulty and about 10 test positive; 990 are good and about 50 test positive falsely. So 10 out of 60, roughly 17 percent. The base rate dominates, and this is the shape to memorise." },
{ t: "cm-bayes", d: 2, q: "MAP estimation with a Gaussian prior on the parameters is equivalent to what?", o: ["Maximum likelihood", "Least squares with L2 regularisation", "L1 regularisation", "Cross-validation"], a: 1, why: "Taking the log turns the Gaussian prior into a quadratic penalty on the parameters. A Laplace prior gives L1 instead, which is why lasso and ridge have clean Bayesian readings." },
{ t: "cm-bayes", d: 2, q: "In Bayesian terms, what does the Kalman predict step compute?", o: ["The posterior", "The prior for the next time step, by propagating the current belief through the motion model", "The likelihood", "The evidence"], a: 1, why: "The update step then applies Bayes' rule with the measurement likelihood to get the posterior. The Kalman filter is exactly Bayesian filtering under linear-Gaussian assumptions." },
{ t: "cm-bayes", d: 2, q: "An anomaly detector has a 1 percent false alarm rate and the fault occurs in 1 window in 10,000. What follows?", o: ["It is a good detector", "Alarms will be overwhelmingly false, about 100 to 1, so nobody will act on them", "It needs a longer window", "The sensitivity is too low"], a: 1, why: "100 false alarms per 10,000 windows against 1 real event. This is why alarm systems get muted, and why false alarm rate must be specified against the base rate rather than in isolation." },
{ t: "cm-bayes", d: 2, q: "What is the difference between the likelihood and the posterior?", o: ["Nothing", "Likelihood is probability of the data given the parameters; posterior is probability of the parameters given the data", "The posterior ignores the prior", "The likelihood includes the evidence"], a: 1, why: "Swapping them is the prosecutor's fallacy. Bayes' rule is precisely the machinery for converting one into the other, and the prior is what you need in order to do it." },
{ t: "cm-bayes", d: 3, q: "What role does the evidence, or marginal likelihood, play?", o: ["It is the prior", "It normalises the posterior, and comparing it between models is the Bayesian form of model selection", "It is the likelihood at the MAP point", "It is ignored in practice"], a: 1, why: "For parameter estimation it is a constant you can ignore. For model comparison it is the whole point, and it automatically penalises unnecessary complexity, which is why it behaves like a principled Occam's razor." },
{ t: "cm-bayes", d: 3, q: "When does MAP coincide with maximum likelihood?", o: ["Never", "When the prior is uniform over the region of interest, so it contributes no gradient", "When the data is Gaussian", "When there is a lot of data"], a: 1, why: "A flat prior adds a constant to the log posterior. In practice large data also drives them together, because the likelihood eventually overwhelms any reasonable prior." },
{ t: "cm-bayes", d: 3, q: "Why is a conjugate prior convenient?", o: ["It is more accurate", "The posterior stays in the same family as the prior, so updating is a closed-form parameter change rather than an integral", "It removes the need for data", "It guarantees convergence"], a: 1, why: "Beta with binomial, Gaussian with Gaussian. It is what makes recursive estimators such as the Kalman filter computable in closed form, and why non-conjugate models need sampling or approximation." },

// --------------------------------------------------------------- cm-ml
{ t: "cm-ml", d: 2, q: "When should the test set be used?", o: ["For tuning hyperparameters", "Once, at the very end, to estimate performance on unseen data", "Every training epoch", "For feature selection"], a: 1, why: "Every look at it leaks information and turns it into a second validation set. That is why the three-way split exists, and why a held-out set that has been used repeatedly no longer tells you anything." },
{ t: "cm-ml", d: 2, q: "A model reaches 99 percent training accuracy and 70 percent validation accuracy. What is the diagnosis?", o: ["Underfitting", "Overfitting: high variance, so it has memorised rather than generalised", "The validation set is wrong", "Bad feature scaling"], a: 1, why: "The remedies are more data, regularisation, a simpler model or early stopping. Underfitting is the opposite signature: both numbers poor and close together." },
{ t: "cm-ml", d: 2, q: "Which model is essentially unaffected by leaving features unscaled?", o: ["k-nearest neighbours", "A decision tree or random forest", "Support vector machine with an RBF kernel", "Logistic regression with regularisation"], a: 1, why: "Trees split on thresholds within each feature independently, so monotone rescaling changes nothing. Anything using distances or penalties on coefficients is scale-sensitive." },
{ t: "cm-ml", d: 2, q: "Fitting a standardising scaler on the full dataset before splitting causes what?", o: ["Nothing important", "Data leakage: test-set statistics inform the transform, so the reported score is optimistic", "Slower training", "Feature collinearity"], a: 1, why: "Fit the scaler on training data only and apply it to the test set. A pipeline object that carries the transform with the model is the standard way to make this impossible to get wrong." },
{ t: "cm-ml", d: 2, q: "What is the bias-variance trade-off, in words?", o: ["Accuracy against speed", "Bias is error from an over-simple model; variance is sensitivity to the particular training sample, and reducing one usually raises the other", "Training against inference cost", "Precision against recall"], a: 1, why: "It is why a very flexible model fits the training set perfectly and generalises badly, and why regularisation helps: it trades a little bias for a large reduction in variance." },
{ t: "cm-ml", d: 3, q: "When does a classical model beat a deep one?", o: ["Never", "On small tabular datasets, where gradient-boosted trees usually win and are far cheaper to train and explain", "On images", "On raw audio"], a: 1, why: "Deep learning wins where the raw input is high-dimensional and structured, such as images, audio or text, and where data is plentiful. Below a few thousand tabular rows it usually loses." },
{ t: "cm-ml", d: 3, q: "Why is accuracy a poor metric on an imbalanced dataset?", o: ["It is hard to compute", "Predicting the majority class always can score very high while detecting nothing of interest", "It ignores the training set", "It requires probabilities"], a: 1, why: "With 1 percent positives, a constant negative prediction scores 99 percent. Precision, recall, F1 or the area under a precision-recall curve are what actually describe the detector." },
{ t: "cm-ml", d: 3, q: "What does k-fold cross-validation buy over a single train/validation split?", o: ["Faster training", "A less noisy performance estimate, since every point is used for validation exactly once", "A larger training set", "It removes the need for a test set"], a: 1, why: "It matters most when data is scarce, where a single split's estimate depends heavily on which points landed where. It costs k times the training, and it still does not replace a held-out test set." }

]);
