// A second pass over every CS and Maths lesson: ten more questions each.
//
// Topic tags are lesson ids, so topicLesson() resolves them by the byId
// fallback and no TOPIC_LESSON entry is needed.
//
// Correct options are kept short and the reasoning put in `why`, which the
// page shows the moment you answer. A distractor is the longest option in
// about three questions out of four, which is chance for four options.
BANKS["CS & Maths"] = BANKS["CS & Maths"].concat([

// ----------------------------------------------------------- structures
{ t: "structures", d: 1, q: "What does a ring buffer give you that a queue on the heap does not?", o: ["Fixed memory and constant-time operations", "The ability to grow when the producer outruns the consumer", "Automatic ordering of elements by their priority", "Safe access from any number of threads at once"], a: 0, why: "Allocation is done once, and push and pop are index arithmetic. That predictability is why it is the default structure in an interrupt-driven system." },
{ t: "structures", d: 2, q: "Why is a power-of-two ring buffer size convenient?", o: ["The index wrap becomes a bitwise mask", "It halves the memory the buffer needs", "It allows two producers to write safely", "It makes the buffer cache-line aligned"], a: 0, why: "Masking is a single instruction where a modulo may be a divide. It also lets the indices free-run and wrap naturally, which simplifies the full and empty test." },
{ t: "structures", d: 2, q: "What makes a single-producer single-consumer ring buffer lock free?", o: ["Each index is written by only one side", "The buffer is protected by a hardware mutex", "Reads and writes are atomic on every platform", "The producer waits for the consumer to finish"], a: 0, why: "Because only one side writes each index, no mutual exclusion is needed, though the indices still need to be atomic with the right ordering. Adding a second producer breaks the argument entirely." },
{ t: "structures", d: 3, q: "Why does a linked list often lose to an array in practice?", o: ["Each node is a separate allocation and a cache miss", "Linked lists cannot store more than a few thousand items", "Insertion into a linked list is not actually constant time", "Arrays support operations that linked lists cannot"], a: 0, why: "Traversal defeats the prefetcher, and the per-node allocation costs memory and time. The complexity table ignores the constant factor, and here the constant factor decides." },
{ t: "structures", d: 2, q: "What is an intrusive list?", o: ["The link pointers live inside the element itself", "A list that can be traversed in both directions", "A list whose nodes are allocated from a pool", "A list that keeps its elements sorted at all times"], a: 0, why: "It avoids a separate node allocation and lets an element be removed without searching for it. It is common in kernels and embedded code for exactly those reasons." },
{ t: "structures", d: 2, q: "When is a fixed-capacity container the right answer?", o: ["When the maximum is known and allocation is unacceptable", "Whenever the container holds fewer than a hundred items", "When the elements are all of the same size", "When the container is accessed from an interrupt"], a: 0, why: "Bounding the memory up front turns an unpredictable allocation into a known one, which is what a real-time path needs. The cost is deciding what happens when it is full." },
{ t: "structures", d: 2, q: "What does a priority queue give you?", o: ["Constant-time access to the smallest element", "Elements returned in the order they arrived", "Constant-time insertion at any position", "A sorted view of every element at all times"], a: 0, why: "A binary heap gives an O(1) peek and logarithmic insert and extract. It is not fully sorted, which is why iterating it does not give you order." },
{ t: "structures", d: 3, q: "Why is a heap stored in a flat array rather than as nodes?", o: ["No pointers, better cache behaviour and less overhead", "It is the only way to keep the heap balanced", "Array storage allows the heap to be sorted in place", "Nodes cannot represent a complete binary tree"], a: 0, why: "The complete-tree property means a child's index is derivable from the parent's, so the structure is implicit. That is why heapsort has such a small constant factor." },
{ t: "structures", d: 2, q: "What does a circular buffer overwrite policy trade?", o: ["Losing old data against blocking the producer", "Memory usage against access time", "Latency against total throughput", "Correctness against implementation simplicity"], a: 0, why: "Either the newest data is dropped or the oldest is, and which is right depends on the application. Silently choosing one without deciding is a common source of surprise." },
{ t: "structures", d: 2, q: "Why does a hash table need a good load factor policy?", o: ["Collisions rise sharply as the table fills", "The hash function stops working above a threshold", "Memory fragmentation increases with occupancy", "The table cannot be resized once it is in use"], a: 0, why: "Lookups degrade towards a linear scan of a bucket as the table fills. Resizing at a threshold keeps the average cost constant, at the price of an occasional expensive insert." },

// -------------------------------------------------------------- leastsq
{ t: "leastsq", d: 1, q: "What does least squares minimise?", o: ["The sum of squared residuals", "The largest single residual in the data set", "The sum of the absolute values of the residuals", "The number of points that lie off the fitted line"], a: 0, why: "Squaring makes the problem differentiable and gives a closed-form solution. It also makes the fit very sensitive to outliers, which is the main practical objection." },
{ t: "leastsq", d: 2, q: "Why solve the normal equations by QR rather than by inversion?", o: ["Forming the normal equations squares the condition number", "QR is faster for every size of problem", "Inversion cannot handle rectangular matrices", "QR also gives you all of the residuals directly as a by-product"], a: 0, why: "Explicitly forming A transpose A doubles the number of digits you lose. QR works on A directly and is far better conditioned." },
{ t: "leastsq", d: 2, q: "What does a large condition number mean for a fit?", o: ["Small changes in the data move the solution a lot", "The fit will take much longer to compute", "The residuals will all be rather larger than expected", "The problem has no solution at all"], a: 0, why: "It is an amplification factor from input error to output error, so a condition number of ten thousand costs you four digits. That is a statement about the problem, not the algorithm." },
{ t: "leastsq", d: 3, q: "What does Tikhonov regularisation add?", o: ["A penalty on the solution norm, damping noise amplification", "Extra data points to make the system determined", "A constraint that the solution must be positive", "A weighting that emphasises only the most recently taken data"], a: 0, why: "It bounds the solution and stops small singular values amplifying noise. The regularisation weight is chosen at the corner of the L-curve where residual and solution norm trade off." },
{ t: "leastsq", d: 2, q: "Why does an outlier damage a least-squares fit so much?", o: ["Its residual is squared, so it dominates the sum", "It changes the number of degrees of freedom", "It makes the normal equations singular", "It shifts the mean of the residuals away from zero"], a: 0, why: "A point ten times further out contributes a hundred times the cost. RANSAC or an L1 norm are the standard alternatives when outliers are expected." },
{ t: "leastsq", d: 2, q: "What does weighted least squares let you express?", o: ["That some measurements are more trustworthy", "That the model should fit recent data first", "That the solution must be non-negative", "That certain parameters are already known"], a: 0, why: "Weighting by the inverse variance is what makes the estimate optimal when the noise is not uniform. It is the same idea as the Kalman gain, in a batch setting." },
{ t: "leastsq", d: 2, q: "What is the residual vector orthogonal to?", o: ["The column space of the design matrix", "The vector of fitted parameters", "The vector of measurements themselves", "The null space of the design matrix"], a: 0, why: "That orthogonality is the geometric statement of the normal equations. It is why the fitted values are the projection of the data onto the model's span." },
{ t: "leastsq", d: 3, q: "Why fit 200 equations for 5 unknowns rather than pick 5?", o: ["Averaging over the redundancy suppresses noise", "The extra equations make the solution exact", "Five equations would give a singular system", "It is the only way to estimate the residuals"], a: 0, why: "The error falls roughly as the square root of the number of measurements. Discarding 195 of them throws that away, and also loses any chance of detecting an outlier." },
{ t: "leastsq", d: 2, q: "How do you decide whether a fit is good?", o: ["Look at the residuals for structure", "Check that the sum of squares is small", "Confirm the condition number is below ten", "Compare the parameters with their expected values"], a: 0, why: "Residuals that curve, fan out or correlate with an input mean the model is wrong, however small the total. The magnitude alone tells you very little." },
{ t: "leastsq", d: 2, q: "What does total least squares account for?", o: ["Error in the independent variable as well", "Correlation between successive measurements", "Constraints on the parameter values", "Outliers in the dependent variable"], a: 0, why: "Ordinary least squares assumes the x values are exact, which is often untrue. Total least squares minimises perpendicular distance instead, which is the right thing when both axes are measured." },

// -------------------------------------------------------------- cm-hash
{ t: "cm-hash", d: 2, q: "What makes a good hash function for a hash table?", o: ["Uniform, cheap distribution of keys across buckets", "Cryptographic strength against deliberate collisions", "A guarantee that no two keys ever collide", "Preservation of the ordering of the keys"], a: 0, why: "Similar keys must not cluster, and the function is on the critical path so it must be cheap. Cryptographic strength only matters when an adversary supplies the keys." },
{ t: "cm-hash", d: 2, q: "How does open addressing differ from chaining?", o: ["It probes for another slot in the same array", "It stores collisions in a secondary hash table", "It rehashes the key until no collision occurs", "It refuses to insert when a collision happens"], a: 0, why: "Everything lives in one array, which is far better for the cache but complicates deletion. Chaining keeps a list per bucket and handles deletion trivially." },
{ t: "cm-hash", d: 3, q: "Why is deletion awkward in an open-addressed table?", o: ["Removing an entry breaks a probe chain", "The array cannot be resized after a deletion", "The hash function has to be recomputed", "Deleted entries cannot be reused later"], a: 0, why: "A lookup stops at an empty slot, so a hole in the middle of a chain hides everything after it. Tombstones solve it and slowly degrade performance until a rehash." },
{ t: "cm-hash", d: 2, q: "What is amortised constant time for a hash table insert?", o: ["Constant on average, with occasional expensive rehashes", "Constant in every case, without exception", "Constant once the table has finally stopped growing at all", "Constant for the first N inserts only"], a: 0, why: "Doubling on resize means the total work over a long sequence is linear, but any single insert may be O(n). That distinction matters in a real-time path." },
{ t: "cm-hash", d: 2, q: "When is a small sorted array better than a hash table?", o: ["When there are only a handful of entries", "When the keys are strings rather than integers", "When lookups outnumber insertions heavily", "When the entries must be iterated in order"], a: 0, why: "Below a few dozen entries, the constant factors of hashing and pointer chasing exceed a cache-friendly linear scan or binary search. Measuring rather than assuming is the point." },
{ t: "cm-hash", d: 2, q: "Why can a hash table be a denial-of-service risk?", o: ["An attacker can choose keys that all collide", "The table grows without bound under load", "Hashing is too slow for high request rates", "The table cannot be cleared between requests"], a: 0, why: "Every operation degrades to a linear scan if the buckets are deliberately loaded. A seeded or keyed hash function is the standard mitigation." },
{ t: "cm-hash", d: 3, q: "What does a Bloom filter give you?", o: ["Membership testing with false positives but no false negatives", "Exact membership testing in a genuinely constant amount of space", "A sorted view of the inserted elements", "The ability to delete elements efficiently"], a: 0, why: "It answers definitely-not or possibly-yes in a fraction of the memory. That suits a cheap pre-filter in front of an expensive lookup." },
{ t: "cm-hash", d: 2, q: "What does an ordered map give you that a hash map does not?", o: ["Iteration in key order and range queries", "Constant-time lookup in the worst case", "Lower memory use for the same entries", "Immunity to a poorly chosen hash function"], a: 0, why: "A balanced tree keeps the keys ordered, at the cost of logarithmic lookup and worse cache behaviour. If you never need the order, you are paying for nothing." },
{ t: "cm-hash", d: 2, q: "Why does an embedded system often use a perfect hash?", o: ["The key set is known at build time", "It uses less memory than any other structure", "It is the only structure with no collisions", "Hash tables cannot be used without a heap"], a: 0, why: "A fixed set of commands or register names can be hashed with no collisions at all, generated offline. Lookup becomes one hash and one comparison." },
{ t: "cm-hash", d: 2, q: "What does hashing a struct by memcmp risk?", o: ["Padding bytes make identical values hash differently", "The struct's size may change between builds", "Any pointers inside the struct will all be dereferenced", "The hash will be too slow for large structs"], a: 0, why: "Uninitialised padding is included in the bytes, so two logically equal structs can differ. Hashing the fields explicitly avoids it entirely." },

// ------------------------------------------------------------ cm-memory
{ t: "cm-memory", d: 1, q: "Why is a cache miss so expensive?", o: ["Main memory is hundreds of cycles away", "The cache must be flushed before the miss is served", "Missing data has to be recomputed from scratch", "The processor stalls until the whole line is used"], a: 0, why: "The gap between processor and memory speed is the dominant fact of modern performance. Two to three hundred cycles is a great many instructions not executed." },
{ t: "cm-memory", d: 2, q: "What does the cache fetch on a miss?", o: ["A whole line, typically 64 bytes", "Only the bytes that were requested", "The page containing the address", "A line plus the next one, always"], a: 0, why: "Neighbouring data comes along free, which is why sequential access is so much faster than random. It is also why a struct's layout matters." },
{ t: "cm-memory", d: 2, q: "What does the prefetcher need to help you?", o: ["A predictable access pattern, ideally sequential", "A hint from the compiler at each access", "Data aligned to the page boundary", "A cache large enough to hold the working set"], a: 0, why: "Sequential and constant-stride patterns are detected and fetched ahead. Pointer chasing gives it nothing to predict, which is a large part of why linked structures are slow." },
{ t: "cm-memory", d: 3, q: "Why is structure of arrays faster for a loop touching one field?", o: ["Only the field you use enters the cache", "It reduces the total memory the program uses", "It allows the compiler to remove bounds checks", "The fields can be allocated on the stack"], a: 0, why: "Array of structures drags whole objects through the cache to read one field. Splitting the fields also makes vectorisation possible, which compounds the gain." },
{ t: "cm-memory", d: 2, q: "What is false sharing?", o: ["Two cores writing different variables in one cache line", "Two threads writing the same variable at once", "A cache line shared between the instructions and the data", "A variable read by two cores simultaneously"], a: 0, why: "The variables are independent but the line is not, so each write invalidates the other core's copy. Padding to a cache line separates them." },
{ t: "cm-memory", d: 2, q: "Why does memory allocation fragment over time?", o: ["Freed blocks leave gaps too small to reuse", "The allocator loses track of freed memory", "The heap grows every time memory is freed", "Allocation sizes increase as the program runs"], a: 0, why: "A pattern of mixed sizes leaves holes that no later request fits. A pool allocator for fixed-size objects avoids the problem by construction." },
{ t: "cm-memory", d: 2, q: "What does an arena or bump allocator give up?", o: ["Individual deallocation, in exchange for speed", "The ability to allocate objects of different sizes", "Alignment guarantees for the allocated memory", "Thread safety across multiple allocating threads"], a: 0, why: "Allocation is a pointer increment and the whole arena is freed at once. It suits a request-scoped or frame-scoped lifetime perfectly and nothing else." },
{ t: "cm-memory", d: 3, q: "Why does alignment matter beyond correctness?", o: ["An unaligned access can straddle two cache lines", "Unaligned data cannot be cached at all", "The compiler refuses to vectorise unaligned data", "Unaligned access always causes a hardware fault"], a: 0, why: "Straddling means two lines fetched instead of one, and on some architectures a fault or a trap-and-emulate. Aligning to the natural size costs a little padding and avoids all of it." },
{ t: "cm-memory", d: 2, q: "What is the working set of a program?", o: ["The memory it actively touches over a short window", "The total memory it has allocated", "The memory resident in physical RAM", "The memory that is shared between all of its threads"], a: 0, why: "If it fits in cache, the program runs at cache speed; if not, at memory speed. Reducing it is often a bigger win than reducing instruction count." },
{ t: "cm-memory", d: 2, q: "Why does a large page size help some workloads?", o: ["Fewer TLB entries cover the same memory", "Large pages are cached more aggressively", "The allocator can serve requests faster", "Page faults become impossible above a size"], a: 0, why: "A TLB miss is a page-table walk, and a program touching gigabytes can thrash the TLB with small pages. Huge pages cut the number of translations needed." },

// -------------------------------------------------------- cm-concurrency
{ t: "cm-concurrency", d: 1, q: "What is a data race?", o: ["Unsynchronised access where at least one is a write", "Two threads reading the same variable", "Two threads competing for the same lock", "A thread that runs before another one has even started"], a: 0, why: "It is undefined behaviour, not merely a wrong value, so the compiler may assume it never happens. Two concurrent reads are not a race." },
{ t: "cm-concurrency", d: 2, q: "What does a mutex give you that an atomic does not?", o: ["Protection of an invariant across several operations", "A guarantee that the protected data is in cache", "Faster access when contention is low", "Ordering between operations on different variables"], a: 0, why: "Atomics make one operation indivisible; a mutex makes a whole region indivisible. Updating two related fields consistently needs the latter." },
{ t: "cm-concurrency", d: 2, q: "What are Coffman's four conditions for deadlock?", o: ["Mutual exclusion, hold and wait, no preemption, circular wait", "Two threads, two locks, two resources and a timeout", "Priority inversion, starvation, livelock and deadlock all together", "Contention, blocking, waiting and a shared resource"], a: 0, why: "Breaking any one of them prevents deadlock, and imposing a global lock order is the usual choice because it breaks circular wait. It is a checklist worth knowing by name." },
{ t: "cm-concurrency", d: 3, q: "What is priority inversion?", o: ["A high-priority task blocked by a low-priority lock holder", "A task whose priority is set incorrectly at start-up", "Two tasks of equal priority never yielding to each other", "The scheduler running tasks in the wrong order"], a: 0, why: "The low-priority holder can be preempted by a medium task, so the high task waits indefinitely. Priority inheritance temporarily raises the holder, which is why it exists." },
{ t: "cm-concurrency", d: 2, q: "What does a condition variable need alongside it?", o: ["A mutex and a predicate checked in a loop", "A timeout to prevent it waiting forever", "A second thread to signal it", "An atomic flag indicating readiness"], a: 0, why: "The mutex protects the shared state and the loop copes with spurious and stale wakeups. Waiting without a predicate is a bug even when it happens to work." },
{ t: "cm-concurrency", d: 2, q: "What is livelock?", o: ["Threads keep running but make no progress", "A thread that never acquires the lock it wants", "Two threads deadlocked on the same resource", "A thread spinning while it waits for a lock"], a: 0, why: "Each thread politely backs off and retries, and they keep colliding. Randomised backoff is what breaks the symmetry." },
{ t: "cm-concurrency", d: 2, q: "Why is a lock-free algorithm not automatically faster?", o: ["Contention still costs cache line transfers", "Lock-free code cannot be optimised by the compiler", "Atomic operations are slower than mutex operations", "Lock-free structures use more memory per element"], a: 0, why: "The line still bounces between cores, and the retry loop can waste a great deal of work. Lock-free buys progress guarantees, not throughput." },
{ t: "cm-concurrency", d: 3, q: "What does memory_order_acquire and release establish?", o: ["A happens-before edge between the releasing and acquiring threads", "That the operation itself cannot be interrupted", "That the value is always written straight through to the main memory", "That no other thread can access the variable"], a: 0, why: "Everything written before the release is visible after the acquire, which is what publishes data safely. Relaxed ordering gives atomicity with none of that." },
{ t: "cm-concurrency", d: 2, q: "Why is a thread pool usually better than a thread per task?", o: ["Thread creation is expensive and the count is bounded", "Pooled threads are always given a higher scheduling priority", "It removes the need for any synchronisation", "Tasks in a pool cannot deadlock each other"], a: 0, why: "Creation costs a stack and a kernel object, and unbounded threads thrash the scheduler. A pool sized near the core count keeps the machine busy without oversubscribing." },
{ t: "cm-concurrency", d: 2, q: "What is the safest way for a thread to share data with an ISR?", o: ["A single-producer ring buffer with atomic indices", "A single mutex taken by both the thread and the ISR", "A global variable marked volatile", "A condition variable signalled from the ISR"], a: 0, why: "An ISR must never block, so it cannot take a mutex. A lock-free queue with one writer on each side is the standard structure." },

// -------------------------------------------------------------- cm-linalg
{ t: "cm-linalg", d: 1, q: "What does the rank of a matrix tell you?", o: ["How many independent directions it spans", "How many rows it has in total", "Whether or not it can be inverted quickly", "The largest eigenvalue's magnitude"], a: 0, why: "A rank-deficient matrix collapses some direction, so information is lost and the inverse does not exist. Numerically, near-deficiency is what a large condition number reports." },
{ t: "cm-linalg", d: 2, q: "What does the singular value decomposition give you?", o: ["Rotation, scaling and rotation, for any matrix", "The eigenvalues of a symmetric matrix only", "A factorisation into triangular matrices", "The inverse of a square matrix directly"], a: 0, why: "It works for rectangular and rank-deficient matrices, which is why it underlies the pseudoinverse and principal component analysis. The singular values are the scale factors." },
{ t: "cm-linalg", d: 2, q: "What does an LU decomposition produce?", o: ["A lower and an upper triangular factor", "Two orthogonal matrices and a diagonal", "A single triangular matrix and its transpose", "The eigenvectors and eigenvalues together"], a: 0, why: "Solving then costs two triangular substitutions, which is cheap. With partial pivoting it is the standard method for a general square system." },
{ t: "cm-linalg", d: 3, q: "Why is Cholesky preferred when the matrix is symmetric positive definite?", o: ["It is about twice as fast and needs no pivoting", "It is the only method that preserves symmetry", "It gives the eigenvalues as a by-product", "It works when the matrix is singular"], a: 0, why: "Exploiting the structure halves the work and the storage. It also fails cleanly if the matrix is not positive definite, which is a useful check." },
{ t: "cm-linalg", d: 2, q: "What does an eigenvector of a matrix satisfy?", o: ["It is only scaled, not rotated, by the matrix", "It is orthogonal to every other eigenvector", "It has unit length by construction", "It lies in the null space of the matrix"], a: 0, why: "The eigenvalue is that scale factor. Orthogonality of eigenvectors holds for symmetric matrices, not in general." },
{ t: "cm-linalg", d: 2, q: "What does the determinant being zero mean?", o: ["The matrix is singular and not invertible", "The matrix has no real eigenvalues", "The matrix is not symmetric", "The system has infinitely many solutions"], a: 0, why: "It means some direction is collapsed to nothing. Numerically the determinant is a poor test, because it scales badly; the condition number is the practical measure." },
{ t: "cm-linalg", d: 2, q: "What is the pseudoinverse for?", o: ["Solving systems that are over- or under-determined", "Inverting a matrix more quickly than usual", "Finding the eigenvalues of a rectangular matrix", "Computing the determinant of a singular matrix"], a: 0, why: "It gives the least-squares solution when there are too many equations and the minimum-norm one when there are too few. It falls straight out of the SVD." },
{ t: "cm-linalg", d: 3, q: "Why is an iterative solver used for a very large sparse system?", o: ["It never forms the dense factors that would not fit", "Iterative methods are always more accurate", "Direct methods simply cannot handle any sparse matrices", "It converges in a fixed number of steps"], a: 0, why: "Factorising a sparse matrix fills it in, and the factors may be far too large. Conjugate gradient and similar methods only need matrix-vector products." },
{ t: "cm-linalg", d: 2, q: "What does a matrix's condition number bound?", o: ["How much relative error is amplified", "How long the solution will take to compute", "The number of iterations a solver needs", "The magnitude of the largest eigenvalue"], a: 0, why: "It is the ratio of largest to smallest singular value, and it tells you how many digits you will lose. A condition number of ten to the eight costs eight digits." },
{ t: "cm-linalg", d: 2, q: "Why is the Hadamard product not matrix multiplication?", o: ["It multiplies entry by entry, not row by column", "It only applies to square matrices", "It is defined only for the symmetric matrices alone", "It produces a scalar rather than a matrix"], a: 0, why: "Element-wise multiplication is a different operation entirely and does not compose linear maps. Confusing the two is easy in languages where the same symbol does both." },

// -------------------------------------------------------------- cm-float
{ t: "cm-float", d: 1, q: "Why should two floats never be compared with equality?", o: ["Rounding makes exactly equal results unlikely", "Equality is undefined for floating-point types", "The comparison is much slower than subtraction", "Compilers optimise the comparison away"], a: 0, why: "0.1 plus 0.2 is not 0.3 in binary floating point. Comparing against a tolerance, absolute or relative, is what you actually want." },
{ t: "cm-float", d: 2, q: "What is catastrophic cancellation?", o: ["Subtracting nearly equal numbers loses significance", "Adding many numbers of the same sign overflows", "Multiplying by a very small number underflows", "Dividing by a number close to zero gives infinity"], a: 0, why: "The leading digits cancel and what remains is mostly rounding error. Reformulating the expression to avoid the subtraction is the fix, as with the quadratic formula." },
{ t: "cm-float", d: 2, q: "What does Kahan summation compensate for?", o: ["The rounding error lost at each addition", "The overflow that occurs with large sums", "The difference between float and double", "The non-associativity of multiplication"], a: 0, why: "It carries the low-order bits forward in a separate variable, so the error does not accumulate over a long sum. It costs a few extra operations per element." },
{ t: "cm-float", d: 3, q: "Why is floating-point addition not associative?", o: ["Each addition rounds, so the order changes the result", "The standard does not define the order of operations", "The compiler may reorder the additions freely", "Addition overflows differently in each order"], a: 0, why: "That is why a parallel reduction can give a different answer from a serial one, and why fast-math flags change results. It is not a bug in either." },
{ t: "cm-float", d: 2, q: "What is a denormal number?", o: ["A value below the smallest normalised magnitude", "A number whose exponent field is made entirely of ones", "A value that cannot be represented at all", "The result of dividing zero by zero"], a: 0, why: "It fills the gap between the smallest normal number and zero, at reduced precision. On some processors operating on them is dramatically slower, which is why flush-to-zero exists." },
{ t: "cm-float", d: 2, q: "How does NaN compare with other values?", o: ["Every comparison with it is false, including equality", "It is always treated as being less than every other number", "It compares equal only to another NaN", "It raises an exception on any comparison"], a: 0, why: "A NaN is not equal to itself, which is the standard idiom for detecting one. That also means a sort with NaNs in the data can behave very strangely." },
{ t: "cm-float", d: 2, q: "What does the machine epsilon tell you?", o: ["The gap between one and the next representable value", "The smallest number that the format is able to represent", "The largest rounding error in any operation", "The precision of the hardware's divide unit"], a: 0, why: "It is about 1.2 times ten to the minus seven for single precision. Relative tolerances are usually expressed as a small multiple of it." },
{ t: "cm-float", d: 3, q: "Why does a fixed absolute tolerance fail for large values?", o: ["The spacing between representable values grows", "Large values are stored with a different exponent", "The tolerance is applied before rounding", "Large values are more likely to be denormal"], a: 0, why: "At a million, consecutive floats differ by far more than a tolerance chosen for values near one. A relative tolerance, or a units-in-the-last-place comparison, scales correctly." },
{ t: "cm-float", d: 2, q: "What does a negative variance from a computed formula indicate?", o: ["Cancellation in the naive sum-of-squares formula", "A genuine property of the data set", "An overflow in the accumulator", "A mistake in the number of degrees of freedom"], a: 0, why: "Subtracting the square of the mean from the mean of the squares cancels badly. Welford's online algorithm avoids the subtraction entirely." },
{ t: "cm-float", d: 2, q: "Why can the same code give different results on two machines?", o: ["Different instruction selection and rounding of intermediates", "The standard leaves the whole format entirely implementation defined", "Compilers use different values for pi", "Memory layout changes the arithmetic"], a: 0, why: "Fused multiply-add, extended-precision registers and vectorised reductions all change the rounding. Bit-exact reproducibility has to be asked for explicitly." },

// -------------------------------------------------------------- cm-stats
{ t: "cm-stats", d: 1, q: "How does the standard error of the mean scale with sample count?", o: ["As one over the square root of N", "Linearly with N", "As the logarithm of N", "It does not depend on N in any way"], a: 0, why: "Four times the samples halves the error, which is why the last digit is so expensive. Systematic error does not shrink at all." },
{ t: "cm-stats", d: 2, q: "What does a 95 percent confidence interval mean?", o: ["95 percent of such intervals would contain the true value", "There is a 95 percent chance the value is inside this one", "95 percent of the data lies within the interval", "The estimate is accurate to within 5 percent"], a: 0, why: "The statement is about the procedure over repeated experiments, not about this particular interval. The Bayesian credible interval is the one that makes the direct probability claim." },
{ t: "cm-stats", d: 2, q: "What does zero correlation between two variables imply?", o: ["No linear relationship, but possibly a nonlinear one", "That the two variables are independent", "That neither one of the two variables affects the other", "That the variables have equal variance"], a: 0, why: "A perfect parabola has zero correlation. Independence implies zero correlation but not the other way round." },
{ t: "cm-stats", d: 3, q: "Why does the central limit theorem matter in practice?", o: ["Sums of many effects become Gaussian regardless of source", "It proves that all measurements are Gaussian", "It guarantees that the sample mean always equals the true mean", "It makes the standard deviation easy to compute"], a: 0, why: "It justifies Gaussian assumptions for aggregated noise even when each contribution is not. It says nothing about individual measurements or heavy tails." },
{ t: "cm-stats", d: 2, q: "What does a p-value actually tell you?", o: ["How surprising the data is if the null hypothesis holds", "The probability that the null hypothesis is actually true", "The size of the effect that was measured", "The probability the result will replicate"], a: 0, why: "It is a statement about the data given a hypothesis, not about the hypothesis given the data. Confusing the two is the commonest misreading in the literature." },
{ t: "cm-stats", d: 2, q: "Why is the median often preferred to the mean?", o: ["It is far less affected by outliers", "It is faster to compute for large data sets", "It always equals the most common value", "It has a smaller standard error"], a: 0, why: "One extreme value moves the mean in proportion to its size and barely moves the median. For a symmetric distribution with no outliers, the mean is the more efficient estimator." },
{ t: "cm-stats", d: 2, q: "What does a histogram's bin width control?", o: ["The trade between noise and detail", "The total area under the histogram", "The number of samples that can be shown", "The accuracy of the estimated mean"], a: 0, why: "Too narrow and it is noise; too wide and structure disappears. Trying several widths is the honest way to look at a distribution." },
{ t: "cm-stats", d: 3, q: "Why does a rare event with a good test still give mostly false alarms?", o: ["The base rate is far smaller than the false positive rate", "The test's sensitivity is too low to be useful", "The specificity has been measured incorrectly", "The sample size was simply insufficient for a good estimate"], a: 0, why: "With a prevalence of one in ten thousand and a one percent false positive rate, alarms outnumber real cases about a hundred to one. Nobody acts on a system that cries wolf." },
{ t: "cm-stats", d: 2, q: "What is the difference between standard deviation and standard error?", o: ["One describes the data, the other the estimate of the mean", "One uses N and the other N minus one", "One is for whole populations and the other one is for samples", "One is squared and the other is not"], a: 0, why: "The standard deviation does not shrink with more data; the standard error does. Quoting the wrong one is a common way to overstate or understate precision." },
{ t: "cm-stats", d: 2, q: "Why does averaging not remove a systematic error?", o: ["It is the same in every sample, so it does not cancel", "The average is computed over too few samples", "Systematic errors also grow as the square root of N itself", "The error is correlated with the measurement"], a: 0, why: "Averaging attacks the random part and leaves anything constant exactly where it was. Separating the two requires measuring a known input, which is what calibration is." },

// ------------------------------------------------------------ cm-sorting
{ t: "cm-sorting", d: 1, q: "What is the lower bound for a comparison sort?", o: ["Order N log N comparisons", "Order N comparisons", "Order N squared comparisons", "Order log N comparisons"], a: 0, why: "It follows from the number of possible orderings and the information a comparison provides. Counting and radix sorts beat it by not comparing." },
{ t: "cm-sorting", d: 2, q: "What does a stable sort preserve?", o: ["The original relative order of equal elements", "The positions of the smallest elements", "The same result on every run", "The original array, leaving it unmodified"], a: 0, why: "It lets you sort by one key and then another to get a compound ordering. Quicksort is not stable, which is why merge sort is chosen when it matters." },
{ t: "cm-sorting", d: 2, q: "Why is introsort the usual standard library choice?", o: ["Quicksort speed with a heapsort worst-case guarantee", "It is the only stable sort with N log N behaviour", "It uses less memory than any other algorithm", "It is optimal for already-sorted input"], a: 0, why: "It switches to heapsort past a depth limit and to insertion sort for small ranges. That gives the average-case speed without quicksort's quadratic worst case." },
{ t: "cm-sorting", d: 3, q: "What causes quicksort's quadratic worst case?", o: ["Consistently bad pivots, such as sorted input", "Far too many duplicate elements inside the array", "Recursion depth exceeding the stack", "An array that is too large for the cache"], a: 0, why: "A first-element pivot on sorted data splits one element off at a time. Median-of-three, random pivots or a heapsort fallback all prevent it." },
{ t: "cm-sorting", d: 2, q: "When does insertion sort beat everything else?", o: ["On small or nearly-sorted ranges", "On large arrays of random integers", "When the comparison function is expensive", "When memory is severely constrained"], a: 0, why: "Its constant factor is tiny and it is O(n) on nearly-sorted data. That is why every good library uses it below a threshold." },
{ t: "cm-sorting", d: 2, q: "What does radix sort require of its keys?", o: ["That they can be split into fixed-size digits", "That they are already at least partially sorted", "That there are no duplicate keys", "That they fit in a machine word"], a: 0, why: "It processes digit by digit and never compares two keys, so it escapes the comparison bound. Its cost depends on the key width rather than on log N." },
{ t: "cm-sorting", d: 2, q: "What is nth_element for?", o: ["Finding the kth smallest without fully sorting", "Sorting only the first n elements of a range", "Removing the nth element from a container", "Partitioning a range into n equal parts"], a: 0, why: "It partitions in linear time on average, which is far cheaper than sorting to find a median. Using a full sort for that is a common and avoidable waste." },
{ t: "cm-sorting", d: 3, q: "Why does merge sort suit external sorting?", o: ["It reads and writes sequentially in large runs", "It requires no additional memory at all", "It is the fastest algorithm on any hardware", "It can sort data that does not fit in a word"], a: 0, why: "Sequential access is what disks and network storage are good at, and merging streams needs only a small buffer per run. Quicksort's random access is exactly wrong there." },
{ t: "cm-sorting", d: 2, q: "What does sorting by a computed key repeatedly cost you?", o: ["The key is recomputed on every comparison", "The sort becomes unstable", "The comparison function may not be transitive", "The sort cannot be parallelised"], a: 0, why: "An expensive key computed inside the comparator runs O(n log n) times. Computing it once into a temporary array, the decorate-sort-undecorate pattern, fixes it." },
{ t: "cm-sorting", d: 2, q: "Why must a comparator define a strict weak ordering?", o: ["Otherwise the sort may crash or loop", "The sort would become unstable", "The result would merely be in the wrong order", "The comparator could not be inlined"], a: 0, why: "Implementations rely on the ordering's properties to bound their loops, so a comparator that says a is less than a can read past the end of the array. It is undefined behaviour, not just a wrong answer." },

// ------------------------------------------------------------- cm-graphs
{ t: "cm-graphs", d: 1, q: "What does breadth-first search find in an unweighted graph?", o: ["The shortest path in number of edges", "The cheapest path by total weight", "Any path between the two nodes", "The path visiting the fewest branches"], a: 0, why: "Exploring level by level means the first time you reach a node is by a shortest route. With weights you need Dijkstra instead." },
{ t: "cm-graphs", d: 2, q: "When does Dijkstra's algorithm fail?", o: ["When any edge weight is negative", "When the graph contains a cycle", "When the graph is disconnected", "When there are several shortest paths"], a: 0, why: "It assumes that once a node is finalised no cheaper route exists, which a negative edge can violate. Bellman-Ford handles negative weights at greater cost." },
{ t: "cm-graphs", d: 2, q: "What does a topological sort produce?", o: ["An ordering respecting every dependency", "The shortest path through the whole graph", "A partition of the graph into components", "The nodes sorted by their degree"], a: 0, why: "It only exists for a directed acyclic graph, and failing to produce one proves there is a cycle. Build systems and initialisation ordering are the classic uses." },
{ t: "cm-graphs", d: 3, q: "What does a failed topological sort tell you?", o: ["There is a cycle among the remaining nodes", "The graph has more than one single component", "Some node has no incoming edges", "The graph is too large to sort"], a: 0, why: "If nodes remain but none has zero in-degree, they form a cycle. That is exactly how a circular dependency is detected." },
{ t: "cm-graphs", d: 2, q: "When is an adjacency matrix better than a list?", o: ["For dense graphs or constant-time edge queries", "For very large sparse graphs", "When the graph changes frequently", "When memory is severely constrained"], a: 0, why: "It costs N squared regardless of edge count, which is fine when the graph is dense. A list is proportional to the edges, which is what a sparse graph wants." },
{ t: "cm-graphs", d: 2, q: "What does A-star add to Dijkstra?", o: ["A heuristic estimate of the remaining cost", "Support for negative edge weights", "The ability to handle dynamic graphs", "A guarantee of finding all shortest paths"], a: 0, why: "An admissible heuristic focuses the search towards the goal without losing optimality. With a zero heuristic it degenerates to Dijkstra exactly." },
{ t: "cm-graphs", d: 2, q: "What is a minimum spanning tree?", o: ["The cheapest set of edges connecting every node", "The shortest path between every pair of nodes", "The tree with the fewest edges in the graph", "The subgraph with the lowest average degree"], a: 0, why: "Kruskal's and Prim's algorithms both find it, and it is the natural answer to laying cable or pipework. It is not the same as shortest paths between pairs." },
{ t: "cm-graphs", d: 3, q: "Why does a union-find structure suit Kruskal's algorithm?", o: ["It answers same-component queries almost in constant time", "It keeps every one of the edges sorted as they are all added", "It detects negative cycles automatically", "It stores the tree in a compact array form"], a: 0, why: "The algorithm needs to know whether adding an edge would create a cycle, which is a connectivity query. With path compression and union by rank it is effectively constant." },
{ t: "cm-graphs", d: 2, q: "What does the diameter of a graph measure?", o: ["The longest shortest path between any two nodes", "The total number of the edges in the entire graph", "The maximum degree of any single node", "The number of components in the graph"], a: 0, why: "It bounds how far information has to travel, which matters for a network or a distributed algorithm. Computing it exactly means all-pairs shortest paths." },
{ t: "cm-graphs", d: 2, q: "Why is depth-first search used for cycle detection?", o: ["A back edge to a node on the current stack is a cycle", "It visits every node in the fewest steps", "It requires less memory than breadth-first search", "It naturally produces a topological ordering"], a: 0, why: "Tracking which nodes are on the recursion stack makes the test immediate. The same traversal also gives you the strongly connected components with a little extra bookkeeping." },

// ----------------------------------------------------------- cm-numerics
{ t: "cm-numerics", d: 2, q: "What makes a differential equation stiff?", o: ["A fast decaying mode forcing tiny steps for stability", "A solution that changes very rapidly all the way through", "A system with more equations than unknowns", "An equation whose derivative cannot be computed"], a: 0, why: "The step is limited by stability rather than by accuracy, which is enormously wasteful. Implicit methods are stable at much larger steps and are the answer." },
{ t: "cm-numerics", d: 2, q: "What does forward Euler do to an oscillator's amplitude?", o: ["It grows steadily, because energy is added each step", "It decays away steadily, because the energy is all lost", "It stays exactly constant as it should", "It oscillates about the correct value"], a: 0, why: "The error is systematically outward for a rotation, so the orbit spirals out. A symplectic integrator preserves the energy far better at the same cost." },
{ t: "cm-numerics", d: 3, q: "What does an implicit method cost you?", o: ["A nonlinear system solved at every step", "Accuracy compared with an explicit method", "The ability to handle nonlinear equations", "Stability at large step sizes"], a: 0, why: "It usually needs a Jacobian and a Newton iteration per step, so each step is far more expensive. For a stiff problem that still wins by an enormous margin." },
{ t: "cm-numerics", d: 2, q: "How does an adaptive step-size method estimate its error?", o: ["Two estimates of the same step at different orders", "By comparing against an analytic solution", "By halving the step and comparing results", "By monitoring the residual of the governing equation"], a: 0, why: "The difference between the two orders is a local error estimate that costs almost nothing extra. Runge-Kutta-Fehlberg and Dormand-Prince are built on exactly this." },
{ t: "cm-numerics", d: 2, q: "How do you check that a simulation has converged?", o: ["Halve the step and see whether the answer changes", "Confirm the residual is below machine epsilon", "Run it twice and compare the two results", "Check that the energy is exactly conserved"], a: 0, why: "If the answer changes materially, the result is not converged and any physical conclusion drawn from it is unsafe. If it does not, the remaining error is in the model." },
{ t: "cm-numerics", d: 2, q: "Why does a smaller starting error not fix an unstable scheme?", o: ["Instability amplifies whatever error exists", "The scheme is stable at double precision", "The initial condition is not the problem", "Smaller errors take longer to grow"], a: 0, why: "Exponential growth applied to a smaller seed merely delays the blow-up. Stability is a property of the scheme and the step, not of the initial data." },
{ t: "cm-numerics", d: 3, q: "What does the CFL condition constrain?", o: ["The step size relative to how fast information travels", "The total number of steps that any simulation is allowed", "The precision required for the state variables", "The smoothness of the initial conditions"], a: 0, why: "Information must not cross more than one cell per step, or the scheme cannot be stable. Halving the spatial cell size therefore forces the time step down too." },
{ t: "cm-numerics", d: 2, q: "What is Newton's method's main weakness?", o: ["It needs a good starting point to converge", "It converges only linearly near the root", "It cannot handle functions with several roots", "It requires the function to be linear"], a: 0, why: "Convergence is quadratic once close, and it can diverge or cycle from a poor start. Bracketing methods are slower and far more robust." },
{ t: "cm-numerics", d: 2, q: "Why is a finite-difference derivative step size a compromise?", o: ["Too large is truncation error, too small is cancellation", "Too large a step overflows, and too small a step underflows", "The step must match the function's period", "Larger steps are always more accurate"], a: 0, why: "The optimum for a forward difference is around the square root of machine epsilon. Central differences are more accurate and cost an extra evaluation." },
{ t: "cm-numerics", d: 2, q: "What does a symplectic integrator preserve?", o: ["A conserved quantity close to the true energy", "The exact trajectory of the system", "The step size right throughout the whole simulation", "The sign of every state variable"], a: 0, why: "It bounds the energy error over very long runs rather than letting it drift. That is why it is the choice for orbital mechanics and molecular dynamics." },

// ------------------------------------------------------------- cm-interp
{ t: "cm-interp", d: 2, q: "What is the Runge phenomenon?", o: ["High-order polynomials oscillating near the interval ends", "Interpolation failing when points are too close", "The error growing linearly with the whole number of points used", "Splines diverging when the data is noisy"], a: 0, why: "It happens with equally spaced points, and adding more makes it worse. Chebyshev spacing, or a piecewise low-order fit, avoids it." },
{ t: "cm-interp", d: 2, q: "What does a cubic spline guarantee?", o: ["Continuity of value, first and second derivative", "That the curve passes near, not through, the points", "That the curve never leaves the data's range", "The lowest possible total curvature"], a: 0, why: "That smoothness is what makes it look right, and it is also why a change anywhere propagates along the whole spline. It can also invent oscillation between noisy points." },
{ t: "cm-interp", d: 3, q: "Why choose a monotone cubic over a natural cubic spline?", o: ["It never invents extrema between data points", "It is smoother across the whole interval", "It requires fewer coefficients to store", "It extrapolates more reliably outside the range"], a: 0, why: "By giving up second-derivative continuity it avoids overshoot entirely. For data that is physically monotone, that matters more than smoothness." },
{ t: "cm-interp", d: 2, q: "What is linear interpolation's frequency response?", o: ["A triangle in time, so sinc squared in frequency", "A brick wall response right at half the sample rate", "Flat across the whole band", "A single pole low-pass response"], a: 0, why: "It attenuates high frequencies noticeably, which is why it softens an upsampled signal. A polyphase filter designed to a specification does far better." },
{ t: "cm-interp", d: 2, q: "When is sinc interpolation exact?", o: ["When the signal is bandlimited and infinitely sampled", "When the samples are equally spaced", "When the signal is periodic", "When the sample rate happens to be an exact power of two"], a: 0, why: "Both conditions fail in practice, so windowed approximations are used. The theorem is the ideal that the practical methods approach." },
{ t: "cm-interp", d: 2, q: "Why must you filter before downsampling?", o: ["Content above the new Nyquist folds in permanently", "The interpolation would otherwise be inaccurate", "The samples would be unevenly spaced", "Downsampling changes the signal's amplitude"], a: 0, why: "Once aliased, the content is indistinguishable from real signal and cannot be removed. The filter has to come first, not after." },
{ t: "cm-interp", d: 3, q: "What does a Lagrange fractional-delay filter approximate?", o: ["The ideal sinc interpolator over a short window", "A linear phase low-pass filter", "The derivative of the signal at a point", "A polynomial fit passing through all the samples"], a: 0, why: "It is maximally flat at DC, which makes it excellent for small delays and poor near Nyquist. Choosing the order trades passband width against cost." },
{ t: "cm-interp", d: 2, q: "Why is extrapolation more dangerous than interpolation?", o: ["The model is unconstrained outside the data", "Extrapolation is computationally more expensive", "It requires a higher-order polynomial", "The error cannot be estimated at all"], a: 0, why: "Inside the data the fit is anchored on both sides; outside it, nothing holds it. A polynomial that fits beautifully within range can diverge immediately beyond it." },
{ t: "cm-interp", d: 2, q: "What does a B-spline basis give you over interpolating splines?", o: ["Local control, since each basis function is compact", "An exact fit through every data point", "A lower-order representation of the same curve", "Guaranteed monotonicity of the result"], a: 0, why: "Moving one control point changes only a small span of the curve, which is what makes it usable in design tools. It approximates rather than interpolates." },
{ t: "cm-interp", d: 2, q: "Why is bilinear image interpolation blurry?", o: ["It is a poor low-pass filter with a wide transition", "It averages too many neighbouring pixels", "It ignores every one of the diagonal neighbours entirely", "It operates on integers rather than floats"], a: 0, why: "Its frequency response rolls off well before Nyquist, so detail is lost. Bicubic and Lanczos are longer kernels with a sharper response." },

// ------------------------------------------------------------ cm-fourier
{ t: "cm-fourier", d: 2, q: "What does Parseval's theorem state?", o: ["Total energy in time equals total energy in frequency", "The transform of a real signal is symmetric", "Convolution in time is multiplication in frequency", "The transform preserves the mean of the signal"], a: 0, why: "It holds up to the known scaling factor for the convention in use. It is a useful check that a transform implementation is correctly normalised." },
{ t: "cm-fourier", d: 2, q: "What does the uncertainty principle say about a signal?", o: ["Narrow in one domain means wide in the other", "A signal cannot be measured exactly", "Frequency resolution improves with sample rate", "Phase and magnitude cannot both be known"], a: 0, why: "A short pulse has a broad spectrum, which is why a wideband transducer is needed for a sharp pulse. It is a mathematical fact, not an instrumental limitation." },
{ t: "cm-fourier", d: 3, q: "What is the DFT, viewed as linear algebra?", o: ["Multiplication by a matrix of roots of unity", "A least-squares fit of sinusoids to the data", "A change of basis into orthogonal polynomials", "A convolution with a bank of matched filters"], a: 0, why: "It is a projection onto a basis of complex exponentials, so it is an orthogonal change of basis. The FFT is just a fast way to apply that matrix." },
{ t: "cm-fourier", d: 2, q: "Why does the DFT assume the signal is periodic?", o: ["A finite transform implies a periodic extension", "Real signals are always periodic", "The algorithm requires a repeating pattern", "Periodicity makes the transform invertible"], a: 0, why: "That implied repetition is what creates the discontinuity at the join and hence spectral leakage. Windowing tapers the ends to remove it." },
{ t: "cm-fourier", d: 2, q: "What does the transform of a rectangular pulse look like?", o: ["A sinc, with the first null at one over the width", "Another rectangle of exactly the same width as before", "A Gaussian centred at the origin", "An exponential decay from DC"], a: 0, why: "The wider the pulse, the narrower the sinc, which is the uncertainty principle made concrete. It is also why a rectangular window has such poor sidelobes." },
{ t: "cm-fourier", d: 2, q: "What is the transform of a Gaussian?", o: ["Another Gaussian", "A sinc function", "A rectangular function", "An exponential decay"], a: 0, why: "It is the unique shape that is its own transform, up to scaling. That is why it appears as the minimum-uncertainty window in time-frequency analysis." },
{ t: "cm-fourier", d: 3, q: "Why is the FFT of a real signal computed more cheaply?", o: ["The conjugate symmetry halves the independent values", "Real arithmetic is faster than complex on all hardware", "The imaginary part is discarded before transforming", "Only half the frequencies are of interest"], a: 0, why: "The negative-frequency half is determined by the positive half, so a real FFT computes only what is needed. It saves roughly half the time and memory." },
{ t: "cm-fourier", d: 2, q: "What does a shift in time do to the spectrum?", o: ["Multiplies it by a linear phase ramp", "Shifts the spectrum by the same amount", "Leaves the spectrum entirely unchanged", "Scales the magnitude by the shift"], a: 0, why: "The magnitude is unchanged and only the phase moves, which is why magnitude spectra are shift invariant. It is also how a fractional delay is applied in the frequency domain." },
{ t: "cm-fourier", d: 2, q: "What does the discrete cosine transform offer over the DFT?", o: ["Real output and better energy compaction", "Exact reconstruction from fewer samples", "A faster algorithm than the FFT", "Immunity to spectral leakage"], a: 0, why: "Its implied even extension avoids the discontinuity a DFT's periodic extension creates. That compaction is why it underlies JPEG and many audio codecs." },
{ t: "cm-fourier", d: 2, q: "Why does multiplying by a window convolve the spectrum?", o: ["Multiplication in one domain is convolution in the other", "Windows are designed to smooth the spectrum", "The window changes the effective sample rate", "The transform becomes nonlinear for any finite record length"], a: 0, why: "The spectrum is smeared by the window's own transform, which is why the main lobe width matters. It is the same duality that makes filtering work." },

// --------------------------------------------------------------- cm-opt2
{ t: "cm-opt2", d: 2, q: "What does gradient descent step along?", o: ["The negative gradient, downhill", "The positive gradient, uphill", "The direction of steepest curvature", "A randomly chosen coordinate direction"], a: 0, why: "The gradient points uphill, so you subtract it. The step size is the whole difficulty, since too large diverges and too small crawls." },
{ t: "cm-opt2", d: 2, q: "What does the Levenberg-Marquardt damping parameter interpolate between?", o: ["Gauss-Newton and gradient descent", "First-order and second-order convergence", "Batch and stochastic updates", "Constrained and unconstrained solutions"], a: 0, why: "Large damping gives a small, safe gradient step and small damping gives a fast Newton-like one. Adapting it per iteration is what makes the method robust." },
{ t: "cm-opt2", d: 3, q: "Why does a convex problem behave so much better?", o: ["Any local minimum is also the global one", "It can always be solved in closed form", "The gradient is constant everywhere", "It has no constraints to satisfy"], a: 0, why: "For a nonconvex problem the answer depends on where you started, so the initial guess is part of the method. Recognising convexity is worth a great deal." },
{ t: "cm-opt2", d: 2, q: "What does a line search do?", o: ["Chooses how far to move along a chosen direction", "Selects which direction to move in", "Decides when the optimisation has converged", "Searches for a better starting point"], a: 0, why: "It separates the direction question from the step-length question, which makes both easier. Wolfe conditions are the usual acceptance test." },
{ t: "cm-opt2", d: 2, q: "What does a parameter sitting on its bound suggest?", o: ["The data wants to push it further", "The optimiser has converged correctly", "The bound was chosen too generously", "The parameter is not identifiable"], a: 0, why: "The bound is doing the fitting rather than the data, so the model or the bound is wrong. It is worth investigating rather than accepting." },
{ t: "cm-opt2", d: 2, q: "Why should parameters be scaled before optimising?", o: ["The penalty and steps treat all coordinates alike", "Unscaled parameters cannot be differentiated", "Scaling guarantees the problem becomes convex", "The optimiser only accepts values near one"], a: 0, why: "A parameter in nanometres and another in metres give a badly conditioned problem where a single step size cannot suit both. It is the same reason regularisation needs scaled features." },
{ t: "cm-opt2", d: 3, q: "What does the Hessian tell you at a stationary point?", o: ["Whether it is a minimum, maximum or saddle", "How far the point is from the global optimum", "The gradient's magnitude at that point", "How many iterations remain"], a: 0, why: "Positive definite means a minimum, and an indefinite Hessian means a saddle. Its condition number also predicts how slowly gradient descent will crawl." },
{ t: "cm-opt2", d: 2, q: "What does stochastic gradient descent trade?", o: ["Noisy steps for far cheaper iterations", "Accuracy for guaranteed convergence", "Memory for computation time", "Convexity for a faster algorithm"], a: 0, why: "Using a minibatch gradient is much cheaper and the noise even helps escape shallow minima. The step size schedule then has to shrink for it to settle." },
{ t: "cm-opt2", d: 2, q: "What does an iteration limit reached without convergence mean?", o: ["The result may be nowhere near a minimum", "The problem has no solution", "The tolerance was set too tight", "The gradient was computed incorrectly"], a: 0, why: "Treating the returned value as an answer is how bad fits get published. Checking the exit status, not just the returned parameters, is basic hygiene." },
{ t: "cm-opt2", d: 2, q: "Why check a hand-written gradient against finite differences?", o: ["A wrong gradient makes the optimiser fail silently", "Finite differences are more accurate", "The optimiser requires both of them to be supplied anyway", "It speeds up the first few iterations"], a: 0, why: "The optimiser will happily converge to nonsense or stall, with no error message. A gradient check at a random point costs minutes and saves days." },

// -------------------------------------------------------------- cm-bayes
{ t: "cm-bayes", d: 2, q: "What is the difference between a likelihood and a posterior?", o: ["Likelihood is data given parameters, posterior the reverse", "Likelihood is normalised and the posterior is not", "Likelihood applies to discrete and posterior to continuous data", "The posterior includes the evidence and the likelihood does not"], a: 0, why: "Bayes' rule connects the two through the prior and the evidence. Confusing them is the root of most misinterpreted statistics." },
{ t: "cm-bayes", d: 2, q: "What does the evidence term do in Bayes' rule?", o: ["Normalises the posterior so it integrates to one", "It weights the prior against the likelihood function", "Measures how surprising the data is", "Determines the number of parameters"], a: 0, why: "It is the marginal likelihood, and comparing it between models is the Bayesian form of model selection. For parameter estimation it often cancels and can be ignored." },
{ t: "cm-bayes", d: 3, q: "When does maximum a posteriori coincide with maximum likelihood?", o: ["When the prior is uniform over the region of interest", "When the data set is very large", "When the likelihood is Gaussian", "Whenever all of the parameters are entirely independent"], a: 0, why: "A flat prior contributes no gradient, so the two optima coincide. With enough data the likelihood dominates any reasonable prior anyway." },
{ t: "cm-bayes", d: 2, q: "What is a conjugate prior?", o: ["One that keeps the posterior in the same family", "One chosen to have no influence on the result", "One derived from a previous experiment", "One that guarantees the posterior is Gaussian"], a: 0, why: "Updating becomes a closed-form parameter change rather than an integral, which is why they appear everywhere in analytic Bayesian work. Modern sampling methods have made them less essential." },
{ t: "cm-bayes", d: 2, q: "What does a Kalman filter's predict step compute, in Bayesian terms?", o: ["The prior for the next time step", "The likelihood of the next measurement", "The posterior given all data so far", "The evidence for the current model"], a: 0, why: "It propagates the current belief through the motion model, which is exactly a prior for the next update. The update step then applies the measurement likelihood." },
{ t: "cm-bayes", d: 2, q: "Why is a prior not simply an admission of bias?", o: ["It states assumptions explicitly rather than hiding them", "Priors are always deliberately chosen so as to be uninformative", "The data overwhelms any prior eventually", "A prior can be derived from first principles"], a: 0, why: "Every method has assumptions; the Bayesian one writes them down where they can be argued with. Sensitivity to the prior is itself a reportable result." },
{ t: "cm-bayes", d: 3, q: "What does MCMC give you that an optimiser does not?", o: ["Samples from the whole posterior, not just its peak", "A guaranteed global optimum", "A considerably faster route to the maximum value itself", "An exact analytic solution"], a: 0, why: "Uncertainty and correlations between parameters come out directly. The cost is convergence diagnostics and a great deal more computation." },
{ t: "cm-bayes", d: 2, q: "What does a credible interval assert?", o: ["The parameter lies inside with a stated probability", "The procedure covers the truth that often", "The data lies inside that range", "The estimate is accurate to precisely that stated precision"], a: 0, why: "It makes the direct probability statement people usually think a confidence interval makes. That difference is the clearest practical distinction between the two frameworks." },
{ t: "cm-bayes", d: 2, q: "Why does a base rate matter so much in a diagnostic test?", o: ["A rare condition makes most positives false", "It changes the test's sensitivity", "It determines the test's specificity", "It affects the way the test itself is calibrated"], a: 0, why: "With a low prevalence, even a very specific test produces alarms that are mostly wrong. That is Bayes' rule applied directly, and it is deeply unintuitive." },
{ t: "cm-bayes", d: 2, q: "What does marginalising over a nuisance parameter do?", o: ["Integrates it out, accounting for its uncertainty", "Fixes it at its most likely value", "Removes it from the whole model altogether entirely", "Constrains it to a narrow range"], a: 0, why: "It propagates the uncertainty rather than pretending you know the value. Plugging in a point estimate understates the uncertainty in everything else." },

// ----------------------------------------------------------------- cm-ml
{ t: "cm-ml", d: 1, q: "When should the test set be used?", o: ["Once, at the very end", "For tuning hyperparameters", "After every training epoch", "Whenever the validation score plateaus"], a: 0, why: "It estimates performance on unseen data, and using it to make decisions turns it into a training set. The validation set is what tuning is for." },
{ t: "cm-ml", d: 2, q: "What does a large gap between training and validation score mean?", o: ["Overfitting: it has memorised rather than generalised", "Underfitting: the model is too simple", "The validation set is simply far too small to be reliable", "The learning rate is set too low"], a: 0, why: "High variance means it has learned the training set's noise. More data, regularisation or a smaller model are the usual responses." },
{ t: "cm-ml", d: 2, q: "What is data leakage?", o: ["Information from the test set influencing training", "Training data escaping into a public repository", "Memory not being freed between epochs", "Labels being corrupted during preprocessing"], a: 0, why: "Fitting a scaler on the whole data set before splitting is the classic instance, and the reported score is then optimistic. It is one of the commonest reasons a model fails in production." },
{ t: "cm-ml", d: 3, q: "What does the bias-variance decomposition describe?", o: ["Error from an over-simple model against sensitivity to the sample", "The split between the systematic and the random parts of measurement error", "The difference between training and inference cost", "The trade between model size and training time"], a: 0, why: "Reducing one usually raises the other, which is why model selection is a balance rather than a maximisation. More data shifts the whole curve favourably." },
{ t: "cm-ml", d: 2, q: "Why is accuracy a poor metric for imbalanced data?", o: ["Predicting the majority class always scores highly", "Accuracy cannot be computed for rare classes", "It ignores the confidence of each prediction", "It requires the classes to be balanced to be defined"], a: 0, why: "A model that detects nothing of interest can score ninety-nine percent. Precision, recall and the area under the operating characteristic are the honest measures." },
{ t: "cm-ml", d: 2, q: "What does cross-validation give you over a single split?", o: ["A less noisy estimate, using every point for validation once", "A guarantee that the model will always generalise to unseen data", "A faster evaluation than a single split", "The ability to skip the test set entirely"], a: 0, why: "It averages over several splits, which matters most when the data set is small. It costs k times the training time." },
{ t: "cm-ml", d: 2, q: "When do gradient-boosted trees usually beat a neural network?", o: ["On small or medium tabular data sets", "On raw audio and image data", "When the data has a strong sequential structure", "When millions of examples are available"], a: 0, why: "They are far cheaper to train and to explain, and they handle mixed feature types naturally. Reaching for a deep network on a spreadsheet is usually the wrong instinct." },
{ t: "cm-ml", d: 3, q: "Why does regularisation require scaled features?", o: ["The penalty treats every coefficient on the same scale", "Unscaled features cannot be differentiated", "The optimiser rejects any features outside a given range", "Scaling is what makes the problem convex"], a: 0, why: "A feature measured in millimetres gets a coefficient a thousand times larger than one in metres, and the penalty punishes it accordingly. Scaling makes the penalty mean what you intended." },
{ t: "cm-ml", d: 2, q: "What does early stopping guard against?", o: ["Continuing to train past the best validation score", "The learning rate decaying too quickly", "The model diverging during the very first few epochs", "Overflow in the loss computation"], a: 0, why: "It is a cheap form of regularisation that needs no extra hyperparameter beyond the patience. It does mean the validation set is influencing training, which is worth remembering." },
{ t: "cm-ml", d: 2, q: "Why is a held-out score from a model that saw the data meaningless?", o: ["The score measures memorisation, not generalisation", "The score cannot be computed reliably", "Held-out data must always be labelled", "The model will simply be far too slow to evaluate at all"], a: 0, why: "Any model with enough capacity can reproduce data it has seen. The whole purpose of holding data out is defeated by looking at it." },

]);
