/* Balanced option lengths, and every distractor is a real misconception. See
 * the note at the top of bank_embc12.js: the reasoning belongs in `why`, which
 * is shown as soon as you answer, not inside the correct option. */

BANKS["Embedded C"] = BANKS["Embedded C"].concat([

// -------------------------------------------------------- emb-test-first
{ t: "emb-test-first", d: 1, q: "Why must you see each assertion fail before trusting it?", o: ["It is a convention that most teams happen to follow", "A test that cannot fail reports success forever", "Coverage tools need a failing run to calibrate against", "The framework will not register it until it has failed"], a: 1, why: "<p>And you will believe it. Break the implementation deliberately and confirm the assertion catches it.</p><p>Every assertion should have been red at least once, or you do not actually know it is connected to the thing it claims to check.</p>" },
{ t: "emb-test-first", d: 2, q: "Why does a test program's exit code matter?", o: ["It is logged, so the history shows which run failed", "Non-zero means failure, which make and CI act on", "It becomes the return value main hands to the shell", "It selects which output format the runner produces"], a: 1, why: "<p>Anything that prints FAILED and returns zero stays green in CI forever.</p><p>The exit code is the interface between the test and everything that runs it.</p>" },
{ t: "emb-test-first", d: 2, q: "Which compiler builds a host unit test for firmware logic?", o: ["The cross compiler, so the test matches the target exactly", "The host compiler, so it runs with no board attached", "Either, since the logic under test is the same code", "A dedicated test compiler that instruments the build"], a: 1, why: "<p>That is the entire point: the logic is exercised in a fast loop, in milliseconds, without hardware.</p><p>Running on target is a separate and also necessary activity, not a replacement.</p>" },
{ t: "emb-test-first", d: 2, q: "Why run the unit suite under -fsanitize=address,undefined?", o: ["They speed the suite up by skipping redundant checks", "They turn a silent overrun into a loud failure", "They replace the need for boundary tests entirely", "They measure which lines the suite actually reached"], a: 1, why: "<p>A one-byte overrun or a signed overflow becomes a stack trace instead of a pass, and a few times the runtime is nothing on a test suite.</p><p>On firmware it is the highest-value setting available, because the same overrun on target corrupts something unrelated and reaches the field as a mystery.</p>" },
{ t: "emb-test-first", d: 2, q: "What does <code>#cond</code> do in a CHECK macro?", o: ["Evaluates the condition a second time, as a safety net", "Stringises it, so the output names the expression", "Comments it out when NDEBUG is defined", "Makes it a compile-time check rather than runtime"], a: 1, why: "<p>Without it you write the expression twice, once to test and once to print, and they drift apart.</p><p>It is most of what a real framework's assertion macros do, which is why twenty lines of your own macro is a legitimate way to start.</p>" },
{ t: "emb-test-first", d: 3, q: "Why should a test contain no branches?", o: ["Branches make the suite measurably slower to run", "It checks different things on different runs", "Coverage tools cannot attribute a branched test", "The framework counts each branch as its own test"], a: 1, why: "<p>Which is how a test quietly stops testing: a conditional assertion can be satisfied by the branch you never take.</p><p>If two cases need different assertions, that is two tests.</p>" },
{ t: "emb-test-first", d: 3, q: "Which values should a test target?", o: ["The middle of the valid range, where real inputs sit", "The boundaries: zero, one, full scale, one past it", "Random values, so the suite covers more each run", "Whatever example values the datasheet happens to give"], a: 1, why: "<p>The middle of the range almost never finds anything, because that is the case the implementation was written against.</p><p>Off-by-one and range-check bugs live at the edges by definition.</p>" },
{ t: "emb-test-first", d: 3, q: "When is it worth moving from a hand-written macro to a framework?", o: ["Immediately, since rolling your own is wasted effort", "When you want per-test isolation, setup and teardown", "Only on large projects, where the overhead pays back", "Never, since a macro can do everything a framework can"], a: 1, why: "<p>Per-test isolation is the main one: without it a crash in one test takes the rest of the run with it. A report format CI can parse is the other.</p><p>Starting without a framework is still right, because it removes the excuse that you cannot test until the tooling is set up.</p>" },

// --------------------------------------------------------- emb-test-fake
{ t: "emb-test-fake", d: 2, q: "Why can a driver that calls the vendor HAL directly not be unit tested?", o: ["The HAL is too slow to run inside a tight test loop", "Nothing can be substituted: it calls the hardware", "The HAL is closed source, so it cannot be recompiled", "It needs an RTOS, which a host test does not give you"], a: 1, why: "<p>And the hardware is not there. The fix is a seam: a struct of function pointers plus a context, so the driver reaches the bus through something a test can replace.</p><p>In Zephyr the device pointer and the <code>i2c_dt_spec</code> already are that seam.</p>" },
{ t: "emb-test-fake", d: 2, q: "Why should a fake record delays rather than actually sleeping?", o: ["The delay function is not portable across hosts", "It keeps the suite instant", "Sleeping in a test upsets the framework's own timing", "It saves power on the machine running the suite"], a: 1, why: "<p>A driver retrying with 50 ms waits would make the suite crawl.</p><p>Recording the total also converts 'does it give up within a second' from a hope into an assertion.</p>" },
{ t: "emb-test-fake", d: 2, q: "What makes a fake more useful than a stub returning zero?", o: ["It is faster, since it avoids the call overhead", "It can be told to fail on a chosen transfer", "It uses less memory than a full stub table would", "It can be generated automatically from the header"], a: 1, why: "<p>Which makes the error paths reachable. On real hardware you cannot make the third transfer fail; in a fake it is one variable.</p><p>Since the error paths are the ones nobody exercises until a customer does, that is where the value is.</p>" },
{ t: "emb-test-fake", d: 2, q: "Which driver tests are worth writing first?", o: ["The happy path, thoroughly, since that is what ships", "The error paths: wrong identity, a failing transfer", "Performance tests, since those catch regressions early", "Tests of the fake, so you can trust everything after"], a: 1, why: "<p>A transfer failing at each point, and a status bit that never clears, belong there too.</p><p>The happy path is exercised by everyone all the time and usually already works. The error paths are the code that runs on the worst day and has never been run at all.</p>" },
{ t: "emb-test-fake", d: 2, q: "Why must a fake reset between tests?", o: ["To free the memory the previous test allocated", "Otherwise one test's state leaks into the next", "So timing measurements start from a known point", "The framework requires a clean object between tests"], a: 1, why: "<p>Then the suite passes or fails depending on order, which is the classic flaky test: it passes alone and fails in the suite, or the reverse.</p><p>Running the suite in a shuffled order in CI is what surfaces it.</p>" },
{ t: "emb-test-fake", d: 3, q: "Why test the register write ORDER, not just the values?", o: ["Order does not matter once the values are all right", "It can work on the bench and fail on other silicon", "Checking order is cheaper than comparing every value", "The datasheet requires the sequence to be documented"], a: 1, why: "<p>Many parts require a specific sequence: unlock, configure, then enable. Right values in the wrong order can happen to work on one revision.</p><p>A spy that records the order turns a datasheet promise into a checked property.</p>" },
{ t: "emb-test-fake", d: 3, q: "What does a passing suite against a fake NOT prove?", o: ["That the logic in the driver is right at all", "Timing, your datasheet reading, or the silicon", "That the error paths behave the way you intended", "That everything it allocated was released again"], a: 1, why: "<p>If the fake and the driver share the same misunderstanding, both are wrong together and every test passes.</p><p>That is exactly why the pyramid keeps a hardware tier at the top.</p>" },
{ t: "emb-test-fake", d: 3, q: "How do you test that an error path does not leak?", o: ["Read the error paths carefully, line by line, twice", "Count allocations in the fake and assert zero", "Run the failing case under a memory profiler", "Use an allocator that reclaims on scope exit"], a: 1, why: "<p>After a failed init the count should be back where it started. Wrapping the allocator in the test build makes leak detection an assertion rather than an inspection.</p><p>It is the error paths that leak, because they are the paths nobody walked.</p>" },

// -------------------------------------------------------- emb-test-ztest
{ t: "emb-test-ztest", d: 2, q: "What does Zephyr's <code>native_sim</code> give you?", o: ["A cycle-accurate simulator of the target processor core", "The application and the kernel, as a native executable", "A remote debug server the probe connects through", "An emulator for the peripherals, but not the kernel"], a: 1, why: "<p>It runs in milliseconds, and threads, semaphores, work queues and timers all behave.</p><p>It is why dual targeting is easier in Zephyr than almost anywhere else, and why an untested Zephyr code base has no excuse.</p>" },
{ t: "emb-test-ztest", d: 2, q: "What does twister do?", o: ["Builds the application for each board in the tree", "Reads every testcase.yaml, builds, runs and reports", "Flashes the board and opens a serial console on it", "Generates a coverage report from an existing run"], a: 1, why: "<p>Each test, for each platform it declares. It reduces the whole CI test job to one command.</p><p>The <code>tags</code> field is what lets you run fast unit tests on every commit and the hardware set overnight.</p>" },
{ t: "emb-test-ztest", d: 2, q: "What is Zephyr's EMUL layer for?", o: ["Emulating the CPU so target code runs on the host", "A fake device behind a devicetree node, on the bus", "Emulating the kernel APIs when Zephyr is not linked", "Modelling timing so latency can be measured on a host"], a: 1, why: "<p>The driver's bus calls reach it instead of silicon, and the driver is completely unmodified: it still calls <code>i2c_burst_read_dt</code> and the emulator answers.</p><p>It is the right mechanism when the thing under test is the driver itself.</p>" },
{ t: "emb-test-ztest", d: 2, q: "What does a passing native_sim suite not prove?", o: ["That the logic under test does what you meant", "Timing, stack usage, the peripheral, or flash fit", "That the kernel APIs were used in a legal order", "That there are no out-of-bounds accesses left anywhere"], a: 1, why: "<p>Interrupt latency belongs on that list too.</p><p>Which is why twister supports device testing, and why the answer is both tiers rather than either. A host pass is a statement about your logic, not about your product.</p>" },
{ t: "emb-test-ztest", d: 2, q: "What are the five NULLs in <code>ZTEST_SUITE(name, ...)</code>?", o: ["Padding, kept so the macro signature stays stable", "The predicate, setup, before, after and teardown", "Five empty test cases the suite will fill in later", "Platform filters, left empty to run everywhere"], a: 1, why: "<p>The predicate decides whether the suite runs at all, which is how a suite is limited to particular platforms.</p><p>Most unit suites need none of the five, which is why they are usually all NULL.</p>" },
{ t: "emb-test-ztest", d: 3, q: "Why pass the optional message to <code>zassert_equal</code>?", o: ["It is required whenever the suite has more than one test", "A bare failure gives you the values but not the intent", "It speeds the test up by skipping the default format", "It is what the runner turns into the process exit code"], a: 1, why: "<p>'expected full scale to equal vref' turns a failure into a diagnosis.</p><p>It is a few seconds while writing and it pays back the first time the test fails in CI rather than at your desk.</p>" },
{ t: "emb-test-ztest", d: 3, q: "Which prj.conf symbol turns on ztest?", o: ["CONFIG_TEST=y", "CONFIG_ZTEST=y", "CONFIG_UNITTEST=y", "CONFIG_ASSERT=y"], a: 1, why: "<p>Along with a <code>testcase.yaml</code> so twister can find the test, and a CMakeLists adding both the test source and the code under test.</p>" },
{ t: "emb-test-ztest", d: 3, q: "Where should a test's devicetree changes live?", o: ["In the product's overlay, so both builds agree", "In a test-only overlay under the test directory", "In the board's .dts, which is where nodes belong", "In prj.conf, alongside the other test settings"], a: 1, why: "<p>So the product's hardware description stays clean. A node that exists only for the test, or one repointed at an emulator, belongs with the test rather than with the product.</p><p>Zephyr picks up <code>boards/&lt;board&gt;.overlay</code> under the test directory automatically.</p>" }

]);
